Cabal/Distribution/Simple/Compiler.hs, Cabal/Distribution/Simple/Configure.hs, Cabal/Distribution/Simple/GHC/ImplInfo.hs, Cabal/Distribution/Simple/GHC/Internal.hs, Cabal/Distribution/Simple/LocalBuildInfo.hs, Cabal/Distribution/Simple/Program/GHC.hs, Cabal/Distribution/Simple/Setup.hs, cabal-install/Distribution/Client/Config.hs
If the compiler (e.g. GHC 7.10) supports outputting OS native debug
info (e.g. DWARF) passing --enable-debug-info[=n] to cabal will
instruct it to do so.
=> Add support for emitting debug info

.travis.yml, Cabal/Cabal.cabal, Cabal/Distribution/Compat/Binary.hs, Cabal/Distribution/Compat/Binary/Class.hs, Cabal/Distribution/Compat/Binary/Generic.hs, Cabal/Distribution/Compiler.hs, Cabal/Distribution/InstalledPackageInfo.hs, Cabal/Distribution/License.hs, Cabal/Distribution/ModuleName.hs, Cabal/Distribution/Package.hs, Cabal/Distribution/PackageDescription.hs, Cabal/Distribution/Simple/Compiler.hs, Cabal/Distribution/Simple/Configure.hs, Cabal/Distribution/Simple/InstallDirs.hs, Cabal/Distribution/Simple/LocalBuildInfo.hs, Cabal/Distribution/Simple/PackageIndex.hs, Cabal/Distribution/Simple/Program/Db.hs, Cabal/Distribution/Simple/Program/Types.hs, Cabal/Distribution/Simple/Setup.hs, Cabal/Distribution/System.hs, Cabal/Distribution/Utils/NubList.hs, Cabal/Distribution/Verbosity.hs, Cabal/Distribution/Version.hs, Cabal/Language/Haskell/Extension.hs, HACKING.md
This is still a work-in-progress.
First I am changing the Travis tests to build Cabal against each GHC version out-of-the-box, i.e., no updating with cabal-install before building the Cabal library. We need to test this way if we are going to support it. Right now, I'm just making this pull request to check that the new tests fail.
=> Fix build with GHC < 7.8 (binary < 0.7)

Cabal/Distribution/Simple/Setup.hs
Fix for #2313, rebased onto 1.22.
=> Retain --enable-executable-profiling and --enable-library-coverage options

Cabal/Distribution/Simple/GHC/ImplInfo.hs
This was warning about CompilerId being a redundant import.
=> Fix compiler warning.

Cabal/Distribution/Simple/Program/Builtin.hs
Fixes #2359.
Since the version checking code for `strip` on many platforms will fail
without consequence, we don't want to warn every time it does.
=> Quiet version checking for `strip`

cabal-install/bootstrap.sh
cabal-install-1.18.0.8/bootstrap.sh requires network-2.6 (502b454)
whereas HTTP-4000.2.11 requires network < 2.6.
So we bump HTTP to 4000.2.16.1 which allows network-2.6.
=> fix bootstrap.sh by bumping HTTP to 4000.2.16.1

Cabal/Distribution/Simple/Configure.hs, Cabal/Distribution/Simple/Setup.hs, cabal-install/Distribution/Client/Config.hs, cabal-install/Distribution/Client/Setup.hs
This re-enables `--enable-library-coverage` and `--enable-executable-profiling`, but using these options will produce a warning about their deprecation. cabal-install will filter the options so `--enable-coverage` and `--enable-profiling` aren't passed to an old Cabal.
=> Compatibility options for profiling and coverage

Cabal/Distribution/Simple/BuildTarget.hs, Cabal/Distribution/Simple/Configure.hs, cabal-install/Distribution/Client/Targets.hs
There are several misspellings of the word "ambiguous" in the source code, including in the API itself (e.g., the `BuildTargetAmbigious` constructor of the `BuildTargetProblem` type). This commit fixes those typos.
=> Fix "ambigious" typos

Cabal/Distribution/Simple/Build.hs, Cabal/Distribution/Simple/GHC.hs, Cabal/Distribution/Simple/GHCJS.hs, Cabal/Distribution/Simple/LHC.hs, Cabal/Distribution/Simple/Program/HcPkg.hs
=> Version test whether or not to use single-file package database, helps #2320 some more

Cabal/Distribution/Simple/GHC.hs
This is useful for clients who use Cabal to call the C compiler, and cannot be defined client side because it requires the `.GHC.Internal` module.
=> Export componentCcGhcOptions

Cabal/Distribution/Simple/Configure.hs, Cabal/Distribution/Simple/Setup.hs, cabal-install/Distribution/Client/Config.hs, cabal-install/Distribution/Client/Setup.hs
Now the released version of cabal-install can be built against
Cabal-1.22.1.0, and there is no need to modify the upper bound on
Hackage. This change prevents Cabal-1.22.1.0 from emitting deprecation
warnings about --enable-executable-profiling, but the correct behavior
of --enable-profiling is preserved. There is no need to rollback the API
changes on master; cabal-install already requires Cabal to have the same
major version.
Tested against cabal-install-1.22.0.0 and cabal-install from the same git branch.
Fixes #2389.
=> rollback API changes about --enable-profiling

Cabal/Distribution/System.hs
See https://github.com/haskell/cabal/issues/2348
Though Android OSs are based on Linux, they have very unique APIs that desktop OSs do not have.
e.g. Bonic C lib, /dev/binder, libandroid.so, lots of Java native APIs, etc.
Plus, Android has own different directory structures, environment variables, application starting scheme and security.
I think it seems better choise to distinguish mobile platforms from desktop OSs.
=> add Android OS

Cabal/Distribution/Compat/Binary.hs
Just running my patch for #2251 through Travis...
=> D.Compat.Binary: catch all ErrorCall in decodeOrFailIO

cabal-install/cabal-install.cabal
Closes: https://github.com/haskell/cabal/issues/2447
=> cabal-install.cabal : Add missing test dependency.

Cabal/Distribution/PackageDescription/Check.hs, Cabal/Distribution/Simple/SrcDist.hs, cabal-install/Distribution/Client/Check.hs
Setup:
```
% cat stats.cabal | grep ghc-options
ghc-options: -Wall -threaded -O2
```
Before:
```
% ../cabal/cabal-install/dist/build/cabal/cabal check
These warnings may cause trouble when distributing the package:
* 'ghc-options: -O2' is rarely needed. Check that it is giving a real benefit
and not just imposing longer compile times on your users.
% echo $?
1
```
After:
```
% ../cabal/cabal-install/dist/build/cabal/cabal check
These warnings may cause trouble when distributing the package:
* 'ghc-options: -O2' is rarely needed. Check that it is giving a real benefit
and not just imposing longer compile times on your users.
% echo $?
0
```
This fixes #1764
=> Treat -O2 in ghc-options as a cabal check "warning"

cabal-install/Distribution/Client/Init.hs
See also: #2418
- Commits in the above pull-request are crushed into two
- Now the filename is ChangeLog.md (not CHANGELOG.md)
=> Auto-generate ChangeLog.md in cabal init

Cabal/Distribution/PackageDescription/Check.hs
This is for fields "extra-source-files", "data-files", "extra-doc-files", "c-sources" and "js-sources"
See https://github.com/haskell/cabal/issues/1531
=> Added checks to see if files and directories exist

cabal-install/Main.hs
This is done so that arguments such as --with-ghc get picked up.
I am not sure if there are any places where reconfiguring will cause problems. It seemed to work fine for me™.
=> Reconfigure when there is no cabal file, fix #1905

Cabal/Distribution/Simple/Haddock.hs
In https://github.com/haskell/cabal/pull/2439 the invocation of Haddock is
changed to use Haddock's new `--package-name` and `--package-version` flags,
necessary for GHC >= 7.10 (Cabal issue
https://github.com/haskell/cabal/issues/2297 / Haddock issue
https://github.com/haskell/haddock/issues/353). However, this commit also
removes the `-package-name` argument to GHC. This is incorrect, as it means
that GHC will end up calling the package `main` and we end up with Haddock link
environments such as
(trans_H9c1w14lEUN3zdWCTsn8jG:Control.Monad.Trans.Error.strMsg, main:Control.Monad.Error.Class)
Note that before this commit we ended up with
(trans_H9c1w14lEUN3zdWCTsn8jG:Control.Monad.Trans.Error.strMsg, mtl-2.1.1:Control.Monad.Error.Class)
which is equally wrong as it uses a package source ID …
=> Make sure to pass the package key to ghc

Cabal/Distribution/Simple/Build.hs
Fixes #2476. Cabal could not build detailed-0.9 test suites with GHC
7.10 because the wrong package key was being used to build the test
suite library.
TODO: We should add real multi-library support to Cabal!
=> Fix test interface detailed-0.9 with GHC 7.10

cabal-install/Distribution/Client/Init.hs, cabal-install/Main.hs
https://github.com/haskell/cabal/issues/2372
=> cabal-install.init: warn if the chosen package name is already registered to the source package index.

Cabal/Distribution/InstalledPackageInfo.hs, Cabal/Distribution/Package.hs, Cabal/Distribution/Simple/GHC/IPI641.hs, Cabal/Distribution/Simple/GHC/IPI642.hs, Cabal/Distribution/Simple/PackageIndex.hs, cabal-install/Distribution/Client/Dependency/TopDown.hs, cabal-install/Distribution/Client/Dependency/TopDown/Constraints.hs, cabal-install/Distribution/Client/Dependency/TopDown/Types.hs, cabal-install/Distribution/Client/Install.hs, cabal-install/Distribution/Client/InstallPlan.hs, cabal-install/Distribution/Client/PackageIndex.hs, cabal-install/Distribution/Client/Types.hs
This pull request is the first of a set of pull requests working towards an implementation of setup dependencies.
This PR moves `installedPackageId` out of `PackageInstalled` into a new superclass `HasInstalledPackageId`, and moves the `PackageFixedDeps` class from `Cabal` to `cabal-install`.
/cc @dcoutts @kosmikus
=> Minor type class cleanup

Cabal/Distribution/InstalledPackageInfo.hs, Cabal/Distribution/Package.hs, Cabal/Distribution/Simple/GHC/IPI641.hs, Cabal/Distribution/Simple/GHC/IPI642.hs, Cabal/Distribution/Simple/PackageIndex.hs, cabal-install/Distribution/Client/BuildReports/Storage.hs, cabal-install/Distribution/Client/Dependency/Modular/ConfiguredConversion.hs, cabal-install/Distribution/Client/Dependency/TopDown.hs, cabal-install/Distribution/Client/Dependency/TopDown/Constraints.hs, cabal-install/Distribution/Client/Dependency/TopDown/Types.hs, cabal-install/Distribution/Client/Freeze.hs, cabal-install/Distribution/Client/Install.hs, cabal-install/Distribution/Client/InstallPlan.hs, cabal-install/Distribution/Client/PackageIndex.hs, cabal-install/Distribution/Client/PlanIndex.hs, cabal-install/Distribution/Client/Types.hs, cabal-install/cabal-install.cabal
This pull request is the second of a set of pull requests working towards an implementation of setup dependencies, and depends on #2487 .
There is a lot of duplication between Cabal and cabal-install, and in fact, a lot of dead code in cabal-install. There is still duplication, but no dead code anymore, and at least the situation is clarified now. Details in the commit messages.
/cc @dcoutts @kosmikus
=> Clean up graph traversal code

Cabal/Cabal.cabal, Cabal/Distribution/Simple/Program/Builtin.hs, Cabal/Distribution/Simple/Program/Internal.hs, Cabal/tests/UnitTests.hs, Cabal/tests/UnitTests/Distribution/Simple/Program/Internal.hs
=> Handle more 'strip --version' output formats.

cabal-install/Distribution/Client/IndexUtils.hs, cabal-install/Distribution/Client/Update.hs
=> Update multiple remote-repos in parallel

cabal-install/Distribution/Client/Run.hs
see #2507
just additional warnings; did not implement anything in the direction of `run`ning test-suites or benchmarks (even thought that might be nice).
=> Additional warnings for 'cabal run'

Cabal/Distribution/Simple/PreProcess.hs
I've recently stumbled upon an issue that didn't let me to build my Haskell project on Windows. It manifested itself as an error:
`cabal: w:\haskell\bin\hsc2hs.exe: does not exist`
The file that seemed to be missing (hsc2hs.exe binary) was actually present in necessary directory, so I started investigating the issue.
It turned out that the core reason was that hsc2hs command line exceeded the maximum allowed length of 32767 characters. The reason why it exceeded the limit was the huge amount of duplicate `--cflag` arguments that appeared from the dependent packages. As a quick fix I just added a `nub` function call to eliminate duplicate arguments and the problem is fixed at least for my project.
While this fix doesn't completely eliminate the problem (at some point there eventually will …
=> Eliminate duplicate hsc2hs command line arguments

cabal-install/Distribution/Client/PlanIndex.hs
This appears to cause CI jobs on GHC head to fail; I guess GHC is now
issuing warnings for redundant constraints.
See https://travis-ci.org/haskell/cabal/jobs/57191163 for example.
=> Fix a redundant constraint

Cabal/Distribution/PackageDescription/Check.hs
This is consistent with the the current -auto-all behavior.
This fixes #2479.
Setup:
```
% grep -- '-fprof-auto' stats.cabal
ghc-prof-options: -Wall -fprof-auto -caf-all -threaded "-with-rtsopts=-p"
```
Before:
```
% ../cabal/cabal-install/.cabal-sandbox/bin/cabal check
No errors or warnings could be found in the package.
```
After:
```
% ../cabal/cabal-install/.cabal-sandbox/bin/cabal check
These warnings may cause trouble when distributing the package:
* 'ghc-prof-options: -fprof-auto' is fine during development, but not
recommended in a distributed package.
```
=> cabal check will fail on -fprof-auto passed as a ghc-option

cabal-install/bash-completion/cabal
The regex used to parse sandbox help message was outdated and relied on the unportable sed -r option which doesn't work on BSDs. I've changed the regex to parse the current format of the help message and use portable basic regex sed syntax.
=> Fixed bash completion for sandbox subcommands

cabal-install/Distribution/Client/Dependency/Modular/Log.hs
This is my naive fix for ticket #2535
=> Slightly better error message in case of backjump limit reached

cabal-install/bootstrap.sh
This fixes cases where strings like "ld" appear in compiler output on lines that have nothing to do with the linker command invocation.
=> bootstrap.sh: fixes linker matching to avoid cases where tested linker names appear unexpectedly in compiler output (fixes #2542)

cabal-install/bootstrap.sh
I was the one who introduced that bit, and it seems like well may have caused more trouble than it helped... so, sorry. :cry: 
Anyway, clang has since then grown the ability to `-print-prog-name`, so I've done away with all that "grepping through ""gcc -###" stuff that caused #1710, #2542, etc.
@creswick @23skidoo, could you try this out, see if it works for you?
=> Rewrite linker check to avoid grepping "ld"s.

cabal-install/Distribution/Client/Init.hs
`cabal init` will create Main.hs if the following conditions hold:
- creating an executable (not a library)
- the mainIs flag has been specified
- the file the mainIs flag is pointing to doesn't exist
This implements issue #2304.
Now, after doing `cabal init`, you can immediately do `cabal install`, `cabal run`, etc.
=> Make `cabal init` create Main.hs if it doesn't exist.

cabal-install/Distribution/Client/Setup.hs, cabal-install/Main.hs
As suggested by @sclv on reddit. See
https://github.com/haskell/cabal/issues/648#issuecomment-96895441
=> Implement a dummy 'uninstall' command.

cabal-install/Distribution/Client/HttpUtils.hs, cabal-install/Distribution/Client/Upload.hs
Turns out it had been using basic auth, when it should have been using digest auth.
=> Force cabal upload to always use digest auth and never basic auth

Cabal/Distribution/PackageDescription/Check.hs
Refs haskell/hackage-server#253.
=> Use PVP-compliant example when warning about missing base upper bound

cabal-install/cabal-install.cabal
```
Distribution/Client/Tar.hs:679:10:
No instance for (Applicative Partial)
arising from the superclasses of an instance declaration
In the instance declaration for ‘Monad Partial’
xcabal: Error: some packages failed to install:
cabal-install-1.18.1.0 failed during the building phase. The exception was:
ExitFailure 1
```
=> cabal-install-1.18 doesn't build on GHC 7.10

Cabal/Distribution/PackageDescription/Check.hs
In particular, allow flags that are appropriate during development if they're guarded by a manual flag.
Various other improvements, see the patch descriptions and diffs for details.
=> Improve a number of ghc-options checks

cabal-install/Distribution/Client/Config.hs, cabal-install/Distribution/Client/Install.hs, cabal-install/Distribution/Client/Setup.hs, cabal-install/changelog
When in offline mode, 'cabal install' only installs packages from the local
tarball cache. Offline mode can be enabled with the '--offline' flag.
Fixes #2566.
=> Implement offline mode for the 'install' command.

Cabal/Distribution/Simple/PreProcess.hs, Cabal/changelog
This commit includes cabal_macros in c2hs call, so it will
be possible to use MIN_VERSION macros in chs files.
=> Provide cabal_macros in c2hs invocation.

cabal-install/Distribution/Client/Dependency.hs, cabal-install/Distribution/Client/Dependency/Modular/Builder.hs, cabal-install/Distribution/Client/Dependency/Modular/ConfiguredConversion.hs, cabal-install/Distribution/Client/Dependency/Modular/Explore.hs, cabal-install/Distribution/Client/Dependency/Modular/Index.hs, cabal-install/Distribution/Client/Dependency/Modular/IndexConversion.hs, cabal-install/Distribution/Client/Dependency/Modular/Linking.hs, cabal-install/Distribution/Client/Dependency/Modular/Message.hs, cabal-install/Distribution/Client/Dependency/Modular/PSQ.hs, cabal-install/Distribution/Client/Dependency/Modular/Package.hs, cabal-install/Distribution/Client/Dependency/Modular/Preference.hs, cabal-install/Distribution/Client/Dependency/Modular/Solver.hs, cabal-install/Distribution/Client/Dependency/Modular/Tree.hs, cabal-install/Distribution/Client/Dependency/Modular/Validate.hs, cabal-install/Distribution/Client/InstallPlan.hs, cabal-install/Distribution/Client/PlanIndex.hs, cabal-install/cabal-install.cabal, cabal-install/tests/UnitTests.hs, cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/Solver.hs
This is the next PR in the quest for setup dependencies, and implements independent goals and linking, as described in detail in the blog post
[Qualified Goals in the Cabal Solver](http://www.well-typed.com/blog/2015/03/qualified-goals/)
This does not change any user observable behaviour -- in particular, we do not make independent goals available to the user as a command line argument (though we could); but having the infrastructure there will be essential for treating setup dependencies as independent, as well as a number of other features that can be built on top of this. One of those features will be base-3-shim support, so that we can change away from using the top-down solver as a default under certain circumstances. That however will be the topic of a later PR.
=> Implement independent goals

cabal-install/Distribution/Client/Dependency.hs, cabal-install/Distribution/Client/Dependency/Modular/Builder.hs, cabal-install/Distribution/Client/Dependency/Modular/ConfiguredConversion.hs, cabal-install/Distribution/Client/Dependency/Modular/Explore.hs, cabal-install/Distribution/Client/Dependency/Modular/Index.hs, cabal-install/Distribution/Client/Dependency/Modular/IndexConversion.hs, cabal-install/Distribution/Client/Dependency/Modular/Linking.hs, cabal-install/Distribution/Client/Dependency/Modular/Message.hs, cabal-install/Distribution/Client/Dependency/Modular/PSQ.hs, cabal-install/Distribution/Client/Dependency/Modular/Package.hs, cabal-install/Distribution/Client/Dependency/Modular/Preference.hs, cabal-install/Distribution/Client/Dependency/Modular/Solver.hs, cabal-install/Distribution/Client/Dependency/Modular/Tree.hs, cabal-install/Distribution/Client/Dependency/Modular/Validate.hs, cabal-install/Distribution/Client/InstallPlan.hs, cabal-install/Distribution/Client/PlanIndex.hs, cabal-install/cabal-install.cabal, cabal-install/tests/UnitTests.hs, cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/Solver.hs
In the definition of `dependencyGraph` we constructed the graph manually, rather than using the standard library funciton `graphFromEdges`. I don't know why we did this, perhaps it predates that function; but it makes the function a bit hard to modify. In particular, once we start introducing fine-grained dependencies (next PR), we will want an edge-labeled graph and having manual graph construction here makes that awkward to do.
This commit lives in a branch forked from #2500, so it looks like a big PR, but actually it's just one commit https://github.com/haskell/cabal/commit/ac47cbc44d20c033b1cc6d0e5b9eede3f204f450 on top of that branch, which is really quite independent of the changes in that branch; this commit can be reviewed completely in isolation. Submitting as a separate PR so …
=> Use standard graph construction in PlanIndex

Cabal/Distribution/Simple/GHC.hs, Cabal/changelog
A small patch to make sure we don't recompile C code from `c-sources:` unless needed.
This has been pretty life-saving when working on projects with tons of c-sources — I've been using it for a few months on my main Cabal without issue.
=> Don't recompile C files unless needed

cabal-install/Main.hs
\a is considered as a bell character, which is omitted as a result. The error message is `The 'sandbox delete-source' command expects t least one argument`
=> Fix sandbox delete-source error message typo

Cabal/Distribution/PackageDescription.hs, Cabal/Distribution/PackageDescription/PrettyPrint.hs
As we don't know whether some field was specified explicitly in the cabal file, we can omit `if` branches as we omit fields.
```
name:                test
cabal-version:       -any
license:             UnspecifiedLicense
Flag myflag
Default:           False
library
if flag(myflag)
Buildable:       True
else
Buildable:       False
```
&rarr;
```
name: test
cabal-version: -any
license: UnspecifiedLicense
flag myflag
default: False
library
if !flag(myflag)
buildable: False
```
---
```
name: test
cabal-version: -any
license: UnspecifiedLicense
flag myflag
default: False
library
if flag(myflag)
extra-libraries:
else
extra-libraries: mylib
```
&rarr;
```
name: test
cabal-version: -any
license: UnspecifiedLicense
flag myflag
default: False
library
if !flag(myflag)
extra-libraries:
mylib
```
--- …
=> Fix #2598. Omit empty CondTree branches

Cabal/Distribution/Simple/GHC.hs
not static ones. They make no sense there, increase startup time and
may violate some distributions policy on rpaths. This closes #2625.
=> Only set rpath on dynamic executables

cabal-install/Distribution/Client/Setup.hs, cabal-install/Distribution/Client/SetupWrapper.hs, cabal-install/Main.hs
This fixes issues when the version of Cabal that cabal-install was built
against differs from the one registered in the local package DB. Normally
we compile an external setup against the local Cabal library, which could
lead to failures or inconsistent results compared to using the internal
method.
=> Allow using cabal program itself as the external setup method

Cabal/Distribution/Text.hs
No change to the syntax, old tags syntax allowed but simply ignored.
Version tags have been deprecated for years and are disappearing from
the Version type in base soon.
=> Ignore tags when parsing version numbers

Cabal/Distribution/Simple/Setup.hs
mappend of HaddockFlags uses the wrong function. Simple one line fix.
=> Distribution.Simple.Setup: fix HaddockFlags mappend

Cabal/Distribution/PackageDescription/Check.hs
Because `cabal sdist` will add a default `Setup.hs` anyway. See #1125 and #2629.
=> Only warn for missing Setup.hs if build type isn't Simple

Cabal/Cabal.cabal, Cabal/Distribution/Lex.hs, Cabal/Distribution/Simple/GHC/Internal.hs
GHC hands us a `String` which we previously tried to parse as a `[String]`, causing GHC's compiler flags to be ignored.
It seems this is the result of an inconsistency between encodings of the settings exposed by `ghc --info`. In some cases (e.g. `Gcc Linker flags`) the flags are encoded as a `[String]` with `show` whereas in other cases (e.g. `C compiler flags`) the flags are just a `String`. We work around this by first attempting to parse a list, then falling back on tokenizing the string if this fails.
This fixes #2292.
=> Parse C compiler flags from GHC correctly

cabal-install/Main.hs
Fixes #2275.
I just copied and tweaked the code from `buildAction`, which had this same issue fixed (`cabal build` used to also say `Run the 'configure' command first.`)
=> Automatically run `configure` before `haddock`

cabal-install/Distribution/Client/Sandbox.hs
Without this change, differences in filename capitalization caused `cabal sandbox delete` to fail with this error message when used with a default sandbox on Windows:
cabal.exe: Non-default sandbox location used:
'C:\folder\.cabal-sandbox'.
Assuming a shared sandbox. Please delete
'C:\folder\.cabal-sandbox' manually.
This commit also allows the cabal-install package tests that delete sandboxes to run on Windows.
=> Compare file paths with equalFilePath for portability

cabal-install/tests/PackageTests/Exec/Check.hs
This change allows the tests "can run executables installed in the sandbox" and
"adds the sandbox bin directory to the PATH" to run on Windows by removing the
executable name from the required error message.
=> Test cabal exec error message in a more portable way

cabal-install/tests/PackageTests/Freeze/Check.hs
The tests now read cabal.config strictly so that the file is closed by the time
it is deleted for the next test.
=> Allow cabal freeze tests to run on Windows

.gitignore, stack.yaml
I needed this when building cabal.exe for MinGHC (see:
https://github.com/fpco/minghc/issues/69). I thought others might find
this useful, especially for the use case of bootstrapping cabal
development.
I went the direction of no curation and explicit packages in the
extra-deps, as I thought that would make more sense for a project low on
the dependency chain, but this could certainly be tweaked to use LTS
Haskell or Stackage Nightly instead.
=> Add a stack.yaml file

HACKING.md
The command line given to get the sandbox package database path is missing quotation which may make it fail in some shells (given certain globbing options). This adds single quotation marks to avoid such potential issues.
=> HACKING.md: Add quotation to sed command

cabal-install/Distribution/Client/Config.hs, cabal-install/Distribution/Client/Setup.hs, cabal-install/Distribution/Client/Types.hs
Joint work with several people on zurihac.
Almost self-contained, and should be backwards-compatible.  The purpose of the change is that we want to add more fields to the remote-repo sections for hackage-security data types.
Hopefully there will be more progress tomorrow.
=> Support new section syntax for remote-repo.

stack.yaml
So that contributors can run `stack test` if they so desire.
=> Add test dependencies to stack.yaml

cabal-install/Distribution/Client/GZipUtils.hs, cabal-install/tests/UnitTests/Distribution/Client/GZipUtils.hs
Related to @23Skidoo question in https://github.com/haskell/cabal/pull/2706
=> maybeDecompress: bail on all errors at the beginning of the stream with zlib < 0.6

Cabal/Distribution/PackageDescription/Check.hs, Cabal/Distribution/Simple/Build.hs, Cabal/Distribution/Simple/Install.hs
This commit relaxes `D.PackageDescription.Check.checkConfiguredPackage` so that it
only warns when a package declares no executables, libraries, tests, or
benchmarks.  Similarly, it relaxes the check during build to only require one
component that is buildable and enabled.  Install now requires an executable or
library.
Note that `cabal install` downloads test packages before failing to install them.  I figured that checking for libraries and executables earlier wasn't worth the added complexity.
/cc @ttuegel
=> Support pure test packages (issue #1186)

Cabal/Distribution/Simple/Compiler.hs, Cabal/Distribution/Simple/Configure.hs, Cabal/Distribution/Simple/GHC.hs, Cabal/Distribution/Simple/GHC/ImplInfo.hs, Cabal/Distribution/Simple/GHC/Internal.hs, Cabal/Distribution/Simple/LocalBuildInfo.hs, Cabal/Distribution/Simple/Program/GHC.hs, Cabal/Distribution/Simple/Setup.hs, Cabal/changelog, Cabal/doc/developing-packages.markdown, Cabal/doc/installing-packages.markdown, cabal-install/Distribution/Client/Config.hs, cabal-install/Distribution/Client/Setup.hs
This is based on top of @ttuegel's patch set "Enable reasonable default profiling options" #2555
=> Add support for automatic profiling detail levels, with reasonable defaults

cabal-install/Distribution/Client/Sandbox.hs
--
I think this fixes #2224. I haven't done extensive manual testing, but the tests all (obviously) still pass.
Example output:
cabal: Cabal sandbox file in $CABAL_SANDBOX_CONFIG does not exist: foo
the "foo" is the content of the env variable.
I should note that the error occurs quite "aggressively", i.e. when the settings are read, and not when they are actually used -- so even things like "cabal info" will fail if the env variable is invalid. I think a more relaxed would be a lot more error-prone since it would be easy to miss cases.
=> Exit with an error if $CABAL_SANDBOX_CONFIG does not point to extant file

Cabal/Distribution/Simple/GHC/Internal.hs, Cabal/Distribution/Simple/PreProcess.hs, Cabal/changelog
=> Ensure that OS X framework headers are in include path

Cabal/Distribution/Simple/Haddock.hs
This change is for adding the ehancement to support haddock
response files.  This is what was used to build HP 7.10.2
for Windows, but it does need a corresponding change in
haddock to utilize it. Hopefully, this and its corresponding
haddock change can make it into the next ghc release and
eliminate much gnashing of teeth, error prone, and time
consuming manual steps in the HP build process.
Modified:
* Cabal/Distribution/Simple/Haddock.hs
* renderArgs function: I put a couple of things into locals
since I needed another use for UTF8 support check, plus I
added another check based on version; the temp file logic
was just as the prologue case above but I did need to
repeat the invocation of the 'k' function in order to
keep the cases separate and allow proper handling of the
temp file …
=> Support haddock response files

cabal-install/Distribution/Client/Config.hs, cabal-install/Distribution/Client/Configure.hs, cabal-install/Distribution/Client/Dependency.hs, cabal-install/Distribution/Client/Dependency/Modular.hs, cabal-install/Distribution/Client/Dependency/Modular/Message.hs, cabal-install/Distribution/Client/Dependency/Modular/Preference.hs, cabal-install/Distribution/Client/Dependency/Modular/Solver.hs, cabal-install/Distribution/Client/Dependency/Modular/Tree.hs, cabal-install/Distribution/Client/Dependency/TopDown.hs, cabal-install/Distribution/Client/Dependency/Types.hs, cabal-install/Distribution/Client/Freeze.hs, cabal-install/Distribution/Client/Install.hs, cabal-install/Distribution/Client/Sandbox/PackageEnvironment.hs, cabal-install/Distribution/Client/Setup.hs, cabal-install/Distribution/Client/Targets.hs, cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/DSL.hs
This commit adds the sources of constraints to debugging and error messages,
e.g., "main config file" or "command line flag".
=> Improve error message for unsatisfiable package constraints (issue #2643)

Cabal/Distribution/Simple/GHC.hs
This fixes the Cabal side of [GHC trac #10568](https://ghc.haskell.org/trac/ghc/ticket/10568)
=> Add frameworks when linking a dynamic library

cabal-install/Distribution/Client/InstallSymlink.hs
This one is trivial. Commit 8ea6f33c34e10dcc9faa046040266e91676e8062 has broken Windows build, this looks to me like a fix. The problem is that ```InstallSymlink.hs``` file is conditionally compiled and Windows part wasn't updated.
=> Fix windows build

Cabal/Distribution/Simple/GHC.hs
GHC doesn't support HPC in interpreter, see
https://downloads.haskell.org/~ghc/7.10.2/docs/html/users_guide/hpc.html#idp22264416
Fixes #2757
=> Disable HPC in REPL for GHC

Cabal/doc/developing-packages.markdown
After #2699, the documentation no longer needs to explain that the example .cabal files with only tests or benchmarks are invalid.
=> Update documentation for test-only packages

Cabal/Distribution/Simple/GHC.hs
=> Only include dynlink opts when building a dynamic executable

Cabal/Distribution/InstalledPackageInfo.hs, Cabal/Distribution/Simple/Build.hs, Cabal/Distribution/Simple/GHC.hs, Cabal/Distribution/Simple/GHC/Internal.hs, Cabal/Distribution/Simple/GHCJS.hs, Cabal/Distribution/Simple/Haddock.hs, Cabal/Distribution/Simple/LHC.hs, Cabal/Distribution/Simple/PreProcess.hs, Cabal/Distribution/Simple/Program/HcPkg.hs, Cabal/Distribution/Simple/Register.hs, cabal-install/Distribution/Client/Haddock.hs, cabal-install/Distribution/Client/Types.hs
This parameter was a legacy when GHC depended directly on
Cabal; this is no longer the case so there is no need for
this parameter (which is unused inside Cabal.)
=> Eliminate InstalledPackageInfo module name parameter.

Cabal/Distribution/Simple/Configure.hs, Cabal/Distribution/Simple/GHC.hs
I'm not sure whether cabal-install should really check that we have recent enough GHC.
I tried this shortly with [composition](http://hackage.haskell.org/package/composition-1.0.1.1/docs/Data-Composition.html) package, `cabal repl` session:
```
λ *Data.Composition > let x f g = f .: g
λ *Data.Composition > :t x
x :: (c -> d) -> (a -> b -> c) -> a -> b -> d
λ *Data.Composition > :t String
<interactive>:1:1: Not in scope: data constructor ‘String’
```
=> Resolve #2593: Lift global database restrictions

Cabal/Distribution/Simple/Utils.hs
(Ideally this would check the version of base instead, but that's not really
possible with bootstrapping Cabal; checking the version of ghc instead is what
happens in lots of other places so sticking with that for now.)
=> For ghc >= 7.10 use displayException in topHandler

cabal-install/Distribution/Client/Sandbox.hs, cabal-install/Distribution/Client/Sandbox/PackageEnvironment.hs
Only the NoComments case of IncludeComments was ever used and we can
simplify the generation of the default "package environment file"
accordingly.
--
This is simplifies some of the work I'm doing around searching for sandboxes (so it's a prerequisite for that), but should be fine for merge as-is since it just eliminates dead code.
=> Remove dead code

Cabal/Distribution/Simple/GHC.hs, Cabal/Distribution/Simple/GHCJS.hs, Cabal/Distribution/Simple/Program/Ar.hs, Cabal/tests/PackageTests/DeterministicAr/Check.hs
Two changes:
* strip static libraries (.a files) at install/copy time, instead of
at build time. Note that Cabal strips shared libraries (.so files)
and executables at install/copy time also.
This is needed for GHC, because it uses Cabal (via ghc-cabal copy)
to install the boot libraries, and relies on Cabal to take of
library stripping. Currently .so files indeed get properly stripped,
but .a files do not.
(Stripping static libraries at build time was introduced in
60409cb9493de99f6549956e09604596e3f28938, with the explanation:
"Call 'stripLib' from createLibArchive so that it's done only
once.")
This bug (if you want to call it that) partially explains the
difference in size of a GHC installation before and after manual
stripping, reported in (edit: …
=> Don't strip libraries in build directory

cabal-install/Distribution/Client/Configure.hs, cabal-install/Distribution/Client/Install.hs, cabal-install/Distribution/Client/Targets.hs
`cabal install` and `cabal configure` warn when any constraint or preference names a package that is not in the source package index or installed package index.
I tried to keep it simple and unobtrusive by only printing the first bad constraint or preference.  Would it be better to summarize all of them?
=> Warn when constraints or preferences refer to unknown packages (fixes #2719)

cabal-install/Main.hs
If I try to use a local cabal-install repo cache by adding a
"remote-repo-cache: <dir>" setting to the local cabal.config, this is
respected by "cabal update" but then ignored by "cabal get", which seems
wrong.  This respects the local cabal.config in "cabal get" too.  Maybe
all commands should do this?
=> Use the sandbox config for "cabal get"

Cabal/Distribution/Compat/Binary.hs, Cabal/Distribution/Simple/Configure.hs
This is a prerequisite for GHC Phabricator [D861](https://phabricator.haskell.org/D861).
=> use a liberal import of Control.Exception to grab the new ErrorCall pattern in base

cabal-install/Distribution/Client/Config.hs
@dcoutts introduced `addInfoForKnownRepos` in 8617d39d3c0be275e4373c1c6d5ddc7368083960, but while we called `addInfoForKnownRepos` when _parsing_ a file, we didn't call it when creating the initial file. This meant that when we created an initial file, we would end up with a different internal configuration (which would not have `addInfoForKnownRepos` applied) than if we wrote out and then read back that same initial file (which would).
=> Call addInfoForKnownRepos in initialSavedConfig

cabal-install/Distribution/Client/Sandbox.hs
This undoes the PR for #2680. I'll comment on that ticket for more details. 
This reverts commit 3488f593dc4f416cf5a281988c972ce2ff406d92.
=> Revert "Exit with an error if $CABAL_SANDBOX_CONFIG does not point to extant file"

cabal-install/Distribution/Client/IndexUtils.hs
Fixes #2396
As stated in one of the commit messages:
The parsePackageIndex wasn't streaming because resulting list was
hidden in two constructors: Either and tuple. By removing that, error
semantics changed in updatePackageIndexCacheFile.
The updatePackageIndexCacheFile problem was sequence call that evaluated
whole list produced by parsePackageIndex. By using lazySequence, any error
during index file parsing will be raised during writing to cache file.
Also removed readPackageIndexFile, as it wasn't used anywhere as far as
I can tell. If this is a mistake I'll include it again.
=> Lower memory usage during index file parsing #2396

Cabal/Distribution/Version.hs
This is useful for performing PVP bounds checking, especially for
tooling that wants to automate such dependency bounds. A demonstration
of this being used in practice is the --pvp-bounds flag for stack:
https://github.com/commercialhaskell/stack/commit/c774f9905b3b112f58fc3789dfb9c26389d33b24
=> Add hasUpperBound and hasLowerBound

Cabal/Language/Haskell/Extension.hs
The `DeriveLift` extension is to be added to GHC as part of [Phab D1168](https://phabricator.haskell.org/D1168), but one of the GHC test suites needs to have `DeriveLIft` as a `Cabal`-recognized extension for it to pass.
=> Add DeriveLift to Language.Haskell.Extension

Cabal/Distribution/Simple.hs
Before this patch, configure scripts were always run just using whatever "sh" was lying around instead of using the searchpath setup -- hence e.g. on windows even with the searchpath set to point to a msys sh, the cygwin would get chosen, causing a mess. Also, the configure scripts weren't being _run_ with an augmented path, so they wouldn't manage to necessarily find the proper compiler toolchain for testing with autoconf. That is also corrected with this patch.
Also note that by putting the proper msys path in place, this means we get the proper uname for msys, which means that even in a generally cygwin system, a "config.guess" script should now properly detect msys for the build process.
I've verified that on a raw windows shell, without msys in my path, but with the proper pointers …
=> Use extra-prog-path in running build-type configure

cabal-install/Distribution/Client/Config.hs, cabal-install/Distribution/Client/Upload.hs
This addresses the issue #1839.
As noted in the commit message, it also fixes a small bug in the upload URI generation when
the repo URI does not end with a slash.
=> Always use new hackage URI

cabal-install/Distribution/Client/Config.hs, cabal-install/tests/UnitTests/Distribution/Client/UserConfig.hs
I combined these two commits into one pull request because the second depends on the first:
**Allow user-config to work with a non-default config file (issue #2679)**
user-config commands now read and update the config file that is specified by
--config-file or CABAL_CONFIG.
**Prevent user-config tests from overwriting config file on Windows (fixes #2678)**
The user-config unit tests now use the --config-file flag to specify a test
config file.
=> Allow user-config to work with a non-default config file

cabal-install/Distribution/Client/Exec.hs, cabal-install/Distribution/Client/Sandbox.hs, cabal-install/Main.hs
For most commands (e.g. `cabal install`), the `package-db` field in `cabal.sandbox.config` is ignored, and the path is reconstructed from the `prefix` and current compiler instead.  This is arguably the right behaviour, because the right package DB depends on the arch/compiler, so it doesn't make sense to specify only one.  This commit makes `cabal sandbox hc-pkg` behave similarly, to avoid invoking ghc-pkg on an incompatible package DB (fixes #1935).
Moreover, the compiler version to use is now picked up from the most recently configured compiler, if any.  Otherwise, the global default compiler is used, as before.
I think the `package-db` field should probably be removed from `cabal.sandbox.config` completely, but I haven't yet investigated this.
@luite hopefully this will make `cabal …
=> Use configured compiler for cabal sandbox hc-pkg

cabal-install/Distribution/Client/Dependency/Modular/Message.hs
This commit prevents cabal from filtering out messages about missing
packages when summarizing the solver trace.
In this example, it adds the line `fail (unknown package: either)`.
$ ../dist/build/cabal/cabal install 
Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
update' to download it.
cabal: Could not resolve dependencies:
trying: stack-0.1.4.1 (user goal)
next goal: either (dependency of stack-0.1.4.1)
fail (unknown package: either)
Dependency tree exhaustively searched.
This commit partially fixes issues #2179 and #2816 but doesn't remind the user to run `cabal update`.  If we mention `update`, I think it should be a separate message, because this line can appear many times in the full trace.
=> Always warn when 'cabal install' cannot find a dependency

Cabal/Distribution/Simple/Haddock.hs, Cabal/Distribution/Simple/Setup.hs, cabal-install/Distribution/Client/Config.hs
This is the first step to implement #2080. It adds a new flag
to `cabal haddock`, called `--for-hackage`, which will generate
documentation suitable for upload to hackage. It's only a collection
of flags, and matches the flags used by the hackage doc builder.
=> cabal haddock: add --for-hackage flag

Cabal/Distribution/Package.hs
=> Backwards compatibility type synonym for InstalledPackageId.

Cabal/Language/Haskell/Extension.hs
Includes `StaticPointers`, `DuplicateRecordFields`, `StrictData` and `ApplicativeDo`.
=> Add some missing extensions to Language.Haskell.Extension

.travis.yml, cabal-install/Setup.hs, cabal-install/tests/IntegrationTests/freeze/should_run/enable_benchmarks_freezes_bench_deps.sh
Without sandbox, there are less moving parts, and tests seem to be more robust.
=> Use global db in travis

cabal-install/Distribution/Client/Freeze.hs, cabal-install/Distribution/Client/InstallPlan.hs, cabal-install/Distribution/Client/PlanIndex.hs
Main thing is that the Graph inside the InstallPlan now includes setup dep edges, which means things based on that now take setup deps into account. Also audited other uses of nonSetupDeps vs flatDeps in InstallPlan and the PlanIndex code.
=> Simplify a few InstallPlan utils, and use setup deps in a few places

Cabal/Distribution/Simple/Utils.hs, cabal-install/Distribution/Client/Init.hs, cabal-install/Distribution/Client/Sandbox.hs, cabal-install/Main.hs
regarding the changes of wording:
1. a "no-op" would not call `cont` in the Nothing case.
2. I think saying
> cabal-install version 1.22.6.0
> __compiled__ using version 1.22.4.0 of the Cabal library 
is better in order to avoid the whole "what, why is ghc-pkg saying something different" confusion.
=> Refactoring and two Doc/Wording changes

Cabal/Distribution/Simple/Command.hs, cabal-install/Distribution/Client/Manpage.hs, cabal-install/Distribution/Client/Setup.hs, cabal-install/Main.hs, cabal-install/Setup.hs, cabal-install/cabal-install.cabal, cabal-install/tests/IntegrationTests/manpage/common.sh, cabal-install/tests/IntegrationTests/manpage/should_run/outputs_manpage.sh
Manual page generation from command list defined in `Main`. Based on the approach and implementation in darcs.
Fixes #848.
=> Manual page generation

Cabal/Cabal.cabal, Cabal/Distribution/Compat/Binary/Class.hs, Cabal/Distribution/Compat/ReadP.hs, Cabal/Distribution/Lex.hs, Cabal/Distribution/PackageDescription.hs, Cabal/Distribution/PackageDescription/Configuration.hs, Cabal/Distribution/PackageDescription/Parse.hs, Cabal/Distribution/PackageDescription/PrettyPrint.hs, Cabal/Distribution/ParseUtils.hs, Cabal/Distribution/Simple/BuildTarget.hs, Cabal/Distribution/Simple/CCompiler.hs, Cabal/Distribution/Simple/Command.hs, Cabal/Distribution/Simple/GHC.hs, Cabal/Distribution/Simple/GHC/Internal.hs, Cabal/Distribution/Simple/GHCJS.hs, Cabal/Distribution/Simple/HaskellSuite.hs, Cabal/Distribution/Simple/LHC.hs, Cabal/Distribution/Simple/PackageIndex.hs, Cabal/Distribution/Simple/Program/Db.hs, Cabal/Distribution/Simple/Program/GHC.hs, Cabal/Distribution/Simple/Setup.hs, Cabal/Distribution/Utils/NubList.hs
This refactoring allows to drop `{-# LANGUAGE CPP #-}` from a couple of
modules again. While at it, this also canonicalises the `Applicative`/`Monad` instances, 
thereby future proofing those.
=> CPP-reducing refactoring

cabal-install/Distribution/Client/Dependency/Modular/Package.hs, cabal-install/Distribution/Client/Dependency/Modular/Preference.hs
When we have a target like "foo-1.0", in terms of solver input this
gets turned into a target package name of "foo" and a (labelled)
constraint of "foo == 1.0". This constraint is of course to ensure
that we pick the right target. However, with the recent addition of
qualified package goals we have the possibility of picking multiple
versions of the same package (e.g. via setup deps). If we have a
constraint like "foo == 1.0" apply everywhere then it becomes
impossible to pick multiple versions of package "foo", which may
mean we cannot find a solution at all. But the constraint for the
target need not apply everywhere, it's just to ensure that for the
"main" instance, we pick the right version.
This patch makes that precise. We have these constraints arising
from targets apply only to …
=> Solver: limit where package target constraints apply

Cabal/Distribution/Simple/Haddock.hs, cabal-install/Distribution/Client/Config.hs, cabal-install/Distribution/Client/HttpUtils.hs, cabal-install/Distribution/Client/Setup.hs, cabal-install/Distribution/Client/Upload.hs, cabal-install/Main.hs, cabal-install/changelog
This is the second part that was still remaining for the implementation of #2080. I still need to test this on powershell though, I'll report back when I've done that.
=> Implement `cabal upload --doc`

cabal-install/Main.hs
This is better than ignoring them because one is likely in some state of
confusion when passing extraneous arguments to `cabal init` and would
probably appreciate being taken out of that state sooner rather than
later.
=> Make `cabal init` reject extra arguments.

Cabal/doc/installing-packages.markdown, cabal-install/Distribution/Client/Config.hs, cabal-install/Distribution/Client/Dependency/Types.hs, cabal-install/Distribution/Client/Freeze.hs, cabal-install/Distribution/Client/Sandbox.hs, cabal-install/Distribution/Client/Sandbox/PackageEnvironment.hs, cabal-install/Distribution/Client/Setup.hs
This lets you either pass `constraints-file` on the command line or in
the ~/.cabal/config file.
The constraints-file serves as a "default" cabal.config file for
freezes should one not be provided by a particular package.
Thus, a "minimal" platform can ship with a file that includes the
platform constraints. Later, a user can simply download a new file for
a new constraints set -- say lts -- and swap their config to point to
that instead.
This makes both the platform in its new ideally-more-minimal guise and
stackage play nicer together and with cabal, in a way that required
minimal changes to cabal proper.
Ideally this or a relative can land soon to help enable the minimal
platform plans (the work grew out of the discussion on:
https://github.com/haskell/haskell-platform/issues/206)
In …
=> Global Constraints Option

Cabal/Distribution/Simple/Program/Ar.hs
AIX uses its own `ar` format variant (with a different header),
which causes Cabal to abort with
Distribution.Simple.Program.Ar.wipeMetadata: Bad global header
This patch simply disables this non-essential operation for AIX.
=> Disable Ar.wipeMetadata for AIX

Cabal/Distribution/Simple/Build/PathsModule.hs
When GHC is invoked with `-fwarn-implicit-prelude', then autogenerated
Paths_* modules are source of unnecessary warnings.
This commit adds OPTIONS_GHC pragma with `-fno-warn-implicit-prelude' in
to Paths_* module, so that such warnings are suppressed.
=> Use `-fno-warn-implicit-prelude' in Paths_* module

Cabal/Distribution/Simple/GHC.hs
This emulates what GHC>=8 will do on its own for older GHC versions.
This is particularly useful in combination with #2644 allowing the
solver to toggle flags depending on the availability of
`-XTemplateHaskell`.
For instance, cross-compilers and/or unregisterised GHC builds often
don't have TemplateHaskell support. Having support for toggling flags
based on availability of `-XTemplateHaskell` allows `cabal` to
support such environments with less manual intervention.
=> Conditionally omit `TemplateHaskell` from set of supported extensions

cabal-install/Distribution/Client/Dependency/Modular.hs, cabal-install/Distribution/Client/Dependency/Modular/Assignment.hs, cabal-install/Distribution/Client/Dependency/Modular/Builder.hs, cabal-install/Distribution/Client/Dependency/Modular/Dependency.hs, cabal-install/Distribution/Client/Dependency/Modular/IndexConversion.hs, cabal-install/Distribution/Client/Dependency/Modular/Linking.hs, cabal-install/Distribution/Client/Dependency/Modular/Solver.hs, cabal-install/Distribution/Client/Dependency/Modular/Validate.hs, cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/DSL.hs, cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/Solver.hs
These are the tests and the corresponding DSL modifications required for merging PR #2732. I don't think GitHub lets you reuse PR issue number so that's why I'm submitting a new PR.
Aside of general mistakes, please check I'm not missing any important test case.
I acknowledge the commit history is not very clean, let me know if you want me to clean it up.
/cc @kosmikus @luigibozzo
=> Tests for solver support language extensions and language flavours

cabal-install/Distribution/Client/IndexUtils.hs, cabal-install/Distribution/Client/Sandbox.hs, cabal-install/Distribution/Client/Sandbox/Index.hs, cabal-install/tests/IntegrationTests/sandbox-sources/should_fail/fail_on_nonexistent_source.err, cabal-install/tests/IntegrationTests/sandbox-sources/should_fail/fail_on_nonexistent_source.sh, cabal-install/tests/IntegrationTests/sandbox-sources/should_fail/fail_removing_source_thats_not_registered.err, cabal-install/tests/IntegrationTests/sandbox-sources/should_fail/fail_removing_source_thats_not_registered.sh, cabal-install/tests/IntegrationTests/sandbox-sources/should_run/tolerate_nonexistent_source.out
This is a continuation of [pull/2939](https://github.com/haskell/cabal/pull/2939) with cleaned-up commits.
=> Implement better error handling for "sandbox delete-source".

Cabal/Distribution/Simple.hs
Most Autoconf configure scripts don't support the non-standard `--with-gcc`
flag, and there does not seem to be any good reason to do so, since
Autoconf has already a proper way to set the c-compiler:
Either via the `CC` environment variable, or (with higher precedence)
by passing a commandline argument of the form `CC=clang-3.8`.
This patch simply replaces the previous non-standard `--with-gcc=clang-3.8`
argument (which was clearly misnamed to begin with) by a `CC=clang-3.8`
command-line argument to the `configure` script.
=> Use standard mechanism to tell ./configure the c-compiler

cabal-install/Distribution/Client/Setup.hs
In the definition of `globalCommand` we had
``` haskell
(case showOrParseArgs of ShowArgs -> take 8; ParseArgs -> id) [..]
```
the intention here is that the first 8 options will be shown when the user asks for `--help`, and the rest are not. However, this is rather error prone. If we forget to update that value when adding a new command line argument, we might either be wondering why the option isn't showing in the help text, or--worse--push another flag out of the help text without noticing.
This commit changes this to
``` haskell
args ShowArgs  = argsShown
args ParseArgs = argsShown ++ argsNotShown
argsShown    = [..]
argsNotShown = [..]
```
which is a lot more robust.
=> Remove magic value from `globalCommand`

cabal-install/Distribution/Client/Config.hs, cabal-install/Distribution/Client/Setup.hs, cabal-install/Distribution/Client/Types.hs
This extends `RemoteRepo` with new fields
``` haskell
-- | Enable secure access to Hackage?
remoteRepoSecure :: Bool,
-- | Root key IDs (for bootstrapping)
remoteRepoRootKeys :: [String],
-- | Threshold for verification during bootstrapping
remoteRepoKeyThreshold :: Int,
```
and modifies the parser accordingly. This does not yet require a dependency on the security library (nor are these settings yet used anywhere).
NOTE: We suggest to make the security functionality opt-in, rather than opt-out, for the first official release. Thus, the 'secure' field will be set to `False` when initialising a `~/.cabal/config` file, and existing `~/.cabal/config` files will be interpreted as if they had `secure: False`.
=> Extend repo config with security settings

Cabal/Distribution/Compiler.hs, Cabal/Distribution/InstalledPackageInfo.hs, Cabal/Distribution/PackageDescription.hs, Cabal/Distribution/Simple/Build.hs, Cabal/Distribution/Simple/BuildTarget.hs, Cabal/Distribution/Simple/Compiler.hs, Cabal/Distribution/Simple/Configure.hs, Cabal/Distribution/Simple/GHC.hs, Cabal/Distribution/Simple/GHC/Internal.hs, Cabal/Distribution/Simple/GHCJS.hs, Cabal/Distribution/Simple/HaskellSuite.hs, Cabal/Distribution/Simple/InstallDirs.hs, Cabal/Distribution/Simple/LHC.hs, Cabal/Distribution/Simple/PackageIndex.hs, Cabal/Distribution/Simple/Program.hs, Cabal/Distribution/Simple/Program/Builtin.hs, Cabal/Distribution/Simple/Program/Db.hs, Cabal/Distribution/Simple/Program/Find.hs, Cabal/Distribution/Simple/Program/HcPkg.hs, Cabal/Distribution/Simple/Program/Types.hs, Cabal/Distribution/Simple/Register.hs, Cabal/Distribution/Simple/Setup.hs, Cabal/Distribution/Simple/UHC.hs, Cabal/Distribution/Simple/Utils.hs
@23Skidoo @hvr ping
A series of patches to the Cabal lib that are needed for the nix-local-build branch of cabal-install.
There's quite a few patches here because I've tried to make each one be clear and do one thing.
Summary:
* Misc exports of useful functions
* Extra instances
* Change the interface to registerPackage so we can use it in cabal-install. This allows cabal-install to register things itself, rather than always relying on Setup register. This requires that registerPackage take fewer unnecessary or big arguments (like LocalBuildInfo).
* Extend registerPackage with a multi-instance capability
* Add compiler-independent utils for creating, deleting and testing existence of package dbs, including requesting using dir-style, but keeping the ability for Cabal lib to use file style …
=> Cabal lib for nix local build

cabal-install/Distribution/Client/BuildReports/Storage.hs, cabal-install/Distribution/Client/FetchUtils.hs, cabal-install/Distribution/Client/IndexUtils.hs, cabal-install/Distribution/Client/Install.hs, cabal-install/Distribution/Client/Sandbox.hs, cabal-install/Distribution/Client/Sandbox/Index.hs, cabal-install/Distribution/Client/Setup.hs, cabal-install/Distribution/Client/Types.hs, cabal-install/Distribution/Client/Update.hs, cabal-install/Distribution/Client/Upload.hs, cabal-install/Main.hs
This PR introduces four small changes; none of these change any functionality: they just change types around a bit to facilitate further changes in later PRs.
* `Index`
The first commit introduces
``` haskell
-- | Which index do we mean?
data Index =
-- | The global index for the specified repository
GlobalIndex Repo
-- | A (sandbox) local repository
| LocalIndex { localIndexFile :: FilePath, localCacheFile :: FilePath }
```
and then uses this in lieu of passing in two `FilePath`s to lots of functions. This means the definitions
``` haskell
indexFile (GlobalIndex repo) = repoLocalDir repo </> "00-index.tar"
cacheFile (GlobalIndex repo) = repoLocalDir repo </> "00-index.cache"
```
now only live in once place, and moreover we can, if we wanted, do something special in certain cases for …
=> Type refactoring

cabal-install/Distribution/Client/Dependency/Modular/Assignment.hs, cabal-install/Distribution/Client/Dependency/Modular/Builder.hs, cabal-install/Distribution/Client/Dependency/Modular/Configured.hs, cabal-install/Distribution/Client/Dependency/Modular/ConfiguredConversion.hs, cabal-install/Distribution/Client/Dependency/Modular/Explore.hs, cabal-install/Distribution/Client/Dependency/Modular/Flag.hs, cabal-install/Distribution/Client/Dependency/Modular/Index.hs, cabal-install/Distribution/Client/Dependency/Modular/Log.hs, cabal-install/Distribution/Client/Dependency/Modular/PSQ.hs, cabal-install/Distribution/Client/Dependency/Modular/Package.hs, cabal-install/Distribution/Client/Dependency/Modular/Preference.hs, cabal-install/Distribution/Client/Dependency/Modular/Solver.hs, cabal-install/Distribution/Client/Dependency/Modular/Tree.hs, cabal-install/Distribution/Client/Dependency/Modular/Validate.hs, cabal-install/Distribution/Client/Dependency/Modular/Version.hs
Using explicit export lists allows for trivial detection of dead code,
and this commit also removes quite a bit of said dead code.
---
This is preliminary work to separating out the solver into its own package.
=> Use explicit export lists for modular solver

cabal-install/Distribution/Client/IndexUtils.hs
The cache construction was using lazy I/O to avoid building the cache in memory all at once, but I found the algorithm a little hard to follow. This commit makes a few changes; they don't change anything fundamental, just make it a bit easier to follow:
* Separated out
``` haskell
tarEntriesList :: Tar.Entries -> [(BlockNo, Tar.Entry)]
```
into its own function. This now makes the top-level of `parsePackageIndex` a straight-forward composition
``` haskell
concatMap (uncurry extract) . tarEntriesList . Tar.read
```
so that it's easier to see that this indeed as lazy as we want. (Previously especially the name "accum" suggests an accumulator and hence a foldl rather than a foldr style, which would not be good; that bit of the algorithm is now the separate `tarEntriesList` function.)
* …
=> Separate out reading index from building cache

Cabal/Cabal.cabal, Cabal/Distribution/Compat/Semigroup.hs, Cabal/Distribution/Lex.hs, Cabal/Distribution/PackageDescription.hs, Cabal/Distribution/PackageDescription/Configuration.hs, Cabal/Distribution/Simple/CCompiler.hs, Cabal/Distribution/Simple/Haddock.hs, Cabal/Distribution/Simple/InstallDirs.hs, Cabal/Distribution/Simple/PackageIndex.hs, Cabal/Distribution/Simple/Program/GHC.hs, Cabal/Distribution/Simple/Setup.hs, Cabal/Distribution/Utils/NubList.hs
This makes the code `-Wcompat`-clean with GHC 8.0
Due to the amount of `Monoid` instances, a compat-layer is used
rather than flooding the code-base with CPP conditionals.
=> Define Semigroup instances

cabal-install/Distribution/Client/Config.hs, cabal-install/Distribution/Client/Setup.hs, cabal-install/Distribution/Client/Update.hs, cabal-install/Main.hs
If used, this will instruct the hackage-security library (once integrated_ to ignore expiry dates on TUF metadata (to be used only if, say, the main server is down and we need to rely on mirrors that have not been updated for longer than the expiry period on the timestamp). Right now this command line argument is unused.
I think this will be the last PR before the PR that adds support for secure repositories. I've set the series of PRs up in such a way that that last PR will be very small and will also make it very obvious that this does not change any of the old code paths (i.e., if you don't opt-in for security you will not get a change in behaviour). However, it will rely on as-yet-unreleased versions of both hackage-security and tar. 
Anyway, this commit is still independent.
=> Introduce ignore-expiry cmdline arg

cabal-install/Distribution/Client/BuildReports/Anonymous.hs, cabal-install/Distribution/Client/Config.hs, cabal-install/Distribution/Client/IndexUtils.hs, cabal-install/Distribution/Client/Install.hs, cabal-install/Distribution/Client/ParseUtils.hs, cabal-install/Distribution/Client/Sandbox.hs, cabal-install/Distribution/Client/Sandbox/PackageEnvironment.hs, cabal-install/Distribution/Client/Targets.hs, cabal-install/Distribution/Client/Types.hs, cabal-install/Main.hs
Some FIXMEs are downgraded to simple comments, some outright removed --
especially very old and non-severe-looking.
(All by my judgment of severity.)
---
This doesn't "handle" all the FIXMEs; this is mostly ones that are easy to judge the severity of. I might do a second round to eliminate all the remaining ones; perhaps creating real GitHub issues for them.
=> Clean up FIXMEs

Cabal/Distribution/Simple/Haddock.hs
* Cabal/Distribution/Simple/Haddock.hs
* VERY IMPORTANT! this feature depends on a particular
version of haddock, that includes the corresponding
support for these style of response files.  However,
we do not really know that version number!  So, this
change here must be co-ordinated with the haddock project.
This is intended to fix haskell/cabal#3004. The other half is haskell/haddock#379.
=> The Cabal part for fully gcc-like response files

Cabal/Distribution/Text.hs
I could not install pcre-light because cabal failed with:
parsing output of pkg-config --modversion failed
The output of that command was simply "8.02", which cabal could not
parse into a Version because of the leading zero. With this patch,
"8.02" now parses as (Version [8,2] []).
=> don't special-case versions with leading zeroes

cabal-install/Distribution/Client/BuildReports/Upload.hs, cabal-install/Distribution/Client/Configure.hs, cabal-install/Distribution/Client/Fetch.hs, cabal-install/Distribution/Client/FetchUtils.hs, cabal-install/Distribution/Client/Freeze.hs, cabal-install/Distribution/Client/Get.hs, cabal-install/Distribution/Client/GlobalFlags.hs, cabal-install/Distribution/Client/IndexUtils.hs, cabal-install/Distribution/Client/Init.hs, cabal-install/Distribution/Client/Install.hs, cabal-install/Distribution/Client/List.hs, cabal-install/Distribution/Client/Sandbox.hs, cabal-install/Distribution/Client/Setup.hs, cabal-install/Distribution/Client/Targets.hs, cabal-install/Distribution/Client/Update.hs, cabal-install/Distribution/Client/Upload.hs, cabal-install/Main.hs, cabal-install/cabal-install.cabal
**NOTE**: This PR consists of two commits, not four; the first two commits listed here are actually #3029.
The first of these commits just moves `GlobalFlags` to its own module, nothing else; this avoids circular module dependencies in the next commit.
The next commit introduces `RepoContext`:
``` haskell
-- | Access to repositories
data RepoContext = RepoContext {
-- | All user-specified repositories
repoContextRepos :: [Repo]
-- | Get the HTTP transport
--
-- The transport will be initialized on the first call to this function
, repoContextGetTransport :: IO HttpTransport
-- | Should we ignore expiry times (when checking security)?
, repoContextIgnoreExpiry :: Bool
}
```
The `RepoContext` records the information about all available repositories, and how to access them (that is, the …
=> Introduce RepoContext

cabal-install/Distribution/Client/Config.hs, cabal-install/Distribution/Client/FetchUtils.hs, cabal-install/Distribution/Client/GlobalFlags.hs, cabal-install/Distribution/Client/IndexUtils.hs, cabal-install/Distribution/Client/Security/HTTP.hs, cabal-install/Distribution/Client/Setup.hs, cabal-install/Distribution/Client/Types.hs, cabal-install/Distribution/Client/Update.hs, cabal-install/cabal-install.cabal
So this is the final PR that introduces support for secure repositories.
**NOTE**: Do not merge this, this currently relies on as-yet-unreleased versions of both the `hackage-security` library (it needs the latest `master` from https://github.com/well-typed/hackage-security) as well as the `tar` package (it currently needs the `pr/TarIndex-toList` branch of https://github.com/edsko/tar/). 
Submitting this as a PR right now so that it can be reviewed now and then merged quickly once the other libraries have been released. (Note that we will also want to have come to a decision re dependencies.)
=> Introduce secure repos

Cabal/Distribution/Version.hs
Try and pick the right default for ghc-8.
Currently the travis build fails for ghc-8 because it's not picking the right CPP defines to be compatible with binary-0.8. The logic is still just as fragile as before, but at least it as a more sensible default. The default was previously to always assume binary<0.8. Now the default is based on the ghc version. If ghc>=8 then we assume binary >=0.8, and otherwise still assume binary<0.8. So it'll still be wrong for people bootstrapping using older ghc but newer binary.
=> Tweak the GHC-8 / binary-0.8 version CPP hackery

Cabal/Cabal.cabal, Cabal/Distribution/PackageDescription/Configuration.hs, Cabal/tests/PackageTests/BuildableField/BuildableField.cabal, Cabal/tests/PackageTests/BuildableField/Main.hs, Cabal/tests/PackageTests/Tests.hs, cabal-install/Distribution/Client/Dependency/Modular/IndexConversion.hs, cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/DSL.hs, cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/Solver.hs
I added a package test for the Cabal component and several unit tests for the solver component.  This PR also resolves a conflict between #2731 and #2732.  I had to make a few changes to the solver DSL:
* Allow a flag to be used multiple times in a package.  Reusing a flag previously caused this error:
Exception: internal error: could not construct a valid install plan.
The proposed (invalid) plan contained the following problems:
Package B-1.0.0 has an invalid configuration, in particular:
missing an assignment for the flag: my-flag
* Represent the Buildable field.  Now both sides of a conditional can be either not buildable, or buildable with a list of dependencies.
* Allow a compiler to support zero languages or extensions.  I changed the signature of `DSL.exResolve` to distinguish …
=> Tests for #2731 (Ignore dependencies that are not Buildable)

cabal-install/bootstrap.sh
* tar needs to be installed before hackage-security
* base64-bytestring is also required
=> bootstrap.sh: add missing pkg and fix tar position

Cabal/Distribution/Simple/Haddock.hs
Backport #3012 (gcc-like response files for Haddock) to the 1.22 branch.
=> Backport #3012 to the 1.22 branch

cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/DSL.hs, cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/Solver.hs
This default is consistent with Cabal.
I updated the test cases from #3039 that rely on the default.  As far as I can tell, the other four tests that use flags are unaffected.  We could also add the ability to set defaults for individual flags.  That would be a bigger change, though, because it would require flags to be declared before they are used.
=> Change default flag value to True in solver DSL.

setup-dev.sh
It seems there are no longer any spurious failures, so we
can enable tests in setup-dev.sh
=> Enable tests in setup-dev.sh

Cabal/Distribution/Package.hs
Test-suite didn't catch it because we don't use this internally.
=> InstalledPackageId compatibility should be a UnitId, not a ComponentId.

cabal-install/Distribution/Client/Dependency/Modular/Solver.hs
Missing parentheses caused the solver to skip preferring linked packages with the use of `--reorder-goals`.
=> Fix bug in solver independent goals.

Cabal/src/Distribution/PackageDescription/Configuration.hs
This commit fixes the space leak in #2777 without modifying the logic for choosing flags.  It is a lot simpler than #2925, though I think an improvement to the algorithm like in #2925 is still needed.  I tested the practicality of solving for more flags by running `./Setup configure` on git-annex with 3 of the 21 flags removed.  Most of the dependencies were missing, which meant that Setup had to try all 2^18 flag combinations.  It took 13 minutes.
/cc @joeyh
=> Fix space leak in ./Setup configure

Cabal/Cabal.cabal, cabal-install/Distribution/Client/BuildReports/Types.hs, cabal-install/Distribution/Client/ComponentDeps.hs, cabal-install/Distribution/Client/Dependency/Types.hs, cabal-install/Distribution/Client/InstallPlan.hs, cabal-install/Distribution/Client/PackageIndex.hs, cabal-install/Distribution/Client/Setup.hs, cabal-install/Distribution/Client/Targets.hs, cabal-install/Distribution/Client/Types.hs, cabal-install/cabal-install.cabal
So we can use them in binary cache files.
This is the first step of merging the nix-local-build branch.
=> Add Binary instances for many types

Cabal/src/Distribution/PackageDescription/Configuration.hs, Cabal/src/Distribution/Simple/Configure.hs, cabal-install/Distribution/Client/Dependency/Modular/IndexConversion.hs
Cabal previously tried all flag combinations, which was very slow.  The new
algorithm assigns one flag at a time, and backtracks when a flag introduces a
dependency that is unavailable.
The new algorithm handles the Buildable field by adding an extra conditional at
the top level of each component that represents the condition for which the
component is buildable.  Since all dependencies go under the "then" branch, they
are only required when a flag choice makes the component buildable.  The buildable
logic is taken from the cabal-install dependency solver.
This commit also changes the error message that is shown when dependencies are
missing.  Previously, Cabal printed the shortest list of missing dependencies
from a single flag assignment.  Now it takes the union of all dependencies that …
=> Improve algorithm for choosing flags with './Setup configure'

cabal-install/Distribution/Client/Dependency.hs, cabal-install/Distribution/Client/Dependency/Modular/Builder.hs, cabal-install/Distribution/Client/Dependency/Modular/ConfiguredConversion.hs, cabal-install/Distribution/Client/Dependency/Modular/Preference.hs, cabal-install/Distribution/Client/Dependency/TopDown.hs, cabal-install/Distribution/Client/Dependency/Types.hs
See the long description in the patch
=> Solver feature: soft prefs for enabling testsuites/benchmarks

cabal-install/Distribution/Client/Configure.hs, cabal-install/Distribution/Client/Dependency.hs, cabal-install/Distribution/Client/Dependency/Modular/Preference.hs, cabal-install/Distribution/Client/Freeze.hs, cabal-install/Distribution/Client/Install.hs, cabal-install/Distribution/Client/SetupWrapper.hs
Mostly two things:
* solver: allow specifying default setup dependencies for packages that don't specify them explicitly
* setup wrapper: a couple extra features we will need
See individual patch descriptions for details.
=> More nix-local-build merging: solver and setup wrapper features

cabal-install/Main.hs
The man page previously listed commands like "cabal.exe install" on Windows, which was unnecessary.
=> Always use "cabal" as the program name when generating the man page.

cabal-install/Distribution/Client/Dependency.hs
The "allow newer" feature works by transforming the package descriptions
to adjust the dependencies on certain packages. This transformation was
not being applied to the dependencies of custom setup scripts.
=> Solver: support setup deps for --allow-newer

Cabal/Cabal.cabal, cabal-install/cabal-install.cabal
The tests use `===` and `counterexample`, which were added in QuickCheck-2.7.
=> Require QuickCheck >= 2.7

cabal-install/Distribution/Client/FileMonitor.hs, cabal-install/Distribution/Client/Glob.hs, cabal-install/Distribution/Client/IndexUtils.hs, cabal-install/Distribution/Client/RebuildMonad.hs, cabal-install/Main.hs, cabal-install/cabal-install.cabal, cabal-install/tests/UnitTests.hs, cabal-install/tests/UnitTests/Distribution/Client/FileMonitor.hs
Two related patches:
* get access to files we need to monitor for changes in source packages and installed packages
* new abstractions for tracking changes to files
The latter is fundamental to the approach we take in the nix-local-build branch. We want to run things automatically (run solver, install deps, configure, build etc) but we only want to run them when needed. This means we need to re-run actions when things those actions depend on change. What can they depend on? Files and values. So that's exactly what a file status cache monitors.
=> New infrastructure: tracking changes in files and values

cabal-install/bootstrap.sh
Since 1e1d82b8e, hashable is needed.  Adapt bootstrap.sh accordingly.
=> Fix bootstrap.sh: add hashable

cabal-install/bootstrap.sh
In 46584a2fdbd I've accidentally put the hashable version string on a
separate line, causing the shell to try to execute the command
"1.2.4.0".  Fix it by removing the line.
=> bootstrap.sh: fix error introduced in 46584a2fdbd

Cabal/Cabal.cabal, Cabal/Distribution/Compat/MonadFail.hs, Cabal/Distribution/Compat/ReadP.hs, Cabal/Distribution/ParseUtils.hs
This silences `-Wnoncanonical-monadfail-instances` warnings in the Cabal
library
=> Cabal: define MonadFail instances

appveyor.yml
This PR only builds the packages and runs the Cabal unit tests, because the other test-suites have failures.  See #3112.
Log: https://ci.appveyor.com/project/grayjay/cabal/build/1.0.47
=> Initial appveyor.yml

cabal-install/cabal-install.cabal, cabal-install/tests/IntegrationTests.hs, cabal-install/tests/IntegrationTests/exec/should_fail/exit_with_failure_without_args.err, cabal-install/tests/IntegrationTests/exec/should_fail/exit_with_failure_without_args.sh, cabal-install/tests/IntegrationTests/exec/should_run/exit_with_failure_without_args.sh, cabal-install/tests/IntegrationTests/user-config/should_fail/doesnt_overwrite_without_f.err
I implemented the simple option described in #2872.  Lines beginning with "RE:" are regular expressions, and other lines are exact matches.
I also updated the tests that check error messages containing the executable name so that they accept `cabal.exe` or `cabal`.
/cc @BardurArantsson
=> Allow regexes in cabal-install integration test .err and .out files

cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/DSL.hs
Broke with 335ac900e3f571ea9222ba4934ab9ab930153ad2.
=> Fix unit test that didn't compile

cabal-install/Main.hs
This commit only removes the extension when it is equal to ".exe".  It fixes the change made in #3103, which didn't handle executable names like `cabal-1.23`.
=> Correctly remove .exe from the cabal command listed in the man page.

cabal-install/tests/IntegrationTests/custom/common.sh, cabal-install/tests/IntegrationTests/exec/common.sh, cabal-install/tests/IntegrationTests/exec/should_run/configures_cabal_to_use_sandbox.sh, cabal-install/tests/IntegrationTests/exec/should_run/configures_ghc_to_use_sandbox.sh, cabal-install/tests/IntegrationTests/freeze/common.sh, cabal-install/tests/IntegrationTests/manpage/common.sh, cabal-install/tests/IntegrationTests/multiple-source/common.sh, cabal-install/tests/IntegrationTests/sandbox-sources/common.sh, cabal-install/tests/IntegrationTests/user-config/common.sh
Spaces in the path to `ghc-pkg` caused two tests to fail when run with the Haskell Platform on Windows.
=> Quote cabal and ghc-pkg paths in cabal-install integration tests

Cabal/Cabal.cabal, Cabal/Distribution/Simple/BuildPaths.hs, Cabal/Distribution/Simple/GHC.hs, Cabal/Distribution/Simple/GHC/Internal.hs, Cabal/Distribution/Simple/GHCJS.hs, Cabal/Distribution/Simple/Program/Find.hs, Cabal/Distribution/Simple/Utils.hs, Cabal/Distribution/System.hs, Cabal/tests/UnitTests.hs, Cabal/tests/UnitTests/Distribution/Simple/Utils.hs, Cabal/tests/UnitTests/Distribution/Version.hs, HACKING.md, cabal-install/Distribution/Client/FileMonitor.hs
For example, we used to search for `ld` when the program name specified by `ghc --info` was `i386-unknown-linux-ld`.
Fixes #3140.
=> configureToolchain: Use the same program names as 'ghc --info'.

cabal-install/tests/README.md
This is a follow-up to #3144 that splits the README into 80-character lines.
=> Format cabal-install/tests/README.md

Cabal/tests/PackageTests.hs, Cabal/tests/PackageTests/TestSuiteTests/ExeV10/Check.hs, Cabal/tests/PackageTests/Tests.hs, appveyor.yml
The flag `--skip-shared-library-tests` allows the tests to run when shared libraries are unavailable, such as during the AppVeyor build.
This is a step towards #3112.  I wanted to minimize the changes to existing tests but also make it easy to see what tests are being skipped.  I'm not sure if this is the best solution.
=> Add flag to disable Cabal package tests that use shared libraries

Cabal/tests/PackageTests/PackageTester.hs, Cabal/tests/PackageTests/Tests.hs, appveyor.yml
I also enabled the Cabal package tests on AppVeyor.
=> Handle "\r\n" in internal library package tests (fixes #3147)

Cabal/Distribution/Simple/GHC.hs, Cabal/Distribution/Simple/GHCJS.hs
=> Pass 'ghc-shared-options' to GHC during the linking phase.

cabal-install/Distribution/Client/Compat/Time.hs, cabal-install/Distribution/Client/FileMonitor.hs, cabal-install/Distribution/Client/Sandbox/Timestamp.hs, cabal-install/cabal-install.cabal, cabal-install/tests/UnitTests.hs, cabal-install/tests/UnitTests/Distribution/Client/Compat/Time.hs, cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/Solver.hs, cabal-install/tests/UnitTests/Distribution/Client/FileMonitor.hs, cabal-install/tests/UnitTests/Distribution/Client/Sandbox/Timestamp.hs, cabal-install/tests/UnitTests/Options.hs
Two changes:
* `getModTime` now uses `modificationTimeHiRes` instead of `modificationTime`
on Unix when the former is available.
* `ModTime` is now represented as a 64-bit unsigned integer in Windows UTC
format (that is, 100 ns resolution and day zero is 1601-01-01) on all
platforms. Previously we used POSIX seconds, which was wrong (low
resolution). Sandbox timestamp files in old format are now up-converted on
the fly.
Fixes #3132.
=> Improve the 'getModTime' implementation.

appveyor.yml
I excluded the FileMonitor tests because of exceptions from `removeDirectoryRecursive` (https://github.com/haskell/cabal/issues/3126#issuecomment-184080769).
I also wanted to enable the integration tests, but I couldn't figure out how to exclude more than one group of tests.  `tasty` doesn't support multiple filters: https://github.com/feuerbach/tasty/issues/38.
=> Run cabal-install unit tests on AppVeyor

cabal-install/cabal-install.cabal
Building from sdist files fails without this fix.
=> cabal-install.cabal: Update 'other-modules'

Cabal/Cabal.cabal, Cabal/Distribution/PackageDescription/Configuration.hs, Cabal/Distribution/Simple/Configure.hs, Cabal/Distribution/Simple/Setup.hs, Cabal/changelog, Cabal/tests/PackageTests/AllowNewer/AllowNewer.cabal, Cabal/tests/PackageTests/AllowNewer/benchmarks/Bench.hs, Cabal/tests/PackageTests/AllowNewer/src/Foo.hs, Cabal/tests/PackageTests/AllowNewer/tests/Test.hs, Cabal/tests/PackageTests/Tests.hs, HACKING.md, cabal-install/Distribution/Client/Config.hs, cabal-install/Distribution/Client/Configure.hs, cabal-install/Distribution/Client/Dependency.hs, cabal-install/Distribution/Client/Dependency/Types.hs, cabal-install/Distribution/Client/Install.hs, cabal-install/Distribution/Client/Setup.hs, cabal-install/changelog, cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/DSL.hs
Two improvements:
* `--allow-newer=foo --allow-newer=bar` now works as expected (equivalent to `--allow-newer=foo,bar`). Fixes #2588.
* `./Setup configure --allow-newer[=foo[,bar]]` now works. Fixes #3163.
=> Improvements to '--allow-newer'

cabal-install/Distribution/Client/Config.hs
Before this change, the relevant section of the default config file looked like this:
```
repository hackage.haskell.org
url: http://hackage.haskell.org/
```
With this change, it looks like this:
```
repository hackage.haskell.org
url: http://hackage.haskell.org/
-- secure: False
-- root-keys:
-- key-threshold:
```
/cc @edsko @dcoutts
=> Make secure remote repos a bit more discoverable.

Cabal/Distribution/Simple/Configure.hs, Cabal/Distribution/Simple/Setup.hs, Cabal/doc/installing-packages.markdown, Cabal/tests/PackageTests/Tests.hs, cabal-install/Distribution/Client/Config.hs, cabal-install/Distribution/Client/Configure.hs, cabal-install/Distribution/Client/Install.hs, cabal-install/Distribution/Client/Setup.hs, cabal-install/changelog
=> Allow limiting the scope of '--allow-newer'. 

Cabal/Cabal.cabal, Cabal/tests/PackageTests.hs, Cabal/tests/PackageTests/Options.hs, Cabal/tests/PackageTests/PackageTester.hs, Cabal/tests/PackageTests/TestSuiteTests/ExeV10/Check.hs, Cabal/tests/PackageTests/Tests.hs, appveyor.yml
There are three commits:
#3146 wasn't flexible enough to allow different tests to be skipped for different reasons.
This commit addresses a TODO comment and allows tests to be filtered and grouped more easily.
The functions `testWhen` and `testUnless` filter tests in the `TestTreeM` monad. The option `--enable-all-tests` ignores filtering.  This commit also applies filtering to the existing package tests that cannot run on Windows.
The test suite chooses whether to disable tests that use shared libraries by checking `D.System.buildOS` and the version of GHC used for `--with-ghc`.  Is that correct?
/cc @ezyang
=> Skip Cabal package tests that cannot run in the current environment

cabal-install/Distribution/Client/Upload.hs
When upload failed (e.g. wrong auth), the previous exitcode was not nonzero as expected.
=> Fix exitcode on `upload`ing failure

appveyor.yml
=> Unbreak the build on AppVeyor.

HACKING.md
This comment is unnecessary after #3180.
=> Revert "Add warning about testing Cabal on Windows"

cabal-install/Distribution/Client/Configure.hs
See #2614.  This commit turns the info-level message into a warning.  Here is an example:
`package` requires a version of Cabal that is not available:
custom-setup
setup-depends: Cabal == 1.24.0.0
Before this commit:
```
$ cabal configure
[1 of 1] Compiling Main             ( dist/setup/setup.hs, dist/setup/Main.o )
Linking ./dist/setup/setup ...
Warning: package.cabal: Ignoring unknown section type: custom-setup
Configuring package-1.0...
```
After:
```
$ cabal configure
Warning: solver failed to find a solution:
Could not resolve dependencies:
trying: package-1.0 (user goal)
next goal: package-setup.Cabal (dependency of package-1.0)
rejecting: package-setup.Cabal-1.22.4.0/installed-43c... (conflict: package => …
```
=> Warn when 'cabal configure' cannot resolve dependencies.

Cabal/Distribution/Compat/Semigroup.hs
This adds `gmappend`/`gmempty` to `Distribution.Compat.Semigroup` so it becomes available for `Cabal` and `cabal-install`.
=> Add `gmappend`/`gmempty` Generics-helpers (re #3169)

Cabal/Distribution/Compat/Semigroup.hs, Cabal/Distribution/Simple.hs, Cabal/Distribution/Simple/Configure.hs, Cabal/Distribution/Simple/Setup.hs
This implements the suggestions mentioned at
https://github.com/haskell/cabal/issues/3169#issuecomment-189281916
The main benefit of this change is turning 'ConfigFlags' into a uniform
product-type suitable for generic derivation of pointwise
`Semigroup`/`Monoid` instances.
NB: This changes the `Binary` serialisation of `ConfigFlags` since there's
now an additional `Maybe` inserted in `configPrograms`'s type
=> Turn 'configPrograms' field into a 'Last'-monoid

Cabal/Distribution/Simple.hs, Cabal/Distribution/Simple/Configure.hs, Cabal/Distribution/Simple/Setup.hs, cabal-install/Distribution/Client/Config.hs
This implements the suggestion from
https://github.com/haskell/cabal/pull/3196#issuecomment-190285328
=> Make configPrograms a bit more backward compatible

cabal-install/Distribution/Client/Dependency/Modular/Dependency.hs
and fix bug in qualifyDeps. See comments in code for motivation/justification. This is part of the investigation into #3160 . 
Requesting review by @kosmikus .
=> Remove functor instance from Dep

cabal-install/Distribution/Client/Dependency/Modular/Cycles.hs, cabal-install/Distribution/Client/Dependency/Modular/Dependency.hs, cabal-install/Distribution/Client/Dependency/Modular/Message.hs, cabal-install/Distribution/Client/Dependency/Modular/Solver.hs, cabal-install/Distribution/Client/Dependency/Modular/Tree.hs, cabal-install/cabal-install.cabal, cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/Solver.hs
**(Only one commit in this PR; the first commit is really #3167.)**
The solver currently does not attempt to detect cyclic solutions; for instance, if we have a package DB where A depends on B and B depends on A, the solver will happily return a "solution" where A and B are both installed; this will then subsequently lead to an internal error when we verify the derived install plan.
This wasn't a major deal until now because the package DB should not really contain cycles in the first place. However, as part of the work on qualified goals, this is becoming increasingly important. Even if we limit the number of qualifiers (#3160), if we want to allow a solution where, say (#1575)
* optparse-applicative's test suite gets built against tasty
* tasty gets built against an older version of …
=> Detect cycles in solver

cabal-install/Distribution/Client/Dependency/Modular/PSQ.hs, cabal-install/Distribution/Client/Dependency/Modular/Preference.hs, cabal-install/Distribution/Client/Dependency/Modular/Solver.hs, cabal-install/Distribution/Client/Dependency/Modular/Tree.hs
This change primarily does two things:
1. For `--reorder-goals`, we use a dedicated datatype `Degree`
rather than an `Int` to compute the approximate branching
degree. We map 0 and 1 to the same value. We then use a
lazy ordering and a shortcutting minimum function to look
for the "best" goal.
The motivation here is that we do not want to spend
unnecessary work. Following any goal that has 0 or 1 as degree
cannot really be "wrong", so we should not look at any others
and waste time.
This will still not always make the use of `--reorder-goals`
better than not using it, but it will reduce the overhead
introduced by it.
2. We use partitioning rather than sorting for most of the other
goal reordering heuristics that are active in all situations.
I think this is slightly more straightforward …
=> Improve goal reorder heuristics.

cabal-install/Distribution/Client/Dependency/Modular/Log.hs, cabal-install/Distribution/Client/Dependency/Modular/Message.hs
This commit removes references to the solver log that prevented it from being garbage collected.  It also forces evaluation of the current level and variable stack in `Message.showMessages`.
There is still a space leak in backjumping, so I profiled without backjumping enabled by merging in this branch: https://github.com/grayjay/cabal/tree/no-backjumping . I stopped each of these runs after a minute, but the times on my branch and master were similar when they solved for fewer packages.
EDIT: I compiled with GHC 7.10.2 and ran `cabal --ignore-sandbox install --dry-run --max-backjumps -1 hackage-server-0.4 aeson yesod --with-compiler C:/ghc-7.6.3_64/bin/ghc +RTS -p -s -h -L50
`
master (https://github.com/haskell/cabal/commit/bbc3638361cfed4ecb5e91daf9e856b051ae22f3):
this branch …
=> Fix space leaks in dependency solver logging.

cabal-install/Distribution/Client/Dependency/Modular/Explore.hs, cabal-install/Distribution/Client/Dependency/Modular/Log.hs, cabal-install/Distribution/Client/Dependency/Modular/Message.hs, cabal-install/Distribution/Client/Dependency/Modular/Solver.hs
This commit refactors backjumping so that it uses the `Progress` type instead of
separate references to a node's children and the conflict set calculated from
those children.  The behavior should be unchanged.
I added to #2914 so that I could test memory usage more easily.  These heap profiles were generated with `cabal --ignore-sandbox install --dry-run --max-backjumps -1 hackage-server-0.4 aeson yesod --with-compiler C:/ghc-7.6.3_64/bin/ghc +RTS -p -s -h -L50`.
after #2914 (https://github.com/haskell/cabal/commit/90c777299251deda571083ec0b95b68ca20e0873):
after both commits (https://github.com/haskell/cabal/commit/c1189c3d61585207e99818531e3cd990d4babf3a):
longer run with both commits, using ` -i10`.  I don't know why it increases later.
I have a few concerns about this PR.  I combined …
=> Fix space leak in solver backjumping

cabal-install/Distribution/Client/Dependency/Modular/Explore.hs
=> Refactor 'Explore.backjumpInfo' after code review

cabal-install/Distribution/Client/Configure.hs, cabal-install/Distribution/Client/Dependency.hs, cabal-install/Distribution/Client/Dependency/Modular.hs, cabal-install/Distribution/Client/Dependency/Modular/Assignment.hs, cabal-install/Distribution/Client/Dependency/Modular/Builder.hs, cabal-install/Distribution/Client/Dependency/Modular/Dependency.hs, cabal-install/Distribution/Client/Dependency/Modular/IndexConversion.hs, cabal-install/Distribution/Client/Dependency/Modular/Linking.hs, cabal-install/Distribution/Client/Dependency/Modular/Solver.hs, cabal-install/Distribution/Client/Dependency/Modular/Validate.hs, cabal-install/Distribution/Client/Dependency/TopDown.hs, cabal-install/Distribution/Client/Dependency/Types.hs, cabal-install/Distribution/Client/Fetch.hs, cabal-install/Distribution/Client/Freeze.hs, cabal-install/Distribution/Client/Install.hs, cabal-install/Distribution/Client/PkgConfigDb.hs, cabal-install/cabal-install.cabal, cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/DSL.hs, cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/Solver.hs
This pull request fixes https://github.com/haskell/cabal/issues/3016 (it does not entirely fix https://github.com/haskell/cabal/issues/335, but it goes in that direction). As explained in more detail in https://github.com/haskell/cabal/issues/3016, having the solver aware of available pkg-config dependencies is important for bindings for recent versions of external APIs.
The implementation is fairly similar to that in https://github.com/haskell/cabal/pull/2873, the only noteworthy point is that on startup we scan the list of all installed pkg-config packages in order to obtain their versions. Obtaining the list of installed packages is straightforward (`pkg-config --list-all`), based on this list we then call `pkg-config --modversion pkg1 pkg2...`.
If there are a lot of packages the …
=> Make the solver aware of pkg-config constraints

cabal-install/Distribution/Client/Dependency.hs, cabal-install/Distribution/Client/Dependency/Modular.hs, cabal-install/Distribution/Client/Dependency/Modular/ConfiguredConversion.hs, cabal-install/Distribution/Client/Dependency/Modular/IndexConversion.hs, cabal-install/Distribution/Client/Dependency/TopDown.hs, cabal-install/Distribution/Client/Dependency/TopDown/Types.hs, cabal-install/Distribution/Client/Dependency/Types.hs, cabal-install/Distribution/Client/Fetch.hs, cabal-install/Distribution/Client/FetchUtils.hs, cabal-install/Distribution/Client/Freeze.hs, cabal-install/Distribution/Client/Get.hs, cabal-install/Distribution/Client/IndexUtils.hs, cabal-install/Distribution/Client/Install.hs, cabal-install/Distribution/Client/InstallPlan.hs, cabal-install/Distribution/Client/List.hs, cabal-install/Distribution/Client/Sandbox/Types.hs, cabal-install/Distribution/Client/Targets.hs, cabal-install/Distribution/Client/Types.hs, cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/DSL.hs
This is a step towards breaking the dependency from the modular
solver on cabal-install.
=> Parameterize SourcePackage and ConfiguredPackage on package location

Cabal/Distribution/Simple/GHC.hs, Cabal/Distribution/Simple/GHC/ImplInfo.hs, Cabal/Distribution/Simple/GHC/Internal.hs, Cabal/Distribution/Simple/Program/GHC.hs, cabal-install/Distribution/Client/SetupWrapper.hs
JUST THE LATEST PATCH, it was based off of #3066, but I think it should not be difficult to commute earlier. See #3108 for some rationale.
=> Change Cabal's GHC support window to GHC 6.12 or later

cabal-install/Distribution/Client/Dependency.hs, cabal-install/Distribution/Client/Dependency/TopDown.hs, cabal-install/Distribution/Client/Dependency/TopDown/Types.hs, cabal-install/Distribution/Client/Fetch.hs, cabal-install/Distribution/Client/Freeze.hs, cabal-install/Distribution/Client/Get.hs, cabal-install/Distribution/Client/IndexUtils.hs, cabal-install/Distribution/Client/Install.hs, cabal-install/Distribution/Client/List.hs, cabal-install/Distribution/Client/Sandbox/Types.hs, cabal-install/Distribution/Client/Targets.hs, cabal-install/Distribution/Client/Types.hs, cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/DSL.hs
The alias is a shorthand for 'SourcePackage UnresolvedPkgLoc' which is
used all over the place.
---
Per @ezyang's request in #3210.
I'm a bit torn on whether this should be shortened to `UnresolvedSrcPkg`, but decided against it based on the fact that we still have `SourcePackage` around. Opinions?
=> Introduce UnresolvedSourcePackage alias

Cabal/Distribution/PackageDescription/Check.hs
The flag enable-executable-profiling warns to change it to just enable-profiling. So we'll fix that here too so we don't send people down an old path.
=> update -prof Check message

cabal-install/Distribution/Client/Config.hs, cabal-install/Distribution/Client/Dependency/Types.hs, cabal-install/Distribution/Client/DistDirLayout.hs, cabal-install/Distribution/Client/FileMonitor.hs, cabal-install/Distribution/Client/GlobalFlags.hs, cabal-install/Distribution/Client/ParseUtils.hs, cabal-install/Distribution/Client/ProjectConfig.hs, cabal-install/Distribution/Client/ProjectConfig/Legacy.hs, cabal-install/Distribution/Client/ProjectConfig/Types.hs, cabal-install/Distribution/Client/RebuildMonad.hs, cabal-install/Distribution/Client/Setup.hs, cabal-install/Distribution/Client/Targets.hs, cabal-install/Distribution/Client/Types.hs, cabal-install/Main.hs, cabal-install/cabal-install.cabal, cabal-install/tests/UnitTests.hs, cabal-install/tests/UnitTests/Distribution/Client/ArbitraryInstances.hs, cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
Supersedes PR #3156. Significant changes since then:
* Split huge `ProjectConfig` module into three as suggested by @23Skidoo 
* Proper QC tests: can round trip from `ProjectConfig` type out to a config file and back. Doing this detected lots of plumbing problems which are all now fixed.
* Several field parsers have to be implemented locally rather than using generic infrastructure. This is directly related to the above point, we need to do that to round trip correctly.
* Specifying packages in projects is greatly extended. Previously only one field for globs which could only match `.cabal` files and the globs were all allowed to match nothing. Matching nothing is useful in one major use case, allowing optional local or "vendor" unpacked deps, so one can just unpack and start using those …
=> Project config

Cabal/doc/developing-packages.markdown, cabal-install/Distribution/Client/Freeze.hs, cabal-install/Distribution/Client/GenBounds.hs, cabal-install/Distribution/Client/Init.hs, cabal-install/Distribution/Client/Setup.hs, cabal-install/Main.hs, cabal-install/cabal-install.cabal, cabal-install/changelog
Same as #3223, but backported to the 1.24 branch.
=> Add the 'gen-bounds' command (1.24 edition)

cabal-install/cabal-install.cabal
The `ProjectConfig` tests use the Arbitrary instance for Map added in 2.8.2.
=> Require QuickCheck >= 2.8.2 for cabal-install unit tests

cabal-install/Distribution/Client/FileMonitor.hs, cabal-install/Distribution/Client/Glob.hs, cabal-install/Distribution/Client/ProjectBuilding.hs, cabal-install/Distribution/Client/ProjectConfig.hs, cabal-install/Distribution/Client/ProjectConfig/Legacy.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Client/RebuildMonad.hs, cabal-install/cabal-install.cabal, cabal-install/tests/UnitTests.hs, cabal-install/tests/UnitTests/Distribution/Client/FileMonitor.hs, cabal-install/tests/UnitTests/Distribution/Client/Glob.hs, cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
A bunch of improvements to file globs and the file monitor code. In particular the file globs can now be absolute with unix or windows paths, or home-dir relative. This is important since users can specify these in cabal.project files.
Also a bunch of improvements to make the file monitor code more regular and detect more kinds of changes.
More tests to cover everything.
=> Glob monitor improvements

cabal-install/bash-completion/cabal
#3272 accidentally disabled completions at the start of flags,
e.g. on "cabal install --".
[CI SKIP]
(I shouldn't have considered more why git did not use a for-loop - because it was not a for loop.)
(Tested all of "cabal run", "cabal run -", "cabal run --", "cabal run -- ". This change does not seem to break #3271 again.)
Sorry for the noise.
=> Fix bash-completion after "--"

cabal-install/Distribution/Client/Dependency/Modular/Builder.hs, cabal-install/Distribution/Client/Dependency/Modular/Dependency.hs, cabal-install/Distribution/Client/Dependency/Modular/Package.hs, cabal-install/Distribution/Client/Dependency/Modular/Preference.hs, cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/Solver.hs
This PR changes the structure of package paths to:
``` haskell
data PP        = PP Namespace Qualifier
data Namespace = DefaultNamespace | Independent Int
data Qualifier = Unqualified | Base PN | Setup PN
```
This separates out a _namespace_ from a _qualifier_; the same space is just used to distinguish top-level goals, which are supposed to be entirely independent from each other. Qualifiers are used when we want to make independent choices for dependencies. Crucially, qualifiers do not have any kind of nesting structure. This addresses the problem described in detail in #3160, but it also introduces a change in behaviour; we will find fewer solutions (though still strictly more solutions than existing released versions of cabal). 
My suggestion would be that @dcoutts first cherry-picks …
=> Limit qualifier depth

cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/DSL.hs, cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/QuickCheck.hs, cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/Solver.hs
This commit removes the `ExTest` constructor from `ExampleDependency`. Test dependencies are now represented using the same `ExampleDependency` constructors as library dependencies.  The only
difference between dependencies of different components is that they are placed under different keys in `D.C.ComponentDeps.ComponentDeps`.
This commit also fixes an issue where duplicate test names caused the quickcheck test to fail (#3276).
=> Simplify representation of test suites in the solver DSL

Cabal/Cabal.cabal, Cabal/Distribution/Compat/GetShortPathName.hs, Cabal/Distribution/Simple.hs
=> Pass short path names to configure scripts on Windows.

cabal-install/Distribution/Client/PkgConfigDb.hs, cabal-install/Distribution/Client/ProjectPlanning.hs
We use the pkg-config db as an input for the solver, so we ought to
monitor it for changes. The pkg-config tool makes this possible, if not
totally trivial.
Note that this is for master only at the moment, as the pkg-config solver stuff is only in master.
=> Monitor the pkg-config db for changes

cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/DSL.hs, cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/QuickCheck.hs, cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/Solver.hs
I added another test and applied the backjump limit.  The backjump limit prevents the test from running out of memory when the solver's log becomes too large.
I tried merging this PR,  #3221, #3234, #3237, @edsko's branch off of #3268, and #3327 into master.  I haven't seen any failures, and the memory usage has been constant.  Maybe we can start running the tests on Travis.
=> Solver quickcheck improvements

Cabal/Cabal.cabal, Cabal/misc/gen-extra-source-files.sh, cabal-install/Distribution/Client/ProjectConfig.hs, cabal-install/cabal-install.cabal, cabal-install/tests/IntegrationTests/new-build/monitor_cabal_files.sh, cabal-install/tests/IntegrationTests/new-build/monitor_cabal_files/.gitignore, cabal-install/tests/IntegrationTests/new-build/monitor_cabal_files/cabal.project, cabal-install/tests/IntegrationTests/new-build/monitor_cabal_files/p/P.hs, cabal-install/tests/IntegrationTests/new-build/monitor_cabal_files/p/Setup.hs, cabal-install/tests/IntegrationTests/new-build/monitor_cabal_files/p/p.cabal, cabal-install/tests/IntegrationTests/new-build/monitor_cabal_files/q/Main.hs, cabal-install/tests/IntegrationTests/new-build/monitor_cabal_files/q/Setup.hs, cabal-install/tests/IntegrationTests/new-build/monitor_cabal_files/q/q-broken.cabal.in, cabal-install/tests/IntegrationTests/new-build/monitor_cabal_files/q/q-fixed.cabal.in
There was a comment claiming that it was done already but this function
does not exist. I think it was referring to findProjectPackages, but
this function tests only matchFileGlob (so it will notice if a.cabal is
renamed to b.cabal) and not the actual contents of the file.
Fixes #3323 (probably) and #3324 (has test).
CC @dcoutts
=> Monitor contents of Cabal files so we rerun solver upon edits (#3323, #3324).

cabal-install/bootstrap.sh
Without this, bootstrap.sh fails to build.
=> Fix boostrap.sh, to adapt to changes

cabal-install/Distribution/Client/FileMonitor.hs, cabal-install/Distribution/Client/Glob.hs, cabal-install/Distribution/Client/ProjectConfig.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Client/RebuildMonad.hs, cabal-install/tests/IntegrationTests/new-build/monitor_cabal_files/cabal.project, cabal-install/tests/UnitTests/Distribution/Client/Glob.hs
This builds on the partial fix from #3325. That patch makes sure that the content of the .cabal files is monitored.
In fact if the original code were working properly the conent would already be being monitored, and not just the content but also the search for the file in the case of a file glob (ie detecting changes in the set of files that match the glob).
So these patches fix the original problem plus some refactoring to eliminate the class of bug at work here. We do not revert the basic idea from #3325 however, we follow the idea that the code that searches for the files should monitor existence of the set of files that match the glob, while the code that reads the files should monitor the file content. So we keep the bit of #3325 that adds monitoring of the file content, and remove …
=> Further refactoring around monitoring cabal files

cabal-install/Distribution/Client/FileMonitor.hs, cabal-install/Distribution/Client/Glob.hs, cabal-install/Distribution/Client/ProjectConfig.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Client/RebuildMonad.hs, cabal-install/tests/IntegrationTests/new-build/monitor_cabal_files/cabal.project, cabal-install/tests/UnitTests/Distribution/Client/Glob.hs
=> Merge #3347 into 1.24

cabal-install/cabal-install.cabal, cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/Solver.hs, travis-script.sh
I cherry-picked the solver test cases from open PRs onto the solver branch (See #3357) and added issue numbers. I used `tasty-expected-failure` to ignore the tests that are currently failing.  It doesn't seem to ignore exceptions with GHC 7.8.4, though.  I can look into it later, but I didn't want to delay the PR.
/cc @edsko
=> Solver test cases

cabal-install/Distribution/Client/Dependency/Modular/Dependency.hs, cabal-install/Distribution/Client/Dependency/Modular/Linking.hs, cabal-install/cabal-install.cabal, cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/Solver.hs, travis-script.sh
All but the last two commits are from  #3359.
See #3357.  I rebased https://github.com/edsko/cabal/tree/pr/FixLinkDeps, except for the last commit, which handles a different issue.  I also removed my commits, because they weren't needed.
/cc @edsko
=> Rebase fixLinkDeps onto solver branch

Cabal/Cabal.cabal, Cabal/Distribution/PackageDescription.hs, Cabal/Distribution/PackageDescription/Configuration.hs, cabal-install/Distribution/Client/Configure.hs, cabal-install/Distribution/Client/Dependency.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Client/SetupWrapper.hs, cabal-install/cabal-install.cabal, cabal-install/tests/IntegrationTests/regression/common.sh, cabal-install/tests/IntegrationTests/regression/t3199.sh, cabal-install/tests/IntegrationTests/regression/t3199/Main.hs, cabal-install/tests/IntegrationTests/regression/t3199/Setup.hs, cabal-install/tests/IntegrationTests/regression/t3199/test-3199.cabal, cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/DSL.hs
Fixes #3199. 
To minimise the impact we should probably add default setup dependencies only to packages affected by #3199 (see @grayjay's [snippet](https://gist.github.com/grayjay/c5c2627d02303bd59a3b164055233bcb)). Note, however, that the setup wrapper will pick Cabal >= 1.24 anyway if it is installed, since it prefers new Cabal versions.
Note also that `cabal configure` will still fail (unlike `cabal install`), though the error message will be more helpful than it currently is:
```
Warning: solver failed to find a solution:
Could not resolve dependencies:
trying: test-t3199-0.1.0.0 (user goal)
next goal: test-t3199-setup.Cabal (dependency of test-t3199-0.1.0.0)
rejecting: test-t3199-setup.Cabal-1.22.5.0/installed-cfe... (conflict:
test-t3199 => …
```
=> Force Cabal >= 1.24 dep when there's no custom-setup stanza.

cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/Solver.hs
This is another test for the issue described in #3327.  The previous test started passing after #3221 was merged.  I found this test case with QuickCheck and tried to clean it up, but, unfortunately, it's still messy.  The failure only occurs with a specific goal order.
The solver must backtrack to avoid linking 1.D.  However, none of the conflict sets at level 6 contain 1.D.  1.D should be added on the line with the message "dependencies not linked".
```
targets: C, A, B
constraints:
stanzas A test (unknown source)
stanzas B test (unknown source)
stanzas C test (unknown source)
stanzas D test (unknown source)
stanzas D test (unknown source)
preferences:
strategy: PreferLatestForSelected
reorder goals: False
independent goals: True
avoid reinstalls: False
shadow packages: False
strong …
```
=> Add test case for backjumping when dependencies are not linked

cabal-install/Distribution/Client/Dependency/Modular/ConflictSet.hs, cabal-install/Distribution/Client/Dependency/Modular/Cycles.hs, cabal-install/Distribution/Client/Dependency/Modular/Dependency.hs, cabal-install/Distribution/Client/Dependency/Modular/Explore.hs, cabal-install/Distribution/Client/Dependency/Modular/Linking.hs, cabal-install/Distribution/Client/Dependency/Modular/Log.hs, cabal-install/Distribution/Client/Dependency/Modular/Preference.hs, cabal-install/Distribution/Client/Dependency/Modular/Var.hs, cabal-install/cabal-install.cabal, cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/Solver.hs
This commit is a pure refactoring, no semantic changes. Submitting as separate PR at @kosmikus  request.
This moves `ConflictSet` and `Var` into their own modules.
=> Make ConflictSet abstract

setup-dev.sh
As it turns out we often get spurious test failures, and it's generally
more useful to be able to actually build *everything* rather than having
the tests pass while building. (We already have pre-merge Travis checks,
so it's not that likely that something will slip through anyway.)
=> Remove the 'run tests' step from setup-dev.sh

cabal-install/Distribution/Client/Dependency.hs, cabal-install/Distribution/Client/Dependency/Modular/Explore.hs, cabal-install/Distribution/Client/Dependency/Modular/Solver.hs, cabal-install/Distribution/Client/Dependency/Types.hs, cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/DSL.hs, cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/QuickCheck.hs, cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/Solver.hs
Here is the test that I mentioned in #3357.  It added a lot more code than I expected, and it doesn't seem to find bugs in conflict sets any faster than the existing tests, so I'm not sure it's worth merging.
=> Add quickcheck test to compare dependency solving with and without backjumping

cabal-install/Distribution/Client/FetchUtils.hs, cabal-install/Distribution/Client/PackageHash.hs, cabal-install/Distribution/Client/ProjectPlanning.hs
During planning we calculate the nix-style package ids by hashing
everything. A crucial component of the package id hashes is the hash of
the package source, which currently is just hashes of tarballs.
For packages from hackage repos we currently have to download the
tarballs after running the solver but before elaborating the install
plan. So we have the slightly surprising behaviour that doing
cabal (new-)build --dry-run will already download the packages.
With packages from repos that support the new TUF-based format we do
have hashes available up front as part of the repo metadata / index,
without having to download the tarballs and hash them.
This patch takes advantage of secure TUF repos to get the package source
hashes without having to download tarballs. For classic non-secure …
=> Use the SHA256 hashes from the TUF repo metadata in planning

cabal-install/Distribution/Client/Configure.hs, cabal-install/Distribution/Client/Dependency.hs, cabal-install/Distribution/Client/Dependency/Modular.hs, cabal-install/Distribution/Client/Dependency/Modular/Assignment.hs, cabal-install/Distribution/Client/Dependency/Modular/Builder.hs, cabal-install/Distribution/Client/Dependency/Modular/ConflictSet.hs, cabal-install/Distribution/Client/Dependency/Modular/Cycles.hs, cabal-install/Distribution/Client/Dependency/Modular/Dependency.hs, cabal-install/Distribution/Client/Dependency/Modular/Explore.hs, cabal-install/Distribution/Client/Dependency/Modular/IndexConversion.hs, cabal-install/Distribution/Client/Dependency/Modular/Linking.hs, cabal-install/Distribution/Client/Dependency/Modular/Log.hs, cabal-install/Distribution/Client/Dependency/Modular/Message.hs, cabal-install/Distribution/Client/Dependency/Modular/Preference.hs, cabal-install/Distribution/Client/Dependency/Modular/Solver.hs, cabal-install/Distribution/Client/Dependency/Modular/Tree.hs, cabal-install/Distribution/Client/Dependency/Modular/Validate.hs, cabal-install/Distribution/Client/Dependency/Modular/Var.hs, cabal-install/Distribution/Client/Dependency/TopDown.hs, cabal-install/Distribution/Client/Dependency/Types.hs, cabal-install/Distribution/Client/Fetch.hs, cabal-install/Distribution/Client/Freeze.hs, cabal-install/Distribution/Client/Install.hs, cabal-install/Distribution/Client/PkgConfigDb.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/cabal-install.cabal, cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/DSL.hs, cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/Solver.hs, setup-dev.sh
=> Port solver fixes from master into 1.24

cabal-install/cabal-install.cabal, cabal-install/tests/IntegrationTests/sandbox-reinstalls/p/Main.hs, cabal-install/tests/IntegrationTests/sandbox-reinstalls/p/p.cabal, cabal-install/tests/IntegrationTests/sandbox-reinstalls/q/Q.hs, cabal-install/tests/IntegrationTests/sandbox-reinstalls/q/q.cabal, cabal-install/tests/IntegrationTests/sandbox-reinstalls/reinstall-modified-source.sh
I started writing this test to debug something and thought it might be useful to add to the test suite.  It runs for about 10 seconds.  I wasn't sure about one part.  How should an integration test wait for timestamps to change?
=> Test reinstalling modified add-source dependencies

appveyor.yml, travis-script.sh
I used `--quickcheck-tests=1000`, which runs for about 4 seconds on Travis.
=> Enable solver quickcheck tests in continuous integration

cabal-install/Distribution/Client/Dependency.hs, cabal-install/Distribution/Client/Dependency/Modular/Builder.hs, cabal-install/Distribution/Client/Dependency/Modular/IndexConversion.hs, cabal-install/Distribution/Client/Dependency/Modular/Solver.hs, cabal-install/Distribution/Client/Dependency/Types.hs, cabal-install/Distribution/Client/InstallPlan.hs, cabal-install/Distribution/Client/PlanIndex.hs, cabal-install/Distribution/Client/ProjectConfig.hs, cabal-install/Distribution/Client/ProjectConfig/Types.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Client/Setup.hs, cabal-install/Distribution/Client/Types.hs, cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/DSL.hs, cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/QuickCheck.hs, cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/Solver.hs, cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
This commit shouldn't change any behavior, except possibly the serialization of GenericInstallPlan, InstallFlags, etc.
=> Use newtypes for Bool solver options

cabal-install/Distribution/Client/Config.hs, cabal-install/Distribution/Client/Configure.hs, cabal-install/Distribution/Client/Dependency.hs, cabal-install/Distribution/Client/Dependency/TopDown.hs, cabal-install/Distribution/Client/Dependency/Types.hs, cabal-install/Distribution/Client/Freeze.hs, cabal-install/Distribution/Client/Install.hs, cabal-install/Distribution/Client/ProjectConfig/Legacy.hs, cabal-install/Distribution/Client/ProjectConfig/Types.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Client/Sandbox/PackageEnvironment.hs, cabal-install/Distribution/Client/Setup.hs, cabal-install/Distribution/Client/Targets.hs, cabal-install/Distribution/Client/Types.hs, cabal-install/Distribution/Solver/Modular/ConfiguredConversion.hs, cabal-install/Distribution/Solver/Modular/Message.hs, cabal-install/Distribution/Solver/Modular/Preference.hs, cabal-install/Distribution/Solver/Modular/Tree.hs, cabal-install/Distribution/Solver/Types/ConstraintSource.hs, cabal-install/Distribution/Solver/Types/ResolverPackage.hs, cabal-install/cabal-install.cabal, cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL.hs
As a follow-up to #3381 these commits move ConstraintSource and ResolverPackage too.
Incidentally, ResolverPackage is a bit anemic as a module, but I've decided to stick with the general pattern of `Distribution.Solver.Types.*` for now. I think it'll be easier to see if there's anything that should perhaps be re-combined later on.
=> Move ConstraintSource and ResolverPackage to Distribution.Solver.*

cabal-install/bash-completion/cabal
The bash completion suffers from a number of issues,
some fix with this patch;
With this patch we expand the path to cabal as well as its arguments.
For example;
~/code/cabal configure --with-ghc=$GHC <tab><tab>
will now work. Both ~ and the $GHC variable will be expanded.
If there are no .cabal files, or multiple files, the script will no longer
crash.
We still invoke cabal to get completions. If cabal detects an error and writes
errors to STDERR, these will no longer be printed to the console. Instead we
don't offer any completions.
=> Fix bugs with bash completion

cabal-install/Distribution/Client/HttpUtils.hs
The plainHttpTransport implementation saved the resulting file only when the
server responded with 200 OK, thus ignoring the payload from the server when
the server responded with a 206 Partial Content. This was causing incremental
updates through hackage-security to fail (it wouldn't fail fatally;
hackage-security would notice the invalid timestamp and download the whole
thing instead, but of course this means we're not actually getting any
incremental behaviour).
=> Don't ignore 206 response in plain-http transport

cabal-install/bootstrap.sh
An outstanding bug in GHC pre-8 causes haddock comments on GADT constructors to fail, which in turn prevents the bootstrapping process from finishing. This works around it by skipping haddocks for hackage-security.
This addresses the problem described in #3389 and well-typed/hackage-security#149, and this fix won't be necessary at all for GHC 8+.
=> Prevent bootstrap.sh from building haddocks for hackage-security

cabal-install/Distribution/Solver/Modular/ConflictSet.hs, cabal-install/Distribution/Solver/Modular/Dependency.hs, cabal-install/cabal-install.cabal
This field is only added if the `debug-conflict-sets` flag is specified to
`cabal config`; it adds a tree to `CallStack`s to a `ConflictSet`. This is very
useful when trying to understand how a certain conflict set was constructed.
/cc @kosmikus
=> Add `conflictSetOrigin` debugging field

cabal-install/Distribution/Solver/Modular/Builder.hs, cabal-install/Distribution/Solver/Modular/Explore.hs, cabal-install/Distribution/Solver/Modular/Preference.hs, cabal-install/Distribution/Solver/Modular/Tree.hs
This PR makes two changes:
* Replace `OpenGoal` with `Goal` as keys for the PSQ in `GoalChoice`
* Document the invariant that the `QGoalReason` cached in `PChoice` and co must equal the reason stored on `GoalChoice` node directly above them.
Fixes #3398.
/cc @kosmikus
=> Simplify `GoalChoice`

Cabal/Distribution/Simple/Haddock.hs
(This is against tag 1.24 but should be considered for where ever convenient.)
Prior to the response file code, all of the details of the
command line for haddock would have been logged (with level
== Verbose), so this corrects an oversight and brings the
information in the logging back to what it used to be for
cabal's haddock invocations, by logging the contents of the
response file.
* Cabal/Distribution/Simple/Haddock.hs
* Restore the logging of the entire command line used when
invoking haddock to what it used to be prior to adding
the response-file creation.
=> Restore Verbose-level logging of the haddock command line

cabal-install/Distribution/Client/Configure.hs, cabal-install/Distribution/Client/Dependency.hs, cabal-install/Distribution/Client/Dependency/TopDown.hs, cabal-install/Distribution/Client/Dependency/Types.hs, cabal-install/Distribution/Client/Freeze.hs, cabal-install/Distribution/Client/Install.hs, cabal-install/Distribution/Client/List.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Client/Targets.hs, cabal-install/Distribution/Solver/Modular.hs, cabal-install/Distribution/Solver/Modular/Preference.hs, cabal-install/Distribution/Solver/Modular/Solver.hs, cabal-install/Distribution/Solver/Types/ConstraintSource.hs, cabal-install/Distribution/Solver/Types/DependencyResolver.hs, cabal-install/Distribution/Solver/Types/InstalledPreference.hs, cabal-install/Distribution/Solver/Types/LabeledPackageConstraint.hs, cabal-install/Distribution/Solver/Types/PackageConstraint.hs, cabal-install/Distribution/Solver/Types/PackagePreferences.hs, cabal-install/cabal-install.cabal, cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL.hs
This completes the move of all the solver types which the modular solver requires to Distribution.Solver.*.
Like last time there are few *tiny* modules, but again I've decided to go for consistency; see #3383.
This means that we now have:
```sh
$ grep -r Client cabal-install/Distribution/Solver|wc -l
0
```
which is to say that there are no longer any dependencies from the Solver namespace to the Client namespace. We should probably add a Travis check or something that ensures that none are added back accidentally.
=> Move solver types to Distribution.Solver.* namespace

Cabal/Distribution/Simple/Compiler.hs, cabal-install/Distribution/Client/ProjectPlanning.hs
See patch descriptions. The main outstanding question that I've not properly checked yet is whether the old-time dep needs to be conditional. Do all current ghc versions still ship it as a core lib? If so it's fine, if not I'll have to make it conditional.
This ought to fix building a few Setup.hs scripts. I can't remember which one it was, but there was a real world example where it failed due to lacking both template-haskell and transformers.
Also add the >= 1.18 workaround that @hvr suggested.
=> Adjustments for what deps we pick for legacy Setup scripts in new-build

Cabal/Distribution/Simple/Utils.hs, Cabal/tests/UnitTests/Distribution/Simple/Utils.hs
It turns out that in rawSystemStdInOut any IO errors, including text
decoding, occurring while collecting the output (stderr or stdout) do
not get reported immediately, but only later if/when the output is
consumed. This is because the exceptions happened in the threads forked
to force the output, but if the main thread looks at the output later
then the exception is reported again.
This leads to very confusing results. In particular we had a case where
the configure process did not fail until writing out the LocalBuildInfo
because that was the first point that forced the output. So the distance
from when the exception really occurred and the fact that the exception
message does not include the name of the program run means that this is
then a pain to track down.
This patch makes sure …
=> Report process output decoding errors in context

cabal-install/Distribution/Client/ProjectPlanning.hs
This is just a version of #3376 but for the 1.24 branch rather than master. It avoids the addition to the Cabal lib.
=> Backport PR #3376 to 1.24, setup deps adjustment

cabal-install/Distribution/Solver/Modular/Solver.hs, cabal-install/cabal-install.cabal, cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs
This PR consists of two commits:
* The first just contains a bunch of additional solver tests that I've used to write the (so far, draft) blog post about backjumping in the solver
* The second add a new `debug-tracetree` configure flag. If enabled, it adds a dependency on my [tracetree](http://hackage.haskell.org/package/tracetree) library, and has the solver spit out the various build trees in .JSON format. This is useful only for debugging, and we don't want to spit these out for very large search trees (i.e., most of the them), but it's nonetheless very helpful when we _are_ debugging the solver or explain how the solver works. I used this to visualize the search trees in the [previous blog post](http://www.well-typed.com/blog/2015/03/qualified-goals/) above the solver, but the …
=> Add (optional) tracetree support into the cabal executable

cabal-install/Distribution/Client/Config.hs, cabal-install/Distribution/Client/Setup.hs, cabal-install/Distribution/Client/Upload.hs, cabal-install/Main.hs
This adds support for uploading package candidates by introducing a new
flag to `cabal upload`, --candidate. With this flag, `cabal upload` will 
upload all supplied tarballs as package candidates. If combined with `--documentation`, the
flag can also be used to upload documentation for a package candidate to
hackage.
The PR also changes `cabal upload` to display warnings that the server generates.
This is in particular useful with candidates. I'm not sure whether we should leave that behaviour
by default or only enable it if uploading candidates, because some of the warnings are not so useful,
like 
Exposed modules use unallocated top-level names: Generics GHC
Currently, I enabled it for all package uploads, regardless of whether they are candidates or not.
=> cabal upload: support package candidates

cabal-install/Distribution/Client/Config.hs
This hides the "publish" flag, so it is not possible to set publish from
cabal.config. Previously, cabal would successfully accept a line "publish: publish"
in cabal.config, but it wouldn't change anything. Now, setting this
field is no longer allowed.
We could have instead allowed setting a default behaviour for publishing packages
in the config file, but it would make the user interface more difficult, since
cabal upload would then have to support three options for setting IsCandidate:
use from config (default), publish (override config), candidate (override config).
=> upload: don't allow 'publish' in cabal.config

Cabal/misc/gen-extra-source-files.sh, cabal-install/Distribution/Client/CmdBuild.hs, cabal-install/Distribution/Client/CmdRepl.hs, cabal-install/Distribution/Client/ProjectBuilding.hs, cabal-install/Distribution/Client/ProjectConfig.hs, cabal-install/Distribution/Client/ProjectOrchestration.hs, cabal-install/cabal-install.cabal, cabal-install/tests/IntegrationTests2.hs, cabal-install/tests/IntegrationTests2/exception/build/Main.hs, cabal-install/tests/IntegrationTests2/exception/build/a.cabal, cabal-install/tests/IntegrationTests2/exception/configure/a.cabal, cabal-install/tests/IntegrationTests2/exception/no-pkg/empty.in, cabal-install/tests/IntegrationTests2/exception/no-pkg2/cabal.project
Some improvements to the exception handling during new-build, plus tests.
Yet TODO: better reporting, handling download exceptions. Covering more cases in tests. Still, it should be a strict improvement.
* It's possible that this might fix #3407, but I have not confirmed this.
* It may also fix the "silent" aspect of #3394, though we may still need to improve the reporting bit here before that's no longer silent. Again not checked that yet.
=> New build exception handling

cabal-install/Distribution/Client/PackageHash.hs
On Windows we have serious problems with path lengths (see #3430).
Windows imposes a maximum path length of 260 chars, and even if we
can use the windows long path APIs ourselves, we cannot guarantee
that ghc, gcc, ld, ar, etc etc all do so too.
So our only choice is to limit the lengths of the paths, and the only
real way to do that is to limit the size of the 'InstalledPackageId's
that we generate. We do this by truncating the package names and
versions and also by truncating the hash sizes.
Truncating the package names and versions is technically ok because they
are just included for human convenience, the full source package id is
included in the hash.
Truncating the hash size is disappointing but also technically ok. We
rely on the hash primarily for collision avoidance not for any …
=> Try using smaller package ids on Windows (see #3430)

Cabal/Distribution/Simple/GHC/Internal.hs
GHC 7.8 [renamed](https://ghc.haskell.org/trac/ghc/ticket/4862) `"Gcc Linker flags"` to `"C compiler link flags"` and `"Ld Linker flags"` to `"ld flags"`. Without this corresponding fix in Cabal, the `old-time` package fails to compile on Ubuntu yakkety amd64, where the system GCC now defaults to `-pie` and GHC has
```console
$ ghc --info | grep -i pie
,("C compiler flags","-fno-PIE -fno-stack-protector")
,("C compiler link flags","-no-pie")
,("ld flags","-no-pie")
```
=> Get linker flags correctly from GHC ≥ 7.8

.travis.yml
Now that we bootstrap Cabal and cabal-install, we don't have to install
the package anymore.
=> No need to install cabal-install package

Cabal/doc/installing-packages.markdown
This PR contains updated docs for `--package-db`. 
I've added info about the intial stack and `--global`/`--user` constraints. There is also information on how to reset the stack using `--package-db=clear`.
Resolve #2345
=> Updated --package-db docs

Cabal/Distribution/Simple/BuildPaths.hs, Cabal/Distribution/Simple/Haddock.hs, Cabal/Distribution/Simple/Install.hs, Cabal/Distribution/Simple/Setup.hs, cabal-install/Distribution/Client/Config.hs, cabal-install/Main.hs
When generating haddocks with the `--for-hackage` switch, the generated
haddocks are placed in a different directory than the normal ones, which
includes the package id instead of just the package name. When we ran
hscolour, we didn't respect this, so the highlighted source would not
be placed in the correct directory and thus was missing from the tarball.
This patch fixes that.
Fixes #3451
=> haddock/hscolour: fix highlighted source location

cabal-install/Distribution/Client/Dependency.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/cabal-install.cabal, cabal-install/tests/IntegrationTests2.hs, cabal-install/tests/IntegrationTests2/build/setup-custom1/A.hs, cabal-install/tests/IntegrationTests2/build/setup-custom1/Setup.hs, cabal-install/tests/IntegrationTests2/build/setup-custom1/a.cabal, cabal-install/tests/IntegrationTests2/build/setup-custom2/A.hs, cabal-install/tests/IntegrationTests2/build/setup-custom2/Setup.hs, cabal-install/tests/IntegrationTests2/build/setup-custom2/a.cabal, cabal-install/tests/IntegrationTests2/build/setup-simple/A.hs, cabal-install/tests/IntegrationTests2/build/setup-simple/Setup.hs, cabal-install/tests/IntegrationTests2/build/setup-simple/a.cabal
Commit 2f97657 added default setup dep handling to the existing install command code paths, but unfortunately broke the handling for the new-build code path. It added a call to addDefaultSetupDependencies into the standardInstallPolicy. That interfered with the addDefaultSetupDependencies that ProjectPlanning was already using.
So this patch splits a basicInstallPolicy out of standardInstallPolicy, where the basicInstallPolicy is all the old stuff, and the standardInstallPolicy just adds the addDefaultSetupDependencies that the install/fetch/freeze commands need. So then ProjectPlanning uses just the basicInstallPolicy.
The 2f97657 commit also added a new and simpler method to determine if a package has had default setup deps added. Previously ProjectPlanning had to use a rather complex …
=> Fix handling of default setup deps

Cabal/Distribution/System.hs
This PR contains documentation for the known `os()` and `arch()` aliases.
Resolves #2138
=> Documentation for known os and arch aliases

cabal-install/Distribution/Client/InstallPlan.hs, cabal-install/Distribution/Client/ProjectBuilding.hs, cabal-install/cabal-install.cabal
Fix issue #3428, by updating the install plan with the right info
When building packages we update the install plan with the completed packages and for libraries we include the InstalledPackageInfo. We now support packages that register multiple libraries but only one of them is the representative public library, and only that one is stashed in the install plan. Out of the list of library registraions we select the primary one by looking for the one with the expected unit it. As part of collecting the registration info we do some processing (to account for older Cabal and ghc versions) and the mistake was that while did that post-processing ok and registered the right libraries we ended up returing the un-processed registraion info and so then failed to find the primary lib, and thus …
=> Fix issue #3428

travis-script.sh
Makes easier to reason how to address https://github.com/haskell/cabal/issues/3465
=> 	Time different blocks of travis script

cabal-install/Distribution/Client/CmdBuild.hs, cabal-install/Distribution/Client/CmdRepl.hs, cabal-install/Distribution/Client/ProjectOrchestration.hs
Fixes issue #3495
This also adds a stub where we can add more detailed failure reporting, but this starts with nothing more than the exit code.
Unlike the existing "cabal install" failure reporting, we don't need or want "build" failure reporting to be quite so noisy in common cases like the one local package failing to build, since ghc reports its own errors and there's enough context to see what's going on.
This is an alternative to #3501 which uses the existing "cabal install" build reporting, which is ok for install but too noisy by default for "cabal build". We can add extra reporting later.
=> Exit with non-0 code when build fails

cabal-install/Distribution/Client/CmdFreeze.hs, cabal-install/Distribution/Client/ProjectConfig.hs, cabal-install/Distribution/Client/ProjectOrchestration.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Client/ProjectPlanning/Types.hs, cabal-install/Main.hs, cabal-install/cabal-install.cabal, cabal-install/tests/IntegrationTests2.hs
Adds a new-freeze command, the freeze command to go along with the other new project-based commands.
See also https://github.com/haskell/cabal/issues/3502
=> New freeze command

cabal-install/Distribution/Solver/Modular/Assignment.hs, cabal-install/Distribution/Solver/Modular/Builder.hs, cabal-install/Distribution/Solver/Modular/ConfiguredConversion.hs, cabal-install/Distribution/Solver/Modular/ConflictSet.hs, cabal-install/Distribution/Solver/Modular/Cycles.hs, cabal-install/Distribution/Solver/Modular/Dependency.hs, cabal-install/Distribution/Solver/Modular/Explore.hs, cabal-install/Distribution/Solver/Modular/Flag.hs, cabal-install/Distribution/Solver/Modular/Linking.hs, cabal-install/Distribution/Solver/Modular/Log.hs, cabal-install/Distribution/Solver/Modular/Message.hs, cabal-install/Distribution/Solver/Modular/Package.hs, cabal-install/Distribution/Solver/Modular/Preference.hs, cabal-install/Distribution/Solver/Modular/Solver.hs, cabal-install/Distribution/Solver/Modular/Tree.hs, cabal-install/Distribution/Solver/Modular/Validate.hs, cabal-install/Distribution/Solver/Modular/Var.hs, cabal-install/Distribution/Solver/Types/PackagePath.hs, cabal-install/cabal-install.cabal
This commit is cherry-picked from #3510.  I'll merge it once the build passes.
=> Move goal qualification types into D.Solver.Types.PackagePath

cabal-install/Distribution/Client/Dependency.hs, cabal-install/Distribution/Solver/Modular/Dependency.hs, cabal-install/Distribution/Solver/Modular/Preference.hs, cabal-install/Distribution/Solver/Modular/Solver.hs, cabal-install/Distribution/Solver/Types/Variable.hs, cabal-install/cabal-install.cabal, cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/QuickCheck.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs
This PR implements #3489.  It isn't ready to be merged yet, because I need to finish updating the tests that are affected by goal order.
I wanted to make it available for review before finishing it, because it probably overlaps with #3502.  The second commit exposes the solver's goal qualification types.  I moved types like `Q`, `QPN`, and `PP` into a new module, `D.Solver.Types.PackagePath`, and renamed some of them.  /cc @dcoutts
=> Add a goal order parameter to the dependency solver

cabal-install/Main.hs
Fixes #3494. Cherry-picked from `1.24`, just double-checking with Travis.
=> cabal-install: make user config optional if possible

cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs
See #3489 and #3510.
@kosmikus Do you think we should specify the goal order for these two tests?  I wasn't completely sure.
=> Freeze solver goal order in two more unit tests

cabal-install/Distribution/Solver/Modular/Builder.hs, cabal-install/Distribution/Solver/Modular/Flag.hs, cabal-install/Distribution/Solver/Modular/IndexConversion.hs, cabal-install/Distribution/Solver/Modular/Preference.hs, cabal-install/Distribution/Solver/Modular/Tree.hs
The first commit creates a newtype for the weak/trivial attribute of package flags and stanzas.
The second commit fixes a bug in dependency solver stanza preferences. Previously, stanza choices were set to "weak" even when the stanza preference did not apply. See https://github.com/haskell/cabal/issues/3453#issuecomment-222580111.
@kosmikus Does it make sense to call the newtype `WeakOrTrivial`?  I'm still not completely sure I understand the meaning of the weak/trivial fields in the solver's `FChoice` and `SChoice` nodes.
=> Fix bug in dependency solver stanza preferences

cabal-install/Distribution/Client/Compat/ExecutablePath.hs
=> Fix getExecutablePath on *BSD.

Cabal/Distribution/Compat/Graph.hs
=> Import hygiene and miscellaneous fixes.

Cabal/Cabal.cabal, Cabal/tests/UnitTests/Distribution/Version.hs, cabal-install/tests/UnitTests/Distribution/Client/ArbitraryInstances.hs
This should be applied to `1.24` as well. I guess.
=> Support QuickCheck-2.9

cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/QuickCheck.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs
This change avoids holding the whole log in memory.
=> Use 'Progress' type to print the solver log in unit tests

Cabal/Distribution/PackageDescription.hs, Cabal/Distribution/PackageDescription/Check.hs, Cabal/Distribution/PackageDescription/Configuration.hs, Cabal/Distribution/PackageDescription/Parse.hs, Cabal/Distribution/PackageDescription/PrettyPrint.hs, Cabal/Distribution/Simple/Build.hs, Cabal/Distribution/Simple/BuildTarget.hs, Cabal/Distribution/Simple/Configure.hs, Cabal/Distribution/Simple/Install.hs, Cabal/Distribution/Simple/JHC.hs, Cabal/Distribution/Simple/LocalBuildInfo.hs, Cabal/Distribution/Simple/PreProcess.hs, Cabal/Distribution/Simple/SrcDist.hs, Cabal/tests/PackageTests/Macros/macros.cabal, Cabal/tests/PackageTests/Tests.hs, cabal-install/Distribution/Client/BuildTarget.hs, cabal-install/Distribution/Client/Dependency/TopDown.hs, cabal-install/Distribution/Client/InstallPlan.hs, cabal-install/Distribution/Client/List.hs, cabal-install/Distribution/Client/PackageUtils.hs, cabal-install/Distribution/Client/ProjectPlanOutput.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Solver/Modular/IndexConversion.hs, cabal-install/Distribution/Solver/Types/ComponentDeps.hs, cabal-install/Distribution/Solver/Types/PackageFixedDeps.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/QuickCheck.hs
The resulting code is more verbose, but it is more backwards-compatible
and actually is simpler to understand in some cases (because
CLibName uniquely identifies the "public library"; no faffing
about with package names to figure it out.)
=> BC fix: libraries -> library/subLibraries (#3574)

Cabal/Distribution/Simple.hs, Cabal/Distribution/Types/HookedBuildInfo.hs
I got sucked into this rathole while puzzling over why
we pass both 'PackageDescription' and 'LocalBuildInfo' (which
has a 'PackageDescription' in 'localPkgDescr').  The conclusion
is that they were different, but not for a good reason. Now they're
the same.
Added docs fixes #1757.
=> Consistently update 'localPkgDescr' with 'HookedBuildInfo' + docs

Cabal/Cabal.cabal, Cabal/Distribution/PackageDescription/Parse.hs, Cabal/Distribution/PackageDescription/PrettyPrint.hs, Cabal/Distribution/ParseUtils.hs, Cabal/Distribution/PrettyUtils.hs
Move pretty-printing related stuff out of `Parse*` modules.
The move of `writePackageDescription` is breaking change, but on the way for `Parsec` the whole 
`Distribution.PackageDescription.Parse` will be redone (types will change).
=> Pretty utils

Cabal/Cabal.cabal, Cabal/Distribution/Simple/Configure.hs, Cabal/Distribution/Simple/Setup.hs, Cabal/Distribution/Version.hs, Cabal/changelog, Cabal/doc/installing-packages.markdown, Cabal/tests/PackageTests/AllowOlder/AllowOlder.cabal, Cabal/tests/PackageTests/AllowOlder/benchmarks/Bench.hs, Cabal/tests/PackageTests/AllowOlder/src/Foo.hs, Cabal/tests/PackageTests/AllowOlder/tests/Test.hs, Cabal/tests/PackageTests/Tests.hs, cabal-install/Distribution/Client/Config.hs, cabal-install/Distribution/Client/Configure.hs, cabal-install/Distribution/Client/Dependency.hs, cabal-install/Distribution/Client/Install.hs, cabal-install/Distribution/Client/ProjectConfig.hs, cabal-install/Distribution/Client/ProjectConfig/Legacy.hs, cabal-install/Distribution/Client/ProjectConfig/Types.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Client/Setup.hs, cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
This provides the dual flag to `--allow-newer` for symmetry
=> Implement `--allow-older`

Cabal/Distribution/PackageDescription/Check.hs
It seems that package authors are unaware of the purpose of
synopsis/description fields, and their impact on cabal and Hackage.  A
common mistake is to write a verbose synopsis and leave the description
field empty or even worse with useless boilerplate-text filled in by
tooling, resulting in a suboptimal presentation on Hackage.
The `synopsis` is supposed to be a terse <80 char description. In fact,
the cabal user's guide states:
> A very short description of the package, for use in a table of
> packages. This is your headline, so keep it short (one line) but as
> informative as possible. Save space by not including the package name
> or saying it’s written in Haskell.
On Hackage this synopsis is printed in the `<title>` and at the top of the
package page, and is difficult to spot. …
=> New `cabal check` to warn about suspiciously short descriptions

Cabal/Cabal.cabal, Cabal/Distribution/Simple/Build.hs, Cabal/Distribution/Simple/BuildTarget.hs, Cabal/Distribution/Simple/Configure.hs, Cabal/Distribution/Simple/GHC.hs, Cabal/Distribution/Simple/GHCJS.hs, Cabal/Distribution/Simple/Install.hs, Cabal/Distribution/Simple/LocalBuildInfo.hs, Cabal/Distribution/Simple/Register.hs, Cabal/Distribution/Simple/Test.hs, Cabal/Distribution/Simple/Test/ExeV10.hs, Cabal/Distribution/Simple/Test/LibV09.hs, Cabal/Distribution/Types/ComponentLocalBuildInfo.hs, Cabal/Distribution/Types/HookedBuildInfo.hs, Cabal/Distribution/Types/LocalBuildInfo.hs, Cabal/Distribution/Types/TargetInfo.hs, Cabal/changelog, Cabal/tests/PackageTests/TestSuiteTests/ExeV10/Check.hs, Cabal/tests/PackageTests/Tests.hs, cabal-install/Distribution/Client/Run.hs, travis-bootstrap.sh
This is an omnibus patch, with the overall goal of making
LocalBuildInfo Great Again.  The essential ideas:
* New type 'TargetInfo' which bundles together 'ComponentLocalBuildInfo'
and 'Component'.  Eventually, it will also record file paths / module
targets.  This data structure is basically what you want; a lot of
old Cabal code did lots of gyrations converting from
'ComponentLocalBuildInfo' to 'Component' and vice versa, now
it's all centralized.
* The "new" API for 'LocalBuildInfo' is in
"Distribution.Types.LocalBuildInfo".  The general principle
is, where we previous dealt in 'ComponentLocalBuildInfo',
we now deal in 'TargetInfo'.  There are shockingly few
functions we need!
* I've restored 'componentsConfigs' to its Cabal 1.24 signature
for BC.
* I killed a number of unused …
=> Refactor LocalBuildInfo interface.

Cabal/Distribution/Simple/Compiler.hs, Cabal/Distribution/Simple/Configure.hs, Cabal/Distribution/Simple/GHC.hs, Cabal/Distribution/Simple/GHCJS.hs, Cabal/Distribution/Simple/Test.hs, Cabal/Distribution/Simple/Test/ExeV10.hs, Cabal/Distribution/Simple/Test/LibV09.hs, Cabal/Distribution/Types/LocalBuildInfo.hs
The profiling settings in LocalBuildInfo are combined as discussed in #3597. Fields were added to track if program coverage is enabled. Both features are now disabled (and a warning emitted) if the compiler does not support them.
=> LocalBuildInfo: combine profiling settings, track program coverage

Cabal/Distribution/Compat/Graph.hs, Cabal/tests/UnitTests/Distribution/Compat/Graph.hs, cabal-install/Distribution/Client/BuildReports/Storage.hs, cabal-install/Distribution/Client/Configure.hs, cabal-install/Distribution/Client/Install.hs, cabal-install/Distribution/Client/InstallPlan.hs, cabal-install/Distribution/Client/InstallSymlink.hs, cabal-install/Distribution/Client/ProjectBuilding.hs, cabal-install/Distribution/Client/ProjectOrchestration.hs, cabal-install/Distribution/Client/ProjectPlanOutput.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Client/ProjectPlanning/Types.hs, cabal-install/Distribution/Client/Types.hs, cabal-install/cabal-install.cabal, cabal-install/tests/IntegrationTests2.hs, cabal-install/tests/UnitTests.hs, cabal-install/tests/UnitTests/Distribution/Client/InstallPlan.hs
Rebased version of #3609. Not yet included fixes from #3611, but each commit does compile and pass tests on at least linux with one ghc version.
=> InstallPlan refactor v3

cabal-install/Distribution/Client/FetchUtils.hs, cabal-install/Distribution/Client/ProjectBuilding.hs, cabal-install/Distribution/Client/ProjectOrchestration.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Client/ProjectPlanning/Types.hs, cabal-install/Distribution/Client/Types.hs, cabal-install/cabal-install.cabal
Partly this is a continuation of the InstallPlan refactoring #3622, but also a related change to fix #3387, by handling exceptions during download properly.
These things are also a step towards finishing #3394 properly, since it means we now have all the `BuildResults` using proper exception types and so will be able to use that to report at the end what if anything when wrong.
=> fix exception handling of downloads in new-build

Cabal/Distribution/PackageDescription/Parse.hs, Cabal/Distribution/PackageDescription/PrettyPrint.hs, Cabal/Distribution/Simple.hs, Cabal/Distribution/Types/HookedBuildInfo.hs, Cabal/Distribution/Types/PackageDescription.hs
This reverts commit af7bb5371a1ac776f93ab075d7e945cefefe0928,
restoring 'HookedBuildInfo' backwards compatibility.
=> Revert "Generalize HookedBuildInfo to work with any type of component."

Cabal/Distribution/Compat/GetShortPathName.hs
=> Now allocates properly sized result buffer.

cabal-install/Distribution/Client/Init/Heuristics.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Client/Sandbox.hs, cabal-install/Distribution/Client/Setup.hs, cabal-install/Distribution/Solver/Modular/Solver.hs
If we were generating Haddock for cabal-install (we're not
currently) these would cause errors.  Make them stop causing
errors.
=> Fix Haddock syntax in cabal-install.

Cabal/Distribution/Simple/GHC.hs
=> Don't pass -package-db and -package flags to --abi-hash.

cabal-install/Distribution/Client/Dependency.hs
This commit undoes a change to the -v3 log caused by the solver parameter newtypes (#3377).
master:
```
preferences: 
strategy: PreferLatestForSelected
reorder goals: ReorderGoals False
count conflicts: CountConflicts True
independent goals: IndependentGoals False
avoid reinstalls: AvoidReinstalls False
shadow packages: ShadowPkgs False
strong flags: StrongFlags False
max backjumps: infinite
```
this PR:
```
preferences: 
strategy: PreferLatestForSelected
reorder goals: False
count conflicts: True
independent goals: False
avoid reinstalls: False
shadow packages: False
strong flags: False
max backjumps: infinite
```
=> Simplify solver parameter log message.

stack.yaml
The external zlib package is required to build the zlib Haskell
library. This change will not affect Stack-using developers who do not
have Nix integration enabled globally. This change will not affect
non-Stack-using developers at all.
=> stack.yaml: add optional Nix dependency zlib

cabal-install/Distribution/Client/CmdBuild.hs, cabal-install/Distribution/Client/CmdRepl.hs, cabal-install/Distribution/Client/InstallPlan.hs, cabal-install/Distribution/Client/ProjectOrchestration.hs
This should fix issue #3394
Previous patches had made the changes to collect the detailed error info all in one place. So this patch is just about deciding what to report and how to report it.
Still TODO is mentioning log files, ie when the package build was being logged to a file, we should include a snippet and say where the log file can be found for full details.
=> Report build failures with reasonably formatted messages

Cabal/Distribution/Simple/GHC/Internal.hs, cabal-install/Distribution/Client/SetupWrapper.hs
=> Pass on -v0 to GHC.

cabal.project.travis
From Travis:
Warning: /Users/travis/build/haskell/cabal/cabal.project.local: Unrecognized
field 'ghc-options' on line 6
This reverts commit 6b7ff81978a91fd8999edf56730d305bc32aaa50.
=> Revert "Try top-level -Werror."

cabal-install/Distribution/Solver/Modular/Explore.hs, cabal-install/Distribution/Solver/Modular/Log.hs, cabal-install/Distribution/Solver/Modular/RetryLog.hs, cabal-install/cabal-install.cabal, cabal-install/tests/UnitTests.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/RetryLog.hs
This commit adds a data structure, `RetryLog`, which is like a difference list
for the `Progress` type, except that it only supports efficient appends at
failures. Since the solver continually appends logs and calls `tryWith` while
exploring the search tree, it is important for those operations to be efficient.
Afterwards, the solver converts the `RetryLog` back to a `Progress` so that it
can be processed with pattern matching in Log.hs and Message.hs.
I got the idea from #3640 (See https://github.com/haskell/cabal/issues/3640#issuecomment-236391147).  The new log type isn't a monad because bind would have had to manipulate failures instead of successes, which is inconsistent with the monad instance for `Progress`.  I also avoided modifying the `Progress` type, because it is convenient …
=> Solver: Use difference lists to combine logs in 'Explore.exploreLog'.

cabal-install/Distribution/Solver/Modular/Linking.hs
If 1.A is already linked to 0.A, then linking 2.A to 1.A gives the same result as linking 2.A to 0.A. This commit avoids creating options to link to packages that are already linked, to reduce the branching factor of the search tree.
=> Solver: Only link packages to other unlinked packages.

appveyor.yml
This fixes #3687
Swithed AppVeyor test to GHC 8.0.1 because 7.10.3 is broken (https://chocolatey.org/packages/ghc/7.10.3) and added the `-y` option and `refreshenv` after installing GHC as suggested by Chocolatey
=> AppVeyor fails installing GHC 7.10.3

cabal-install/Distribution/Client/Compat/ExecutablePath.hs
Reverts haskell/cabal#3531 (and reopens haskell/cabal#3512)
See also explaination in https://ghc.haskell.org/trac/ghc/ticket/12377#comment:4
=> Revert "Fix getExecutablePath on *BSD."

cabal-install/Distribution/Client/BuildReports/Anonymous.hs, cabal-install/Distribution/Client/BuildReports/Storage.hs, cabal-install/Distribution/Client/CmdBuild.hs, cabal-install/Distribution/Client/CmdRepl.hs, cabal-install/Distribution/Client/Install.hs, cabal-install/Distribution/Client/InstallPlan.hs, cabal-install/Distribution/Client/InstallSymlink.hs, cabal-install/Distribution/Client/ProjectBuilding.hs, cabal-install/Distribution/Client/ProjectOrchestration.hs, cabal-install/Distribution/Client/ProjectPlanning/Types.hs, cabal-install/Distribution/Client/Types.hs, cabal-install/tests/IntegrationTests2.hs
This is the follow-up to #3665 and should address all the issues raised there.
Reporting build logs is important as we otherwise have no real info for why deps failed to build. It does make the presentation more difficult however because build logs can be long and in principle there can be several, which means it can take up more than a single screen in a console. The first thing users notice is typically the last few messages, so in the case that we're presenting long build logs then its important to also include a short summary at the end.
So our approach is this: for packages where we want to show a build log, we dump those first, in full, each with a header to indicate which package it is, log file name (for later reference), plus any extra detail we have from the phase of the failure …
=> Rework new-build failure reporting to include build logs

Cabal/doc/developing-packages.markdown
I was recently [tripped up](https://github.com/haskell/vector/pull/134#issuecomment-240459112) since negating (`!`) an `impl` test with a version constraint didn't behave like I thought it did. Per @hvr's request, I'm documenting this behavior here.
=> Clarify what logical negation of impl with version ranges means

Cabal/Distribution/Compat/Environment.hs, cabal-install/Distribution/Client/SetupWrapper.hs, cabal-install/Distribution/Client/Utils.hs
But first things first; need `unsetEnv` to implement `withEnv` to implement same-process environment change.
=> Fix #3483, set HASKELL_DIST_DIR

Cabal/Distribution/Compat/Environment.hs
See https://ghc.haskell.org/trac/ghc/ticket/12494; we cargo-culted
some incorrect code from base. Lift the restriction.
=> Make setEnv accept empty strings.

Cabal/Distribution/Simple/Build/Macros.hs, Cabal/changelog, Cabal/tests/PackageTests/PackageTester.hs
I also realized LOCAL_COMPONENT_ID is pessimal if we don't
depend on a library, so I removed it. (It has never been
in a real Cabal release.)
=> Fix #3041, ifndef all CURRENT_PACKAGE_KEY and related macros.

cabal-install/Distribution/Solver/Modular/Log.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs
Previously, the solver filtered out redundant backjumping messages twice, once in `Log.logToProgress` and again in `Message.showMessages`. However, `showMessages` relied on the backjumping messages to determine where to insert messages about missing packages. This led to missing "unknown package" messages (part of issue #3617).
This commit removes the filtering in `logToProgress`, because it was redundant.
=> Avoid filtering the solver log before 'showMessages'.

cabal-install/Distribution/Client/BuildTarget.hs
Fixes #3391. CC @hesselink , @23Skidoo , @hvr, @dcoutts, @acfoltzer. Please test and report.
=> Fix #3391: build all packages if no target is specified.

Cabal/Distribution/Simple/GHC.hs, Cabal/Distribution/Simple/GHCJS.hs, Cabal/Distribution/Simple/Utils.hs, Cabal/changelog
Look for package databases on GHC_PACKAGE_PATH or GHCJS_PACKAGE_PATH as necessary, lifting the restriction that these variables be unset.
Fixes #3728 and #2711.
=> Respect GHC_PACKAGE_PATH

stack.yaml
Adding more tools for building with Stack on Nix.
=> stack.yaml/nix: add required build and test tools

Cabal/Cabal.cabal, Cabal/Distribution/PackageDescription/Check.hs, Cabal/Distribution/Version.hs, Cabal/changelog, Cabal/doc/developing-packages.markdown, Cabal/tests/PackageTests/CaretOperator/Check.hs, Cabal/tests/PackageTests/CaretOperator/my.cabal, Cabal/tests/PackageTests/Tests.hs, Cabal/tests/UnitTests/Distribution/Version.hs
This implements a new syntactic sugar: The version range operator
`^>=` which is equivalent to `>=` intersected with an
automatically inferred major upper bound.
This new syntax is only allowed for `cabal-version: >=2.0`, and
allows to describe the most common use of version
bounds more conveniently:
build-depends: foo ^>= 1.2.3.4,
bar ^>= 1
The declaration above is exactly equivalent to
build-depends: foo >= 1.2.3.4 && < 1.3,
bar >= 1 && < 1.1
The `^`-symbol was chosen because it can serve as a mnemonic when the
`>` sign is rotated and interpreted as "less than ceiling"
Moreover, `^` appears to become a quasi-standard to denote morally
equivalent operator that way in other language ecosystems which similiar
to Haskell have adopted semantic versioning:
- Node: …
=> Implement Caret-style version range operator

cabal-install/Distribution/Client/ProjectConfig/Legacy.hs
=> Fix #3752, don't specify compiler/optimization twice.

Cabal/Distribution/Simple/Test/LibV09.hs
Currently, when a detailed-0.9 test suite raises an exception, it fails to write its `TestLogs` data to a log file, and cabal experiences a parse error when trying to read it.  This patch adds exception catching code to `Distribution.Simple.Test.LibV09.stubMain`.
Really, there should be another per-test exception handler in `stubRunTests'`.  This one will still be necessary to handle exceptions that occur outside of a test suite, like in the `tests :: IO [Test]` computation.
I think this will fix #1426
=> stubMain now catches exceptions

cabal-install/Distribution/Client/Setup.hs, cabal-install/Distribution/Solver/Modular/Cycles.hs, cabal-install/Distribution/Solver/Modular/Explore.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs
I removed the comments about --independent-goals not being ready, because #2842 was fixed, and @kosmikus said that the other comment was added before setup dependencies were finished.  I tried the option just now, and it seemed to work.  It seems like we don't really need it with new-build, though.
=> Update some dependency solver comments

Cabal/Distribution/Simple/InstallDirs.hs, Cabal/Distribution/Simple/PreProcess/Unlit.hs, Cabal/Distribution/Simple/Test/LibV09.hs, Cabal/Distribution/Text.hs, Cabal/Distribution/Version.hs, cabal-install/Distribution/Client/Init/Types.hs, cabal-install/Distribution/Client/Upload.hs, cabal-install/Main.hs
When 'read' is used on invalid input, it raises a "no parse" exception that is
typically very unhelpful to the user.  It is generally more desirable to either
handle the error or produce a more helpful error message.
This actually happens sometimes.  When a user creates a detailed-0.9 test
suite, and that test suite crashes or is killed so it can't write its result
log, the bare read in Distribution.Simple.Test.LibV09.runTest fails and cabal
fails with "no parse".
I could have just written a patch to fix that, but it seemed like a better idea
to find all uses of bare read and see what we can do for all of them.
I have grepped through the repository and I think I've found all uses of bare
'read' that might raise the dreaded 'no parse' exception.  The plan is to
separately patch each of …
=> Added TODO: eradicateNoParse comments to all uses of bare 'read'

cabal-install/Distribution/Client/CmdFreeze.hs
We deliberately exclude version constraints of packages that are local to the project (since their versions are fixed to be what they are anyway, and it'd just make it harder to bump versions etc). However the flag constraints of local packages were also being ignored, which leads to "slushy" frozen files.
We saw this in practice with leksah where the flag gtk-3.18 was varying between different users and causing great confusion.
=> Fix freeze constraints to include flags of local packages

cabal-install/Distribution/Client/SetupWrapper.hs, cabal-install/cabal-install.cabal, cabal-install/tests/IntegrationTests/custom-setup/Cabal-99998/Cabal.cabal, cabal-install/tests/IntegrationTests/custom-setup/Cabal-99998/CabalMessage.hs, cabal-install/tests/IntegrationTests/custom-setup/Cabal-99999/Cabal.cabal, cabal-install/tests/IntegrationTests/custom-setup/Cabal-99999/CabalMessage.hs, cabal-install/tests/IntegrationTests/custom-setup/custom-setup-without-cabal-defaultMain/Setup.hs, cabal-install/tests/IntegrationTests/custom-setup/custom-setup-without-cabal-defaultMain/custom-setup-without-cabal-defaultMain.cabal, cabal-install/tests/IntegrationTests/custom-setup/custom-setup-without-cabal/Setup.hs, cabal-install/tests/IntegrationTests/custom-setup/custom-setup-without-cabal/custom-setup-without-cabal.cabal, cabal-install/tests/IntegrationTests/custom-setup/custom-setup/Setup.hs, cabal-install/tests/IntegrationTests/custom-setup/custom-setup/custom-setup.cabal, cabal-install/tests/IntegrationTests/custom-setup/custom_setup_without_Cabal_doesnt_allow_Cabal_import.sh, cabal-install/tests/IntegrationTests/custom-setup/custom_setup_without_Cabal_doesnt_require_Cabal.sh, cabal-install/tests/IntegrationTests/custom-setup/installs_Cabal_as_setup_dep.sh
Previously, cabal always chose a Cabal library version to use for a package's
setup script that didn't take setup-depends into account (cabalLibVersion).
cabalLibVersion depended on the cabal-version field, the installed versions of
Cabal, etc., and it was used when setup dependencies were not chosen by the
dependency solver. When a package had a setup-depends, cabalLibVersion was later
ignored in favor of the version chosen by the dependency solver. However,
calculating the variable caused an error when the only suitable Cabal version
was installed during the same install command (issue #3436). cabalLibVersion was
also used to filter the configure flags (issue #3433).
This commit sets cabalLibVersion to the version chosen by the dependency solver,
when possible.
I added an integration …
=> Consistently use the Cabal version picked by the dependency solver.

cabal-install/Distribution/Client/Dependency.hs, cabal-install/Distribution/Solver/Modular/Solver.hs, cabal-install/Distribution/Solver/Types/DependencyResolver.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs
The solver can handle duplicate targets by linking them together, but the log
is more complex, and the result is the same as if the targets were deduplicated
beforehand.
Duplicate targets can occur in a sandbox (issue #3203).
=> Deduplicate build targets by storing them in a set.

cabal-install/Distribution/Client/SetupWrapper.hs
It is useful to know outside of `setupWrapper` which Setup version will
be used, so the two phases (knowing and running) are separated.
This is merely refactoring. I need it for my `reconfigure` branch and I don't want it to get merge-conflicted again while I finish that feature.
=> SetupWrapper: separate determining and running Setup

cabal-install/Distribution/Client/SrcDist.hs
=> D.C.SrcDist: pass builddir to the setup script.

Cabal/Distribution/Simple/Utils.hs, cabal-install/Distribution/Client/ProjectOrchestration.hs
COMMIT 1:
Now if you cabal new-build -v, it will tell you which file
changed that caused us to rebuild.  This is not a full fix
for #3352 because we still don't output this info by default,
but it's a start.
COMMIT 2:
Make default install plan printing more chatty, fixes #3352.
Now it looks something like this by default:
```
- Cabal-1.25.0.0 (test:package-tests) (file Cabal.cabal changed)
- Cabal-1.25.0.0 (test:unit-tests) (cannot read state cache)
- cabal-install-1.25.0.0 (exe:cabal, test:integration-tests, test:integration-tests2, test:solver-quickcheck, test:unit-tests) (file tests/UnitTests/Distribution/Solver/Modular/DSL.hs changed)
- pretty-show-1.6.12 (exe:ppsh) (first run)
```
Signed-off-by: Edward Z. Yang …
=> Make default install plan printing more chatty

cabal-install/Distribution/Client/DistDirLayout.hs, cabal-install/Distribution/Client/ProjectConfig.hs, cabal-install/Distribution/Client/ProjectPlanning.hs
We went through all the trouble of populating projectConfigCacheDir... and then didn't use it. Stop doing something dumb.
I am not sure why the original code did something insane,
which may indicate a lurking bug.
=> Axe cabalPackageCacheDirectory, use projectConfigCacheDir, fixing #3392

cabal-install/Distribution/Client/ProjectConfig.hs, cabal-install/cabal-install.cabal, cabal-install/tests/IntegrationTests2.hs, cabal-install/tests/IntegrationTests2/exception/bad-config/cabal.project
This is for the "packages: blah/*/" locations in cabal.project files, when they don't match anything or match crazy unrecognised stuff. Previously we just used the derived Show.
Also improve classification of project package problems in a couple cases so we get more accurate helpful error messages in those cases.
Should improve #3636, but that one could be better since it's for the special case of an implicit project file.
=> Error messages for package locations

cabal-install/Distribution/Solver/Modular/Builder.hs, cabal-install/Distribution/Solver/Modular/Degree.hs, cabal-install/Distribution/Solver/Modular/Explore.hs, cabal-install/Distribution/Solver/Modular/Linking.hs, cabal-install/Distribution/Solver/Modular/PSQ.hs, cabal-install/Distribution/Solver/Modular/Preference.hs, cabal-install/Distribution/Solver/Modular/Solver.hs, cabal-install/Distribution/Solver/Modular/Tree.hs, cabal-install/Distribution/Solver/Modular/Validate.hs, cabal-install/Distribution/Solver/Modular/WeightedPSQ.hs, cabal-install/cabal-install.cabal, cabal-install/tests/UnitTests.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/WeightedPSQ.hs
I split this out from #2917 because the data structure is also needed for goal-scoring (#3488).  `WeightedPSQ` associates weights with choices in the search tree.  This PR uses `WeightedPSQ` for package, flag, and stanza choices and `PSQ` for goal choices, but eventually all choices should use `WeightedPSQ`.  There are a few TODOs in the code.
/cc @kosmikus 
EDIT: This PR uses `[Double]` as the weight type to avoid changing the behavior of the solver.
=> Add 'WeightedPSQ' and use it to sort package, flag, and stanza choices.

cabal-install/Distribution/Client/Types.hs
Prevents us from trying to build a package multiple times,
when we should only build it once.
This is basically 15dd84559f3b957752e97dd7014758b7c17d5657 all
over again, but for the legacy codepath.
Fixes #3721.
CC @tuncer
=> Deduplicate nodeNeighbors in legacy codepath.

cabal-install/Distribution/Client/Install.hs, cabal-install/Distribution/Client/ProjectConfig.hs, cabal-install/changelog
Specifically, this changes the default from `.../$pkgid.log`
to `.../$compiler/$libname.log`, which avoids logfiles overwriting
each other even though theyty refer to different artifacts, as well
as aligning the format with `~/.cabal/store`'s structure.
This addresses #3807
=> Change default logfile template to use more unique name

cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Client/SolverInstallPlan.hs
Previously we'd build Cabal and custom setup dependencies
with profiling even though it wasn't necessary. Using a
refined dependency graph fixes the problem.
If looking at a Graph with different set of neighbors becomes
a common op, maybe we should add some functions to handle
this specific case.
Fixes #3789.
=> Compute profiling/shared based on library deps only.

Cabal/Distribution/PackageDescription/Check.hs, Cabal/Distribution/Simple/Configure.hs, Cabal/Distribution/Simple/GHC.hs, Cabal/Distribution/Simple/Haddock.hs, Cabal/Distribution/Simple/Install.hs, Cabal/Distribution/Simple/Register.hs, Cabal/Distribution/Simple/SrcDist.hs, Cabal/Distribution/Simple/Utils.hs
We can't use the one from System.FilePath since we don't know if we're
dealing with Windows or Posix paths. See comments in code for more
detail.
This was discovered while working on haskell/hackage-server#533.
=> Use platform independant isRelative.

.gitignore, Cabal/Distribution/Simple/Setup.hs, cabal-install/Distribution/Client/Configure.hs, cabal-install/Distribution/Client/Reconfigure.hs, cabal-install/Distribution/Client/Sandbox.hs, cabal-install/Distribution/Client/SavedFlags.hs, cabal-install/Distribution/Client/Setup.hs, cabal-install/Main.hs, cabal-install/cabal-install.cabal, cabal-install/changelog
Fixes #2214 by adding a `reconfigure` command and invoking it whenever necessary. The last configure flags used are saved in a version-independent format so it should never be necessary for the user to reconfigure manually.
=> Add `reconfigure` command

cabal-install/cabal-install.cabal, cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/QuickCheck.hs
This PR ensures that randomly-generated ComponentDeps don't have tests and exes with the same name.  It also evaluates the solver result to force install plan validation.  Previously, the tests only evaluated enough of the result to determine whether the solver found an install plan, but that install plan could be invalid.
=> Validate InstallPlan in solver quickcheck tests, and update tests to handle executables.

cabal-install/Distribution/Client/Config.hs, cabal-install/Main.hs, cabal-install/tests/UnitTests/Distribution/Client/UserConfig.hs
Update on #3714. Fixes #3710. Two changes:
Firstly, fix the distinction between raw config and effective config. The raw config is what is actually in the config file. The effective config is the raw config plus defaults and other adjustments. Normally we want the effctive config, but commands like config update and diff need to work with raw config. The first patch sorts that out. We need to do that so that we can add more defaults without having those written to the initial config file, or breaking the config update and diff commands.
Secondly, we add new hackage root keys. To simplify bootstrapping the hackage security, clients like cabal-install should ship the root keys. These are the initial root keys. Note that there is crypographic evidence that these are the right keys that any …
=>  Add the new hackage root keys for distribution with cabal (v2)

cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Client/ProjectPlanning/Types.hs
@hvr reported that some component names were being reported
multiple times:
ezyang@sabre:~/Dev/cabal-tmp$ cabal-shake new-build
- Cabal-1.25.0.0 (lib) (file Cabal.cabal changed)
- happy-1.19.5 (exe:happy, exe:happy) (dependency rebuilt)
This is because a build target was showing up multiple times in the
list, which can occur if we simultaneously build-depends and build-tools
on the same package.  So nub it out.
=> Nub build targets, prevent duplicate output of component.

Cabal/Distribution/PackageDescription/Check.hs, Cabal/Distribution/Simple/Configure.hs, Cabal/Distribution/Simple/GHC.hs, Cabal/Distribution/Simple/Haddock.hs, Cabal/Distribution/Simple/Install.hs, Cabal/Distribution/Simple/Register.hs, Cabal/Distribution/Simple/SrcDist.hs, Cabal/Distribution/Simple/Utils.hs
This was discussed in #3810. Only use the platform independent
heuristics when we have to.
Also rename the functions to isPortableAbsolute and isPortableRelative
to make the distinction clearer.
=> Only use portable isAbsolute/isRelative when we have to.

cabal-install/Distribution/Solver/Modular/Preference.hs
The space leak was introduced in #3594. #3594 added a new variable,
`sortedVersions`, to sort the subtrees under package choice nodes in the search
tree. However, `sortedVersions` referenced the subtrees and caused them to be
retained when it was not used. This commit forces evaluation of
`sortedVersions`.
=> Fix a space leak in package preferences (part of issue #3824).

Cabal/doc/conf.py, Cabal/doc/nix-local-build.rst
A really basic cabal lexer, but makes code samples a little bit nicer.
I've only converted `nix-local-build.rst` so far.
=> Basic cabal lexer for docs

.travis.yml, Cabal/Distribution/Compat/Binary.hs, Cabal/Distribution/Compat/Environment.hs, Cabal/changelog
GHC 7.4 is more than four years old now, well outside our three-year
support window. (Actually, GHC 7.6 is outside our support window too,
but I don't have any pending patches which are broken with that
version.)
Attn. @23Skidoo @rthomas
=> Drop support for GHC 7.4

Cabal/doc/_templates/layout.html, Cabal/doc/conf.py, Cabal/doc/installing-packages.rst, Cabal/doc/references.inc
Makes installing-packages.rst less noisy by replacing most of monospace
markup with `.. option::`. This makes it possible to reference options
from other parts of docs and adds them to index.
Index is no longer empty so it is added to nav menu via template
override in _template folder
[preview](https://sopvop.github.io/cabal/installing-packages.html#programs-used-for-building)
and [index](https://sopvop.github.io/cabal/genindex.html)
=> Make docs less noisy and referenceable

cabal-install/Distribution/Client/HttpUtils.hs
Ignore HTTP range requests when using 'wget', as it doesn't support them and would instead fail.
=> WGET doesn't support range requests, so we should ignore them when using it

cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/cabal-install.cabal, cabal-install/tests/IntegrationTests/regression/t3827.sh, cabal-install/tests/IntegrationTests/regression/t3827/cabal.project, cabal-install/tests/IntegrationTests/regression/t3827/p/P.hs, cabal-install/tests/IntegrationTests/regression/t3827/p/p.cabal, cabal-install/tests/IntegrationTests/regression/t3827/q/Main.hs, cabal-install/tests/IntegrationTests/regression/t3827/q/q.cabal
Previously, we were only doing library dependencies of the libraries,
which is wrong if we try to profile an executable.
Fixes #3827. CC @grayjay.
=> Correctly propagate profiling for ALL library dependencies.

cabal-install/Distribution/Client/Setup.hs
@23Skidoo We discussed improving the help text for the reconfigure command. Is this what you had in mind?
IIUC, the man page is generated from the command-line help text, so this should update the man page, too.
=> Add examples to help text for reconfigure command

cabal-install/Distribution/Client/CmdBuild.hs, cabal-install/Distribution/Client/CmdConfigure.hs, cabal-install/Distribution/Client/CmdRepl.hs, cabal-install/Distribution/Client/InstallPlan.hs, cabal-install/Distribution/Client/ProjectBuilding.hs, cabal-install/Distribution/Client/ProjectOrchestration.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Solver/Modular/Preference.hs, cabal-install/cabal-install.cabal, cabal.project
The flag was already there, this just hooks it up with the logic.
It works in the obvious way given how new-build works. That is, it does not affect solving, it's just a matter of changing what bits we chose to build, much like the logic for selecting which bits of the install plan to execute based on the targets to build.
The difference from pruning for the selected targets (which is just taking a dep closure) is that for `--only-dependencies` it does not always make sense so it can fail. The logic for this already existed in the old `cabal install` code path, so this just ports it over. It's a little different since it works on the `ElaboratedInstallPlan` rather than the `SolverInstallPlan`.
If it fails it gives us something like:
$ cabal new-build --dry network ./hackage-repo-tool/ …
=> Implement cabal new-build --only-dependencies

Cabal/doc/nix-local-build.rst
I believe it's "per-project" vs "cached across *projects*" not "...across *packages*"
[skip ci]
=> doc: "Local versus external packages" intro paragraph bad contrast

cabal-install/Distribution/Client/GlobalFlags.hs, cabal-install/Distribution/Client/IndexUtils.hs
"Secure" cabal repositories use a new extended & incremental
`01-index.tar`. In order to avoid issues resulting from clobbering
new/old-style index data, we save them locally to different names.
With this patch, secure repos generate/update the files below on `cabal update`
- `01-index.cache`
- `01-index.tar`
- `01-index.tar.gz`
- `01-index.tar.idx`
- `mirrors.json`
- `root.json`
- `snapshot.json`
- `timestamp.json`
...while the legacy codepaths for non-secure repos operate on the files
- `00-index.cache`
- `00-index.tar`
- `00-index.tar.gz`
- `00-index.tar.gz.etag`
This way the old/new codepaths don't interfere with each other anymore.
Note: The format of `01-index.cache` file will be extended by the upcoming `--index-state` feature
This trivially addresses #3854
=> Store secure repo index data as 01-index.*

cabal-install/Distribution/Client/ProjectConfig.hs, cabal-install/Distribution/Client/ProjectConfig/Legacy.hs, cabal-install/Distribution/Client/ProjectConfig/Types.hs, cabal-install/tests/IntegrationTests2.hs, cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
This changes the error when a `cabal.project` is missing from:
```
% cabal new-build
The package location glob 'foo./*.cabal' does not match any files or directories.
```
To (Implicit):
```
% cabal new-build
When using an implicit cabal.project configuration, the following errors were encountered:
The package location glob './*.cabal' does not match any files or directories.
```
Or (Explicit):
```
% cabal new-build
When using the configuration located at /home/bren/proj/cabal/cabal.project, the following errors were encountered:
The package location glob './*.cabal' does not match any files or directories.
```
This is done by tracking the provenance of the `cabal.project` file in `readProjectLocalConfig`, otherwise it defaults to `Implicit`.
The `ProjectConfig` is now also passed to …
=> Track cabal.project provenance for error reporting

cabal-install/Distribution/Solver/Modular/Builder.hs, cabal-install/Distribution/Solver/Modular/Cycles.hs, cabal-install/Distribution/Solver/Modular/Explore.hs, cabal-install/Distribution/Solver/Modular/Linking.hs, cabal-install/Distribution/Solver/Modular/Preference.hs, cabal-install/Distribution/Solver/Modular/Solver.hs, cabal-install/Distribution/Solver/Modular/Tree.hs, cabal-install/Distribution/Solver/Modular/Validate.hs
This PR is part of #2917.  The new field is only used for some refactoring in this PR, but #2917 uses it to store the install plan scores.
/cc @kosmikus
=> Add a new field to solver Done nodes, and simplify Explore.exploreLog.

Cabal/Distribution/GetOpt.hs
As suggested by @ezyang, invite anyone to have a go at merging.
Also re-export the types from the GetOpt from base rather than re-defining locally. In particular this means we gain a few instances.
The changes wrt base GetOpt are:
* One change to allow us to treat "cabal --flag command" as "cabal command --flag" e.g. "cabal -v configure" to mean "cabal configure -v" for flags that are not recognised as global flags, pass them on to the sub-command. See the difference in 'shortOpt'.
* Line wrapping in the 'usageInfo' output, plus a more compact rendering of short options, and slightly less padding.
=> Clarify the differences with the GetOpt from base

Cabal/Distribution/Simple/Configure.hs
=> Rename configProf/configCoverage local variables to not shadow.

cabal-install/Distribution/Client/ProjectBuilding.hs
Previously the output was:
Building profunctors-5.2 lib...
Building semigroupoids-5.1...
Now it is:
Building profunctors-5.2 (lib)...
Building semigroupoids-5.1 (all, due to Custom setup)...
Fixes #3808.
CC @phadej
=> Print that we are building all due to Custom setup.

cabal-install/Distribution/Client/InstallPlan.hs, cabal-install/Distribution/Client/ProjectBuilding.hs, cabal-install/Distribution/Client/ProjectOrchestration.hs, cabal-install/Distribution/Client/ProjectPlanOutput.hs, cabal-install/Distribution/Client/ProjectPlanning.hs
So why add an Installed state? Didn't we just remove the `Installed`, `Processing` and `Failed` states? Those states were used when we followed the approach of updating the `InstallPlan` as a build progressed (whereas we now do traversals without altering the `InstallPlan`).
The idea of adding an Installed state now is that we can more usefully represent the state of the plan when we "improve" the plan with packages from the store or when we update the plan having checked if inplace packages are up to date. Currently in these two places we replace `Configured` source packages with `PreExisting` packages. There's a couple problems with this. Firstly the `PreExisting` state only contains an `InstalledPackageInfo` which means we loose information compared to all the detail in the Configured …
=> Installplan installed state

Cabal/Distribution/Compat/Prelude.hs, Cabal/Distribution/Package.hs, Cabal/Distribution/Version.hs
I needed the `NFData` instance for `Dependency`... which made me realise that
writing the implementation for the also needed `VersionRange` instance by hand
was too tedious, so here we are with a `genericRnf` compat helper...
=> Add helper for Generic NFData instances

Cabal/Distribution/Compat/Binary.hs, cabal-install/Distribution/Client/IndexUtils.hs
This commit extends the index cache entries relevant for 01-index to
include block numbers and timestamps, and makes them strict so recent
GHCs unpack the fields:
data IndexCacheEntry
= CachePackageId PackageId BlockNo
| CachePreference Dependency
| CacheBuildTreeRef BuildTreeRefType BlockNo
to
data IndexCacheEntry
= CachePackageId PackageId !BlockNo !Timestamp
| CachePreference Dependency !BlockNo !Timestamp
| CacheBuildTreeRef !BuildTreeRefType !BlockNo
For the legacy `00-index.tar`s, the 'Timestamp' field is set to (-1),
and the original 00-index.cache format is retained.
For (secure) `01-index.tar`s, all of `IndexCacheEntry`s data is stored
in the `01-index.cache` file.
Moreover, to avoid having to write out and parse new two integers per
cache entry, this patch switches to using …
=> Extend 01-index.cache & use 'Binary' encoding

Cabal/Distribution/Simple/Configure.hs, cabal-install/Distribution/Client/Setup.hs
In Cabal 1.22.5.0, the semantics of
--disable-profiling/--enable-profiling depend on ordering (because there
is a hack that operates by looking at the current flag assignment and
doing something). In particular, if I specify --enable-library-profiling
--disable-profiling, I end up with library profiling DISABLED.
The fix is that we NEVER pass --enable-profiling or --disable-profiling
to Cabal. At the moment, and according to my historical analysis, Cabal
ONLY uses configProf to affect the effective library/executable
profiling, which means that anything we do with --enable-profiling, we
can do using the library/executable profiling individually. Since these
are always flags for the versions of Cabal library we support, we will
get order invariance. Historical versions have varied on …
=> Never use --enable-profiling when invoking Setup.

cabal-install/Distribution/Client/Configure.hs, cabal-install/Distribution/Client/Dependency.hs, cabal-install/Distribution/Solver/Modular.hs, cabal-install/Distribution/Solver/Modular/IndexConversion.hs, cabal-install/Distribution/Solver/Modular/Solver.hs, cabal-install/Distribution/Solver/Types/Settings.hs
There is a bug in `cabal configure`'s invocation of the solver in
Distribution/Client/Configure.hs:
standardInstallPolicy
installedPkgIndex
(SourcePackageDb mempty packagePrefs)
[SpecificSourcePackage localPkg]
We can see that the solver is given an EMPTY source package database.
This is because we assume that everything you need from cabal configure
is taken from the installed package index.
But this is NOT true for executables, which never have an entry in the
installed package index. So we SHOULD NOT solve for
executables in the legacy codepath, since there isn't anything useful we
can do with the info anyway.  This gets toggled using a new solver
parameter SolveExecutables.
I didn't bother with a test because this will be obsoleted by
nix-local-build.
Fixes #3875
Signed-off-by: Edward …
=> Don't solve for executables in legacy code path.

cabal-install/Distribution/Client/IndexUtils.hs, cabal-install/Distribution/Client/IndexUtils/Timestamp.hs, cabal-install/cabal-install.cabal, cabal-install/tests/UnitTests.hs, cabal-install/tests/UnitTests/Distribution/Client/IndexUtils/Timestamp.hs
Most notably, this allows us to provide a custom instance for `Text`
This is a broken out commit from my `--index-state` patch-queue which can be
reviewed & merged in its own right IMO.
=> Turn 'Timestamp' into a proper type

Cabal/doc/nix-local-build.rst, cabal-install/Distribution/Client/Config.hs, cabal-install/Distribution/Client/IndexUtils.hs, cabal-install/Distribution/Client/IndexUtils/Timestamp.hs, cabal-install/Distribution/Client/Install.hs, cabal-install/Distribution/Client/ProjectConfig.hs, cabal-install/Distribution/Client/ProjectConfig/Legacy.hs, cabal-install/Distribution/Client/ProjectConfig/Types.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Client/Setup.hs, cabal-install/tests/UnitTests/Distribution/Client/ArbitraryInstances.hs, cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
This implements a new flag `--index-state` (and its `cabal.project`/config-file
equivalent `index-state: ...`) which allows to change the source package index
state the solver uses to compute install-plans. This is particularly useful in
combination with freeze-files in order to also freeze the state the package
index was in at the time the install-plan was frozen.
This provides the core functionality, on which future enhancements can build
upon. See also description of #3604 for some possible enhancements.
=> Implement `--index-state` aka index freezing

cabal-install/cabal-install.cabal
Fwiw, the GHC executables are compiled with full `-rtsopts` as well.
The benefit is that one can use flags such as `-M1G` to limit the heap
space, or profile memory usage via `-hT`.
=> Enable `-rtsopts` for `cabal` executable

cabal-install/Distribution/Client/IndexUtils.hs
Without this optimisation, `cabal info zzz` results in
```
960,397,120 bytes allocated in the heap
739,652,560 bytes copied during GC
67,757,128 bytes maximum residency (24 sample(s))
2,234,096 bytes maximum slop
147 MB total memory in use (0 MB lost due to fragmentation)
```
with this optimisation:
```
1,000,825,744 bytes allocated in the heap
656,112,432 bytes copied during GC
44,476,616 bytes maximum residency (24 sample(s))
2,302,864 bytes maximum slop
109 MB total memory in use (0 MB lost due to fragmentation)
```
So the total memory in use is significantly lower. The total runtime is
also slighlty reduced, from
```
INIT    time    0.001s  (  0.001s elapsed)
MUT     time    0.683s  (  1.050s elapsed)
GC      time    0.946s  (  0.946s elapsed)
EXIT    time    0.005s  (  0.005s …
```
=> Use hash-consing to optimise index cache

cabal-install/Distribution/Client/FileMonitor.hs, cabal-install/Distribution/Client/InstallPlan.hs, cabal-install/Distribution/Client/ProjectBuilding.hs, cabal-install/Distribution/Client/ProjectOrchestration.hs, cabal-install/Distribution/Client/ProjectPlanOutput.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Client/RebuildMonad.hs, cabal-install/tests/UnitTests/Distribution/Client/FileMonitor.hs
PR #3863 got merged but then had to be reverted due to a latent bug in the FileMonitor code.
PR #3887 fixes the FileMonitor stuff (as yet unmerged).
So this PR is just the original one, but rebased on top of the FileMonitor fixes. So ignore the first 3 patches (or go comment on them in #3887).
Note it's difficult to have an integration test for install plan improvement at the moment because we don't have an easy way to get non-hackage packages into the store. Once we add support for local tarballs then this will be easier to test automatically.
=> Installplan installed state (V2)

cabal-install/Distribution/Client/FileMonitor.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Client/RebuildMonad.hs, cabal-install/tests/UnitTests/Distribution/Client/FileMonitor.hs
This fixes the bug that @ezyang identified previously https://github.com/haskell/cabal/pull/3863#issuecomment-248495178
> What seems to happen is that the mtime monitor is overwritten, so that we now only test directory existence. I guess monitors should be a monoid and accumulate?
The fix is that rather than doing any fancy merging of monitor kinds, we just do the simple thing and keep each monitor spec separately, so each one will be checked when the file system is probed. Internally, rather than keeping a Map indexed by FilePath we just keep a list.
Also add a unit test for this fix.
For belt & braces we add a check on the posix specified behaviour of directory modification times that we rely on.
While we're at it follow another of @ezyang's suggestions to use more `Rebuild` monad …
=> FileMonitor fix

Cabal/Distribution/Compat/Graph.hs, cabal-install/Distribution/Client/InstallPlan.hs
This subsumes PR #3888 and fixes issue #3889.
We worked out what the actual problem with the InstallPlan processing invariant failures were. The invariant was wrong. See the discussion in #3889 for details.
This PR fixes the invariant, and adds a couple other parts to the invariant that we think are true. Also add commentary on the invariant and do something similar to what PR #3888 does (but a bit more lightweight) so we get more informative assertion violations in future.
Finally, do a bit of housekeeping, rename some things and export a few more utils that are going to be useful in other upcoming PRs.
=> InstallPlan fixes and misc housekeeping

cabal-install/Distribution/Client/Configure.hs, cabal-install/Distribution/Client/ProjectBuilding.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Client/SetupWrapper.hs
Fixes #3899
When cabal new-repl spawns ghci, it spawns this as a subprocess.
In UNIX like systems, if a CTRL+C is sent to this child process
it also bubbles up to the parent process, causing it to terminate.
Also see https://hackage.haskell.org/package/process-1.4.2.0/docs/System-Process.html#g:4.
However, this is not what we want for interactive subprocesses.
Interactive processes usually define their own handlers for CTRL+C,
for example GHCi uses CTRL+C to reset the input buffer. So instead
of terminating on CTRL+C we want to delegate CTRL+C to GHCi
and let it do its thing.
Luckily, we can enable CTRL+C delegation such that the parent
process ignores the CTRL+C and instead delegates it to the
child process.
=> Make interactive setup delegate CTRL+C

Cabal/Distribution/Simple/Utils.hs, Cabal/changelog, Cabal/tests/UnitTests/Distribution/Simple/Utils.hs
This implements a compact representation of `[Char]`.
The data is stored internally as UTF8 in an `ShortByteString`
when compiled against `bytestring >= 0.10.4`, and otherwise in a
(strict) `ByteString`.
=> Add `Distribution.Simple.Utils.ShortText` type

Cabal/Distribution/Simple/Utils.hs, cabal-install/Distribution/Client/CmdBuild.hs, cabal-install/Distribution/Client/CmdConfigure.hs, cabal-install/Distribution/Client/CmdRepl.hs, cabal-install/Distribution/Client/InstallPlan.hs, cabal-install/Distribution/Client/ProjectBuilding.hs, cabal-install/Distribution/Client/ProjectBuilding/Types.hs, cabal-install/Distribution/Client/ProjectOrchestration.hs, cabal-install/Distribution/Client/ProjectPlanOutput.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/cabal-install.cabal, cabal-install/tests/IntegrationTests2.hs
This is a bunch of changes leading up to adding better support for tracking the status of the project, which leads on to maintaining a .ghc.environment and other similar outputs.
So this is mostly about rearranging things in the project orchestration and the modules it touches.
=> Project orchestration preparatory work

Cabal/Distribution/Utils/ShortText.hs
Fixes bootstrapping by GHC build system.
CC @hvr
=> Handle the case when min-version binary macro is not defined.

Cabal/Distribution/InstalledPackageInfo.hs
sep allows for horizontal separation, which is absolutely
not what we want.  Use hcat instead.  Thanks @stepcut
for reporting.
I'd like this to merge to 1.24 too, if the bug is present there.
=> Fix reexported-modules display mangling.

Cabal/Distribution/Simple/Utils.hs
It seems that GHC HEAD is now unable to infer the correct
type for "f . g" when g has a higher-rank type.  So eta-expand
all such occurrences to keep the build working.
=> GHC 8.1 compatibility fixes.

cabal-install/Distribution/Client/Install.hs
In 9e99b3f49911028edc1c2be8152002a6a3b7ad3c I turned of executable
solving for legacy configure, but I forgot to turn it off for legacy
install too, which lead to assertion failures.
Fixes #3912.
=> Don't solve for executables in legacy install codepath.

cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/QuickCheck.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs
I added some unit tests while trying to reproduce a bug.
I also had to change the solver DSL so that it no longer enables all packages' tests by default.  I added a function (mkTestEnableAllTests) to enable tests in the existing unit tests that relied on that behavior.
=> Add unit tests for solver stanza preferences.

cabal-install/Distribution/Client/Utils.hs, cabal-install/cabal-install.cabal, cabal-install/tests/IntegrationTests/custom/custom_dep.sh, cabal-install/tests/IntegrationTests/custom/plain.err, cabal-install/tests/IntegrationTests/custom/plain.sh, cabal-install/tests/IntegrationTests2.hs, cabal.project, travis-script.sh
=> cabal.project: Add a constraint on unix.

cabal-install/Distribution/Client/Config.hs
Some new users think that the `-- Cabal library version: 1.25.0.0` string is a setting they should uncomment.
=> Make the initial '~/.cabal/config' comment more obvious.

stack.yaml
The hackage-security dependency in stack.yaml (0.5.2.1) is incompatible with what cabal-install requires (>=0.5.2.2). Bumping the version to that lower bound resolves the dependency issue.
=> Fix Stack build

Cabal/tests/UnitTests/Distribution/Version.hs
This definition was both in the module, and in a CPP-conditionally imported other module. This patch removes this redundancy.
In the normal Cabal build this was not an issue, since it uses a newer version of QuickCheck. The Stack-based build however still uses an old one, which lead to both the import as well as the local definition from being in the code. The testsuite would then fail with a duplicate definition error.
Resolves haskell/cabal#3950
=> Remove duplicate definition of adjustSize

Cabal/Distribution/Simple/Configure.hs, cabal-install/Distribution/Client/Setup.hs, cabal-install/cabal-install.cabal, cabal-install/changelog
Testing protocol:
```
$ cabal-1.24 sandbox init
$ cabal-1.24 install --enable-profiling -w /opt/ghc/7.4.2/bin/ghc trivia
```
`trivia` depends on `distributive`, which has a Custom build-type.
=> Backport #3873 to the 1.24 branch

Cabal/Distribution/Simple/BuildPaths.hs, Cabal/Distribution/Simple/Haddock.hs, Cabal/Distribution/Simple/Install.hs, Cabal/Distribution/Simple/Setup.hs, cabal-install/Distribution/Client/Config.hs, cabal-install/Main.hs
Testing protocol:
```
$ cabal-1.24 get trivia
$ cd trivia-0.0
$ cabal-1.24 sandbox init
$ cabal-1.24 install --only-dep
$ cabal-1.24 haddock --for-hackage --hyperlink-source
$ file-roller dist/trivia-0.0-docs.tar.gz
```
=> Backport #3452 to the 1.24 branch

Cabal/Distribution/Simple/GHCJS.hs, cabal-install/Distribution/Client/Setup.hs
Same as #3957, but for `master`. Also includes an unrelated formatting patch.
Fixes #3915.
=> D.S.GHCJS.libAbiHash: exclude trailing newline.

cabal-install/Distribution/Solver/Modular/Explore.hs
Encountered during the implementation of #3570.
We used to miss a lot of conflicts during counting in `logBackjump`.
Counting initial conflicts here drastically reduces search time in some
cases.
Not sure whether counting the current conflicts (`cs`) may be even
better than counting the initial conflicts (`initial`) ⇒ Benchmarking by @kosmikus?
=> Fix conflict counting bug

cabal-install/Distribution/Solver/Modular/Solver.hs
The DEBUG_TRACETREE debugging feature of cabal-install
still had a call to 'showVersion' in it, which has been
removed by recent changes to 'Distribution.Version'.
=> Adapt to changes in Distribution.Version.

.travis.yml
Per the comment at [1] it is no longer necessary.
[1] https://github.com/haskell/cabal/pull/3966#discussion_r82519000
=> Remove "allow_failures" from travis configuration

cabal-install/Distribution/Client/GlobalFlags.hs, cabal-install/Distribution/Client/Security/DNS.hs, cabal-install/cabal-install.cabal
This way `cabal` can bootstrap secure repos even if the primary Hackage
instance is currently unreachable, as long as there's at least one
reachable and working secure mirror available.
NB: This new code-path is only used for the initial bootstrap. Once the
repository cache has been bootstrapped, its @mirrors.json@ meta-data is
used instead.
See also https://github.com/well-typed/hackage-security/issues/171
=> Implement DNS-based mirror bootstrap protocol

Cabal/Distribution/Version.hs, Cabal/tests/UnitTests/Distribution/Utils/NubList.hs, Cabal/tests/UnitTests/Distribution/Version.hs
With tests,
as an extra improved `NubList` properties (it had a typo, so added few properties there as well)
=> Show Version returning "mkVersion [...]"

cabal-install/Distribution/Client/ProjectBuilding.hs
This is for paths under $dist/tmp/ where we unpack package source tarballs and build them. This is for packages destined for the store. The names of these tmp dirs don't matter since they're guaranteed to be unique, so we only need short identifiers. So stop using full package names, and put the build artefacts in their own dir, rather than using a dist dir under the src dir.
This is intended to address #3972
=> Reduce path lengths for temp package src and build dirs

Cabal/Distribution/Simple/Configure.hs
If you build a big number of packages, all with
the same extra -I flags, the flags get inherited
by the dependent packages and duplicated.
For big dependency trees it can exceed the
maximum command line length on some systems,
this happened to me with Linux and hoogle 5.
This patch decreases the redundancy by
dropping all but the first occurrence of
an include dir, preserving the semantics,
as they are processed left to right.
=> Dedupe include dirs inherited from dependencies

cabal-install/Distribution/Client/ProjectOrchestration.hs, cabal-install/Distribution/Client/ProjectPlanOutput.hs
We construct a PostBuildProjectStatus which has sets of package ids covering various properties, including:
- out of date
- definitely up to date
- probably up to date
- invalid due to dep changes
- invalid due to direct build failure
We also persistently keep track of the "probably up to date" set between builds.
In this patch we just calculate and maintain these things but don't yet use them except for debug output. The idea is it should be useful for things like maintaining the .ghc.environment, deleting stale build dirs or package registrations, maintaining exe wrapers/symlinks etc.
=> Initial impl of maintaining project build status

Cabal/Distribution/Simple/GHC.hs, Cabal/Distribution/Simple/GHC/ImplInfo.hs, Cabal/Distribution/Simple/GHC/Internal.hs, cabal-install/Distribution/Client/ProjectOrchestration.hs, cabal-install/Distribution/Client/ProjectPlanOutput.hs
New version of the ghc environments stuff, now based on the project build status infrastructure. This makes the implementation simpler and should also be much more accurate and useful.
What this really needs is testing with ghc-8.0.2. There's only so much I can do with looking at what the output would look like for older ghc versions.
Ignore the first patch, it's covered by PR #3920.
=> GHC environments (v2)

.travis.yml, travis-solver-debug-flags.sh
The job should detect issues like #3967.
=> Add Travis job to build cabal with solver debug flags enabled.

Cabal/Distribution/Simple/GHC.hs
Unfortunately, "native" GHC advertises support for `JavaScriptFFI` even though
it doesn't support it. See also https://ghc.haskell.org/ticket/11214 for respective
bug.
However, in order to properly declare that packages require `JavaScriptFFI` support
via `other-extensions` we need to fixup the list of extensions fed to the cabal solver.
This patch does something similiar to the workaround we added some time ago to
filter out TemplateHaskell for older GHCs which didn't properly advertise
`TemplateHaskell` availability (c.f. 9f68eb4455808ea9dd9adc5a59b5ebee52a02de8)
=> Workaround GHC #11214 by filtering JavaScriptFFI

.travis.yml, Cabal/tests/PackageTests/Tests.hs, travis-install.sh, travis-script.sh
This increases our test coverage for using Cabal with GHC 7.0, 7.2
and HEAD.
=> Re-enable Travis testing other versions of GHC.

Cabal/Distribution/Simple/SrcDist.hs, cabal-install/Distribution/Client/FileMonitor.hs, cabal-install/Distribution/Client/ProjectBuilding.hs, cabal-install/Distribution/Client/RebuildMonad.hs, cabal-install/Distribution/Client/SourceFiles.hs, cabal-install/cabal-install.cabal
For non-Custom packages, replace sdist with hand-rolled rebuild checking.
New module Distribution.Client.SourceFiles implements
'needElaboratedConfiguredPackage', which if run in the 'Rebuild'
monad is sufficient to ensure all source files that participate
in a build are monitored.
Fixes #3401.  It also fixes the "we didn't detect a new file
appearing" problem.
=> For non-Custom packages, replace sdist with hand-rolled rebuild checking

cabal-install/Distribution/Client/CmdFreeze.hs
We sometimes have to union constraints from different places, but we should simplify those before rendering so we don't add needless redundancy like "aeson-pretty ==0.8.1 || ==0.8.1". So we just use
simplifyVersionRange after unioning things.
Fixes #4002
=> Avoid generating redundant constraints in new-freeze

.travis.yml, travis-common.sh
if osx build is too slow, it will cut it down, making the cache populate. So restarting the job would help!
=> Timer osx pr

Cabal/Distribution/InstalledPackageInfo.hs, Cabal/Distribution/Simple/Build/PathsModule.hs, Cabal/Distribution/Simple/Compiler.hs, Cabal/Distribution/Simple/Configure.hs, Cabal/Distribution/Simple/GHC/IPI642.hs, Cabal/Distribution/Simple/Install.hs, Cabal/Distribution/Simple/InstallDirs.hs, Cabal/Distribution/Simple/LocalBuildInfo.hs, Cabal/Distribution/Simple/Register.hs, Cabal/Distribution/Simple/Setup.hs, Cabal/doc/developing-packages.markdown, Cabal/doc/installing-packages.markdown, cabal-install/Distribution/Client/Setup.hs
--dynlibdir indicates the directory in which dynamic libraries
are installed. By default this setting is equal to:
$libdir/$abi
The static libraries will still end up in:
$libdir/$libsubdir
With $libsubdir/$abi as the default directory for dynamic
libraries, dynamic libraries will by default end up in a
single shared directory (per package database). This has the
potential to reduce start-up times for dynamically linked
executable as only one RPATH per package database will be
needed.
This commit uses the functionality defined in
https://phabricator.haskell.org/D2611
to tell GHC's > 8.0.1 package database that dynamic libraries
are copied to the directories mentioned in the
`dynamic-library-dirs`
field.
=> Backport "Add `--dynlibdir`" to 1.24

Cabal/Distribution/InstalledPackageInfo.hs, Cabal/Distribution/Simple/Build/PathsModule.hs, Cabal/Distribution/Simple/Compiler.hs, Cabal/Distribution/Simple/Configure.hs, Cabal/Distribution/Simple/GHC/IPI642.hs, Cabal/Distribution/Simple/Install.hs, Cabal/Distribution/Simple/InstallDirs.hs, Cabal/Distribution/Simple/LocalBuildInfo.hs, Cabal/Distribution/Simple/Register.hs, Cabal/Distribution/Simple/Setup.hs, Cabal/doc/developing-packages.rst, Cabal/doc/installing-packages.rst, Cabal/tests/PackageTests/Tests.hs, cabal-install/Distribution/Client/Setup.hs
`--dynlibdir` indicates the directory in which dynamic libraries
are installed. By default this setting is equal to:
`$libdir/$abi`
The static libraries will still end up in:
`$libdir/$libsubdir`
With `$libsubdir/$abi` as the default directory for dynamic
libraries, dynamic libraries will by default end up in a
single shared directory (per package database). This has the
potential to reduce start-up times for dynamically linked
executable as only one RPATH per package database will be
needed.
=> Add `--dynlibdir`

cabal-install/Distribution/Client/ProjectBuilding.hs
Packages like `alex` include pre-generated lexer/parser source
in their source tarball as e.g.
dist/build/alex/alex-tmp/Scan.hs
dist/build/alex/alex-tmp/Parser.hs
to avoid having to have alex already installed before building
alex...
Unfortunately, 8dc39db73dc40e3ca84116f6915ff8d1cc78f584 broke
packages relying on this accidental feature by changing where the
distdir points to. This patch partly reverts that commit and
therefore addresses the regression aspect of #4009.
=> Fix install of packages bundling generated source in dist/

cabal-install/Distribution/Client/InstallPlan.hs, cabal.project
It turns out that the install plan elaboration is constructing cyclic plans in some cases. The effect is that executing the plan simply misses out anything that depends on the packages involved in the cycle. This is probably the cause of #3996
With this patch such cases will fail with an assertion such as:
internal error in InstallPlan.fromSolverInstallPlanWithProgress:
The following packages are involved in a dependency cycle
hspec-discover-2.3.1-da63d0b4e952e7949a113646e4af0aac925a4d864a1db650..
The cause is clearly in the caller of `fromSolverInstallPlanWithProgress` and the only caller of that is `ProjectPlanning.elaborateInstallPlan`. The problem appears to be to do with the intra-package dependencies. The hspec-discover-2.3.1 example is one where it has a lib and an exe and the exe …
=> Add InstallPlan invariant assertion checking, revealing cyclic dep problem

cabal-install/Distribution/Client/ProjectPlanning.hs
In the old code, we assumed that only libraries could get
installed, but with executable dependencies this is no
longer true.  Handle it correctly.
This bug caused cycles in the elaborated install plan which
could cause dependency closure to fail, resulting in
weird errors.
Fixes #3996.
CC @dcoutts
=> Allocate different ComponentId for lib and exe.

cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/cabal-install.cabal, cabal-install/tests/IntegrationTests/new-build/T3978.err, cabal-install/tests/IntegrationTests/new-build/T3978.sh, cabal-install/tests/IntegrationTests/new-build/T3978/cabal.project, cabal-install/tests/IntegrationTests/new-build/T3978/p/p.cabal, cabal-install/tests/IntegrationTests/new-build/T3978/q/q.cabal
When a library/executable is unbuildable, the solver may still
return a reference to it.  Handle this gracefully in ProjectPlanning
with a nice error message, rather than an assert failure.
Fixes #3978.
=> Do an early check for unbuildable deps, and give good error.

Cabal/Distribution/Compat/CreatePipe.hs, Cabal/Distribution/Simple/InstallDirs.hs, cabal-install/Distribution/Client/InstallSymlink.hs, cabal-install/Distribution/Client/SetupWrapper.hs, cabal-install/Distribution/Client/Win32SelfUpgrade.hs
The code had a mixtire of `#ifdef mingw32_HOST_OS` and `#if`. The later
works but is not really correct. GHC HEAD has just got a new warning flag
`-Wcpp-undef` which will warn on `#if` used with an undefined identifier.
Since we want to turn that on in the GHC build system we need to fix cabal
first.
=> Fix CPP usage

cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/QuickCheck.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs
Three commits:
This commit modifies the tests so that they disable executables instead of
libraries.  Disabling executables with `Buildable: False` is a more realistic
test case.
See #3988.
Previously, the solver DSL ignored some types of dependencies when they appeared
in executables or under flags. This commit uses one function, mkBuildInfoTree,
to create all BuildInfos, so that any dependency can be used in any location.
The checks might detect some errors in the DSL. The commit also adds non-default
values to some fields to make the checks pass, such as adding a default-language
to each component.
Related to #3784
/cc @ezyang 
I don't know if you need the first commit for #3988, since #4023 was merged, but I still think it's an improvement.
=> Solver DSL improvements

Cabal/Distribution/PackageDescription/Check.hs
This causes filepath to not validate, which means GHC build doesn't
work. Annoying. Let's not for 8.0 series.
This reverts commit 0b458361e7a1af485e74354bad74b8ae02e0f5f4.
=> Revert "D.PD.Check: extra-doc-files only allowed when Cabal >= 1.18."

Cabal/misc/gen-extra-source-files.hs
Without a package qualified import, runhaskell will attempt to
load all of Cabal from source, because the files happen to
be named in the same way as the import requests.  That leads
to very slow runtimes.
Fixes #4007.
CC @phadej
=> Force gen-extra-source-files to use pre-installed library.

Cabal/Distribution/Backpack/ConfiguredComponent.hs, Cabal/Distribution/PackageDescription/Check.hs, Cabal/Distribution/Simple/Configure.hs, Cabal/changelog, Cabal/tests/PackageTests/Tests.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/cabal-install.cabal, cabal-install/tests/IntegrationTests/new-build/T4017.sh, cabal-install/tests/IntegrationTests/new-build/T4017/cabal.project, cabal-install/tests/IntegrationTests/new-build/T4017/p/p.cabal, cabal-install/tests/IntegrationTests/new-build/T4017/q/q.cabal
In #4017, hvr reported that when he used --allow-older/--allow-newer,
there was an assert failure in toConfiguredComponent.  Indeed
the problem was that toConfiguredComponent was testing version
ranges of build-depends to determine which package to select, but
there was no satisfying one (since the build-depends field had
not been updated.)
After thinking about this for a bit, it seemed a bit bogus for
us to be doing another version check at this late phase; we
already picked dependencies earlier in the configuration process.
So I decided to drop it.
To drop it, however, I needed to remove support for a feature (discussed
in #4020), which uses version ranges to disambiguate whether or not a
dependency is on an external package or an internal package.  This
feature doesn't seem to be very …
=> Drop version check when resolving package names.

cabal-install/Distribution/Client/BuildTarget.hs, cabal-install/bootstrap.sh, cabal-install/cabal-install.cabal
This implements the changes identified in PR #3969.
@ezyang @23Skidoo @dcoutts 
I even tested it:
```sh
cabal new-build thing
cabal: Unknown build target 'thing'.
There is no component 'thing'.
Perhaps you meant the component 'thing1' or 'thing2' or 'thing3'?
The project has no package 'thing'.
```
=> Better error messages

cabal-install/Distribution/Client/CmdHaddock.hs, cabal-install/Main.hs, cabal-install/cabal-install.cabal
I believe this should be a reasonable first cut at the implementation of `new-haddock`. Of course, like `new-install` it's quite unclear where the resulting artifacts should be placed.
=> [WIP] Skeleton of new-haddock

Cabal/Cabal.cabal, Cabal/Distribution/Simple/LocalBuildInfo.hs, Cabal/tests/PackageTests/Regression/T4025/A.hs, Cabal/tests/PackageTests/Regression/T4025/T4025.cabal, Cabal/tests/PackageTests/Regression/T4025/exe/Main.hs, Cabal/tests/PackageTests/Tests.hs
In 1.24, installedPkgs contained only references to the external package
database, not any internal libraries. In particular, when we built a
dynamically linked executable, installedPkgs did NOT have a reference to
the internal library; instead, depLibraryPaths has a special case
(hasInternalDeps) to add the final libdir to the RPATH.
In HEAD, after 0d15ede, we started adding internal libraries (with the
INPLACE registrations) to installedPkgs to fix #2971.  But depLibraryPaths
was not updated, which means that the inplace registrations got picked
up and added to the RPATH, resulting in bad temporary directories
showing up in RPATHs.
In this commit, we just filter out internal entries from installedPkgs
and compute the library dirs for them from scratch (this code already
existed, so no …
=> Don't use installedPkgs for internal library library dirs.

Cabal/Distribution/ParseUtils.hs
Is this an intentional inconsistency with the old parser? Compare with the endpoints of https://github.com/haskell/cabal/blob/master/Cabal/Distribution/ParseUtils.hs#L630-L658
CC @phadej
=> parsec: Fix inconsistency and allow parse quoted-versions for build-tools

Cabal/Distribution/Simple/Configure.hs, cabal-testsuite/PackageTests/ForeignLibs/Check.hs, cabal-testsuite/PackageTests/ForeignLibs/my-foreign-lib.cabal, cabal-testsuite/PackageTests/ForeignLibs/src/MyForeignLib/AnotherVal.hs, cabal-testsuite/PackageTests/ForeignLibs/src/MyForeignLib/Hello.hs, cabal-testsuite/PackageTests/Tests.hs, cabal-testsuite/cabal-testsuite.cabal
This is supposed to test if a foreign library can depend on Haskell code in the same project but in a different binary object.
=> Add test for foreign libs to depend on Haskell libs

Cabal/Cabal.cabal, Cabal/Distribution/Backpack/ComponentsGraph.hs, Cabal/Distribution/Backpack/ConfiguredComponent.hs, Cabal/Distribution/InstalledPackageInfo.hs, Cabal/Distribution/Package.hs, Cabal/Distribution/Package/TextClass.hs, Cabal/Distribution/PackageDescription/Parse.hs, Cabal/Distribution/PackageDescription/Parsec/FieldDescr.hs, Cabal/Distribution/ParseUtils.hs, Cabal/Distribution/Parsec/Class.hs, Cabal/Distribution/Simple/Build.hs, Cabal/Distribution/Simple/Configure.hs, Cabal/Distribution/Simple/Setup.hs, Cabal/Distribution/Types/BuildInfo.hs, cabal-install/Distribution/Client/PackageHash.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Client/ProjectPlanning/Types.hs, cabal-install/Distribution/Client/World.hs, cabal-install/Distribution/Solver/Modular/Assignment.hs, cabal-install/Distribution/Solver/Modular/Dependency.hs, cabal-install/Distribution/Solver/Modular/IndexConversion.hs, cabal-install/Distribution/Solver/Modular/Package.hs, cabal-install/Distribution/Solver/Modular/Validate.hs, cabal-install/Distribution/Solver/Types/PkgConfigDb.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL.hs
This is a follow-up to https://github.com/haskell/cabal/pull/4057, so until that is dealt with this diff will also be humongous and unreviewable.
This PR makes separate types for different types of dependencies:
- `Dependency` is now just for regular (usually library) dependencies on haskell packages
- `LegacyExeDependecy` for legacy `build-tools` dependencies 
- `PkgconfigDependecy` for pkg-config dependencies
Additionally, there is a newtype `PkgconfigName` for pkg-config library names. For Cabal's uses alone this wouldn't be worth it, but cabal-install already distinguishes these libraries widely with `PackageName`. Continuing to use `PackageName` seemed inconsistent with the newly-rigorous use of `Dependecy`, while going back to `String` seemed like a step backwards.
Plain `String` is …
=> Make more dependency types

cabal-install/Distribution/Client/CmdBuild.hs, cabal-install/Distribution/Client/CmdConfigure.hs
So that exes and other unnecessary components in dependencies are ignored.
Before:
```
$ cabal new-configure
In order, the following would be built (use -v for more details):
- Crypto-4.2.5.1 (exe:SymmetricTest) (requires build)
- Crypto-4.2.5.1 (exe:WordListTest) (requires build)
- Crypto-4.2.5.1 (exe:SHA1Test) (requires build)
- Crypto-4.2.5.1 (exe:QuickTest) (requires build)
- Crypto-4.2.5.1 (exe:RSATest) (requires build)
- Crypto-4.2.5.1 (exe:HMACTest) (requires build)
- HaXml-1.25.3 (exe:Xtract) (requires build)
- HaXml-1.25.3 (exe:Validate) (requires build)
- HaXml-1.25.3 (exe:MkOneOf) (requires build)
- HaXml-1.25.3 (exe:CanonicaliseLazy) (requires build)
- HaXml-1.25.3 (exe:Canonicalise) (requires build)
- HaXml-1.25.3 (exe:XsdToHaskell) (requires build) …
```
=> new-configure: Select the same plan subset as new-build.

Cabal/Cabal.cabal, Cabal/Distribution/InstalledPackageInfo.hs, Cabal/Distribution/Simple/Compiler.hs, Cabal/Distribution/Simple/Configure.hs, Cabal/Distribution/Simple/Program/Db.hs, Cabal/Distribution/Simple/Program/Types.hs, Cabal/Distribution/Types/ComponentName.hs, Cabal/Distribution/Utils/BinaryWithFingerprint.hs, Cabal/Distribution/Utils/NubList.hs, cabal-install/Distribution/Client/FileMonitor.hs, cabal-install/Distribution/Client/InstallPlan.hs, cabal-install/Distribution/Client/PackageHash.hs, cabal-install/Distribution/Client/ProjectConfig/Types.hs, cabal-install/Distribution/Client/ProjectPlanOutput.hs, cabal-install/Distribution/Client/ProjectPlanning/Types.hs, cabal-install/Distribution/Client/RebuildMonad.hs, cabal-install/Distribution/Client/SolverInstallPlan.hs, cabal-install/Distribution/Client/Types.hs, cabal-install/Distribution/Solver/Types/OptionalStanza.hs, cabal-install/Distribution/Solver/Types/PkgConfigDb.hs, cabal-install/Distribution/Solver/Types/SourcePackage.hs, cabal-install/tests/UnitTests/Distribution/Client/FileMonitor.hs
The idea is we can use Rep to get a full, structural representation
of a type, and the fingerprint it using Typeable.  This gives
us a very concise way of fingerprinting our Binary representation.
This patch is not completely correct; the fingerprint needs
to be overridable when someone writes a custom Binary instance.
But this should be "good enough" in practice; we're not using
these fingerprints to check anything security critical.
TODO: Not sure if I have tagged all the call-sites which could
profit from this.
Fixes #4059.
=> Add fingerprint of Generic representation when serializing.

Cabal/Distribution/Simple/Utils.hs, Cabal/Distribution/Verbosity.hs, cabal-install/Distribution/Client/ProjectOrchestration.hs
Unfortunately, propagating the `Verbosity` to the `topHandler`
proves to be more complicated.
This is mostly a problem for `die` invocations which are translated
into user-error exceptions (which in turn then cause callstacks
to be printed; are we abusing `die`?)
=> Implement +nowrap verbosity flag to suppress log-msg line-wrapping

cabal-install/Distribution/Client/Compat/Process.hs
Closes #1613.  See the discussion there.
=> D.C.Compat.Process.readProcessWithExitCode: also catch permission errors

cabal-testsuite/PackageTests.hs, cabal-testsuite/PackageTests/PackageTester.hs
Now that cabal-testsuite uses a Custom setup, we can assume
that we are able to read the LBI from our build.  This is good
news, because the old algorithm didn't really work at all
(and stopped working with cabal-install-1.24.0.1)
Fixes #4108.
=> Assume LocalBuildInfo is available in cabal-testsuite.

Cabal/Distribution/Simple/Configure.hs
See #3974. The same problem also affects the inherited library directories.
=> Deduplicate library directory arguments when testing libraries

Cabal/Distribution/PackageDescription/Configuration.hs, cabal-testsuite/PackageTests/Tests.hs
The `addBuildableCondition` function was added to solve the problem with "buildable: False". The problem was that we would solve or check dependencies on the basis of the component in question being needed, and then at the end discover that the component is actually not buildable at all, and if we'd known that up front we would not have solved for the component's dependencies.
The trick that `addBuildableCondition` does is a syntactic transformation, from components like:
```
executable blah
buildable: False
build-depends: foo >= 1, bar < 2
something-else: whatever
```
to:
```
executable blah
-- empty!
```
Or at least, that's the intention. In the above situation the implementation of `addBuildableCondition` returns an empty `CondNode`:
```
CondNode mempty mempty []
```
The type at which …
=> Fix implementation of addBuildableCondition

cabal-install/bootstrap.sh
otherwise a local Cabal 1.24.0.0 will cause build failure
```
Distribution/Client/Setup.hs:76:40: error:
Module
‘Distribution.Simple.Configure’
does not export
‘computeEffectiveProfiling’
```
due to haskell/cabal@fbfc811.
=> bootstrap.sh: bump 1.24's minimum Cabal to 1.24.1

cabal-install/cabal-install.cabal, cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL/TestCaseUtils.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs
This commit moves the utility functions from UnitTests.Distribution.Solver.Modular.Solver to a new module, UnitTests.Distribution.Solver.Modular.DSL.TestCaseUtils.
I'm planning to use these functions in a performance test for #4110.
=> Move functions for creating solver HUnit test cases into a new module.

Cabal/doc/developing-packages.rst, cabal-install/Distribution/Client/Get.hs, cabal-install/Distribution/Client/Setup.hs, cabal-install/changelog
With this `cabal get` gains the ability to
a) unpack and update with the .cabal revision which was
active at the given index-state, as well as
b) allow to unpack the most recent package version
(while satisfying imposed version constraints) as of
the given index-state
The `--index-state` flag can be combined with `--pristine` if only b) is
desired.
=> Add `--index-state` support to `cabal get`

Cabal/Cabal.cabal, Cabal/Distribution/PackageDescription/Configuration.hs, Cabal/changelog, Cabal/tests/PackageTests/BuildTargetErrors/BuildTargetErrors.cabal, Cabal/tests/PackageTests/BuildTargetErrors/Main.hs, Cabal/tests/PackageTests/Tests.hs
I added an entry to the changelog, but I'm not sure if the version is correct.  Will there be a Cabal 1.24.1.1?  I also had to copy the test for this issue in a separate commit.
=> Cherry-pick #4094 onto 1.24.

appveyor.yml, cabal-install/Distribution/Solver/Modular/Explore.hs, cabal-install/Distribution/Solver/Types/Progress.hs, cabal-install/cabal-install.cabal, cabal-install/tests/MemoryUsageTests.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL/TestCaseUtils.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/MemoryUsage.hs, travis-script.sh
The new test suite uses the solver DSL and is built with `-with-rtsopts=-M4M`.  I think this is a better way to check for space leaks than using the cabal executable, because it isolates the solver and uses simpler packages.  Here's an example where I introduced a space leak by removing the bang patterns on the Int parameter in https://github.com/haskell/cabal/blob/e496b09eb3e9d15ca3380155a85c9a5c7a3587d5/cabal-install/Distribution/Solver/Modular/Message.hs#L54:
Solver DSL (There are three tests, because I used PR #4110.)
cabal executable
I also had to fix two space leaks to make the tests pass.  One occurs when the solver always has exactly one choice for the next goal.  The other is caused by a bug in GHC 7.6.3.
=> Add test suite with two basic tests for solver space leaks.

cabal-install/Distribution/Client/Exec.hs, cabal-install/Distribution/Client/Install.hs, cabal-install/cabal-install.cabal, cabal-install/tests/IntegrationTests.hs, cabal-install/tests/IntegrationTests/exec/T4049.sh, cabal-install/tests/IntegrationTests/exec/T4049/UseLib.c, cabal-install/tests/IntegrationTests/exec/T4049/csrc/MyForeignLibWrapper.c, cabal-install/tests/IntegrationTests/exec/T4049/my-foreign-lib.cabal, cabal-install/tests/IntegrationTests/exec/T4049/src/MyForeignLib/Hello.hs, cabal-install/tests/IntegrationTests/exec/T4049/src/MyForeignLib/SomeBindings.hsc
See #4049
Adding the sandbox lib dir means that foreign libraries are found by random executables after installing those foreign libraries, even if they are installed to the sandbox. Without this, LD_LIBRARY_PATH needs to be set manually if using sandboxes.
=> Add sandbox lib dir to environment during cabal exec

cabal-install/Distribution/Client/ProjectPlanOutput.hs
As a fix for #4010 is nowhere in sight, I'm taking the initiative to disable this feature until we have a fix.
=> Disable environment files due to #4010.

Cabal/Distribution/PackageDescription/Parse.hs, Cabal/Distribution/PackageDescription/Parsec/FieldDescr.hs, Cabal/Distribution/Parsec/Class.hs, Cabal/Distribution/Simple/Configure.hs, Cabal/Distribution/Simple/GHC.hs, Cabal/Distribution/Types/ForeignLib.hs, Cabal/doc/developing-packages.rst, cabal-testsuite/PackageTests/ForeignLibs/my-foreign-lib.cabal, cabal-testsuite/PackageTests/ForeignLibs/setup.test.hs
=> Foreign library versioning

cabal-install/bootstrap.sh
Cabal-1.18 in ghc-7.8 does not support -j
=> bootstrap.sh: do not use -j on ghc-7.8

cabal-install/Distribution/Solver/Modular/PSQ.hs, cabal-install/Distribution/Solver/Modular/Preference.hs, cabal-install/Distribution/Solver/Modular/Solver.hs
Previously, the solver applied goal-ordering heuristics by removing all
non-preferred goal choices when there was at least one preferred choice. This
left fewer goals for later steps, such as conflict counting, to work with.
This commit changes the heuristics so that they only sort the goals. I didn't
change the `preferBaseGoalChoice` heuristic, though, because it made the solver
slower in some cases. I also think that it is safe to always choose the version
of base first, because there is usually only one choice anyway.
I reversed the order of the heuristics, because sorting gives the most weight to
the last step, and pruning gives the most weight to the first step. The solver's
behavior should be unchanged with --no-count-conflicts.
/cc @kosmikus
This change is related to #3488.
I was …
=> Solver: Avoid removing goal choices from the tree when applying heuristics.

cabal-install/Distribution/Solver/Modular/Explore.hs
`simplifyVar` removes flag names from the `Var` type, so that all flags within a
package are treated as one during backjumping. A more complete fix would involve
creating a `SimpleVar` type.
The bug caused the conflict counting heuristic to never prefer flag goals. Flag
variables in the tree's goals had the flags' original names, and the flag
variables in the conflict map did not have names, so they could never be equal.
Since this fix changes the goal order, I wanted to test for an unexpected large
negative impact on solver runtime. I ran the solver on all packages on Hackage
individually with GHC 8.0.1 and looked for differences of more than 10% between
master and the branch. There were twelve packages. I reran those packages three
times and found ten with a significant difference in …
=> Solver: Add missing call to 'simplifyVar'.

Cabal/Distribution/Simple/BuildTarget.hs, cabal-install/Distribution/Client/BuildTarget.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/QuickCheck.hs
=> Add some missing occurrences of flib in cabal-install.

cabal-install/Distribution/Solver/Modular/Builder.hs, cabal-install/Distribution/Solver/Modular/Linking.hs, cabal-install/Distribution/Solver/Modular/Solver.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/MemoryUsage.hs
The solver creates linked nodes by copying existing unlinked nodes. Previously,
the subtrees shared data, which caused a space leak. This commit combines the
"build" and "addLinking" tree traversals so that the nodes are copied before
they are expanded into full trees.
This should prevent sharing more reliably than my previous PR, #3530.
I'd like to add a regression test, but I'm not sure how to do it without significantly lengthening the build.  I wrote a test with the solver DSL (https://github.com/grayjay/cabal/commit/1f1b95d7b4d836ac79a60f943bb36e0ac6ef41e8) that fails when I limit the heap size.  Do you think we should add another test suite that we run with a limited heap?  I can't add the test to the existing unit test suite, because some of the quickcheck tests already cause …
=> Solver: Fix space leak in 'addlinking' (issue #2899).

Cabal/Cabal.cabal, Cabal/Distribution/Simple/BuildPaths.hs, Cabal/Distribution/Simple/Haddock.hs, Cabal/Distribution/Simple/Install.hs, Cabal/Distribution/Simple/Setup.hs, Cabal/changelog, Cabal/doc/index.markdown, cabal-install/Main.hs, cabal-install/bootstrap.sh, cabal-install/cabal-install.cabal
=> Bring back old types of {hscolour,haddock}Pref and haddockForHackage.

cabal-install/Distribution/Solver/Modular/ConflictSet.hs, cabal-install/Distribution/Solver/Modular/Dependency.hs, cabal-install/Distribution/Solver/Modular/Explore.hs, cabal-install/Distribution/Solver/Modular/Log.hs
Pull request for #3570.
The final confilct set is printed along with the conflict count of each conflict, if available.
Open for discussion:
- The original error message is thrown away, we currently only show the conflilct set. Should we restore it and print both?
- The conflict count is not actually a useful metric. Should we expose it, or should we rescale it to something more useful to the user?
=> Print final conflict set when search is exhaustive

cabal-install/Distribution/Solver/Modular/Assignment.hs, cabal-install/Distribution/Solver/Modular/ConflictSet.hs, cabal-install/Distribution/Solver/Modular/Cycles.hs, cabal-install/Distribution/Solver/Modular/Dependency.hs, cabal-install/Distribution/Solver/Modular/Explore.hs, cabal-install/Distribution/Solver/Modular/Linking.hs, cabal-install/Distribution/Solver/Modular/Log.hs, cabal-install/Distribution/Solver/Modular/Message.hs, cabal-install/Distribution/Solver/Modular/Preference.hs, cabal-install/Distribution/Solver/Modular/Solver.hs, cabal-install/Distribution/Solver/Modular/Tree.hs
This is a cleanup after #3960.
The parameter in `ConflictSet qpn` is only ever used with `QPN`, so the parametricity does not really make sense. Also, with #3960 the `ConflictMap` is exposed a bit more, and although `ConflictSet` and `ConflictMap` are very similar in their usage, one is parameterized over `qpn` and the other is not.
=> Migrate ConflictSet qpn ↦ ConflictSet

Cabal.nix, Cabal/doc/index.rst, Cabal/doc/nix-integration.rst, cabal-install.nix, cabal-install/Distribution/Client/Config.hs, cabal-install/Distribution/Client/GlobalFlags.hs, cabal-install/Distribution/Client/Nix.hs, cabal-install/Distribution/Client/ProjectConfig/Legacy.hs, cabal-install/Distribution/Client/Reconfigure.hs, cabal-install/Distribution/Client/Setup.hs, cabal-install/Main.hs, cabal-install/cabal-install.cabal, cabal-install/changelog, default.nix
These commits add Nix integration to `cabal-install`. If the global `--enable-nix` option is specified and a `shell.nix` file exists, `cabal` will run the affected commands in a `nix-shell` instance.
=> Nix integration

cabal-install/Distribution/Solver/Modular/Explore.hs
This reverts commit adc1fe96e06a652f798c7f1ed62b60b9809df383.
See #4152.
=> Revert "Solver: Add missing call to 'simplifyVar'."

Cabal/Distribution/Simple/Program/Strip.hs
I'm weird person, and sometimes use `POSIX_CORRECTLY`:
```
/usr/bin/strip: '--strip-unneeded': No such file
```
=> Have path as the last argument

Cabal/Distribution/InstalledPackageInfo.hs, Cabal/Distribution/Simple/Build.hs, Cabal/Distribution/Simple/GHC/IPI642.hs, Cabal/Distribution/Simple/Register.hs
Last two commits only.
GHC will make use of this to do more accurate shadowing computation,
because now we can tell if something is ABI-compatible, even if the 'id'
matches.
=> New 'abi-depends' field which tracks 'depends' plus 'abi'

Cabal/Distribution/PackageDescription/Check.hs
This PR contains an update to cabal check:
Since `-auto-all` is an alias for `-fprof` flag, then the `PackageDistSuspicious` warning should mention `ghc-prof-options` as well.
fixes #3718
=> adding ghc-prof-options to fprof warning

cabal-install/Distribution/Client/ProjectBuilding.hs, cabal-install/Distribution/Client/ProjectPlanning.hs
cabal-version semantics prior to 1.8 joined all `build-depends`;
as suggested by @ezyang it's easier for now to just fallback to
legacy mode, than to add proper support for per-components builds
for ancient cabal-spec versions
Fixes #4121
=> Disable per-components mode for cabal-spec version < 1.8

cabal-install/Distribution/Client/Upload.hs, cabal-install/bootstrap.sh, cabal-install/cabal-install.cabal
The `echo` library implements a cross-console way to disable input echoing while performing an action (like entering one's password). It requires a surprising amount of scaffolding to make it work on Windows, so it's probably best to keep it as a separate library that's maintained outside of `cabal-install`.
Fixes #4128.
=> Depend on echo to fix #4128

cabal-install/Distribution/Client/Dependency.hs, cabal-install/Distribution/Solver/Modular/Solver.hs
65e9b88bc849e76040ed7947591ea7172cd02db5 made template-haskell non-upgradable
65ae95c191b19ec1884a4d80afbdaba9c3d477d1 made it upgradable again
...and this commit makes it non-upgradable again
While there may be a few cases when `template-haskell` can be
reinstalled, it's generally not advisable, and causes more harm than the
benefit in the few cases where we'd gain install-plan
flexibility (e.g. when only template-haskell's API is needed for
compile, but no actual TH evaluation takes place).
Closes #4098
=> Mark `template-haskell` non-upgradable (again)

cabal-install/Distribution/Solver/Modular/Builder.hs, cabal-install/Distribution/Solver/Modular/Cycles.hs, cabal-install/Distribution/Solver/Modular/Explore.hs, cabal-install/Distribution/Solver/Modular/Linking.hs, cabal-install/Distribution/Solver/Modular/Preference.hs, cabal-install/Distribution/Solver/Modular/Solver.hs, cabal-install/Distribution/Solver/Modular/Tree.hs, cabal-install/Distribution/Solver/Modular/Validate.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs
Previously, the solver only checked for cycles after it had already found a
solution. That reduced the number of times that it performed the check in the
common case where there were no cycles. However, when there was a cycle, the
solver could spend a lot of time searching subtrees that already had a cyclic
dependency and therefore could not lead to a solution. This is part of
#3824.
Changes in this commit:
- Store the reverse dependency map on all choice nodes in the search tree, so
that 'detectCyclesPhase' can access it at every step.
- Check for cycles incrementally at every step. Any new cycle must contain the
current package, so we just check whether the current package is reachable
from its neighbors.
- If there is a cycle, we convert the map to a graph and find a strongly
connected …
=> Solver: Check for cycles after every step.

Cabal/Cabal.cabal, Cabal/Distribution/Backpack/Configure.hs, Cabal/Distribution/Backpack/ConfiguredComponent.hs, Cabal/Distribution/Backpack/LinkedComponent.hs, Cabal/Distribution/Backpack/ReadyComponent.hs, Cabal/Distribution/Backpack/UnifyM.hs, Cabal/Distribution/Types/ComponentInclude.hs, cabal-install/Distribution/Client/ProjectPlanning.hs
There were a number of fields in 'LinkedComponent' which
were "too" flexible, in that they were fully determined by
other fields in the structure.  This refactor deletes those
fields and replaces them with functions that refer to the
fields directly.
I also introduce a new type, ComponentInclude, to take
the place of tuples which were used to represent includes
(mixins) in Backpack.
There's also more documentation for lots of bits.
=> Refactor Backpack data structures to be less flexible.

cabal-install/Distribution/Client/Dependency.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Solver/Modular/Package.hs, cabal-install/Distribution/Solver/Modular/Preference.hs, cabal-install/Distribution/Solver/Types/ConstraintSource.hs, cabal-testsuite/PackageTests/Regression/T3932/cabal.test.hs
Going along with the existing approach of using a constraint rather than altering the deps of custom Setup.hs scripts, but make the constraint only apply to Cabal instances that are dependencies of Setup.hs scripts not all instances of Cabal.
Also rearrange things a little with a dedicated solver policy function for adding a min dep on Cabal versions for setup scripts.
This is a follow-up to #4051. @ezyang @dagit 
@kosmikus @grayjay could you have a look at my use of `setupPP` and let us know if this will make sure the constraint applies to all setup deps. I'm not quite sure about the linking and whether this will catch all cases of Cabal instances occurring as deps of Setup scripts.
=> Refine the fix for requiring Cabal > 1.20 for Setup.hs

Cabal/default.nix, Cabal/doc/nix-integration.rst, cabal-install/Distribution/Client/Nix.hs, cabal-install/default.nix, default.nix
The Nix expressions for Cabal and cabal-install are updated. Nix expressions are instantiated in a "fake" Nix shell to cope with environment impurities introduced by newer versions of cabal2nix. cabal looks at the `CABAL_IN_NIX_SHELL` environment variable instead of `IN_NIX_SHELL`; it was pointed out that cabal need not care if it is running inside `nix-shell` because we only care if we are running in a shell created by cabal.
=> Nix integration improvements

Cabal/Distribution/Backpack/LinkedComponent.hs, Cabal/Distribution/Backpack/ReadyComponent.hs, Cabal/Distribution/Backpack/UnifyM.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Client/ProjectPlanning/Types.hs
A signature package is a package that contains only signatures but no
modules (equivalently, it is a package that has no provisions.)
Previously, we did not treat signature packages any differently from
normal packages, which, in particular, meant that when we instantiated a
package using a signature package, we also instantiated the signature
package.  This is actually pretty useless, because we never actually use
the instantiated signature (there's no code that actually gets compiled
in this case).
This patch treats signature packages specially, so that we don't
actually instantiate dependencies on them.  This means we have
to compile less packages when handling signatures.  Good!
=> Don't compile signature packages with instantiations.

cabal-install/Distribution/Client/CmdFreeze.hs, cabal-install/Distribution/Client/Configure.hs, cabal-install/Distribution/Client/Dependency.hs, cabal-install/Distribution/Client/Freeze.hs, cabal-install/Distribution/Client/Install.hs, cabal-install/Distribution/Client/List.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Client/Targets.hs, cabal-install/Distribution/Solver/Modular.hs, cabal-install/Distribution/Solver/Modular/Preference.hs, cabal-install/Distribution/Solver/Types/PackageConstraint.hs, cabal-install/Distribution/Solver/Types/PackagePath.hs, cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs, cabal-install/tests/UnitTests/Distribution/Client/Targets.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL.hs
The main changes are:
1. Updated the syntax of qualifiers in PackagePath.hs to use colon as a separator rather than hyphen.
2. Changed PackageName to QPN in PackageConstraint.
3. Added 'UserQualifier' into UserConstraint.
The only difference to the overall behaviour of cabal due to this patch is that qualified constraints will be parsed on the command line. Currently the solver etc. just ignores these qualifiers, however everything should be all set now to make the solver act on them.
One last thing: I'm going to add some new unit tests for the UserConstraint parser, but if it's okay I'll leave that till the next submission to stop this one getting too big.
=> Qualified constraints (issue #3502)

Cabal/doc/nix-local-build.rst, cabal-install/Distribution/Client/Config.hs, cabal-install/Distribution/Client/Dependency.hs, cabal-install/Distribution/Client/Fetch.hs, cabal-install/Distribution/Client/Freeze.hs, cabal-install/Distribution/Client/Install.hs, cabal-install/Distribution/Client/ProjectConfig.hs, cabal-install/Distribution/Client/ProjectConfig/Legacy.hs, cabal-install/Distribution/Client/ProjectConfig/Types.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Client/Setup.hs, cabal-install/Distribution/Solver/Modular/Solver.hs, cabal-install/Distribution/Solver/Types/Settings.hs, cabal-install/changelog, cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL/TestCaseUtils.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/QuickCheck.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs
--install-base-libraries makes cabal ignore the list of packages that cannot be
installed or upgraded.
I haven't added documentation yet.
=> Add flag to allow the dependency solver to install any package (issue #4209).

Cabal/shell.nix, cabal-install/Distribution/Client/Nix.hs, cabal-install/shell.nix
Replaces #4208. We do not actually care about canonicity of paths, but
makeAbsolute is not available in older versions of directory.
=> Remove makeAbsolute

cabal-install/Distribution/Client/CmdFreeze.hs, cabal-install/Distribution/Client/Configure.hs, cabal-install/Distribution/Client/Dependency.hs, cabal-install/Distribution/Client/Freeze.hs, cabal-install/Distribution/Client/Install.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Client/Targets.hs, cabal-install/Distribution/Solver/Modular.hs, cabal-install/Distribution/Solver/Modular/Builder.hs, cabal-install/Distribution/Solver/Modular/ConfiguredConversion.hs, cabal-install/Distribution/Solver/Modular/Dependency.hs, cabal-install/Distribution/Solver/Modular/Package.hs, cabal-install/Distribution/Solver/Modular/Preference.hs, cabal-install/Distribution/Solver/Modular/Solver.hs, cabal-install/Distribution/Solver/Types/PackageConstraint.hs, cabal-install/Distribution/Solver/Types/PackagePath.hs, cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs, cabal-install/tests/UnitTests/Distribution/Client/Targets.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL.hs
This is some further refactoring to address issues discussed in PR #4219
=> Qualified constraints (issue #3502) part 2

Cabal/Distribution/Simple/Haddock.hs
We did parse but did not yet use the --foreign-libraries flag for cabal
haddock.
=> Only build haddock for foreign libraries if requested

Cabal/Distribution/Compat/Prelude.hs, Cabal/Distribution/ModuleName.hs, Cabal/Distribution/Package.hs, Cabal/Distribution/Types/GenericPackageDescription.hs, Cabal/Distribution/Types/UnqualComponentName.hs, Cabal/Distribution/Utils/ShortText.hs, cabal-install/Distribution/Client/Init.hs, cabal-testsuite/cabal-testsuite.cabal, stack.yaml
=> Add IsString instance for ShortText newtypes

Cabal/doc/installing-packages.rst, Cabal/doc/nix-local-build.rst, cabal-install/Distribution/Client/Dependency.hs, cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs, cabal-install/tests/UnitTests/Distribution/Client/Targets.hs
In this PR:
- Non-upgradeable package constraints now use `ScopeAnyQualifier`.
- Added documentation for qualified constraints. I've also refactored the documentation a bit as there was duplication of information between the description of the `--constraint` command line option and the `constraints` field of cabal.project (let me know if any objections to my moving things around).
- Added unit tests for parsing qualified constraints.
@grayjay You asked me before if there is anything else you'll need to do aside from enforcing the constraints in `Distribution.Solver.Modular.Preference`. Mainly just the following:
- I would advise briefly checking all instances where `PackageConstraint` / `UserConstraint` values are constructed and pattern-matched (you can just grep for these identifiers). …
=> Qualified constraints: documentation and unit tests (issue #3502)

Cabal/Distribution/Simple/GHC.hs, Cabal/Distribution/Simple/GHC/ImplInfo.hs, Cabal/Distribution/Simple/GHC/Internal.hs, Cabal/Distribution/Simple/GHCJS.hs, Cabal/Distribution/Simple/Program/GHC.hs
Use `-Wmissing-home-modules` starting from `ghc-8.2.1` when building a library. The relevant Trac issue: https://ghc.haskell.org/trac/ghc/ticket/13129
The idea is to warn user about modules, not listed neither in `exposed-modules`, nor in `other-modules`.
See  #1746 for details.
=> Enable -Wmissing-home-modules when building a library

Cabal/doc/installing-packages.rst, cabal-install/Distribution/Client/Targets.hs, cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs, cabal-install/tests/UnitTests/Distribution/Client/Targets.hs
This commit comments out the part of #4219 that parses build tool dependency
qualifiers, to disable the feature until we finalize the syntax. It also comments
out the part of #4236 that tests the parsing.
See https://github.com/haskell/cabal/pull/4236#issuecomment-272771170.
/cc @robjhen @ezyang
=> Temporarily disallow constraints that have build tool dependency qualifiers.

README.md
It wasn't clear what "three-year support window for cabal-install" means re: self-upgrade.
=> Clarify our policy on cabal-install support window.

cabal-install/Distribution/Client/Install.hs
shayan_ on IRC reported that if you had root-cmd set in your
.cabal/config, cabal install would always fail to run.  That's
bad, esp. because root-cmd would only have an effect when
--global was passed.  Downgrade the warning.
=> Degrade root-cmd error to warning.

cabal-testsuite/Test/Cabal/Prelude.hs, cabal-testsuite/cabal-testsuite.cabal, cabal-testsuite/tests/Setup.hs, cabal-testsuite/tests/fail.test.hs, cabal-testsuite/tests/tests.cabal
This PR fixes a bug in the cabal-testsuite, where the result of calling `runghc Setup.hs`
wasn't checked for failure.
I also wrote a regression test for this, however that test depends on the fact that failing
tests throw `ErrorCall`, and I'm not sure if it's good to rely on that in a test. I haven't
found any other way to check whether a test fails though, since `fails` only checks that all
assertions fail, while in this case I want to check that there actually is an assertion. In
other words, `fails (return ())` succeeds, which is not what we need in this case.
=> cabal-testsuite: check return code of `runghc Setup.hs`

Cabal/doc/installing-packages.rst, cabal-install/Distribution/Client/CmdFreeze.hs, cabal-install/Distribution/Client/Dependency.hs, cabal-install/Distribution/Client/Freeze.hs, cabal-install/Distribution/Client/Targets.hs, cabal-install/Distribution/Solver/Modular/Preference.hs, cabal-install/Distribution/Solver/Types/PackageConstraint.hs, cabal-install/changelog, cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs, cabal-install/tests/UnitTests/Distribution/Client/Targets.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL/TestCaseUtils.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/QuickCheck.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs, cabal-testsuite/PackageTests/Regression/T4154/cabal.project, cabal-testsuite/PackageTests/Regression/T4154/install-time-with-constraint.test.hs, cabal-testsuite/PackageTests/Regression/T4154/repo/Cabal-99999/Cabal.cabal, cabal-testsuite/PackageTests/Regression/T4154/time.cabal
This PR is a continuation of #4236.  I made two changes to `ConstraintScope` before enforcing the constraints in the solver:
* I removed the `Namespace` from the `ScopeQualified` constructor.  This change doesn't affect the behavior of the solver, because we currently don't use `Namespace` anywhere.
* I added a `ScopeAnySetupQualifier` constructor to allow constraints to apply to all setup scripts.  The new constructor is only used internally in this PR.
This PR also adds dependencies with version ranges to the solver DSL.  I ended up not needing the version ranges for these unit tests, but I left them because I think they could be useful.
/cc @robjhen @kosmikus 
EDIT:
/cc @dcoutts @23Skidoo @ezyang @Ericson2314 @hvr @phadej 
Here is a summary of the changes, from the changelog:
* Added …
=> Enforce qualified constraints in the dependency solver.

Cabal/Cabal.cabal, Cabal/Distribution/Compat/Map/Strict.hs, Cabal/Distribution/Simple/PackageIndex.hs
This also bumps the lower bound on containers to `>= 0.5` which
should be fine since that was released in May 2012. This change
should work therefore fine with the last 4 major GHC releases.
=> Fix deprecation warnings from containers

Cabal/Distribution/Simple/Test/LibV09.hs, cabal-testsuite/PackageTests/Regression/T4270/Lib.hs, cabal-testsuite/PackageTests/Regression/T4270/T4270.cabal, cabal-testsuite/PackageTests/Regression/T4270/Test.hs, cabal-testsuite/PackageTests/Regression/T4270/setup.test.hs, cabal-testsuite/Test/Cabal/Monad.hs, cabal-testsuite/Test/Cabal/Prelude.hs
The detailed-0.9 test suite type compiles the test module into a shared library,
so for running the tests, we need to include the directory where the shared
library is stored in LD_LIBRARY_PATH.
=> Fix #4270: make detailed-0.9 test suites work with dynamic exes

Cabal/Distribution/Compat/Graph.hs, Cabal/Distribution/Compat/Map/Strict.hs
GHC's stage0 build doesn't provide MIN_VERSION_* macros. We need to take care to
provide appropriate version check macros by hand in GHC's build system.
=> Fix GHC bootstrapping

Cabal/Cabal.cabal, Cabal/Distribution/PackageDescription/Configuration.hs, Cabal/Distribution/Types/DependencyMap.hs
This is a tiny part of https://github.com/haskell/cabal/pull/4265, which I'm really interested in getting merged before 2.0 is cut so we aren't stuck with a bad anti-component syntax. I'm hoping merging it piecemeal will help! (But also I'm going to be super busy until Monday).
=> Move DependencyMap to its own module.

Cabal/Distribution/Backpack/LinkedComponent.hs, Cabal/Distribution/Utils/LogProgress.hs, cabal-install/tests/IntegrationTests/new-build/T3978.err
- Report all reexport errors, not just the first one
- Give more information about how the modules are different
- Add quotes and prettify the foramt
- Preserve spaces when reporting errors
The new message looks like this:
Problem with module re-exports:
- Ambiguous reexport 'Data.Map'
It could refer to either:
'containers-0.5.6.2-59326c33e30ec8f6afd574cbac625bbb:Data.Map'
brought into scope by the build dependency on containers
or 'containers-dupe-0.1.0.0-2AdbRP7BsOEKELRWSQejuE:Data.Map'
brought into scope by the build dependency on containers-dupe
The ambiguity can be resolved by qualifying the
re-export with a package name.
The syntax is 'packagename:ModuleName [as NewName]'.
- The module 'Missing'
is not exported by any suitable package.
It occurs in neither the 'exposed-modules' of …
=> Improvements to reexported module message:

Cabal/Distribution/Simple/Setup.hs
Just a humble, simple and "free" request to add `deriving (Read)` to `BuildFlags` -- simplifies things slightly for a handful of current/future tool writers / Setup.hs integrations where you dump the buildflags (and other Hook args) in a temp file, invoke your tool (or `--frontend`) to then read that dump in again to get Cabal's rich project/lib/pkg contextual info-collection about the current build.
Of course `StandaloneDeriving` works fine too for this for me right now, but hey, maybe you guys won't mind adding the `Read`, if not no biggie =)
=> DeriveRead for BuildFlags

Cabal/Cabal.cabal, cabal-install/cabal-install.cabal
I'd like to bump the version of `process` in the GHC tree, but need to bump it in Cabal first.
Bumped the rest just to be consistent with versions of `process` used.
https://github.com/haskell/process/blob/master/changelog.md
This is being bumped for a new `process` API in Windows that is off by default.
=> Update process bounds.

cabal-install/Distribution/Client/Install.hs
Previously `cabal install foo` in a sandbox would say
Warning: the --global flag is deprecated -- it is generally considered a bad
idea to install packages into the global store
even though the user didn't actually specify `--global`. That's because sandbox configs specify `--global` by default in their local configs for technical reasons. So this patch just skips the warning if we're going to install into a sandbox.
=> issue #3933: skip the --global deprecation warning when installing to a sandbox

cabal-install/Distribution/Solver/Modular/Builder.hs, cabal-install/Distribution/Solver/Modular/Cycles.hs, cabal-install/Distribution/Solver/Modular/Explore.hs, cabal-install/Distribution/Solver/Modular/Flag.hs, cabal-install/Distribution/Solver/Modular/IndexConversion.hs, cabal-install/Distribution/Solver/Modular/Linking.hs, cabal-install/Distribution/Solver/Modular/Preference.hs, cabal-install/Distribution/Solver/Modular/Solver.hs, cabal-install/Distribution/Solver/Modular/Tree.hs, cabal-install/Distribution/Solver/Modular/Validate.hs, cabal-install/Distribution/Solver/Types/Flag.hs, cabal-install/cabal-install.cabal, cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/MemoryUsage.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/QuickCheck.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs
Three commits:
This fixes #4299. The change gives the dependency solver the flexibility to link
dependencies when the user has only set a manual flag on one of them.
Previously, the solver would force the constrained dependency to have the
flag value from the constraint and force the unconstrained dependency to have
the default flag value. In cases where the single instance restriction required
the dependencies to be linked, the solver couldn't find a solution.
Qualified constraints can still be used to force different dependencies on a
package to use different flag values. For example,
`--constraint 'pkg +flag' --constraint 'pkg2:setup.pkg -flag'` turns the flag on
for the top-level dependency and off for the setup dependency.
I also stored flag default values in the search tree to …
=> Allow the solver to toggle manual flags to match constraints that have any qualifier.

Cabal/Cabal.cabal
This is necessary for GHC 8.2.
=> Bump upper bound on time

.travis.yml, travis-common.sh, travis-install.sh, travis-script.sh, travis/README.md, travis/upload.sh
- Setup the ssh key for cabal-website deploy right before we use
it, so it doesn't get clobbered by our pushbot deploy script.
Furthermore, umask the key to 600, so that we can override it.
- Add some more helpful information to the Pushbot commit messages,
including what branch/PR the build was for, and a link to the
relevant GitHub page.
- Have Travis spoof the author and email of the original committer,
so that Travis sends the build notification message to the right place.
=> A few bug fixes to our CI setup.

.travis.yml, cabal-install/Distribution/Client/Utils/Assertion.hs, cabal-install/Distribution/Solver/Modular/Linking.hs, cabal-install/cabal-install.cabal, travis-script.sh
I added a function, `debugAssert`, that wraps `assert` and only calls it when
the build flag `debug-assertions` is enabled.  The flag defaults to false. I
only replaced one call to `assert` so far (in Distribution.Solver.Modular.Linking)
in order to resolve #4258.
__________________________
I enabled `debug-assertions` in a new GHC 8.0.1 build job, because I figured that it is important to continue testing with the default flag settings in all of the other matrix entries.  I could set `-fdebug-assertions` in one of the existing jobs instead, if it's not worth creating a separate job.
I can also make a PR for the 2.0 branch.
=> Control expensive assertion in Distribution.Solver.Modular.Linking with a build flag.

Cabal/Distribution/Types/DependencyMap.hs
This removes on last use of `Data.Map`, which has been long deprecated.
=> Fix use of deprecated functions from Data.Map

Cabal/Distribution/Types/DependencyMap.hs
DependencyMap: Replace usage of Data.Map with Data.Map.Lazy
The former has been deprecated for quite some time.
(cherry picked from commit e4c36b9dd51820f2380ce7a66f980c4e7b2e96fc)
=> Cherry-pick #4352 into master

cabal-install/Distribution/Client/Get.hs, cabal-install/Distribution/Client/IndexUtils.hs, cabal-install/Distribution/Client/Install.hs, cabal-install/Distribution/Client/ProjectConfig.hs, cabal-install/Distribution/Client/ProjectConfig/Types.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Client/Setup.hs, cabal-install/Distribution/Client/Update.hs, cabal-install/changelog, cabal-install/main/Main.hs
=> Support for --index-state on cabal update

Cabal/Distribution/Simple/Register.hs, cabal-testsuite/PackageTests/Backpack/TemplateHaskell/A.hsig, cabal-testsuite/PackageTests/Backpack/TemplateHaskell/M.hs, cabal-testsuite/PackageTests/Backpack/TemplateHaskell/bkpth.cabal, cabal-testsuite/PackageTests/Backpack/TemplateHaskell/setup.out, cabal-testsuite/PackageTests/Backpack/TemplateHaskell/setup.test.hs
This fixes GHC bug
https://ghc.haskell.org/trac/ghc/ticket/13268
=> Don't specify hs-libraries when none exists!

Cabal/Distribution/Backpack/Configure.hs, Cabal/Distribution/Backpack/ConfiguredComponent.hs, Cabal/Distribution/Backpack/PreExistingComponent.hs, Cabal/Distribution/Simple/Configure.hs, cabal-install/Distribution/Client/ProjectPlanning.hs
It no longer hacks around build-depends: that code has been moved to Backpack.Configure, and will be removed altogether with LibDependency
@ezyang I suppose as the foundation this should be reviewed carefully?
=> Clean up PreExistingComponent

Cabal/Distribution/Backpack/Configure.hs, Cabal/Distribution/Backpack/ConfiguredComponent.hs, Cabal/Distribution/Backpack/LinkedComponent.hs, Cabal/Distribution/Backpack/ReadyComponent.hs, cabal-install/Distribution/Client/InstallPlan.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Client/ProjectPlanning/Types.hs, cabal-testsuite/PackageTests/NewBuild/T3978/cabal.out
* toConfiguredComponents and friends are now monadic.  This means
we can report a user-friendly error when we fail to find a
dependency in the dependency map.  I had to rejigger a bit
of the logic in ProjectPlanning since we were knot-tying through
this function, but it all worked out.  This means
that unbuildable_external_lib_deps is no more.
* cc_internal_build_tools is no more; instead it's cc_exe_deps,
which tracks ALL dependencies.  It also comes with a PackageId
so we can build ConfiguredId cabal-install side.  This change
propagates all the way to 'ReadyComponent'
* ProjectPlanning: Instead of recomputing dependencies from scratch,
we instead use the ElaboratedConfiguredPackages we just finished
making to build the ComponentDeps.
* ProjectPlanning now constructs a skeletal …
=> ProjectPlanning refactor

Cabal/Distribution/Verbosity.hs, cabal-testsuite/PackageTests/CustomPlain/cabal.project, cabal-testsuite/PackageTests/CustomPlain/cabal.test.hs
Since VQuiet is set programmatically, it's inappropriate
for it to be propagated to the command line.  But unfortunately,
if it was set, we were accidentally using the fancy flag format.
This patch moves VQuiet to its own field in Verbosity so we
don't get confused.
Fixes #4393.
=> Don't put VQuiet in VFlags; that's reserved for user-toggles.

cabal-install/tests/UnitTests/Distribution/Solver/Modular/MemoryUsage.hs
The test previously caused the solver to backtrack because of a missing package.
Missing packages are handled as a special case in the solver, so the test didn't
exercise as much code as it could have.  This commit causes the solver to
backtrack with a version conflict, which is a more common type of failure.
Other tests continue to test the missing package case.
=> Use a more common type of conflict in the solver basic memory usage test.

cabal-install/Distribution/Client/ProjectBuilding.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Client/ProjectPlanning/Types.hs, cabal-testsuite/PackageTests/NewBuild/T4405/cabal.out, cabal-testsuite/PackageTests/NewBuild/T4405/cabal.project, cabal-testsuite/PackageTests/NewBuild/T4405/cabal.test.hs, cabal-testsuite/PackageTests/NewBuild/T4405/p/P.hs, cabal-testsuite/PackageTests/NewBuild/T4405/p/PTest.hs, cabal-testsuite/PackageTests/NewBuild/T4405/p/p.cabal, cabal-testsuite/PackageTests/NewBuild/T4405/q/Q.hs, cabal-testsuite/PackageTests/NewBuild/T4405/q/q.cabal
Previously, we used the solver dependencies to figure out
what to monitor, but this lead to a failure mode where we
would also monitor the monitor files associated with the
test suite, which we really shouldn't do.
This patch pushes the monitor file calculation later until
the build step, at which point we know exactly what our
dependencies are, and monitor those precisely.
Fixes #4405.
=> More accurately determine monitors to monitor.

Cabal/Distribution/Simple/Setup.hs
This tries to address (part of) #4414 by minimally extending `splitArgs`
with support for escaping (only) `"`s by prefixing them with `\`s.
=> Add minimal support for escaping `"`s to splitArgs

cabal-install/Distribution/Client/Setup.hs
In particular, the Cmd* modules don't mappend in the defaults
before using the flags, so ensuring they're setup correctly from
the start helps avoid errors.
This default flag business is extremely dodgy and I wish we had a better
story for it.
=> Use default flags rather than mempty.

Cabal/Distribution/Backpack/LinkedComponent.hs, Cabal/Distribution/Backpack/ReadyComponent.hs, Cabal/Distribution/Simple/PackageIndex.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Client/ProjectPlanning/Types.hs, cabal-testsuite/PackageTests/Backpack/Includes2/cabal-external-target.out, cabal-testsuite/PackageTests/Backpack/Includes2/cabal-external-target.test.hs, cabal-testsuite/PackageTests/Backpack/Includes2/cabal-internal-target.out, cabal-testsuite/PackageTests/Backpack/Includes2/cabal-internal-target.test.hs
Three bugs:
* `mkPackageIndex` still wasn't quite right, resulting in assert failures when using internal libraries in some situations. I think I've finally nailed it.
* When I say `cabal new-build foo-indef`, I only want to typecheck an indefinite package, not also build all of its instantiations. This is now done.
* When I say `build-depends: str-sig, str-string`, I'm saying, "please verify str-string matches str-sig." But this check will only be done if we build the instantiated signature package, which we were not doing previously.
=> Some bugfixes I noticed from Backpacking

Cabal/Distribution/Simple/Build.hs, Cabal/Distribution/Simple/GHC.hs, Cabal/Distribution/Simple/GHCJS.hs, Cabal/Distribution/Simple/LHC.hs, Cabal/Distribution/Simple/Program/HcPkg.hs, Cabal/Distribution/Simple/Register.hs, cabal-install/Distribution/Client/Compat/FileLock.hsc, cabal-install/Distribution/Client/DistDirLayout.hs, cabal-install/Distribution/Client/Install.hs, cabal-install/Distribution/Client/ProjectBuilding.hs, cabal-install/Distribution/Client/ProjectOrchestration.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Client/RebuildMonad.hs, cabal-install/Distribution/Client/Store.hs, cabal-install/cabal-install.cabal, cabal-install/tests/IntegrationTests2.hs, cabal-install/tests/UnitTests.hs, cabal-install/tests/UnitTests/Distribution/Client/Store.hs
We need to be able to safely do concurrent builds of different projects that share the store. This code documents and implements a concurrency strategy for reading and writing entries in the store.
This patch includes new compat code for file locks, taken from the base library from ghc-8.2.x.
It is not yet used or indeed tested. This PR is here for feedback on the concurrency strategy (which is clearly documents in the haddock docs in the module) and to check that the locking code does indeed build on windows.
=> WIP: concurrent store updates

cabal-install/Distribution/Client/Compat/FileLock.hsc
with this fix, `cabal` can be built with GHC 8.2.1RC via
```
cabal new-build -w ghc-8.2.1 exe:cabal \
--allow-newer=hackage-security:time,HTTP:base,vector:base,cabal-install:time
```
=> Fix CPP in FileLock.hsc

Cabal/Distribution/Simple/Configure.hs
Remove redundant do, bracket and $. Though it is a minor change,
avoiding warnings is always better.
I am not sure whether such minor changes are accepted. I was trying to read and understand the Configure.hs code but these kept coming up on my editor as warnings.
=> configure: remove redundancy

Cabal/Cabal.cabal, Cabal/Distribution/Backpack/LinkedComponent.hs, Cabal/Distribution/Backpack/MixLink.hs, Cabal/Distribution/Backpack/ModuleScope.hs, Cabal/Distribution/Backpack/PreModuleShape.hs, Cabal/Distribution/Backpack/UnifyM.hs, Cabal/Distribution/Types/ModuleRenaming.hs, cabal-testsuite/PackageTests/Backpack/T4447/A.hs, cabal-testsuite/PackageTests/Backpack/T4447/Main.hs, cabal-testsuite/PackageTests/Backpack/T4447/T4447.cabal, cabal-testsuite/PackageTests/Backpack/T4447/cabal.project, cabal-testsuite/PackageTests/Backpack/T4447/foo-indef/A.hsig, cabal-testsuite/PackageTests/Backpack/T4447/foo-indef/B.hs, cabal-testsuite/PackageTests/Backpack/T4447/setup.out, cabal-testsuite/PackageTests/Backpack/T4447/setup.test.hs, cabal-testsuite/PackageTests/ReexportedModules/setup-fail-ambiguous.cabal.out, cabal-testsuite/PackageTests/ReexportedModules/setup-fail-ambiguous.out
A few things:
- We now have a proper pre-mixin-linking pass which computes
just the set of requirements we expect to see after mixin
linking is done.  That lets us precompute the unit id
for locally defined modules.
- Since we now know the correct module identities, we can
make shapes for exposed-modules/other-modules and make
them participate in mix-in linking.
- But we don't actually want to instantiate a requirement with
a locally defined module, because GHC can't compile that!
We want to error in this case.  Previously, we didn't notice
that this had occurred at all; now it is caught, fixing #4447.
=> Implement pre-mixin-linking, make local modules participate.

Cabal/Distribution/Backpack/ComponentsGraph.hs, Cabal/Distribution/Package.hs, Cabal/Distribution/Simple/Configure.hs, Cabal/Distribution/Simple/PackageIndex.hs, cabal-install/Distribution/Client/Init.hs, cabal-install/Distribution/Client/ProjectConfig/Legacy.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Solver/Modular/IndexConversion.hs, cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL.hs
=> Re-export Dependency from Distribution.Package.

Cabal/Distribution/Backpack/ComponentsGraph.hs, Cabal/Distribution/Backpack/Configure.hs, cabal-install/Distribution/Client/ProjectBuilding.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Client/ProjectPlanning/Types.hs, cabal-testsuite/PackageTests/NewBuild/T4450/A.hs, cabal-testsuite/PackageTests/NewBuild/T4450/Main.hs, cabal-testsuite/PackageTests/NewBuild/T4450/Setup.hs, cabal-testsuite/PackageTests/NewBuild/T4450/T4450.cabal, cabal-testsuite/PackageTests/NewBuild/T4450/cabal.out, cabal-testsuite/PackageTests/NewBuild/T4450/cabal.project, cabal-testsuite/PackageTests/NewBuild/T4450/cabal.test.hs, cabal-testsuite/PackageTests/NewBuild/T4450/dep/Dep.hs, cabal-testsuite/PackageTests/NewBuild/T4450/dep/dep.cabal, cabal-testsuite/Test/Cabal/Prelude.hs
Previously, we stated that registration was needed if any build target
was a library.  Actually, this is not enough: if we have a build target
on an executable which in turn depends on the library, we must register
it.
To actually get this information, I had to refactor ComponentsGraph to
return the actual *graph*, so I could do a reverse closure on it, giving
me the set of components that actually depend on the library.  That info
then gets plumbed through ElaboratedPackage and then used to determine
if registration is necessary.
Fixes #4450, but it's possible there is another variant of the bug
that occurs if the executable to be built does NOT depend on the
librayr.
=> More accurate "registration needed?" calculation for packages.

cabal-install/Distribution/Client/CmdConfigure.hs, cabal-testsuite/PackageTests/NewConfigure/LocalConfigOverwrite/NewConfigure.cabal, cabal-testsuite/PackageTests/NewConfigure/LocalConfigOverwrite/Setup.hs, cabal-testsuite/PackageTests/NewConfigure/LocalConfigOverwrite/cabal.out, cabal-testsuite/PackageTests/NewConfigure/LocalConfigOverwrite/cabal.project, cabal-testsuite/PackageTests/NewConfigure/LocalConfigOverwrite/cabal.test.hs
The new-configure blows away the old `cabal.project.local`, even if
you've tweaked it by hand and it has some sort of substantial changes.
To prevents accidents like this from happening, we should print the old
local file if we overwrite it.
This fixes #3943 .
=> Output old config before rewriting `cabal.project.local`

cabal.project
See #4497 for more details. We'll have to set this bound
until tasty fixes the bug.
=> Set upper bound for unbounded-delays

Cabal/Distribution/Simple/Utils.hs
I noticed that in some cases we weren't adding a trailing
newline to error messages arising from "error"; this
patch adds a few newlines where there were none to solve
the problem.
=> Improve error display in top level handler.

cabal-testsuite/PackageTests/BuildTargets/UseLocalPackage/Main.hs, cabal-testsuite/PackageTests/BuildTargets/UseLocalPackage/cabal.project, cabal-testsuite/PackageTests/BuildTargets/UseLocalPackage/pkg.cabal, cabal-testsuite/PackageTests/BuildTargets/UseLocalPackage/repo/pkg-1.0/pkg.cabal, cabal-testsuite/PackageTests/BuildTargets/UseLocalPackage/repo/pkg-2.0/pkg.cabal, cabal-testsuite/PackageTests/BuildTargets/UseLocalPackage/use-local-version-of-package.out, cabal-testsuite/PackageTests/BuildTargets/UseLocalPackage/use-local-version-of-package.test.hs
While I was working on #4481 I noticed that we only test this behavior for internal libraries (PackageTests/BuildDeps/InternalLibrary3/setup.test.hs).
=> Add an integration test for choosing to build the local version of a package.

cabal-install/Distribution/Client/ProjectConfig.hs, cabal-install/Distribution/Client/ProjectConfig/Legacy.hs, cabal-install/Distribution/Client/ProjectConfig/Types.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Client/Setup.hs, cabal-install/Distribution/Client/Targets.hs, cabal-install/Distribution/Solver/Modular/Builder.hs, cabal-install/Distribution/Solver/Modular/Package.hs, cabal-install/Distribution/Solver/Types/PackageConstraint.hs, cabal-install/Distribution/Solver/Types/PackagePath.hs, cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs, cabal-testsuite/PackageTests/BuildTargets/UseLocalPackageForSetup/cabal.project, cabal-testsuite/PackageTests/BuildTargets/UseLocalPackageForSetup/pkg/pkg.cabal, cabal-testsuite/PackageTests/BuildTargets/UseLocalPackageForSetup/repo/setup-dep-1.0/setup-dep.cabal, cabal-testsuite/PackageTests/BuildTargets/UseLocalPackageForSetup/setup-dep/setup-dep.cabal, cabal-testsuite/PackageTests/BuildTargets/UseLocalPackageForSetup/use-local-package-as-setup-dep.out, cabal-testsuite/PackageTests/BuildTargets/UseLocalPackageForSetup/use-local-package-as-setup-dep.test.hs
--independent-goals could be useful for using local packages as setup or
build-tool dependencies in new-build.  See #4295 for an example of a dependency
problem that requires --independent-goals.  The flag is off by default.
I also had to update the constraints that cabal uses to force all build targets to be built with local packages.  They were too restrictive before, because they applied to all top-level dependencies.  Now they only apply to specific build targets.
@dcoutts Is there any problem with exposing this flag in new-build?  I didn't really understand the comments explaining why some of the flags were commented out in new-build, so I didn't know whether they still applied.  I marked them with Github comments.
=> Uncomment --independent-goals flag.

Cabal/Cabal.cabal, Cabal/Distribution/PackageDescription/Check.hs, Cabal/Distribution/PackageDescription/Parse.hs, Cabal/Distribution/PackageDescription/Parsec/FieldDescr.hs, Cabal/Distribution/PackageDescription/PrettyPrint.hs, Cabal/Distribution/Parsec/Class.hs, Cabal/Distribution/Simple/Build.hs, Cabal/Distribution/Simple/Configure.hs, Cabal/Distribution/Simple/GHC.hs, Cabal/Distribution/Simple/GHCJS.hs, Cabal/Distribution/Simple/Haddock.hs, Cabal/Distribution/Simple/Install.hs, Cabal/Distribution/Simple/InstallDirs.hs, Cabal/Distribution/Simple/LHC.hs, Cabal/Distribution/Simple/Setup.hs, Cabal/Distribution/Types/Executable.hs, Cabal/Distribution/Types/ExecutableScope.hs, Cabal/doc/installing-packages.rst, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Client/Setup.hs, cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
I use executables installed into '$libexecdir' with great effect in ghc-mod and cabal-helper but so far I've been using an ugly hack in Setup.hs so I figured why not get this upstreamed since it's relatively straightforward.
Now in #708 the request is for a boolean field "Is-Helper-Executable" but I figured having support for specifying an arbitrary path while using the `PathTemplate` variables is a lot more flexible and just seems like the consistent thing to do since there aren't any other such boolean fields anywhere in the PackageDescription apart from say 'buildable'.
I've added a check to make sure packages that end up on hackage don't have absolute paths in 'install-dir' which seems like a reasonable restriction.
I haven't tested the bits in PrettyPrint yet and I'd appreciate …
=> Implement 'scope' field for executables (#708)

cabal-install/cabal-install.cabal, cabal-install/main/Main.hs, cabal-install/tests/IntegrationTests2.hs, cabal-install/tests/MemoryUsageTests.hs, cabal-install/tests/SolverQuickCheck.hs, cabal-install/tests/UnitTests.hs, cabal.project, cabal.project.travis, travis-common.sh, travis-script.sh, travis/binaries/.travis.yml, travis/binaries/travis-cleanup.sh, travis/binaries/travis-test.sh, travis/upload.sh
Greatly reduce the amount of build product we upload.
See #4462 for the gory details.
Main things about this commit:
- New 'monolithic' flag on cabal-install, which combines
all of the tests into a single binary.  It's not very
much code, and you don't pay for any of it on a release
build.  I quite like it.  The one downside is that
we can't also pull in Cabal test suites this way.
- Env vars got moved into travis-common.sh
- travis-script.sh now runs the cabal-tests tests, because
we aren't sending enough build product over to do them
on the second Travis run
=>  Greatly reduce the amount of build product we upload.

cabal-install/Distribution/Client/ProjectPlanning/Types.hs, cabal-testsuite/PackageTests/BuildTargets/UseLocalPackageForSetup/pkg/Main.hs, cabal-testsuite/PackageTests/BuildTargets/UseLocalPackageForSetup/pkg/Setup.hs, cabal-testsuite/PackageTests/BuildTargets/UseLocalPackageForSetup/pkg/pkg.cabal, cabal-testsuite/PackageTests/BuildTargets/UseLocalPackageForSetup/repo/setup-dep-1.0/Module.hs, cabal-testsuite/PackageTests/BuildTargets/UseLocalPackageForSetup/repo/setup-dep-1.0/setup-dep.cabal, cabal-testsuite/PackageTests/BuildTargets/UseLocalPackageForSetup/setup-dep/Module.hs, cabal-testsuite/PackageTests/BuildTargets/UseLocalPackageForSetup/setup-dep/setup-dep.cabal, cabal-testsuite/PackageTests/BuildTargets/UseLocalPackageForSetup/use-local-package-as-setup-dep.out, cabal-testsuite/PackageTests/BuildTargets/UseLocalPackageForSetup/use-local-package-as-setup-dep.test.hs, cabal-testsuite/PackageTests/NewBuild/CustomSetup/LocalPackageWithCustomSetup/Setup.hs, cabal-testsuite/PackageTests/NewBuild/CustomSetup/LocalPackageWithCustomSetup/build-local-package-with-custom-setup.out, cabal-testsuite/PackageTests/NewBuild/CustomSetup/LocalPackageWithCustomSetup/build-local-package-with-custom-setup.test.hs, cabal-testsuite/PackageTests/NewBuild/CustomSetup/LocalPackageWithCustomSetup/cabal.project, cabal-testsuite/PackageTests/NewBuild/CustomSetup/LocalPackageWithCustomSetup/pkg.cabal, cabal-testsuite/PackageTests/NewBuild/CustomSetup/LocalPackageWithCustomSetup/repo/setup-dep-2.0/SetupDep.hs, cabal-testsuite/PackageTests/NewBuild/CustomSetup/LocalPackageWithCustomSetup/repo/setup-dep-2.0/setup-dep.cabal, cabal-testsuite/PackageTests/NewBuild/CustomSetup/RemotePackageWithCustomSetup/Main.hs, cabal-testsuite/PackageTests/NewBuild/CustomSetup/RemotePackageWithCustomSetup/build-package-from-repo-with-custom-setup.out, cabal-testsuite/PackageTests/NewBuild/CustomSetup/RemotePackageWithCustomSetup/build-package-from-repo-with-custom-setup.test.hs, cabal-testsuite/PackageTests/NewBuild/CustomSetup/RemotePackageWithCustomSetup/cabal.project, cabal-testsuite/PackageTests/NewBuild/CustomSetup/RemotePackageWithCustomSetup/pkg.cabal, cabal-testsuite/PackageTests/NewBuild/CustomSetup/RemotePackageWithCustomSetup/repo/remote-pkg-2.0/RemotePkg.hs, cabal-testsuite/PackageTests/NewBuild/CustomSetup/RemotePackageWithCustomSetup/repo/remote-pkg-2.0/Setup.hs, cabal-testsuite/PackageTests/NewBuild/CustomSetup/RemotePackageWithCustomSetup/repo/remote-pkg-2.0/remote-pkg.cabal, cabal-testsuite/PackageTests/NewBuild/CustomSetup/RemotePackageWithCustomSetup/repo/remote-setup-dep-3.0/RemoteSetupDep.hs, cabal-testsuite/PackageTests/NewBuild/CustomSetup/RemotePackageWithCustomSetup/repo/remote-setup-dep-3.0/remote-setup-dep.cabal, cabal-testsuite/Test/Cabal/Plan.hs
I tried to make the integration test from #4481 ([PackageTests/BuildTargets/UseLocalPackageForSetup/use-local-package-as-setup-dep.test.hs](https://github.com/haskell/cabal/blob/81396cd1d3eb3af73cbea23526b61c5908dc44c2/cabal-testsuite/PackageTests/BuildTargets/UseLocalPackageForSetup/use-local-package-as-setup-dep.test.hs)) more thorough by removing --dry-run from the build command, and I ran into a bug.  The bug prevented cabal from building local packages if they were only needed as setup dependencies.  That meant that cabal didn't build the library for setup-dep-2.0 in the test.
Changes in this PR:
- Fix the bug by modifying D.C.ProjectPlanning.Types.elabOrderLibDependencies.
- Support parsing global packages in plan.json in cabal-testsuite/Test/Cabal/Plan.hs to allow the test to pass. …
=> Fix a bug in building local setup dependencies.

Cabal/changelog, Cabal/doc/developing-packages.rst, Cabal/doc/installing-packages.rst
I clarified that $libexecsubdir is a sub-directory of $libexecdir, added some motivation for the subdir change to the changelog and added an example to the docs.
=> Improve exe `scope` docs

cabal-install/Distribution/Client/ProjectPlanOutput.hs, cabal-install/Distribution/Client/ProjectPlanning.hs
This was temporarily disabled via
3033776a742022693917d05ce18440c560e721e7 due to #4010
but it turns out that we can easily workaround this for
older Cabal versions.
All we need to do is inject `--ghc-options=-hide-all-packages` into
the flags passed to Setup.hs when an old `Cabal` version is detected
(this was suggested by @dcoutts in
https://github.com/haskell/cabal/issues/4010#issuecomment-254958478)
Luckily, `-hide-all-packages` is idempotent in GHC, so we can place it
anywhere on the GHC command-line as well as multiple times with the
same result.
This would close #4010
=> Reenable GHC environment file support

Cabal/Distribution/Simple/Utils.hs, Cabal/Distribution/Verbosity.hs
This prepends a posix timestamp (with milliseconds precision) to log
messages (before any wrapping is applied)
Example output:
$ cabal update --verbose=verbose+timestamp
1478941945.027 Downloading the latest package list from hackage.haskell.org
1478941945.029 Selected mirror http://hackage.haskell.org/
1478941945.036 Downloading timestamp
...
$ cabal --verbose=normal+timestamp new-build --dry --enable-tests
1478947448.519 Resolving dependencies...
1478947450.887 In order, the following would be built (use -v for more details):
- Cabal-1.25.0.0 (lib) (configuration changed)
- hackage-security-0.5.2.2 (lib) (dependency rebuilt)
- cabal-testsuite-1.25.0.0 (test:package-tests) (dependency rebuilt)
- Cabal-1.25.0.0 (test:unit-tests) (dependency rebuilt)
- cabal-install-1.25.0.0 (exe:cabal, …
=> Implement +timestamp verbosity flag

Cabal/Distribution/Simple/GHC/ImplInfo.hs
Relevant background on `-Wmissing-home-modules`: https://github.com/haskell/cabal/issues/1746#issuecomment-272691469.
=> More accurate -Wmissing-home-modules version check.

Cabal/Distribution/Verbosity.hs, cabal-install/Distribution/Client/Setup.hs, cabal-install/Distribution/Client/SetupWrapper.hs
This is is a follow-up to #4518
=> Filter `+timestamp` out when invoking Cabal-2.0.0 custom-setups

Cabal/Distribution/Simple/GHC.hs
`gbuildSources` was introduced by a refactoring in
382143aa7322605d1a9f0480e383490e186c7ea0 but there
doesn't appear to be a good reason why the modules are
only passed for a non-haskell main module.
So this patch consistently passes `other-modules` to
`ghc --make` for both variants of executables.
Addresses part of #4528
=> Pass other-modules to `ghc --make` for exe components

Cabal/Distribution/Simple/GHC/Internal.hs
i.e. not only library components, but also executables, tests and benchmarks.
(With GHC-8.2.1 snapshot 8.2.0.20170521 or earlier, this emits a harmless warning about `Main`;
the next upcoming snapshot build of GHC-8.2.1 will already omit the spurious warning)
This addresses the other half of #4528
=> Pass -Wmissing-home-modules to all component types

cabal-install/cabal-install.cabal
This should hopefully silence all 4 combinations of flag(lib)
and flag(monolithic).
`cabal-install.cabal` would greatly benefit from common stanzas (#2832)
as it would help reduce the redundancy significantly.
=> Silence new -Wmissing-home-modules warning for `cabal-install`

cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
In response to #4044, begin using record syntax instead of positional arguments.
I think this can be improved so I am happy for any kind of feedback and/or tips, especially since a part still uses positional arguments, but this change should already make it a bit clearer.
=> Refactor ProjectConfig Arbitrary instances

cabal-install/Distribution/Solver/Modular/Assignment.hs, cabal-install/Distribution/Solver/Modular/Dependency.hs, cabal-install/Distribution/Solver/Modular/Validate.hs
This just moves some functions and types into Validate.hs in preparation for
#4391.
______________________________________________________
I wanted to make separate PRs with the refactoring changes from #4562, to avoid conflicts.  This is the first commit from #4562.
=> Solver: Refactor Validate.hs.

cabal-install/Distribution/Solver/Compat/Prelude.hs, cabal-install/Distribution/Solver/Modular/Linking.hs, cabal-install/Distribution/Solver/Modular/Log.hs, cabal-install/Distribution/Solver/Modular/Preference.hs, cabal-install/Distribution/Solver/Types/ComponentDeps.hs, cabal-install/Distribution/Solver/Types/PackageConstraint.hs, cabal-install/Distribution/Solver/Types/PackageIndex.hs, cabal-install/Distribution/Solver/Types/PackagePath.hs, cabal-install/Distribution/Solver/Types/PkgConfigDb.hs, cabal-install/Distribution/Solver/Types/Progress.hs, cabal-install/cabal-install.cabal, cabal-install/main/Main.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL/TestCaseUtils.hs
The idea here is to break the dependency that has crept in from the
"Solver" into the "Client". (If there's ever going to be a separate
solver then the dependency would become a big problem.)
----
=> Move Distribution.Client.Compat.Prelude to Distribution.Compat.Prelude

Cabal/doc/nix-local-build.rst, cabal-install/Distribution/Client/Dependency.hs, cabal-install/Distribution/Client/Types.hs, cabal-install/changelog, cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
This extends the capabilities of `--allow-{newer,older}` to allow for more
fine-grained scoping to control more precisely which packages and constraints
a relaxation is applied to. See updated documentation for more details.
=> Enhance `--allow-{newer,older}` syntax

Cabal/Distribution/Compat/CopyFile.hs, Cabal/Distribution/Simple/Configure.hs
I noticed that `filesEqual` always compares files contents, but there's faster way to check whether files are different - just check their sizes.
I wrote small benchmarking suite that tested old and new `filesEqual` on both equal files containing letter 'a' replicated N times and on different files of different sizes with similar contents (the suite is (here)[https://github.com/sergv/benchmarks/blob/master/bench/CompareFileContents.hs]. The output suggests, that size check introduces negligible overhead in case files are equal, but makes comparison of different files independent of their size, thus gaining huge speedups on larger files:
```
benchmarking 10Kb/Equal/filesEqualCabal
time                 28.42 μs   (28.19 μs .. 28.66 μs)
0.999 R²   (0.999 R² .. 1.000 R²)
mean …
```
=> Speed up equal files check

cabal-install/Distribution/Client/TargetSelector.hs
without this `cabal new-run` without targets errors with an irrefutable pattern
=> an empty target is an empty string

Cabal/Language/Haskell/Extension.hs
PR aims to fix issue #4582.
Only documentation links to [Glasgow Haskell Compiler Users Guide](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#ghc-flag--XStaticPointers) are replaced.
=> fixing broken links

Cabal/Language/Haskell/Extension.hs
- corret hugs documentation liks
- add StrictData and Strict ghc flag links
- update documentation links for PolymorphicComponents, Generics, GADTs and MonoPatBinds
issue #4582
This PR aims to fix remaining broken links #4582
But there are still two 404-links
- [AutoDeriveTypeable](https://github.com/haskell/cabal/issues/4582#issuecomment-313312570)
- [ImplicitPrelude](https://github.com/haskell/cabal/issues/4582#issuecomment-313308367)
=> fixing documentation links

cabal-install/Distribution/Client/Init.hs
I don't know if it was there for a reason, but it looks like it wasn't.
=> Remove extra space from ChangeLog generation

Cabal/Distribution/PackageDescription.hs, Cabal/Distribution/Simple/GHC.hs, Cabal/Distribution/Simple/GHCJS.hs, Cabal/Distribution/Simple/LHC.hs, Cabal/Distribution/Types/BuildInfo.hs, Cabal/Language/Haskell/Extension.hs, cabal-testsuite/PackageTests/QuasiQuotes/dynamic/Exe.hs, cabal-testsuite/PackageTests/QuasiQuotes/dynamic/Lib.hs, cabal-testsuite/PackageTests/QuasiQuotes/dynamic/QQ.hs, cabal-testsuite/PackageTests/QuasiQuotes/dynamic/my.cabal, cabal-testsuite/PackageTests/QuasiQuotes/dynamic/setup.cabal.out, cabal-testsuite/PackageTests/QuasiQuotes/dynamic/setup.out, cabal-testsuite/PackageTests/QuasiQuotes/dynamic/setup.test.hs, cabal-testsuite/PackageTests/QuasiQuotes/profiling/Exe.hs, cabal-testsuite/PackageTests/QuasiQuotes/profiling/Lib.hs, cabal-testsuite/PackageTests/QuasiQuotes/profiling/QQ.hs, cabal-testsuite/PackageTests/QuasiQuotes/profiling/my.cabal, cabal-testsuite/PackageTests/QuasiQuotes/profiling/setup.cabal.out, cabal-testsuite/PackageTests/QuasiQuotes/profiling/setup.out, cabal-testsuite/PackageTests/QuasiQuotes/profiling/setup.test.hs, cabal-testsuite/PackageTests/QuasiQuotes/vanilla/Exe.hs, cabal-testsuite/PackageTests/QuasiQuotes/vanilla/Lib.hs, cabal-testsuite/PackageTests/QuasiQuotes/vanilla/QQ.hs, cabal-testsuite/PackageTests/QuasiQuotes/vanilla/my.cabal, cabal-testsuite/PackageTests/QuasiQuotes/vanilla/setup.cabal.out, cabal-testsuite/PackageTests/QuasiQuotes/vanilla/setup.out, cabal-testsuite/PackageTests/QuasiQuotes/vanilla/setup.test.hs
Addresses #4580. I have not added a test for this. I could easily modify or duplicate the tests in cabal-tests/PackageTests/TemplateHaskell if you think it worthwhile.
Note that ghc-8.2 is smart enough to not need this logic, I'm not sure when those smarts were added.
I verified this works by modifying those tests to have QuasiQuotes in their cabal files, and running them with ghc-7.6.3.
=> Refine "doingTH" check to include checking for QuasiQuotes

cabal-install/Distribution/Solver/Modular/Explore.hs, cabal-testsuite/PackageTests/Backpack/Includes2/setup-external.cabal.out, cabal-testsuite/PackageTests/BuildTargets/UseLocalPackageForSetup/use-local-package-as-setup-dep.out, cabal-testsuite/PackageTests/ConfigureComponent/Exe/setup.cabal.out
Two main commits:
In Explore.hs, the solver calculates a conflict set corresponding to the option
to not choose a value for each goal, called `initial`.  That conflict set should
be added to the ConflictMap when the current goal causes a conflict.  However,
there was a bug, and the solver added `initial` to the ConflictMap at every
level.
The bug meant that the solver preferred all goals that it had already chosen.
If a new goal started to cause conflicts, it would take a while for the solver
to start preferring the new goal over the ones that it had previously seen.
See #4595 for an example where this problem caused longer backjumps and slowed
down the solver.
The conflict set that represents the option to not choose a value for a goal,
`initial`, has two purposes:
1. `initial` …
=> Fix bug in conflict counting.

cabal-install/Distribution/Client/ProjectOrchestration.hs, cabal-testsuite/PackageTests/Backpack/Includes2/cabal-external-target.out, cabal-testsuite/PackageTests/Backpack/Includes2/cabal-external.out, cabal-testsuite/PackageTests/Backpack/Includes2/cabal-internal-target.out, cabal-testsuite/PackageTests/Backpack/Includes2/cabal-internal.out, cabal-testsuite/PackageTests/Backpack/Includes3/cabal-external.out, cabal-testsuite/PackageTests/Backpack/Includes3/cabal-internal.out, cabal-testsuite/PackageTests/BuildDeps/InternalLibrary1/cabal.out, cabal-testsuite/PackageTests/BuildTargets/UseLocalPackage/use-local-version-of-package.out, cabal-testsuite/PackageTests/BuildToolDepends/setup.out, cabal-testsuite/PackageTests/BuildTools/External/cabal.out, cabal-testsuite/PackageTests/BuildTools/Internal/cabal.out, cabal-testsuite/PackageTests/CustomSegfault/cabal.out, cabal-testsuite/PackageTests/CustomWithoutCabal/cabal.out, cabal-testsuite/PackageTests/CustomWithoutCabalDefaultMain/cabal.out, cabal-testsuite/PackageTests/Exec/cabal.out, cabal-testsuite/PackageTests/ExecModern/cabal.out, cabal-testsuite/PackageTests/InternalLibraries/cabal.out, cabal-testsuite/PackageTests/NewBuild/MonitorCabalFiles/cabal.out, cabal-testsuite/PackageTests/NewBuild/T3827/cabal.out, cabal-testsuite/PackageTests/NewBuild/T4017/cabal.out, cabal-testsuite/PackageTests/NewBuild/T4375/cabal.out, cabal-testsuite/PackageTests/NewBuild/T4405/cabal.out, cabal-testsuite/PackageTests/NewConfigure/LocalConfigOverwrite/cabal.out, cabal-testsuite/PackageTests/Regression/T3436/cabal.out, cabal-testsuite/PackageTests/Regression/T4154/install-time-with-constraint.out, cabal-testsuite/PackageTests/Regression/T4202/cabal.out, cabal-testsuite/PackageTests/TestSuiteTests/ExeV10/cabal.out
Prints build profile—at the moment only compiler and optimization level. Sample output:
```
Build profile: with-compiler: ghc-7.10.3, optimization: MaximumOptimisation
```
With this `cabal.project.local`:
```
optimization: 2
```
This is a naive attempt to address #3945. I'm not only new to Cabal but also to Haskell. I'd gladly follow any hints by a mentor to get this merged but feel free to discard it if there's absolutely no hope.
=> Print build profile in new-build command

cabal-install/Distribution/Client/CmdRun.hs, cabal-testsuite/PackageTests/NewBuild/CmdRun/Datafiles/Datafiles.cabal, cabal-testsuite/PackageTests/NewBuild/CmdRun/Datafiles/Main.hs, cabal-testsuite/PackageTests/NewBuild/CmdRun/Datafiles/cabal.out, cabal-testsuite/PackageTests/NewBuild/CmdRun/Datafiles/cabal.project, cabal-testsuite/PackageTests/NewBuild/CmdRun/Datafiles/cabal.test.hs, cabal-testsuite/PackageTests/NewBuild/CmdRun/Datafiles/data/hello.txt
This enables the executale to find the datafiles in inplace builds.
Fixes #4120
=> Add datadir env var before running the exe

cabal-install/Distribution/Client/CmdBench.hs, cabal-install/Distribution/Client/CmdBuild.hs, cabal-install/Distribution/Client/CmdConfigure.hs, cabal-install/Distribution/Client/CmdHaddock.hs, cabal-install/Distribution/Client/CmdRepl.hs, cabal-install/Distribution/Client/CmdRun.hs, cabal-install/Distribution/Client/CmdTest.hs, cabal-install/Distribution/Client/ProjectOrchestration.hs, cabal-testsuite/PackageTests/NewBuild/CmdRun/ExeAndLib/cabal.out, cabal-testsuite/PackageTests/NewBuild/CmdRun/ExeAndLib/cabal.test.hs
followup of #4586
Previously, the extraction of the target from the targetStrings was done
twice: inside the function passed to 'runProjectPreBuildPhase' and right
after it.
Now 'runProjectPreBuildPhase' is able to return information from that
function, and the duplication was removed, along with some assumptions
about the number of targets.
---
This is one of the possible approaches, the other being adding a field in ProjectBuildContext.
The only way to avoid a Maybe or a sum type in said field, is parameterizing it.
```haskell
data ProjectBuildContext arbitraryData = ProjectBuildContext{
...
someFieldName :: arbitraryData
}
```
Which has the advantage of not having to modify all the Cmd*.hs files and passing `()`s everywhere, but after some thinking I like the first solution the best.
=> Reduce duplication in CmdRun

Cabal/Distribution/Simple/Configure.hs
As mentioned in issues #4541 and #4544
=> Add detailed bad libs info to missing libs

Cabal/doc/nix-local-build.rst, cabal-install/Distribution/Client/CmdBench.hs, cabal-install/Distribution/Client/ProjectBuilding.hs, cabal-install/Distribution/Client/ProjectBuilding/Types.hs, cabal-install/Distribution/Client/ProjectOrchestration.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Client/ProjectPlanning/Types.hs, cabal-install/changelog, cabal-testsuite/PackageTests/NewBuild/CmdBench/MultipleBenchmarks/Bar.hs, cabal-testsuite/PackageTests/NewBuild/CmdBench/MultipleBenchmarks/Foo.hs, cabal-testsuite/PackageTests/NewBuild/CmdBench/MultipleBenchmarks/MultipleBenchmarks.cabal, cabal-testsuite/PackageTests/NewBuild/CmdBench/MultipleBenchmarks/cabal.out, cabal-testsuite/PackageTests/NewBuild/CmdBench/MultipleBenchmarks/cabal.project, cabal-testsuite/PackageTests/NewBuild/CmdBench/MultipleBenchmarks/cabal.test.hs
=> Make new-bench actually run the benchmarks

cabal-install/Distribution/Client/ProjectConfig.hs, cabal-install/Distribution/Client/ProjectConfig/Legacy.hs, cabal-install/Distribution/Client/ProjectConfig/Types.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
`--config-file` now works for new-* commands
=> Allow --config-file flag for new-build

Cabal/Distribution/PackageDescription.hs, Cabal/Distribution/PackageDescription/Parse.hs, Cabal/Distribution/PackageDescription/Parsec/FieldDescr.hs, Cabal/Distribution/Simple/BuildPaths.hs, Cabal/Distribution/Simple/Configure.hs, Cabal/Distribution/Simple/GHC.hs, Cabal/Distribution/Simple/Setup.hs, Cabal/Distribution/Types/BuildInfo.hs, Cabal/Distribution/Types/LocalBuildInfo.hs, Cabal/doc/installing-packages.rst, Cabal/doc/nix-local-build.rst, cabal-install/Distribution/Client/Config.hs, cabal-install/Distribution/Client/ProjectConfig/Legacy.hs, cabal-install/Distribution/Client/ProjectConfig/Types.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Client/ProjectPlanning/Types.hs, cabal-install/Distribution/Client/Setup.hs, cabal-install/changelog, cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
This adds support for GHCs `-staticlib` flag, which produces a static library that has all dependencies rolled into a massive archive.  This is rather useful when building libraries that are supposed to be deployed and linked. `-staticlib` is only available for macOS/iOS in GHC 8.2 and earlier, due to the reliance on `libtool`. With [D3721](https://phabricator.haskell.org/D3721), this will be available in GHC 8.4+ for all platforms.
=> Add staticlib

cabal-install/Distribution/Client/CmdBench.hs, cabal-install/Distribution/Client/CmdBuild.hs, cabal-install/Distribution/Client/CmdConfigure.hs, cabal-install/Distribution/Client/CmdFreeze.hs, cabal-install/Distribution/Client/CmdHaddock.hs, cabal-install/Distribution/Client/CmdRepl.hs, cabal-install/Distribution/Client/CmdRun.hs, cabal-install/Distribution/Client/CmdTest.hs, cabal-install/Distribution/Client/Setup.hs
Fixes #4581. 
With 1e90ae4380cdcef5662d933e3a34dcfef6080ec1 flags from the global
configuration would be ignored. This patch makes sure the defaults are
mixed in only for the new-build code path.
=> Use default flags only for new-* path

Cabal/doc/nix-local-build.rst, cabal-install/Distribution/Client/Config.hs, cabal-install/Distribution/Client/Configure.hs, cabal-install/Distribution/Client/Dependency.hs, cabal-install/Distribution/Client/Install.hs, cabal-install/Distribution/Client/ProjectConfig.hs, cabal-install/Distribution/Client/ProjectConfig/Legacy.hs, cabal-install/Distribution/Client/Setup.hs, cabal-install/Distribution/Client/Types.hs, cabal-install/changelog, cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
This continues the work started in  a0d8035 (#4575)
=> Augment `--allow-{newer,older}` syntax to support wildcards

Cabal/Cabal.cabal, Cabal/Distribution/PackageDescription/Check.hs, Cabal/Distribution/Simple/Program/Run.hs, Cabal/Distribution/Simple/Utils.hs, Cabal/Distribution/Utils/Generic.hs, Cabal/Distribution/Utils/IOData.hs, Cabal/changelog, Cabal/tests/UnitTests/Distribution/Simple/Utils.hs, cabal-install/Distribution/Client/Check.hs, cabal-install/Distribution/Client/IndexUtils.hs, cabal-install/Distribution/Client/Targets.hs
This refactoring is intended to clean-up various instances where `[Char]` is used to convey
something other than Unicode text. This picks up unfinished yak-shaving that was put aside when working
on #3913 ... ;-)
Note: this PR has been carefully split into self-contained commits to ease reviewing
=> Refactor/cleanup of `String`/`ByteString` usage

cabal-install/Distribution/Client/ProjectConfig/Legacy.hs, cabal-install/changelog
This fixes the inconvenience occuring in `cabal.project` files of
separate `allow-*` statements overwriting each other. Currently,
without this patch,
allow-newer: base
allow-newer: directory
is *NOT* equivalent to
allow-newer: base, directory
but rather to the last occurence of `allow-newer`, i.e.
allow-newer: directory
This behaviour has been present since cabal 1.24
----
=> Turn `allow-{newer,older}` into an accumulating field

cabal-install/Distribution/Client/Configure.hs, cabal-testsuite/PackageTests/Backpack/Includes2/setup-external.cabal.out, cabal-testsuite/PackageTests/ConfigureComponent/Exe/setup.cabal.out, cabal-testsuite/PackageTests/InternalVersions/BuildDependsBad/setup.cabal.out
Before, it would print a list of packages and append
`Trying configure anyway.`
without any separator between the list and the new sentence.
=> Add missing separator in solver fallback message

.travis.yml, cabal.project, solver-benchmarks/HackageBenchmark.hs, solver-benchmarks/LICENSE, solver-benchmarks/README.md, solver-benchmarks/main/hackage-benchmark.hs, solver-benchmarks/solver-benchmarks.cabal, solver-benchmarks/tests/HackageBenchmarkTest.hs, travis-common.sh, travis-script.sh
This benchmark is based off of a script written by @kosmikus.  It adds
functionality for running multiple trials for each package, but it is currently
missing other features.
___________________________________________________________
____________________________________________________________
I wanted to add a benchmark to make it easier to manually test changes to the solver's algorithm.  I'm not sure how it should fit into the repository and CI, though, since it currently isn't portable, and it doesn't have flexible dependency bounds.
This benchmark is meant to be used for finding packages that are affected by a change to the dependency solver when …
=> Start adding a benchmark that solves for all packages on Hackage.

Cabal/Distribution/PackageDescription/Check.hs, Cabal/Distribution/Simple/Setup.hs, Cabal/Distribution/Types/CondTree.hs, Cabal/Distribution/Utils/Generic.hs, Cabal/changelog, Cabal/doc/developing-packages.rst
=> cabal check flag names

Cabal/Distribution/Parsec/Types/ParseResult.hs
Noticed one (possibly) low-hanging fruit.
Try to parse whole Hackage (`index-01.tar`)
```
parser-hackage-tests parse-parsec +RTS s
```
In short: with CPS it takes less memory, but seems that a bit more time. Though memory measurement is exact, time isn't.
`ParseResult` is a monad where parsing from outer-format `[Field]` (think `Value`), is elaborated into `GenericPackageDescription`
Note: I really have to profile, but atm I'm out of time. This is very local change, so could wait.
```
294,510,120,352 bytes allocated in the heap
24,907,645,200 bytes copied during GC
12,271,240 bytes maximum residency (5899 sample(s))
976,336 bytes maximum slop
25 MB total memory in use (0 MB lost due to fragmentation)
Tot time (elapsed)  Avg pause  Max pause
Gen  0     565906 colls,     0 par   28.432s …
```
=> CPSise ParseResult

Cabal/Cabal.cabal, Cabal/Distribution/Compat/Lens.hs, Cabal/Distribution/PackageDescription/Check.hs, Cabal/Distribution/PackageDescription/Parsec.hs, Cabal/Distribution/Types/Benchmark.hs, Cabal/Distribution/Types/BuildInfo.hs, Cabal/Distribution/Types/BuildInfo/Lens.hs, Cabal/Distribution/Types/Component.hs, Cabal/Distribution/Types/Executable.hs, Cabal/Distribution/Types/ForeignLib.hs, Cabal/Distribution/Types/GenericPackageDescription/Lens.hs, Cabal/Distribution/Types/Library.hs, Cabal/Distribution/Types/PackageDescription/Lens.hs, Cabal/Distribution/Types/TestSuite.hs, Cabal/changelog, Cabal/tests/ParserHackageTests.hs
This patch introduces `Distribution.Compat.Lens`, a small portion of `lens`. The need is two fold:
- to provide lenses to users of `Cabal`
- to use it internally in places where lenses shine (subjectively, see `Check.hs`)
The design is simple:
- `Distribution.Compat.Lens` have some definitions from `lens`.
- type modules have sibling `.Lens` module which exports the type and lenses, with the same name as fields. Users can either
```haskell
import Distribution.Types.PackageDescription
import qualified Distribution.Types.PackageDescription.Lens as L
```
or
```haskell
import Distribution.Types.PackageDescription.Lens
```
Latter variant is not yet viable, as not everything is lensified. But we can make progress there quite easily.
To better compare lens and "old-school" Haskell approaches see …
=> Introduce Distribution.Compat.Lens

Cabal/Distribution/Simple/Setup.hs
This was introduced by f8dc46a0fe68e35ec0397da92d7e9d4f168aa126 which
resulted in passing `--flags=+foo` to older custom setup scripts which
wouldn't recognize the `+` prefix.
This was reported by @cocreature
=> Fix minor regression in flag assignment marshalling to custom-setup

cabal-install/Distribution/Client/PackageHash.hs, cabal-install/Distribution/Client/ProjectBuilding.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Client/Store.hs, cabal-install/changelog, cabal-install/tests/UnitTests/Distribution/Client/Store.hs
This is a stab at #4263 as an alternative to #4426.
The general strategy is:
- put all libraries into `$store/lib`. This though makes them not prefix relocatable anymore.
I'm fine with that for macOS.
- As that is not enough to stay under the load command limit for my tiny sample app, we
mutilate the package name as well. We cut the abi hash to 4 byte 😱 and drop vowels.
We can not drop the `-ghcX.Y.Z` suffix it seems as GHC seems to append that on it's own.
This then produces only one `@rpath` entry to `$HOME/.cabal/store/ghc-x.y.z/lib`. And thus
saving quite a bit already.
The alternative strategy I though of was to rename only the dynamic library to …
=> Put libraries into $store/lib

Cabal/doc/installing-packages.rst, Cabal/doc/nix-local-build.rst
The relevant code for this can be found in https://github.com/haskell/cabal/blob/master/Cabal/Distribution/Simple/GHC/Internal.hs#L280. Thanks to @hvr for pointing me to it.
=> Document that Cabal passes -O2 to C compilers

Cabal/Distribution/PackageDescription/Check.hs
In order to migrate from pre `scope` Setup.hs hacks to 2.0 we would like
to specify both `scope` and `x-scope` (as just `scope` can't be accessed
from Setup.hs AFAIK) and handle Cabal<2.0 with custom logic. However
this check makes this undistributable as hackage rejects such packages.
=> Demote 'scope' field version check to a warning

Cabal/Distribution/Simple/GHC/ImplInfo.hs, Cabal/Distribution/Simple/GHC/Internal.hs, Cabal/Distribution/Simple/Program/GHC.hs
These are supported by GHC 8.0 and later and will soon (probably GHC 8.4)
actually affect the compiler's output.
Note that I haven't tested this yet but I'm putting it here so I don't forget about it.
=> Add support for GHC's numeric -g debug levels

Cabal/Distribution/Verbosity.hs, cabal-install/Distribution/Client/Install.hs, cabal-install/Distribution/Client/ProjectConfig.hs
This fixes a case where the log-output "In order, the following would be
installed: ..." would fail to honor verbosity flags.
=> Fix verbosity flags getting removed before being passed to `printPlan`

Cabal/Distribution/Compat/Parsec.hs, Cabal/Distribution/Parsec/Class.hs, Cabal/Distribution/Version.hs, Cabal/tests/UnitTests/Distribution/Version.hs
foldVersionRange' recognises (> x || == v)  and (== x || > x) as
(>= v), and similarly for <=. Therefore `simpleParsec . display` isn't
structurally `id`, but `normalizeVersionRange`.
=> Add normaliseVersionRange

Cabal/Distribution/Compat/Newtype.hs, Cabal/Distribution/Verbosity.hs, Makefile
This is poor man doctest.
ping @hvr @23Skidoo 
Prerequisites:
- `doctest` executable is in `$PATH`, compiled with GHC used to
new-build the Cabal
- `.ghc.environment` file is generated
As GHC picks up dependencies from `.ghc.environment` file, a simple
`doctest MODULES` works.
As you see, I had a bug in doctests. For now, I don't add this to CI,
as it's enough to run doctests occasionally (there are only 4 examples
atm).
=> Add make doctest [ci skip]

Cabal/Distribution/Types/PackageDescription.hs, Cabal/changelog
This is the same modification I just made to the Stack codebase, which caused an integration test to pass.
=> Include foreign libs in allBuildInfo (fixes #4763)

cabal-install/Distribution/Client/DistDirLayout.hs, cabal-install/changelog, cabal-testsuite/PackageTests/TestSuiteTests/ExeV10/cabal.out
This has been a pet-peeve of mine since 1.24 but I forgot to address
this in time for the 2.0 release, as it conflates all the component
kinds into an opaque single "c" namespace thereby losing information,
rather than encoding the component type in a more expressive single
letter path component.
=> Differentiate letter for the dist-dir layout of components

cabal-install/Distribution/Client/Targets.hs, cabal-install/changelog
Previously, a command like
cabal install uHttpc
would silently auto-correct this to
cabal install uhttpc
However, this is inconsistent as `build-depends` or `constraints`
are not case-insensitive.
So with this patch,
cabal install VULKAN uHttpc
result in the following error(s) instead:
There is no package named 'VULKAN'. However, the following package names exist: 'Vulkan', 'vulkan'.
There is no package named 'uHttpc'. However, the following package name exists: 'uhttpc'.
=> Don't automatically case-correct mispelled package-names

appveyor.yml, travis-install.sh
=> appveyor.yml: Use cabal-install-2.0.0.0 binary.

cabal-install/Distribution/Solver/Modular/Assignment.hs, cabal-install/Distribution/Solver/Modular/Builder.hs, cabal-install/Distribution/Solver/Modular/Cycles.hs, cabal-install/Distribution/Solver/Modular/Dependency.hs, cabal-install/Distribution/Solver/Modular/Flag.hs, cabal-install/Distribution/Solver/Modular/IndexConversion.hs, cabal-install/Distribution/Solver/Modular/Linking.hs, cabal-install/Distribution/Solver/Modular/Message.hs, cabal-install/Distribution/Solver/Modular/Preference.hs, cabal-install/Distribution/Solver/Modular/Solver.hs, cabal-install/Distribution/Solver/Modular/Validate.hs, cabal-install/Distribution/Solver/Modular/Var.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs, cabal-testsuite/PackageTests/Backpack/Includes2/setup-external.cabal.out, cabal-testsuite/PackageTests/ConfigureComponent/Exe/setup.cabal.out
_____________________________________________________________________________________________________
This change is necessary to remove the package instance (I) from Var
(issue #4142).  One of the main uses of the package instance is when varPI is
called by the linking phase in order to get the dependencies introduced by flags
and stanzas.  The validation phase also needs to look up dependencies introduced
by flags and stanzas, but it does so by looking up the dependencies once when it
chooses a package and then storing the dependencies in a map.  I refactored the
linking phase to also store dependencies in a map.
This change has several effects:
- The …
=> Remove the package instance from D.Solver.Modular.Var (closes #4142).

Cabal/Language/Haskell/Extension.hs
These extensions were introduced in GHC 8.2.1.
=> Add DerivingStrategies and UnboxedSums to Language

Cabal/Distribution/Simple/GHC.hs, cabal-testsuite/PackageTests/Backpack/T4754/P.hs, cabal-testsuite/PackageTests/Backpack/T4754/Sig.hsig, cabal-testsuite/PackageTests/Backpack/T4754/p.cabal, cabal-testsuite/PackageTests/Backpack/T4754/pexe/PExe.hs, cabal-testsuite/PackageTests/Backpack/T4754/setup.cabal.out, cabal-testsuite/PackageTests/Backpack/T4754/setup.out, cabal-testsuite/PackageTests/Backpack/T4754/setup.test.hs
I am not sure what I was thinking when I modified the
code to skip profiling builds if there was no code,
but this is surely wrong!  Comes with a test.
Fixes #4754.
=> Make Backpack work with profiling.

Cabal/Distribution/Types/UnitId.hs
=> Use a handwritten Parsec instance for DefUnitId.

cabal-install/Distribution/Solver/Modular/Builder.hs
#4562 removed one of PotentialGoal's two fields, so now it is easier to just use
the other field's type, FlaggedDep QPN.
=> Solver: Remove PotentialGoal type.

cabal-install/Distribution/Client/SetupWrapper.hs
See https://github.com/haskell/cabal/commit/e2bf243300957321497353a2f85517e464f764ab#commitcomment-24487898.
=> SetupWrapper: Assume that old Cabals bootstrap.

Cabal/Cabal.cabal, Cabal/changelog
Tested using a bootstrap of GHC. I couldn't find a changelog file so don't know where to add the version bump.
=> Cabal: Bump Win32 version bounds for GHC 8.4

Cabal/Makefile, Cabal/doc/README.md, Cabal/doc/conf.py, Cabal/doc/nix-local-build.rst
- Fix Makefile to work on arch where we need to use sphinx-build2
- README: mention python 2 and use Makefile
- html output now properly links to github source
- new-freeze documentation fixed for the --project-file case
fixes #4833, #4834 [ci skip]
Tested by running "make users-guide" and looking at the html.
=> doc: Makefile, Add proper source link, Add to new-freeze

Cabal/doc/nix-local-build.rst, cabal-install/Distribution/Client/CmdUpdate.hs, cabal-install/Distribution/Client/Setup.hs, cabal-install/Distribution/Client/Types.hs, cabal-install/cabal-install.cabal, cabal-install/changelog, cabal-install/main/Main.hs
new-update uses the new-style logic to update the repositories.  As such it
respects `repository` fields in the `cabal.project(.local)` file and updates
them as well.  This is essential when working with hackage overlays, where
the overlay repositories are specified as `repository` fields in the
`cabal.project(.local)` file.
=> Adds `new-update`

Cabal/Distribution/Types/GenericPackageDescription.hs
See https://github.com/haskell/cabal/issues/4808#issuecomment-337048211
=> RFC: Potential fix for #4808

cabal-install/Distribution/Client/Security/DNS.hs, cabal-install/bootstrap.sh, cabal-install/cabal-install.cabal
This avoids calling out to an external `nslookup` program and having
to screen scrape its output. The `resolv` library supports all
platforms which provide the ubiquitous `libresolv` API.
This is hidden behind the manual cabal flag `resolv` which is
currently disabled by default.
=> Implement native DNS hackage-security bootstrap via resolv/windns packages

README.md
I notice imports like
import qualified Text.PrettyPrint as Disp
( Doc, render, char, text )
which seem overly precise to me, when `Disp.` is only used
locally as a module prefix, and there's no other imports sharing
the same module prefix.
Instead, it should suffice to either use
import qualified Text.PrettyPrint as Disp
or
import Text.PrettyPrint
( Doc, render, char, text )
or in rare cases even
import Text.PrettyPrint as Disp
( Doc, render, char, text )
Hence this relaxes the coding guidelines to allow these simpler forms
to be used.
=> RFC: Relax coding guideline regarding module imports

cabal-install/Distribution/Client/CmdBench.hs, cabal-install/Distribution/Client/CmdErrorMessages.hs, cabal-install/Distribution/Client/CmdInstall.hs, cabal-install/Distribution/Client/CmdRun.hs, cabal-install/Distribution/Client/CmdTest.hs, cabal-install/Distribution/Client/Dependency.hs, cabal-install/Distribution/Client/List.hs, cabal-install/Distribution/Client/ProjectConfig.hs, cabal-install/Distribution/Client/ProjectOrchestration.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Client/TargetSelector.hs, cabal-install/Distribution/Client/Targets.hs, cabal-install/Distribution/Client/Types.hs, cabal-install/cabal-install.cabal, cabal-install/changelog, cabal-install/main/Main.hs, cabal-install/tests/IntegrationTests2.hs, cabal-testsuite/PackageTests/NewBuild/CmdRun/Single/cabal.out
Add the first part of the new-install command: nonlocal exes.
See #4558 for the design concept.
This part of the command installs executables from outside of a project
(ie from hackage) in the store and then symlinks them in the cabal bin
directory.
This is done by creating a dummy project and adding the targets as extra
packages.
---
---
Some questions:
* How do I test this? A package test would probably require hackage access. Is there a way to add a local source?
* Is the dummy project thing the right way of doing this? And should I put that code in a more generic module? Or maybe I should substitute the dummy project with some sort of global project?
* How do I get the default `~/.cabal/bin` directory? I couldn't find it in the old install command. Is it hardcoded somewhere? Do I have …
=> new-install: nonlocal exes

Cabal/Distribution/Simple.hs
=> Adds defaultMainWithHooksNoReadArgs

cabal-install/Distribution/Client/CmdFreeze.hs, cabal-testsuite/PackageTests/NewFreeze/cabal.project, cabal-testsuite/PackageTests/NewFreeze/my-local-package.cabal, cabal-testsuite/PackageTests/NewFreeze/new_freeze.out, cabal-testsuite/PackageTests/NewFreeze/new_freeze.test.hs, cabal-testsuite/PackageTests/NewFreeze/repo/my-build-tool-dep-1.0/my-build-tool-dep.cabal, cabal-testsuite/PackageTests/NewFreeze/repo/my-build-tool-dep-2.0/my-build-tool-dep.cabal, cabal-testsuite/PackageTests/NewFreeze/repo/my-build-tool-dep-3.0/my-build-tool-dep.cabal, cabal-testsuite/PackageTests/NewFreeze/repo/my-library-dep-1.0/my-library-dep.cabal
new-freeze produces constraints that allow all versions of each package from the
install plan, in order to constrain setup and build tool dependencies without
using qualified constraints. Since the constraints should apply to top-level,
setup, and build tool dependencies, they should use an 'any' qualifier.
I also added a package test for new-freeze.
=> Apply 'any' qualifier to new-freeze constraints (fixes #4832).

Cabal/Distribution/PackageDescription/Check.hs, Cabal/Distribution/PackageDescription/FieldGrammar.hs, Cabal/Distribution/PackageDescription/Parse.hs, Cabal/Distribution/ParseUtils.hs, Cabal/Distribution/Simple/BuildPaths.hs, Cabal/Distribution/Simple/BuildTarget.hs, Cabal/Distribution/Simple/GHC.hs, Cabal/Distribution/Simple/Register.hs, Cabal/Distribution/Types/BuildInfo.hs, Cabal/Distribution/Types/BuildInfo/Lens.hs, Cabal/doc/developing-packages.rst, Cabal/doc/installing-packages.rst
So this is primarily, so that I can give the `rts` package `rts.cabal` file.
But I believe these have uses outside of the rts as well.
=> Add s/cmm-sources + extra-bundled-libraries

cabal-install/Distribution/Client/Config.hs
globalCacheDir (remote-repo-cache) is now initialized by default because only
cabal-install can determine the correct default location relative to
defaultCabalDir. The globalLogsDir (build-logs) and globalWorldFile (world-file)
already had the same behavior.
Resolves: #4845.
I tested this change by removing the `remote-repo-cache` line from my `$HOME/.cabal/config` and confirming that a simple `cabal update` works. (This command requires `remote-repo-cache` to be set.)
=> Initialize globalCacheDir in baseSavedConfig

Cabal/Distribution/Simple/Install.hs, Cabal/changelog
When installing a lirbary, we should look for it's headers in it's 'build' preference first, then relative to the current path.
=> Look for install includes in buildpref as well

cabal-install/Distribution/Client/CmdInstall.hs
And error if they are explicitly enabled, so we never try to install
remote packages with tests and/or benchs.
Fixes #4855
...no tests for new-install yet
=> Disable tests and benchs by default on new-install

Cabal/Distribution/PackageDescription/FieldGrammar.hs, Cabal/Distribution/PackageDescription/Parse.hs, Cabal/Distribution/Simple/Register.hs, Cabal/Distribution/Types/BuildInfo.hs, Cabal/Distribution/Types/BuildInfo/Lens.hs, Cabal/changelog, Cabal/doc/developing-packages.rst
This used to be done in `ghc-cabal`. With the long term goal of getting rid of ghc-cabal eventually, it's functionality needs to end up in cabal.
While this is a custom hack, it is restricted to the GHC module only. A more generic solution would be to add `virtual-modules` I suppose. GHC does custom handling for `GHC.Prim`, and there is no support for `virtual-modules` in the package config file either as far as I can see. As such this seems to be the least invasive solution.
=> Adds `virtual-modules` to handle cases like `GHC.Prim` from `ghc-prim`.

Cabal/Language/Haskell/Extension.hs, Cabal/changelog
This is #4858 by @bgamari, with the `changelog` corrected.
=> Extension: Add HexFloatLiterals

Cabal/Distribution/PackageDescription/Check.hs
As pointed out by @hvr, #4857, #4875 did not contain the necessary "check" logic. This PR tries to address this shortcoming.
=> Add `checkVersion` for added fields

Cabal/Distribution/Simple/GHC.hs, Cabal/changelog, cabal-testsuite/PackageTests/COnlyMain/foo.c, cabal-testsuite/PackageTests/COnlyMain/my.cabal, cabal-testsuite/PackageTests/COnlyMain/setup.cabal.out, cabal-testsuite/PackageTests/COnlyMain/setup.out, cabal-testsuite/PackageTests/COnlyMain/setup.test.hs
Do not try to call GHC on an empty set of `inputModules`.
Fixes #4890
=> Allow empty set of input modules.

README.md
I've so often failed to find that link. Let's just add it to the readme.
[skip ci]
=> Add binary distribution download link to Readme

Cabal/Distribution/Simple/Register.hs
After using this for a while. It occured to me that due to linker ordering, and GHC just forwarding the libraries as specified in the `hsLibraries` field, we should put the `extraBundledLibs` at the end. As such the haskell library can reference the `extraBundledLibs`.
This still leave the question of recursively linked libs. But getting that linked right should rather be deal with in GHC, which optimally would use being and end groups for the libraries to link.
=> Change order of hsLibraries

Cabal/Distribution/PackageDescription/Check.hs, Cabal/Distribution/Simple/Configure.hs, Cabal/Distribution/Simple/GHC/Internal.hs, Cabal/Distribution/Simple/Program/GHC.hs, Cabal/Distribution/Simple/Setup.hs, Cabal/Distribution/Types/LocalBuildInfo.hs, Cabal/changelog, Cabal/doc/nix-local-build.rst, cabal-install/Distribution/Client/Config.hs, cabal-install/Distribution/Client/PackageHash.hs, cabal-install/Distribution/Client/ProjectConfig/Legacy.hs, cabal-install/Distribution/Client/ProjectConfig/Types.hs, cabal-install/Distribution/Client/ProjectPlanning.hs, cabal-install/Distribution/Client/ProjectPlanning/Types.hs, cabal-install/Distribution/Client/Setup.hs, cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
Add --enable-split-sections flag and pipe it through to the GHC backend. Note
that some of the implementation here could be made a bit more precise:
-split-sections and -split-objs are mutually exlusive yet the types don't
currently reflect this.
Fixes #4819.
=> Split sections support

cabal-install/Distribution/Client/IndexUtils.hs
This provides a provisional (i.e. hacky) retrofitted implementation of
the forward-compat scheme described in #4899 for the cabal-2.0 branch.
This hack works by constructing a dummy package description in case
the package description fails to be parsed via the standard parser,
and we detect a new-style cabal-spec declaration.
=> Implement preliminary support for new forward-compat scheme

cabal-testsuite/cabal-testsuite.cabal
=> Relax bounds for aeson and optparse-applicative in test-suite

cabal-install/Distribution/Solver/Modular/IndexConversion.hs, cabal-install/Distribution/Solver/Modular/Message.hs, cabal-install/Distribution/Solver/Modular/Tree.hs, cabal-testsuite/PackageTests/CustomWithoutCabal/custom-setup-without-cabal.cabal, cabal-testsuite/PackageTests/Regression/T3436/custom-setup/custom-setup.cabal
This is a forward-port of #4907
=> Have the solver reject packages with a too-new/unsupported spec-version

Makefile, cabal-dev-scripts/LICENSE, cabal-dev-scripts/Setup.hs, cabal-dev-scripts/cabal-dev-scripts.cabal, cabal-dev-scripts/src/GenExtraSourceFiles.hs, cabal.project.meta, travis-install.sh, travis-meta.sh
this way we have proper bounds, and `make gen-extra-source-files`.
---
=> Turn gen-extra-source-files into proper package

Cabal/Distribution/Simple/Program/Hpc.hs
Prior to GHC 8.0, hpc requires relative search paths. We now pass relative paths
in all cases; we do not want to separately condition on GHC and HPC versions.
Frankly, it is surprising that this ever worked.
I tested this on #4902, but I am making a separate pull request because this bugfix needs to be backported as far as possible.
=> D.S.Program.Hpc: Use relative .mix search paths

Cabal/Distribution/Simple/Build.hs
The stub executable is linked against the test-library
which already contains all `other-modules`, so we need
to remove those from the stub-exe's build-info to avoid
build errors due to duplication.
This addresses #4918
=> Don't pass `other-modules` to stub executable for detailed-0.9

cabal-testsuite/PackageTests/CustomWithoutCabal/cabal.test.hs, cabal-testsuite/PackageTests/CustomWithoutCabalDefaultMain/cabal.test.hs, cabal-testsuite/PackageTests/Regression/T3436/Cabal-1.2/Cabal.cabal, cabal-testsuite/PackageTests/Regression/T3436/Cabal-1.2/CabalMessage.hs, cabal-testsuite/PackageTests/Regression/T3436/Cabal-2.0/Cabal.cabal, cabal-testsuite/PackageTests/Regression/T3436/Cabal-2.0/CabalMessage.hs, cabal-testsuite/PackageTests/Regression/T3436/Cabal-99998/CabalMessage.hs, cabal-testsuite/PackageTests/Regression/T3436/Cabal-99999/CabalMessage.hs, cabal-testsuite/PackageTests/Regression/T3436/cabal.out, cabal-testsuite/PackageTests/Regression/T3436/cabal.project, cabal-testsuite/PackageTests/Regression/T3436/cabal.test.hs, cabal-testsuite/PackageTests/Regression/T3436/custom-setup/custom-setup.cabal, cabal-testsuite/PackageTests/Regression/T3436/sandbox.out, cabal-testsuite/PackageTests/Regression/T3436/sandbox.test.hs
Some comments were lost in the migration to the new integration test suite.
=> Restore a few integration test comments and new-build package arguments.

cabal-install/Distribution/Client/ProjectPlanning.hs
Sent by `f-a` on IRC (#hackage) http://www.ariis.it/link/t/0001-Do-not-create-folders-when-failing-on-no-.project-or.patch
```
12:55 < f-a> btw, I am doing this to fix a minor annoyance of mine with cabal-install
12:55 < f-a> if you run, say, `cabal new-build` in an unrelated folder
12:55 < f-a> cabal creates dist-newstyle folder before exiting with error
12:56 < hvr> even if there isn't any .cabal file around?
12:56 < f-a> yup
12:56 < hvr> ok, that's nasty
12:56 < f-a> f@x60s:~$ cd ~/
12:56 < f-a> f@x60s:~$ cabal new-build
12:56 < f-a> No cabal.project file or cabal file matching the default glob './*.cabal' was found.
12:56 < f-a> Please create a package description file <pkgname>.cabal or a cabal.project file referencing the packages you want to 
build.
12:56 < f-a> f@x60s:~$ lsc
12:56 …
```
=> Do not create folders when failing on no .project or .cabal file

Cabal/Cabal.cabal, Cabal/Distribution/Utils/Generic.hs, Cabal/Distribution/Utils/String.hs, Cabal/tests/UnitTests.hs, Cabal/tests/UnitTests/Distribution/Utils/Generic.hs
This should finally address #4644
=> Modify replacement properties of `encodeStringUtf8`/`decodeStringUtf8`

cabal-install/Distribution/Client/Init.hs, cabal-install/Distribution/Client/Init/Types.hs, cabal-install/Distribution/Client/Setup.hs
@cartazio @hvr This is the initial proposed change for allowing users to initialize their .cabal to have both a library and executables. I will be adding the changelog in a following commit.
=> Initial feature add: create both Library and Executable on cabal init

Cabal/Distribution/Verbosity.hs, travis-script.sh
I don't think it ever uncovered any bugs that the Linux bot missed. This should speed up the build a little.
=> Skip the Haddock step on macOS.

.travis.yml, cabal-install/bootstrap.sh
=> travis-ci: bootstrap on 8.2.2 as well
