- Cabal/Language/Haskell/Extension.hs
> Register GHC 7.10 extensions.

- Cabal/Cabal.cabal
- Cabal/Distribution/Simple.hs
- Cabal/Distribution/Simple/Build.hs
- cabal-install/bootstrap.sh
- cabal-install/cabal-install.cabal
This will make it easier to build 7.8 using 7.10
> Backport some changes to make 1.18 build with GHC 7.10

- Cabal/Distribution/Simple/Build.hs
> Gracefully handle leftover single file inplace databases, fixes #2301

- .gitignore
- Cabal/.gitignore
- Cabal/tests/PackageTests/.gitignore
- make some paths non-global via / prefix
- remove redundancies
- add /Cabal/Setup and /cabal-install/Setup
> Clean up .gitignore files, add ignore for Setup

- Cabal/Distribution/Package.hs
> Fully specify package key format, so external tools can generate it.

- Cabal/Distribution/Simple/Program/Builtin.hs
- Cabal/Distribution/Simple/Program/Strip.hs
Fixes #2339 
Tested on Yosemite, Windows 7, CentOS 5 32/64-bit, CentOS 6 32/64-bit
The only thing I don't feel 100% about here is how we parse the numeric version out of the `strip --version` output. It's pretty inconsistent between platforms and versions and how the binutils were built, so we try to parse the first numeric word of the output and pull out a major and minor version for comparison. At worst this will prevent library stripping from working on 32-bit Linux systems with non-standard `strip --version` output.
> Avoid broken `strip` versions on 32-bit Linux

- Cabal/Distribution/Simple/Program/Strip.hs
per @23Skidoo's suggestion in #2356
> Build a Version the right way in Strip module

- Cabal/Distribution/PackageDescription/PrettyPrint.hs
> Remove 'condTreeConstraints' field from pretty printing

- cabal-install/Main.hs
Fixes #2357 for test suites and benchmarks.
Just checking the tests on Travis...
> Skip unbuildable tests and benchmarks

- Cabal/Distribution/Simple/Configure.hs
Especially clarify when the FilePath argument is the dist directory or the setup-config file, since I found it quite confusing when using that API.
> Add and fix the documentation.

- Cabal/Distribution/Simple/Haddock.hs
This in conjunction with the next haddock release should fix https://github.com/haskell/cabal/issues/2297.
> Haddock: Use --package-{name|version} when available

- Cabal/Distribution/System.hs
fixes haskell/hackage-server#269
> add GNU Hurd OS

- Cabal/Distribution/Package.hs
- Cabal/Distribution/Simple/Configure.hs
> Put full package name and version in library names, fixes #2437.

- Cabal/tests/PackageTests/TestSuiteExeV10/Check.hs
Starting with version 7.10, GHC puts the module interface (.mix) files
for each project in a subdirectory of -hpcdir named for the package
key. We must adjust the search path accordingly when checking for the
.mix file.
Fixes #2457. Waiting on Travis.
> fix HPC tests with GHC 7.10

- Cabal/Cabal.cabal
- Cabal/Distribution/Simple/Setup.hs
- Cabal/Makefile
- cabal-install/Distribution/Client/Setup.hs
- cabal-install/cabal-install.cabal
> Don't pass '--{en,dis}able-profiling' to old setup exes.

- Cabal/Distribution/Simple/PackageIndex.hs
This fixes some warnings on GHC HEAD. @edsko, is it OK to remove these constraints?
> -Wall police

- HACKING.md
> Fix HACKING.md description of how to run tests

- Cabal/Distribution/Simple/Build/PathsModule.hs
> Paths_ module: don't require base >= 4.

- cabal-install/Distribution/Client/HttpUtils.hs
Fixes #1962.
Just checking if this compiles on Travis...
> Print a more friendly message when http_proxy is down.

- cabal-install/Distribution/Client/Setup.hs
> Doc fix: 'cabal freeze PACKAGES' is not supported.

- cabal-install/Distribution/Client/Init.hs
Looks a little more meaningful rather than after comments flag.
> Move SrcDirs following Main file generator.

- cabal-install/Distribution/Client/Install.hs
This improves the install-plan reporting in `cabal install -v2`'s output
to include reverse-dependencies, thereby giving valuable information why
a package was included in the install-plan to begin with.
Moreover, this also disables line-wrapping for the install-plan for
verbosity `verbose` and greater, to make the output easier to parse
for humans as well as computers
Example output for `cabal install --dry -v2 http-client`:
```
In order, the following would be installed:
base64-bytestring-1.0.0.1 (via: http-client-0.4.11.2) (new package)
data-default-class-0.0.1 (via: http-client-0.4.11.2 cookie-0.4.1.5) (new package)
mtl-2.2.1 (via: exceptions-0.8.0.2 parsec-3.1.9) (new package)
network-2.6.0.2 (via: http-client-0.4.11.2 streaming-commons-0.1.12) (new package)
old-locale-1.0.0.7 (via: …
```
> Add dependency-graph information to `printPlan` output

- Cabal/doc/developing-packages.markdown
> Document 'extensions' field replacements

- Cabal/Distribution/PackageDescription/Check.hs
- Cabal/Distribution/Simple/Utils.hs
- cabal-install/Distribution/Client/IndexUtils.hs
- cabal-install/Distribution/Client/Targets.hs
Implements first bullet point of #2573
It seems that second point is implemented already, the BOM is ignored.
> Make cabal check warn about BOM

- Cabal/Distribution/Simple/Command.hs
- Cabal/Distribution/Simple/Setup.hs
- cabal-install/Distribution/Client/Init.hs
- cabal-install/Distribution/Client/Setup.hs
followup to my previous efforts (see #2259)
originally i had planned to wait for #2344 (so i could include #2345), but ran out of patience; instead i added a  temporary fix to the package-db description including the warning that "The exact behaviour (especially the initial list) is not clearly defined at this point."
> commandline documentation

- cabal-install/Distribution/Client/BuildReports/Upload.hs
- cabal-install/Distribution/Client/Config.hs
- cabal-install/Distribution/Client/Fetch.hs
- cabal-install/Distribution/Client/FetchUtils.hs
- cabal-install/Distribution/Client/Freeze.hs
- cabal-install/Distribution/Client/Get.hs
- cabal-install/Distribution/Client/HttpUtils.hs
- cabal-install/Distribution/Client/Install.hs
- cabal-install/Distribution/Client/List.hs
- cabal-install/Distribution/Client/Setup.hs
- cabal-install/Distribution/Client/Targets.hs
- cabal-install/Distribution/Client/Types.hs
- cabal-install/Distribution/Client/Update.hs
- cabal-install/Distribution/Client/Upload.hs
- cabal-install/Distribution/Client/Utils.hs
- cabal-install/Main.hs
- cabal-install/cabal-install.cabal
- cabal-install/changelog
Merge of #2613 plus additional reformatting, refactoring, fixing a few things and changing the behaviour of when we automatically try to use https.
> Gbaz https

- cabal-install/Distribution/Client/Exec.hs
This is a *partial* fix to #2381 so that it at least warns for non-existent $GHC_PACKAGE_PATH on "cabal exec"
> Warn if GHC{,JS}_PACKAGE_PATH points to non-directory

- cabal-install/Distribution/Client/SetupWrapper.hs
The design called for allowing deps to be specified, and for the
Setup.hs to be able to use the same version macros as in other code.
This patch completes that second part.
Setup.hs scripts have to declare {-# LANGUAGE CPP #-} if they want to use it, and they have to have a custom-setup stanza.
> Use the version macros when building Setup.hs

- Cabal/Cabal.cabal
- cabal-install/cabal-install.cabal
Found by building from the source dist tarballs.
> Add missing test modules

- cabal-install/Distribution/Client/Init.hs
> cabal init: generate less for PublicDomain

- Cabal/Distribution/Simple/Build.hs
- Cabal/tests/PackageTests/BuildTestSuiteDetailedV09/Check.hs
- Cabal/tests/PackageTests/BuildTestSuiteDetailedV09/Dummy2.hs
- Cabal/tests/PackageTests/BuildTestSuiteDetailedV09/my.cabal
> Properly use test name for test libraries, with updated test.

- cabal-install/Distribution/Client/BuildReports/Storage.hs
- cabal-install/Distribution/Client/Configure.hs
- cabal-install/Distribution/Client/Dependency.hs
- cabal-install/Distribution/Client/Dependency/Modular.hs
- cabal-install/Distribution/Client/Dependency/Modular/ConfiguredConversion.hs
- cabal-install/Distribution/Client/Dependency/TopDown.hs
- cabal-install/Distribution/Client/Dependency/TopDown/Types.hs
- cabal-install/Distribution/Client/Dependency/Types.hs
- cabal-install/Distribution/Client/Fetch.hs
- cabal-install/Distribution/Client/Freeze.hs
- cabal-install/Distribution/Client/Get.hs
- cabal-install/Distribution/Client/IndexUtils.hs
- cabal-install/Distribution/Client/Install.hs
- cabal-install/Distribution/Client/InstallPlan.hs
- cabal-install/Distribution/Client/InstallSymlink.hs
- cabal-install/Distribution/Client/List.hs
- cabal-install/Distribution/Client/PackageIndex.hs
- cabal-install/Distribution/Client/PlanIndex.hs
- cabal-install/Distribution/Client/Targets.hs
- cabal-install/Distribution/Client/Types.hs
- cabal-install/Distribution/Client/Utils/LabeledGraph.hs
- cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/DSL.hs
#2733 with conflicts resolved. Just checking that the Travis build passes. CR comments are in #2733.
> Refactoring installplan

- Cabal/Distribution/Simple/GHC.hs
- Cabal/changelog
Not sure if there's a plan for another 1.22 release, but if so it would be great to have this on board.
> Cherry-pick "Don't recompile C files unless needed"

- Cabal/Distribution/Simple/GHC.hs
- Cabal/Distribution/Simple/Program/GHC.hs
Alternative solution to https://github.com/haskell/cabal/pull/2776
> Resolve #2772: generate database flags (may omit global db)

- Cabal/Distribution/Simple/Utils.hs
> Don't print ExitCode in topHandlerWith

- Cabal/Distribution/PackageDescription/Check.hs
- cabal-install/Distribution/Client/Init.hs
- cabal-install/Distribution/Client/Init/Heuristics.hs
- cabal-install/tests/PackageTests/Freeze/Check.hs
I don't like TODO markers, but at least this is more consistent.
> Change "XXX" markers to "TODO"

- Cabal/Cabal.cabal
- cabal-install/cabal-install.cabal
> Bump the upper bound on 'process'.

- Cabal/Distribution/Simple/Test/LibV09.hs
- Cabal/Distribution/Simple/Utils.hs
This commit changes the way that Setup creates the `stdin` handle for the detailed test subprocess.  It allows `System.Process.createProcess` to create the handle, instead of passing in a handle from `D.Compat.CreatePipe.createPipe`.
I also added the function `D.S.Utils.createProcessWithEnv`, which is more general than the existing `rawSystemIOWithEnv`.
This change also allows Setup to run detailed tests when it is not compiled with `-threaded`.
/cc @ttuegel
> Prevent detailed-0.9 test suites from freezing on Windows (fixes #2762)

- Cabal/Cabal.cabal
> Don't bootstrap Cabal, fixing #2845.

- Cabal/tests/PackageTests.hs
- Cabal/tests/PackageTests/PackageTester.hs
Prior to this patch, the testsuite used your global package db, and
sometimes, the inplace package db, which led to errors if you didn't
have old-time installed globally. They looked like this:
BuildDeps/SameDepsAllRound:          Cabal result was Result {successful = False, success = Failure, outputText = "\"/home/enolan/cabal/Cabal/tests/Setup configure --user -w  /home/enolan/.nix-profile/bin/ghc\" in PackageTests/BuildDeps/SameDepsAllRound\nConfiguring SameDepsAllRound-0.1...\nSetup: At least the following dependencies are missing:\nold-time -any\n"}
> Carry package dbs into testsuite

- .travis.yml
Should speed up the Travis build a little.
> Use a common sandbox for building Cabal and cabal-install.

- cabal-install/cabal-install.cabal
as there now is custom code is Setup.hs
> Set Build-type: Custom

- Cabal/Distribution/Simple/Setup.hs
- Cabal/Distribution/Simple/Test/ExeV10.hs
- Cabal/changelog
- Cabal/tests/PackageTests.hs
- Cabal/tests/PackageTests/TestSuiteTests/ExeV10/Check.hs
- Cabal/tests/PackageTests/TestSuiteTests/ExeV10/tests/test-Foo.hs
> Show details direct

- Cabal/Distribution/Version.hs
Related to https://github.com/haskell/cabal/issues/2919
Maybe we should merge this on top of whatever is the last release?
See https://github.com/kolmodin/binary/pull/87
> binary-0.8.0.0 will provide Binary Version

- setup-dev.sh
---
This was part of a different branch, but just in the interests of getting it merged, I've split it out. Should be pretty uncontroversial :).
> Rework setup-dev.sh to reduce redundancy

- Cabal/Distribution/Simple/BuildTarget.hs
- Cabal/Distribution/Simple/Program/Find.hs
Trying to make the code less confusing to the next person :)
> Improve some comments.

- Cabal/Cabal.cabal
- Cabal/Distribution/Simple/Program/Find.hs
Previously this did not build.
> Program.Find: Fix on Win32

- cabal-install/Distribution/Client/IndexUtils.hs
> Make sure 'tarEntriesList' does not create thunks

- Cabal/Distribution/Simple/GHC.hs
> Also probe in canonicalized path, if binary was a symlink.

- Cabal/Distribution/PackageDescription/Check.hs
- Cabal/Distribution/PackageDescription/Parse.hs
- Cabal/Distribution/Simple/Build.hs
- Cabal/Distribution/Simple/Configure.hs
- Cabal/doc/developing-packages.markdown
- Cabal/tests/PackageTests/BenchmarkStanza/Check.hs
- Cabal/tests/PackageTests/TestStanza/Check.hs
These commits are unrelated but I didn't feel like making a separate PR for each one. One refactors configure, the other removes some functionality from build-depends (yes I checked, there is no package on Hackage which uses that functionality.)
> Some cleanups

- Cabal/Cabal.cabal
- Cabal/Distribution/Version.hs
Related to https://github.com/haskell/cabal/issues/2919 and https://github.com/haskell/cabal/issues/2966
> 1.22 binary 0.8

- Cabal/Cabal.cabal
- Cabal/tests/PackageTests/BenchmarkStanza/Check.hs
- Cabal/tests/PackageTests/PackageTester.hs
- Cabal/tests/PackageTests/TestStanza/Check.hs
- Cabal/tests/PackageTests/Tests.hs
> Reenable warnings on package-tests.

- Cabal/Language/Haskell/Extension.hs
> Two new extensions coming with GHC 8.0, fixes #3025.

- cabal-install/Distribution/Client/Dependency.hs
- cabal-install/Distribution/Client/Dependency/Modular/Preference.hs
- cabal-install/Distribution/Client/Dependency/TopDown.hs
- cabal-install/Distribution/Client/Dependency/Types.hs
- cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/DSL.hs
- cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/Solver.hs
Creating PR for this fix, need to discuss one thing before it is ready for merge. I will comment below.
> Fix #2645 - make cabal merge package preferences if more than one is specified

- Cabal/Cabal.cabal
- Cabal/tests/PackageTests/HaddockNewline/A.hs
- Cabal/tests/PackageTests/HaddockNewline/ChangeLog.md
- Cabal/tests/PackageTests/HaddockNewline/HaddockNewline.cabal
- Cabal/tests/PackageTests/HaddockNewline/LICENSE
- Cabal/tests/PackageTests/HaddockNewline/Setup.hs
- Cabal/tests/PackageTests/Tests.hs
Putting it here so we don't lose it. #3004
> Failing test for #3004.

- cabal-install/Distribution/Client/IndexUtils.hs
- cabal-install/Distribution/Client/Sandbox/Index.hs
In `listBuildTreeRefs` we find this somewhat mysterious code:
``` haskell
listWithIgnored :: IO [BuildTreeRef]
listWithIgnored = readBuildTreeRefsFromFile $ path
listWithoutIgnored :: IO [FilePath]
listWithoutIgnored = do
let repo = RepoLocal { repoLocalDir = takeDirectory path }
pkgIndex <- fmap packageIndex
. getSourcePackagesStrict verbosity $ [repo]
return [ pkgPath | (LocalUnpackedPackage pkgPath) <-
map packageSource . allPackages $ pkgIndex ]
```
It is not at all obvious (at least, not to me) how `listWithIgnored` and `listWithoutIgnored` do almost the same thing. In addition---and, for my current purposes, more importantly---this is the _only_ place in the entire `cabal-install` codebase where we are constructing a `Repo` out of nothing, and that's causing me a lot of grief in …
> Improve separation of concerns: introduce readBuildTreeRefsFromCache

- cabal-install/Distribution/Client/HttpUtils.hs
Function `putHttpFile` already allowed for request headers; we just do the same thing in `getHttp` as is done in `putHttpFile`.
> Add support for request headers in getHttp

- Cabal/Distribution/Simple/Configure.hs
- Cabal/Distribution/Simple/GHCJS.hs
- Cabal/tests/PackageTests/TestSuiteTests/ExeV10/Check.hs
- Cabal/tests/PackageTests/TestSuiteTests/ExeV10/my.cabal
- Cabal/tests/PackageTests/TestSuiteTests/ExeV10/tests/test-Short.hs
- cabal-install/bootstrap.sh
- cabal-install/cabal-install.cabal
> Simple commits

- cabal-install/Distribution/Client/Dependency/Modular/Assignment.hs
- cabal-install/Distribution/Client/Dependency/Modular/Dependency.hs
- cabal-install/Distribution/Client/Dependency/Modular/Explore.hs
- cabal-install/Distribution/Client/Dependency/Modular/Flag.hs
- cabal-install/Distribution/Client/Dependency/Modular/IndexConversion.hs
- cabal-install/Distribution/Client/Dependency/Modular/Log.hs
- cabal-install/Distribution/Client/Dependency/Modular/Package.hs
- cabal-install/Distribution/Client/Dependency/Modular/Preference.hs
- cabal-install/Distribution/Client/Dependency/Modular/Tree.hs
- cabal-install/Distribution/Client/Dependency/Modular/Version.hs
This is the continuation of #2924 -- please see discussion, etc. there.
> Remove dead code in modular solver

- Cabal/doc/installing-packages.markdown
@23Skidoo @dcoutts Here's a first attempt at documenting repository configuration. Since there was no section on cabal configuration at all yet in the manual, I added one. It is fairly minimal at the moment, but I think it is serviceable.
> First stab at documenting repo configuration

- cabal-install/cabal-install.cabal
> allow building with recent (master) HTTP

- Cabal/Distribution/InstalledPackageInfo.hs
- Cabal/Distribution/Package.hs
- Cabal/Distribution/Simple/PackageIndex.hs
> Add some more backwards-compatibility functions, fixes #3068.

- cabal-install/Distribution/Client/ComponentDeps.hs
- cabal-install/Distribution/Client/InstallPlan.hs
- cabal-install/Distribution/Client/PlanIndex.hs
- cabal-install/Distribution/Client/Setup.hs
- cabal-install/Distribution/Client/Utils.hs
A number of small patches needed as preparation for merging the nix-local-build branch into master.
* Adds a few utils.
* Minor refactoring.
* A fix that ought to be in master anyway.
> Misc nix-local-build preparation patches

- cabal-install/Distribution/Client/Config.hs
- cabal-install/Distribution/Client/Setup.hs
- cabal-install/Main.hs
- cabal-install/changelog
- cabal-install/tests/IntegrationTests/user-config/common.sh
- cabal-install/tests/IntegrationTests/user-config/should_fail/doesnt_overwrite_without_f.err
- cabal-install/tests/IntegrationTests/user-config/should_fail/doesnt_overwrite_without_f.sh
- cabal-install/tests/IntegrationTests/user-config/should_run/cabal-config
- cabal-install/tests/IntegrationTests/user-config/should_run/overwrites_with_f.out
- cabal-install/tests/IntegrationTests/user-config/should_run/overwrites_with_f.sh
- cabal-install/tests/IntegrationTests/user-config/should_run/runs_without_error.out
- cabal-install/tests/IntegrationTests/user-config/should_run/runs_without_error.sh
- cabal-install/tests/UnitTests/Distribution/Client/UserConfig.hs
> Add new 'user-config' subcommand 'init'.

- HACKING.md
> Typo in Hacking.md

- cabal-install/cabal-install.cabal
- cabal-install/tests/README
- cabal-install/tests/README.md
> Start documenting cabal-install integration tests

- Cabal/Distribution/PackageDescription/Check.hs
- Cabal/doc/developing-packages.markdown
In addition to `ghc-options` and `ghc-prof-options`. Some people specify `-fprof -auto-all` there.
> D.PD.Check: Also check 'ghc-shared-options'.

- Cabal/Distribution/Text.hs
- cabal-install/Distribution/Client/Config.hs
- cabal-install/Distribution/Client/Dependency.hs
- cabal-install/Distribution/Client/Setup.hs
@edsko, this touches some of your code.
> Small tweaks to config file parsing.

- cabal-install/Distribution/Client/Sandbox.hs
Fixes #2381. If CABAL_SANDBOX_PACKAGE_PATH, GHC_PACKAGE_PATH, or
GHCJS_PACKAGE_PATH refer to a package database inside the sandbox, warn
the user that the package database has been deleted.
> Warn user when deleting package database

- Cabal/Distribution/Simple/Build.hs
- Cabal/Distribution/Simple/GHC.hs
- Cabal/Distribution/Simple/GHCJS.hs
- Cabal/Distribution/Simple/Haddock.hs
- Cabal/Distribution/Simple/Program/GHC.hs
- cabal-install/Distribution/Client/SetupWrapper.hs
- cabal-install/Main.hs
Basically a two-line change, the rest is about passing a `Platform` value to `renderGhcArgs`.
> Don't pass OSX-specific options to GHC on non-OSX.

- Cabal/Distribution/Simple/Setup.hs
> Distribution.Simple.Setup: remove job cap

- .travis.yml
See https://github.com/haskell/cabal/pull/3197#issuecomment-194567139.
Please don't merge until Travis is green.
> Don't use './Setup' for building 'cabal-install'.

- Cabal/Distribution/Simple/Configure.hs
- Cabal/Distribution/Simple/Utils.hs
- Cabal/Distribution/Text.hs
These changes are fairly non-invasive, but improve the user interface considerably. Once this passes, I will backport to the 1.24 branch
> Fix ConfigStateFileErrorMessages

- Cabal/doc/developing-packages.markdown
- cabal-install/Distribution/Client/Freeze.hs
- cabal-install/Distribution/Client/GenBounds.hs
- cabal-install/Distribution/Client/Init.hs
- cabal-install/Distribution/Client/Setup.hs
- cabal-install/Main.hs
- cabal-install/cabal-install.cabal
- cabal-install/changelog
An updated version of #2774 with some mindless refactorings to make it work against current `master`.
> Add the gen-bounds command.

- Cabal/tests/README.md
> More detailed docs for the PACKAGETESTS flags.

- cabal-install/Distribution/Client/InstallPlan.hs
- cabal-install/Distribution/Client/PackageHash.hs
- cabal-install/Distribution/Client/ProjectBuilding.hs
- cabal-install/Distribution/Client/ProjectPlanning.hs
- cabal-install/Distribution/Client/Types.hs
- cabal-install/Main.hs
- cabal-install/cabal-install.cabal
Ready for review.
Ignore the first 8 patches, they're inherited from PR #3226. It's just the last 4.
It consists of two major phases, planning and building (each of which consists of several passes mostly involving the ElaboratedInstallPlan data structure).
> Project planning building

- cabal-install/bash-completion/cabal
(I looked at `git`'s bash-completion, and simplified slightly.)
> Respect "--" in bash-completion, fixes #3271

- appveyor.yml
> Make AppVeyor less chatty.

- cabal-install/Main.hs
> 'cabal test': don't fail on no test suites.

- Cabal/Distribution/Simple/Utils.hs
> Only catch and unwrap user errors (simplified fix for #3310).

- Cabal/misc/gen-extra-source-files.sh
- cabal-install/Distribution/Client/ProjectConfig.hs
- cabal-install/cabal-install.cabal
- cabal-install/tests/IntegrationTests/new-build/monitor_cabal_files.sh
- cabal-install/tests/IntegrationTests/new-build/monitor_cabal_files/.gitignore
- cabal-install/tests/IntegrationTests/new-build/monitor_cabal_files/cabal.project
- cabal-install/tests/IntegrationTests/new-build/monitor_cabal_files/p/P.hs
- cabal-install/tests/IntegrationTests/new-build/monitor_cabal_files/p/Setup.hs
- cabal-install/tests/IntegrationTests/new-build/monitor_cabal_files/p/p.cabal
- cabal-install/tests/IntegrationTests/new-build/monitor_cabal_files/q/Main.hs
- cabal-install/tests/IntegrationTests/new-build/monitor_cabal_files/q/Setup.hs
- cabal-install/tests/IntegrationTests/new-build/monitor_cabal_files/q/q-broken.cabal.in
- cabal-install/tests/IntegrationTests/new-build/monitor_cabal_files/q/q-fixed.cabal.in
> Merge #3325 into 1.24.

- cabal-install/Distribution/Client/ProjectPlanning.hs
- cabal-install/Distribution/Client/ProjectPlanning/Types.hs
First three commits are just some extra commenting from when I was analyzing the code.
> Don't include requests for non-existent stanzas in pkgStanzasRequested, fixes #3340.

- Cabal/Distribution/PackageDescription.hs
- Cabal/Distribution/PackageDescription/Configuration.hs
- cabal-install/Distribution/Client/Configure.hs
- cabal-install/Distribution/Client/Dependency.hs
- cabal-install/Distribution/Client/ProjectPlanning.hs
- cabal-install/Distribution/Client/SetupWrapper.hs
- cabal-install/cabal-install.cabal
- cabal-install/tests/IntegrationTests/regression/t3199.sh
- cabal-install/tests/IntegrationTests/regression/t3199/Main.hs
- cabal-install/tests/IntegrationTests/regression/t3199/Setup.hs
- cabal-install/tests/IntegrationTests/regression/t3199/test-3199.cabal
- cabal-install/tests/UnitTests/Distribution/Client/Dependency/Modular/DSL.hs
See #3337.
Once a better fix is found, parts of this can be reverted.
> Merge #3337 into master

- cabal-install/Distribution/Client/FetchUtils.hs
- cabal-install/Distribution/Client/PackageHash.hs
- cabal-install/Distribution/Client/ProjectPlanning.hs
> Port #3370 to master

- cabal-install/Distribution/Client/IndexUtils.hs
This should address #2956 and is motivated by #3378
> Resolve tar-entry masking in `packageListFromCache`

- cabal-install/Distribution/Solver/Modular/Validate.hs
This makes it a bit easier to modify it (for example, during debugging).
> Make `Validate` a proper monad

- cabal-install/Distribution/Client/ProjectBuilding.hs
- cabal-install/Distribution/Client/ProjectPlanning/Types.hs
- cabal-install/cabal-install.cabal
- cabal-install/tests/IntegrationTests/internal-libs/cabal.project
- cabal-install/tests/IntegrationTests/internal-libs/new_build.sh
> Correctly handle internal libraries in new-build.

- cabal-install/Distribution/Client/Config.hs
- cabal-install/Distribution/Client/Setup.hs
- cabal-install/Distribution/Client/Upload.hs
- cabal-install/Main.hs
- cabal-install/changelog
Plus some other small tweaks.
Fixes #1823.
> Remove 'upload --check'.

- cabal-install/Distribution/Client/HttpUtils.hs
This PR has a few commits that each fix a difference in what some transport
does in comparision to all the others. See the commits for more details,
they should be pretty self-explanatory.
> Fix various behavior differences between the transports

- travis-script.sh
* remove bashisms
* fix POSIX compliance
* change shebang to /bin/sh
> travis-script.sh: fix POSIX and sh compat

- travis-script.sh
Instead of spawning expr we can use sh arithmetic expansion.
> travis-script.sh: use shell arith expansion

- cabal-install/Distribution/Client/ProjectBuilding.hs
Allowing parallel installation of files, just serialising the actual registration. Also previously only store package installs were serialised but we also need to serialise registration of packages in the local inplace package db.
This is just a minor cleanup patch, nothing significant. Technically the lack of serialising the inplace registrations would have been a source of bugs, but it's not one I've ever seen in practice.
> Change install lock to just a registration lock

- cabal-install/Main.hs
> cabal-install: make user config optional if possible

- Cabal/Distribution/Version.hs
- Cabal/tests/UnitTests/Distribution/Version.hs
Supersedes https://github.com/haskell/cabal/pull/3518.
> Add differenceVersionRanges

- Cabal/doc/developing-packages.markdown
> Markdown formatting fixes, fixes #3481.

- Cabal/tests/PackageTests/Tests.hs
- cabal-install/bootstrap.sh
- travis-script.sh
Something useful found while exploring osx on travis
> OSX related corrections

- .travis.yml
- travis-install.sh
- travis-script.sh
Tries to implement https://github.com/haskell/cabal/issues/3550
> Try to install ghc manually on osx

- .travis.yml
> Test bootstrap on OSX.

- Cabal/doc/developing-packages.markdown
> doc: Add brief description of setup-depends

- Cabal/Distribution/Compat/Graph.hs
> Add an IsNode instance for Either.

- Cabal/Distribution/Compat/Graph.hs
- Cabal/tests/UnitTests/Distribution/Compat/Graph.hs
- cabal-install/Distribution/Client/BuildReports/Storage.hs
- cabal-install/Distribution/Client/Configure.hs
- cabal-install/Distribution/Client/Install.hs
- cabal-install/Distribution/Client/InstallPlan.hs
- cabal-install/Distribution/Client/InstallSymlink.hs
- cabal-install/Distribution/Client/ProjectBuilding.hs
- cabal-install/Distribution/Client/ProjectOrchestration.hs
- cabal-install/Distribution/Client/ProjectPlanOutput.hs
- cabal-install/Distribution/Client/ProjectPlanning.hs
- cabal-install/Distribution/Client/ProjectPlanning/Types.hs
- cabal-install/Distribution/Client/Types.hs
- cabal-install/cabal-install.cabal
- cabal-install/tests/IntegrationTests2.hs
- cabal-install/tests/UnitTests.hs
- cabal-install/tests/UnitTests/Distribution/Client/InstallPlan.hs
> Installplan refactor

- cabal-install/Distribution/Client/SetupWrapper.hs
> Make internal/self-exect setup methods more chatty.

- travis-bootstrap.sh
- travis-common.sh
- travis-meta.sh
- travis-script.sh
Doesn't fail with osx, thought locally it does...
> Test travis

- travis-script.sh
See https://github.com/haskell/cabal/pull/3630#issuecomment-235438329.
> Don't test sdist in the main script.

- cabal-install/Distribution/Client/Dependency.hs
> Remove TODO mentioning top down solver

- cabal-install/Setup.hs
> ensure appropriate permissions for manpage

- Cabal/Distribution/Compiler.hs
- Cabal/Distribution/PackageDescription.hs
- Cabal/Distribution/PackageDescription/Parse.hs
- Cabal/Distribution/Simple/Utils.hs
- Cabal/Distribution/System.hs
- Cabal/Distribution/Types/GenericPackageDescription.hs
- Cabal/Distribution/Types/SourceRepo.hs
- Cabal/Language/Haskell/Extension.hs
- cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
Found those while working on parsec parser
> Few very small refactors

- cabal.project.travis
> Try top-level -Werror.

- Cabal/Distribution/Simple/PreProcess.hs
> Fix preprocessors to put output in correct directory.

- cabal-install/Distribution/Client/Configure.hs
- cabal-install/cabal-install.cabal
- cabal-install/tests/IntegrationTests/regression/t2755.sh
- cabal-install/tests/IntegrationTests/regression/t2755/A.hs
- cabal-install/tests/IntegrationTests/regression/t2755/Setup.hs
- cabal-install/tests/IntegrationTests/regression/t2755/test-t2755.cabal
> Fix #2755 by always respecting enable flags on configure.

- Cabal/Distribution/Simple/Build/PathsModule.hs
- Cabal/doc/developing-packages.markdown
- cabal-install/Distribution/Client/ProjectBuilding.hs
- cabal-install/Distribution/Client/ProjectPlanning.hs
- cabal-install/cabal-install.cabal
- cabal-install/tests/IntegrationTests/common.sh
- cabal-install/tests/IntegrationTests/regression/t3335.sh
- cabal-install/tests/IntegrationTests/regression/t3335/A.hs
- cabal-install/tests/IntegrationTests/regression/t3335/Setup.hs
- cabal-install/tests/IntegrationTests/regression/t3335/cabal.project
- cabal-install/tests/IntegrationTests/regression/t3335/t3335.cabal
> Fix #3335 by not passing build arguments if not supported.

- cabal-install/Distribution/Client/ProjectBuilding.hs
- cabal-install/Distribution/Client/ProjectOrchestration.hs
- cabal-install/cabal-install.cabal
- cabal-install/tests/IntegrationTests/custom/segfault.sh
- cabal-install/tests/IntegrationTests/custom/segfault/Setup.hs
- cabal-install/tests/IntegrationTests/custom/segfault/cabal.project
- cabal-install/tests/IntegrationTests/custom/segfault/plain.cabal
> Give an explicit message when SIGSEGV happens.

- cabal-install/Distribution/Client/Manpage.hs
- cabal-install/tests/IntegrationTests.hs
> Set LC_ALL=C for integration-tests, partial workaround for #3326.

- cabal-install/Distribution/Client/CmdBuild.hs
- cabal-install/Distribution/Client/CmdConfigure.hs
- cabal-install/Distribution/Client/CmdFreeze.hs
- cabal-install/Distribution/Client/CmdRepl.hs
- cabal-install/Main.hs
> Fix #3319: Give proper CommandUI to the Nix-local build commands.

- Cabal/doc/developing-packages.markdown
> Stop recommending detailed-0.9, no one actually believes that.

- Cabal/doc/installing-packages.markdown
- Cabal/doc/nix-local-build.markdown
- cabal-install/Distribution/Client/ProjectConfig/Types.hs
Work in progress docs for nix-local-build. Totally reviewable right now though. Please comment.
CC @dcoutts @hvr @23Skidoo @phadej
> Docs for nix-local-build

- cabal-install/Distribution/Client/ProjectPlanOutput.hs
Here's the new ones:
- style: local | inplace | global
- dist-dir: the dist directory for the build
- bin-file: the binary of the component/executable
If anyone wants to bikeshed the keys, better to do now
than later.
> Add some new fields to plan.json, upon @hvr's request.

- cabal-install/Distribution/Client/DistDirLayout.hs
- cabal-install/Distribution/Client/ProjectPlanning/Types.hs
> Add optimization level to build directory structure.

- Cabal/doc/nix-local-build.rst
@winterland1989 does this answer your question? I had trouble figuring out what to write.
> Say a bit more about vendoring in local packages, CC @winterland1989

- cabal-install/Distribution/Client/ProjectConfig/Legacy.hs
- cabal-install/Distribution/Client/ProjectConfig/Types.hs
- cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
> Remove deprecated/obsolete projectConfigWorldFile, fixes #3749.

- appveyor.yml
- cabal-install/Distribution/Client/SetupWrapper.hs
- cabal-install/cabal-install.cabal
- cabal-install/tests/IntegrationTests/custom-setup/common.sh
- cabal-install/tests/IntegrationTests/custom-setup/should_run/Cabal-99998/Cabal.cabal
- cabal-install/tests/IntegrationTests/custom-setup/should_run/Cabal-99998/CabalMessage.hs
- cabal-install/tests/IntegrationTests/custom-setup/should_run/Cabal-99999/Cabal.cabal
- cabal-install/tests/IntegrationTests/custom-setup/should_run/Cabal-99999/CabalMessage.hs
- cabal-install/tests/IntegrationTests/custom-setup/should_run/custom-setup-without-cabal-defaultMain/Setup.hs
- cabal-install/tests/IntegrationTests/custom-setup/should_run/custom-setup-without-cabal-defaultMain/custom-setup-without-cabal-defaultMain.cabal
- cabal-install/tests/IntegrationTests/custom-setup/should_run/custom-setup-without-cabal/Setup.hs
- cabal-install/tests/IntegrationTests/custom-setup/should_run/custom-setup-without-cabal/custom-setup-without-cabal.cabal
- cabal-install/tests/IntegrationTests/custom-setup/should_run/custom-setup/Setup.hs
- cabal-install/tests/IntegrationTests/custom-setup/should_run/custom-setup/custom-setup.cabal
- cabal-install/tests/IntegrationTests/custom-setup/should_run/custom_setup_without_Cabal_doesnt_allow_Cabal_import.sh
- cabal-install/tests/IntegrationTests/custom-setup/should_run/custom_setup_without_Cabal_doesnt_require_Cabal.sh
- cabal-install/tests/IntegrationTests/custom-setup/should_run/installs_Cabal_as_setup_dep.sh
> Cherry-pick #3688 and #3723 onto 1.24

- cabal-install/Distribution/Solver/Modular/IndexConversion.hs
- cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL.hs
- cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs
CC @grayjay. The commit which fixes this failing test case is #3782
> Add support for executables to DSL, and failing test for #3775

- cabal-install/Distribution/Client/PackageHash.hs
- cabal-install/Distribution/Client/ProjectPlanning.hs
- cabal-install/Distribution/Client/ProjectPlanning/Types.hs
- cabal-install/Distribution/Solver/Types/PkgConfigDb.hs
Tested by building glib and eyeballing cabal-hashes.txt.
> Track pkg-config deps in hash, fixes #3493.

- cabal-install/tests/UnitTests/Distribution/Solver/Modular/QuickCheck.hs
> Document how solver quickcheck tests create valid ComponentDeps.

- Cabal/doc/conf.py
- Cabal/doc/developing-packages.rst
- Cabal/doc/installing-packages.rst
- Cabal/doc/intro.rst
- Cabal/doc/nix-local-build.rst
Also makes 'cabal' a default highlighter.
I think a much prettier highlighter can be made by simplifying the yaml highlighter from pygments, but IMO it's more work than anyone would care to do.
> More docs highlighting changes

- .travis.yml
- Cabal/Distribution/Compat/Binary.hs
- Cabal/Distribution/Compat/Environment.hs
- Cabal/changelog
- README.md
- travis-script.sh
Fixes #3838. See discussion in #3838 for rationale.
/cc @hvr @ttuegel
> Revive GHC 7.4 support and revise the GHC compatibility window for the Cabal library

- cabal-install/Distribution/Client/Setup.hs
Previously, the code was inconsistent on whether or not
flags_x_y_z indicated that these flags could be used
up to version x.y.z, or should be used prior to x.y.z.
This commit picks the LATTER and renames everything
consistently this way.  The bonus is that now the names
match up with the conditionals. Yay.
More patch coming shortly.
> Renumber flags version numbers in 'filterConfigureFlags'.

- Cabal/Distribution/Compat/Exception.hs
- Cabal/Distribution/Simple/Program/HcPkg.hs
> Give more informative error when ghc-pkg dump fails.

- cabal-install/Distribution/Client/ProjectOrchestration.hs
> Print profiling status when displaying install plan.

- cabal-install/Distribution/Client/Config.hs
Fixes #3867.
~~This is WIP -- I also need to fix pretty-printing of multiline fields:~~ 
```
repository hackage.haskell.org                                                                                                                        
url: http://hackage.haskell.org/                                                                                                                    
-- secure: True                                                                                                                                     
-- root-keys: fe331502606802feac15e514d9b9ea83fee8b6ffef71335479a2e68d84adc6b0                                                                      
1ea9ba32c526d1cc91ab5e5bd364ec5e9e8cb67179a471872f6e26f0ae773d42 …
```
> 'user-config init': Print the default 'remote-repo' correctly.

- cabal-install/Distribution/Client/Install.hs
- cabal-install/Distribution/Client/ProjectOrchestration.hs
> Print the number of jobs we're using.

- Cabal/Distribution/Version.hs
- Cabal/tests/UnitTests/Distribution/Version.hs
This optimises the [Int] representation to a 16-byte heap object for
~99% of version numbers occuring on Hackage.
One noteworthy improvement of this optimisation is a significant reduction of the size
of the `01-index.cache` file from previously 6299700 bytes (before #3905) down
to 3408864 bytes, i.e. down to ~54%
----
Also, this reduces the memory footprint a bit for e.g. `cabal info zzz` from
```
cabal.0: There is no package named 'zzz'.
You may need to run 'cabal update' to get the latest list of available
packages.
859,337,368 bytes allocated in the heap
447,261,128 bytes copied during GC
37,385,208 bytes maximum residency (19 sample(s))
1,311,136 bytes maximum slop
103 MB total memory in use (0 MB lost due to fragmentation)
Tot time (elapsed)  Avg pause  Max pause
Gen  0      1613 …
```
> Optimise `Version` representation

- Cabal/Distribution/ModuleName.hs
Admittedly, this is a rather modest optimisation for typical small
packages having only a few `ModuleName`s. However, when cabal-install 
loads lots of package descriptions this adds up.
> Optimise internal representation of `ModuleName`

- Cabal/Distribution/Version.hs
NB: I'm submitting this PR on behalf of @dcoutts ; be careful when merging this PR to retain proper authorship
See https://github.com/dcoutts/cabal-version-bench/blob/master/src/Distribution/Version.hs
> Optimise Distribution.Version.mkVersion

- cabal-install/Distribution/Client/Sandbox/PackageEnvironment.hs
This makes freeze files a bit more version-control-friendly.
> PackageEnvironment: Sort constraints in produced freeze file

- cabal-install/Distribution/Client/ProjectBuilding.hs
- cabal-install/Distribution/Client/ProjectBuilding/Types.hs
> Only reregister inplace package if we built it.

- Cabal/Cabal.cabal
- Cabal/Distribution/Compat/DList.hs
- Cabal/Distribution/Lex.hs
In new parser there are few places where it can be used, so we can win few percents of performance...
> Add Distribution.Compat.DList

- cabal-install/Distribution/Solver/Modular/Solver.hs
> Fix -Werror failure.

- .travis.yml
- travis-install.sh
- travis-stack.sh
> Add CI target for building Cabal using Stack

- Cabal/Distribution/PackageDescription/Check.hs
- Cabal/Distribution/PackageDescription/Parse.hs
- Cabal/changelog
- Cabal/tests/PackageTests/Backpack/Includes1/Includes1.cabal
- Cabal/tests/PackageTests/Backpack/Includes2/Includes2.cabal
- Cabal/tests/PackageTests/Backpack/Includes2/fail.cabal
- Cabal/tests/PackageTests/Backpack/Includes2/src/src.cabal
- Cabal/tests/PackageTests/Backpack/Includes5/Includes5.cabal
- Cabal/tests/PackageTests/Backpack/Reexport1/p/p.cabal
- cabal-install/tests/IntegrationTests/backpack/includes2/Includes2.cabal
- cabal-install/tests/IntegrationTests/backpack/includes2/src/src.cabal
> Rename 'backpack-includes' to 'mixins'.

- .travis.yml
> Add explicit osx image to GHC 7.8.4 job

- Cabal/Distribution/Simple/Build.hs
Generally, the the runner (e.g. new-build) will know
better about the specific package db that the package
should be registered inplace into.  So don't register
into our distdir; it's not useful.
> Don't register inplace if we're in per-component mode.

- cabal-install/Distribution/Solver/Modular.hs
> Deduplicate packages in the install plan after the solver removes qualifiers.

- stack.yaml
Convenience for `stack build`.
> Add edit-distance-0.2.2.1 to stack.yaml

- Cabal/doc/nix-local-build.rst
> [skip ci] Minor reorg of profiling documentation.

- Cabal/Distribution/Simple/Configure.hs
> [ci skip] Commentary for configureRequiredProgram.

- README.md
> Style guideline for CPP.

- Cabal/doc/developing-packages.rst
- cabal-testsuite/PackageTests/ForeignLibs/Check.hs
- cabal-testsuite/PackageTests/Tests.hs
Duplication introduced by #4065.
> Deduplicate version checks in cabal-testsuite

- Cabal/Distribution/Simple.hs
> Fix missing line pointed out by @abooij.

- cabal-install/Distribution/Client/ProjectPlanOutput.hs
This adds the following new fields:
- `.compiler-id`
- `.os`
- `.arch`
- `.install-plan[].pkg-name`
- `.install-plan[].pkg-version`
- `.install-plan[].pkg-src-sha256`
Having separate "pkg-{name,version}" fields is desirable because the "id"-field
is actually a UnitId which is supposed to be an opaque id which may not
always be easily convertible into a PackageId via string operations.
The "pkg-src-sha256" is generally useful to uniquely identify a
source-tarball (when the package-id is not exact enough).
Finally, the compiler-id/os/arch information is needed to determine the
values of the respective impl()/os()/arch() predicates used in
conditionals in .cabal files.
Here's an example demonstrating the new fields:
```js
{
"cabal-version": "1.25.0.0",
"cabal-lib-version": "1.25.0.0", …
```
> Add more fields to plan.json schema

- Cabal/Distribution/Parsec/Lexer.x
> Fix redundant import warning from Parsec.

- Cabal/Distribution/Package.hs
- Cabal/Distribution/Types/PkgconfigDependency.hs
And Travis still passed on the old one...huh.
> Oops! Forget to delete old PkgconfigDependency during refactor

- Cabal/Distribution/Simple/Configure.hs
> Fix copy-paste mistake in error message

- cabal-install/Distribution/Client/Exec.hs
It's only the last patch that does something, but it's based on @ezyang's work in order to see if it did anything.
DO NOT MERGE THIS - primarily this was the easiest way to run the tests on Windows.
> Attempt to fix issue 4133

- Cabal/Cabal.cabal
- cabal-install/cabal-install.cabal
This should also be applied to `master`.
> Bump directory upper bound to < 1.4

- Cabal/Cabal.cabal
- cabal-install/bootstrap.sh
- cabal-install/cabal-install.cabal
> Update 'bootstrap.sh' and the upper bound on 'time'.

- Cabal/Distribution/Backpack/ConfiguredComponent.hs
- Cabal/Distribution/Backpack/LinkedComponent.hs
- Cabal/Distribution/Backpack/UnifyM.hs
- Cabal/Distribution/Simple/Build.hs
- Cabal/Distribution/Simple/Configure.hs
- Cabal/Distribution/Simple/PackageIndex.hs
- cabal-install/Distribution/Client/ProjectOrchestration.hs
- cabal-testsuite/PackageTests/Backpack/Fail1/Fail1.cabal
- cabal-testsuite/PackageTests/Backpack/Fail1/setup.test.hs
- cabal-testsuite/PackageTests/Backpack/Fail2/Fail2.cabal
- cabal-testsuite/PackageTests/Backpack/Fail2/setup.test.hs
- cabal-testsuite/PackageTests/Backpack/Fail3/Fail3.cabal
- cabal-testsuite/PackageTests/Backpack/Fail3/Main.hs
- cabal-testsuite/PackageTests/Backpack/Fail3/UnfilledSig.hsig
- cabal-testsuite/PackageTests/Backpack/Fail3/setup.test.hs
- cabal-testsuite/PackageTests/Backpack/Indef2/Indef2.cabal
- cabal-testsuite/PackageTests/Backpack/Indef2/setup.test.hs
> Backpack fixes

- appveyor.yml
> Unsilence curl to figure out why https download is failing

- cabal-install/bootstrap.sh
Fix [provided by @mvkorpel](https://github.com/haskell/cabal/issues/3440#issuecomment-227134861).
/cc @geoff-codes
> Fix #3440.

- appveyor.yml
> Don't pipe choco install to NUL.

- cabal-install/Distribution/Solver/Modular/Cycles.hs
> Add a comment to 'Distribution.Solver.Modular.Cycles.findCycles'.

- Cabal/Cabal.cabal
- Cabal/Distribution/PackageDescription.hs
- Cabal/Distribution/PackageDescription/Check.hs
- Cabal/Distribution/PackageDescription/Configuration.hs
- Cabal/Distribution/PackageDescription/Parse.hs
- Cabal/Distribution/PackageDescription/Parsec.hs
- Cabal/Distribution/PackageDescription/PrettyPrint.hs
- Cabal/Distribution/Parsec/ConfVar.hs
- Cabal/Distribution/Types/CondTree.hs
- Cabal/Distribution/Types/Condition.hs
- Cabal/Distribution/Types/GenericPackageDescription.hs
- cabal-install/Distribution/Solver/Modular/IndexConversion.hs
- cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL.hs
> Split Condition/CondTree out of GenericPackageDescription.

- Cabal/Distribution/Simple/Register.hs
> Do not compute ABI hash for inplace installation.

- .travis.yml
- travis-script.sh
> Restore jobs parameter to travis-script.sh

- Cabal/doc/nix-local-build.rst
- cabal-install/Distribution/Client/Config.hs
- cabal-install/Distribution/Client/Dependency.hs
- cabal-install/Distribution/Client/Fetch.hs
- cabal-install/Distribution/Client/Freeze.hs
- cabal-install/Distribution/Client/Install.hs
- cabal-install/Distribution/Client/ProjectConfig.hs
- cabal-install/Distribution/Client/ProjectConfig/Legacy.hs
- cabal-install/Distribution/Client/ProjectConfig/Types.hs
- cabal-install/Distribution/Client/ProjectPlanning.hs
- cabal-install/Distribution/Client/Setup.hs
- cabal-install/Distribution/Solver/Modular/Solver.hs
- cabal-install/Distribution/Solver/Types/Settings.hs
- cabal-install/changelog
- cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
- cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL.hs
- cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL/TestCaseUtils.hs
- cabal-install/tests/UnitTests/Distribution/Solver/Modular/QuickCheck.hs
- cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs
See https://github.com/haskell/cabal/pull/4227#issuecomment-272114153.
> Rename --install-base-libraries to --allow-boot-library-installs.

- cabal-install/Distribution/Client/CmdTest.hs
- cabal-install/Distribution/Client/ProjectBuilding.hs
- cabal-install/Distribution/Client/ProjectPlanning.hs
- cabal-install/Distribution/Client/ProjectPlanning/Types.hs
- cabal-install/Main.hs
- cabal-install/cabal-install.cabal
- cabal-testsuite/PackageTests/TestSuiteTests/ExeV10/cabal.project
- cabal-testsuite/PackageTests/TestSuiteTests/ExeV10/cabal.test.hs
I have no idea what I have done, so all comments are more than welcome.
> WIP: new-test

- Cabal/doc/nix-local-build.rst
> Restore documentation about multiple constraints.

- appveyor-retry.cmd
- appveyor.yml
> Retry when running Appveyor to work around failures.

- Cabal/Distribution/Backpack/Configure.hs
- Cabal/Distribution/Simple/Configure.hs
- Cabal/Distribution/Simple/PackageIndex.hs
- Cabal/Distribution/Simple/Utils.hs
A few miscellaneous Backpack improvements.
> Backpack improvements

- Cabal/Distribution/Simple/Build/Macros.hs
- Cabal/changelog
See https://github.com/haskell/cabal/issues/4319
> Implement CURRENT_PACKAGE_VERSION macro

- cabal-testsuite/PackageTests/Exec/sandbox-ghc-pkg.out
- cabal-testsuite/PackageTests/Exec/sandbox-hc-pkg.out
- cabal-testsuite/PackageTests/Exec/sandbox-path.out
- cabal-testsuite/PackageTests/Exec/sandbox.out
- cabal-testsuite/PackageTests/Regression/T3436/sandbox.out
Failure introduced in 9098fac671be0d60bd89f38834c51974a0841df2.
> Unbreak the test suite.

- Cabal/Distribution/Compat/Stack.hs
- Cabal/Distribution/Simple/Build.hs
- Cabal/Distribution/Simple/Utils.hs
- cabal-install/Distribution/Client/SetupWrapper.hs
> Fix accidentally broken call stacks.

- .travis.yml
- appveyor.yml
- cabal.project.travis
- travis-install.sh
> Switch GHC 8.0 series to 8.0.2 in CI.

- README.md
> Tips for CI. [skip ci]

- appveyor.yml
> Add PATH to curl to slightly speed up build.

- Cabal/Distribution/Simple/Setup.hs
> Add WithCallStack to partial functions.

- appveyor.yml
> Fix #4456.

- Cabal/Cabal.cabal
- cabal-install/cabal-install.cabal
This is necessary for GHC 8.2.
> Bump upper bound on process

- cabal-install/Distribution/Client/FetchUtils.hs
IOW, treat the result-MVar like an IVar
The less optimal properties of `readMVar` prior to base-4.7 shouldn't
be a problem for this use-pattern (I hope).
A smallish repro-case which triggers the problem is e.g.
library
build-depends:       hspec-discover
build-tool-depends:  hspec-discover:hspec-discover
as this results in `waitAsyncPackageDownload` (which is a wrapper
around `waitAsyncFetchPackage`) being invoked twice for `hspec-discover`,
which results either in a `BlockedIndefinitelyInMVar` or in a
`BlockedIndefinitelyOnSTM` (depending on `-j`-level).
This is because our install plans can now use the same tarball for many builds,
e.g. different components and/or qualified goals, and these all go through the
download phase so we end up using `waitAsyncFetchPackage` twice on the same …
> Don't consume result in `waitAsyncFetchPackage`

- .travis.yml
- travis/binaries/.travis.yml
> Test Trusty Travis builds.

- cabal-install/Distribution/Client/ProjectConfig.hs
Just translate it to the local file case.
FYI: this is a trivial first step in a WIP branch on support for tarball packages, local and remote, which should make it easier to see how to integrate repo packages (ie git, darcs, etc)
> Handle file:// urls in cabal.project files

- cabal-testsuite/PackageTests/NewBuild/T4477/Main.hs
- cabal-testsuite/PackageTests/NewBuild/T4477/T4477.cabal
- cabal-testsuite/PackageTests/NewBuild/T4477/cabal.project
- cabal-testsuite/PackageTests/NewBuild/T4477/cabal.test.hs
> Failing test case for #4477.

- .github/PULL_REQUEST_TEMPLATE.md
Shamelessly cribbed from Stack.
[ci skip]
> Add a pull request template.

- Cabal/Cabal.cabal
- Cabal/Distribution/PackageDescription/Check.hs
- Cabal/Distribution/PackageDescription/Parse.hs
- Cabal/Distribution/PackageDescription/Parsec/FieldDescr.hs
- Cabal/Distribution/PackageDescription/PrettyPrint.hs
- Cabal/Distribution/Parsec/Class.hs
- Cabal/Distribution/Simple/Build.hs
- Cabal/Distribution/Simple/Configure.hs
- Cabal/Distribution/Simple/GHC.hs
- Cabal/Distribution/Simple/GHCJS.hs
- Cabal/Distribution/Simple/Haddock.hs
- Cabal/Distribution/Simple/Install.hs
- Cabal/Distribution/Simple/InstallDirs.hs
- Cabal/Distribution/Simple/LHC.hs
- Cabal/Distribution/Simple/Setup.hs
- Cabal/Distribution/Types/Executable.hs
- Cabal/Distribution/Types/ExecutableScope.hs
- Cabal/doc/installing-packages.rst
- cabal-install/Distribution/Client/ProjectPlanning.hs
- cabal-install/Distribution/Client/Setup.hs
- cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
Rebase of #3461 onto master. @23Skidoo
> Implement 'scope' field for executables (rebased on master)

- appveyor.yml
- cabal.project
> Remove unbounded-delays constraint.

- cabal-install/Distribution/Client/Init.hs
This PR attempts to solve issue #4496 .  This is my first contribution, and I would love feedback!  It builds locally and seems to fix the problem on my local machine.
> checks if license provided is alphanumeric. #4496 WIP

- travis/binaries/travis-test.sh
> Correctly apply rtsopts on MemoryUsageTests.

- cabal-install/cabal-install.cabal
> cabal-install.cabal: Improve comments for monolithic flag

- cabal-install/Distribution/Client/Compat/FileLock.hsc
- cabal-install/cabal-install.cabal
> Fix compilation with GHC 8.2

- Cabal/Distribution/Simple/GHC.hs
`other-modules` is intended for non-main modules (which is also stated
in the cabal manual). Unfortunately, a few packages, such as `happy` do
incorrectly specify `other-modules: Main` for their executables, thereby
causing GHC to complain about duplicate Main modules.
The workaround implemented here is to filter out the main module
name (while taking into account `ghc-options: -main-is ...`) from the
`other-modules` passed to GHC, and emit a warning in the process.
> Workaround invalid .cabal files with Main modules in other-extensions

- cabal-install/Distribution/Client/ProjectBuilding.hs
fixes #4521
This seems to work but I’m not sure if it is the right way to do
this. It also places the doc tarball in `dist-newstyle` instead of in
`dist`. While that seems reasonable for `new-haddock` this means that
currently (since there is not yet a `new-dist`) the doc tarball will
live in a different directory than the source tarball. I’m also not
sure if it should go in some subdirectory of new-dist instead.
It should probably also have an integration test but I haven’t yet
looked into what the best way to test this is.
> Make new-haddock --haddock-for-hackage generate doc tarball

- cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL.hs
- cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL/TestCaseUtils.hs
Now DSL.exResolve takes a goal-ordering function, which is more flexible
than a list of sorted goals.
____________________________________________________
This is the second commit from #4562.
> Refactor goal sorting in the solver DSL.

- AUTHORS
- Cabal/Cabal.cabal
- Cabal/Distribution/Simple/Test/LibV09.hs
- Cabal/Makefile
- Cabal/changelog
- Cabal/default.nix
- appveyor.yml
- cabal-install/bootstrap.sh
- cabal-install/changelog
- cabal-testsuite/cabal-testsuite.cabal
- travis-common.sh
- travis-deploy.sh
Once this PR is merged, I'll tag Cabal 2.0.0.2.
> Fix remaining GHC 8.2.1 blockers

- .travis.yml
- travis-common.sh
- travis-install.sh
- travis/upload.sh
> Upgrade to 2.0 branch.

- .travis.yml
- travis-common.sh
- travis-install.sh
- travis-script.sh
- travis/upload.sh
This is f3ade3fea60a8eadc90c0b0eaba20bcca7aceb1d cherry-picked to the 2.0 branch.
> Use cabal-install 2.0 on Travis for the 2.0 branch as well

- stack.yaml
> Bring stack.yaml up to date

- Cabal/Distribution/PackageDescription/PrettyPrint.hs
- Cabal/Distribution/Types/AbiHash.hs
- Cabal/Distribution/Types/Component.hs
- Cabal/Distribution/Types/ComponentId.hs
- Cabal/Distribution/Types/ComponentRequestedSpec.hs
- Cabal/Distribution/Types/GenericPackageDescription.hs
- Cabal/Distribution/Types/LegacyExeDependency.hs
- Cabal/Distribution/Types/MungedPackageName.hs
- Cabal/Distribution/Types/PackageDescription.hs
- Cabal/Distribution/Types/PackageName.hs
- Cabal/Distribution/Types/PkgconfigDependency.hs
- Cabal/Distribution/Types/PkgconfigName.hs
- Cabal/Distribution/Types/UnitId.hs
- Cabal/Distribution/Types/UnqualComponentName.hs
- Cabal/Distribution/Utils/ShortText.hs
- Cabal/Distribution/Version.hs
> Correct @since annotations

- Cabal/Cabal.cabal
- Cabal/tests/CheckTests.hs
- Cabal/tests/ParserTests.hs
> Use Diff for diffs in golden tests

- Cabal/Distribution/Types/BuildInfo.hs
> Improve Haddock markups (fixes #4703)

- Cabal/Distribution/Parsec/Types/ParseResult.hs
- Cabal/tests/CheckTests.hs
- Cabal/tests/ParserHackageTests.hs
- Cabal/tests/ParserTests.hs
> Implement all Applicative ParseResult methods

- Cabal/Cabal.cabal
- Cabal/tests/ParserTests.hs
- Cabal/tests/ParserTests/regressions/issue-774.cabal
- Cabal/tests/ParserTests/regressions/issue-774.format
> Add regression test. Resolves #774

- Cabal/Cabal.cabal
- Cabal/Distribution/Compat/Lens.hs
- Cabal/Distribution/Types/BuildInfo/Lens.hs
- Cabal/Distribution/Types/Library.hs
- Cabal/Distribution/Types/Library/Lens.hs
- Cabal/Distribution/Types/PackageDescription/Lens.hs
- Cabal/Distribution/Types/SourceRepo/Lens.hs
- generics-sop-lens.hs
> Add SourceRepo.Lens

- Cabal/Cabal.cabal
- Cabal/Distribution/Types/Benchmark/Lens.hs
- Cabal/Distribution/Types/Executable/Lens.hs
- Cabal/Distribution/Types/ForeignLib/Lens.hs
- Cabal/Distribution/Types/SetupBuildInfo/Lens.hs
- Cabal/Distribution/Types/TestSuite/Lens.hs
- Benchmark
- Executable
- ForeignLib
- SetupBuildInfo
- TestSuite
> Add more lens modules

- Cabal/default.nix
- cabal-install/default.nix
I built `cabal-install` with Nix.
> Re-generate default.nix files with cabal2nix to fix builds.

- Cabal/Distribution/Compat/Lens.hs
I might need this for parser work (to provide accumulating grammar evaluation)
---
> Add ALens machinery

- Cabal/Cabal.cabal
- Cabal/Distribution/Compat/Lens.hs
- Cabal/Distribution/Types/Executable/Lens.hs
- Cabal/Distribution/Types/Lens.hs
- Cabal/Distribution/Types/PackageId/Lens.hs
> Add D.Types.PackageId.Lens and D.Types.Lens

- Cabal/Distribution/Utils/Generic.hs
Also doctestify few examples in Utils.Generics
---
> Add unfoldrM, spanMaybe, breakMaybe

- Cabal/Distribution/Compat/Prelude.hs
> Use any/all from Foldable

- Cabal/Distribution/Simple/Utils.hs
This mitigates the inconvenience of #4757.
> Utils: Emit current working directory of run processes in debug output

- cabal-install/Distribution/Client/Upload.hs
The message now reads like
$ cabal upload -d dist/uhttpc-0.1.1.1-docs.tar.gz
Uploading documentation dist/uhttpc-0.1.1.1-docs.tar.gz...
Documentation successfully uploaded for package candidate. You can now preview
the result at
'https://hackage-origin.haskell.org/package/uhttpc-0.1.1.1/candidate'. To
upload non-candidate documentation, use 'cabal upload --publish'.
while previously it read like
$ cabal upload -d dist/uhttpc-0.1.1.1-docs.tar.gz
Uploading documentation dist/uhttpc-0.1.1.1-docs.tar.gz...
Ok
This improves usability as it gives a clear signal the docs have been
uploaded as candidate, and also on which URL you can see the result.
This implements the suggestion voiced in
https://github.com/haskell/cabal/issues/4777#issuecomment-330790520
Please include the following checklist …
> Improve success message when `cabal upload`ing documentation

- Cabal/Distribution/Simple/Build/PathsModule.hs
> Fix a typo

- .travis.yml
- Cabal/misc/gen-extra-source-files.hs
> Update meta to work on GHC-8.2.1

- Cabal/tests/ParserTests/regressions/issue-774.cabal
- Cabal/tests/ParserTests/regressions/issue-774.format
> Fixes #2661. Add a regression test, issue is already fixed

- cabal-install/Distribution/Client/List.hs
- cabal-install/Distribution/Client/Nix.hs
- cabal-install/Distribution/Client/ParseUtils.hs
- cabal-install/Distribution/Client/Reconfigure.hs
> Preliminary base-4.11 compatibility fixes

- Cabal/doc/developing-packages.rst
> WIP rewording docs

- Cabal/Distribution/Text.hs
> fixed comment typo: 'is' to 'it' [ci skip]

- .travis.yml
> Travis: use 8.2.2 to compile configurations with expensive asserts.

- .travis.yml
- cabal-install/Distribution/Client/SetupWrapper.hs
- cabal-install/bootstrap.sh
- cabal-install/cabal-install.cabal
- cabal-install/changelog
- cabal-testsuite/PackageTests/TestSuiteTests/ExeV10/setup-with-hpc.multitest.hs
>  cabal-install: Remove support for building with GHC < 7.10.

- Cabal/Distribution/PackageDescription/Check.hs
This is to address #4551.
This was tested by fetching `edit-distance`, trying the various combinations of `-O0`/`-O2` in the library / test / benchmark sections, and checking the output and return code.
> Changes to `cabal check` for `-O0` with tests or benchmarks.

- Cabal/Distribution/Parsec/Lexer.hs
- Cabal/misc/travis-diff-files.sh
- Makefile
- travis-meta.sh
> Enable 'make lexer' in travis-meta.

- Cabal/Cabal.cabal
- Cabal/tests/ParserTests.hs
- Cabal/tests/ParserTests/ipi/transformers.cabal
- Cabal/tests/ParserTests/ipi/transformers.format
First step towards solving #2276 
---
> InstalledPackageInfo parser roundtrip test

- Cabal/Cabal.cabal
- Cabal/tests/custom-setup/CabalDoctestSetup.hs
- Cabal/tests/custom-setup/CustomSetupTests.hs
- Cabal/tests/custom-setup/IdrisSetup.hs
- cabal-dev-scripts/cabal-dev-scripts.cabal
- cabal-dev-scripts/src/GenExtraSourceFiles.hs
- cabal-install/cabal-install.cabal
> Add cabal-doctest and idris Setup.hs as smoke tests for BC

- cabal-install/Distribution/Client/ProjectPlanning.hs
based on a suggestion by @ezyang
Workarounds #4548 for now.
> Suppress per-component for build-type:configure

- Cabal/Cabal.cabal
- Cabal/Distribution/InstalledPackageInfo.hs
- Cabal/Distribution/Types/InstalledPackageInfo.hs
- Cabal/Distribution/Types/InstalledPackageInfo/Lens.hs
This adds only structural lenses, I'll add more higher level ones in the next PR
---
> Add Distribution.Types.InstalledPackageInfo.Lens

- Cabal/Cabal.cabal
- Cabal/Distribution/FieldGrammar/Parsec.hs
- Cabal/Distribution/PackageDescription/Parsec.hs
- Cabal/Distribution/Parsec/Common.hs
- Cabal/Distribution/Types/BuildType.hs
- Cabal/Distribution/Types/PackageDescription.hs
- Cabal/tests/ParserTests.hs
- Cabal/tests/ParserTests/regressions/common2.cabal
- Cabal/tests/ParserTests/regressions/common2.expr
- Cabal/tests/ParserTests/regressions/common2.format
- Cabal/tests/ParserTests/regressions/encoding-0.8.cabal
- Cabal/tests/ParserTests/regressions/encoding-0.8.format
- Cabal/tests/ParserTests/warnings/multiplesingular.cabal
- cabal-testsuite/PackageTests/Regression/T4270/T4270.cabal
- cabal-testsuite/PackageTests/TestSuiteTests/LibV09/LibV09.cabal
Fixes #5020, includes #5021 
---
> Build type default

- Cabal/Distribution/ModuleName.hs
- Cabal/Distribution/Package.hs
- Cabal/Distribution/PackageDescription/Configuration.hs
- Cabal/Distribution/PrettyUtils.hs
- Cabal/Distribution/ReadE.hs
- Cabal/Distribution/Simple/LocalBuildInfo.hs
- Cabal/Distribution/Simple/PackageIndex.hs
- Cabal/Distribution/Simple/Program.hs
- Cabal/Distribution/Types/GenericPackageDescription.hs
- Cabal/Distribution/Types/Library.hs
- Cabal/Distribution/Types/LocalBuildInfo.hs
- Cabal/Distribution/Types/PackageDescription.hs
- Cabal/Distribution/Types/UnitId.hs
- Cabal/Distribution/Types/Version.hs
- Cabal/Distribution/Version.hs
- Cabal/Language/Haskell/Extension.hs
> Issue 4406

- Cabal/Cabal.cabal
- Cabal/tests/UnitTests/Distribution/Version.hs
> Use QuickCheck-2.11, get rid of an orphan

- Cabal/Distribution/PackageDescription/Parsec.hs
- cabal-install/Distribution/Client/Check.hs
> Promote parser warnings into PackageChecks in 'cabal check'

- Cabal/Distribution/Types/GenericPackageDescription.hs
This is useful for code that uses "parallel" in combination with Cabal data
structures (like we do in cabal2nix and hackage2nix).
> Derive NFData for FlagName and FlagAssignment.

- Cabal/Cabal.cabal
- Cabal/Distribution/Compat/Lens.hs
- Cabal/Distribution/Parsec/Common.hs
- Cabal/tests/HackageTests.hs
- travis-script.sh
- travis/binaries/travis-test.sh
- travis/upload.sh
- validate.sh
> Hackage tests optparse applicative

- travis/binaries/.travis.yml
- travis/binaries/travis-test.sh
> Enable hackage-tests on downstream travis

- cabal-install/Distribution/Client/CmdErrorMessages.hs
> Fix typo in new-build error message.

- Cabal/Distribution/PackageDescription/FieldGrammar.hs
> Mark cxx-options, cxx-sources and virtual-modules available since spec 2.1

- cabal-install/Distribution/Client/CmdUpdate.hs
Straightforward port of the fix from #4950 to `new-update`. Tested by running `new-update` and checking that the `.tar` file has an updated timestamp.
---
>  Port #4950 to new-update.

- cabal-install/Distribution/Client/SetupWrapper.hs
> SetupWrapper: Dump Setup arguments

- Cabal/Distribution/Simple/Haddock.hs
`--ghc-options` flags are passed all the way through to Haddock. In the process, `argGhcOptions` is no longer a `Flag` and no longer requires a bogus GHC version (Haddock will handle those issues).
This fixes #4982.
---
> Haddock support for '--ghc-options'

- Cabal/Distribution/License.hs
- Cabal/Distribution/SPDX/LicenseExceptionId.hs
- Cabal/Distribution/SPDX/LicenseExpression.hs
- Cabal/Distribution/SPDX/LicenseId.hs
- boot/SPDX.LicenseId.template.hs
- license-list-data/exceptions.json
- license-list-data/licenses.json
Resolves https://github.com/haskell/cabal/issues/5145
(Note: the spec is 2.1 but license list version is 3.0 - they have different version numbers).
---
> Update SPDX license list to 3.0 (28 December 2017)

- cabal-install/Distribution/Solver/Modular.hs
- cabal-install/Distribution/Solver/Modular/ConflictSet.hs
- cabal-install/Distribution/Solver/Modular/Dependency.hs
- cabal-install/Distribution/Solver/Modular/Explore.hs
> Solver cleanup

- cabal-testsuite/PackageTests/Regression/T4154/install-time-with-constraint.out
- cabal-testsuite/PackageTests/Regression/T4154/install-time-with-constraint.test.hs
- cabal-testsuite/PackageTests/Regression/T4154/repo/Cabal-99999/Cabal.cabal
This commit addresses the comments in PR #5183.
______________________________________________________________________
I can also cherry-pick this onto the 2.2 branch after it's merged.
> Update regression test for issue #4154 after the fix for issue #415.

- Cabal/Distribution/Types/BuildInfo.hs
> Fix typo [ci skip]

- appveyor.yml
- cabal-install/Distribution/Client/HttpUtils.hs
> Backport #5197 to 2.2

- cabal-install/bootstrap.sh
> Bump dep versions in the bootstrap script.

- Cabal/ChangeLog.md
- Cabal/Distribution/PackageDescription/Check.hs
I confirmed with the repro in #5206
> Add missing relative for getFileContents #5206

- Cabal/doc/nix-local-build.rst
> new-install docs

- Cabal/tests/UnitTests/Distribution/SPDX.hs
> Add isAcceptedLicense to the test-suite

- Cabal/Distribution/Types/BuildInfo.hs
This is just a port of PR #5233 into 2.2 branch.
> Cherry-pick typo fix to 2.2

- Cabal/Distribution/Simple/Glob.hs
> Small readability improvement.

- .travis.yml
- cabal-dev-scripts/cabal-dev-scripts.cabal
- cabal-dev-scripts/src/GenExtraSourceFiles.hs
- update-cabal-files.sh
> .travis.yml: Use 8.4.2 for the meta check.

- cabal-install/changelog
> Add changelog entry for PR #5304.

- cabal-testsuite/PackageTests/NewBuild/CmdExec/GhcInvocation/cabal.test.hs
- cabal-testsuite/Test/Cabal/Prelude.hs
> Fix a 7.10.3 build found in https://github.com/haskell/cabal/pull/5319

- .travis.yml
- cabal-testsuite/Test/Cabal/Monad.hs
> .travis.yml: s/8.4.2/8.4.3/

- cabal-testsuite/PackageTests/Backpack/Includes1/setup.test.hs
- cabal-testsuite/PackageTests/Backpack/Includes5/setup.test.hs
- cabal-testsuite/PackageTests/BuildDeps/TargetSpecificDeps1/setup.test.hs
- cabal-testsuite/PackageTests/BuildDeps/TargetSpecificDeps3/setup.test.hs
> Update tests to accomodate output changes in GHC HEAD.

- Cabal/ChangeLog.md
- Cabal/Language/Haskell/Extension.hs
> 8.6 extensions

- cabal-testsuite/PackageTests/Check/MissingGlobDirectory2/cabal.out
- cabal-testsuite/PackageTests/Check/MissingGlobDirectory2/dir/foo.en.html
- cabal-testsuite/PackageTests/Check/MissingGlobDirectory2/pkg.cabal
> Make sure one more glob/check case is being exercised by tests

- Cabal/doc/nix-local-build.rst
> Remove note about bug in Cabal 1.24

- appveyor.yml
- cabal-testsuite/PackageTests/Check/MissingGlobDirectory/cabal.out
- cabal-testsuite/PackageTests/Check/MissingGlobDirectory/cabal.test.hs
- cabal-testsuite/cabal-testsuite.cabal
Like #5486, but for 2.4. See https://github.com/haskell/cabal/commit/123291c0939789aa7c3e4970c4a22adf50c0a9ee#comments.
---
> Try to fix AppVeyor (2.4).

- appveyor.yml
- cabal-testsuite/PackageTests/Check/MissingGlobDirectory/cabal.out
- cabal-testsuite/PackageTests/Check/MissingGlobDirectory/cabal.test.hs
- cabal-testsuite/cabal-testsuite.cabal
See https://github.com/haskell/cabal/commit/123291c0939789aa7c3e4970c4a22adf50c0a9ee#comments.
---
> Try to fix AppVeyor.

- Cabal/doc/nix-local-build.rst
> Update outdated references to cabal HEAD in nix-style-local-build docs

- cabal-install/Distribution/Client/CmdSdist.hs
- cabal-testsuite/PackageTests/NewSdist/ManyDataFiles/Main.hs
- cabal-testsuite/PackageTests/NewSdist/ManyDataFiles/cabal.project
- cabal-testsuite/PackageTests/NewSdist/ManyDataFiles/many-data-files.cabal
- cabal-testsuite/PackageTests/NewSdist/ManyDataFiles/many-data-files.out
- cabal-testsuite/PackageTests/NewSdist/ManyDataFiles/many-data-files.test.hs
- cabal-testsuite/Test/Cabal/Prelude.hs
Fixes #5541.
Closes #5542.
I think I know the one-line fix to cure the bug, but I want to toss my attempted test at the CI and see if it can at least fail correctly first.
> Fix #5541.

- travis/binaries/travis-test.sh
- travis/upload.sh
> New S3 based build product upload

- cabal-install/Distribution/Client/CmdRepl.hs
> Filter out executables from package-id flags

- cabal-install/bootstrap.sh
> Fix a typo in cabal-install/bootstrap.sh [ci skip]

- Cabal/Distribution/Compat/Directory.hs
- Cabal/Distribution/Simple/Configure.hs
> Check existence of packagedb before dumping it

- cabal-install/Distribution/Client/CmdRun.hs
- cabal-install/Distribution/Client/ProjectBuilding.hs
- cabal-install/Distribution/Client/ProjectPlanning.hs
- cabal-install/Distribution/Client/ProjectPlanning/Types.hs
> Datadir env var generation for vcs and tarballs

- cabal-install/Distribution/Client/ProjectPlanning/Types.hs
As the case of `cpphs-1.20.8` has shown in #5379, in cases when a
monolithic package gets installed due to its executable components
(i.e. `exe:cpphs`) into the store we *have* to register if there's a
buildable public library (i.e. `lib:cpphs`) that was built and installed
into the same store folder as otherwise this will cause build failures
once a target actually depends on `lib:cpphs`
This ought to fix #5379
(TODO: changelog entry when cherry-picking to 2.4)
> Do register monolithic packages if they contain a buildable pub-lib

- cabal-install/Distribution/Client/ProjectBuilding.hs
Using windows/msys paths can contain both kinds of slashes.
This causes issues when we compare paths but don't normalize
them, leading us to assume they refer to different locations.
I've tested it by using new-build on a bunch of projects with custom store dirs.
This fixes #5458
---
https://github.com/AndreasPK/cabal/commits/master).
No behaviour change.
> Fix a bug where cabal tried to copy files after moving them.

- cabal-install/Distribution/Client/CmdInstall.hs
- cabal-install/Distribution/Client/DistDirLayout.hs
- cabal-install/Distribution/Client/ProjectOrchestration.hs
Note: Since `mkCabalDirLayout` is pure I had to `makeAbsolute` at each caller. Maybe I should just make it impure instead..
Fixes #5485
/cc @hvr
> Make store path absolute

- cabal-install/Distribution/Client/CmdInstall.hs
> Don't install anything if --dry is used

- cabal-install/Distribution/Client/CmdInstall.hs
Temporary hotfix until we have a proper fix for #5641 
/cc @hvr
> Warn on new-install failure (temp hotfix for #5641)

- Cabal/doc/nix-local-build.rst
- cabal-install/Distribution/Client/CmdBuild.hs
- cabal-install/Distribution/Client/CmdExec.hs
- cabal-install/Distribution/Client/ProjectPlanning.hs
- cabal-install/Distribution/Client/ProjectPlanning/Types.hs
- cabal-install/Distribution/Client/Setup.hs
- cabal-install/changelog
- cabal-testsuite/PackageTests/NewBuild/CmdBuild/OnlyConfigure/Bar.hs
- cabal-testsuite/PackageTests/NewBuild/CmdBuild/OnlyConfigure/Baz.hs
- cabal-testsuite/PackageTests/NewBuild/CmdBuild/OnlyConfigure/Foo.hs
- cabal-testsuite/PackageTests/NewBuild/CmdBuild/OnlyConfigure/Lib.hs
- cabal-testsuite/PackageTests/NewBuild/CmdBuild/OnlyConfigure/OnlyConfigure.cabal
- cabal-testsuite/PackageTests/NewBuild/CmdBuild/OnlyConfigure/cabal.out
- cabal-testsuite/PackageTests/NewBuild/CmdBuild/OnlyConfigure/cabal.project
- cabal-testsuite/PackageTests/NewBuild/CmdBuild/OnlyConfigure/cabal.test.hs
This is a backport of #5578 to 2.4
> Backport #5578

- .travis.yml
- README.md
- cabal-testsuite/PackageTests/CustomDep/custom/custom.cabal
- travis-common.sh
- travis-install.sh
- travis-meta.sh
- travis-script.sh
- travis/binaries/.travis.yml
- travis/upload.sh
> Travis: Use cabal-install-2.4, drop cabal-install-head.

- Cabal/Distribution/SPDX/LicenseExceptionId.hs
- Cabal/Distribution/SPDX/LicenseId.hs
- Cabal/Distribution/SPDX/LicenseListVersion.hs
- Cabal/doc/file-format-changelog.rst
- Makefile
- boot/SPDX.LicenseExceptionId.template.hs
- boot/SPDX.LicenseId.template.hs
- cabal-dev-scripts/src/GenSPDX.hs
- cabal-dev-scripts/src/GenSPDXExc.hs
- cabal-dev-scripts/src/GenUtils.hs
- license-list-data/exceptions-3.3.json
- license-list-data/licenses-3.3.json
Resolves https://github.com/haskell/cabal/issues/5687
---
> SDPX License List 3.3

- Cabal/Distribution/PackageDescription/Check.hs
> Use Pretty (not Text) in D.P.Check

- Cabal/Distribution/Backpack/ComponentsGraph.hs
- Cabal/Distribution/Backpack/Configure.hs
- Cabal/Distribution/Backpack/ConfiguredComponent.hs
- Cabal/Distribution/Backpack/DescribeUnitId.hs
- Cabal/Distribution/Backpack/Id.hs
- Cabal/Distribution/Backpack/LinkedComponent.hs
- Cabal/Distribution/Backpack/MixLink.hs
- Cabal/Distribution/Backpack/ModuleScope.hs
- Cabal/Distribution/Backpack/ReadyComponent.hs
- Cabal/Distribution/Backpack/UnifyM.hs
> Remove Text from D.BackPack

- Cabal/Distribution/CabalSpecVersion.hs
- Cabal/Distribution/FieldGrammar.hs
- Cabal/Distribution/FieldGrammar/Class.hs
- Cabal/Distribution/FieldGrammar/Parsec.hs
- Cabal/Distribution/FieldGrammar/Pretty.hs
- Cabal/Distribution/PackageDescription/FieldGrammar.hs
- Cabal/Distribution/PackageDescription/Parsec.hs
- Cabal/Distribution/Types/BuildType.hs
- Cabal/Distribution/Types/InstalledPackageInfo/FieldGrammar.hs
- Cabal/tests/ParserTests/regressions/wl-pprint-indef.format
> Make CabalSpecVersion complete

- cabal-install/Distribution/Client/CmdSdist.hs
See: https://github.com/haskell/cabal/pull/5755#issuecomment-443542558
> Fix Incorrect `tar.gz` Extension

- Cabal/Distribution/Simple/Configure.hs
Closes #4291
This can be broken when we explicitly set a prefix outside of pkgroot, even for ghc > 8.0. To repro:
```
$ cd /tmp
$ cabal get pandoc
$ cd pandoc-2.4
$ cabal sandcastle init
$ cabal install --only-dependencies --enable-relocatable --prefix=/tmp/prefix
...
Configuring blaze-markup-0.8.2.2...
cabal: Library directory of a dependency:
"/tmp/pandoc-2.4/.cabal-sandbox/../../prefix/lib/x86_64-linux-ghc-8.6.2/blaze-builder-0.4.1.0-KrFxFv3kgua3BTNMsMBadC"
is not relative to the installation prefix:
"/tmp/prefix"
```
We can fix it by simply canonicalize the path before comparing.
---
> Fix checkRelocatable for deps when prefix is not subdir of pkgroot

- .gitignore
- Cabal/Makefile
- Cabal/doc/cabaldomain.py
- Cabal/doc/developing-packages.rst
- Cabal/doc/file-format-changelog.rst
I changed how to build docs a little using `virtualenv`. That's IMHO a bit saner approach
> Spec changes 3.0 [docs]

- Cabal/Distribution/FieldGrammar/FieldDescrs.hs
- Cabal/Distribution/FieldGrammar/Parsec.hs
- Cabal/Distribution/Fields.hs
- Cabal/Distribution/InstalledPackageInfo.hs
- cabal-install/Distribution/Client/SourceRepoParse.hs
> Use FieldName in FieldGrammar.FieldDescrs

- .gitattributes
- cabal-testsuite/PackageTests/NewBuild/CmdRun/Script/cabal.project
- cabal-testsuite/PackageTests/NewBuild/CmdRun/Script/cabal.test.hs
- cabal-testsuite/PackageTests/NewBuild/CmdRun/Script/script.cabal
- cabal-testsuite/PackageTests/NewBuild/CmdRun/Script/script.hs
Add a test, which should allow merging #5790.
> Add test for script extraction

- cabal-install/Distribution/Client/CmdRun.hs
- cabal-install/main/Main.hs
> Fix shebang handling code

- Cabal/ChangeLog.md
- Cabal/Distribution/Compat/Prelude.hs
- Cabal/doc/developing-packages.rst
- Cabal/doc/nix-local-build.rst
- cabal-install/Distribution/Client/Compat/Prelude.hs
- cabal-install/Distribution/Client/ProjectPlanning.hs
- cabal-install/Distribution/Solver/Compat/Prelude.hs
- cabal-install/tests/UnitTests/Distribution/Client/InstallPlan.hs
> Typofixes in comments and docs

- Cabal/doc/developing-packages.rst
> Copy edit the docs: simply -> simplify

- cabal-install/Distribution/Client/CmdTest.hs
Follow-up as promised on https://github.com/haskell/cabal/pull/5768#discussion_r239067205.
---
> Minor code cleanup to address @23Skidoo's comment.

- Cabal/Distribution/Parsec/Newtypes.hs
> Export Sep

- Cabal/Cabal.cabal
- Cabal/Distribution/PackageDescription/Parsec.hs
- Cabal/tests/ParserTests.hs
- Cabal/tests/ParserTests/errors/undefined-flag.cabal
- Cabal/tests/ParserTests/errors/undefined-flag.errors
> Check for used but undefined flags already in parser

- Cabal/Distribution/PackageDescription/Quirks.hs
> Add undefined flag quirks

- cabal-install/Distribution/Client/ProjectPlanning.hs
- cabal-install/Distribution/Client/ProjectPlanning/Types.hs
- cabal-testsuite/PackageTests/Backpack/bkpcabal01/Main.hs
- cabal-testsuite/PackageTests/Backpack/bkpcabal01/bkpcabal01.cabal
- cabal-testsuite/PackageTests/Backpack/bkpcabal01/cabal.out
- cabal-testsuite/PackageTests/Backpack/bkpcabal01/cabal.project
- cabal-testsuite/PackageTests/Backpack/bkpcabal01/cabal.test.hs
- cabal-testsuite/PackageTests/Backpack/bkpcabal01/impl/H.hs
- cabal-testsuite/PackageTests/Backpack/bkpcabal01/impl/I.hs
- cabal-testsuite/PackageTests/Backpack/bkpcabal01/p/H.hsig
- cabal-testsuite/PackageTests/Backpack/bkpcabal01/p/P.hs
- cabal-testsuite/PackageTests/Backpack/bkpcabal01/q/I.hsig
- cabal-testsuite/PackageTests/Backpack/bkpcabal01/q/Q.hs
This exemplifies the bpkcabal01 regression (introduced via #5863); @ezyang is aware of this
See e.g. failure at
- https://travis-ci.org/haskell/cabal/jobs/504058651#L4431
- https://travis-ci.org/haskell/cabal/jobs/504058649#L3944
> Add bkpcabal01 regression test-case

- cabal-install/Distribution/Client/Upload.hs
it turns out that Cabal will happily send your password to whatever the
last configured `repository` is (see #4402). This is a security risk!
Therefore, following common best practice, this patch makes sure to
include the domain name in the username and password prompts.
Please also shortly describe how you tested your change:
```
~/build/haskell/cabal $ cabal new-run cabal -- upload ./dist-newstyle/sdist/Cabal-2.5.0.0.tar.gz
Warning: The package list for 'hackage.haskell.org' is 30 days old.
Run 'cabal update' to get the latest list of available packages.
Up to date
hackage.haskell.org password: 
~/build/haskell/cabal $ gvim ~/.cabal/config # add repository
~/build/haskell/cabal $ cabal new-run cabal -- upload ./dist-newstyle/sdist/Cabal-2.5.0.0.tar.gz
Warning: …
```
> Include the domain name in the password prompt

- Cabal/doc/developing-packages.rst
- Cabal/doc/nix-local-build-overview.rst
- Cabal/doc/nix-local-build.rst
> Convert all new- to v2- in docs [ci skip]

- .travis.yml
- Cabal/Distribution/Simple/GHC.hs
> Support window 8.8

- Cabal/Distribution/Compat/CopyFile.hs
`normalise` from `System.FilePath` has an annoying behavior in that it doesn't simplify `FilePath`. The documented behavior on Windows is to normalise `Z://` into `Z:\\\\` which in the `Win32` namespace won't matter but since we're using the `device` namespace `\\?\Z:\\` is an invalid path to the filesystem.
This results in cabal throwing an illegal path exception for such cases which happen to be fairly common when building `GHC`.  This fixes it by inlining some more code from `System.Directory` which has a function which correctly preserves the semantics of a path when converted to a device path.
Tested with a full GHC bootstrap and testrun. Fixes https://gitlab.haskell.org/ghc/ghc/merge_requests/619
---
Please also shortly describe how …
> Cabal: don't use normalise for copyFile on Windows

- Cabal/Cabal.cabal
- Cabal/ChangeLog.md
- Cabal/Distribution/Compat/Newtype.hs
- Cabal/Distribution/FieldGrammar/Class.hs
- Cabal/Distribution/Parsec/Newtypes.hs
- Cabal/Distribution/SPDX/LicenseExceptionId.hs
- Cabal/Distribution/SPDX/LicenseId.hs
- Cabal/Distribution/Types/InstalledPackageInfo/FieldGrammar.hs
- Cabal/tests/UnitTests/Distribution/SPDX.hs
- boot/SPDX.LicenseExceptionId.template.hs
- boot/SPDX.LicenseId.template.hs
> Changes 2019 04 23

- cabal-install/bash-completion/cabal
`new-install`: only complete for local packages.
> cleanup (bash-completion)

- Cabal/Distribution/Simple/Haddock.hs
Related: https://github.com/haskell/haddock/pull/547
---
> Pass --rexport for reexported-modules to haddock

- Cabal/Distribution/PackageDescription/Check.hs
> Fix spelling error

- Cabal/Distribution/Compat/ResponseFile.hs
Fixes #6061
Arguments to `--index-state` also use the `@` syntax, so instead of exiting when a non-existent response file is passed as an argument, print a warning and pass it as a literal argument. `--index-state=@1234` continues to work without warnings.
---
> Pass `@...` as a literal argument if the response file does not exist and support recursive response files

- Cabal/Distribution/Compat/Parsing.hs
- Cabal/Distribution/Compat/Prelude.hs
- Cabal/Distribution/Fields/ConfVar.hs
- Cabal/Distribution/PackageDescription/Configuration.hs
- Cabal/Distribution/Simple/PackageIndex.hs
- Cabal/Distribution/Simple/Test/Log.hs
- Cabal/Distribution/Types/PkgconfigVersionRange.hs
- Cabal/Distribution/Types/VersionInterval.hs
- Cabal/Distribution/Types/VersionRange/Internal.hs
- cabal-install/Distribution/Client/TargetSelector.hs
- cabal-install/Distribution/Solver/Types/PackageIndex.hs
> Fix #6082: Use pseudo-NonEmpty

- cabal-install/Distribution/Client/CmdInstall.hs
> Only build what's necessary for `v2-install`

- cabal-install/Distribution/Client/CmdInstall.hs
- cabal-install/changelog
> Add default for v2-install

- cabal-install/Distribution/Client/CmdInstall/ClientInstallFlags.hs
- cabal-install/changelog
> Fix install-method and overwrite-policy in .cabal/config

- cabal-install/Distribution/Client/CmdInstall.hs
- cabal-install/Distribution/Client/CmdRepl.hs
- cabal-install/Distribution/Client/CmdRun.hs
- cabal-install/changelog
> Fix `v2-repl` changing directory incorrectly.

- cabal-install/Distribution/Client/ProjectConfig.hs
The original error constructors had zero extra information (for
debugginng) when triggered. The error message "NoCabalFileFound"
is simply not useful without further context.
All of the existing CabalFileSearchFailure constructors now include
a FilePath field.
---
> Improve CabalFileSearchFailure messages

- cabal-testsuite/PackageTests/NewBuild/CmdRun/Script/cabal.out
- cabal-testsuite/PackageTests/NewBuild/CmdRun/Script/cabal.test.hs
- cabal-testsuite/PackageTests/NewBuild/CmdRun/Script/script.hs
> Issue 5775 seems to be fixed, let's see

- cabal-install/Distribution/Client/CmdHaddock.hs
- cabal-install/Distribution/Client/ProjectOrchestration.hs
- cabal-testsuite/PackageTests/NewHaddock/Fails/Example.hs
- cabal-testsuite/PackageTests/NewHaddock/Fails/cabal.out
- cabal-testsuite/PackageTests/NewHaddock/Fails/cabal.project
- cabal-testsuite/PackageTests/NewHaddock/Fails/cabal.test.hs
- cabal-testsuite/PackageTests/NewHaddock/Fails/example.cabal
> Issue 5977

- Cabal/Cabal.cabal
- Cabal/Distribution/Fields/ParseResult.hs
- Cabal/Distribution/InstalledPackageInfo.hs
- Cabal/Distribution/Simple/HaskellSuite.hs
- Cabal/Distribution/Simple/Program/HcPkg.hs
- Cabal/tests/CheckTests.hs
- Cabal/tests/ParserTests.hs
- cabal-install/Distribution/Client/Install.hs
- cabal-install/Distribution/Client/ProjectBuilding.hs
- cabal-install/Distribution/Client/ProjectConfig.hs
- cabal-install/Distribution/Client/Utils/Parsec.hs
- cabal-install/cabal-install.cabal
- cabal-install/cabal-install.cabal.pp
> runParseResult reutrns NonEmpty PError

- Cabal/Distribution/SPDX/LicenseExceptionId.hs
- Cabal/Distribution/SPDX/LicenseId.hs
- Cabal/Distribution/SPDX/LicenseListVersion.hs
- Cabal/doc/file-format-changelog.rst
- Cabal/tests/UnitTests/Distribution/SPDX.hs
- Makefile
- boot/SPDX.LicenseExceptionId.template.hs
- boot/SPDX.LicenseId.template.hs
- cabal-dev-scripts/src/GenSPDX.hs
- cabal-dev-scripts/src/GenSPDXExc.hs
- cabal-dev-scripts/src/GenUtils.hs
- license-list-data/exceptions-3.6.json
- license-list-data/licenses-3.6.json
> Update to SPDX License List 3.6 2019-07-10

- Cabal/Distribution/FieldGrammar/Parsec.hs
- Cabal/tests/ParserTests/regressions/multiple-libs-2.check
- Cabal/tests/ParserTests/regressions/multiple-libs-2.format
- Cabal/tests/ParserTests/regressions/wl-pprint-indef.format
Supersedes https://github.com/haskell/cabal/pull/6151
> parser: Clearly state that invalid fields are ignored

- Cabal/Distribution/FieldGrammar/Parsec.hs
- Cabal/Distribution/SPDX/LicenseExceptionId.hs
- Cabal/Distribution/SPDX/LicenseId.hs
- Cabal/Distribution/SPDX/LicenseListVersion.hs
- Cabal/doc/file-format-changelog.rst
- Cabal/tests/ParserTests/regressions/multiple-libs-2.check
- Cabal/tests/ParserTests/regressions/multiple-libs-2.format
- Cabal/tests/ParserTests/regressions/wl-pprint-indef.format
- Cabal/tests/UnitTests/Distribution/SPDX.hs
- Makefile
- boot/SPDX.LicenseExceptionId.template.hs
- boot/SPDX.LicenseId.template.hs
- cabal-dev-scripts/src/GenSPDX.hs
- cabal-dev-scripts/src/GenSPDXExc.hs
- cabal-dev-scripts/src/GenUtils.hs
- license-list-data/exceptions-3.6.json
- license-list-data/licenses-3.6.json
> Backports ignore msg spdx

- cabal-install/Distribution/Client/SourceFiles.hs
This ought to be the right fix, but I'm not actually sure what the original code is achieving here. When would headers go in `extra-source-files` rather than `includes`?
---
> Properly expand globs when looking for headers in extra-src-files.

- Cabal/doc/installing-packages.rst
> doc: Linkify some :pkg-fields:

- .github/ISSUE_TEMPLATE/bug_report.md
> Fix spelling error in bug report template [ci skip]

- .travis.yml
> Bump from GHC 8.6.4 to 8.6.5

- Cabal/Distribution/Backpack/ComponentsGraph.hs
- Cabal/Distribution/Compat/Prelude.hs
- Cabal/Distribution/PackageDescription/Check.hs
- Cabal/Distribution/Simple.hs
- Cabal/Distribution/Simple/Build.hs
- Cabal/Distribution/Simple/Configure.hs
- Cabal/Distribution/Simple/GHC.hs
- Cabal/Distribution/Simple/GHCJS.hs
- Cabal/Distribution/Simple/HaskellSuite.hs
- Cabal/Distribution/Simple/Program/HcPkg.hs
- Cabal/Distribution/Simple/Program/Run.hs
- Cabal/Distribution/Simple/UHC.hs
- Cabal/Distribution/Types/VersionInterval.hs
- Cabal/Distribution/Types/VersionRange.hs
- Cabal/Distribution/Utils/Generic.hs
- Cabal/Language/Haskell/Extension.hs
- Cabal/tests/UnitTests/Distribution/Version.hs
- cabal-install/Distribution/Client/CmdInstall.hs
- cabal-install/Distribution/Client/CmdRepl.hs
- cabal-install/Distribution/Client/HttpUtils.hs
- cabal-install/Distribution/Client/Init/Heuristics.hs
- cabal-install/Distribution/Client/Outdated.hs
- cabal-install/Distribution/Client/SetupWrapper.hs
- cabal-install/Distribution/Deprecated/ViewAsFieldDescr.hs
- cabal-install/main/Main.hs
- cabal-install/solver-dsl/UnitTests/Distribution/Solver/Modular/DSL.hs
rebased #6330 with doctests fixed
> Replace Prelude.head/tail/init/last with NonEmpty

- .travis.yml
> Change travis dist: trusty -> xenial

- cabal-testsuite/cabal-testsuite.cabal
- solver-benchmarks/solver-benchmarks.cabal
- validate.dockerfile
Pre-installing deps should speed-up validation;
marginally, but still few minutes.
> Pre-install deps in validate.dockerfile, relax some upper bounds.

- .travis.yml
- Cabal/Cabal.cabal
- cabal-install/Distribution/Client/CmdBuild.hs
- cabal-install/Distribution/Client/CmdSdist.hs
- cabal-install/Distribution/Client/GZipUtils.hs
- cabal-install/cabal-install.cabal
- cabal-install/cabal-install.cabal.pp
- cabal-install/tests/UnitTests/Distribution/Client/GZipUtils.hs
- cabal-testsuite/Test/Cabal/Monad.hs
- cabal-testsuite/Test/Cabal/OutputNormalizer.hs
- cabal-testsuite/cabal-testsuite.cabal
- travis-install.sh
- travis-script.sh
- travis/binaries/.travis.yml
Based on #6388, resolves #6280
> Travis ghc 8.8

- Cabal/Distribution/Simple/Program/Db.hs
- cabal-testsuite/cabal-testsuite.cabal
- travis/binaries/.travis.yml
And forward port correct since annotation for `needProgram`
> regex-tdfa-1.3.1.0

- Cabal/Cabal.cabal
- Cabal/ChangeLog.md
- Cabal/Distribution/Compat/Lens.hs
- Cabal/Distribution/FieldGrammar/Parsec.hs
- Cabal/Distribution/Fields/Field.hs
- Cabal/Distribution/Simple/GHC.hs
- Cabal/Distribution/Simple/GHCJS.hs
- Cabal/Distribution/Simple/Program/GHC.hs
- Cabal/Distribution/Types/BuildInfo.hs
- Cabal/Distribution/Types/LocalBuildInfo.hs
- Cabal/Distribution/Types/PkgconfigVersionRange.hs
- Cabal/Distribution/Utils/NubList.hs
- Cabal/Language/Haskell/Extension.hs
- Cabal/doc/developing-packages.rst
- Cabal/doc/nix-local-build.rst
- Cabal/tests/UnitTests.hs
- Cabal/tests/UnitTests/Distribution/Simple/Program/GHC.hs
- cabal-install/Distribution/Client/FetchUtils.hs
- cabal-install/Distribution/Client/ProjectBuilding.hs
- cabal-install/Distribution/Client/ProjectConfig/Legacy.hs
- cabal-install/Distribution/Client/ProjectPlanning.hs
- cabal-install/Distribution/Solver/Modular/IndexConversion.hs
- cabal-install/changelog
- cabal-install/tests/IntegrationTests2.hs
- cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs
- cabal-testsuite/PackageTests/AutogenModules/SrcDist/setup.test.hs
- cabal-testsuite/PackageTests/Regression/T5309/memoized-tcm/costMatrixWrapper.h
Fixes https://github.com/haskell/cabal/issues/6218
- https://github.com/haskell/cabal/pull/6379
- https://github.com/haskell/cabal/pull/6380
- https://github.com/haskell/cabal/pull/6385
- https://github.com/haskell/cabal/pull/6372
- https://github.com/haskell/cabal/pull/6217
> Backport 3.0 batch 4

- cabal-install/Distribution/Client/InstallPlan.hs
Related issues are https://github.com/haskell/cabal/issues/6437
and https://github.com/reflex-frp/reflex/issues/375
> Improve few internalErrors in InstallPlan

- cabal-install/Distribution/Solver/Modular/Builder.hs
- cabal-install/Distribution/Solver/Modular/ConflictSet.hs
- cabal-install/Distribution/Solver/Modular/Dependency.hs
- cabal-install/Distribution/Solver/Modular/Explore.hs
- cabal-install/Distribution/Solver/Modular/Linking.hs
- cabal-install/Distribution/Solver/Modular/Preference.hs
- cabal-install/Distribution/Solver/Modular/Validate.hs
See https://github.com/haskell/cabal/pull/5918#issuecomment-575936172.
> Backport cleanup commits from PR #5918 to 3.2

- cabal-install/Distribution/Solver/Modular/Package.hs
- cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs
- cabal-testsuite/PackageTests/Backpack/Includes2/setup-external.cabal.out
- cabal-testsuite/Test/Cabal/OutputNormalizer.hs
> Show full ABI hash for installed packages in solver log (fixes #5892).

- Cabal/Distribution/Simple/Utils.hs
- Cabal/doc/installing-packages.rst
- Cabal/doc/nix-local-build.rst
- cabal-install/Distribution/Client/CmdExec.hs
- cabal-install/Distribution/Solver/Modular/Package.hs
- cabal-install/cabal-install.cabal.pp
- cabal-install/tests/IntegrationTests2.hs
- cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs
- cabal-testsuite/PackageTests/Backpack/Includes2/setup-external.cabal.out
- cabal-testsuite/Test/Cabal/OutputNormalizer.hs
- https://github.com/haskell/cabal/pull/6464
- https://github.com/haskell/cabal/pull/6473
- https://github.com/haskell/cabal/pull/6498
- https://github.com/haskell/cabal/pull/6499
- https://github.com/haskell/cabal/pull/6501
+ a commit from #6502 helping with bootstrap (lukko is cabal-version: 2.2)
> Backport batch 4 3.2

- cabal-install/Distribution/Client/IndexUtils.hs
> IndexUtils: Add missing whitespace in warning

- Cabal/Distribution/Simple/Build/Macros/Z.hs
- boot/cabal_macros.template.h
- cabal-testsuite/PackageTests/CabalMacros/Mdl.hs
- cabal-testsuite/PackageTests/CabalMacros/my.cabal
- cabal-testsuite/PackageTests/CabalMacros/setup.cabal.out
- cabal-testsuite/PackageTests/CabalMacros/setup.out
- cabal-testsuite/PackageTests/CabalMacros/setup.test.hs
> Correct casing of CURRENT_PACKAGE_KEY

- Cabal/Distribution/Types/PkgconfigVersion.hs
Related to https://github.com/haskell/cabal/issues/6539
> Add doctests for Parsec PkgconfigVersion

- Cabal/doc/README.md
> Correct a typo in README [ci skip]

- Cabal/Cabal-quickcheck/src/Test/QuickCheck/Instances/Cabal.hs
- Cabal/Distribution/Types/Flag.hs
- Cabal/tests/UnitTests/Distribution/Described.hs
- cabal-install/Distribution/Client/BuildReports/Types.hs
- cabal-install/Distribution/Client/Types.hs
- cabal-install/tests/UnitTests/Distribution/Client/ArbitraryInstances.hs
- cabal-install/tests/UnitTests/Distribution/Client/Described.hs
- cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
Move few Arbitrary instances to more correct places,
add tests
> Add Described FlagName and RepoName instances

- cabal-install/Distribution/Client/Config.hs
See #6210 for more information.
---
> Default to 'NoReports' for remote build reporting.

- cabal-install/Distribution/Client/SrcDist.hs
- cabal-install/main/Main.hs
- changelog.d/issue-6635
> Remove v1-sdist

- Cabal/tests/ParserTests/regressions/shake.cabal
- Cabal/tests/ParserTests/regressions/shake.expr
- Cabal/tests/ParserTests/regressions/shake.format
> Add hs-source-dirs: NL . test-case

- Cabal/Cabal-quickcheck/src/Test/QuickCheck/Instances/Cabal.hs
- Cabal/Distribution/Types/PackageVersionConstraint.hs
- Cabal/tests/UnitTests/Distribution/Described.hs
- cabal-install/tests/UnitTests/Distribution/Client/ArbitraryInstances.hs
First step towards https://github.com/haskell/cabal/issues/5570
> Add Described PackageVersionConstraint

- cabal-install/Distribution/Client/CmdRun.hs
- weeder.dhall
> Add more weeder roots

- .github/workflows/quick-jobs.yml
- boot/ci-quick-jobs.template.yml
https://github.com/actions/virtual-environments/blob/releases/ubuntu18/20200604/images/linux/Ubuntu1804-README.md
> Fix Quick jobs CI

- Cabal/Distribution/Compat/Internal/TempFile.hs
> WINIO: Add support for WINIO to Cabal.

- .stylish-haskell.yaml
I have used this one "successfully" in new modules for three
or so years.
> Add stylish-haskell config.

- cabal-install/Distribution/Client/CmdFreeze.hs
- cabal-install/Distribution/Client/IndexUtils.hs
- cabal-install/Distribution/Client/IndexUtils/ActiveRepos.hs
- cabal-install/tests/UnitTests/Distribution/Client/DescribedInstances.hs
- changelog.d/active-repositories
> Add active-repositories merge strategy: skip

- Cabal/doc/getting-started.rst
> Fix minor typo

- Cabal/Cabal.cabal
- Cabal/Distribution/Compat/Process.hs
- Cabal/Distribution/Simple/GHC.hs
- Cabal/Distribution/Simple/Program/GHC.hs
- Cabal/tests/UnitTests/Distribution/Simple/Program/GHC.hs
- cabal-dev-scripts/cabal-dev-scripts.cabal
- cabal-install/Distribution/Client/CmdSdist.hs
- cabal-install/Distribution/Client/ProjectPlanning.hs
- cabal-testsuite/cabal-testsuite.cabal
Backports:
- https://github.com/haskell/cabal/pull/7004
- https://github.com/haskell/cabal/pull/7023
- https://github.com/haskell/cabal/pull/7024
- https://github.com/haskell/cabal/pull/7025
> Backport to 3.4 20200902

- doc/getting-started.rst
(cherry picked from commit 7dfe60e98179c320e2a1715d4452f5f7554474ec)
---
Forward-port of #7014
> Fix minor typo (Forward-port of #7014)

- Cabal/Cabal-QuickCheck/src/Test/QuickCheck/Instances/Cabal.hs
- Cabal/Cabal.cabal
- Cabal/Distribution/Simple/SrcDist.hs
- Cabal/Distribution/Types/VersionRange/Internal.hs
- cabal-install/Distribution/Client/CmdRepl.hs
- cabal-testsuite/PackageTests/SDist/T7028/cabal.out
- cabal-testsuite/PackageTests/SDist/T7028/cabal.project
- cabal-testsuite/PackageTests/SDist/T7028/cabal.test.hs
- cabal-testsuite/PackageTests/SDist/T7028/pkg/Main.hs
- cabal-testsuite/PackageTests/SDist/T7028/pkg/data.txt
- cabal-testsuite/PackageTests/SDist/T7028/pkg/t7028.cabal
- https://github.com/haskell/cabal/issues/7040
- https://github.com/haskell/cabal/pull/7041
- https://github.com/haskell/cabal/pull/7037
- https://github.com/haskell/cabal/pull/7032
- https://github.com/haskell/cabal/pull/7030
> Backport to 3.4 20200908

- Cabal/Distribution/Utils/Structured.hs
- cabal-install/Distribution/Client/Dependency.hs
- release.py
- https://github.com/haskell/cabal/pull/7049
- https://github.com/haskell/cabal/pull/7050
> Backport to 3.4 20200910

- cabal-install/Distribution/Client/BuildReports/Storage.hs
- cabal-install/Distribution/Client/CmdUpdate.hs
- cabal-install/Distribution/Client/IndexUtils.hs
- cabal-install/Distribution/Client/JobControl.hs
- cabal-install/Distribution/Client/Types/Repo.hs
- Backports https://github.com/haskell/cabal/pull/7062 (https://github.com/haskell/cabal/issues/7061)
> Backport to 3.4 20200913

- Cabal/Cabal.cabal
- cabal-install/Distribution/Client/ProjectOrchestration.hs
Backports
- https://github.com/haskell/cabal/pull/7078
- https://github.com/haskell/cabal/pull/7085
> Backport to 3.4 20200924

- doc/nix-local-build-overview.rst
Update the documentation accordingly
> Nix style local builds have become the default

- cabal-install/src/Distribution/Client/ProjectPlanning.hs
- cabal-testsuite/PackageTests/ExtraPackages/Foo.hs
- cabal-testsuite/PackageTests/ExtraPackages/cabal.out
- cabal-testsuite/PackageTests/ExtraPackages/cabal.project
- cabal-testsuite/PackageTests/ExtraPackages/cabal.test.hs
- cabal-testsuite/PackageTests/ExtraPackages/my.cabal
- cabal-testsuite/PackageTests/ExtraPackages/repo/some-exe-0.0.1.0/Main.hs
- cabal-testsuite/PackageTests/ExtraPackages/repo/some-exe-0.0.1.0/some-exe.cabal
- cabal-testsuite/src/Test/Cabal/OutputNormalizer.hs
- changelog.d/pr-6972
> Pr 6972 extra packages

- Cabal/Distribution/PackageDescription/Parsec.hs
- Cabal/doc/nix-local-build-overview.rst
- Cabal/tests/ParserTests/regressions/mixin-1.cabal
- Cabal/tests/ParserTests/regressions/mixin-1.expr
- Cabal/tests/ParserTests/regressions/mixin-1.format
- cabal-install/Distribution/Client/CmdBench.hs
- cabal-install/Distribution/Client/CmdBuild.hs
- cabal-install/Distribution/Client/CmdConfigure.hs
- cabal-install/Distribution/Client/CmdFreeze.hs
- cabal-install/Distribution/Client/CmdHaddock.hs
- cabal-install/Distribution/Client/CmdInstall.hs
- cabal-install/Distribution/Client/CmdRepl.hs
- cabal-install/Distribution/Client/CmdRun.hs
- cabal-install/Distribution/Client/CmdTest.hs
- cabal-install/Distribution/Client/CmdUpdate.hs
- cabal-install/Distribution/Client/ProjectOrchestration.hs
Backports
- https://github.com/haskell/cabal/pull/7093
- https://github.com/haskell/cabal/pull/7097
- https://github.com/haskell/cabal/pull/7098
> Backport to 3.4 20201011

- Makefile
- cabal-install/cabal-install-solver/src/Distribution/Solver/Modular/Assignment.hs
- cabal-install/cabal-install-solver/src/Distribution/Solver/Modular/Configured.hs
- cabal-install/cabal-install-solver/src/Distribution/Solver/Types/OptionalStanza.hs
- cabal-install/cabal-install-solver/src/Distribution/Solver/Types/SolverPackage.hs
- cabal-install/cabal-install.cabal.dev
- cabal-install/cabal-install.cabal.zinza
- cabal-install/src/Distribution/Client/Configure.hs
- cabal-install/src/Distribution/Client/Install.hs
- cabal-install/src/Distribution/Client/ProjectOrchestration.hs
- cabal-install/src/Distribution/Client/ProjectPlanning.hs
- cabal-install/src/Distribution/Client/ProjectPlanning/Types.hs
- cabal-install/src/Distribution/Client/SourceFiles.hs
- cabal-install/src/Distribution/Client/Types/ConfiguredPackage.hs
- cabal-install/tests/UnitTests.hs
- cabal-install/tests/UnitTests/Distribution/Client/ArbitraryInstances.hs
- cabal-install/tests/UnitTests/Distribution/Solver/Types/OptionalStanza.hs
> Add OptionalStanzaSet and OptionalStanzaMap

- doc/cabal-project.rst
Fixes #7155
---
* [*] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [*] Any changes that could be relevant to users have been recorded in the changelog (add file to `changelog.d` directory).
* [*] The documentation has been updated, if necessary.
> Document required +/- before flags in package sections.

- .github/workflows/artifacts.yml
- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/quick-jobs.yml
- .github/workflows/windows.yml
- boot/ci-artifacts.template.yml
- boot/ci-linux.template.yml
- boot/ci-macos.template.yml
- boot/ci-quick-jobs.template.yml
- boot/ci-windows.template.yml
- cabal-testsuite/PackageTests/ForeignLibs/UseLib.c
- cabal-testsuite/PackageTests/ForeignLibs/csrc/MyForeignLibWrapper.c
- cabal-testsuite/PackageTests/ForeignLibs/my-foreign-lib.cabal
- cabal-testsuite/PackageTests/ForeignLibs/setup.test.hs
> Use environment paths in GitHub CI

- .github/workflows/quick-jobs.yml
- Cabal/Distribution/Fields/Lexer.hs
- Cabal/Distribution/Simple/Build/PathsModule.hs
- boot/ci-quick-jobs.template.yml
- cabal-testsuite/PackageTests/PathsModule/MissingSafeHaskellMode/my.cabal
- cabal-testsuite/PackageTests/PathsModule/MissingSafeHaskellMode/setup.cabal.out
- cabal-testsuite/PackageTests/PathsModule/MissingSafeHaskellMode/setup.out
- cabal-testsuite/PackageTests/PathsModule/MissingSafeHaskellMode/setup.test.hs
backports:
- https://github.com/haskell/cabal/pull/7219
- https://github.com/haskell/cabal/pull/7205
> Backport to 3.4 20201230

- cabal-install/cabal-install.cabal
- cabal-install/src/Distribution/Client/HashValue.hs
- cabal-install/src/Distribution/Client/HttpUtils.hs
- cabal-testsuite/cabal-testsuite.cabal
---
--> https://build.opensuse.org/project/show/devel:languages:haskell:ghc-8.10.x
> Allow base16-bytestring 1.0 and newer

- Cabal/src/Distribution/Simple/Command.hs
- changelog.d/spelling-suggestion
Patch from Francesco Ariis
---
> Suggest command on spelling mistakes

- cabal-install/src/Distribution/Client/Config.hs
- cabal-install/src/Distribution/Client/ProjectBuilding.hs
- cabal-install/src/Distribution/Client/ProjectConfig.hs
- cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs
- cabal-install/src/Distribution/Client/ProjectConfig/Types.hs
- cabal-install/src/Distribution/Client/Setup.hs
- cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
- changelog.d/only-download
- doc/cabal-project.rst
> --only-download flag

- doc/cabal-package.rst
This adds documentation for #7353.
> Documented the interaction between Backpack and Template Haskell.

- Cabal/src/Distribution/Simple/GHC.hs
- changelog.d/pr-7252
- Add a changelog entry
- Carry out a small renaming suggested by @phadej to make the implementation a bit clearer
---
*  [x] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
> Follow-up to #7252

- cabal-install/cabal-install.cabal
- cabal-install/src/Distribution/Client/CmdInstall.hs
- cabal-install/src/Distribution/Client/CmdListBin.hs
- cabal-install/src/Distribution/Client/CmdRepl.hs
- cabal-install/src/Distribution/Client/CmdRun.hs
- cabal-install/src/Distribution/Client/ProjectOrchestration.hs
- cabal-install/src/Distribution/Client/ProjectPlanning.hs
- cabal-install/tests/UnitTests.hs
- cabal-install/tests/UnitTests/Distribution/Client/ProjectPlanning.hs
Innocent refactoring with the intention to learn the code-base a bit better
> Replace List with NonEmpty in TargetsMap

- cabal-install/src/Distribution/Client/CmdOutdated.hs
- cabal-testsuite/PackageTests/Outdated/cabal.project.missing.freeze
- cabal-testsuite/PackageTests/Outdated/outdated_freeze.out
- cabal-testsuite/PackageTests/Outdated/outdated_freeze.test.hs
- changelog.d/pr-7440
> Print error message if no freeze file can be found

- Cabal/ChangeLog.md
- changelog.d/spelling-suggestion
- release-notes/Cabal-3.6.0.0.md
> Add Cabal-3.6.0.0 release notes

- Cabal/ChangeLog.md
- changelog.d/spelling-suggestion
- release-notes/Cabal-3.6.0.0.md
> Add Changelog for Cabal-3.6.0.0

- .github/mergify.yml
> add merge-me label for mergify-driven merge strats

- cabal-install-solver/src/Distribution/Solver/Modular/WeightedPSQ.hs
> add traverseWithKey to cabal-install-solver

- cabal-install/src/Distribution/Client/Init/FlagExtractors.hs
- cabal-install/src/Distribution/Client/Init/Interactive/Command.hs
- cabal-install/src/Distribution/Client/Init/Simple.hs
- cabal-install/src/Distribution/Client/Init/Utils.hs
- cabal-install/tests/UnitTests/Distribution/Client/Init/Simple.hs
- cabal-install/tests/UnitTests/Distribution/Client/Init/Utils.hs
> add baseDep to simple project generation

- cabal-install/changelog
- release-notes/cabal-install-3.6.0.0.md
> add changelog for cabal-install-3.6.0.0

- changelog.d/pr-7402
- doc/cabal-commands.rst
> Change mentions of "overwrite" to "backup"

- cabal-install/src/Distribution/Client/Dependency.hs
- cabal-install/src/Distribution/Client/Fetch.hs
- cabal-install/src/Distribution/Client/FetchUtils.hs
- cabal-install/src/Distribution/Client/Freeze.hs
- cabal-install/src/Distribution/Client/HttpUtils.hs
- cabal-install/src/Distribution/Client/ProjectBuilding.hs
- cabal-install/src/Distribution/Client/ProjectPlanning.hs
- cabal-install/src/Distribution/Client/RebuildMonad.hs
- cabal-install/src/Distribution/Client/Reconfigure.hs
- cabal-install/src/Distribution/Client/SolverInstallPlan.hs
- cabal-install/src/Distribution/Client/SourceFiles.hs
- cabal-install/src/Distribution/Client/Targets.hs
- cabal-install/src/Distribution/Client/Upload.hs
- cabal-install/src/Distribution/Client/Utils.hs
- cabal-install/src/Distribution/Client/VCS.hs
- cabal-install/src/Distribution/Client/World.hs
---
Similar to https://github.com/haskell/cabal/pull/7492
Only tested by building `cabal-install` and CI.
> more type annotations

- doc/installing-packages.rst
Clarify that it is not necessary to provide `secure` or `root-keys` for the default repository.
---
> [ci skip] Update installing-packages.rst

- .gitlab-ci.yml
- .gitlab/ci.sh
- .gitlab/common.sh
> add gitlab ci integration to cabal

- changelog.d/pr-7402
- doc/cabal-commands.rst
This PR will close #7590, this time proper.
> Fix mentions of overwrite and backup flags for v2-configure

- Cabal/src/Distribution/Compat/CopyFile.hs
- cabal-install/src/Distribution/Client/Compat/FilePerms.hs
- changelog.d/pr-7572
> Add file perm bits to current mode rather than overriding

- .gitlab-ci.yml
Yeah... CI here https://gitlab.haskell.org/maerwald/cabal/-/jobs/807336
> Add i386 build

- Cabal/README.md
A minor docs-only change.
I will merge after a single review.
> Update Cabal/README.md (see #7391)

- doc/cabal-commands.rst
- doc/setup-commands.rst
> docs: move flags not supported by Setup.hs, fixes #7859

- changelog.d/pr-7873
> Changelog for #7873

- Cabal/src/Distribution/Types/BuildInfo.hs
examples also properly sequenced
> extraBundledLibs (fix typos in comments)

- cabal-install/src/Distribution/Client/ParseUtils.hs
- changelog.d/pr-7903
> Silencing warning about unrecognised world-file field

- Makefile
- README.md
> Remove leftover mentions of artifacts.yml

- cabal-testsuite/PackageTests/Init/init.out
- cabal-testsuite/PackageTests/Init/init.test.hs
> Testing cabal init for buildable output

- changelog.d/issue-7714
Changelog for #7714 / #7726: cabal man
> Changelog for #7714 / #7726: cabal man

- CONTRIBUTING.md
- README.md
> backticks (markdown files)

- changelog.d/issue-7279
Progress towards #8040
---
* [😄] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
> Add changelog for #7279 and #8006

- cabal-install/src/Distribution/Client/TargetSelector.hs
- cabal-install/tests/IntegrationTests2.hs
- cabal-testsuite/PackageTests/NewBuild/CmdRun/MultiplePackages/cabal.out
Resolves https://github.com/haskell/cabal/issues/7968
> don't suggest 'all' target for run action

- Cabal-syntax/src/Distribution/Backpack.hs
https://github.com/haskell/cabal/pull/7882 resubmitted
Cabal-syntax/src/Distribution/Backpack.hs
> Backpack (comment fixes)

- cabal-install/src/Distribution/Client/CmdConfigure.hs
> Update stale docs for configure

- cabal-install/src/Distribution/Client/Setup.hs
> add explanation for what -w does in init context

- CONTRIBUTING.md
> Mention file-format-changelog.rst in CONTRIBUTING

- .github/workflows/changelogs.yml
The changelog-d tool was rejecting those entries.
Maybe we should add a changelog-d call in ci...
> Fix typos in changelog entries

- Cabal/ChangeLog.md
- Cabal/README.md
- cabal-install-solver/cabal-install-solver.cabal
Let's remember to forward-port this, with changes, to master, once the dust settles.
> All kinds of last touches before the 3.8.0 pre-release

- doc/cabal-package.rst
- doc/intro.rst
Doc changes by Vilius Panevėžys <vp@mikrovisata.net> sent to cabal-devel@haskell.org.
---
> Update repo URL in doc example and Drop outdated Hackage vs CPAN package counts

- Cabal-syntax/src/Language/Haskell/Extension.hs
- Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
- changelog.d/pr-8170
> Update the list of known GHC extensions to match GHC 9.2

- Cabal-syntax/src/Language/Haskell/Extension.hs
> Simplify Language extension documentation

- Cabal/src/Distribution/PackageDescription/Check.hs
This should fix #7088. All credits go to the author of #7104.
---
> Drop >= in suggestions to cabal-version (rebase #7104)

- doc/cabal-project.rst
- doc/conf.py
- doc/requirements.in
- doc/requirements.txt
> Add strikethrough text support

- changelog.d/pr-8223
> Add changelog for future proofing liftA2 export from Prelude

- changelog.d/pr-8237
- doc/cabal-commands.rst
> Document `cabal check` in the user guide

- cabal-testsuite/PackageTests/NewBuild/CmdBench/OptionsFlag/OptionsFlag.hs
- cabal-testsuite/PackageTests/NewBuild/CmdTest/OptionsFlag/OptionsFlag.hs
> Improve --test/benchmark-options test accuracy

- cabal-install/src/Distribution/Client/Init/Interactive/Command.hs
> Fix cabal-version 3.4 description in cabal init

- release-notes/Cabal-3.8.1.0.md
- release-notes/cabal-install-3.8.1.0.md
> Fixup headers of 3.8.1.0 release notes

- release-notes/Cabal-3.8.1.0.md
- release-notes/cabal-install-3.8.1.0.md
Somewhat opinionated!
@Mergifyio backport 3.8
> Clean up 3.8.1.0 changelogs

- .github/workflows/whitespace.yml
Capitalize on bug fix: https://hackage.haskell.org/package/fix-whitespace-0.0.10/changelog
> CI: bump fix-whitespace to 0.0.10

- .github/mergify.yml
> [ mergify ] better implementation of 2 day delay

- .github/workflows/validate.yml
- validate.sh
> Make validate.sh show the output of cabal-plan

- changelog.d/pr-8162
- Fixed changelog entry for haddock-package command
---
> Fixed changelog entry for haddock-package command

- .gitlab-ci.yml
It's a half of solution for #8376 (see https://github.com/haskell/cabal/issues/8376#issuecomment-1214450441). It's tested to at least [succeed on GitLab](https://gitlab.haskell.org/ulysses4ever/cabal/-/pipelines/55722).
---
> gitlab CI generates deb11 images

- Cabal-syntax/src/Language/Haskell/Extension.hs
- cabal-testsuite/PackageTests/Regression/T8507/Foo.hs
- cabal-testsuite/PackageTests/Regression/T8507/cabal.out
- cabal-testsuite/PackageTests/Regression/T8507/cabal.project
- cabal-testsuite/PackageTests/Regression/T8507/cabal.test.hs
- cabal-testsuite/PackageTests/Regression/T8507/pkg.cabal
- fix-whitespace.yaml
Closes #8507 
---
Now with regression test.
> Use munch1 to parse Language

- doc/config.rst
A minor documentation improvement (I hope).
> Elaborate on XDG directories in users guide.

- doc/nix-local-build.rst
> Fix typo in import feature documentation

- .github/workflows/changelogs.yml
- CONTRIBUTING.md
I'll just leave it on github for now :shrug: 
---
> Switch to fgaz's changelog-d fork

- doc/file-format-changelog.rst
> Add example on how refer private libs in build-depends

- cabal-testsuite/PackageTests/LinkerOptions/NonignoredConfigs/cabal.test.hs
> Fix typo in cabal.test.hs

- CONTRIBUTING.md
Based on a discussion in https://github.com/haskell/cabal/pull/8669 and my local tests.
> Fix build instructions in CONTRIBUTING.md for people with old cabal

- Cabal/src/Distribution/Simple/Command.hs
Not sure that's better. I think, the docs are still not helpful if you are confused. At least, explains parameters.
> Improve docs for 'option' and 'reqArg'

- Cabal-syntax/Cabal-syntax.cabal
- Cabal-syntax/LICENSE
- Cabal-tests/Cabal-tests.cabal
- Cabal-tests/LICENSE
- Cabal/Cabal.cabal
- Cabal/LICENSE
- LICENSE
- cabal-benchmarks/LICENSE
- cabal-benchmarks/cabal-benchmarks.cabal
- cabal-dev-scripts/LICENSE
- cabal-install-solver/LICENSE
- cabal-install-solver/cabal-install-solver.cabal
- cabal-install/LICENSE
- cabal-install/cabal-install.cabal
- cabal-testsuite/LICENSE
- cabal-testsuite/cabal-testsuite.cabal
- doc/conf.py
- solver-benchmarks/LICENSE
- solver-benchmarks/solver-benchmarks.cabal
> Update © year to 2023

- .gitlab-ci.yml
- .gitlab/brew.sh
Use a specific release instead of HEAD.
Darwin job: https://gitlab.haskell.org/haskell/cabal/-/jobs/1399049
---
> Stabilize use of brew in GitLab CI

- .github/workflows/validate.yml
I felt lucky and wanted to check if the problem still exists... Waiting for CI. Draft for now.
> CI: ubuntu 20.04 -> latest

- .readthedocs.yml
- doc/README.md
- doc/requirements.txt
Cf. https://github.com/haskell/cabal/security/dependabot/3
---
> docs: dependabot security suggestion

- CONTRIBUTING.md
Fourmolu < 0.12 results in spurious suggestions, see #8976.
---
* N/A ~Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).~
* ~Include [manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) if your PR relates to cabal-install.~
N/A ~Bonus points for added automated tests!~
> Specify Fourmolu version

- CONTRIBUTING.md
In particular, mention that Markdown is allowed.
---
* [N/A] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [N/A] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [N/A] Include [manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) if your PR relates to cabal-install.
> CONTRIBUTING.md: more description of changelogs

- CONTRIBUTING.md
> Update CONTRIBUTING.md to be clearer about the location of the QA notes

- doc/cabal-package.rst
> Add documentation for default-language field

- Cabal-syntax/src/Distribution/System.hs
- Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
- Cabal/src/Distribution/Simple/PreProcess.hs
- changelog.d/pr-9062
> Add support for the 64-bit RISC-V architecture

- cabal-install/cabal-install.cabal
- cabal-testsuite/PackageTests/NewUpdate/UpdateIndexState/update-index-state.out
- cabal-testsuite/PackageTests/NewUpdate/UpdateIndexState/update-index-state.test.hs
Fixes #9054
Closes #9059
N/A
---
> cabal-install: update resolv to 0.2.0.2

- cabal-testsuite/PackageTests/MultiRepl/EnabledSucc/cabal.test.hs
---
* [N/A] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [N/A] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [N/A] Include [manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) if your PR relates to cabal-install.
> workaround for #9103: skip test failing on Windows

- .github/workflows/format.yml
- .github/workflows/lint.yml
- .hlint.yaml
HLS often alerts me to one HLint suggestion or another in this project. This adds a default configuration that silences these and shows how many of each suggestion we have so that when we want to tackle these we can.
> Add HLint configuraton.

- doc/cabal-commands.rst
Have the section on `cabal help` match this command's output and link to sections in the command intro.
---
> Bring the command help up to date

- .github/mergify.yml
> Mergify: rebase as Mikolaj (fix #8462)

- .hlint.yaml
- Cabal/src/Distribution/Compat/ResponseFile.hs
- Cabal/src/Distribution/Compat/Time.hs
- Cabal/src/Distribution/ReadE.hs
- Cabal/src/Distribution/Simple/Build.hs
- Cabal/src/Distribution/Simple/Haddock.hs
- Cabal/src/Distribution/Utils/Json.hs
- cabal-install-solver/src/Distribution/Solver/Modular/Linking.hs
- cabal-install-solver/src/Distribution/Solver/Modular/Message.hs
- cabal-install/src/Distribution/Client/CmdRun.hs
- cabal-install/src/Distribution/Client/GenBounds.hs
- cabal-install/src/Distribution/Client/Install.hs
- cabal-install/src/Distribution/Client/List.hs
- cabal-install/src/Distribution/Client/ProjectPlanOutput.hs
- cabal-install/src/Distribution/Client/ProjectPlanning.hs
- cabal-install/src/Distribution/Client/Utils.hs
- generics-sop-lens.hs
> Follow hlint suggestion: move brackets to avoid $

- cabal-install/src/Distribution/Client/HttpUtils.hs
> Use case insensitive match on ETag headers

- cabal-install/src/Distribution/Client/List.hs
- cabal-install/src/Distribution/Client/ProjectPlanOutput.hs
Somehow, Fourmolu became unhappy on `master`. This PR should fix it.
> Fix fourmolu

- changelog.d/issue-9113
As requested here: https://github.com/haskell/cabal/pull/9116#issuecomment-1646802064
See also #9131.
> Add changelog for #9113

- Cabal/src/Distribution/Simple/Program/Builtin.hs
The key is "ld command can create merge objects" and has a value of "YES" (the default) or "NO" (if the linker is `lld`).
---
> Check if ldProgram can create merge objects

- Cabal/Cabal.cabal
- cabal-install-solver/cabal-install-solver.cabal
- cabal-install/cabal-install.cabal
> Allow containers-0.7

- Cabal/src/Distribution/Lex.hs
- Cabal/src/Distribution/Simple.hs
- Cabal/src/Distribution/Simple/Flag.hs
- Cabal/src/Distribution/Utils/IOData.hs
- cabal-install/src/Distribution/Client/Main.hs
See commit message.
I'll also drop down to 10-20 comments per 2 weeks, to reduce the need for others' review.
> Add 9 and revise 6 comments.

- release-notes/Cabal-3.10.2.1.md
> Create Cabal-3.10.2.1 release notes

- README.md
Bold and italic do not mix.
---
> Fix italic in README.md

- solver-benchmarks/HackageBenchmark.hs
hackage-benchmark uses the environment variable CABAL_CONFIG to specify the location of the config file. cabal started requiring the config file to exist in that case in 6942e7e8da2579ce35f4d1a5634f2bb287dfd147, so this commit runs "cabal user-config init".
---
> Solver Hackage benchmark: Explicitly initialize cabal config files

- cabal-dev-scripts/cabal-dev-scripts.cabal
- cabal-install-solver/cabal-install-solver.cabal
- cabal-install/cabal-install.cabal
- cabal-install/tests/UnitTests/Distribution/Client/ArbitraryInstances.hs
- cabal-testsuite/cabal-testsuite.cabal
> [cabal-3.8] bump bounds for ghc-9.4

- .github/workflows/validate.yml
> Add solver Hackage benchmarks to GitHub Actions (fixes #9495)

- Cabal/Cabal.cabal
> Cabal: Allow Win32-2.14

- cabal-testsuite/PackageTests/LinkerOptions/.gitignore
> Ignore test T7339 output, libhello.so

- Cabal-syntax/Cabal-syntax.cabal
- Cabal-syntax/LICENSE
- Cabal-tests/Cabal-tests.cabal
- Cabal-tests/LICENSE
- Cabal/Cabal.cabal
- Cabal/LICENSE
- LICENSE
- cabal-benchmarks/LICENSE
- cabal-benchmarks/cabal-benchmarks.cabal
- cabal-dev-scripts/LICENSE
- cabal-install-solver/LICENSE
- cabal-install-solver/cabal-install-solver.cabal
- cabal-install/LICENSE
- cabal-install/cabal-install.cabal
- cabal-testsuite/LICENSE
- cabal-testsuite/cabal-testsuite.cabal
- doc/conf.py
- solver-benchmarks/LICENSE
- solver-benchmarks/solver-benchmarks.cabal
> update copyright for 2024

- cabal.project.release
- cabal.project.validate
cf: https://github.com/haskell/cabal/issues/9819
> Pin index-state in both release and validate project files

- cabal-install/cabal-install.cabal
> cabal-install needs Cabal 3.10.3

- Makefile
> Fix --project-file option for boostrap

- .gitignore
> Ignore testdb/intree generated files

- cabal-install/src/Distribution/Client/ProjectPlanning.hs
> Update setupMinCabalVersionConstraint for GHC 9.10

- Cabal/src/Distribution/Simple/GHC.hs
> Support GHC 9.12

- Cabal-syntax/ChangeLog.md
- Cabal/ChangeLog.md
- Cabal/README.md
A number of minor fixes for changelog/readmes.
---
> Fix changelog/readme

- doc/cabal-commands.rst
> Add docs for list-bin support of scripts

- Cabal/src/Distribution/PackageDescription/Check/Target.hs
> Add comment clarifying disabling check for scripts

- Cabal-syntax/ChangeLog.md
- Cabal/ChangeLog.md
- cabal-install-solver/ChangeLog.md
- cabal-install/changelog
Our release checklist is missing these files.
> missed the two changelog pointers

- cabal-install/changelog
See https://github.com/haskell/cabal/pull/9696#discussion_r1651689945 ff.
> Remove a stray line from cabal-install changelog

- .github/workflows/quick-jobs.yml
- cabal-testsuite/cabal-testsuite.cabal
> cabal-testsuite.cabal: bump custom-setup bounds on Cabal(-syntax) after the release

- project-cabal/ghc-latest.config
> ghc-latest.config: rere is up to date with GHC 9.10 now

- .github/workflows/changelogs.yml
- changelog.d/config
Release: https://codeberg.org/fgaz/changelog-d/releases/tag/v1.0.1
Adds a `packages` check and helps a bit with #10263
---
> Update changelog-d to 1.0.1

- .gitignore
> Ignore VSCodium work directory

- Cabal-syntax/ChangeLog.md
- cabal-install-solver/ChangeLog.md
- cabal-install/changelog
- release-notes/Cabal-3.14.0.0.md
Miscellaneous changelog fixes for 3.14.
---
> Add miscellaneous changelog fixes

- Cabal-syntax/src/Language/Haskell/Extension.hs
- Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
- changelog.d/pr-10339
- editors/vim/syntax/cabal.vim
> Add OrPatterns extensions

- Cabal-syntax/src/Distribution/SPDX/LicenseExceptionId.hs
- Cabal-syntax/src/Distribution/SPDX/LicenseId.hs
- Cabal-syntax/src/Distribution/SPDX/LicenseListVersion.hs
- Makefile
- cabal-dev-scripts/src/GenSPDX.hs
- cabal-dev-scripts/src/GenSPDXExc.hs
- cabal-dev-scripts/src/GenUtils.hs
- changelog.d/pr-10341
- doc/file-format-changelog.rst
- license-list-data/exceptions-3.25.json
- license-list-data/licenses-3.25.json
- templates/SPDX.LicenseExceptionId.template.hs
- templates/SPDX.LicenseId.template.hs
> Update SPDX license list to version 3.25

- cabal-testsuite/src/Test/Cabal/Monad.hs
> Fix `--accept` flag in `cabal-testsuite`

- README.md
> README: add Cabal-hooks to the list of packages

- buildinfo-reference-generator/buildinfo-reference-generator.cabal
- cabal-install-solver/cabal-install-solver.cabal
- cabal-install/cabal-install.cabal
- cabal-testsuite/cabal-testsuite.cabal
----
This needs to be backported to the 3.14 branch.
> Bump base bound to 4.21 for GHC 9.12

- doc/how-to-source-packages.rst
> Typo respositories

- Cabal-syntax/src/Distribution/Types/MissingDependencyReason.hs
Minor, typo depency.
👉️ **Template B: This PR does not modify behaviour or interface**
* [👍] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
> Typo depency

- doc/cabal-package-description-file.rst
Small fix in the documentation.
> Fix typo in constraint example

- .github/workflows/validate.yml
See https://github.com/haskell/cabal/actions/runs/12415183173/job/34666846889
> The release cleanup action requires a token

- .github/workflows/check-sdist.yml
For 3.14 branch which ships with it.
> add ghc 9.12.1 to sdist check list

- cabal.release.project
> cabal.release.project: pick newer `unix` that fixes important bugs on i386 and arm

- .github/workflows/validate.yml
Currently [failing](https://github.com/haskell/cabal/actions/runs/12448218422/job/34753867653) due to https://github.com/liudonghua123/delete-release-action/issues/1
Petition to fast-track (again)...
---
> CI: prerelease: fixup cleanup (again)

- Cabal-syntax/Cabal-syntax.cabal
- Cabal/Cabal.cabal
- cabal-install-solver/cabal-install-solver.cabal
- cabal-install/cabal-install.cabal
> bump version numbers for 3.14.1.1

- Cabal-hooks/Cabal-hooks.cabal
> Fix casing of extra-source-files in Cabal-hooks

- doc/conf.py
See https://github.com/haskell/cabal/issues/10754#issuecomment-2670780733
> docs/conf.py: bump project development version

- doc/setup-commands.rst
> Fix typo: looses -> loses

- Cabal-syntax/src/Distribution/Utils/Path.hs
> exporting FileLike and PathLike

- Cabal-hooks/Cabal-hooks.cabal
- cabal-install/cabal-install.cabal
> Backport #10895: Preflight checks

- Cabal/src/Distribution/Simple/Configure.hs
> Allow building foreign libraries on FreeBSD

- bootstrap/bootstrap.py
Currently, the bootstrap script does not support parallelizing the build process - it runs in a single thread, which is quite slow. However, this can be improved by passing the -j parameter to the Setup executable
I'm not sure how naturally this is handled in the commit, but not using a global variable and passing option through all functions seemed like a worse approach to me
BTW - it will be good to see same functionality in hadrian bootstrap script
> bootstrap/bootstrap.py: Added support for multithreaded builds

- cabal-install/cabal-install.cabal
> cabal-install.cabal: allow hashable-1.5

- Cabal/Makefile
- doc/conf.py
Found while un-bumping for 3.16.
---
> missed version bumps

- Cabal/src/Distribution/Simple/Configure.hs
- changelog.d/pr-11042
Fixes #11034 
Alternative to https://github.com/haskell/cabal/pull/11040
> Allow relocatable builds on FreeBSD

- scripts/release/create-release-metadata-for-ghcup.sh
- scripts/release/download-cabal-install-release-binaries.sh
Fix typos in release script comments.
[Is 'useable' preferred in certain regions, or just an alternate spelling of 'usable'?](https://english.stackexchange.com/questions/69709/is-useable-preferred-in-certain-regions-or-just-an-alternate-spelling-of-usa)
---
> Fix typos in release script comments

- MAINTAINERS.md
> Add Matthew Pickering to maintainers list
