haskell/cabal

Cabal/Distribution/PackageDescription/PrettyPrint.hs
Cabal/tests/ParserHackageTests.hs

Foreign lib names not parsed by readp

---

Cabal/Distribution/Parsec/Parser.hs
Cabal/Distribution/Simple/Compiler.hs
Cabal/Distribution/Simple/GHC/Internal.hs
Cabal/Distribution/Simple/PreProcess.hs
Cabal/Distribution/Simple/Program/GHC.hs
Cabal/doc/developing-packages.rst
cabal-install/Distribution/Client/DistDirLayout.hs
cabal-install/Distribution/Client/PackageHash.hs
cabal-install/Distribution/Client/Types.hs
cabal-install/Distribution/Client/Win32SelfUpgrade.hs

[ci skip]
No tests were added.

Fix cases where "it's" was used as a possessive

---

Cabal/Cabal.cabal
Cabal/Distribution/PackageDescription/FieldGrammar.hs
Cabal/Distribution/PackageDescription/Parsec.hs
Cabal/Distribution/Parsec/Newtypes.hs
Cabal/changelog
Cabal/doc/developing-packages.rst
Cabal/tests/ParserTests.hs
Cabal/tests/ParserTests/errors/common1.cabal
Cabal/tests/ParserTests/errors/common1.errors
Cabal/tests/ParserTests/errors/common2.cabal
Cabal/tests/ParserTests/errors/common2.errors
Cabal/tests/ParserTests/errors/common3.cabal
Cabal/tests/ParserTests/errors/common3.errors
Cabal/tests/ParserTests/regressions/Octree-0.5.format
Cabal/tests/ParserTests/regressions/common.cabal
Cabal/tests/ParserTests/regressions/common.format
Cabal/tests/ParserTests/regressions/common2.cabal
Cabal/tests/ParserTests/regressions/common2.format
Cabal/tests/ParserTests/regressions/elif.format
Cabal/tests/ParserTests/regressions/encoding-0.8.cabal
Cabal/tests/ParserTests/regressions/encoding-0.8.format
cabal-dev-scripts/src/GenExtraSourceFiles.hs

RFC: Common stanzas

---

Cabal/Distribution/PackageDescription.hs
Cabal/Distribution/PackageDescription/Check.hs
Cabal/Distribution/PackageDescription/FieldGrammar.hs
Cabal/Distribution/PackageDescription/Parse.hs
Cabal/Distribution/Types/PackageDescription.hs
Cabal/Distribution/Types/PackageDescription/Lens.hs
Cabal/changelog
Cabal/doc/developing-packages.rst
cabal-install/Distribution/Client/Dependency.hs
cabal-install/Distribution/Client/ProjectBuilding.hs
cabal-install/Distribution/Client/ProjectPlanning.hs
cabal-install/Distribution/Client/SetupWrapper.hs
cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL.hs
cabal-testsuite/PackageTests/CustomPlain/plain.cabal
cabal-testsuite/PackageTests/CustomPlain/setup.cabal.out
cabal-testsuite/PackageTests/CustomPlain/setup.out
cabal-testsuite/PackageTests/SimpleDefault/M.hs
cabal-testsuite/PackageTests/SimpleDefault/Setup.hs
cabal-testsuite/PackageTests/SimpleDefault/cabal.project
cabal-testsuite/PackageTests/SimpleDefault/cabal.test.hs
cabal-testsuite/PackageTests/SimpleDefault/my.cabal
cabal-testsuite/Test/Cabal/Prelude.hs

A personal pet-peeve of mine when writing `.cabal` files from scratch is forgetting about declaring the `build-type`, which historically will then be inferred to be `Custom` which is almost always *not* what is desired. Instead, a better default is `Simple` as that represents the most basic and recommended `build-type`. Morever, starting with `cabal-version:1.24`, we have a redundant signal in the `.cabal` file to statically imply a custom `build-type`, namely the `custom-setup` stanza.
To this end, this PR finally removes this papercut by improving the defaulting to use the following simple rules:
- When `cabal-version` is set to `2.1` or higher,   the default is `Simple` unless a `custom-setup` stanza exists, in which case the inferred default is `Custom`.
- For lower `cabal-version`s …

Improve `build-type` defaulting

---

Cabal/Distribution/Simple/Compiler.hs
Cabal/Distribution/Simple/GHC/Internal.hs
Cabal/Distribution/Simple/HaskellSuite.hs
Cabal/Distribution/Simple/JHC.hs
Cabal/Distribution/Simple/LHC.hs
Cabal/Distribution/Simple/Program/GHC.hs
Cabal/Distribution/Simple/UHC.hs
Cabal/changelog

Not every supported extension for a compiler has a corresponding flag.
for example NondecreasingIndentation is enabled by default on GHC 7.0.4,
hence it is considered a supported extension but not an accepted flag.
To resolve this, wrap Flags in Maybe, and follow through the resulting
refactoring.
Fixes #4443
This was tested by running the repro example in the issue (#4443)
I intend to add a test to the suite, but I'd like some feedback on this much first.

Fix NondecreasingIndentation filtering

---

cabal-install/Distribution/Solver/Modular/Builder.hs
cabal-install/Distribution/Solver/Modular/Dependency.hs
cabal-install/Distribution/Solver/Modular/IndexConversion.hs
cabal-install/Distribution/Solver/Modular/Solver.hs
cabal-install/Distribution/Solver/Modular/Validate.hs
cabal-install/Distribution/Solver/Modular/Version.hs
cabal-install/tests/UnitTests/Distribution/Solver/Modular/MemoryUsage.hs
cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs

This commit changes DependencyReason's list fields to maps and sets. Duplicate
flags were possible when a flag appeared multiple times in nested conditionals
or a flag controlled a "Buildable: False" field. The duplicate flag could show
up in log messages:
Before:
```
[__5] trying: json-rpc-client:+demo
[__6] trying: process-1.6.1.0/installed-1.6... (dependency of json-rpc-client +demo +demo)
```
After:
```
[__5] trying: json-rpc-client:+demo
[__6] trying: process-1.6.1.0/installed-1.6... (dependency of json-rpc-client +demo)
```

Solver: Deduplicate flags and stanzas in DependencyReason.

---

cabal-install/Distribution/Client/Compat/Directory.hs
cabal-install/Distribution/Client/Update.hs
cabal-install/cabal-install.cabal

See https://github.com/haskell/cabal/pull/4950#issuecomment-352753882 for context.

Unbreak the build with directory < 1.2.3.0.

---

cabal-install/Distribution/Client/Fetch.hs
cabal-install/Distribution/Client/Setup.hs

This is a work in progress to address #4723, that I'm putting up here to get some feedback because I'm not sure what other wiring needs to be done for new options to commands.
I've tested this with the various combinations of `--enable-tests` / `--enable-benchmarks` with `cabal-fetch --dry-run (other options here) ad` and it seems to do what it should.

Adds --enable-tests and --enable-benchmarks to 'cabal fetch'.

---

cabal-install/Distribution/Client/Init.hs

`cabal init` currently generates trailing whitespaces; this patch
simply adds a final post-processing step filtering out any such trailing
whitespace.
Below is an example (the red markers represent the annoying end-of-line trailing whitespace); with this patch, all those red areas are gone.
----

Kill trailing whitespaces in `.cabal` file emitted by `cabal init`

---

Cabal/Cabal.cabal
Cabal/Distribution/Parsec/Class.hs
Cabal/Distribution/SPDX.hs
Cabal/Distribution/SPDX/LicenseExceptionId.hs
Cabal/Distribution/SPDX/LicenseId.hs
Cabal/Distribution/SPDX/LicenseReference.hs
Cabal/Distribution/Utils/Generic.hs
Cabal/tests/UnitTests.hs
Cabal/tests/UnitTests/Distribution/SPDX.hs
Makefile
boot/SPDX.LicenseExceptionId.template.hs
boot/SPDX.LicenseId.template.hs
cabal-dev-scripts/cabal-dev-scripts.cabal
cabal-dev-scripts/src/GenSPDX.hs
cabal-dev-scripts/src/GenSPDXExc.hs
cabal.project.meta
license-list-data/exceptions.json
license-list-data/licenses.json
travis-meta.sh

[WIP] Distribution.SPDX.LicenseId generation

---

Cabal/Cabal.cabal
Cabal/Distribution/Parsec/Class.hs
Cabal/Distribution/Parsec/Common.hs
Cabal/tests/ParserTests.hs
Cabal/tests/ParserTests/regressions/encoding-0.8.cabal
Cabal/tests/ParserTests/regressions/encoding-0.8.format
Cabal/tests/ParserTests/warnings/doubledash.cabal

Resolves #2681
Cabal files don't have trailing line comments. In many fields they
simply cause parse errors, but e.g. in extra-source-files
virtually everything is accepted. As there is simple
work around if people actually want double-dash, let's warn
about bare one.

Warn if -- token is found. Don't warn if it's "--".

---

Cabal/Cabal.cabal
Cabal/Distribution/Compat/DList.hs
Cabal/Distribution/Parsec/Class.hs
Cabal/Distribution/Types/VersionRange.hs
Cabal/tests/ParserTests.hs
Cabal/tests/ParserTests/errors/range-ge-wild.cabal
Cabal/tests/ParserTests/errors/range-ge-wild.errors

- No more `try`
- It recognises wild-card version after all operators,
but fails with more descriptive warning after non-==
Fixes #989
---

Issue 989 range op wild

---

Cabal/Distribution/Compat/CopyFile.hs
cabal-install/changelog

Tested by trying to compile cabal itself on a long path.
Should fix partially #3972, #4914, #4515. The reason why partial is because any operation that hits the GHC I/O manager will destroy device path support. Because the GHC I/O manager is using non-native posix like APIs which are mapped to the old Win32 APIs that are bound by MAX_PATH.
This patch works because it avoids touching the I/O manager for doing the file copy and instead does a direct copy using the Win32 API. The Windows APIs do not have the same limitations as the posix ones and so do not require the file to be on the same drive before issuing a copy/move. So this should be much faster …

Add support on Windows for copying to long paths.

---

Cabal/Distribution/InstalledPackageInfo.hs
Cabal/tests/ParserTests.hs

@hvr I chose to go more BC way, I'm afraid we will out of run to test ghc-pkg changes properly.
`showFullInstalledPackageInfo` could be removed for next Cabal / GHC-8.6 when we have better time.
---
showInstalledPackageInfo uses full variant, but with pkgroot set to
Nothing. This way we field descriptions have roundtrip property (wo it's
simpler to proceed with reworking the parsing using parsec framework).
We introduce new name, so no (coordinated) changes to ghc-pkg are needed.

Add showFullInstalledPackageInfo

---

cabal-install/Distribution/Client/CmdBench.hs
cabal-install/Distribution/Client/CmdBuild.hs
cabal-install/Distribution/Client/CmdErrorMessages.hs
cabal-install/Distribution/Client/CmdHaddock.hs
cabal-install/Distribution/Client/CmdInstall.hs
cabal-install/Distribution/Client/CmdRepl.hs
cabal-install/Distribution/Client/CmdRun.hs
cabal-install/Distribution/Client/CmdTest.hs
cabal-install/Distribution/Client/ProjectOrchestration.hs
cabal-install/Distribution/Client/TargetSelector.hs
cabal-install/tests/IntegrationTests2.hs
cabal-testsuite/PackageTests/NewBuild/CmdRun/ExeAndLib/cabal.out

Much improved support for named packages in the target selector syntax and resolution. Instead of just supporting syntax of a single unadorned package name, all the existing syntax that allow package names are extended to support named packages.
This includes packages from the `extra-packages` but also indirect deps and packages from hackage. The resolution for `extra-packages` and indirect deps should just work, while currently packages outside the project are reported as an error (but we're in a good position now to resolve to packages from hackage if we want).
So this should be a better basis for the target handling for the new install code, since any command should now be able to refer to packages outside of the project (or at least we're a short step from tha now).
This passes the …

Target package names

---

Cabal/Distribution/Backpack/ConfiguredComponent.hs
Cabal/Distribution/Types/AnnotatedId.hs
cabal-install/Distribution/Client/ProjectOrchestration.hs
cabal-install/Distribution/Client/ProjectPlanning.hs
cabal-testsuite/PackageTests/NewBuild/T3827/cabal.out
cabal-testsuite/PackageTests/Regression/T4986/cabal.out
cabal-testsuite/PackageTests/Regression/T4986/cabal.project
cabal-testsuite/PackageTests/Regression/T4986/cabal.test.hs
cabal-testsuite/PackageTests/Regression/T4986/client/Hello.hs
cabal-testsuite/PackageTests/Regression/T4986/client/client.cabal
cabal-testsuite/PackageTests/Regression/T4986/happy/Main.hs
cabal-testsuite/PackageTests/Regression/T4986/happy/happy.cabal

Fix #4986, and extra refactoring

---

Cabal/Distribution/Simple/Build.hs
Cabal/Distribution/Simple/Utils.hs
cabal-install/Distribution/Client/SetupWrapper.hs

Restore BC for rewriteFile

---

Cabal/Distribution/PackageDescription/Check.hs
Cabal/Distribution/Types/BuildType.hs
Cabal/changelog
cabal-install/Distribution/Client/SetupWrapper.hs
cabal-install/main/Main.hs

This is a follow-up to #4958 which opened up the opportunity to do
this make-illegal-states-unrepresentable refactoring as well.

Remove `UnknownBuildType` from `BuildType`

---

cabal-install/Distribution/Client/Config.hs
cabal-install/Distribution/Client/GlobalFlags.hs
cabal-install/Distribution/Client/HttpUtils.hs
cabal-install/Distribution/Client/ProjectConfig.hs
cabal-install/Distribution/Client/ProjectConfig/Legacy.hs
cabal-install/Distribution/Client/ProjectConfig/Types.hs
cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs

This should resolve half of #4995 -- as usual, two lines of straightforward changes, and 20x as many lines to make sure the data gets threaded to where it needs to go. In this case I've added an extra prog path field to the GlobalFlags object so it can thread through to be used in looking up binaries for the http transport. It is automatically derived from the setting in the config file.

Pass extra dirs to http transport

---

Cabal/doc/cabaldomain.py

At least it's not just me who is confused by the naming scheme.  `project.cabal` seems much more logical to me as it's a `cabal` file. However, cabal expects the file to be called `cabal.project`, so let's make the documentation less confusing.

project.cabal -> cabal.project

---

cabal-install/Distribution/Client/Config.hs
cabal-install/Distribution/Client/Setup.hs
cabal-install/changelog
cabal-install/main/Main.hs
cabal-install/tests/UnitTests/Distribution/Client/UserConfig.hs

Should resolve https://github.com/haskell/cabal/issues/4901
This adds an additional option for `user-config`, as `--append=` or `-a`. This can be used multiple times, each time adding a new line to the delta on `user-config` files for `init` `update` or `diff`. This lets tools like the platform installer pass in, e.g. msys directories for `extra-prog-path` and `extra-lib-dirs` etc.
Tested on some example files, and new-test passes.

append option for user-config command

---

Cabal/tests/UnitTests/Distribution/Version.hs

Fix bogus prop_foldVersionRange': strip parens

---

Cabal/Cabal.cabal
Cabal/Distribution/FieldGrammar/Parsec.hs
Cabal/Distribution/Parsec/Common.hs
Cabal/tests/ParserTests.hs
Cabal/tests/ParserTests/regressions/common2.cabal
Cabal/tests/ParserTests/regressions/common2.expr
Cabal/tests/ParserTests/regressions/common2.format
Cabal/tests/ParserTests/regressions/encoding-0.8.cabal
Cabal/tests/ParserTests/regressions/encoding-0.8.format
Cabal/tests/ParserTests/warnings/multiplesingular.cabal
cabal-testsuite/PackageTests/Regression/T4270/T4270.cabal
cabal-testsuite/PackageTests/TestSuiteTests/LibV09/LibV09.cabal

Resolves https://github.com/haskell/cabal/issues/366
---

Warn on multiply specified singular fields

---

Cabal/doc/nix-local-build.rst
cabal-install/Distribution/Client/CmdRun.hs
cabal-install/changelog
cabal-install/tests/IntegrationTests2.hs
cabal-install/tests/IntegrationTests2/targets/lib-only/p.cabal
cabal-testsuite/PackageTests/NewBuild/CmdRun/MultipleExes/cabal.out
cabal-testsuite/PackageTests/NewBuild/CmdRun/MultiplePackages/cabal.out

This is especially useful for passing arguments to a single test suite
ping @merijn this is already usable
Closes #4684

Allow new-run to run tests and benchmarks too

---

Cabal/Cabal.cabal
Cabal/tests/Instances/TreeDiff.hs
Cabal/tests/Instances/TreeDiff/Language.hs
Cabal/tests/Instances/TreeDiff/SPDX.hs
Cabal/tests/Instances/TreeDiff/Version.hs
Cabal/tests/ParserHackageTests.hs
Cabal/tests/ParserTests.hs

I saw GHC-7.10.3 randomly failing when compiling TreeDiffInstances. hopefully this help, or we can split the file further.
---

Split TreeDiffInstances to lower memory pressure

---

.travis.yml
stack.yaml
travis-install.sh
travis-stack.sh

Tested by running `stack build --test` in the repo.  Travis changes not yet tested, we'll see once it checks this PR.  Previously it would immediately yield the following error:
```
Error: While constructing the build plan, the following exceptions were encountered:
In the dependencies for Cabal-2.1.0.0:
QuickCheck-2.10.1 from stack configuration does not match >=2.11.3 && <2.12 (latest matching
version is 2.11.3)
tree-diff must match >=0.0.1 && <0.1, but the stack configuration has no specified version
(latest matching version is 0.0.1)
needed since Cabal is a build target.
Some different approaches to resolving this:
* Consider trying 'stack solver', …
```

Fix stack configuration and improve travis stack setup

---

Cabal/Distribution/Make.hs
Cabal/Distribution/Simple.hs
Cabal/Distribution/Simple/Configure.hs
Cabal/Distribution/Simple/InstallDirs.hs
Cabal/Distribution/Simple/Setup.hs
cabal-install/Distribution/Client/Config.hs
cabal-install/Distribution/Client/ProjectConfig/Legacy.hs
cabal-install/Distribution/Client/Setup.hs

This change adds the ability to pass `--prefix=\${pkgroot}`. It is on purpose undocumented, as it should be only used with absolute care.
Fixes #4872

Allow ${pkgroot} prefix.

---

cabal-install/Distribution/Solver/Modular/Builder.hs
cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs

The solver already detected cycles involving more than one package, but it
allowed dependencies between components within a package.  This commit treats a
dependency between a package's setup script and library as a cycle in order to
allow the solver to backtrack and try to break the cycle.  A more thorough
solution would involve tracking all dependencies between components, as in #4087.
This commit also fixes the internal error in issue #4980.
/cc @kosmikus @hvr

Solver: Detect cycles between packages and their setup scripts (fixes #4161).

---

cabal-install/cabal-install.cabal
cabal-install/tests/UnitTests/Distribution/Solver/Modular/QuickCheck.hs
cabal-install/tests/UnitTests/Distribution/Solver/Modular/QuickCheck/Utils.hs

This could help with debugging test cases that run out of memory or timeout in
CI, such as the failure in #5054.

Print the seed before running each solver-quickcheck test.

---

cabal-testsuite/PackageTests/Configure/setup.test.hs

Skip PackageTests/Configure/setup.test.hs if autoreconf is not in $PATH

---

Cabal/Distribution/Simple/Configure.hs
cabal-testsuite/PackageTests/Regression/T4720/bug/Main.hs
cabal-testsuite/PackageTests/Regression/T4720/bug/bug.cabal
cabal-testsuite/PackageTests/Regression/T4720/bug/cbits/bug.c
cabal-testsuite/PackageTests/Regression/T4720/cabal.out
cabal-testsuite/PackageTests/Regression/T4720/cabal.project
cabal-testsuite/PackageTests/Regression/T4720/cabal.test.hs

Only to libraries and executables before this.
Fixes #4720

--extra-*-dirs were not being passed to all components

---

Cabal/Distribution/Compiler.hs

I have code that depends on the NFData instance (previously defined locally as an orphan), and I verified that code still works properly.

CompilerId: add NFData instance (based on genericRnf)

---

Cabal/Distribution/Simple/Build/PathsModule.hs
cabal-install/changelog
cabal-testsuite/PackageTests/PathsModule/Library/my.cabal

Fixes https://github.com/commercialhaskell/stack/issues/3789
I couldn't get the tests working for me, so instead I interacted with `cabal-testsuite/PacakgeTests/AutogenModules/SrcDist` manually.  Running `cabal install` there yielded
```
Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
update' to download it.
In order, the following will be installed:
AutogenModules-0.1 (reinstall)
Warning: Note that reinstalls are always dangerous. Continuing anyway...
Configuring AutogenModules-0.1...
Building AutogenModules-0.1...
Failed to install AutogenModules-0.1
Build log ( …
```

Make Paths_ autogen module work with default-extensions (stack 3789)

---

Cabal/Cabal.cabal
Cabal/Distribution/PackageDescription/Parsec.hs
Cabal/tests/ParserTests.hs
Cabal/tests/ParserTests/errors/issue-5055-2.cabal
Cabal/tests/ParserTests/errors/issue-5055-2.errors
Cabal/tests/ParserTests/errors/issue-5055.cabal
Cabal/tests/ParserTests/errors/issue-5055.errors
Cabal/tests/ParserTests/regressions/issue-5055.cabal
Cabal/tests/ParserTests/regressions/issue-5055.expr
Cabal/tests/ParserTests/regressions/issue-5055.format

Make Cabal-2.2 behave like Cabal-2.0 related to #5055

---

Cabal/Distribution/PackageDescription/Check.hs
Cabal/Distribution/PackageDescription/FieldGrammar.hs
Cabal/Distribution/Types/ExecutableScope.hs
Cabal/tests/ParserTests/regressions/issue-5055.expr
Cabal/tests/ParserTests/regressions/issue-5055.format
Cabal/tests/ParserTests/regressions/shake.expr
Cabal/tests/ParserTests/regressions/shake.format
Cabal/tests/ParserTests/regressions/wl-pprint-indef.expr
Cabal/tests/ParserTests/regressions/wl-pprint-indef.format
Makefile

Fixes #5083
Related to #5003
Note: `buildable: ` field has `All` semantics. `scope: ` has
`AnyPrivate` semantics. Both might be surprising, but are "logical".
https://hackage.haskell.org/package/Cabal-2.0.1.1/docs/src/Distribution.PackageDescription.Parse.html#line-248

Remove 'ExecutableScopeUnknown'.

---

Cabal/Cabal.cabal
Cabal/Distribution/PackageDescription/Check.hs
Cabal/Distribution/Simple/Build/PathsModule.hs
Cabal/Distribution/Types/PackageDescription.hs
Cabal/changelog
Cabal/tests/CheckTests.hs
Cabal/tests/ParserTests/regressions/extensions-paths-5054.cabal
Cabal/tests/ParserTests/regressions/extensions-paths-5054.check
Makefile
cabal-testsuite/PackageTests/PathsModule/Library/my.cabal

A variant of #5087, which does check on `cabal-version: 2.1`
Let's see if appveyor is more happy with this one.

Issue 5086b

---

Cabal/changelog

Forgot to do this in #4383 
[skip ci]

Update Cabal/changelog with buildDepends removal

---

Cabal/Language/Haskell/Extension.hs
Cabal/changelog

GHC 8.6 will support this extension.
No test has been done locally.

WIP: Add BlockArguments to KnownExtension

---

Cabal/Distribution/Simple/Setup.hs

When trying to make the "target-package-db" flag hidden in #4892, I unintentionally also
made it unrecognized. This should rectify that and also make the code more readable.

Fix Hidden Args.

---

Cabal/Distribution/SPDX/License.hs
Cabal/Distribution/SPDX/LicenseExpression.hs
Cabal/Distribution/SPDX/LicenseId.hs
boot/SPDX.LicenseId.template.hs

Add licenseIdMigrationMessages. Resolves #5109.

---

cabal-install/Distribution/Client/Dependency.hs
cabal-install/Distribution/Solver/Modular.hs
cabal-install/Distribution/Solver/Modular/Log.hs
cabal-install/Distribution/Solver/Modular/Message.hs
cabal-install/Distribution/Solver/Modular/Preference.hs
cabal-install/Distribution/Solver/Modular/Solver.hs
cabal-install/Distribution/Solver/Modular/Tree.hs
cabal-install/Distribution/Solver/Modular/WeightedPSQ.hs
cabal-install/Distribution/Solver/Types/Variable.hs
cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL/TestCaseUtils.hs
cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs
cabal-testsuite/PackageTests/Backpack/Includes2/setup-external.cabal.out
cabal-testsuite/PackageTests/BuildTargets/UseLocalPackage/use-local-version-of-package.out
cabal-testsuite/PackageTests/BuildTargets/UseLocalPackageForSetup/use-local-package-as-setup-dep.out
cabal-testsuite/PackageTests/ConfigureComponent/Exe/setup.cabal.out
cabal-testsuite/PackageTests/InternalVersions/BuildDependsBad/setup.cabal.out

_________________________________________________________________
This commit changes the way that the solver generates the summarized log that it
displays at normal verbosity.
Previously, the solver saved the full log from the start to the first backjump.
Then it filtered the log using the conflict set from the node where the first
backjump occurred, i.e., it removed all lines from the log that did not relate
to variables in the conflict set.  The solver also printed the final conflict
set at the end of the log.
This approach had several problems:
1. It was possible for the conflicts at the first backjump to be unrelated to
the final conflict set …

 Rerun dependency solver to generate a better error message (issue #4823).

---

Cabal/doc/developing-packages.rst

This is a small doc change that addresses #1847 by just indicating limitations very clearly.

indicate explicitly name req for main-is module

---

cabal-install/Distribution/Client/ProjectConfig/Legacy.hs
cabal-install/changelog

This should help with #4939. `--with-PROG` flags should be applied to every
package.  If we change hsc2hs via `--with-hsc2hs=` or any other program and
similarly `--hsc2hs-options` should also be provided to that program.  Same
holds for `--PROG-options`.  Because we do no inherit the properties from
AllPackages for LocalPackages, we need to have the set of programs and options
in both.

Put command line --with-PROG into AllPackages

---

cabal-install/Distribution/Solver/Modular.hs
cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs

_____________________________________________________________________
After #5012, the solver generated the summarized log by using a goal order that
preferred goals from the final conflict set.  It completely ignored the original
goal order parameter.  This caused a failure in one of the unit tests that set a
goal order and then checked the summarized log, when the solver's goal order
changed for other reasons (See #5012).
This commit combines the two goal orders, with the goal order that prefers goals
from the conflict set taking precedence over the original goal order.
_____________________________________________________________________
This should …

Don't ignore goal order parameter when generating summarized solver log.

---

cabal-install/Distribution/Client/CmdBench.hs
cabal-install/Distribution/Client/CmdBuild.hs
cabal-install/Distribution/Client/CmdConfigure.hs
cabal-install/Distribution/Client/CmdFreeze.hs
cabal-install/Distribution/Client/CmdHaddock.hs
cabal-install/Distribution/Client/CmdInstall.hs
cabal-install/Distribution/Client/CmdRepl.hs
cabal-install/Distribution/Client/CmdRun.hs
cabal-install/Distribution/Client/CmdTest.hs
cabal-install/Distribution/Client/CmdUpdate.hs
cabal-install/Distribution/Client/Setup.hs

This is not finished yet; this is supposed to address issues like #4737 or #5139
/cc @alexbiehl
----
Regressions:
```
$ cabal new-haddock all
fromFlag NoFlag. Use fromFlagOrDefault
error, called at ./Distribution/Simple/Setup.hs:172:21 in Cabal-2.1.0.0-inplace:Distribution.Simple.Setup
fromFlag, called at ./Distribution/Client/CmdHaddock.hs:156:32 in cabal-install-2.1.0.0-inplace:Distribution.Client.CmdHaddock
```

Replace flag-defaulting hack by proper solution

---

cabal-install/Distribution/Client/ProjectConfig/Legacy.hs

I think this was an oversight from https://github.com/haskell/cabal/commit/32ff1cac28206ae320c2cb39dce2d07d74991799 when we introduced `projectConfigAllPackages`. 
Without this patch `convertLegacyGlobalConfig` considers global configuration (e.g. `~/.cabal/config`) only for packages that are local to the project. This patch puts global configuration into `projectConfigAllPackages` to make sure it is applied to all packages whether they are project local or not.

Apply global config to all packages

---

cabal-install/Distribution/Client/ProjectBuilding.hs
cabal-install/Distribution/Client/ProjectConfig/Legacy.hs
cabal-install/Distribution/Client/ProjectPlanning.hs

Adds the ability to generate haddock documentation for non-inplace
package builds.
In other words this allows
- `$ cabal new-build --enable-documentation`
- `$ echo "documentation: true" >> cabal.project && cabal new-build`
- `$ echo "documentation: true" >> ~/.cabal/config && cabal new-build`
And it will generate (and install) haddock documentation for any
package.
(This works best with https://github.com/haskell/cabal/pull/5142 as otherwise global configuration cannot be applied to non-local packages)

Make --enable-documentation work

---

Cabal/Language/Haskell/Extension.hs
Cabal/changelog

GHC 8.6 will support this extension.
This extension has already landed in ghc master branch.
(https://phabricator.haskell.org/D4235)
No testing performed.

Extension: Add NumericUnderscores

---

solver-benchmarks/tests/HackageBenchmarkTest.hs

tasty-hunit deprecated the Assertable typeclass in version 0.10, so this commit
updates the solver-benchmarks unit tests.

Use 'assertBool' instead of 'assert' to avoid deprecation warning.

---

Cabal/Distribution/Compiler.hs
Cabal/changelog

fix haskell/hackage-server#674
----
tested with `cabal build`

Add Eta compiler

---

cabal-install/bootstrap.sh

Now that Cabal depends on parsec bootstrap.sh should compile its `Setup.hs` with the bootstrapping libraries' package-db in scope, otherwise users will be forced to manually install the correct version of parsec etc. to even get the bootstrap script to work!

bootstrap: Pass SCOPE_OF_INSTALL to ghc when building Setup.hs

---

Cabal/Distribution/Simple/GHC.hs

This finally addresses the long-standing ticket #415
NB: This is against the 2.2 branch

Emit warning when an unknown GHC version is encountered

---

cabal-install/Distribution/Client/ProjectPlanning.hs
cabal-testsuite/PackageTests/CustomDep/cabal.test.hs
cabal-testsuite/PackageTests/CustomPlain/cabal.test.hs
cabal-testsuite/PackageTests/Regression/T3932/cabal.test.hs

This addresses #415
This injects lower-bound constraints on Cabal for custom setup
dependencies to prevent the solver from selecting unsupported
configurations.
Previously we already added an absolute lower bound `Cabal >= 1.20`
for nix-local builds, as that's the minimum version we need to be able
to interact with custom Setup.hs scripts. This refines with logic by
restricting that lower bound even more based on GHC version.
This patch augments this with the following rules:
- GHC 8.4+   constrains  `Cabal >= 2.2`
- GHC 8.2    constrains  `Cabal >= 2.0`
- GHC 8.0    constrains  `Cabal >= 1.24`
- GHC 7.10   constrains  `Cabal >= 1.22`
- (default   constraint `Cabal >= 1.20`)
This only affects nix-style local builds codepaths.
----

Implement ghc/cabal compatiblity matrix

---

Cabal/Cabal.cabal
cabal-install/bootstrap.sh
cabal-testsuite/cabal-testsuite.cabal

the versions are bundled with GHC-8.4.1, no need to support older.
some tool to make regexps in `bootstrap.sh` would be great, so I leave them as they are for now. (FWIW I have a library in cooking which can be used for that)
---

Bump parsec and text lower-bounds

---

cabal-install/Distribution/Client/ProjectPlanning.hs
cabal-install/tests/IntegrationTests2.hs
cabal-testsuite/PackageTests/CustomDep/cabal.test.hs
cabal-testsuite/PackageTests/CustomPlain/cabal.test.hs
cabal-testsuite/PackageTests/Regression/T3932/cabal.test.hs

This is a backport of #5165 to 2.2

Implement ghc/cabal compatiblity matrix (#415)

---

Cabal/Distribution/Simple/Program/GHC.hs

The patch which introduced support for split-sections, 450d6bc, contained a
cut-and-paste error such that it was controlled by the split-objs flag. Fix
this.
Fixes #5011.

Fix split-sections flag

---

cabal-install/Distribution/Client/Dependency.hs
cabal-install/Distribution/Client/ProjectPlanning.hs
cabal-install/Distribution/Solver/Types/ConstraintSource.hs
cabal-testsuite/PackageTests/Regression/T4154/install-time-with-constraint.out
cabal-testsuite/PackageTests/Regression/T4154/install-time-with-constraint.test.hs
cabal-testsuite/PackageTests/Regression/T4154/time.cabal

See commit comments; this completes the work for addressing #415 
(NB: This PR only touches `cabal-install`)

Last part of addressing #415

---

cabal-install/Distribution/Client/Dependency.hs
cabal-install/Distribution/Client/ProjectPlanning.hs
cabal-install/Distribution/Solver/Types/ConstraintSource.hs
cabal-install/tests/IntegrationTests2.hs
cabal-testsuite/PackageTests/Regression/T4154/install-time-with-constraint.out
cabal-testsuite/PackageTests/Regression/T4154/install-time-with-constraint.test.hs
cabal-testsuite/PackageTests/Regression/T4154/time.cabal

This is a forward-port of #5180 / 7ce486e6553d24877ae3b23868b95d20bf83760a

Last part of addressing #415 (fwd-ported)

---

Cabal/Distribution/Compat/Environment.hs

Fixes #5181, tested with `cabal new-build Cabal.cabal` on `master` and `Cabal-v2.0.1.1` branch with GHC `8.2.2` and `7.6.3`.

Fix base compat files so they work with GHC < 7.8

---

Cabal/Distribution/Simple/Bench.hs
Cabal/Distribution/Simple/Build.hs
Cabal/Distribution/Simple/BuildPaths.hs
Cabal/Distribution/Simple/GHC.hs
Cabal/Distribution/Simple/GHCJS.hs
Cabal/Distribution/Simple/JHC.hs
Cabal/Distribution/Simple/LHC.hs
Cabal/Distribution/Simple/Test/ExeV10.hs
Cabal/Distribution/Simple/Test/LibV09.hs
cabal-install/Distribution/Client/Install.hs
cabal-install/Distribution/Client/Run.hs
cabal-install/Distribution/Client/SetupWrapper.hs
cabal-testsuite/PackageTests/InternalLibraries/Executable/setup-static.test.hs

When building *for* a host, we do *not* want to rely on the *buildOS*, which is in almost all
cross-compilation cases the wrong OS.  The local build info however knows the right OS
if it was able to extract it from the compiler.  This however will only work until the compiler
gains multi-target support. But that's so far out that this patch should be sufficient for the
time being.

cross compile exe extension

---

cabal-install/Distribution/Client/CmdInstall.hs
cabal-install/Distribution/Client/Config.hs
cabal-install/changelog

Now new-install(-nonlocal-exes) should work without issues (if the ~/.cabal/config was generated with this)
Closes #5000 (yay!)
@23Skidoo can we cherry-pick it on 2.2 too?
* Not necessary since those are Cabal/Setup.hs paths

Fix new-install symlink location

---

Cabal/Distribution/PackageDescription/Check.hs
Cabal/Distribution/PackageDescription/Configuration.hs
Cabal/Distribution/Types/BuildInfo/Lens.hs
Cabal/Distribution/Types/CondTree.hs
Cabal/Distribution/Types/GenericPackageDescription.hs
Cabal/Distribution/Types/GenericPackageDescription/Lens.hs
Cabal/Distribution/Types/PackageDescription.hs

Just enough to simplify 'Distribution.PackageDescription.Configuration' for now.
#5100 will rely on this, both for brevity and package-description polymorphism.
CC @kmicklas

Add more lenses for PackageDescription and GenericPackageDescription

---

cabal-install/Distribution/Client/ProjectPlanning.hs
cabal-testsuite/PackageTests/NewBuild/T4288/CustomIssue.hs
cabal-testsuite/PackageTests/NewBuild/T4288/Setup.hs
cabal-testsuite/PackageTests/NewBuild/T4288/T4288.cabal
cabal-testsuite/PackageTests/NewBuild/T4288/cabal.project
cabal-testsuite/PackageTests/NewBuild/T4288/cabal.test.hs
cabal-testsuite/PackageTests/NewBuild/T4288/setup-helper/SetupHelper.hs
cabal-testsuite/PackageTests/NewBuild/T4288/setup-helper/setup-helper.cabal

#5170 cherry-picked onto 2.2.
@23Skidoo Do you think we should apply this to 2.2?  It only affects new-build.

Look for transitive setup dependency on Cabal when choosing Cabal spec version. (2.2)

---

cabal-testsuite/PackageTests/Regression/T4154/install-time-with-constraint.out
cabal-testsuite/PackageTests/Regression/T4154/install-time-with-constraint.test.hs
cabal-testsuite/PackageTests/Regression/T4154/repo/Cabal-99999/Cabal.cabal

This is #5186 cherry-picked onto the 2.2 branch.
____________________________________________________________________
This commit addresses the comments in PR #5183.
(cherry picked from commit 2b197f8e5a6bf15700656090872810c78225effd)

Update regression test for issue #4154 after the fix for issue #415. (2.2)

---

Cabal/Distribution/Simple/GHC.hs
cabal.project.travis

This finally addresses the long-standing ticket #415
(cherry picked from commit 5339b36e7408b022abb7eeff4f8f1c7de54b8e50)

Emit warning when an unknown GHC version is encountered (2.0 backport)

---

appveyor.yml
cabal-install/Distribution/Client/HttpUtils.hs

This fixes the powershell transport protocol. The reason for the breakage is because certain headers like
"Range" are protected in the .NET framework https://msdn.microsoft.com/en-us/library/system.net.httpwebrequest(v=vs.110).aspx which means you can't set them purely as metadata and need to go through the proper getter/setters.

Fix powershell transport

---

cabal-install/Distribution/Solver/Modular.hs
cabal-install/Distribution/Solver/Modular/Explore.hs
cabal-install/Distribution/Solver/Modular/Log.hs
cabal-install/Distribution/Solver/Modular/Message.hs
cabal-install/Distribution/Solver/Modular/Solver.hs
cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL.hs
cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL/TestCaseUtils.hs
cabal-install/tests/UnitTests/Distribution/Solver/Modular/QuickCheck.hs
cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs
cabal-testsuite/PackageTests/BuildTargets/UseLocalPackage/use-local-version-of-package.out
cabal-testsuite/PackageTests/InternalVersions/BuildDependsBad/setup.cabal.out

________________________________________________________________________
This PR enforces the backjump limit when the solver explores the search tree, which could simplify implementing features such as #2860 or #4594.  It also skips processing the log when the log doesn't need to be printed, since the log is no longer needed for enforcing the backjump limit.  The main commits are:
Previously, the solver enforced the backjump limit by counting `Backjump`
messages during log processing.  This commit instead enforces the backjump limit
when the solver explores the search tree.  This change simplifies the log
processing step and allows us to skip creating …

Enforce the backjump limit before creating the solver log. 

---

cabal-install/Distribution/Client/IndexUtils.hs
cabal-install/Distribution/Client/Sandbox/Index.hs

This is anticipated refactoring (since `readCacheStrict` will
be removed anyway once we remove the `cabal sandbox` code) is
motivated by workarounding a GHC 8.4.1 caused regression
(see https://ghc.haskell.org/trac/ghc/ticket/13930 for details)
Addresses #5201

Refactoring removing `data ReadPackageIndexMode`

---

Cabal/Distribution/SPDX.hs

We implement version 3.0, not 2.1.

Fix the SPDX spec version number

---

Cabal/Distribution/Simple/PreProcess.hs
Cabal/Distribution/System.hs

We recognize arm64 as an alias.

add support for the aarch64 architecture

---

Cabal/Distribution/PackageDescription/Check.hs
Cabal/tests/ParserTests/regressions/issue-774.check

Fix warning message for `cabal-version` field (see #5108)

---

cabal-install/Distribution/Client/CmdRun.hs
cabal-install/Distribution/Client/Configure.hs
cabal-install/Distribution/Client/ProjectBuilding.hs
cabal-install/Distribution/Client/ProjectPlanning.hs
cabal-install/Distribution/Client/ProjectPlanning/Types.hs
cabal-install/Distribution/Client/SetupWrapper.hs
cabal-install/Distribution/Client/Utils.hs
cabal-install/changelog
cabal-testsuite/PackageTests/NewBuild/T5164/cabal.project
cabal-testsuite/PackageTests/NewBuild/T5164/cabal.test.hs
cabal-testsuite/PackageTests/NewBuild/T5164/setup-lib/SetupLib.hs
cabal-testsuite/PackageTests/NewBuild/T5164/setup-lib/example.txt
cabal-testsuite/PackageTests/NewBuild/T5164/setup-lib/setup-lib.cabal
cabal-testsuite/PackageTests/NewBuild/T5164/uses-custom-setup/Setup.hs
cabal-testsuite/PackageTests/NewBuild/T5164/uses-custom-setup/UsesCustomSetup.hs
cabal-testsuite/PackageTests/NewBuild/T5164/uses-custom-setup/uses-custom-setup.cabal

This is accomplished by adding a `useExtraEnvOverrides` field to `SetupScriptOptions`, which allows for setting (or unsetting) any environment variables you wish. This is used when invoking a custom `Setup` script executable to set the values of variables like `<component>_datadir` when using `new-build`. (Not doing this before led to #5164).
Along the way, I moved `dataDirsEnvironmentForPlan` into `Distribution.Client.ProjectPlanning.Types` (as that seemed like the most logical place to put it) so that it could be used in `Distribution.Client.ProjectPlanning` as well, where we also need to initialize `useExtraEnvOverrides`.
I attempted to add a test, but I failed miserably at actually running the test suite, so I have no idea if it actually works or not. Fingers crossed.
Please include …

Fix #5164 by overriding environment variables when new-building custom Setups

---

.travis.yml
cabal-install/bootstrap.sh
cabal-install/cabal-install.cabal

Also drop `bytestring-builder` from the bootstrap script, cabal-install no longer supports `bytestring < 0.10.2` anyway.
---

Drop support for network < 2.6

---

Cabal/Distribution/Simple/Haddock.hs
cabal-install/Distribution/Client/Haddock.hs

With this patch Cabal passes the directory to hyperlinked sources for each package, if present. This helps for package cross-references in hyperlinked-sources. 

Haddock: Pass hyperlink source directory with --read-interface

---

.travis.yml
travis-solver-debug-flags.sh

I think https://github.com/haskell/cabal/pull/5235/commits/668825dcbe3e26e73c7b8fad411ceecefab7b97a broke the solver-debug-flags Travis job because `tracetree` hasn't been updated for GHC 8.4.1.  This PR uses GHC 8.2.2 again and also updates the script to use new-build.
____________________________________________________________________

Use GHC 8.2.2 and new-build for solver-debug-flags Travis job

---

.travis.yml

This reverts commit 0e3718c496012a2b476529445c434438d1c6b71c.
tracetree was updated for GHC 8.4.1 in version 0.1.0.2.

Revert "Use GHC 8.2.2 for solver-debug-flags Travis job."

---

Cabal/ChangeLog.md
Cabal/Distribution/Simple.hs
Cabal/Distribution/Simple/Haddock.hs
Cabal/Distribution/Simple/Setup.hs
Cabal/Distribution/Simple/UserHooks.hs
Cabal/doc/nix-local-build.rst
cabal-install/Distribution/Client/Config.hs
cabal-install/Distribution/Client/ProjectBuilding.hs
cabal-install/Distribution/Client/ProjectConfig/Legacy.hs
cabal-install/Distribution/Client/ProjectPlanning.hs
cabal-install/Distribution/Client/ProjectPlanning/Types.hs

Currently settings `documentation: true` enables documentation
generation via haddock for your whole package, including tests and benchmarks.
However, there are additional flags to control generation of
documentation for these "second class" documentation targets, which are
currently not honored at the cabal-install side of things. Namely,
`tests`, `benchmarks`, `executables`, etc. provided under the
`haddock` section in your `$CABAL_HOME/config`.
This patch adds a more sensible approach to documentation generation
via haddock. The new behaviour works like this:
- Setting `documentation: true` or passing
`--enable-documentation` to cabal-install enables documentation
for any component in the build plan honoring the respective
flags for "second class" doc targets from configuration
or CLI. …

Haddock: Generate haddock for components

---

Cabal/Distribution/Simple/Program/Types.hs
cabal-install/Distribution/Client/ProjectPlanning.hs

This piggybacks any filters on Cabal's support for known programs, it allows us to specify a version specific argument filtering function for each program Cabal knows about.
See #4247.

Infrastructure to filter commandline arguments

---

Cabal/Cabal.cabal
cabal-install/cabal-install.cabal

See https://ghc.haskell.org/trac/ghc/ticket/15042.
I ran the `Cabal` test suites against `unix-2.8`, and they all passed.

Bump upper bound on unix to < 2.9

---

Cabal/doc/nix-local-build.rst

The correct link:
https://www.haskell.org/cabal/users-guide/installing-packages.html#cmdoption-setup-configure-constraint
previously was `...configure--constraint` instead of `...configure-constraint`.
---

Fix doc link to --constraint option

---

Cabal/tests/HackageTests.hs

I use a `Monoid` constraint on `v` since I think else it breaks on pre-8.4 compilers where `Semigroup` is not a superclass of `Monoid`. Should fix the trivial test failure that's been bugging me for ages.

Add Semigroup instance to fix CI test failures

---

cabal-install/Distribution/Client/TargetSelector.hs

The pattern guard was clearly meant as a list-comprehension filter,
but on a let-bound pattern, it instead caused a circular loop in which
whether the LHS variables are bound the the RHS values depends on the
values of the LHS variables.
fixes #5081
---
I tested this by running the problematic command from `#5081`. Result before the fix:
$ cabal new-build test:unknown-test-suite
cabal: Internal error in target matching. It should always be possible to find
a syntax that's sufficiently qualified to give an unambiguous match. However
when matching 'test:unknown-test-suite' we found test:unknown-test-suite
(unknown-component) which does not have an unambiguous syntax. The possible
syntax and the targets they match are as follows:
cabal: …

fix infinite loop in D.Client.TargetSelector

---

Cabal/Distribution/Simple/Build/PathsModule.hs

Cabal is causing an abi issue by forcing it's own architecture's calling convention on each module it creates in the `Path_` modules on Windows.
Compiling a 64 bit executable with a 32 bit cabal happens to work because the linker can perform fixups, adding an indirection to to correct the calling convention. However compiling a 32 bit executable from a 64 bit cabal will fail since the linker can't change the callee.
This corrects that by if cpp is enabled to use predefines from the compiler to determine what to do. Unfortunately due to a bug in GHC I have to rely on macro GHC puts out instead of the standard platform macros. So this only works for GHC code.
It has the old method as fallback for if cpp is not supported. Fixes #5254
Tested …

Fix architecture mismatch of the Paths_ modules on Windows

---

cabal-install/Distribution/Client/ProjectConfig.hs
cabal-install/Distribution/Client/ProjectPlanning.hs

- Use (projectConfigConfigFile, distProjectFile "") as key
for config FileMonitor, instead of ().
- Add verbose printing of relevant config file paths.
Fixes #4662 and probably #5225.

Fix cabal project caching bug, Add verbose printing

---

Cabal/Cabal.cabal
appveyor.yml

I'm tempted to make revisions to Cabal-2.2.0.0 and Cabal-2.2.0.1 also (at least the D.C.Newtype module breaks). OTOH `transformers-0.4.0.0` is deprecated, so I have to adjust my tooling anyway (https://github.com/phadej/trustee/issues/4)

Disallow transformers-0.4.0.0

---

Cabal/Cabal.cabal
Cabal/Distribution/Simple/Flag.hs
Cabal/Distribution/Simple/Program/Builtin.hs
Cabal/Distribution/Simple/Program/GHC.hs
Cabal/Distribution/Simple/Setup.hs

Uses the just merged infrastructure to normalise commandline arguments to filter out any GHC flags that don't affect the build products. Currently only filters commandline arguments for GHC >=8.0 && <8.5 as those are the only versions I checked the flags for.
I went through the GHC DynFlags source for all those version to figure out which flags can be filtered and to follow the right format. Anything I wasn't sure about is left alone, some flags I'm still unsure about are documented in #4247.
Also filters out all haddock arguments, as those should never affect GHC build products.

Prototype flag normalisation for GHC 8.0-8.4

---

.travis.yml
cabal-install/tests/IntegrationTests2.hs

This ought to fix the build matrix. I believe the issue is GHC trac
5129, where evaluate is being miscompiled: in cabal-testsuite's
Test.Cabal.Server, in the function readUntilEnd, the 'read' function
is protected by an 'if' to ensure that it doesn't result in the
dreaded 'no parse'. However, some sophisticated putStrLn
debugging has revealed that it is being called in *both* branches, not
just the safe one; this is the worst sort of heisenbug because it
vanished when I put a putStrLn before the evaluate!
Since the evaluate function is fixed in 8.4.2 and bumping to 8.4.2
has a patch for trac 5129, this is as fixed as it can get.
Tested locally, found it …

travis: Move the 8.4.1 builders to 8.4.2.

---

Cabal/Distribution/PackageDescription/Check.hs

It's 'extra-source-files', not 'extra-src-files'.

check: correct an error message to use the real field name.

---

cabal-testsuite/PackageTests/NewBuild/CmdExec/GhcInvocation/cabal.test.hs
cabal-testsuite/Test/Cabal/Monad.hs
cabal-testsuite/cabal-testsuite.cabal

This test was leaving a 'Main' executable behind. Since we don't ever
actually run it, just check that the compilation succeeds, we can send
it straight to /dev/null.

Avoid leaving leftover files in the source tree in tests.

---

appveyor.yml

Previously, --hide-successes caused solver-quickcheck to only print the seed
that was added in 4d83212fbec3f990f3d90801077da05e5133bd99.  This commit removes
--hide-successes so that the test suite prints the test names with the seeds.

Print all test output when running solver-quickcheck on AppVeyor.

---

Cabal/Cabal.cabal
Cabal/tests/UnitTests/Distribution/Simple/Glob.hs

For efficiency reasons, matchDirFileGlob isn't a simple call to
getDirectoryContentsRecursive and then a filter with
fileGlobMatches. So test both that naive approach and the actual
approach to make sure they are both correct.
I only realised this was a problem right after #5284 was merged!
Since this is tests-only, I'll merge once Travis and AppVeyor are green.

globbing: improve test coverage.

---

travis-install.sh
travis-stack.sh

In the log [here](https://travis-ci.org/haskell/cabal/jobs/333032268), stack is giving `InvalidAbsFile` when invoked with `--stack-yaml stack.yaml`.  I believe that this is quite old behavior.  Theory is that despite downloading stack, travis was not actually using the new stack since the PATH wasn't modified.  Instead of modifying the PATH I've gone with the approach of running stack via an absolute path to the install location.
Untested, lets see if it passes travis.

Use downloaded version of stack in travis CI

---

cabal-install/Distribution/Client/Configure.hs
cabal-install/Distribution/Client/Install.hs
cabal-install/Distribution/Client/ProjectBuilding.hs
cabal-install/Distribution/Client/ProjectPlanning.hs
cabal-install/Distribution/Client/Setup.hs
cabal-install/Distribution/Client/SetupWrapper.hs
cabal-install/Distribution/Client/SrcDist.hs
cabal-install/main/Main.hs

Addresses https://github.com/haskell/cabal/issues/5260.
Since f3cacffe5fc412664f6bb49ed42a028efd7a9d8e we pass the components to generate documentation for to `Setup` with `new-haddock`. Older `Cabal`s do not like this as reported by Herbert in #5260. This patch installs an argument filter mechanism just like the one for flag filtering. We now never pass extra arguments to `Setup haddock` for older `Cabal`s.
---

SetupWrapper: Filtering for Setup arguments

---

Cabal/Distribution/Simple/Install.hs
cabal-testsuite/PackageTests/ForeignLibs/my-foreign-lib.cabal
cabal-testsuite/PackageTests/ForeignLibs/src/MyForeignLib/Export.hs

Do not ignore `install-includes stanza in the foreign-library.
And install headers.

Support installing headers in foreign library target.

---

Cabal/Distribution/Simple/PreProcess.hs

Fix some typos in PreProcess.hs

---

Cabal/Distribution/Backpack/ConfiguredComponent.hs

@hsenag pointed out that "dependency on unbuildable library" isn't necessarily obviously related to `buildable: False`, and may be misinterpreted as a more general cause (like e.g. being unbuildable due to version constraints). This PR is a first suggestion to start the bikeshedding round...
----
Previously,
Dependency on unbuildable library from darcs
In the stanza 'test-suite darcs-test'
In the inplace package 'darcs-2.11.0'
With this patch,
Dependency on unbuildable (i.e. 'buildable: False') library from darcs
In the stanza 'test-suite darcs-test'
In the inplace package 'darcs-2.11.0'

Try to make unbuildable error message more obvious

---

Cabal/doc/nix-local-build.rst
cabal-install/Distribution/Client/CmdClean.hs
cabal-install/cabal-install.cabal
cabal-install/changelog
cabal-install/main/Main.hs

I think it needs some clean-up most likely, but by my understanding of what it's supposed to do, it's at least feature complete.
---
Fixes #2957

[WIP!] cabal new-clean

---

Cabal/Distribution/Simple/Build.hs
Cabal/Distribution/Simple/Haddock.hs

`setup haddock` now updates the package index with each internal library it haddocks. This fixes https://github.com/haskell/cabal/issues/4969 
(don't mind the commit from https://github.com/haskell/cabal/pull/5226 here)
/cc @shlevy
---

Haddock: add internal libraries to package index

---

Cabal/doc/developing-packages.rst

I added descriptions for the Backpack-related `signatures:` and `mixins:` fields, which were missing according to issue #4761.
The new entries don't explain Backpack in detail, but give the basic syntax and link to the [GHC Wiki entry](https://ghc.haskell.org/trac/ghc/wiki/Backpack) and to the [GHC user guide](https://downloads.haskell.org/~ghc/master/users-guide/separate_compilation.html#module-signatures) for more information.

Added documentation for Backpack-related fields.

---

Cabal/ChangeLog.md
Cabal/Distribution/Simple/Configure.hs

See https://github.com/NixOS/nixpkgs/issues/41340.
Also see #3974 and #4105.
Haven't tested it yet, will do that tomorrow.
* ~[ ] investigate whether it's actually legitimate that cabal tries to combine the flags from these different sections into one (`ordNub`ed or not) -- maybe there might be flags across the different sections that are mutually exculsive~ filed https://github.com/haskell/cabal/issues/5360 instead

Dedupe more includeDirs and extraLibDirs

---

Cabal/ChangeLog.md
Cabal/Distribution/System.hs

Add powerpc64le to the list of aliases and document in haddock docs.
Tested by building store-core on a PowerPC 64-bit little endian and verified that `arch(PPC64)` in a conditional evaluates to true.

Recognize `powerpc64le` as `PPC64`

---

cabal-install/Distribution/Client/CmdLegacy.hs

We don't need to hard-wrap the message as we originate it, since
that's handled elsewhere.

Correct formatting of the legacy command name warning

---

Cabal/ChangeLog.md
Cabal/Distribution/Simple/Build.hs
Cabal/Distribution/Simple/GHC.hs
Cabal/Distribution/Simple/GHCJS.hs
Cabal/Distribution/Simple/Setup.hs
Cabal/Distribution/Types/GenericPackageDescription.hs
Cabal/doc/nix-local-build.rst
cabal-install/Distribution/Client/CmdRepl.hs
cabal-install/Distribution/Client/PackageHash.hs
cabal-install/Distribution/Client/ProjectBuilding.hs
cabal-install/Distribution/Client/ProjectPlanning.hs
cabal-install/Distribution/Client/ProjectPlanning/Types.hs
cabal-install/changelog

Continuing efforts from #4247, apply similar recompilation avoidance to local packages as well. Need to look into how this interacts with new-haddock.

Applying flag normalisation to local packages.

---

Cabal/Cabal.cabal
Cabal/doc/file-format-changelog.rst
Cabal/doc/index.rst

As suggested in #5401.
[skip ci]
cc @phadej

Add the start of a changelog for the Cabal file format

---

Cabal/Distribution/Simple/Glob.hs
Cabal/Distribution/Simple/Haddock.hs
Cabal/Distribution/Simple/SrcDist.hs

This was only a convenience function, but its use could obscure how it
is introducing a dependency on the CWD. By removing it, the "."
argument to `matchDirFileGlob` is explicit.
Any external code using `matchFileGlob` would have needed to be
changed as #5284 changed its signature and the module it lives in; it
is not much more of a burden to switch to `matchDirFileGlob` at the
same time.

Remove matchFileGlob.

---

cabal-install/bootstrap.sh

jgm/zip-archive#47 has been merged and released as part of 0.3.3, so
there is now no need to grab old-time and old-locale in booststrap.sh.

bootstrap: no need for old-locale and old-time now

---

Cabal/Distribution/CabalSpecVersion.hs
Cabal/Distribution/PackageDescription/Parsec.hs

Lexically, they're identical to 2.2, but the semantics of globs have
changed slightly.
cc @phadej. I grepped for `CabalSpecV2_2` and put in an analogous `CabalSpecV2_4` wherever I found it. Is there anything else that needs doing?

Allow 2.4-spec files to be parsed.

---

cabal-install/Distribution/Client/CmdTest.hs

It's non-obvious that the expected way to pass command line options to
a test suite would be a different command, so mention it explicitly.
Closes #5416.
Ran it and made sure the `--help` output looked right.

Mention new-run in new-tests's --help output.

---

Cabal/ChangeLog.md
Cabal/Distribution/PackageDescription/Check.hs
Cabal/Distribution/Simple/Glob.hs
Cabal/Distribution/Simple/Haddock.hs
Cabal/Distribution/Simple/Install.hs
Cabal/Distribution/Simple/SrcDist.hs
Cabal/tests/UnitTests/Distribution/Simple/Glob.hs
cabal-testsuite/PackageTests/Check/InvalidGlob/cabal.out
cabal-testsuite/PackageTests/Check/InvalidGlob/cabal.test.hs
cabal-testsuite/PackageTests/Check/InvalidGlob/pkg.cabal
cabal-testsuite/PackageTests/Check/MissingGlobDirectory/Foo.hs
cabal-testsuite/PackageTests/Check/MissingGlobDirectory/cabal.out
cabal-testsuite/PackageTests/Check/MissingGlobDirectory/cabal.test.hs
cabal-testsuite/PackageTests/Check/MissingGlobDirectory/data/hello.dat
cabal-testsuite/PackageTests/Check/MissingGlobDirectory/file-not-a-directory
cabal-testsuite/PackageTests/Check/MissingGlobDirectory/pkg.cabal
cabal-testsuite/PackageTests/Check/MissingGlobDirectory/present/present/hello
cabal-testsuite/PackageTests/Check/MissingGlobDirectory2/Foo.hs
cabal-testsuite/PackageTests/Check/MissingGlobDirectory2/cabal.out
cabal-testsuite/PackageTests/Check/MissingGlobDirectory2/cabal.test.hs
cabal-testsuite/PackageTests/Check/MissingGlobDirectory2/pkg.cabal
cabal-testsuite/PackageTests/Check/MultiDotGlob2.2/data/index.dat
cabal-testsuite/PackageTests/Check/MultiDotGlob2.2/doc/index.html
cabal-testsuite/PackageTests/Check/MultiDotGlob2.2/src/index.js
cabal-testsuite/PackageTests/Check/NoGlobMatches/cabal.out
cabal-testsuite/PackageTests/Check/NoGlobMatches/cabal.test.hs
cabal-testsuite/PackageTests/Check/NoGlobMatches/pkg.cabal

Tests added!
This PR is based on top of #5401 and #5402 (which explains today's PR frenzy: I didn't expect to need to do #5401 when I started!). I'll rebase on master once those two are merged. As noted in #5401, the `cabal-version` check in `Check.hs` is kind of weird; I have left it in the expected output of the relevant test on the basis that it's easy to remove later.

cabal check improvements for globs

---

cabal-install/Distribution/Client/PackageHash.hs

Think this should be a minor change. Removes an unused language pragma (I think) and fixes some typos in the OSX linker workaround description.

Fixup spelling in hashedInstalledPackageIdVeryShort comment on OSX linker workaround.

---

cabal-install/Distribution/Client/Init.hs

---
Current changelog default name for new projects is ``ChangeLog.md``.
The word "Changelog" is nowadays [a single word](https://en.wikipedia.org/wiki/Changelog), so I lowercased the capital "L".
An alternative could have been "Changelog.md", but Pascal-cased name are usually restricted to source files in Haskell projects. Yet another alternative could have been "CHANGELOG.md", but all caps + .md extension is uncommon.

Changed default changelog name to "changelog.md"

---

Cabal/Distribution/Simple/GHCJS.hs

because ghcjs does not like if the flag appears more than once, and it
seems it was happy before with the `jsSrc` files to be passed without a
flag.
This works-round https://github.com/ghcjs/ghcjs/issues/678 and
fixes #5442

Do not pass -js-lib-src to ghcjs

---

cabal-install/Distribution/Client/CmdBench.hs
cabal-install/Distribution/Client/CmdBuild.hs
cabal-install/Distribution/Client/CmdHaddock.hs
cabal-install/Distribution/Client/CmdInstall.hs
cabal-install/Distribution/Client/CmdRepl.hs
cabal-install/Distribution/Client/CmdRun.hs
cabal-install/Distribution/Client/CmdSdist.hs
cabal-install/Distribution/Client/CmdTest.hs
cabal-install/Distribution/Client/TargetSelector.hs
cabal-install/changelog
cabal-install/tests/IntegrationTests2.hs

Disambiguate selectors by the command being used

---

Cabal/ChangeLog.md
Cabal/Distribution/Compat/Lens.hs
Cabal/Distribution/Simple/Haddock.hs
Cabal/Distribution/Types/PackageDescription/Lens.hs
cabal-install/Distribution/Client/ProjectBuilding.hs
cabal-install/Distribution/Client/ProjectOrchestration.hs
cabal-install/changelog

Attempt to avoid Haddock errors, make them nonfatal anyway

---

Cabal/Distribution/Compat/Lens.hs
Cabal/Distribution/Simple/Flag.hs
Cabal/Distribution/Simple/Utils.hs
Cabal/Distribution/Types/Executable/Lens.hs
Cabal/Distribution/Types/PackageDescription/Lens.hs
Cabal/Distribution/Types/PackageId.hs
Cabal/doc/nix-local-build.rst
cabal-install/Distribution/Client/CmdInstall.hs
cabal-install/Distribution/Client/CmdRepl.hs
cabal-install/Distribution/Client/CmdUpdate.hs
cabal-install/Distribution/Client/FetchUtils.hs
cabal-install/Distribution/Client/Install.hs
cabal-install/Distribution/Client/InstallPlan.hs
cabal-install/Distribution/Client/ProjectConfig.hs
cabal-install/Distribution/Client/ProjectOrchestration.hs
cabal-install/Distribution/Client/Types.hs
cabal-install/changelog

Closes #5425. Adds `--package` flag, allows `new-repl` use outside of project folders.

Add --build-depends flag, associated support to new-repl

---

Cabal/Distribution/Simple/Program/Builtin.hs
cabal-install/Distribution/Client/PackageHash.hs
cabal-install/Distribution/Client/ProjectPlanning.hs

This should help with https://github.com/haskell/cabal/issues/5341
This adds haddock flags and arguments to the package hash. Changing haddock flags for non-local packages will retrigger a build of these.
I view this as a quick fix. I think we really want documentation to be treated as a separate component.

Add Haddock flags to package hash

---

Cabal/doc/developing-packages.rst
cabal-install/Distribution/Client/Outdated.hs
cabal-install/Distribution/Client/Setup.hs
cabal-install/changelog
cabal-testsuite/PackageTests/Outdated/outdated-project-file.out
cabal-testsuite/PackageTests/Outdated/outdated-project-file.test.hs
cabal-testsuite/PackageTests/Outdated/variant.project
cabal-testsuite/PackageTests/Outdated/variant.project.freeze

This doesn't get anywhere near the improvements suggested in #4831,
but it's a very respectable improvement over the status-quo for not
much effort.
New test added for this.

outdated: accept --project-file

---

Cabal/ChangeLog.md
Cabal/Distribution/Backpack/ConfiguredComponent.hs
cabal-install/Distribution/Client/ProjectPlanning.hs
cabal-testsuite/PackageTests/Regression/T5409/Main.hs
cabal-testsuite/PackageTests/Regression/T5409/cabal.project
cabal-testsuite/PackageTests/Regression/T5409/pkg.cabal
cabal-testsuite/PackageTests/Regression/T5409/repo/build-tool-pkg-1/build-tool-pkg.cabal
cabal-testsuite/PackageTests/Regression/T5409/repo/build-tool-pkg-1/main/Main.hs
cabal-testsuite/PackageTests/Regression/T5409/repo/build-tool-pkg-1/src/BuildToolLibrary.hs
cabal-testsuite/PackageTests/Regression/T5409/repo/build-tool-pkg-2/build-tool-pkg.cabal
cabal-testsuite/PackageTests/Regression/T5409/repo/build-tool-pkg-2/main/Main.hs
cabal-testsuite/PackageTests/Regression/T5409/repo/build-tool-pkg-2/src/BuildToolLibrary.hs
cabal-testsuite/PackageTests/Regression/T5409/use-different-versions-of-dependency-for-library-and-build-tool.out
cabal-testsuite/PackageTests/Regression/T5409/use-different-versions-of-dependency-for-library-and-build-tool.test.hs

new-build had assumed that each component could only directly depend on one
version of each package.  However, a component can depend on two different
versions of a package by listing it as a build-depends and build-tool-depends
dependency.  The incorrect assumption caused new-build to mix up the two
instances of the dependency when converting the solver's package-based install
plan (SolverInstallPlan) to the component-based install plan
(ElaboratedInstallPlan).  This commit fixes the bug by keeping build-depends and
build-tool-depends dependencies separate between reading them from the
SolverPackage and passing them to
D.Backpack.ConfiguredComponent.toConfiguredComponent.
This commit changes the signature of
D.Backpack.ConfiguredComponent.toConfiguredComponent to allow distinguishing …

Fix bug in converting SolverInstallPlan to ElaboratedInstallPlan (fixes #5409).

---

Cabal/doc/developing-packages.rst
cabal-install/Distribution/Client/Setup.hs
cabal-install/changelog

outdated: accept v1/v2 aliases for freeze-file flags

---

Cabal/Distribution/PackageDescription/Parsec.hs
Cabal/Distribution/Parsec/ParseResult.hs
Cabal/doc/nix-local-build.rst
cabal-install/Distribution/Client/CmdRun.hs
cabal-install/Distribution/Client/TargetSelector.hs
cabal-install/cabal-install.cabal
cabal-install/changelog
cabal-install/main/Main.hs

Closes #3843. Implements effectively the design given, with some changes:
* `cabal new-run` allows the user to run scripts in files without shebangs
* The `{- cabal: -}` syntax is now that of the executable block
---

Add cabal scripting support

---

Cabal/ChangeLog.md
Cabal/Distribution/Simple/Register.hs

Resolves #5465
I have tried to `new-build` one personal package, and the output was without any `abi-depends` related warnings. However, when I was using `new-install` on the same package, the warnings were still printed out. So this is not the complete fix of the task, but I don't know what can be done about that.

Set abiDepends field in IPI to []

---

Cabal/Cabal.cabal

This will be necessary for GHC 8.6. Please do cherry-pick into the stable branch.
---

Cabal: Allow binary 0.10

---

Cabal/doc/conf.py
Cabal/doc/nix-local-build.rst
cabal-install/Distribution/Client/ProjectPlanOutput.hs
cabal-install/changelog

This PR extends packages in the `plan.json` file with a `pkg-src` field. This is really helpful for third-party tooling to find the paths to all the project local packages including source repositories and such.
/cc @hvr @shlevy

Extend packages in plan.json with pkg-src field

---

Cabal/Distribution/Compat/Graph.hs

This is required to compile Cabal with `-Wcompat` under https://phabricator.haskell.org/D5044

Remove a '*' kind annotation

---

Cabal/Distribution/Simple/Haddock.hs
cabal-install/Distribution/Client/Setup.hs

We error-out when `--quickjump` is specified on a version of Haddock that
doesn't support it. However, if `--quickjump` was implied by
`--haddock-for-hackage`, we should just warn.
Fixes #5494.
---

`--haddock-for-hackage` works with older Haddock

---

Cabal/doc/developing-packages.rst

[skip ci]
This should probably be merged to 2.4 as well.
---

docs: mention hiding in mixins and issues for the parsing bug

---

Cabal/Distribution/Simple/Haddock.hs

Herbert noticed that with `--haddock-for-hackage` we were passing strange `file://..` urls to the html directories. It soon showed that I had screwed up in an earlier PR.

Fix x-package references with --haddock-for-hackage

---

cabal-install/Distribution/Client/CmdInstall.hs
cabal-install/Distribution/Client/ProjectConfig/Legacy.hs
cabal-install/Distribution/Client/ProjectConfig/Types.hs
cabal-install/Distribution/Client/ProjectOrchestration.hs
cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs

This fixes https://github.com/haskell/cabal/issues/5504. Sorry for the diff noise. ~I think @hvr wants to push a WS cleanup first.~

Move projectConfigStoreDir to ProjectConfigShared

---

Cabal/Distribution/Types/GenericPackageDescription/Lens.hs

Record syntax is easier to read and more robust against refactors.
@phadej you were saying the old one was autogenerated, but is there a way to automatically regenerate it? If not, I think this is better.

Make GenericPackageDescription lenses more maintainable

---

Cabal/ChangeLog.md
Cabal/Distribution/PackageDescription/Check.hs
cabal-testsuite/PackageTests/Backpack/Includes2/cabal-internal.out
cabal-testsuite/PackageTests/BuildTools/Internal/cabal.out
cabal-testsuite/PackageTests/InternalVersions/BuildDependsExtra/setup.cabal.out
cabal-testsuite/PackageTests/InternalVersions/BuildDependsExtra/setup.out
cabal-testsuite/PackageTests/InternalVersions/BuildDependsExtra/setup.test.hs
cabal-testsuite/PackageTests/Regression/T5309/cabal.out
cabal-testsuite/PackageTests/TestSuiteTests/ExeV10/cabal.out

Issue #5119 is tracking spurious generation of these warnings. There
are a lot of them! We can't release with so many false positives, so
just squelch the warning outright.
This is a hack and this commit should be reverted if we get a proper
fix that can be backported to the 2.4 branch.
---

Hack around #5119 by disabling the warning.

---

cabal-install/Distribution/Solver/Modular/Builder.hs
cabal-install/Distribution/Solver/Modular/Explore.hs
cabal-install/Distribution/Solver/Modular/Message.hs
cabal-install/Distribution/Solver/Modular/Tree.hs
cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs

Two main commits:
Previously, the solver represented an unknown package with an empty PChoice
node, because an unknown package is like a package with no versions.  Now that
--reject-unconstrained-dependencies also needs to reject whole packages, it is
simpler to handle both types of failures similarly, and use a failure node for
both.  Another advantage of using a failure node now is that the node can store
more information about why the package was rejected.  The explicit node also
simplifies generating the solver log.
This commit treats a failure node under a goal choice as a backjump in
D.S.Modular.Explore.exploreLog, which fixes #5502.
The one-line error message is more similar to the message for rejecting a
package version.
Closes #5501.
Before:
```
[__0] trying: A-3.0.0 (user goal) …
```

Solver: Improve handling of failures involving whole packages, such as unknown packages.

---

.travis.yml

Josh here from Travis CI
Our `sudo: true` infrastructure are full VMs and are generally faster build environments than the `false` counterpart.
Additionally, we can enable 4 core VMs, giving you faster compile times.
This change will allow me to enable the 4 core feature for testing.

WIP: use sudo: true on travis ci

---

cabal-install/Distribution/Client/ProjectConfig/Legacy.hs

Before this change, only the last set of program args would be kept in new-style commands. For example, the following wouldn't complain about the bogus GHC option `--bogus`, because only `-O1` got passed to GHC.
cabal new-build --ghc-option '--bogus' --ghc-option '-O1'
Now, all program args are kept.
---

Don't throw away any program args in new-style commands

---

Cabal/Distribution/Simple/Configure.hs
Cabal/Distribution/Simple/GHC.hs

Fresh PR for https://github.com/haskell/cabal/pull/5118

Foreign Library RTS Selection

---

cabal-install/Distribution/Client/CmdSdist.hs
cabal-install/Distribution/Client/Setup.hs
cabal-install/changelog

---
I've executed the following command:
```
$ cabal --storedir foo/ new-build cabal-install
```
And got this error:
```
ghc-pkg: foo/ghc-8.4.3/package.db: getDirectoryContents:openDirStream: does
not exist (No such file or directory)
```
Without change in this PR it produces some error regarding parsing CLI arguments.
Maybe I should change some existing test to make sure that `storedir` option won't disappear? But I don't know which one and whether I should do this or not...

[#5484] Add 'storedir' alias for 'store-dir'

---

Cabal/ChangeLog.md
Cabal/Distribution/Simple/PreProcess.hs

---
Fixes #3122. Also see [Trac #13896](https://ghc.haskell.org/trac/ghc/ticket/13896).
`hsc2hs` has gained the ability to accept command line arguments via response files, which helps 
to work around the limit on their length on Windows. This is the next step which updates Cabal to use a response file when invoking `hsc2hs`. Unfortunately, I have not yet tried to build the projects ([this gist](https://gist.github.com/mkscrg/18c560b8eb303c6ebcf2) and [ermine](https://github.com/ermine-language/ermine)) mentioned in the issue. I will do it as soon as I get access to a Windows machine (or once I setup Vagrant or something). Note that this patch only changes the invocation logic for `hsc2hs >= 0.68.4` which will be released with GHC 8.6. …

Pass command line arguments to hsc2hs using response files

---

Cabal/Distribution/Simple.hs

In the course of 4466310e48e8c401ca2492d0fc2c5018ad8de961 (see #5526) the
`Setup.hs haddock` CLI was extended to allow component ids to be passed
as positional arguments. However, `autoconfUserHooks` which is used in
case of `build-type: Configure` wasn't updated accordingly, and consequently
this caused `new-haddock` to break for packages using `Configure`.
cc @alexbiehl
Fixes #5503

Allow arguments to be passed to `Setup.hs haddock` for `build-type:configure`

---

Cabal/doc/developing-packages.rst

Clarify build-tool-depends a bit more

---

Cabal/doc/developing-packages.rst

Document https://github.com/haskell/cabal/pull/4751#issuecomment-418269774
---

doc: common stanzas: import must be the first field

---

Cabal/Distribution/Simple/GHC.hs
cabal-install/changelog

For some reason repl invocation was skipped for indefinite components.
However, GHCi seems to handle them just fine.
Fixes #5619.
How I tested this change: Using the test case from issue #5619. Ran `cabal new-repl` and verified that it does indeed launch GHCi.
I couldn't figure out how to add this as an automated test to the suite, as it required somehow killing GHCi to avoid hanging indefinitely. The simplest options I could think of is passing `:quit` as input, but I couldn't find facilities for passing stdin in the test machinery.
---

Setup: Don't skip repl for indefinite components

---

Cabal/ChangeLog.md
Cabal/Language/Haskell/Extension.hs

I compiled it and tested it on a project, that uses `DerivingVia` as a `default-extension`.

Add DerivingVia to KnownExtensions

---

cabal-install/Distribution/Client/ProjectPlanning.hs

Monolithic inplace packages have a directory for each exe, so we allow
multiple paths and return all the exe paths of the package.
Fixes #5104
/cc @hvr

Fix monolithic inplace build tool PATH

---

cabal-install/Distribution/Client/CmdInstall.hs
cabal-install/Distribution/Client/Install.hs
cabal-install/Distribution/Client/InstallSymlink.hs

Phase 2 of the fix for #5491. Followup to #5602.
Erroring out is safer and more explicit.
Next, we'll have to check for error/no-op as early as possible (currently we build everything first).
/cc @hvr

new-install: error on existing symlink, overwrite option

---

cabal-install/Distribution/Client/CmdInstall.hs

It conflicted with the flag with the same name from configFlags
Fixes #5550
/cc @hvr

Filter out ambiguous builddir flag

---

Cabal/doc/nix-local-build.rst
cabal-install/Distribution/Client/CmdBuild.hs
cabal-install/Distribution/Client/CmdExec.hs
cabal-install/Distribution/Client/ProjectPlanning.hs
cabal-install/Distribution/Client/ProjectPlanning/Types.hs
cabal-install/Distribution/Client/Setup.hs
cabal-install/changelog
cabal-testsuite/PackageTests/NewBuild/CmdBuild/OnlyConfigure/Bar.hs
cabal-testsuite/PackageTests/NewBuild/CmdBuild/OnlyConfigure/Baz.hs
cabal-testsuite/PackageTests/NewBuild/CmdBuild/OnlyConfigure/Foo.hs
cabal-testsuite/PackageTests/NewBuild/CmdBuild/OnlyConfigure/Lib.hs
cabal-testsuite/PackageTests/NewBuild/CmdBuild/OnlyConfigure/OnlyConfigure.cabal
cabal-testsuite/PackageTests/NewBuild/CmdBuild/OnlyConfigure/cabal.out
cabal-testsuite/PackageTests/NewBuild/CmdBuild/OnlyConfigure/cabal.project
cabal-testsuite/PackageTests/NewBuild/CmdBuild/OnlyConfigure/cabal.test.hs

When this flag is active we only execute the Cabal build system's 'configure'
step for each local unit and nothing else. This allows (re)generating the Setup
configuration cache which is accessed directly by tooling like ghc-mod and HIE
through cabal-helper and allows such tooling to forgoe a full rebuild.
I've added a new `BuildFlags` type for `v2-build` specific options since don't think just sticking this in any of the other flags sets makes even a lick of sense.
It seems to me that for some reason the `defaultBuildFlags` are not being applied to the flags before being passed to `buildAction`, so I have worked around that by doing `fromFlag (buildOnlyConfigure defaultBuildFlags <> buildOnlyConfigure buildFlags)` which is kind of really ugly.
@hvr turns out combining …

Add new v2-build flag '--only-configure'

---

cabal-install/Distribution/Client/Init/Types.hs
cabal-install/Distribution/Client/Setup.hs
cabal-install/main/Main.hs

Fixes #5654 
Fixes #4936
----
Besides giving you the ability to conveniently pick a different `ghc` which you could workaround by e.g.
```
PATH=/opt/ghc/8.6.2/bin:$PATH cabal init
```
via a simpler, more explicit (because it doesn't rely on the indirection via $PATH to pick the right exe), and more idiomatic
```
cabal init -w ghc-8.6.2
```
if you have a setup where all `ghc` versions are symlinked version-suffixed in your $PATH already.
However, there's also the case where you don't have *any* `ghc` in your PATH, but *only* `ghc-<version>` symlinks; this is e.g. the default setup scheme promoted by `ghcup` and for this case, there's not necessarily any workaround (other than creating a `cabal.config` file or modifying your global cabal config). Or an even more pathological case is
``` …
```

Add `-w`/`--with-compiler` flag to `cabal init`

---

cabal-install/bootstrap.sh

* `bootstrap.sh` can use local tarball, this change enhances it by using
the unpacked local directory if that exists, so it's possible to play
with a patch of a dependency locally.
* a flag `--no-install` is added, so we can fetch and unpack all
dependencies without actually installing them. this will allow us to
later patch or build standalone cabal offline.
Test plan:
`./bootstrap.sh --no-install` downloads a bunch of packages and
I can run `./bootstrap.sh` later to build cabal without network.
---

Enable bootstrap script to download and use local unpacked dependencies

---

Cabal/doc/nix-local-build.rst

This page is often surfaces above the "Developing Packages Quickstart" section in search results (for queries including "cabal new project") but a beginner ending up here may not know how to set up their package before using the commands here. This adds a link to the relevant section in the docs that walks through how to set up a package so they don't need to go looking for it themselves.
This is a docs-only change.
[ci skip]

Link to 'developing packages' from new-build docs.

---

cabal-install/Distribution/Client/CmdInstall.hs

Tell the user about --lib when new-installing a package with no exes

---

Cabal/Distribution/Simple/Program/GHC.hs

This change should be backported to the 2.4 branch for the next point release.
---

Cleans up the `-Werror` check, adds GHC 8.6.1 support and also filters RTS flags, fixing #5575

---

Cabal/Distribution/Compat/Prelude.hs

Due to a bug in ghc, some unused imports do not yield warnings.
This commit will remove such unused imports in preparation for
the ghc bug fix (see https://ghc.haskell.org/trac/ghc/ticket/13064).
---
Testing: Building in CI should be sufficient here.

Remove unused Semigroup imports.

---

cabal-install/main/Main.hs

We used to only transliterate coding failures on Windows, but this can
fail on other platforms as well, e.g. when `LANG=C` is set on Linux.
We have done this in ghc for all platforms:
https://phabricator.haskell.org/D4642
Before, following commands will fail
```
$ LANG=C cabal install base-compat --verbose=3
Finalized package description:
...
(c) 2014-2018 Jo<stdout>: commitBuffer: invalid argument (invalid character)
```
and now finishes without problem, and print
```
(c) 2014-2018 Jo?o Crist?v?o,
```
instead.
---

Always transliterate coding failures for stdout and stderr

---

Cabal/Distribution/Simple/Build.hs
cabal-testsuite/PackageTests/Regression/T5677/cabal.out
cabal-testsuite/PackageTests/Regression/T5677/cabal.project
cabal-testsuite/PackageTests/Regression/T5677/cabal.test.hs
cabal-testsuite/PackageTests/Regression/T5677/impl/Sig.hs
cabal-testsuite/PackageTests/Regression/T5677/impl/impl.cabal
cabal-testsuite/PackageTests/Regression/T5677/prog/prog.cabal
cabal-testsuite/PackageTests/Regression/T5677/prog/prog.hs
cabal-testsuite/PackageTests/Regression/T5677/prog/src/Prog.hs
cabal-testsuite/PackageTests/Regression/T5677/sig/Sig.hsig
cabal-testsuite/PackageTests/Regression/T5677/sig/sig.cabal

Issue #5677 demonstrates one way for warnings to be produced by dummy
signatures. Autogenerated code really ought to never be generating
warnings, under any sets of flags provided by the user; this patch
uses the big hammer of entirely disabling warnings for the generated
signatures.
Fixes #5677.
---

Suppress warnings in autogenerated signatures.

---

Cabal/Distribution/Simple/GHC.hs
Cabal/Distribution/Simple/GHC/Internal.hs
Cabal/Distribution/Simple/GHCJS.hs

Compile profiling library for use with GHCi when both
`--enable-profiling` and `--enable-library-for-ghci` are passed.
The merged `HS${package}.p_o` file can be loaded instead of
`libHS${package}_p.a` when we run GHCi with
`-prof -fexternal-interpreter` to speed up the linking time.
This depends on the change in ghc side:
https://phabricator.haskell.org/D5169
This will produce a new `.p_o` file which will get picked up by
new ghc and ignored by older version. It's backward compatible.
```bash
$HOME/gao/cabal/cabal-install/dist/build/cabal/cabal install --with-ghc=$HOME/gao/ghc/inplace/bin/ghc-stage2 --enable-profiling --enable-library-for-ghci --reinstall
$HOME/gao/ghc/inplace/bin/ghc-stage2 -prof -fexternal-interpreter -package-db=base64-bytestring-1.0.0.1/.cabal-sandbox/x86_64-linux-ghc- …
```

Compile profiling library for use with GHCi

---

Cabal/Distribution/Types/ModuleRenaming.hs

We have this code in `Cabal`, which I don't believe to be syntactically valid Haskell:
```
do fmap ModuleRenaming parseRns
<++ parseHidingRenaming
<++ return DefaultRenaming
```
It works by a fluke. The GHC parser shifts and we parse it as
```
do (fmap ModuleRenaming parseRns
<++ parseHidingRenaming
<++ return DefaultRenaming)
```
rather than
```
do (fmap ModuleRenaming parseRns)
(<++ parseHidingRenaming)
(<++ return DefaultRenaming)
```
However, this behaviour is hard to support. I'm currently working on a set of changes to the parser that result in no shift in this case -- and then get the latter parse, which results in an error about no LHS for `<++`.
Furthermore, even in today's GHC such syntax is not fully supported (happens to work for the `<++` operator above, but not if the …

Remove 'do' in 'instance Text ModuleRenaming'

---

cabal-install/Distribution/Client/ProjectPlanOutput.hs
cabal-install/Distribution/Client/ProjectPlanning.hs
cabal-install/Distribution/Client/ProjectPlanning/Types.hs
cabal-install/Distribution/Solver/Types/ComponentDeps.hs

Having this enables tooling to give better error messages when build output is
missing. cabal-install can choose to include optional components in the build
plan even though they weren't requested explicitly by the user. Currently
tooling would have to assume missing build output after a `v2-build all` call
means the component is currently disabled, which is just not very clean.
---

Add 'optional-target' field to plan.json

---

Cabal/Distribution/Simple/Setup.hs
cabal-install/Distribution/Client/CmdBench.hs
cabal-install/Distribution/Client/CmdBuild.hs
cabal-install/Distribution/Client/CmdConfigure.hs
cabal-install/Distribution/Client/CmdExec.hs
cabal-install/Distribution/Client/CmdFreeze.hs
cabal-install/Distribution/Client/CmdHaddock.hs
cabal-install/Distribution/Client/CmdInstall.hs
cabal-install/Distribution/Client/CmdLegacy.hs
cabal-install/Distribution/Client/CmdRepl.hs
cabal-install/Distribution/Client/CmdRun.hs
cabal-install/Distribution/Client/CmdTest.hs
cabal-install/Distribution/Client/CmdUpdate.hs
cabal-install/Distribution/Client/Config.hs
cabal-install/Distribution/Client/Install.hs
cabal-install/Distribution/Client/ProjectConfig/Legacy.hs
cabal-install/Distribution/Client/ProjectConfig/Types.hs
cabal-install/Distribution/Client/ProjectPlanning.hs
cabal-install/Distribution/Client/ProjectPlanning/Types.hs
cabal-install/Distribution/Client/Sandbox.hs
cabal-install/Distribution/Client/Setup.hs
cabal-install/changelog
cabal-install/main/Main.hs
cabal-install/tests/UnitTests/Distribution/Client/ArbitraryInstances.hs
cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs

Make all of the old-style `test` flags available to `new-test`/`new-build`/`new-install`/etc. This should include:
* `--log` (as `--test-log`)
* `--machine-log` (as `--test-machine-log`)
* `--show-details` (as `--test-show-details`)
* `--keep-tix-files` (as `--test-keep-tix-files`)
* `--test-options` (as `--test-options`)
* `--test-option` (as `--test-option`)
---
---
Fixes #4803
Fixes #4643
Fixes #4766
Fixes #5416

Port 'TestFlags' to 'new-test'

---

Cabal/Distribution/Simple/GHC.hs
Cabal/Distribution/Simple/GHCJS.hs

Summary:
Fix old trac links
https://phabricator.haskell.org/D5259
Test Plan:
Manually verify links
GHC Trac Issues: #15733
---

Fix some broken links (Trac #15733) [ci skip]

---

cabal-install/Distribution/Client/CmdInstall.hs

f6aaeeeae3daca0240a6192024934f4b2143412e acted on units, but an exe+lib
package generates two units (when per-component building is enabled) and
it produced a warning for the lib one.
Now the check is done on all units together.
/cc @hvr

Fix erroneous "no exes" warning on lib+exe packages

---

cabal-install/Distribution/Client/CmdInstall.hs
cabal-install/changelog

As pointed out to me by @hvr, this bit of helpful error reporting was not present in new-install.
Fixes #5601.
---

Add message to alert user to potential package casing errors.

---

cabal-install/Distribution/Client/CmdClean.hs
cabal-install/changelog

new-clean should not delete dist-newstyle/src

---

Cabal/doc/developing-packages.rst
Cabal/doc/nix-local-build.rst

Fix a typo
Clarify pkg-config (closes #4242)
Clarify cabal-version (closes #2571)
Minor tweak to description of extra-bundled-libraries.
---

Documentation updates [ci skip]

---

Cabal/Distribution/Simple/GHC/EnvironmentParser.hs
cabal-install/Distribution/Client/CmdClean.hs
cabal-install/Distribution/Client/Config.hs
cabal-install/Distribution/Client/ProjectConfig/Legacy.hs
cabal-install/Distribution/Client/ProjectConfig/Types.hs
cabal-install/Distribution/Client/ProjectOrchestration.hs
cabal-install/Distribution/Client/ProjectPlanning/Types.hs
cabal-install/Distribution/Client/Setup.hs
cabal-install/Distribution/Client/Types.hs
cabal-install/tests/UnitTests/Distribution/Client/ArbitraryInstances.hs
cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
cabal-testsuite/PackageTests/NewBuild/CmdExec/GhcInvocation/cabal.test.hs

* Add a config flag to control generation of `.ghc.environment` files. Fixes #4542.
* Change `new-clean` to also remove `.ghc.environment` files. Fixes #5587.
This is the final blocker before the 2.4.1.0 release.
I haven't updated the docs yet, will do tomorrow.
---

Improve the handling of .ghc.environment files

---

cabal-install/Distribution/Client/CmdSdist.hs
cabal-install/changelog

Fix #5643 which is a bigger bug than original reported: `v2-install` currently does not work at all if there are git packages. // @hasufell 
---

Fix "source-repository-package breaks 'cabal v2-install'"

---

Cabal/Distribution/PackageDescription/Configuration.hs
Cabal/Distribution/PackageDescription/FieldGrammar.hs
Cabal/Distribution/PackageDescription/Parsec.hs
Cabal/Distribution/PackageDescription/PrettyPrint.hs

Next in series to get rid of ReadP
---

Remove Text from D.PackageDescription

---

cabal-install/Distribution/Client/Check.hs
cabal-install/Distribution/Client/ProjectConfig.hs
cabal-install/Distribution/Client/Utils/Parsec.hs
cabal-install/cabal-install.cabal
cabal-install/cabal-install.cabal.pp

- Separate the logic into own module
- Use same function in `cabal check` codepath
- Tweak the output a little more
```
% cabal check
Warning: tree-diff.cabal:88:5:
unexpected 't'
expecting space, "&&", white space, "||", comma or end of input
cabal: Errors encountered when parsing cabal file ./tree-diff.cabal:
tree-diff.cabal:88:5:
unexpected 't'
expecting space, "&&", white space, "||", comma or end of input
87 | tagged >=0.8.5 && <0.9
88 | text >=1.2.2.2 && <1.3,
89 | time >=1.4.2 && <1.9,
tree-diff.cabal:70:3: Unknown field: "build-depend"
69 | Data.TreeDiff.QuickCheck
70 | build-depend: base
71 | build-depends:
tree-diff.cabal:59:3: Unknown field: "build-depend"
58 | library
59 | build-depend: base
60 | exposed-modules:
```
--- …

Improve printing of errors of parsing .cabal files even further

---

Cabal/Distribution/FieldGrammar/Parsec.hs
Cabal/Distribution/PackageDescription/Parsec.hs
Cabal/Distribution/Parsec/Class.hs
Cabal/tests/ParserTests/regressions/MiniAgda.check
cabal-install/Distribution/Client/Utils/Parsec.hs

```
Errors encountered when parsing cabal file ./tree-diff.cabal:
tree-diff.cabal:102:7: 
unexpected 'n'
expecting space, "&&", white space, "||", comma or end of input
98 |       void               >=0.7.2    && <0.8
99 | 
100 |       -- space and comments
101 | 
102 |       nats               >=1.1.1    && <1.2,
|       ^
tree-diff.cabal:86:48: version with tags
85 |     tagged               >=0.8.5    && <0.9,
86 |     text                 >=1.2.2.2  && <1.3-foo,
|                                                ^
```
---

Fancy error printing

---

Cabal/doc/nix-local-build.rst
cabal-install/Distribution/Client/CmdInstall.hs
cabal-install/Distribution/Client/CmdSdist.hs
cabal-install/Distribution/Client/DistDirLayout.hs
cabal-install/Distribution/Client/Setup.hs
cabal-install/Distribution/Client/SrcDist.hs
cabal-install/cabal-install.cabal
cabal-install/cabal-install.cabal.pp
cabal-install/changelog
cabal-install/main/Main.hs

This PR addresses #5735, including the removal of the `zip-archive` dependency per the comments
Extra:

Remove support for `.zip` format source distributions

---

Cabal/Cabal.cabal
Cabal/Distribution/FieldGrammar/Class.hs
Cabal/Distribution/FieldGrammar/FieldDescrs.hs
Cabal/Distribution/FieldGrammar/Parsec.hs
Cabal/Distribution/FieldGrammar/Pretty.hs
Cabal/Distribution/PackageDescription/FieldGrammar.hs
Cabal/doc/cabaldomain.py
Cabal/doc/developing-packages.rst
Cabal/doc/file-format-changelog.rst
Cabal/tests/ParserTests.hs
Cabal/tests/ParserTests/errors/removed-fields.cabal
Cabal/tests/ParserTests/errors/removed-fields.errors

- extensions
- (singular) hs-source-dir
- build-tools
Example, with `cabal-version: 2.5`
```
[laptop] tree-diff % cabal new-build --dry
Errors encountered when parsing cabal file ./tree-diff.cabal:
tree-diff.cabal:59:3: error:
The field "extensions" is removed in the Cabal specification version 2.5. Please use 'default-extensions' or 'other-extensions' fields.
58 | library
59 |   extensions: CPP
|   ^
tree-diff.cabal:60:3: error:
The field "extensions" is removed in the Cabal specification version 2.5. Please use 'default-extensions' or 'other-extensions' fields.
59 |   extensions: CPP
60 |   extensions: DeriveGeneric
|   ^
```
Resolves https://github.com/haskell/cabal/issues/5726
---
Please also shortly describe how you tested your …

Remove fields in cabal spec 3.0

---

validate.sh

- Add bunch of installed constraints to cabal.project.local.travis
- Fix compat in D.Compat.Directory
- Compat (process-1.1/ghc-7.6) in cabal-testsuite
- validate.sh improvements
- Warningless cabal-testsuite build
Forward port of #5730 
---

Remove unix constraint from cabal.project (forward port)

---

Cabal/Distribution/Simple/PreProcess.hs

This fixes https://github.com/haskell/cabal/issues/5764
`-x` will be passed to `hsc2hs` automatically any time we are cross-compiling. 
I tested this by building the `network` package.

Automatically pass -x to hsc2hs when cross-compiling

---

Cabal/Distribution/Simple/Setup.hs
cabal-install/Distribution/Client/CmdTest.hs
cabal-install/Distribution/Client/Config.hs
cabal-install/Distribution/Client/ProjectConfig/Legacy.hs
cabal-install/Distribution/Client/ProjectConfig/Types.hs
cabal-install/Distribution/Client/ProjectPlanning.hs
cabal-install/Distribution/Client/ProjectPlanning/Types.hs
cabal-install/Distribution/Client/Setup.hs
cabal-install/changelog
cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs

Change the default behaviour of `v2-test` so that it succeeds when no test suites are found.
This changes the exit code behaviour of the `v2-test` command when the "problem" is that no tests were found. Previously, when no tests were found `cabal v2-test` exit with status `1`, now prints a it friendlier message and exits with status `0`. The old behaviour can be achieved by passing `--test-fail-when-no-test-suites` to `cabal v2-test`.
This addresses #5435.
**--help output**
```
$ cabal v2-test help
<snip>
--test-fail-when-no-test-suites                      Exit with failure when no
test suites are found.
<snip>
```
**Before**
```
$ cabal v2-test
cabal: Cannot run tests for the target '' which refers to the package
initsample-0.1.0.0 because it does not contain …
```

Make v2-test succeed when no test suites found

---

Cabal/ChangeLog.md
Cabal/Distribution/Simple.hs

This fixes https://github.com/haskell/cabal/issues/5765
This has the minor downside of possibly breaking past behavior, since a `configure` script could feasibly error when passed an unknown flag. However, this would only occur when cross-compiling, and any `configure` script that doesn't accept a `--host` flag is unlikely to cross-compile anyways. 
I tested this by cross-compiling `network` (which uses `build-type: Configure`) locally.

pass --host=$HOST to configure when cross-compiling

---

Cabal/Distribution/Simple/Program/Find.hs

Due to idiosyncrasies (courtesy of the `SearchPath` Win32 function) in
the Windows implementation of `findExecutable` we need to explicitly try
both, with and without appending the Windows specific executable
extensions (i.e. `.exe`).
For example, before this patch,
cabal new-build -w ghc-8.6.2
would fail to find the `ghc-8.6.2.exe` even though it's on `%PATH%` and
invoking
ghc-8.6.2 --version
on the `CMD.exe` shell would have been able to locate the executable.

Fix `--with-compiler` failing to locate compiler on Windows

---

cabal-testsuite/PackageTests/Regression/T4291/dependee/Dependee.hs
cabal-testsuite/PackageTests/Regression/T4291/dependee/dependee.cabal
cabal-testsuite/PackageTests/Regression/T4291/depender/depender.cabal
cabal-testsuite/PackageTests/Regression/T4291/setup.cabal.out
cabal-testsuite/PackageTests/Regression/T4291/setup.out
cabal-testsuite/PackageTests/Regression/T4291/setup.test.hs

Add a regression test for #4291: relocatable is broken because some double dots in a path are not interpreted
This test used to fail with error message like:
```
setup: Library directory of a dependency: "/home/watashi/gao/hackage-github/cabal.fork/cabal-testsuite/PackageTests/Regression/T4291/setup.dist/../../../../../../../../../../tmp/cabal-testsuite-b71ce456fcbd95fa/prefix/lib/x86_64-linux-ghc-8.6.2/dependee-0.1.0.0"
is not relative to the installation prefix:
"/tmp/cabal-testsuite-b71ce456fcbd95fa/prefix"
```
and now passes with #5767: Fix checkRelocatable for deps when prefix is not subdir of pkgroot
---

Add a regression test for #4291

---

Cabal/Cabal.cabal
Cabal/tests/CheckTests.hs
Cabal/tests/ParserTests.hs
Makefile

Add hacked the --cwd argument parsing to
parser-tests and check-tests. It's a kludge
but it's good enough.

Add rules to run tests via "make parser-tests" etc

---

Cabal/ChangeLog.md
Cabal/Distribution/Simple/Register.hs
Cabal/Distribution/Types/InstalledPackageInfo.hs
Cabal/Distribution/Types/InstalledPackageInfo/FieldGrammar.hs
Cabal/Distribution/Types/InstalledPackageInfo/Lens.hs
Cabal/tests/ParserTests/ipi/Includes2.expr
Cabal/tests/ParserTests/ipi/internal-preprocessor-test.expr
Cabal/tests/ParserTests/ipi/issue-2276-ghc-9885.expr
Cabal/tests/ParserTests/ipi/transformers.expr

This pr only modifies the datatype. The field is not filled with the correct visibility info yet. We'll need a ghc-pkg compiled with this patch to actually record this information and properly test the visibility checks.
/cc @phadej @ezyang @23Skidoo
---

Add LibraryVisibility to InstalledPackageInfo

---

Cabal/Distribution/Simple/Build.hs
Cabal/Distribution/Simple/GHCJS.hs
Cabal/Distribution/Simple/LocalBuildInfo.hs

This PR contains two commits:
----
For some reason, the two operations
testSuiteExeV10AsExe :: TestSuite -> Executable
benchmarkExeV10asExe :: Benchmark -> ComponentLocalBuildInfo -> (Executable, ComponentLocalBuildInfo)
were different even though benchmarks and test-suite should be handled
mostly the same.
This divergence was exposed by #5831.
----
This way, we automatically gain *some* level of support for
`build-tools-depends` as well as for `v2-install` for applications
which are executed via nodejs
For instance, the following now works:
$ cabal v2-install -w /opt/ghcjs/8.4/bin/ghcjs --ghcjs alex --symlink-bindir=/tmp/bin
Build profile: -w ghcjs-8.4.0.1 -O1
- alex-3.2.4 (exe:alex) (requires …

Improve GHCJS support

---

cabal-install/Distribution/Client/Init.hs

`cabal init --simple` provides a way of initializing a cabal package with sensible defaults instead of requiring one to go through the entire interactive prompt. Its goal is to generate a modern directory structure (src/MyLib.hs, app/Main.hs, tests/MyLibTests.hs, etc.) and showcase new cabal features (^>=, recent cabal spec version, common stanzas, etc).
This change defaults to using a more recent cabal spec version instead of the current default of version 1.12.
This partially addresses #5696 and #5705.
Manually tested. After running `cabal init --simple` the `.cabal` file contains `cabal-version: 2.4` as the first line of the file.
---

Default to cabal version 2.4 when running `cabal init --simple`.

---

cabal-install/Distribution/Client/Config.hs
cabal-install/Distribution/Client/Setup.hs
cabal-install/main/Main.hs

This PR adds support for specifying the `non-interactive` option for `cabal init` in `~/.cabal/config` with the default value being `False`. This does not change any default behaviour.
When the configuration file is generated (when it does not exist), it will contain the following line:
```
-- non-interactive: False
```
This partially addresses #5696.
Manually tested. Added `non-interactive: False` to `~/.cabal/config` and ran `cabal init`:
```
$ cabal init
Guessing dependencies...
Generating LICENSE...
Warning: unknown license type, you must put a copy in LICENSE yourself.
Generating Setup.hs...
Generating CHANGELOG.md...
Generating myapp.cabal...
Warning: no synopsis given. You should edit the .cabal file and add one.
You may want to edit the .cabal file and add a Description field.
``` …

Add global configuration option for non-interactive cabal init.

---

cabal-install/Distribution/Client/CmdRepl.hs
cabal-install/changelog

`cabal repl --build-dep base, lens` now works as promised.
---

Allow list for `repl --build-depends`

---

cabal-install/Distribution/Client/Init.hs
cabal-install/changelog

Fixes haskell/cabal#5577.
---
> Please also shortly describe how you tested your change. Bonus points for added tests!
I have not. Pointers on how to do so are very appreciated!

Generate valid Main.lhs files with `cabal init`.

---

Cabal/doc/installing-packages.rst

Add information about the `--config-file` command line flag and the `CABAL_CONFIG` environment variable for specifying the cabal config file to section 2.1 ([Configuration](https://www.haskell.org/cabal/users-guide/installing-packages.html)) of the Cabal User Guide.
Fixes #5322.
---

Add documentation on --config-file and CABAL_CONFIG env variable.

---

cabal-install/Distribution/Client/Config.hs

Add a new `init` section to the global cabal config file for `cabal init`. The following fields can be currently be configured in this section: `non-interactive`, `cabal-version`, `license`, `language`, `source-dir`.
Partially addresses #5696.
Re-generating ~/.cabal/config results in a section containing the current default values for `cabal init`:
```
init
-- non-interactive: False
-- cabal-version: 1.10
-- license: BSD3
-- language: Haskell2010
-- source-dir:
```
Changing the values to:
```
init
non-interactive: True
cabal-version: 2.5
-- license: BSD3
-- language: Haskell2010
-- source-dir:
```
And running `cabal init --exe` does not enter the interactive prompt and produces a cabal file with `cabal-version: 2.5`.
---
Please also …

Add init section to global cabal config.

---

Cabal/doc/developing-packages.rst

Add a paragraph about common stanzas to the "Modules imported from other packages" section in Quickstart. This improves discoverability of this cabal feature which is currently somewhat difficult to find.
Fixes #5860.
Rendered docs: https://i.imgur.com/OcOgFhy.png
/cc @david-christiansen
---

Add info on common stanzas to Quickstart module import section

---

cabal-install/Distribution/Client/Init.hs

Default to initializing an executable when running `cabal init` non-interactively. This is inline with the other Haskell project initialization tools, as well as tools in other languages (such as Rust's Cargo).
This partially addresses #5696.
It is more common to want a binary than a library because often one wants to simply play around with an idea then to develop a full fledged library to publish on Hackage. Additionally, the binary case is always more common than the library case because each library is depended upon by _1 or more_ executables.
**Before:**
`cabal init --non-interactive` produces a library.
The `Library` option is choice 1 in the interactive prompt list.
**After:**
`cabal init --non-interactive` produces a binary.
The `Executable` option is choice 1 in the interactive …

Default to initializing executable when not specified to `cabal init`

---

cabal-install/Distribution/Client/CmdSdist.hs

The help message did not end with newline before and looked weird as it
can concatenate with next shell prompt.
---

Append newline to the end of sdist help message

---

cabal-install/Distribution/Client/CmdSdist.hs
cabal-install/changelog

This was broken by 7a029caa7026f9b6b585a68062a4175eadb6ca4f
We can not use `ByteString.pack` and then print it as `String`, which
will get encoded again based on the system setting, and very likely,
we get different things unless the encoding is something like ISO-8859-1, e.g.
in UTF-8 environment, the magic of gz "\x1f\x8b" will get encoded again
into "\x1f\xc2\x8b".
Before:
```
$ /cabal sdist --output-dir=- | tar -t -z -f -
tar: This does not look like a tar archive
```
And now:
```
$ cabal sdist --output-dir=- | tar -t -z -f -  | tail -n 1
cabal-install-2.5.0.0/tests/README.md
```
---

Fix sdist output when sent to stdout

---

Cabal/Distribution/Backpack/ReadyComponent.hs
cabal-testsuite/PackageTests/Backpack/T5634/Go.hs
cabal-testsuite/PackageTests/Backpack/T5634/T5634.cabal
cabal-testsuite/PackageTests/Backpack/T5634/Unused.hsig
cabal-testsuite/PackageTests/Backpack/T5634/impl/Impl.hs
cabal-testsuite/PackageTests/Backpack/T5634/setup.cabal.out
cabal-testsuite/PackageTests/Backpack/T5634/setup.out
cabal-testsuite/PackageTests/Backpack/T5634/setup.test.hs
cabal-testsuite/PackageTests/Backpack/T5634/sig-with-th/Sig.hsig
cabal-testsuite/PackageTests/Backpack/T5634/sig-with-th/THFuns.hs

Signed-off-by: Edward Z. Yang <ezyang@fb.com>
Didn't have time to add tests tonight, they'll come later. Affected users may want to see if this patch solves their problem. Fixes #5634
---

Instantiate fully instantiated dependencies even in indefinite packages.

---

Cabal/doc/installing-packages.rst

Copy edit the docs: a the -> the

---

Cabal/doc/nix-local-build.rst
cabal-install/Distribution/Client/Setup.hs
cabal-install/changelog

The last time the max-backjumps was increased was back in 2014
(see 0229cd5252d44ca65cf33fe350852b46b1a70b20) as suggested
per #1780, and while `--reorder-goals` might often help as well,
it also often comes at a bigger runtime penalty on average than
doubling the max-backjumps.
This should also address issues such as #5882
---

Increase `max-backjumps` default from 2000 to 4000

---

Cabal/Distribution/Fields/Parser.hs
Cabal/Distribution/Parsec/FieldLineStream.hs
Cabal/Distribution/Simple/BuildPaths.hs

Single quotes in Haddock are used for references to other identifiers.
Character literals should have both the single quote and possible backslash
escaped with extra backslashes.
[ci skip]
---

Docs: properly escape character literals

---

cabal-install/Distribution/Client/Setup.hs

When introducing the --interactive flag in #5864 I accidentally changed the flag
name from --non-interactive to --nonInteractive. This reverts that change.
---

Fix non-interactive flag name.

---

Cabal/Cabal.cabal
Cabal/ChangeLog.md
Cabal/Distribution/Types/VersionRange.hs
Cabal/doc/developing-packages.rst
Cabal/tests/ParserTests.hs
Cabal/tests/ParserTests/errors/version-sets-1.cabal
Cabal/tests/ParserTests/errors/version-sets-1.errors
Cabal/tests/ParserTests/errors/version-sets-2.cabal
Cabal/tests/ParserTests/errors/version-sets-2.errors
Cabal/tests/ParserTests/errors/version-sets-3.cabal
Cabal/tests/ParserTests/errors/version-sets-3.errors
Cabal/tests/ParserTests/errors/version-sets-4.cabal
Cabal/tests/ParserTests/errors/version-sets-4.errors
Cabal/tests/ParserTests/regressions/version-sets.cabal
Cabal/tests/ParserTests/regressions/version-sets.expr
Cabal/tests/ParserTests/regressions/version-sets.format

I've found the `^>=` operator to be quite verbose to use when I am supporting multiple ghcs (or stackage snapshots). I found this cool post from ages ago https://www.reddit.com/r/haskell/comments/7tykqi/should_stackage_ignore_version_bounds/dtgp0v0 which looked good. e.g.
```
build-depends: network ^>= { 2.6.3.6, 2.7.0.2, 2.8.0.0, 3.0.1.0 }
```
I don't know how to write a test. Somebody please help?
---

caret operator accepts a set of versions

---

Cabal/Cabal.cabal
Cabal/Distribution/PackageDescription/Parsec.hs
Cabal/Distribution/Types/ModuleRenaming.hs
Cabal/doc/file-format-changelog.rst
Cabal/tests/HackageTests.hs
Cabal/tests/ParserTests.hs
Cabal/tests/ParserTests/errors/mixin-1.cabal
Cabal/tests/ParserTests/errors/mixin-1.errors
Cabal/tests/ParserTests/errors/mixin-2.cabal
Cabal/tests/ParserTests/errors/mixin-2.errors
Cabal/tests/ParserTests/regressions/mixin-1.cabal
Cabal/tests/ParserTests/regressions/mixin-1.expr
Cabal/tests/ParserTests/regressions/mixin-1.format
Cabal/tests/ParserTests/regressions/mixin-2.cabal
Cabal/tests/ParserTests/regressions/mixin-2.expr
Cabal/tests/ParserTests/regressions/mixin-2.format
Cabal/tests/ParserTests/regressions/mixin-3.cabal
Cabal/tests/ParserTests/regressions/mixin-3.expr
Cabal/tests/ParserTests/regressions/mixin-3.format

Rebased to current (2019-03-02) `master`
Unconflicts and improves over https://github.com/haskell/cabal/pull/5293

Piyush whitespace issue

---

Cabal/tests/HackageTests.hs
Cabal/tests/UnitTests.hs
Cabal/tests/UnitTests/Distribution/Simple/Utils.hs
validate.sh

- `unit-tests` take optional `--with-ghc` for a single test
- `hackage-tests` respect `CABAL_CONFIG`

Make Cabal tests environment configurable

---

Cabal/ChangeLog.md
Cabal/Distribution/Simple/Configure.hs
Cabal/Distribution/Simple/Utils.hs

The config-state header is a human readable line prepended to the
binary serialisation which looks like
Saved package config for pkgname-1.2.3 written by Cabal-2.5.0.0 using ghc-8.6
However, the functions generating and parsing this header didn't take into
account that package names are not limited to the ASCII subset and blindly used
the ByteString `pack` function which truncates away the high bits of the `Char`
code point resulting in a corrupted header with a non-sensical package-name.
The fix is simply to serialise the package-name with the UTF-8 encoding which
works nicely with the rest of the UTF-8 unaware string handling functions.
Hence the fix is a lot shorter than this commit message.
Fixes #2557

Fix corrupted config file header for non-ASCII package names

---

cabal-install/bash-completion/cabal

* ran `shellcheck` (a bash linter) on `./`
* add `shopt -s nullglob` to `_cabal_list_targets`
tested manually (tabbing in a bash shell) and via `shellcheck`.
---

fix « cabal »'s bash-completion (see issue #5927)

---

cabal-install/Distribution/Client/CmdInstall.hs
cabal-install/Distribution/Client/Setup.hs

Fixes #5788 by
- adding `--ghc-options` (actually the full suite of configure-related options
already available to other `v2-*` commands, but `--ghc-options` is the one
most folks care about)
- prefixing haddock related options with `haddock-`
The fact that `Distribution.Client.Setup` and `Distribution.Simple.Setup` both
export a bunch of functions that are identically named _and_ have similar
functionality is probably going to continue to cause bugs of this sort...
---

Fix some `v2-install` options

---

Cabal/doc/nix-local-build.rst
cabal-install/Distribution/Client/CmdBench.hs
cabal-install/Distribution/Client/CmdBuild.hs
cabal-install/Distribution/Client/CmdConfigure.hs
cabal-install/Distribution/Client/CmdExec.hs
cabal-install/Distribution/Client/CmdFreeze.hs
cabal-install/Distribution/Client/CmdHaddock.hs
cabal-install/Distribution/Client/CmdInstall.hs
cabal-install/Distribution/Client/CmdInstall/ClientInstallFlags.hs
cabal-install/Distribution/Client/CmdRepl.hs
cabal-install/Distribution/Client/CmdRun.hs
cabal-install/Distribution/Client/CmdTest.hs
cabal-install/Distribution/Client/CmdUpdate.hs
cabal-install/Distribution/Client/Config.hs
cabal-install/Distribution/Client/InstallSymlink.hs
cabal-install/Distribution/Client/ProjectConfig/Legacy.hs
cabal-install/Distribution/Client/ProjectConfig/Types.hs
cabal-install/Distribution/Client/ProjectPlanning.hs
cabal-install/Distribution/Client/Setup.hs
cabal-install/README.md
cabal-install/bootstrap.sh
cabal-install/cabal-install.cabal
cabal-install/cabal-install.cabal.pp
cabal-install/changelog
cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs

TODOs:
Closes #5644
Closes #5837
Closes #5843
/cc @hvr

bindir-method/install-method, installdir, new-install flags in SavedConfig -- 3.0 version

---

Cabal/doc/nix-local-build.rst
cabal-install/Distribution/Client/CmdBench.hs
cabal-install/Distribution/Client/CmdBuild.hs
cabal-install/Distribution/Client/CmdConfigure.hs
cabal-install/Distribution/Client/CmdExec.hs
cabal-install/Distribution/Client/CmdFreeze.hs
cabal-install/Distribution/Client/CmdHaddock.hs
cabal-install/Distribution/Client/CmdInstall.hs
cabal-install/Distribution/Client/CmdInstall/ClientInstallFlags.hs
cabal-install/Distribution/Client/CmdRepl.hs
cabal-install/Distribution/Client/CmdRun.hs
cabal-install/Distribution/Client/CmdTest.hs
cabal-install/Distribution/Client/CmdUpdate.hs
cabal-install/Distribution/Client/Config.hs
cabal-install/Distribution/Client/InstallSymlink.hs
cabal-install/Distribution/Client/ProjectConfig/Legacy.hs
cabal-install/Distribution/Client/ProjectConfig/Types.hs
cabal-install/Distribution/Client/ProjectPlanning.hs
cabal-install/cabal-install.cabal
cabal-install/cabal-install.cabal.pp
cabal-install/changelog
cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs

Backport of #5870
TODOs:
/cc @hvr

bindir-method, copy-bindir, new-install flags in SavedConfig -- 2.4 version

---

Cabal/Distribution/Simple/Glob.hs

[ci skip]
Haddock only change and it compiles locally.
---

Improve the globbing Haddocks.

---

appveyor.yml

The new `cabal-head` packages now automatically detect AppVeyor and set the required paths. (You can see this in the build log)
also use AppVeyor time better by not building branches to open PRs since the PR itself is also built.
I play to push this out to the stable branch with the next `cabal-install` release.

Tidy up AppVeyor slightly

---

Cabal/doc/nix-local-build.rst

Fix some markdown in the local builds docs

---

cabal-install/Distribution/Client/Setup.hs

In Cabal-1.22.0 this flag was temporarily removed, but it was added back
in Cabal-1.22.1.0.
Resolves #5946
---

Don't pass --{disable,enable}-executable-profiling to lib:Cabal-1.22.0

---

cabal-install/main/Main.hs

Fix comment to avoid haddock parsing error

---

cabal-install/Distribution/Client/ProjectOrchestration.hs
cabal-install/Distribution/Client/Types.hs
cabal-install/changelog

See https://mail.haskell.org/pipermail/ghc-devs/2019-March/017351.html for discussion about this default.
---

Disable .ghc-environment file generation by default

---

Cabal/Distribution/Compat/Prelude.hs
Cabal/Distribution/Simple/InstallDirs.hs
Cabal/Distribution/Simple/PreProcess/Unlit.hs
Cabal/Distribution/Simple/Program/GHC.hs
Cabal/Distribution/Simple/Test/LibV09.hs
Cabal/tests/UnitTests/Distribution/Version.hs
cabal-install/Distribution/Client/Compat/Prelude.hs
cabal-install/Distribution/Deprecated/Text.hs
cabal-install/main/Main.hs

Motivated by failing test, which now gives more hints why it failed:
```
panic! read @TestSuiteLog ""
error, called at ./Distribution/Simple/Test/LibV09.hs:127:34 in Cabal-3.0.0.0-inplace:Distribution.Simple.Test.LibV09
runTest, called at ./Distribution/Simple/Test.hs:69:19 in Cabal-3.0.0.0-inplace:Distribution.Simple.Test
doTest, called at ./Distribution/Simple/Test.hs:115:24 in Cabal-3.0.0.0-inplace:Distribution.Simple.Test
```

Don't export 'read': panic explicitly

---

Cabal/ChangeLog.md
Cabal/Language/Haskell/Extension.hs

This was added in GHC 8.4 but apparently either no-one's missed its
absence since then, or users have been suffering in silence with the
warnings.
---

Add EmptyDataDeriving as an Extension constructor.

---

cabal-install/Distribution/Solver/Types/ComponentDeps.hs

We require `containers > 0.5.6.2` now.
---

Fix a TODO.

---

.github/PULL_REQUEST_TEMPLATE.md

PR template: Fix link to coding conventions

---

Cabal/Distribution/Simple/Setup.hs
Cabal/Distribution/Simple/Test/ExeV10.hs
Cabal/Distribution/Simple/Test/LibV09.hs
Cabal/doc/installing-packages.rst
cabal-install/Distribution/Client/Config.hs
cabal-install/Distribution/Client/Install.hs
cabal-install/Distribution/Client/ProjectBuilding.hs
cabal-install/Distribution/Client/ProjectConfig/Legacy.hs
cabal-install/Distribution/Client/ProjectConfig/Types.hs
cabal-install/Distribution/Client/ProjectPlanning.hs
cabal-install/Distribution/Client/ProjectPlanning/Types.hs
cabal-install/Distribution/Client/Setup.hs
cabal-install/changelog
cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs

Sometimes we need to run the test ins some prebuild context, for
these cases we now allow a script/application to be passed as
`--test-wrapper`, which will obtain the execution arguments and
be responsible for running the test in the environment.
A test-wrapper could for example do the following to execute a
test through wine:
```
set -euo pipefail
WINEDLLOVERRIDES="winemac.drv=d" \
WINEDEBUG=-all+error \
LC_ALL=en_US.UTF-8 \
WINEPREFIX=$(mktemp -d) \
/path/to/bin/wine64 $@*
```
---

Add test-wrapper option to wrap test execution

---

Cabal/Distribution/Compat/Semigroup.hs
Cabal/Distribution/Simple.hs
Cabal/Distribution/Simple/Program/GHC.hs
Cabal/Distribution/Simple/Setup.hs

Both will be deprecated in GHC 8.8.
This is part of https://gitlab.haskell.org/ghc/ghc/merge_requests/842.

Stop using Data.Monoid.{First,Last}

---

Cabal/Distribution/Simple/Register.hs

Local packages may have include heades in
- `inplaceDir </> d` (bundled, in source tree)
- `inplaceDir </> libTargetDir </> d` (autogenerated, somewhere in
builddir)
We need both, for dependant packages to work.
The simple reproduce case is to have `unix` and `process`
locally in the project and try to build `process` (which depends on `unix` and its `HsUnixConfig.h`)
--- 
This addresses 
- https://github.com/haskell/cabal/issues/5223#issuecomment-381571846
- https://github.com/haskell/cabal/issues/5223#issuecomment-490229741

Add autogen include directories for inplace packages

---

cabal-install/Distribution/Client/Security/HTTP.hs

I added `[ci skip]` to the commit message because I only added a single space to a string. I didn't do any further testing either. Feel free to point out any steps I need to take since this *is* a user-facing message.
---
* [x ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [x ] Any changes that could be relevant to users have been recorded in the changelog.
* [x ] The documentation has been updated, if necessary.
* [x ] If the change is docs-only, `[ci skip]` is used to avoid triggering the build bots.

Fix typo in "Unexpected response" message

---

Cabal/Distribution/Simple/Build/PathsModule.hs
Cabal/Distribution/Simple/Install.hs
Cabal/Distribution/Simple/LocalBuildInfo.hs

The generated datadir path can be incorrect if a project is configured for a single component as per https://github.com/haskell/cabal/issues/5862
Since the install command uses the non-component variant of the paths for the datadir, https://github.com/haskell/cabal/blob/27ef964abfa78e9b2013e51bd197f6c2321a36d0/Cabal/Distribution/Simple/Install.hs#L98-L114 this patch changes the generated path to use the same function.
---

Fix datadir path in generated `Paths_` file

---

cabal-install/Distribution/Client/CmdErrorMessages.hs

Suggest adding '--enable-tests'. [ci skip]
---

Improve error message for 'new-test' command

---

Cabal/Distribution/Simple/SrcDist.hs

Previously we would look at directly at the sDistDistPref flag. However,
this may not be set, resulting in #6068. We should rather be using
findDistPrefOrDefault to find the DistPref directory.
---

Simple.SrcDist: Fix search for DistPref

---

Cabal/Cabal.cabal
Cabal/ChangeLog.md
Cabal/Distribution/Compat/Parsing.hs
Cabal/Distribution/Compat/Prelude.hs
Cabal/Distribution/Compat/Semigroup.hs
Cabal/Distribution/Fields/ConfVar.hs
Cabal/Distribution/PackageDescription/Configuration.hs
Cabal/Distribution/Types/PkgconfigVersionRange.hs
Cabal/Distribution/Types/VersionRange/Internal.hs

This is a proof of concept for depending on `semigroups` instead of defining a fake local `class Semigroup` as suggested in https://github.com/haskell/cabal/issues/6082#issuecomment-502598220
/cc @phadej
---

Replace fake `Semigroup`/`NonEmpty` with proper ones from `semigroups`

---

cabal-install/Distribution/Client/CmdBench.hs
cabal-install/Distribution/Client/CmdBuild.hs
cabal-install/Distribution/Client/CmdConfigure.hs
cabal-install/Distribution/Client/CmdExec.hs
cabal-install/Distribution/Client/CmdFreeze.hs
cabal-install/Distribution/Client/CmdHaddock.hs
cabal-install/Distribution/Client/CmdInstall.hs
cabal-install/Distribution/Client/CmdRepl.hs
cabal-install/Distribution/Client/CmdRun.hs
cabal-install/Distribution/Client/CmdSdist.hs
cabal-install/Distribution/Client/CmdTest.hs
cabal-install/Distribution/Client/CmdUpdate.hs
cabal-install/Distribution/Client/ProjectOrchestration.hs
cabal-install/changelog

Still needs to go in the changelog, also fixes the issue where Haddock failures don't make `v2-haddock` error out.
Fixes #5641.
---

Add proper error reporting for v2-install

---

cabal-install/Distribution/Client/Get.hs

---
Tested locally, I'd like to try to add tests for get, though.
closes #6053

Unpack in existing directory if empty

---

Cabal/Cabal.cabal
Cabal/Distribution/Simple.hs
Cabal/Distribution/Simple/Build.hs
Cabal/Distribution/Simple/Setup.hs
Cabal/Distribution/Simple/ShowBuildInfo.hs
Cabal/Distribution/Simple/UserHooks.hs
Cabal/Distribution/Simple/Utils/Json.hs

This is the lib:Cabal part extracted from PR #5954 by @fendor and squashed into two commits.
---

show-build-info (lib:Cabal part)

---

Cabal/Distribution/Simple/Configure.hs
Cabal/Distribution/Simple/Setup.hs
Cabal/Distribution/Types/InstalledPackageInfo.hs
Cabal/Distribution/Types/InstalledPackageInfo/FieldGrammar.hs
Cabal/tests/ParserTests/ipi/internal-preprocessor-test.expr
Cabal/tests/ParserTests/ipi/internal-preprocessor-test.format
Cabal/tests/ParserTests/ipi/issue-2276-ghc-9885.expr
Cabal/tests/ParserTests/ipi/issue-2276-ghc-9885.format
Cabal/tests/ParserTests/ipi/transformers.expr
Cabal/tests/ParserTests/ipi/transformers.format
cabal-install/Distribution/Client/Config.hs
cabal-install/Distribution/Client/ProjectConfig/Legacy.hs
cabal-install/Distribution/Client/ProjectPlanning.hs
cabal-testsuite/PackageTests/ConfigureComponent/SubLib/setup-explicit-fail.out
cabal-testsuite/PackageTests/ConfigureComponent/SubLib/setup-explicit.test.hs
cabal-testsuite/PackageTests/MultipleLibraries/cabal.out
cabal-testsuite/PackageTests/MultipleLibraries/cabal.project
cabal-testsuite/PackageTests/MultipleLibraries/cabal.test.hs
cabal-testsuite/PackageTests/MultipleLibraries/d/d.cabal
cabal-testsuite/PackageTests/MultipleLibraries/p/p.cabal

This will make Cabal error out when depending on a private library.
It does not give detailed info on which sublibrary is the culprit because that would require changing the `dependencySatisfiable` and `finalizePD` return types, and that touches A LOT of the codebase. It can be done later.
/cc @ezyang @phadej
TODO:
Closes #5806

Prevent dependency on private library

---

Cabal/ChangeLog.md
Cabal/Distribution/PackageDescription/Check.hs
cabal-testsuite/PackageTests/Backpack/Includes2/cabal-internal.out
cabal-testsuite/PackageTests/BuildTools/Internal/cabal.out
cabal-testsuite/PackageTests/InternalVersions/BuildDependsExtra/setup.cabal.out
cabal-testsuite/PackageTests/InternalVersions/BuildDependsExtra/setup.out
cabal-testsuite/PackageTests/InternalVersions/BuildDependsExtra/setup.test.hs
cabal-testsuite/PackageTests/Regression/T5309/cabal.out
cabal-testsuite/PackageTests/Regression/T5677/cabal.out
cabal-testsuite/PackageTests/TestSuiteTests/ExeV10/cabal.out

See #5119 and #6085. We didn't fix this properly in time for 3.0, so need to apply the same hack again.
Fixes #6085.

3.0 port of the 2.4 #5119 hack

---

Cabal/ChangeLog.md
Cabal/Distribution/Simple/Configure.hs
Cabal/Distribution/Simple/Setup.hs
Cabal/doc/nix-local-build.rst

Fixes #2702
If you enable `debug-info` then you also have to stop the libraries and
executables being stripped as otherwise the debug symbols are removed.
---

Make `debug-info` >= 1 imply library/executable-stripping: False

---

Cabal/ChangeLog.md
Cabal/Distribution/Simple/Install.hs
cabal-testsuite/PackageTests/Regression/T6125/Main.hs
cabal-testsuite/PackageTests/Regression/T6125/data/foo/bar.html
cabal-testsuite/PackageTests/Regression/T6125/myprog.cabal
cabal-testsuite/PackageTests/Regression/T6125/setup.cabal.out
cabal-testsuite/PackageTests/Regression/T6125/setup.out
cabal-testsuite/PackageTests/Regression/T6125/setup.test.hs

Treating globs like filenames was always illegitimate, but this code
was broken further by the addition of recursive globs.
I had a look around for other dubious code along these lines, and it
looks like this site is the only problematic one.
Fixes #6125.
---

Make `Setup.hs copy/install` work when data-files uses **.

---

cabal-install/Distribution/Client/CmdRun.hs
cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptLiterate/cabal.out
cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptLiterate/cabal.project
cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptLiterate/cabal.test.hs
cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptLiterate/script.cabal
cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptLiterate/script.lhs

A lite variant, without additional syntax. There's codepath so we could add it, if we comeup with something good. Until then `\iffalse` (by @23Skidoo ) idiom is IMHO good enough.
```latex
\iffalse
{- cabal:
build-depends: base >= 4.3 && <5
-}
\fi
\documentclass{article}
\begin{document}
\begin{code}
{-# LANGUAGE BangPatterns #-}
{-# LANGUAGE ScopedTypeVariables #-}
import Prelude
main :: IO ()
main = putStrLn "Hello World"
\end{code}
\end{document}
```
EDIT: there's no new syntax, so I hope this is an uncontroversial change.

cabal run works with Literate Haskell file

---

cabal-install/Distribution/Client/Config.hs
cabal-install/Distribution/Client/ProjectConfig/Legacy.hs
cabal-install/Distribution/Deprecated/ParseUtils.hs
cabal-install/changelog
cabal-testsuite/PackageTests/UserConfig/cabal.out
cabal-testsuite/PackageTests/UserConfig/cabal.test.hs

This changes parsing of cabal config files to be more uniform with parsing of cabal project files.
Specifically,  "extra-include-dirs", "extra-lib-dirs", "extra-framework-dirs", "extra-prog-path", and "configure-options" are now parsed as comma separated fields rather than single strings. This should resolve #5420 by making the syntax for this portable across systems. It is an alternative approach to #6155. Rather than writing multiple lines in config files, it brings the parsing and printing into accord by allowing parsing of comma separation (which the emitting already assumes is possible).
The entire config parser stuff is pretty antiquated and needs a full rewrite. In the meantime, this just "patches" the parsing after the fact. It makes use of the same parsers as for cabal project …

Parse list fields in cabal config file

---

Cabal/ChangeLog.md
Cabal/Distribution/Simple/GHC.hs

Tentative. Fixes #4925
Based on #5446; that one should be merged first and then this one rebased.
To review, only review the top commits (this change is much smaller than it looks here).

Pass `ld-options` through to GHC

---

Cabal/doc/nix-local-build.rst

Someone mentioned this section was confusing in #haskell. I added an
example of command line usage so there is no confusion.
[ci skip]
P.s.: I expected `templated path` to be a link to a section explaining how these templates work and what templating variables are available. Should I open up an issue on this?
---

Improve docs for html-location

---

cabal-install/Distribution/Client/CmdInstall.hs

Commit 273dacf ("Extract installLibraries and InstallExes from
installAction") makes 'getInstalledPackages' get passed the
pre-`configCompilerEx` ProgramDb which will cause pattern match failures when
the code tries to lookup ghc-pkg in the progdb.
As far as I can tell on master currently any `v2-install` invocation would fail with 
```
Distribution/Simple/GHC.hs:1967:5-56: Irrefutable pattern failed for pattern Just ghcPkgProg
```
but I only tested with `cabal v2-install --lib Cabal-3.0.0.0`.
---

Fix v2-install ProgramDb confusion

---

cabal-install/Distribution/Client/ProjectPlanning.hs
release-checklist.md

This should be straight-forward and backported to `3.0` branch

New ghc version

---

Cabal/doc/developing-packages.rst

I replaced the note about `hs-source-dir` being deprecated in the
description of `hs-source-dirs` by a field of its own to include the
`deprecated` and `removed` fields because it's no longer in 3.0.
Source directories can be shared among components but there's a
non-obvious caveat which I've tried to clarify with a note for `hs-source-dirs`.
This definitely needs review because I'm not sure I understood it and whether I'm getting the point across.
---

Document hs-source-dirs

---

Cabal/doc/nix-local-build.rst

Documents the deficiency from https://github.com/haskell/cabal/issues/6005 in the user manual. In the event that the issue does not get fixed for some time, documenting this should help prevent people from wasting space on hackage by uploading packages that no build tool can currently build.

Warn that dependencies using backpack are broken when installed from hackage

---

Cabal/Distribution/Types/ExeDependency.hs

This is tricky: There are no `happy :happy` (note the space) uses of `build-tool-depends` on Hackage, so if we are quick to make Cabal-3.0.x.y with this patch and deploy `hackage-server` using it, it can be as simple as this.
Note: this is different than with spaces in `mixins` as here I'm *restricting* the grammar: existing `cabal-install` / tools using old `Cabal` will continue to work fine.
Edit: look at the `Make ExeDependency parser stricter` commit to see how the example output change.

Exe dependency less lexeme

---

Cabal/Cabal.cabal
Cabal/Distribution/Compat/FilePath.hs
Cabal/Distribution/Simple/Utils.hs
Cabal/tests/UnitTests/Distribution/Simple/Utils.hs

On Windows dropExeExtension doesn't actually drop the exe extension.
We have
splitExtension "foo.exe" == ("foo", ".exe")
but the code is expecting just `"exe"` for the extension field.
Among other things this makes `guessToolFromGhcPath` behave
unexpectedly. Since `takeVersionSuffix` can't see past the extension the
`null suf` case in `mkGuesses` will trigger which causes the versioned
program path candidates to not be looked for.
---

Fix dropExeExtension on Windows

---

cabal-install/Distribution/Client/CmdInstall.hs

It should fix #5925 and help to fix https://github.com/DanielG/cabal-helper/issues/83
Tested manually running the command and check that the package env file contains the custom `store-dir`:
```shell
PS D:\dev\ws\haskell\cabal-test> cabal install --lib --package-env .
Wrote tarball sdist to
D:\dev\ws\haskell\cabal-test\dist-newstyle\sdist\cabal-test-0.1.0.0.tar.gz
Up to date
PS D:\dev\ws\haskell\cabal-test> type .\.ghc.environment.x86_64-mingw32-8.6.5
clear-package-db
global-package-db
package-db C:\Users\atrey\AppData\Roaming\cabal\store\ghc-8.6.5\package.db
package-id ghc-8.6.5
....
PS D:\dev\ws\haskell\cabal-test> D:\bin\cabals\3.1.0.0\cabal install --lib --package-env .
Wrote tarball sdist to …
```

Correct store-dir dir in ghc env files generated by `cabal install --lib --package-env`

---

travis/upload.sh

Fixes #6324
Tested in my fork.

CI: Add travis_retry when uploading binaries to S3

---

.travis.yml

But then exclude builds in forks from the notifications.
In terms of testing, the `if` condition I'm fairly confident about, as it's a simpler version of a version I use at work.  Also it triggered https://travis-ci.com/dwijnand/cabal/builds/133725400 to build.
Regarding the notification changes, I believe them to be correct, using https://docs.travis-ci.com/user/notifications#conditional-notifications as reference.  However, using https://config.travis-ci.com/explore it complains that:
[alert] on notifications.slack.rooms: expected an encrypted string
So perhaps someone should double-check that builds are still notified if this PR lands.
(Btw, I'm getting a "Failed! token_revoked" error message when trying to use https://haskell-cabal.herokuapp.com/.  May I join the Slack team some other …

.travis.yml: Allow forks to build

---

Cabal/Distribution/Simple/Program/GHC.hs

Fixes #5103.
I tested this change by locally building cabal-install, running it in a project whose `test-suite` has `other-modules` and asserting that the main module was in scope in the REPL.  I would love to make that a test, but I would need a little guidance (and/or prior art).
I'm also not sure if this is changelog worthy and/or if there is documentation to change or add to.  Please advise as I'd be happy to add these.
More generally, this is my first cabal PR (edit: nvm, second, after #5943 🙂) and I'm still ramping up in Haskell, so any feedback is welcome.

Start GHCi with the main module in scope

---

cabal-install/Distribution/Client/CmdInstall.hs
cabal-install/Distribution/Client/InstallSymlink.hs

Previously, the flags --program-suffix and --program-prefix
were ignored when given to v2-install.
To fix this, both installation cases, symlink and copy need to be
aware of the new installation name.
Closes #6179 
---

Honour suffix and prefix on install

---

validate.sh

In recent versions of cabal-plan the --builddir= flag has become a
non-global flag; i.e. it needs to be placed after the sub-command rather
than before.
`validate.sh` isn't tested in CI so...
[ci skip]
Tested on... phadej's machine.
Fixes #6332

validate.sh: Fix cabal-plan invocation

---

cabal-install/tests/UnitTests/Distribution/Client/VCS.hs

I haven't understood 100%, but something about having the following in
my ~/.gitconfig:
[tag]
gpgsign = true
forceSignAnnotated = true
means that creating these tags block on my editor exiting and providing
the annotated tag commit message.  I also didn't investigate all the
options, but I tested that this one fixes the issue for me.
Tested by running `validate.sh`.

tests: avoid blocking on git tagging

---

cabal-install/Distribution/Client/SourceFiles.hs
cabal-testsuite/PackageTests/Regression/T6334/cabal.out
cabal-testsuite/PackageTests/Regression/T6334/cabal.project
cabal-testsuite/PackageTests/Regression/T6334/cabal.test.hs
cabal-testsuite/PackageTests/Regression/T6334/foo/README.md
cabal-testsuite/PackageTests/Regression/T6334/foo/foo.cabal
cabal-testsuite/PackageTests/Regression/T6334/foo/src/Foo.hs

Revert "Properly expand globs when looking for headers in extra-src-files."
This reverts commit 3b54835cc6ac756c09e3809254c3213e09947180.
cc @quasicomputational

Add regression test, and resolve #6334

---

.travis.yml

.travis.yml: Add fast_finish to get build status faster

---

validate.sh

Previously this would work until CABAL_TESTSUITE_BDIR was needed, at
which point it would fail because it looked for things under
.../ghc-8.6/... while cabal v2-build actually put them in
.../ghc-8.6.5/...
Hard-coding "ghc" is unfortunate, but I didn't know if there was an easy
way to avoid it.  I also didn't want to over-complicate it, until it was
necessary.
validate.sh isn't tested in CI so...
[ci skip]
Tested by running `validate.sh`.

validate.sh: Allow using short-version ghc binaries, like ghc-8.6

---

Cabal/Cabal.cabal
Cabal/Distribution/Simple/Program/GHC.hs
Cabal/tests/UnitTests.hs
Cabal/tests/UnitTests/Distribution/Simple/Program/GHC.hs

cc @merijn
I don't think `-fshow-docs-of-hole-fits` is the only non-trivial safe-to-omit flag. I'm not stressing about this too much, as situation may be improved.

Add GHC-8.8 flags to normaliseGhcFlags (with test)

---

.travis.yml
CONTRIBUTING.md

They don't seem to have worked for a long time nor is there a relevant presence of Cabal devs on Slack.

Remove Slack notifications

---

cabal-install/Distribution/Client/ProjectBuilding.hs

It's probably silent assumption that `setup Cabal.copyCommand`
would create directory structure. Who said it would do that.
For empty packages, sometimes it doesn't.
It's easier to be defensive here
---
I didn't write any test, I'll take a blame for that, I did test locally though.
---
```
% ghc-pkg --package-db=/cabal/store/ghc-8.6.5/package.db describe snap-app-0.7.0
name: snap-app
version: 0.7.0
id: snap-app-0.7.0-69381acbcfc33e2f42e1fee72b15c9d7d1d268b1e258f52f29e71a36232fc0bb
key: snap-app-0.7.0-69381acbcfc33e2f42e1fee72b15c9d7d1d268b1e258f52f29e71a36232fc0bb
license: BSD-3-Clause
author: None
synopsis: None
description:
None
abi: daffb3201b734bc0c941cb76f1ff3f3e
exposed: True
data-dir: /cabal/store/ghc-8.6.5/snap-app-0.7.0-69381acbcfc33e2f42e1fee72b15c9d7d1d268b1e258f52f29e71a36232fc …
```

Fix #4130: Create incoming directory

---

.docker/validate-7.6.3.dockerfile
.docker/validate-8.6.5.dockerfile
.docker/validate-8.8.1.dockerfile
Makefile
cabal-testsuite/Test/Cabal/Monad.hs
cabal-testsuite/Test/Cabal/Prelude.hs
cabal-testsuite/main/cabal-tests.hs

In short, this allows to run `make validate-in-docker-8.8.1`, which is nice.

Validate rearrangements

---

cabal-testsuite/cabal-testsuite.cabal
solver-benchmarks/solver-benchmarks.cabal
travis-common.sh
validate.sh

Similar change is done in 3.0 branch already.

Freeze the versions of cabal-testsuite and solver-benchmarks

---

Cabal/Distribution/InstalledPackageInfo.hs
Cabal/Distribution/Simple/HaskellSuite.hs
Cabal/Distribution/Simple/Program.hs
Cabal/Distribution/Simple/Program/HcPkg.hs
Cabal/Distribution/Simple/Program/Run.hs
Cabal/Distribution/Simple/Program/Script.hs
Cabal/Distribution/Simple/Utils.hs
Cabal/Distribution/Utils/IOData.hs
Cabal/tests/ParserTests.hs
Cabal/tests/UnitTests/Distribution/Simple/Utils.hs
cabal-install/Distribution/Client/HttpUtils.hs
cabal-install/Distribution/Client/Install.hs
cabal-install/Distribution/Client/ProjectBuilding.hs

Based on #6364 
Parsing the `ghc-dump` is now two times faster and uses less memory.
For big cabal nix-stores this speedup is noticeable:
```haskell
{- ghc-pkg --simple-output
%  time ghc-pkg-8.6.5 --package-db=/cabal/store/ghc-8.6.5/package.db list --simple-output | wc 
1    4473   82025
ghc-pkg-8.6.5 --package-db=/cabal/store/ghc-8.6.5/package.db list --simple-output  2,40s user 0,06s system 99% cpu 2,457 total
wc  0,00s user 0,00s system 0% cpu 2,457 total
-}
{- This script BEFORE THE CHANGE
% time runghc GhcPkgScript.hs ghc-pkg-8.6.5 /cabal/store/ghc-8.6.5/package.db | wc
Loaded package environment from /home/phadej/.ghc/x86_64-linux-8.6.5/environments/default
4473    4473  372073
runghc GhcPkgScript.hs ghc-pkg-8.6.5 /cabal/store/ghc-8.6.5/package.db  13,34s user 1,22s system 100% cpu …
```

IOData improvements and faster ghc-pkg dump parsing

---

Cabal/Distribution/FieldGrammar.hs
Cabal/Distribution/FieldGrammar/Class.hs
Cabal/Distribution/FieldGrammar/FieldDescrs.hs
Cabal/Distribution/FieldGrammar/Parsec.hs
Cabal/Distribution/FieldGrammar/Pretty.hs
Cabal/Distribution/InstalledPackageInfo.hs
Cabal/Distribution/ModuleName.hs
Cabal/Distribution/PackageDescription/Check.hs
Cabal/Distribution/PackageDescription/FieldGrammar.hs
Cabal/Distribution/PackageDescription/Parsec.hs
Cabal/Distribution/Simple/Haddock.hs
Cabal/Distribution/Types/InstalledPackageInfo.hs
Cabal/Distribution/Types/InstalledPackageInfo/FieldGrammar.hs
Cabal/Distribution/Types/InstalledPackageInfo/Lens.hs
Cabal/Distribution/Types/PackageDescription.hs
Cabal/Distribution/Types/PackageDescription/Lens.hs
Cabal/Distribution/Utils/ShortText.hs
Cabal/tests/HackageTests.hs
Cabal/tests/Instances/TreeDiff.hs
Cabal/tests/UnitTests/Distribution/Utils/Structured.hs
Makefile
cabal-install/Distribution/Client/Init/Heuristics.hs
cabal-install/Distribution/Client/List.hs
cabal-install/solver-dsl/UnitTests/Distribution/Solver/Modular/DSL.hs

Based on #6366 
For benchmarks see https://oleg.fi/shorttext-benchmarks.html
- synthetic `hackage-tests`: no difference
- `Distribution.Simple.Program.HcPkg.dump`: faster and less memory usage
- there's still plenty of `(:)` due `FilePath`s (my hypothesis)
- `cabal build --dry all` in large-ish project: same time, but less residency

Use ShortText in IPI

---

.docker/validate-7.10.3.dockerfile
.docker/validate-7.6.3.dockerfile
.docker/validate-7.8.4.dockerfile
.docker/validate-8.0.2.dockerfile
.docker/validate-8.2.2.dockerfile
.docker/validate-8.4.4.dockerfile
.docker/validate-8.6.5.dockerfile
.docker/validate-8.8.1.dockerfile
.dockerignore
Cabal/Cabal.cabal
Cabal/ChangeLog.md
Cabal/Distribution/Compat/FilePath.hs
Cabal/Distribution/PackageDescription/Check.hs
Cabal/Distribution/Simple/Program/GHC.hs
Cabal/Distribution/Simple/Utils.hs
Cabal/tests/UnitTests/Distribution/Simple/Utils.hs
Makefile
cabal-testsuite/Test/Cabal/Monad.hs
cabal-testsuite/Test/Cabal/Prelude.hs
cabal-testsuite/main/cabal-tests.hs
validate.sh

Backporting to 3.0

---

cabal-install/Distribution/Client/CmdInstall.hs
cabal-install/Distribution/Client/CmdInstall/ClientInstallFlags.hs
cabal-install/Distribution/Client/CmdRepl.hs
cabal-install/Distribution/Client/Config.hs
cabal-install/Distribution/Client/ProjectConfig.hs
cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs

Resolve #5919
Resolve #6410
Add `withProjectOrGlobalConfigIgn` to unify the behaviour with `-z` in `cabal
repl`

Implement cabal install -z

---

cabal-install/Distribution/Client/ProjectOrchestration.hs

Now there's a warning
```
Warning: There are no packages or optional-packages in the project
cabal: There is no <pkgname>.cabal package file or cabal.project file. To
build packages locally you need at minimum a <pkgname>.cabal file. You can use
'cabal init' to create one.
For non-trivial projects you will also want a cabal.project file in the root
directory of your project. This file lists the packages in your project and
all other build configuration. See the Cabal user guide for full details.
```
It's subtle, but that's the issue with how we output warnings, not the warning itself.
I'm only making it a warning at this point, as I'm not 100% sure if that setup may still be useful for something. Playing safe for 3.2

Resolve #6013: Warn if packages and optional-packages are both empty

---

cabal-install/Distribution/Client/InstallPlan.hs

Related issues are https://github.com/haskell/cabal/issues/6437
and https://github.com/reflex-frp/reflex/issues/375

Improve few internalErrors in InstallPlan

---

.docker/validate-8.8.1.dockerfile
cabal.project.validate
solver-benchmarks/HackageBenchmark.hs
solver-benchmarks/solver-benchmarks.cabal
validate.sh

One commit on top of #6434 which allows to run benchmarks as part of `validate.sh` (to see that they work).
Probably because of asserts in development version, `cabal-install-3.0.1.0` seems to be slightly faster, on my machine :)
cc @grayjay, I'll merge this when travis turns green.

Grayjay update solver benchmarks

---

cabal-dev-scripts/src/Preprocessor.hs
cabal-install/Distribution/Client/CmdRun.hs
cabal-install/Distribution/Client/CmdRun/ClientRunFlags.hs
cabal-install/cabal-install.cabal
cabal-install/cabal-install.cabal.pp

I tested with meta-command:
```
% cabal run -- cabal run --ignore-project cabal-dev-scripts/src/Preprocessor.hs -- --help
```

Add --ignore-project flag to v2-run

---

Cabal/Distribution/Utils/Structured.hs
Cabal/doc/installing-packages.rst
cabal-install/Distribution/Client/CmdUpdate.hs
cabal-install/Distribution/Client/Config.hs
cabal-install/Distribution/Client/FetchUtils.hs
cabal-install/Distribution/Client/GlobalFlags.hs
cabal-install/Distribution/Client/HashValue.hs
cabal-install/Distribution/Client/IndexUtils.hs
cabal-install/Distribution/Client/PackageHash.hs
cabal-install/Distribution/Client/ProjectConfig.hs
cabal-install/Distribution/Client/ProjectConfig/Legacy.hs
cabal-install/Distribution/Client/ProjectConfig/Types.hs
cabal-install/Distribution/Client/ProjectPlanOutput.hs
cabal-install/Distribution/Client/ProjectPlanning.hs
cabal-install/Distribution/Client/Setup.hs
cabal-install/Distribution/Client/Types.hs
cabal-install/Distribution/Client/Update.hs
cabal-install/cabal-install.cabal
cabal-install/cabal-install.cabal.pp
cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
cabal-install/tests/UnitTests/Distribution/Client/TreeDiffInstances.hs

Resolve #6359
`preferred-versions` are left out for now.
It shouldn't be difficult to add, but needs work nevertheless.
Also change the index cache to use `Distribution.Utils.Structured`,
making Binary instances generically derived.
Almost as a feature generated 01-index.cache is never updated.
If you change the contents of the directory, you have to purge
01-index.cache file yourself.

Implement file+noindex:///local/repositories

---

Cabal/Distribution/PackageDescription/Check.hs
Cabal/Distribution/Simple/Compiler.hs
Cabal/Distribution/Simple/Configure.hs
Cabal/Distribution/Simple/HaskellSuite.hs
Cabal/Distribution/Simple/Utils.hs
Cabal/Distribution/Utils/Generic.hs

So we do with many other stuff

Resolve #6375: Let export safe* from both Utils.Generic and Simple.Utils

---

Cabal/doc/installing-packages.rst

Fixed a typo

---

.docker/validate-7.6.3.dockerfile
.docker/validate-8.8.1.dockerfile
.docker/validate-old.dockerfile
.github/workflows/validate.yml
Makefile
boot/validate.template.yml
cabal-dev-scripts/cabal-dev-scripts.cabal
cabal-dev-scripts/src/GenValidate.hs
cabal.project.validate
cabal.project.validate.libonly
validate.sh

I'm not removing `.travis.yml` just yet. Let's have it on until 3.2 is done.
I'll cleanup the generation (there's todo about documenting it), will do that early 2020 and then merge. Please comment before that. The setup is simpler, but I'm not 100% if it has same the coverage as current travis setup
- *pro* simpler
- *pro* uses `validate.sh`, so you have better chance to reproduce on own machine
- *con* even closer integration with GitHub
- yet, the new setup is less GitHub specific than the current setup is Travis specific, so I guess it's not that bad

Use GitHub Actions

---

Cabal/doc/nix-local-build.rst

Calling `v2-build` by itself doesn't work.  Need `all`.

Doc: v2-building every package requires "all" [ci skip]

---

cabal-install/Distribution/Solver/Modular/Package.hs
cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs
cabal-testsuite/PackageTests/Backpack/Includes2/setup-external.cabal.out
cabal-testsuite/Test/Cabal/OutputNormalizer.hs

This reverts commit fbe7d73e4361134262669a72e72a78bb2d8f023b, reversing
changes made to f6e7cdd60d83d887cafa1385a6df85bd392cfc36.
Fixes #6495 regression. Looks like solver changes conflicted in non-obvious way.

Revert "Merge pull request #6476 from grayjay/issue-5892"

---

cabal-install/Distribution/Solver/Modular/Package.hs
cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs
cabal-testsuite/PackageTests/Backpack/Includes2/setup-external.cabal.out
cabal-testsuite/Test/Cabal/OutputNormalizer.hs

This commit is the same as 96c3bf9121125fd6d316dd97dddd7264cfca736a, but with
the unit tests updated to fix #6495.  The tests check less of the solver output
so that they are less fragile.

Show full ABI hash for installed packages in solver log (fixes #5892).

---

cabal-install/cabal-install.cabal.pp
cabal-install/tests/IntegrationTests2.hs

On Windows moving files fails often enough,
let's try another tactic for recovering modified file.

Try to make test for 3324 more robust

---

cabal-install/tests/IntegrationTests2.hs

If this doesn't work either, then `integration-tests2` needs to allow testing out of the tree, and copy the test-case into temporary directory...

Try to make regression test for 3324 more robust

---

Cabal/Distribution/Simple/Flag.hs
Cabal/doc/nix-local-build.rst
cabal-install/Distribution/Client/CmdInstall.hs
cabal-install/Distribution/Client/CmdInstall/ClientInstallFlags.hs
cabal-install/Distribution/Client/Compat/Directory.hs
cabal-install/Distribution/Client/InstallSymlink.hs
cabal-install/cabal-install.cabal
cabal-install/cabal-install.cabal.pp
cabal-install/changelog

Copy on windows

---

Cabal/Cabal.cabal
Cabal/ChangeLog.md
Cabal/Distribution/Compat/Process.hs
Cabal/Distribution/Simple/Utils.hs
cabal-install/Distribution/Client/SetupWrapper.hs

use process jobs

---

Cabal/Distribution/Simple/Configure.hs

This results e.g. in
cabal: The pkg-config package 'blas' version ==0.3 || >0.3 is required but the
version installed on the system is version 0.2.20+ds
output instead of failing to parse 0.2.20+ds as a PkgconfigVersion.
We don't need to parse the `pkg-config --modversion` output
as strictly as the versions in `.cabal` file.
I.e. at all, as `PkgconfigVersion` comparison works somehow
on any possible version strings.
cc @amigalemming if you want to try this out. I'll backport it to 3.2 branch.
You won't be able to write `+` in `.cabal` file, but at least `Cabal` will accept whatever `pkg-config --modversion` gives it.

Accept any pkg-config --modversion output

---

Cabal/Distribution/Types/Dependency.hs
Cabal/tests/ParserTests/regressions/issue-5846.format
cabal-testsuite/PackageTests/MultipleLibraries/cabal.out

Disallow spaces around colon in Parsec Dependency

---

Cabal/ChangeLog.md
Cabal/Distribution/Simple/Configure.hs
Cabal/Distribution/Types/Dependency.hs
Cabal/Distribution/Types/PkgconfigVersion.hs
Cabal/tests/ParserTests/regressions/issue-5846.format
cabal-testsuite/PackageTests/MultipleLibraries/cabal.out

Backports:
- https://github.com/haskell/cabal/pull/6541
- https://github.com/haskell/cabal/pull/6540
- https://github.com/haskell/cabal/pull/6538

Backport batch 5 3.2

---

cabal-install/Distribution/Client/PackageHash.hs

Only on non-Windows and non-macOS. The unit-ids become a bit longer:
Changes e.g.
component cabal-fmt-0.1.2-ff4d3d1e89ec09722d5bccbf9724beeddb2bd9dcd99a200ff350860e49ecb0f2
include cabal-fmt-0.1.2-3fc69567df6c17a860b37365e18b4b35f7d2e64ffdbab5d91cd775762ae888f1
unit cabal-fmt-0.1.2-ff4d3d1e89ec09722d5bccbf9724beeddb2bd9dcd99a200ff350860e49ecb0f2
include cabal-fmt-0.1.2-3fc69567df6c17a860b37365e18b4b35f7d2e64ffdbab5d91cd775762ae888f1
to
component cabal-fmt-0.1.2-e-cabal-fmt-173382ac142508c938885649c3384b3512c441f46ff13c57cda2f345fe5f0859
include cabal-fmt-0.1.2-l-cabal-fmt-internal-3fc69567df6c17a860b37365e18b4b35f7d2e64ffdbab5d91cd775762ae888f1
unit cabal-fmt-0.1.2-e-cabal-fmt-173382ac142508c938885649c3384b3512c441f46ff13c57cda2f345fe5f0859
include …

Include component name in unit-id

---

Cabal/Distribution/Compat/CopyFile.hs
Cabal/Distribution/Compat/CreatePipe.hs
Cabal/Distribution/Compat/Environment.hs
Cabal/Distribution/Compat/GetShortPathName.hs
Cabal/Distribution/Compat/Prelude.hs
Cabal/Distribution/Compat/Time.hs
Cabal/Distribution/PackageDescription/Check.hs
Cabal/Distribution/PackageDescription/PrettyPrint.hs
Cabal/Distribution/PackageDescription/Quirks.hs
Cabal/Distribution/Simple.hs
Cabal/Distribution/Simple/BuildTarget.hs
Cabal/Distribution/Simple/Compiler.hs
Cabal/Distribution/Simple/Configure.hs
Cabal/Distribution/Simple/GHC.hs
Cabal/Distribution/Simple/GHC/Internal.hs
Cabal/Distribution/Simple/GHCJS.hs
Cabal/Distribution/Simple/Haddock.hs
Cabal/Distribution/Simple/InstallDirs.hs
Cabal/Distribution/Simple/LocalBuildInfo.hs
Cabal/Distribution/Simple/Program/Find.hs
Cabal/Distribution/Simple/Program/Run.hs
Cabal/Distribution/Simple/Register.hs
Cabal/Distribution/Simple/Setup.hs
Cabal/Distribution/Simple/SrcDist.hs
Cabal/Distribution/Simple/Test/LibV09.hs
Cabal/Distribution/Simple/UHC.hs
Cabal/Distribution/Simple/Utils.hs
Cabal/Distribution/Utils/Generic.hs
Cabal/Distribution/Utils/LogProgress.hs
cabal-install/Distribution/Client/Compat/Prelude.hs

Remove WithCallStack IO type alias

---

Cabal/Distribution/Types/PkgconfigName.hs
Cabal/Distribution/Types/PkgconfigVersionRange.hs
Cabal/Distribution/Types/UnitId.hs
Cabal/Distribution/Types/VersionRange/Internal.hs

Doesn't seem to noticeably speed-up e.g. hackage-tests,
but I guess there is no harm in this either. Less work for the optimizer.

Expand elem

---

Cabal/Cabal-quickcheck/Cabal-quickcheck.cabal
Cabal/Cabal-quickcheck/src/Test/QuickCheck/Instances/Cabal.hs
Cabal/Cabal.cabal
Cabal/tests/UnitTests/Distribution/SPDX.hs
Cabal/tests/UnitTests/Distribution/Version.hs
cabal.project

... which may become a package we upload
---
The follow-up would be to make `cabal-install` test-suite use the new package.
That would require fiddling with `validate.sh` and project files and CI.
Therefore I'm not doing it yet. (Help welcome!)

Split QuickCheck instances into separate directory

---

Cabal/doc/developing-packages.rst

Previously the user's guide stated that the `extensions` field was
preferred over `ghc-options` even though `extensions` are deprecated
in favour for `default-extensions`.
[ci skip]
---

docs: Reference default-extensions from ghc-options

---

Cabal/Distribution/FieldGrammar/FieldDescrs.hs
Cabal/Distribution/Simple/Utils.hs

Originally written by Ryan Scott in
https://github.com/haskell/cabal/pull/6545#issuecomment-592712318

Adapt to simplified subsumption patch

---

Cabal/Distribution/Simple/Utils.hs
cabal-install/Distribution/Client/SetupWrapper.hs

Add rewriteFileLBS and use it to write setup wrapper

---

cabal-install/tests/IntegrationTests2.hs

The filesystem woes make it fail way too often

Disable test for 3324 on Windows

---

cabal-install/Distribution/Client/CmdUpdate.hs
cabal-install/Distribution/Client/Config.hs
cabal-install/Distribution/Client/GlobalFlags.hs
cabal-install/Distribution/Client/HttpUtils.hs
cabal-install/Distribution/Client/IndexUtils.hs
cabal-install/Distribution/Client/IndexUtils/Timestamp.hs
cabal-install/Distribution/Client/Install.hs
cabal-install/Distribution/Client/ProjectConfig/Legacy.hs
cabal-install/Distribution/Client/Setup.hs
cabal-install/Distribution/Client/Types.hs
cabal-install/Distribution/Client/Update.hs
cabal-install/Distribution/Client/Upload.hs
cabal-install/tests/UnitTests/Distribution/Client/IndexUtils/Timestamp.hs
cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
cabal-install/tests/UnitTests/Distribution/Client/TreeDiffInstances.hs

Make it, LocalRepo, RemoteRepo, IndexState and Timestamp use
Pretty/Parsec instead of Text
Mostly adding `unRepoName` to error printing statements

Add RepoName newtype

---

Cabal/Distribution/PackageDescription/Quirks.hs
Cabal/tests/HackageTests.hs

Partially fixes https://github.com/haskell/cabal/issues/6587
For local files, there might be invalid UTF8; but if
file comes from Hackage, we can assume they are valid UTF8.

Add Quirk for single invalid UTF8 file.

---

Cabal/Cabal-quickcheck/src/Test/QuickCheck/Instances/Cabal.hs
Cabal/Distribution/Types/Dependency.hs
Cabal/Distribution/Types/PackageName.hs
Cabal/Distribution/Types/UnqualComponentName.hs
Cabal/Distribution/Types/VersionRange.hs
Cabal/Distribution/Types/VersionRange/Internal.hs
Cabal/tests/ParserTests/regressions/encoding-0.8.expr
Cabal/tests/ParserTests/regressions/encoding-0.8.format
Cabal/tests/UnitTests/Distribution/Utils/Structured.hs
Cabal/tests/UnitTests/Distribution/Version.hs
cabal-install/Distribution/Client/IndexUtils/Timestamp.hs
cabal-install/Distribution/Deprecated/Text.hs
cabal-install/cabal-install.cabal.pp
cabal-install/tests/UnitTests.hs
cabal-install/tests/UnitTests/Distribution/Client/ArbitraryInstances.hs
cabal-install/tests/UnitTests/Distribution/Client/Described.hs
cabal.project.validate

- Writing a regex to parse dates is awful.
- Add ShortText conversions to PackageName and UnqualComponentName
- Add mkDependency, which maintains the invariant
- Remove VersionRangeParens - it's not preserved by `parsec . pretty` roundtrip
- Move moree instances into Cabal-quickcheck,use the package in cabal-install tests

Add Described to IndexState (incl. tests).

---

cabal-install/Distribution/Client/CmdFreeze.hs
cabal-install/Distribution/Client/CmdUpdate.hs
cabal-install/Distribution/Client/Get.hs
cabal-install/Distribution/Client/IndexUtils.hs
cabal-install/Distribution/Client/IndexUtils/IndexState.hs
cabal-install/Distribution/Client/Install.hs
cabal-install/Distribution/Client/ProjectConfig/Types.hs
cabal-install/Distribution/Client/ProjectOrchestration.hs
cabal-install/Distribution/Client/ProjectPlanning.hs
cabal-install/Distribution/Client/Setup.hs
cabal-install/Distribution/Client/Types.hs
cabal-install/Distribution/Client/Update.hs
cabal-install/tests/IntegrationTests2.hs
cabal-install/tests/UnitTests/Distribution/Client/ArbitraryInstances.hs
cabal-install/tests/UnitTests/Distribution/Client/Described.hs
cabal-install/tests/UnitTests/Distribution/Client/TreeDiffInstances.hs

One concern I have is the syntax.
`v2-update` uses comma :
```
hackage.haskell.org,HEAD
hackage.haskell.org,2020-03-16T01:24:50Z
hackage.haskell.org,@123123123
```
Yet, I don't want comma in configuration files to mean anything else then list separator,
therefore I took colon, which we use e.g. in `allow-newer` and other "namespace" cases:
```
hackage.haskell.org:HEAD
hackage.haskell.org:2020-03-16T01:24:50Z
hackage.haskell.org:@123123123
```
This is a bit unfortunate, as timestamp has colons in it.
Another alternative would be to use `@`, note double `@` when using posix-timestamp.
```
hackage.haskell.org@HEAD
hackage.haskell.org@2020-03-16T01:24:50Z
hackage.haskell.org@@123123123
```
---
I'll merge the colon version; this can be changed before `3.4` is released.
Perfectly, `v2-update` …

Allow specify index-state per repository

---

Cabal/tests/HackageTests.hs

This allows to quickly write ad-hoc queries over Hackage data.

Add forEachGPD to hackage-tests

---

Cabal/Cabal.cabal
Cabal/Distribution/InstalledPackageInfo.hs
Cabal/Distribution/Parsec/Warning.hs
Cabal/Distribution/Types/Dependency.hs
Cabal/Distribution/Types/LibraryVisibility.hs
Cabal/tests/CheckTests.hs
Cabal/tests/ParserTests/regressions/issue-5846.format
Cabal/tests/ParserTests/regressions/issue-6083-pkg-pkg.format
Cabal/tests/ParserTests/regressions/public-multilib-1.cabal
Cabal/tests/ParserTests/regressions/public-multilib-1.check
Cabal/tests/ParserTests/regressions/public-multilib-2.cabal
Cabal/tests/ParserTests/regressions/public-multilib-2.check
cabal-install/Distribution/Client/ProjectPlanning.hs
cabal-testsuite/PackageTests/MultipleLibraries/cabal.out
cabal-testsuite/Test/Cabal/Monad.hs

Needs backport to whatever branch `hackage-server` would pick up.

Mark public libs as an experimental feature

---

cabal-install/Distribution/Client/Init.hs

When `build-type: Simple` the contents of Setup.hs MUST BE standard. It is only
in advanced cases where a custom setup file is needed.
This also has the positive consequence of simplifying the directory contents created during package initialization.
---

Don't write Setup.hs file during cabal init.

---

.docker/validate-8.10.1.dockerfile
.github/workflows/linux.yml
Makefile
cabal-dev-scripts/src/GenValidate.hs
cabal-install/Distribution/Client/CmdSdist.hs
cabal-testsuite/cabal-testsuite.cabal

Also add validate-8.10.1 make rule
This needs backporting. I'll do that when `cabal-install` dependencies are updated as well.

Add GHC-8.10.1 job. Only tests Cabal-the-lib part atm.

---

Cabal/Cabal-quickcheck/src/Test/QuickCheck/Instances/Cabal.hs
Cabal/Distribution/PackageDescription.hs
Cabal/Distribution/PackageDescription/Check.hs
Cabal/Distribution/Types/SourceRepo.hs
Cabal/tests/Instances/TreeDiff.hs
Cabal/tests/ParserTests/regressions/Octree-0.5.expr
Cabal/tests/ParserTests/regressions/common-conditional.expr
Cabal/tests/ParserTests/regressions/common.expr
Cabal/tests/ParserTests/regressions/common2.expr
Cabal/tests/ParserTests/regressions/common3.expr
Cabal/tests/ParserTests/regressions/elif.expr
Cabal/tests/ParserTests/regressions/elif2.expr
Cabal/tests/ParserTests/regressions/generics-sop.expr
Cabal/tests/ParserTests/regressions/jaeger-flamegraph.expr
Cabal/tests/ParserTests/regressions/nothing-unicode.expr
Cabal/tests/ParserTests/regressions/shake.expr
Cabal/tests/ParserTests/regressions/th-lift-instances.expr
Cabal/tests/ParserTests/regressions/wl-pprint-indef.expr
Cabal/tests/UnitTests/Distribution/Utils/Structured.hs
cabal-install/Distribution/Client/VCS.hs
cabal-install/tests/UnitTests/Distribution/Client/Get.hs
cabal-install/tests/UnitTests/Distribution/Client/TreeDiffInstances.hs

fixes #6432 
Previously we had:
```
data RepoType = Darcs | Git | SVN | CVS
| Mercurial | GnuArch | Bazaar | Monotone
| OtherRepoType String
```
And these changes split the `RepoType` into two like this:
```
data KnownRepoType = Darcs | Git | SVN | CVS
| Mercurial | GnuArch | Bazaar | Monotone
data RepoType = KnownRepoType KnownRepoType
| OtherRepoType String
```

6432 - Split RepoType into type with known VCS and other

---

cabal-install/Distribution/Client/Config.hs

Cabal version 2.4 is over 2 years old at this point and has numerous additions
compared to the current default 1.10.
There are numerous references to the `^>=` operator throughout the docs (nix-local-build.rst and developing-packages.rst) but this does not work in version 1.10. This results in unnecessary confusion for users which then must manually edit the cabal file to change the version. To add to the confusion, the format written to the cabal file (`cabal-version: >=1.10`) only works for this version, to use a newer version you need to remove the `>=` which is undocumented and confusing.
Lets just default to a more recent version. 
---

Default to cabal version 2.4 when running cabal init.

---

cabal-install/Distribution/Client/Init.hs
cabal-install/Distribution/Client/Init/Licenses.hs
cabal-install/Distribution/Client/Init/Types.hs

Adding/rewording cabal init comments.

Comments and small refactorings in cabal init code.

---

cabal-install/bootstrap.sh

These were needed to work with base-4.13.0.0 which comes with ghc-8.8.2.
---
Amended #6531 (updated `resolv` bound).

Update bootstrap dependencies to work with base-4.13.0.0.

---

Cabal/ChangeLog.md
cabal-install/changelog
changelog.d/cabal-init
changelog.d/config
changelog.d/documentation
changelog.d/index-state
changelog.d/install-sha256
changelog.d/issue-6210
changelog.d/issue-6369
changelog.d/issue-6393
changelog.d/issue-6432
changelog.d/issue-6575
changelog.d/others
changelog.d/public-libs
changelog.d/utf8

Since 3.2 we have done at least:
- `cabal init` defaults to `cabal-version: 2.4` [#6607](https://github.com/haskell/cabal/pull/6607)
- Documentation updates [#6613](https://github.com/haskell/cabal/pull/6613)
- *cabal-install* More rich `index-state` syntax. `v2-freeze` saves `index-state`. [#6581](https://github.com/haskell/cabal/pull/6581) [#6596](https://github.com/haskell/cabal/pull/6596) [#6597](https://github.com/haskell/cabal/pull/6597)
- *cabal-install* Check sha256 if `#sha256=...` fragments are given to URIs [#6576](https://github.com/haskell/cabal/pull/6576)
- Default to 'NoReports' for remote build reporting [#6210](https://github.com/haskell/cabal/issues/6210) [#6625](https://github.com/haskell/cabal/pull/6625)
- *cabal-install* Allow cabal v2-install pkgname:exename …

Changelog.d

---

cabal-install/Distribution/Client/CmdInstall.hs
cabal-install/Distribution/Client/CmdRepl.hs
cabal-install/Distribution/Client/CmdRun.hs
cabal-install/Distribution/Client/CmdSdist.hs
cabal-install/Distribution/Client/ProjectConfig.hs
cabal-install/Distribution/Client/ProjectOrchestration.hs
cabal-testsuite/PackageTests/Regression/T5318/sdist-list-sources.out
cabal-testsuite/PackageTests/Regression/T5318/sdist-list-sources.test.hs
cabal-testsuite/PackageTests/SDist/T5195/cabal.out
cabal-testsuite/PackageTests/SDist/T5195/cabal.test.hs

Cabal v2-sdist --ignore-project

---

cabal-install/Distribution/Client/CmdInstall.hs
cabal-install/Distribution/Client/Config.hs

Cabal 3.0.0.0 added the `--installdir` option to specify the location that binaries should be installed in. Running a `cabal user-config update` would populate the config file with the default value, but the `cabal install` program would error if it wasn't set. This change uses the default value that would be written to the config if its unset, and outputs a warning.
Previous error:
```
cabal: installdir is not defined. Set it in your cabal config file or use
--installdir=<path>
```
New warning (install succeds):
```
Warning: installdir is not defined. Set it in your cabal config file or use
--installdir=<path>. Using default installdir: "/path/to/the/default/installdir/bin"
```
This resolves #5973  
---
Please also shortly describe how …

Use default install directory if not specified.

---

cabal-install/Distribution/Client/Config.hs
cabal-install/Distribution/Client/Init/Command.hs
cabal-install/Distribution/Client/Init/Defaults.hs
cabal-install/Distribution/Client/Init/FileCreators.hs
cabal-install/Distribution/Client/Init/Types.hs
cabal-install/Distribution/Client/Setup.hs
changelog.d/cabal-init

Improve `cabal init` code a bit

---

.readthedocs.yml

At some point ReadTheDocs switched the default Python version from 2.7 to 3.7 causing all Cabal user guide docs to no longer build. The error surfaces as:
```
File "/home/docs/checkouts/readthedocs.org/user_builds/m-renaud-haskell-cabal/checkouts/mrenaud-docs-getting-started/Cabal/doc/cabaldomain.py", line 153
sig = re.sub(ur'<([-a-zA-Z ]+)>', ur'⟨\1⟩', sig)
```
This PR adds a config file which pins to python 2.7, we really should just update cabaldomain.py to be compatible with Python 3.7, but that's for another day.
Verified this branch builds at: https://readthedocs.org/projects/m-renaud-haskell-cabal/builds/10780554/ (not sure if this is publicly visible or not).
Edit: after looking at https://readthedocs.org/projects/cabal/builds/, it appears the docs have built successfully, maybe …

Add .readthedocs.yml config file and pin to Python v2.7.

---

Cabal/doc/getting-started.rst
Cabal/doc/index.rst

Create a Getting Started guide focused on newcomers to the Haskell ecosystem and Cabal. This page sits at the front of the Cabal user guide and walks through creating a new package, building and running it, and adding a dependency on a package from Hackage.
Rendered docs can be found at: https://m-renaud-haskell-cabal.readthedocs.io/en/mrenaud-docs-newcomer-tutorial/getting-started.html
Follow-up PRs:
- Link to `cabal (v2-)build` docs (when they are written)
- Write and link to section about `^>=` (there's no place that really explains it currently)
- More commentary about `:target` syntax (and write docs discussing target syntax to link to)
- Add section about "projects"
---
Please also shortly describe how you tested your change. Bonus …

Create "Getting started" tutorial.

---

cabal-install/Distribution/Client/Init/Command.hs

Default to SPDX.NONE license in cabal init interactive mode.

---

Cabal/Distribution/Simple/PackageIndex.hs
cabal-install/Distribution/Client/List.hs
cabal-install/Distribution/Client/Setup.hs
cabal-install/Distribution/Solver/Types/PackageIndex.hs
changelog.d/issue-4267

This PR adds `--exact` flag to the cabal list command which
enables exact match on the package name while searching.
Supersedes #6618

4267 Add --exact flag to the list command

---

cabal-install/Distribution/Client/Setup.hs
changelog.d/issue-5224

Fixes #5224, supersedes #6609 and #6313

Mention password-command option in upload --help

---

cabal-install/Distribution/Client/Config.hs
cabal-install/Distribution/Client/Init/Command.hs
cabal-install/Distribution/Client/Init/Defaults.hs
cabal-install/Distribution/Client/Init/Prompt.hs
changelog.d/cabal-init

This sets the default directory for the main module as `app/` (`--application-dir=app`) and library source files as `src/` (`--source-dir=src`).
This avoids the problem described in #6150 of having a library and executable share the same `hs-source-dirs`. Even for just the executable case its best to have a separate directory because its likely that eventually code will be moved into internal libraries for testing (which should also have a separate `hs-source-dirs`).
Tested manually, both interactively and non-interactively.
This resolves #6150. 
---

Default cabal init application-dir to app, and source-dir to src.

---

Cabal/Distribution/PackageDescription/Check.hs
Cabal/Distribution/Types/SourceRepo.hs
Cabal/tests/UnitTests/Distribution/Utils/Structured.hs
cabal-install/Distribution/Client/VCS.hs
cabal-install/tests/UnitTests/Distribution/Client/VCS.hs

cabal-install support is very WIP
Fixes #6610 
I wrote a note in the code, the `cabal-install` side of the story is incomplete, but I think we need an actual `pijul` user to figure the details.

6610 Add pijul to known repository type

---

cabal-install/Distribution/Client/Init/FileCreators.hs
cabal-install/cabal-install.cabal.pp
cabal-install/tests/UnitTests.hs
cabal-install/tests/UnitTests/Distribution/Client/Init/FileCreators.hs
tests/UnitTests/Distribution/Client/Init/goldens/generateCabalFile/exe-only.cabal
tests/UnitTests/Distribution/Client/Init/goldens/generateCabalFile/lib-exe-and-test.cabal
tests/fixtures/init/exe-only-golden.cabal
tests/fixtures/init/lib-exe-and-test-golden.cabal

I'll be switching `cabal init` to use `PrettyField` in an upcoming PR, this will make it easier to verify that the output remains approximately the same (modulo better formatting).

Add FileCreators.generateCabalFile unit tests.

---

cabal-install/Distribution/Client/Init/FileCreators.hs
tests/fixtures/init/exe-only-golden.cabal
tests/fixtures/init/lib-exe-and-test-golden.cabal

This matches what is produced by PrettyField, so that when we switch over the
cabal file generation from manual formatting to PrettyField formatting we see
the true diffs and less field indent line noise.

Reduce cabal init field offset formatting by one space.

---

cabal-install/Distribution/Client/CmdRepl.hs

This PR updates the `--build-depends` help string in repl. Additionally, it looks like my extr-whitespace-stripping macro caught some extraneous whitespace in the file. If you want me to revert, just say so

update --build-depends help string

---

Cabal/Cabal.cabal
Cabal/Distribution/FieldGrammar/Described.hs
Cabal/Distribution/ModuleName.hs
Cabal/Distribution/Parsec/Newtypes.hs
Cabal/Distribution/Utils/GrammarRegex.hs
Cabal/doc/buildinfo-fields-reference.rst
Cabal/tests/UnitTests/Distribution/Described.hs
buildinfo-reference-generator/src/Main.hs
buildinfo-reference-generator/template.zinza
cabal-install/Distribution/Client/Types/RepoName.hs
cabal-install/tests/UnitTests/Distribution/Client/Described.hs

Rename Regex to GrammarRegex to avoid confusion

---

cabal-install/tests/UnitTests/Distribution/Client/Init/FileCreators.hs
tests/fixtures/init/lib-and-exe-golden.cabal

The key item captured in this test is that when `cabal init --libandexe` is run in an empty directory it will result in a dependency on the library from the executable in the form of `build-depends = <package-name>` but with no version constraints since they are implied by the version of the current package.

Add cabal init golden test exercising --libandexe behaviour.

---

cabal-install/Distribution/Client/Setup.hs
cabal-install/main/Main.hs

All three were hidden commands, first two were unimplemented
and the last one no-one knows about.

Resolve #6691: Remove upgrade, uninstall and win32selfupgrade commands

---

Cabal/Distribution/Simple/Command.hs
cabal-install/Distribution/Client/CmdSdist.hs
cabal-install/Distribution/Client/ProjectConfig/Types.hs
cabal-install/Distribution/Client/ProjectFlags.hs
cabal-install/Distribution/Client/Setup.hs
cabal-install/cabal-install.cabal
cabal-install/cabal-install.cabal.pp

First step to not repeat `project-file` spec everywhere

Add ProjectFlags, use in sdist

---

Cabal/doc/cabal-project.rst
cabal-install/Distribution/Client/ProjectConfig.hs
changelog.d/issue-6739

Change 'optional-packages' default on missing cabal.project

---

cabal-install/Distribution/Client/CmdHaddock.hs
cabal-install/Distribution/Client/CmdInstall.hs
cabal-install/Distribution/Client/CmdRepl.hs
cabal-install/Distribution/Client/CmdRun.hs
cabal-install/Distribution/Client/NixStyleOptions.hs
cabal-install/cabal-install.cabal
cabal-install/cabal-install.cabal.pp

Make NixStyleOptions

---

Cabal/Distribution/Backpack/Id.hs

-this-package-key command-line flag has been deprecated in GHC a long
time ago (superseded by -this-unit-id). Cabal should support newer GHC
releases without it.

Support for -this-package-key deprecation

---

cabal-install/tests/UnitTests/Distribution/Client/ArbitraryInstances.hs
cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs

This is suboptimal, as applicative stuff have to in order. But we suffer from that in `arbitrary` already.

Add shrinker, so writing big non-generic product shrinkers is easier

---

Cabal/Distribution/Compiler.hs

Cabal.Distribution.Compiler: add Functor, Foldable, and Traversable instances for PerCompilerFlavor

---

cabal-install/Distribution/Client/CmdInstall.hs

Pulls out implementation details into standalone functions. This makes the required inputs clear and removes from-afar data dependencies.
---

Internal refactorings to install command.

---

Cabal/doc/developing-packages.rst

Since `cabal init` is no longer interactive by default
(as per my version, 3.0.0.0), including other minor
changes to the `init` process, change the `cabal init`
section to mention the usage of the `--interactive` flag,
and the new minor changes (which/the order questions
are asked, what the terminal output is).
I came across this problem while learning `cabal`
(having recently migrated from `stack`) and reading
this section of Cabal's quickstart guide.
Apologies if I have made any mistakes; I am relatively
new to Haskell.
---

cabal init not interactive by default in 3.0

---

Makefile
cabal.project.weeder
weeder.dhall

```
make weeder
```
to run weeder.
There are plenty of false positives. But still, useful. Thanks @ocharles for the tool.

Add weeder

---

Cabal/Distribution/Compat/CharParsing.hs
Cabal/Distribution/Types/Flag.hs
cabal-install/Distribution/Client/BuildReports/Anonymous.hs
cabal-install/Distribution/Client/BuildReports/Types.hs
cabal-install/Distribution/Client/Config.hs
cabal-install/Distribution/Client/Configure.hs
cabal-install/Distribution/Client/Dependency/Types.hs
cabal-install/Distribution/Client/Get.hs
cabal-install/Distribution/Client/ProjectConfig/Legacy.hs
cabal-install/Distribution/Client/ProjectPlanOutput.hs
cabal-install/Distribution/Client/Sandbox/PackageEnvironment.hs
cabal-install/Distribution/Client/Setup.hs
cabal-install/Distribution/Client/SetupWrapper.hs
cabal-install/Distribution/Client/Targets.hs
cabal-install/Distribution/Deprecated/ParseUtils.hs
cabal-install/Distribution/Deprecated/Text.hs
cabal-install/Distribution/Solver/Types/PackagePath.hs
cabal-install/Distribution/Solver/Types/Settings.hs
cabal-install/tests/UnitTests/Distribution/Client/ArbitraryInstances.hs
cabal-install/tests/UnitTests/Distribution/Client/Described.hs
cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
cabal-install/tests/UnitTests/Distribution/Client/Targets.hs

- 2020-05-08: This is a bit of rabbit hole. I try to dig myself up. Plenty of tests failing.

Remove text instances

---

cabal-install/Distribution/Client/World.hs
cabal-install/tests/UnitTests/Distribution/Client/ArbitraryInstances.hs
cabal-install/tests/UnitTests/Distribution/Client/Described.hs

Blocked on removal of `-any` and `-none`. #6589

Remove Text WorldPkgInfo

---

Cabal/Distribution/Simple/PackageIndex.hs
cabal-install/Distribution/Client/List.hs
cabal-install/Distribution/Client/Setup.hs
cabal-install/Distribution/Solver/Types/PackageIndex.hs
cabal-install/bootstrap.sh
cabal-install/cabal-install.cabal
cabal-install/cabal-install.cabal.pp
cabal-install/main/Main.hs

Regex list

---

cabal-install/Distribution/Client/CmdUpdate.hs

For example:
Downloading the latest package list from hackage.haskell.org
Updated package list of hackage.haskell.org to index-state 2020-05-15T09:13:06Z
To revert to previous state run:
cabal v2-update 'hackage.haskell.org,2020-05-10T18:58:02Z'
Or
Package list of hackage.haskell.org is up to date at index-state 2020-05-15T09:13:06Z
ping @samuela

Resolve #6804: v2-update reports new index-state

---

cabal-install/Distribution/Client/CmdBench.hs
cabal-install/Distribution/Client/CmdBuild.hs
cabal-install/Distribution/Client/CmdErrorMessages.hs
cabal-install/Distribution/Client/CmdHaddock.hs
cabal-install/Distribution/Client/CmdInstall.hs
cabal-install/Distribution/Client/CmdRepl.hs
cabal-install/Distribution/Client/CmdRun.hs
cabal-install/Distribution/Client/CmdTest.hs
cabal-install/Distribution/Client/ProjectOrchestration.hs
cabal-install/Distribution/Client/TargetProblem.hs
cabal-install/cabal-install.cabal
cabal-install/cabal-install.cabal.pp
cabal-install/tests/IntegrationTests2.hs

Moved "problem rendering" to CmdErrorMessages module
Additions by Oleg Grenrus:
- There were CommonTargetProblem, but now
TargetProblem has an extension point so we can have just one type.
A lot of code is simplified as we don't need to pass in injection
from CommonTargetProblem to the resulting `err` type.
--
An extension of #6774. cc @m-renaud

Refactor shared TargetProblem data types into their own module.

---

Cabal/doc/cabal-commands.rst
cabal-install/Distribution/Client/TargetSelector.hs
cabal-install/cabal-install.cabal
cabal-install/cabal-install.cabal.pp
cabal-install/tests/IntegrationTests2.hs
cabal-install/tests/IntegrationTests2/targets/simple/p.cabal
cabal-install/tests/IntegrationTests2/targets/simple/q/q.cabal

Squashed and rebased #6623 
---
Add Integration tests for File Target Selector
Add Integration test for Target Selecetors for files that
are part of other-modules in sub-directories.
Normalise Filepaths for target matching
Add filepath and module target syntax to readthedocs
Add ambiguous file target test-case

Prepend hs-source-dir to match-component

---

.github/workflows/artifacts.yml
.github/workflows/windows.yml
boot/ci-artifacts.template.yml
boot/ci-windows.template.yml

- msys2 should be installed
- there is cabal and GHC, but we want to be sure about
versions, so we reinstall.
---
Let's see if this works.

Fix Windows GitHub Action

---

cabal-install/Distribution/Client/Setup.hs

In #6836 I noticed that I forgot to filter out the --allow-depending-on-private-libs flag for old Cabals. With that patch it becomes necessary to have the filtering, but I guess having it in 3.2 would be good too?

Backport filter --allow-depending-on-private-libs

---

Cabal/Distribution/Simple/Compiler.hs
Cabal/Distribution/Types/CondTree.hs
cabal-install/Distribution/Client/ProjectPlanning.hs
cabal-install/Distribution/Client/Setup.hs
cabal-install/Distribution/Solver/Modular/Dependency.hs
cabal-install/Distribution/Solver/Modular/Index.hs
cabal-install/Distribution/Solver/Modular/IndexConversion.hs
cabal-install/Distribution/Solver/Modular/Message.hs
cabal-install/Distribution/Solver/Modular/Tree.hs
cabal-install/Distribution/Solver/Modular/Validate.hs
cabal-install/solver-dsl/UnitTests/Distribution/Solver/Modular/DSL.hs
cabal-install/tests/UnitTests/Distribution/Solver/Modular/MemoryUsage.hs
cabal-install/tests/UnitTests/Distribution/Solver/Modular/QuickCheck.hs
cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs
cabal-testsuite/PackageTests/MultipleLibraries/Failing/cabal.out
cabal-testsuite/PackageTests/MultipleLibraries/Successful/cabal.test.hs
cabal-testsuite/PackageTests/MultipleLibraries/T6083Pre/cabal.test.hs
cabal-testsuite/PackageTests/MultipleLibraries/T6083PreMixin/cabal.test.hs
changelog.d/public-libs-solver

Adds check overrides to #6812 / #6047
/cc @phadej @grayjay

Solver: Support dependencies on sub-libraries (issue #6039) (3rd iteration)

---

Cabal/Cabal-tree-diff/src/Data/TreeDiff/Instances/Cabal.hs
Cabal/Distribution/Backpack/ComponentsGraph.hs
Cabal/Distribution/Backpack/Id.hs
Cabal/Distribution/Backpack/LinkedComponent.hs
Cabal/Distribution/Backpack/UnifyM.hs
Cabal/Distribution/PackageDescription.hs
Cabal/Distribution/PackageDescription/Check.hs
Cabal/Distribution/PackageDescription/Configuration.hs
Cabal/Distribution/PackageDescription/FieldGrammar.hs
Cabal/Distribution/PackageDescription/Parsec.hs
Cabal/Distribution/PackageDescription/PrettyPrint.hs
Cabal/Distribution/Simple/Build.hs
Cabal/Distribution/Simple/Build/Macros.hs
Cabal/Distribution/Simple/BuildPaths.hs
Cabal/Distribution/Simple/BuildToolDepends.hs
Cabal/Distribution/Simple/Configure.hs
Cabal/Distribution/Simple/GHC.hs
Cabal/Distribution/Simple/GHC/Internal.hs
Cabal/Distribution/Simple/GHCJS.hs
Cabal/Distribution/Simple/PreProcess.hs
Cabal/Distribution/Simple/Program/GHC.hs
Cabal/Distribution/Simple/Setup.hs
Cabal/Distribution/Simple/SrcDist.hs
Cabal/Distribution/Types/ComponentLocalBuildInfo.hs
cabal-install/Distribution/Client/List.hs
cabal-install/Distribution/Client/SetupWrapper.hs
cabal-install/Distribution/Solver/Modular/IndexConversion.hs
cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL/TestCaseUtils.hs

Now it re-exports a collection of modules,
not individual symbols.

Refactor D.PackageDescription

---

cabal-testsuite/PackageTests/Regression/T6853/cabal.out
cabal-testsuite/PackageTests/Regression/T6853/cabal.project
cabal-testsuite/PackageTests/Regression/T6853/cabal.test.hs
cabal-testsuite/PackageTests/Regression/T6853/pkg-foo/Foo.hs
cabal-testsuite/PackageTests/Regression/T6853/pkg-foo/pkg-foo.cabal

It's import that flag is *True*, so it's passed without prefix-sign.
This is test case forgotten in #6854

Add test for #6853

---

Cabal/Cabal.cabal
Cabal/Distribution/Compat/CreatePipe.hs
Cabal/Distribution/Simple/Test/ExeV10.hs
Cabal/Distribution/Simple/Test/LibV09.hs
Cabal/Distribution/Simple/Utils.hs
Cabal/tests/UnitTests/Distribution/Compat/CreatePipe.hs

cc @Mistuke 
This doesn't yet work due
```
Unit Tests
Distribution.Compat.CreatePipe
Locale Encoding:                                                                      FAIL
tests/UnitTests/Distribution/Compat/CreatePipe.hs:19:
createPipe should support Unicode roundtripping
expected: "\252"
but got: "\195\188"
```
Compare:
```haskell
createPipeInternal :: IO (Handle, Handle)
createPipeInternal = do
(readfd, writefd) <- Posix.createPipe
readh <- Posix.fdToHandle readfd
writeh <- Posix.fdToHandle writefd
return (readh, writeh)
```
and
```haskell
createPipe = do
(readfd, writefd) <- Posix.createPipe
readh <- fdToHandle readfd
writeh <- fdToHandle writefd
hSetEncoding readh localeEncoding
hSetEncoding writeh localeEncoding
return (readh, writeh)
where
_ = callStack
```
---
I will think how …

Use process createPipe

---

Cabal/Distribution/Simple/GHC.hs
cabal-install/Distribution/Client/CmdInstall.hs

cabal-install currently assumes that the GHC environment files are always located in `$HOME/.ghc/`. However, GHC itself doesn't query the home directory directly. Instead, it uses `getAppUserDataDirectory "ghc"` ([GHC code](https://gitlab.haskell.org/ghc/ghc/-/blob/4898df1cc25132dc9e2599d4fa4e1bbc9423cda5/compiler/main/DynFlags.hs#L1514), [getAppUserDataDirectory](https://hackage.haskell.org/package/directory-1.3.6.1/docs/System-Directory.html#v:getAppUserDataDirectory)) which happens to coincide with `$HOME/.ghc/` on UNIX systems. On Windows, however, GHC ends up looking in `%APPDATA%/ghc/`.
As a result, `cabal install --lib` doesn't change the correct environment files on Windows.
This PR changes the environment file locations to match GHC. On UNIX, there is no change since …

Update GHC environment location (fixes #6565)

---

cabal-install/Distribution/Client/CmdInstall.hs
changelog.d/issue-6856

In so far as I didn't even add a newline, just some output characters.
I tested it by running the binary and observing the warning is now red on my screen.  I googled and found claims the color works on windows terminals as well.

Fix #6856 Make `--lib` warning louder and clearer

---

Cabal/Distribution/Compat/Prelude.hs
cabal-install/Distribution/Client/TargetSelector.hs
cabal-install/tests/IntegrationTests2.hs

These should have been returning an error message but instead were
causing an internal error because disambiguateTargetSelectors was
rendering syntax and rematching on it, which isn't equivalent. Due to
the way syntaxForm1File renders, it does not add a FileStatus to its
TargetStringFileStatus and so cannot be matched upon again.
The fix is to just copy over the FileStatus from the match input.
This fixes #6874

Fix ambiguous file target selectors causing an internal error

---

.gitignore
cabal-install/Distribution/Client/CmdConfigure.hs
cabal-install/Distribution/Client/TargetProblem.hs
cabal-testsuite/PackageTests/NewConfigure/LocalConfigOverwrite/cabal.out
cabal-testsuite/PackageTests/NewConfigure/LocalConfigOverwrite/cabal.test.hs
cabal-testsuite/PackageTests/NewConfigure/LocalConfigOverwrite/foo.project

Tell users about cabal.project.local~

---

cabal-install/Distribution/Client/Dependency.hs
cabal-install/Distribution/Client/Sandbox.hs

Bootstrapping cabal-install with ghc-master fails without these minor patches.
(Some of the package versions in bootstrap.sh also need updates, separate PR later).

Cabal-install GHC master compat

---

cabal-install/Distribution/Client/SourceFiles.hs
changelog.d/issue-4746

This should alleviate #4746 for most use cases, if the dependent files
are declared in `extra-source-files`. The downside is that `cabal`
will not be able to avoid invoking GHC in as many cases, but GHC's
`--make` should be smart enough to avoid any "actual" rebuilding that
isn't necessary.
----

Rebuild on changes in all extra-source-files

---

Cabal/Distribution/Backpack/ComponentsGraph.hs
Cabal/Distribution/Backpack/Configure.hs
cabal-testsuite/PackageTests/BuildDeps/DepCycle/setup.cabal.out
cabal-testsuite/PackageTests/BuildDeps/DepCycle/setup.out
cabal-testsuite/PackageTests/MultipleLibraries/T6894/Bar.hs
cabal-testsuite/PackageTests/MultipleLibraries/T6894/Foo.hs
cabal-testsuite/PackageTests/MultipleLibraries/T6894/cabal.out
cabal-testsuite/PackageTests/MultipleLibraries/T6894/cabal.project
cabal-testsuite/PackageTests/MultipleLibraries/T6894/cabal.test.hs
cabal-testsuite/PackageTests/MultipleLibraries/T6894/issue.cabal
cabal-testsuite/PackageTests/MultipleLibraries/T6894/setup.cabal.out
cabal-testsuite/PackageTests/MultipleLibraries/T6894/setup.out
cabal-testsuite/PackageTests/MultipleLibraries/T6894/setup.test.hs

@grayjay do you know where solver cycle check is? I found one in `Cabal` already.

Add a reproducer for #6894

---

cabal-install/Distribution/Client/BuildReports/Storage.hs
cabal-install/Distribution/Client/CmdInstall.hs
cabal-install/Distribution/Client/CmdRepl.hs
cabal-install/Distribution/Client/CmdRun.hs
cabal-install/Distribution/Client/CmdSdist.hs
cabal-install/Distribution/Client/Configure.hs
cabal-install/Distribution/Client/Dependency.hs
cabal-install/Distribution/Client/Fetch.hs
cabal-install/Distribution/Client/Get.hs
cabal-install/Distribution/Client/IndexUtils.hs
cabal-install/Distribution/Client/Init/Heuristics.hs
cabal-install/Distribution/Client/Install.hs
cabal-install/Distribution/Client/InstallSymlink.hs
cabal-install/Distribution/Client/List.hs
cabal-install/Distribution/Client/ProjectConfig.hs
cabal-install/Distribution/Client/ProjectPlanning.hs
cabal-install/Distribution/Client/TargetSelector.hs
cabal-install/Distribution/Client/Targets.hs
cabal-install/Distribution/Solver/Types/SourcePackage.hs
cabal-install/solver-dsl/UnitTests/Distribution/Solver/Modular/DSL.hs
cabal-install/tests/IntegrationTests2.hs

Also remove specific field for PackageId, as it is in GPD.

Rename fields in SourcePackage

---

Cabal/Distribution/PackageDescription/Check.hs
Cabal/Distribution/PackageDescription/FieldGrammar.hs
Cabal/doc/file-format-changelog.rst
Cabal/tests/ParserTests/regressions/issue-6288-a.check
Cabal/tests/ParserTests/regressions/issue-6288-d.check
Cabal/tests/ParserTests/regressions/issue-6288-f.check
cabal-testsuite/PackageTests/AutogenModules/SrcDist/AutogenModules.cabal
cabal-testsuite/PackageTests/AutogenModules/SrcDist/setup.test.hs
cabal-testsuite/PackageTests/Backpack/T5634/T5634.cabal
cabal-testsuite/PackageTests/Backpack/T5634/setup.cabal.out
cabal-testsuite/PackageTests/Backpack/T5634/setup.out
cabal-testsuite/PackageTests/BenchmarkStanza/my.cabal
cabal-testsuite/PackageTests/BenchmarkStanza/setup.cabal.out
cabal-testsuite/PackageTests/BenchmarkStanza/setup.out
cabal-testsuite/PackageTests/Haddock/my.cabal
cabal-testsuite/PackageTests/Regression/T3847/T3847.cabal
cabal-testsuite/PackageTests/Regression/T4025/T4025.cabal
cabal-testsuite/PackageTests/Regression/T4025/setup.cabal.out
cabal-testsuite/PackageTests/Regression/T4025/setup.out

- Add availableSince to language/extension fields
- Also autogen-modules once we are on that.
- Remove default-language check for cabal-version: 3.4
We cannot make the field `uniqueFieldAlaDef`, as that would require
specifying `default-language` in each subconditional.
I leave it for https://github.com/haskell/cabal/issues/6925
Note: the default language is whatever is the compiler's default.
The GHC-8.10 default is its variant of Haskell2010
with NondecreasingIndentation and without DatatypeContexts
---

Resolve #6288

---

Cabal/Distribution/Simple/BuildTarget.hs
cabal-install/Distribution/Client/CmdListBin.hs
cabal-install/Distribution/Client/ProjectPlanOutput.hs
cabal-install/Distribution/Client/Setup.hs
cabal-install/cabal-install.cabal
cabal-install/cabal-install.cabal.dev
cabal-install/cabal-install.cabal.prod
cabal-install/cabal-install.cabal.zinza
cabal-install/main/Main.hs
cabal-install/tests/IntegrationTests2.hs

Partially resolves #6807 
I need to test this on Windows and with GHCJS

Issue 6807 listbin

---

Cabal/Distribution/Simple/GHC.hs
Cabal/Distribution/Simple/GHCJS.hs
Cabal/Distribution/Simple/Program/Builtin.hs
Cabal/Distribution/Simple/Program/GHC.hs
Cabal/Distribution/Types/CondTree.hs
Cabal/Distribution/Types/InstalledPackageInfo/FieldGrammar.hs
Cabal/doc/cabal-project.rst
Cabal/doc/conf.py
Cabal/doc/hcar/Cabal-201611.tex
Cabal/doc/references.inc
Cabal/tests/custom-setup/CabalDoctestSetup.hs
cabal-install/Distribution/Solver/Types/Progress.hs

update ghc trac links to point to ghc gitlab

---

Cabal/Distribution/System.hs
changelog.d/pr-6301

rebased #6301 (added a changelog entry).

Accept "linux-androideabi" as an alias for Android

---

Cabal/doc/cabal-package.rst
Cabal/doc/cabal-project.rst
Cabal/doc/developing-packages.rst
Cabal/doc/file-format-changelog.rst
Cabal/doc/installing-packages.rst
Cabal/doc/nix-local-build-overview.rst
Cabal/doc/setup-commands.rst

This fixes about half of the "broken link" warnings displayed by sphinx.
<details>
<summary>sphinx warnings before this PR</summary>
<pre>
/home/jhrcek/Devel/github.com/haskell/cabal/Cabal/doc/developing-packages.rst:211: WARNING: Unknown target name: "common stanzas".
/home/jhrcek/Devel/github.com/haskell/cabal/Cabal/doc/developing-packages.rst:295: WARNING: Unknown target name: "package versioning policy".
/home/jhrcek/Devel/github.com/haskell/cabal/Cabal/doc/installing-packages.rst:237: WARNING: Unknown target name: "hackage".
/home/jhrcek/Devel/github.com/haskell/cabal/Cabal/doc/installing-packages.rst:245: WARNING: Unknown target name: "hackage".
/home/jhrcek/Devel/github.com/haskell/cabal/Cabal/doc/nix-local-build-overview.rst:4: WARNING: malformed hyperlink target. …

Fix broken links in documentation

---

Cabal/Distribution/Compat/DList.hs
Cabal/Distribution/Compat/Newtype.hs
Cabal/Distribution/FieldGrammar/Class.hs
Cabal/Distribution/FieldGrammar/FieldDescrs.hs
Cabal/Distribution/FieldGrammar/Newtypes.hs
Cabal/Distribution/PackageDescription/Check.hs
doc/cabal-package.rst
doc/cabal-project.rst
doc/nix-local-build-overview.rst
doc/setup-commands.rst

I finished going through the user's guide and here's the last batch of fixes + couple of minor haddock fixes.
The build of Cabal library is broken at the moment as commented [here](https://github.com/haskell/cabal/pull/6970#issuecomment-660450922)

Fix broken links in user's guide + few haddock fixes

---

Cabal/Cabal.cabal
Cabal/src/Distribution/Simple/Build/PathsModule.hs
Cabal/src/Distribution/Simple/Build/PathsModule/Z.hs
Makefile
cabal-dev-scripts/cabal-dev-scripts.cabal
cabal-dev-scripts/src/GenPathsModule.hs
templates/Paths_pkg.template.hs

This breaks `absolute` and `relocatable` variants. Let me see if we have any tests for them (maybe on windows).

Generate Paths module using zinza template

---

.github/workflows/artifacts.yml
.github/workflows/bootstrap.yml
.gitignore
bootstrap/bootstrap.py
release.py
templates/ci-artifacts.template.yml
templates/ci-bootstrap.template.yml

A script essentially runs `v2-install cabal-install:exe:cabal`,
but does some simple setup, so the result is less luckily
to be influences by environment.
Also improve bootstrap to do out-of-tree builds.
---

Add release.py

---

Cabal/src/Distribution/Compat/Process.hs

The CPP used to enable it even for version 1.6.8 which
turned out to still be buggy which causes segfaults when
building Cabal with ghc-8.10. See #6986.
This does not fully fix the issue as without job support
build failures can still sporadically occur.
---
Haven't tested it locally yet but will do so.

Bump process version required for job support to 1.6.9

---

Cabal/src/Distribution/Utils/Structured.hs

Like #7015, but rebased and lowered the cut bound to `0.10.4` (which ships with GHC-7.8)

Data.ByteString.Lazy.Builder -> Data.ByteString.Builder

---

.gitignore
Cabal/Cabal-QuickCheck/src/Test/QuickCheck/Instances/Cabal.hs
Cabal/Cabal.cabal
Cabal/src/Distribution/FieldGrammar/Newtypes.hs
Cabal/src/Distribution/PackageDescription/Check.hs
Cabal/src/Distribution/Types/PkgconfigVersionRange.hs
Cabal/src/Distribution/Types/VersionInterval.hs
Cabal/src/Distribution/Types/VersionInterval/Legacy.hs
Cabal/src/Distribution/Types/VersionRange.hs
Cabal/src/Distribution/Version.hs
Cabal/tests/UnitTests/Distribution/Version.hs
cabal-benchmarks/bench/CabalBenchmarks.hs
cabal-benchmarks/cabal-benchmarks.cabal
cabal-install/src/Distribution/Client/Dependency.hs
cabal-install/src/Distribution/Client/GenBounds.hs
cabal-install/src/Distribution/Client/Outdated.hs

This is the first part of rewriting VersionInterval code to support `^>=` version ranges.

Simpler normalise version range

---

Makefile
cabal-testsuite/PackageTests/Backpack/Includes3/cabal-repo.out
cabal-testsuite/PackageTests/BuildTargets/UseLocalPackage/use-local-version-of-package.out
cabal-testsuite/PackageTests/BuildTargets/UseLocalPackageForSetup/use-local-package-as-setup-dep.out
cabal-testsuite/PackageTests/Freeze/disable-benchmarks.out
cabal-testsuite/PackageTests/Freeze/disable-tests.out
cabal-testsuite/PackageTests/Freeze/dry-run.out
cabal-testsuite/PackageTests/Freeze/enable-benchmarks.out
cabal-testsuite/PackageTests/Freeze/enable-tests.out
cabal-testsuite/PackageTests/Freeze/freeze.out
cabal-testsuite/PackageTests/NewBuild/CustomSetup/LocalPackageWithCustomSetup/build-local-package-with-custom-setup.out
cabal-testsuite/PackageTests/NewBuild/CustomSetup/RemotePackageWithCustomSetup/build-package-from-repo-with-custom-setup.out
cabal-testsuite/PackageTests/NewBuild/T4375/cabal.out
cabal-testsuite/PackageTests/NewFreeze/BuildTools/new_freeze.out
cabal-testsuite/PackageTests/NewFreeze/Flags/new_freeze.out
cabal-testsuite/PackageTests/NewFreeze/FreezeFile/new_freeze.out
cabal-testsuite/PackageTests/Outdated/outdated-project-file.out
cabal-testsuite/PackageTests/Outdated/outdated.out
cabal-testsuite/PackageTests/Outdated/outdated_freeze.out
cabal-testsuite/PackageTests/Regression/T3932/cabal.out
cabal-testsuite/PackageTests/Regression/T5409/use-different-versions-of-dependency-for-library-and-build-tool.out
cabal-testsuite/PackageTests/Regression/T5409/use-different-versions-of-dependency-for-library-and-build-tool.test.hs
cabal-testsuite/main/cabal-tests.hs
cabal-testsuite/src/Test/Cabal/Prelude.hs

only 3 skipped on recent GHCs with `make validate-via-docker-8.6.5`

Skip less: docker ulimit and local+noindex to run withRepo tests. 

---

Cabal/src/Distribution/Simple/Program/GHC.hs
cabal-testsuite/PackageTests/FFI/ForeignOptsC/Main.hs
cabal-testsuite/PackageTests/FFI/ForeignOptsC/README.md
cabal-testsuite/PackageTests/FFI/ForeignOptsC/cabal.out
cabal-testsuite/PackageTests/FFI/ForeignOptsC/cabal.project
cabal-testsuite/PackageTests/FFI/ForeignOptsC/cabal.test.hs
cabal-testsuite/PackageTests/FFI/ForeignOptsC/cbits/clib.c
cabal-testsuite/PackageTests/FFI/ForeignOptsC/cbits/clib.h
cabal-testsuite/PackageTests/FFI/ForeignOptsC/foreign-opts-c.cabal
cabal-testsuite/PackageTests/FFI/ForeignOptsCxx/Main.hs
cabal-testsuite/PackageTests/FFI/ForeignOptsCxx/README.md
cabal-testsuite/PackageTests/FFI/ForeignOptsCxx/cabal.out
cabal-testsuite/PackageTests/FFI/ForeignOptsCxx/cabal.project
cabal-testsuite/PackageTests/FFI/ForeignOptsCxx/cabal.test.hs
cabal-testsuite/PackageTests/FFI/ForeignOptsCxx/cxxbits/cxxlib.cpp
cabal-testsuite/PackageTests/FFI/ForeignOptsCxx/cxxbits/cxxlib.h
cabal-testsuite/PackageTests/FFI/ForeignOptsCxx/foreign-opts-cxx.cabal

Intends to resolve [this issue](https://github.com/haskell/cabal/issues/6421). To summarize, cabal passes all C and C++ flags through GHC to the underlying C or C++ compiler using `-optc`. This works for GHC < 8.10, but now GHC expects C++ flags to come through `-optcxx`. This means that anything through `-optc` is ignored, so we cannot pass any flags to the C++ compiler. This change simply detects the GHC version and uses the correct arguments.
This PR has been tested manually on this [repro](https://github.com/ejconlon/ffi-repro) and two `PackageTests` have been added to `cabal-testsuite`. They pass under GHC 8.8.4 and GHC 8.10.2.

Pass -optcxx for GHC >= 8.10

---

cabal-install/src/Distribution/Client/ProjectOrchestration.hs

This PR provides slightly more information when a [project contains duplicates in 'packages' declaration](https://github.com/haskell/cabal/issues/6197). Hopefully this is a useful stopgap before a better way of presenting the error message is found.
Before:
```
$ cabal v2-build
TODO: add support for multiple packages in a directory
error, called at ./Distribution/Client/ProjectOrchestration.hs:548:9 in main:Distribution.Client.ProjectOrchestration
```
After:
```
$ cabal v2-build
Warning: Parsing the index cache failed (Data.Binary.Get.runGet at position
16: Non-matching structured hashes: a257ca064dfb5e0cb74f74e64a975b9e;
expected: f46da61e7afa58a5e8fd1d2b6fb79899). Trying to regenerate the index
cache... …
```

Slightly more information on multiple package error

---

Cabal/Cabal.cabal

Cabal is unaffected by the renamings done in 2.10.0.
---

Bump Win32 bound to <2.11

---

cabal-install/src/Distribution/Client/CmdLegacy.hs

This was causing the description of "new" prefixed and unprefixed
commands to be printed at both the top and bottom of their help text.

Fix command notes being replaced by descriptions

---

.gitignore
solver-benchmarks/HackageBenchmark.hs
solver-benchmarks/solver-benchmarks.cabal

This way they won't remake caches all the time.
I'm curious in comparing vastly different `cabal` versions (e.g. previous and current release), and these kept fighting over cache files, making numbers hugely inflated by cache updates. Having separate `CABAL_DIR`s makes them isolated (also from users' setup).
As a bonus I also calculate geometric mean of speedups across all packages.
cc @grayjay, you might be interested in this.

Make solver-benchmark use fresh cabal-dirs

---

Cabal/Cabal.cabal

Cabal: Bump time upper bound

---

cabal-install/src/Distribution/Client/Init/Command.hs

Fixes #6861, #6236
Regarding item number 2 on the checklist, I do not think this bugfix is significant enough to warrant a changelog entry.
```
auri@aoi lens $ cabal init --non-interactive
cabal: The name lens is already in use by another package on Hackage.
auri@aoi lens $ cabal init --non-interactive --package-name=microlens
cabal: The name microlens is already in use by another package on Hackage.
```
```
auri@aoi lens $ cabal init --interactive --package-name=microlens
Should I generate a simple project with sensible defaults? [default: y] y
cabal: The name microlens is already in use by another package on Hackage.
auri@aoi lens $ cabal init --interactive --package-name=microlens
Should I generate a simple project with sensible defaults? [default: y] n
[snip]
The name microlens is …
```

Fix cabal init name deduction

---

Cabal/src/Distribution/GetOpt.hs

Currently usageInfo is very ridgid about wrapping the cmdline help
output. Only the help text itself is wrapped, the list of short and long
option names is kept on one line always.
This patch allows more wrapping to happen for very long long-option
names. For example cabal-install has the
--write-ghc-environment-files=always|never|ghc8.4.4+
option which pushes the help text column over 80 cols for no good
reason. By simply wrapping the possible values after the "=" onto the next
line we can already return sanity to the output.
The patch also gets rid of the dedicated short options column. Previously
the long options column would be aligned to where the longest short option
ends, but since the vast majority of options are long options this seems
misguided. Now long and short options are …

Cabal: Improve cmdline help readability by breaking long lines

---

cabal-install/src/Distribution/Client/CmdErrorMessages.hs

Fixes error messages like this one (note the missing space in `Build.hsin`):
```
cabal: The run command can only run an executable as a whole, not files or
modules within them, but the target 'Build.hs' refers to the file Build.hsin
the executable shake
```

Add missing spaces between words in output

---

doc/cabal-commands.rst

The text for the `--lib` flag to the `cabal install` subcommand has been moved to its own subheading below that of `cabal install`. Also the text has been slightly reworded.
This is convenient because sometimes you want to link directly to the `cabal install --lib` behavior.
(Sorry if this is too trivial a change.)

Moved info for cabal install --lib to sub-heading

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

changelog.d isn't documented anywhere, and often the few example ones that are present aren't enough to understand how it works imo. This is mostly reverse engineered from the changelog-d code.
---

Add changelog.d documentation

---

release-notes/Cabal-3.4.0.0.md

* [*] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [*] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ *] The documentation has been updated, if necessary.

Reference ghc-9.0 in 3.0 changelog as that's what 8.12 became.

---

cabal-install/src/Distribution/Client/ProjectConfig.hs
cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs
cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs

In a project with lots of constraints it's not always obvious from which file a constraint is coming from. Also we are currently showing a big `TODO` message in place of the file name which is not nice.
It's not super great that we pass a dummy ConstraintSource to showProjectConfig but I would say it's not worse than before. 
Prior to this patch
```
$ cabal build all
cabal: Could not resolve dependencies:
[__0] trying: some-package-0.24.1.2 (user goal)
[__1] trying: foldl-1.4.8 (dependency of some-package)
[__2] next goal: mwc-random (dependency of foldl)
[__2] rejecting: mwc-random-0.15.0.0 (constraint from project config TODO
requires ==0.14.0.0)
[__2] trying: mwc-random-0.14.0.0
[__3] next goal: math-functions (dependency of mwc-random)
[__3] rejecting: …
```

Propagate provenance when parsing ProjectConfig

---

Cabal/Cabal.cabal

Bump upper bound on bytestring

---

doc/cabal-project.rst

I was confused about the resolution of settings in the presence of a `cabal.project` so I added some minimal documentation that would've helped me.
I was confused because in a project with both a `<pkgname>.cabal` and a `cabal.project`, v2-build complained about neither of them existing:
```
cabal: There is no <pkgname>.cabal package file or cabal.project file. To
build packages locally you need at minimum a <pkgname>.cabal file. You can use
'cabal init' to create one.
For non-trivial projects you will also want a cabal.project file in the root
directory of your project. This file lists the packages in your project and
all other build configuration. See the Cabal user guide for full details.
```
The problem turned out to be not setting `packages:` in the `cabal.project`, I'd only set …

Clarify cabal.project documentation

---

Cabal/Cabal.cabal

To accomodate 2.12.0.0. No changes necessary

Bump Win32 bound

---

cabal-install/src/Distribution/Client/CmdListBin.hs
changelog.d/issue-7326

Fixes #7326.
---
I made a cabal project with an executable same name as the package. list-bin complained of ambiguity. Compiled and ran this version successfully.

Assume list-bin target selectors are for executables

---

.github/workflows/artifacts.yml
.github/workflows/bootstrap.yml
.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/quick-jobs.yml
.github/workflows/windows.yml
templates/ci-artifacts.template.yml
templates/ci-bootstrap.template.yml
templates/ci-linux.template.yml
templates/ci-macos.template.yml
templates/ci-quick-jobs.template.yml
templates/ci-windows.template.yml

Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#7308 Let CI jobs run on all PRs, not just those rooted off master.**
I want to use stack diffs (https://github.com/ezyang/ghstack/) to
submit PRs to Cabal.  Stack diffs, simply by virtue of what they
are, are PRs that are targeted to branches that are not master (they
target an appropriate base that lets GitHub render only the change
in question, even if there are other changes below it.)  However,
I don't get CI jobs on those stack diffs because the current
pull_request branch selector is too restrictive.  This PR makes
it less restrictive.
This PR is submitted using ghstack to validate that this indeed
works.
Signed-off-by: Edward Z. Yang <ezyang@fb.com>

Let CI jobs run on all PRs, not just those rooted off master.

---

cabal-install/cabal-install.cabal.dev
cabal-install/cabal-install.cabal.prod
cabal-install/cabal-install.cabal.zinza

#7195 just modified the .cabal file. CI should have caught that but it didn't, I have no idea why. It only caught it later in a backport: https://github.com/haskell/cabal/runs/2149553218
Closes #7077 for real this time

Actually propagate base16-bytestring 1.0 to all cabal files

---

Cabal/Cabal.cabal

Declare compatibility with Win32-2.12.0.0. No functional changes necessary; just a bounds bump.

Bump Win32 upper bound

---

cabal-install/src/Distribution/Client/CmdInstall.hs
cabal-install/src/Distribution/Client/CmdInstall/ClientInstallFlags.hs

Context: for the nth time, that confusing message pointed an user to `--lib` when it should have pointed them to `build-depends` instead  https://old.reddit.com/r/haskell/comments/mj7kv5/monthly_hask_anything_april_2021/gtwlp46/
I rewrote the message so that it suggests `build-depends` first, and requires (or at least encourages) people to know what ghc environments are before using `--lib`.
I also marked `--lib` as provisional, because that's what it is
---

Mark "install --lib" as provisional

---

Cabal/src/Distribution/Simple/GHC.hs
cabal-testsuite/PackageTests/CmmSourcesDyn/cabal.out
cabal-testsuite/PackageTests/CmmSourcesDyn/cabal.project
cabal-testsuite/PackageTests/CmmSourcesDyn/cabal.test.hs
cabal-testsuite/PackageTests/CmmSourcesDyn/cbits/HeapPrim.cmm
cabal-testsuite/PackageTests/CmmSourcesDyn/cmmexperiment.cabal
cabal-testsuite/PackageTests/CmmSourcesDyn/demo/Main.hs
cabal-testsuite/PackageTests/CmmSourcesDyn/setup.out
cabal-testsuite/PackageTests/CmmSourcesDyn/setup.test.hs
cabal-testsuite/PackageTests/CmmSourcesDyn/src/Demo.hs

Fixes #7182 
Patch is by @bgamari, I have just rebased it on master as requested by @phadej in #7183
---

Include `cmm-sources` when linking shared objects

---

Cabal/src/Distribution/Simple/Hpc.hs
Cabal/src/Distribution/Simple/Program/Hpc.hs
Cabal/src/Distribution/Simple/Test.hs
Cabal/src/Distribution/Simple/Test/ExeV10.hs
Cabal/src/Distribution/Simple/Test/LibV09.hs

Currently, if you have multiple packages in a project and try and run
the test suite of a single package with --enable-coverage, hpc will fail
to run. The problem is that _all_ dependencies of the package are built
with `-fhpc`, but when we run `hpc markup`, we are only passing the
`.mix` directory of the package being tested. Because we built all
dependencies with `-fhpc` and we haven't excluded them from the report,
we need to supply their `.mix` directories too.
The above suggests one fix - compute the transitive closure of all
`.mix` directories. However, there is another solution - change from
using an exclude-list to using an include-list. This is the approach
used in this commit.
Explicitly enumerating all modules to _include_ in the report is simpler
to code, but is also more …

Fix test --enable-coverage for multi-package projects

---

cabal-testsuite/PackageTests/CmmSourcesDyn/demo/Main.hs

Fixes a CI regression merged in #7252 due to https://gitlab.haskell.org/ghc/ghc/-/issues/19397. An issue has been raised to track the followup: https://github.com/haskell/cabal/issues/7363

Workaround for failing test due to GHC #19397

---

Cabal/src/Language/Haskell/Extension.hs
changelog.d/pr-7349
editors/vim/syntax/cabal.vim

* Treat `GHC2021` as a language rather than a language extension
* Fix the spellings of the `FieldSelectors` and `OverloadedRecordDot` extensions
---

Fixes for GHC 9.2

---

changelog.d/issue-7370
doc/cabal-project.rst

Added a declaimer (copied and changed) from the `with-compiler` section to the `compiler` section of the cabal project description part of the docs to assist with #7370 

Documented limitation with compiler field in project files 

---

cabal-install/src/Distribution/Client/CmdInstall.hs
cabal-install/src/Distribution/Client/ProjectBuilding.hs

Plus a comment and some clean-up
Fixes #7351
---
I ran `cabal install --only-download`. No test though

 Fix --only-download making install fail

---

cabal-install/cabal-install.cabal
cabal-install/src/Distribution/Client/IndexUtils.hs
cabal-install/tests/UnitTests.hs
cabal-install/tests/UnitTests/Distribution/Client/IndexUtils.hs
cabal-testsuite/src/Test/Cabal/Prelude.hs
changelog.d/pr-7295
doc/installing-packages.rst

Closes #7294 
Generated index parses `preferred-versions` file contents.
The plan is to allow **one** preferred-versions file in the top-level of the LocalRepo location. 
Example:
```
index/
├── base-3.0.3.1.tar.gz
│   └── base.cabal
├── base-3.0.3.2.tar.gz
│   └── base.cabal
├── base-4.0.0.0.tar.gz
│   └── base.cabal
├── template-haskell-2.3.0.0.tar.gz
│   └── template-haskell.cabal
├── template-haskell-2.3.0.1.tar.gz
│   └── template-haskell.cabal
├── template-haskell-2.4.0.0.tar.gz
|   └── template-haskell.cabal
├── noindex.cache
└── preferred-versions
```
where `preferred-versions` contains the accumulated preferred versions, similar to how it looks in https://hackage.haskell.org/packages/preferred.
The `preferred-versions` are serialised into `noindex.cache` and can be read from the …

Add 'preferred-versions' support for LocalIndexRepo 

---

Cabal/src/Distribution/Simple/GHC.hs
cabal-testsuite/PackageTests/GhcPkgGuess/SameDirectory/setup.cabal.out
cabal-testsuite/PackageTests/GhcPkgGuess/SameDirectory/setup.out
cabal-testsuite/PackageTests/GhcPkgGuess/SameDirectoryGhcVersion/setup.cabal.out
cabal-testsuite/PackageTests/GhcPkgGuess/SameDirectoryGhcVersion/setup.out
cabal-testsuite/PackageTests/GhcPkgGuess/SameDirectoryVersion/setup.cabal.out
cabal-testsuite/PackageTests/GhcPkgGuess/SameDirectoryVersion/setup.out
changelog.d/pr-7392

Motivation
----------
Often times, the user facing `ghc` binary is
symlinked by other forces, such as the package manager,
tooling like ghcup etc. As such, the naming convention
(version suffix in particular) may not align with the
assumptions made in Cabal and it may find an incorrect ghc-pkg.
See:
- https://github.com/haskell/cabal/issues/7390
- https://gitlab.haskell.org/ghc/ghc/-/issues/18807
- https://gitlab.haskell.org/haskell/ghcup-hs/-/issues/73
Solution
--------
Guessing the ghc-pkg path is already a hack and will be solved
more appropriately in the future, see
- https://gitlab.haskell.org/ghc/ghc/-/merge_requests/4214
- https://gitlab.haskell.org/ghc/ghc/-/snippets/2710
These patches will solve the issue for future GHC versions.
As such, this patch provides a workaround for …

Prefer canonicalized path when guessing tools from GHC path

---

doc/getting-started.rst

Explain why an older cabal-version is used

---

cabal.project.coverage

This PR addresses #7384 by deliberately keeping the project coverage details encapsulated in a dedicated `.project` file so the main build will not result in .tix file litter.

remove coverage from main cabal.project, add to dedicated file

---

cabal-install/src/Distribution/Client/CmdConfigure.hs
cabal-install/src/Distribution/Client/CmdExec.hs
cabal-install/src/Distribution/Client/CmdFreeze.hs
cabal-install/src/Distribution/Client/CmdRun.hs
cabal-install/src/Distribution/Client/ProjectConfig.hs
cabal-testsuite/PackageTests/NewConfigure/ConfigFile/ConfigFile.cabal
cabal-testsuite/PackageTests/NewConfigure/ConfigFile/Setup.hs
cabal-testsuite/PackageTests/NewConfigure/ConfigFile/cabal.out
cabal-testsuite/PackageTests/NewConfigure/ConfigFile/cabal.project
cabal-testsuite/PackageTests/NewConfigure/ConfigFile/cabal.test.hs
cabal-testsuite/PackageTests/NewFreeze/FreezeFile/new_freeze.out
cabal-testsuite/PackageTests/NewFreeze/FreezeFile/new_freeze.test.hs
changelog.d/pr-7407

Changes the behavior of the following commands under the --dry-run flag
- `v2-configure` and `v2-freeze` no longer write files.
- `v2-exec` and `v2-run` print out the command that would've been
executed rather than doing so.
Adds package tests for the configure and freeze commands.
---

Increase effect of --dry-run flag (#7379)

---

cabal-install/src/Distribution/Client/CmdConfigure.hs
cabal-install/src/Distribution/Client/CmdExec.hs
cabal-install/src/Distribution/Client/CmdFreeze.hs
cabal-install/src/Distribution/Client/CmdRun.hs
cabal-install/src/Distribution/Client/ProjectConfig.hs
cabal-testsuite/PackageTests/NewConfigure/ConfigFile/ConfigFile.cabal
cabal-testsuite/PackageTests/NewConfigure/ConfigFile/Setup.hs
cabal-testsuite/PackageTests/NewConfigure/ConfigFile/cabal.out
cabal-testsuite/PackageTests/NewConfigure/ConfigFile/cabal.project
cabal-testsuite/PackageTests/NewConfigure/ConfigFile/cabal.test.hs
cabal-testsuite/PackageTests/NewFreeze/FreezeFile/new_freeze.out
cabal-testsuite/PackageTests/NewFreeze/FreezeFile/new_freeze.test.hs
changelog.d/pr-7407

Backport of #7407, fixes the conflict in #7427
(cherry picked from previous version of commit 84884bbc21a63b61d698138f549baae152efd878)

Increase purview of --dry-run and --only-download flags (#7379) (Backport of #7407)

---

cabal-install/cabal-install.cabal
cabal-install/main/Main.hs
cabal-install/src/Distribution/Client/CmdOutdated.hs
cabal-install/src/Distribution/Client/Setup.hs

Move `Outdated` to `CmdOutdated` module.
Modifications include:
* Explicit imports
* Removes redundant parenthesis
* Reformats the code-style to fit to other `Cmd*` modules
* Remove old code-paths from `cabal-install/src/Distribution/Client/Setup.hs`
Pre-step for #6815, performs no actual behaviour modification.
I started with this refactoring, noticing a bit too late that it is probably not completely necessary for #6815, but submitting it now anyway as I deem it helpful. Feel free to correct me, though!
---

Modernise `outdated` command

---

Cabal/src/Distribution/PackageDescription/Check.hs
changelog.d/rel-path-check

Should fix #7426.
---
Leaving testing to the CI, but the existing tests didn't seem to catch the bug, and going digging to figure out the test format to add one that would seemed like it would take longer than it did to find, diagnose, and fix in the first place.

Allow relative paths starting with single-character directories

---

cabal-install/src/Distribution/Client/CmdBuild.hs
cabal-install/src/Distribution/Client/CmdConfigure.hs
cabal-install/src/Distribution/Client/CmdExec.hs
cabal-install/src/Distribution/Client/CmdOutdated.hs
cabal-install/src/Distribution/Client/ProjectFlags.hs

closes #6815 
---
I tested it manually that it uses the correct freeze file.

Prefer ProjectFlags over additional field in OutdatedFlags

---

cabal-install/src/Distribution/Client/Init/FlagExtractors.hs
cabal-install/src/Distribution/Client/Init/Interactive/Command.hs
cabal-install/src/Distribution/Client/Init/Prompt.hs
cabal-install/src/Distribution/Client/Init/Types.hs

This PR aims to fix #7464. For any field that is both optional and don't have a default value, an `"[optional]"` "tag" will be appended next to the input location.
---

Inidication that a field is optional for cabal init prompts

---

cabal-install/src/Distribution/Client/Init/Interactive/Command.hs

This PR removes an unnecessary print statement during the init process when the package dir matches a hackage package name. 
---

Remove redundant init message for hackage dir name

---

Cabal/src/Distribution/PackageDescription/Check.hs
cabal-testsuite/PackageTests/Backpack/Includes2/cabal-internal.out
cabal-testsuite/PackageTests/BuildDeps/InternalLibrary1/cabal.out
cabal-testsuite/PackageTests/BuildTools/Internal/cabal.out
cabal-testsuite/PackageTests/CmmSources/cabal.out
cabal-testsuite/PackageTests/CmmSourcesDyn/cabal.out
cabal-testsuite/PackageTests/InternalLibraries/cabal.out
cabal-testsuite/PackageTests/InternalVersions/BuildDependsExtra/setup.cabal.out
cabal-testsuite/PackageTests/InternalVersions/BuildDependsExtra/setup.out
cabal-testsuite/PackageTests/InternalVersions/BuildDependsExtra/setup.test.hs
cabal-testsuite/PackageTests/InternalVersions/BuildToolDependsExtra/setup.cabal.out
cabal-testsuite/PackageTests/InternalVersions/BuildToolDependsExtra/setup.out
cabal-testsuite/PackageTests/InternalVersions/BuildToolDependsExtra/setup.test.hs
cabal-testsuite/PackageTests/InternalVersions/BuildToolsExtra/setup.cabal.out
cabal-testsuite/PackageTests/InternalVersions/BuildToolsExtra/setup.out
cabal-testsuite/PackageTests/InternalVersions/BuildToolsExtra/setup.test.hs
cabal-testsuite/PackageTests/MultipleLibraries/T6083Post/cabal.out
cabal-testsuite/PackageTests/MultipleLibraries/T6083PostMixin/cabal.out
cabal-testsuite/PackageTests/MultipleLibraries/T6894/cabal.out
cabal-testsuite/PackageTests/Regression/T5309/cabal.out
cabal-testsuite/PackageTests/Regression/T5677/cabal.out
cabal-testsuite/PackageTests/TestSuiteTests/ExeV10/cabal.out
changelog.d/pr-7470-backport

Backport from #7470
(cherry picked from commit 81fccc550da400d00075120244e490ec459330f3)

Commenting out extraneous version warnings (Backport of #7470)

---

.github/workflows/macos.yml
templates/ci-macos.template.yml

For some reason, `cabal v2-install cabal-plan` installs the library on macos instead of the executable, causing CI failures such as: https://github.com/haskell/cabal/pull/7477/checks?check_run_id=3170346447
Logs from CI:
``` 
cd $(mktemp -d)
cabal v2-install cabal-plan --constraint='cabal-plan ^>=0.6.2.0' --constraint='aeson +fast'
shell: /bin/bash -e {0}
Build profile: -w ghc-8.8.3 -O1
- base-compat-0.11.2 (lib) (requires download & build)
- base-orphans-0.8.4 (lib) (requires download & build)
- base16-bytestring-0.1.1.7 (lib) (requires download & build)
- dlist-1.0 (lib) (requires download & build)
- hashable-1.3.2.0 (lib) (requires download & build)
- indexed-traversable-0.1.1 (lib) (requires …
```

Force cabal to use a build plan where exe:cabal-plan is enabled

---

.github/workflows/macos.yml
templates/ci-macos.template.yml

Backport 3.6: Force cabal to use a build plan where exe:cabal-plan is enabled

---

cabal-install-solver/src/Distribution/Solver/Types/PackageIndex.hs

This changes the `PackageIndex` in the solver to make certain invariant checks that were previously `assert` into `expensiveAssert` which ensures they'll never make it into a production executable. Should significantly (20%?) speed up solver time. Related to #7466

set package index asserts expensive

---

doc/cabal-commands.rst

With Backpack interoperability problems now resolved, the related warnings in
the documentation can probably be removed. [1]
Drops the sole warning located by a text search for "6005".
[1] https://github.com/haskell/cabal/issues/6005#issuecomment-850468676
---

Drop obsolete Backpack warning from Chapter 6. (See: #6005)

---

Cabal/src/Distribution/Simple.hs
changelog.d/pr-7510

No tests, because they depend on a particular version of autoconf and I think the current tests of autoconf would already fail with the new autoconf version on Windows CI (but either they are not run on Windows or autoconf on CI is old; they are run on Linux, because setting PATH_SEPARATOR breaks these tests and @jneira kindly reproduced the fail on Windows locally).
---

Set PATH_SEPARATOR=; when calling ./configure; fix #7494

---

doc/cabal-commands.rst

Doc change only, moving target forms to its own section and adding a warning about install all as the target, see #6769.

Move target forms to its own section, warning about install all.

---

Cabal/src/Distribution/Simple/Program/Script.hs

The command echo behaves differently in different shells whereas printf is more portable. This means `runhaskell Setup register --gen-script` may generate a buggy script for some shells. if there are escape sequences in the package description.
Although all shells have echo the implementations is different. POSIX says: if the first argument is -n or any argument contains backslashes, then the behaviour is unspecified. The scripts currently produced are only guaranteed to work correctly in bash-like shells.
Some packages such as [lens](https://github.com/ekmett/lens/blob/master/lens.cabal#L79) contain backslashes in their descriptions. In this case the 'register.sh' script produced by `runhaskell Setup register --gen-script` does not behave consistently for different shells. You can test …

Change echo to printf

---

cabal-install-solver/src/Distribution/Solver/Modular/Cycles.hs
cabal-install-solver/src/Distribution/Solver/Modular/Explore.hs
cabal-install-solver/src/Distribution/Solver/Modular/Linking.hs
cabal-install-solver/src/Distribution/Solver/Modular/Preference.hs
cabal-install-solver/src/Distribution/Solver/Modular/Solver.hs
cabal-install-solver/src/Distribution/Solver/Modular/Tree.hs
cabal-install-solver/src/Distribution/Solver/Modular/Validate.hs
cabal-install-solver/src/Distribution/Solver/Modular/WeightedPSQ.hs

This is the last refactor I had in mind to address the general performance issues discussed in https://github.com/haskell/cabal/issues/7466
It attains some modest but real improvement (mainly in allocations) from eliminating the intermediate `cata` calls in favor of explicit recursion in the solver tree.
For `trav` calls, rather than eliminate them entirely, it lifts out their intermediate functions to the top level and explicitly fuses them in the solver pipeline, which yields somewhat more significant improvements.
Overall not the huge win I hoped, but nonetheless given the straightforward nature of the changes to the code, still worth it I think.

solver: swap catas with recursion, fuse travs

---

Cabal/src/Distribution/GetOpt.hs

This was a leftover from the first iteration in #7190 where we used to map over optNames, but it's not needed anymore.

GetOpt: Make OptHelp less polymorphic

---

Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
Cabal/src/Distribution/PackageDescription/Check.hs
Cabal/src/Distribution/Simple/Utils.hs
Cabal/src/Distribution/Verbosity.hs
Cabal/src/Distribution/Verbosity/Internal.hs
cabal-testsuite/PackageTests/Backpack/Includes2/cabal-internal.out
cabal-testsuite/PackageTests/BuildDeps/InternalLibrary1/cabal.out
cabal-testsuite/PackageTests/BuildTools/Internal/cabal.out
cabal-testsuite/PackageTests/CmmSources/cabal.out
cabal-testsuite/PackageTests/CmmSourcesDyn/cabal.out
cabal-testsuite/PackageTests/InternalLibraries/cabal.out
cabal-testsuite/PackageTests/InternalVersions/BuildDependsExtra/setup.test.hs
cabal-testsuite/PackageTests/InternalVersions/BuildToolDependsExtra/setup.test.hs
cabal-testsuite/PackageTests/InternalVersions/BuildToolsExtra/setup.test.hs
cabal-testsuite/PackageTests/MultipleLibraries/T6083Post/cabal.out
cabal-testsuite/PackageTests/MultipleLibraries/T6083PostMixin/cabal.out
cabal-testsuite/PackageTests/MultipleLibraries/T6894/cabal.out
cabal-testsuite/PackageTests/Regression/T5213/cabal.out
cabal-testsuite/PackageTests/Regression/T5213ExeCoverage/cabal.out
cabal-testsuite/PackageTests/Regression/T5309/cabal.out
cabal-testsuite/PackageTests/Regression/T5677/cabal.out
cabal-testsuite/PackageTests/TestSuiteTests/ExeV10/cabal.out
changelog.d/pr-7470
changelog.d/pr-7470-backport

This PR will add the ability to suppress all warnings within a given command. For example, to suppress all warnings in `cabal build`, while keeping the output verbose: `cabal build --verbose="verbose+nowarn"`.
This PR serves as a palliative measure for #7286, while also doubling up on adding a new feature.
---

Suppress warnings for verbosity

---

doc/getting-started.rst

Removes the special case for installing the Haskell toolchain on Windows, because ghcup now also supports Windows.
---

ghcup supports Windows

---

cabal-install/src/Distribution/Client/CmdHaddock.hs
cabal-install/src/Distribution/Client/ProjectBuilding.hs
cabal-install/src/Distribution/Client/ProjectConfig.hs
cabal-install/src/Distribution/Client/ProjectConfig/Types.hs
cabal-install/src/Distribution/Client/Utils.hs
changelog.d/pr-7550
doc/cabal-project.rst

Both `stack` and other package managers like `cargo` have an `--open`
flag for the common case of opening documentation locally for
inspection or reference. This patch adds a `--open` flag, which when set
tries to open the HTML file associated with the generated
documentation, either through `xdg-open` (Linux) or `open` (macOS).
This is my first patch to `cabal`, so please inform me if I’ve made some obvious error apparent to someone with more experience in this codebase. I haven’t yet ported this functionality to `haddock` itself, but I can should that be necessary.
I tested this by, in the `cabal` project, invoking `cabal run cabal-install:exe:cabal -- haddock Cabal --open`.
Fixes #7366.

Add --open flag to `cabal haddock`

---

doc/cabal-package.rst

Fix #7469: broken link to "prefix independence" in docs.
I tested this by building the documentation with sphinx and checking that the link now works.
---

Fix #7469: broken link to "prefix independence" in docs

---

Cabal/src/Distribution/Utils/Path.hs

Fix #7582: add `Ord` to the derived instances of `SymbolicPath`.
- Tested by checking compilation.
- Given the granularity of the changelog, this change is below the threshold.
---

Fix #7582: add Ord to the derived instances of SymbolicPath

---

.github/mergify.yml

This change has been made by @fgaz from https://mergify.io config editor.
---
actions/merge/strict is deprecated, so I switched it to merge queues.
I also changed the merge method from squash to rebase+merge, for a clean history (provided prs are clean too), which _I think_ was the original intent behind the introduction of this bot. Opinions? Maybe there should be both this and a "squash+merge me" label for squashable atomic prs so that we don't have to ask the author to do it when it's necessary?
edit: added the squash strategy too

ci(Mergify): use rebase+merge queue

---

cabal-install/src/Distribution/Client/ProjectBuilding.hs

Resolves #6267 and #6114
This is a conservative cut at which flags to ignore, on the grounds its better to be safe than sorry. It can always be expanded based on other requests.

don't consider test flags in reconfigure check

---

Cabal-tests/Cabal-tests.cabal
Cabal-tests/tests/UnitTests.hs
Cabal-tests/tests/UnitTests/Distribution/Simple/Command.hs
Cabal/src/Distribution/GetOpt.hs
Cabal/src/Distribution/ReadE.hs
Cabal/src/Distribution/Simple/Command.hs
changelog.d/option-argument-errors

This addresses issue #7573.
Before:
```
$ cabal build cabal-install -v=3
=3
error, called at ./Distribution/ReadE.hs:42:24 in Cbl-3.4.0.0-ee8b7702:Distribution.ReadE
$ cabal build --max-backjumps=abc
Cannot parse number: abc
error, called at ./Distribution/ReadE.hs:42:24 in Cbl-3.4.0.0-ee8b7702:Distribution.ReadE
```
After:
```
$ cabal run cabal-install:cabal -- build -v=3
cabal: invalid argument to option `-v': =3
$ cabal run cabal-install:cabal -- build --max-backjumps=abc
cabal: invalid argument to option `--max-backjumps': Cannot parse number: abc
```
---

Handle option argument parse errors without 'error' (fixes #7573)

---

cabal-install/src/Distribution/Client/Setup.hs

Resolves https://github.com/haskell/cabal/issues/2612
Motivated by https://github.com/haskell/cabal/issues/5346 this exposes a few more global flags in `cabal --help` -- particularly active-repositories, and store-dir, which are both useful. It also hides default-user-config which is a v1-freeze thing that I think never acquired much traction. And while we're at it, documents a bit what the flags that aren't exposed are, to help with future cleanup efforts.

change documented global flags

---

Cabal/Cabal.cabal

`text-2.0` is not yet released, but I would like to update `Cabal` (not `cabal-install`) HEAD so that we can bump `text` submodule in GHC source tree and start patching of `head.hackage` to iron out potential migration issues before a final release. Cf. https://github.com/haskell/parsec/pull/135
`Cabal` package does not really delve into `text` deep enough to be affected by `text-2.0` changes, and I checked all usages manually.

Allow text-2.0 in Cabal.cabal only

---

cabal-install-solver/src/Distribution/Solver/Types/PkgConfigDb.hs
cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL/TestCaseUtils.hs
cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs
changelog.d/pr-7621

Potentially resolves https://github.com/haskell/cabal/issues/7448
This is a one lexeme change that I would argue "fixes" `pkgconfig-depends` handling in the solver. Before, if there was no `pkg-config` that could be found, the solver would optimistically succeed. But since the builder then requires using `pkg-config` to get the linking flags, this would necessarily fail on build anyway. Now, we fail. This lets a user set up an auto flag that toggles between using a `pkgconfig-depends` and explicit `extra-libraries` etc stanza.
I _think_ this gives a nice solution that is strictly better than the prior situation.

Backtrack when no pkgconfigdb is present

---

.gitlab-ci.yml
.gitlab/ci.sh
.gitlab/shell.nix
cabal.project

https://gitlab.haskell.org/maerwald/cabal/-/pipelines/40563 all green

Add darwin aarch64 support to CI

---

cabal-install/src/Distribution/Client/BuildReports/Anonymous.hs
cabal-install/src/Distribution/Client/ProjectOrchestration.hs
cabal-install/src/Distribution/Client/ProjectPlanning.hs

Resolves #6851 -- or rather resolves it enough for the purposes of hackage builder, which is likely the only thing that ever cared about these flags.
In particular makes the `--report-planning-failure` and `--build-summary` flags do anything at all. Note that this preserves the v1 behavior that by default, build-summary information for all builds gets written to ~/.cabal/logs/build.log (which had been lost with v2-build before). The former flag writes build-summary info even if the solver fails (otherwise such info is written only if a build occurs). The latter controls where to write summary info to.
Some notes on what this doesn't do:
This does _not_ provide the still missing "remote build reports" (enabled by `--remote-build-reporting`) since hackage builder doesn't use them, and …

handle build reports in v2-build

---

doc/cabal-package.rst

Fix #4894: document alternatives to write a tested-with list
A grab-bag of alternatives as discussed at haskell/cabal#4894.
This PR is based on PR #7603 to get extra sphinx sanity checking.

Additional examples in doc of `tested-with` (fix #4894)

---

.github/workflows/users-guide.yml

Simplified from agda/agda/.github/workflows/user-manual.yml
Simple minded.  Builds doc by
- installing python
- `make users-guide`
- upload-artifact
Maybe something more sophisticated could be done later where we push to `ghpages` or something.
Tested by downloading the artifact and having a rough look.
See new job __Users guide__ in the checks below.  Should maybe also switched to "Required".

CI for building doc with sphinx

---

cabal-testsuite/README.md

cabal-testsuite/README: typos, formatting
Dotting some `i`s.
---

cabal-testsuite/README: typos, formatting

---

Makefile

cabal list-bin was introduced in cabal-install 3.4, so it's safe to
assume every cabal _developer_ has it by now. By using that, we
remove the dependency on cabal-plan from the Makefile (though it's still
present in other places).
---
---
I'm not sure if CI will be fine with this though. some jobs are run with older images. on the other hand, CI doesn't use many make commands. let's see...

Change cabal-plan list-bin to cabal list-bin in Makefile

---

Cabal/src/Distribution/Simple.hs
changelog.d/pr-7510

This reverts PR #7510 due to regression #7649. This revert reintroduces the problem from #7494, but it's going to be fixed differently (most probably) soon.

Revert PR #7510 (which was "Set PATH_SEPARATOR=; when calling ./configure")

---

.github/workflows/windows.yml
templates/ci-windows.template.yml

A part of the effort to prevent hiccups like #7649.
I've tested that it fails with 3.6, works after reverting the offending autoconf PR, once the new CI jobs are merged, I will test if the new autoconf fix passes with it.
I've also fixed some details in he previous CI jobs from the workflow and bumped cabal used for bootstrapping from 3.2 to 3.4 in order to make `list-bin` available, needed for the dogfooding jobs.
Citing IRC:
> I will build master, wipe out store, build master again using the exe just obtained
> this is an automatic replication of the test with which @jneira originally detected #7649
> let's see if that's longer than current CIs
> (that was Tamar's reservation about this idea, I think)
> our windows.yml CI workflow builds network as part of all cabal deps (and cabal …

Add CI dogfood test; only Windows for this PR

---

Cabal/src/Distribution/Simple/Build/PathsModule/Z.hs
templates/Paths_pkg.template.hs

Generate Paths_ module with qualified Data.List.last import

---

.github/workflows/quick-jobs.yml
cabal-dev-scripts/cabal-dev-scripts.cabal
templates/ci-quick-jobs.template.yml

This PR is the second aiming to eliminate the recent CI failures. This one seems to be caused by a bumped GHC version on GHA that also bump `TH` that forces `lens` bump that conflicts with bounds in cabal-dev-scripts.cabal.

Try to fix CI/Meta-checks failure

---

Cabal/src/Distribution/Simple.hs

Should fix #7649 but I don't have msys2 on this machine so other than building Cabal I can't test until I get home.
@jneira @Mikolaj , @jneira could you test this until then?
---

Windows: rewrite paths to configure

---

.github/workflows/quick-jobs.yml
cabal-dev-scripts/cabal-dev-scripts.cabal
templates/ci-quick-jobs.template.yml

Manual backport of #7659, because it touches CI.

Try to fix CI/Meta-checks failure (backport of #7659)

---

.github/workflows/windows.yml
templates/ci-windows.template.yml

I guess I mistakenly removed it when resolving a conflict in backport
of #7653 in c3354c96cbfdad3fac8afcce9c5806f77187bcee,
because on master these omitted lines are absent.
BTW, this backport was not reviewed, by my mistake.
A good example why careful reviews are essential.
Sadly, this PR will get in without reviews, too, because we are 
greatly lagging behind with reviews this week.

Bring back cabal-install-dev call removed by backport of #7653

---

Cabal/src/Distribution/Simple.hs

This is a backport of pull request #7652, because the automatic one failed and could not be automatically redone.

Windows: rewrite paths to configure (backport #7652) 

---

Makefile

Reverts haskell/cabal#7648
The replacement of `cabal-plan list-bin` by `cabal list-bin` did not work for macOS.
Details see https://github.com/haskell/cabal/pull/7648#issuecomment-924111500.

Revert "Change cabal-plan list-bin to cabal list-bin in Makefile"

---

cabal-install/src/Distribution/Client/Init/FileCreators.hs
cabal-install/src/Distribution/Client/Init/Format.hs
cabal-install/tests/UnitTests/Distribution/Client/Init/Golden.hs
cabal-install/tests/fixtures/init/golden/cabal/cabal-lib-and-exe-no-comments.golden
cabal-install/tests/fixtures/init/golden/cabal/cabal-lib-and-exe-with-comments.golden
cabal-install/tests/fixtures/init/golden/cabal/cabal-lib-no-comments.golden
cabal-install/tests/fixtures/init/golden/cabal/cabal-lib-with-comments.golden
cabal-install/tests/fixtures/init/golden/cabal/cabal-test-suite-no-comments.golden
cabal-install/tests/fixtures/init/golden/cabal/cabal-test-suite-with-comments.golden
cabal-install/tests/fixtures/init/golden/exe/exe-build-tools-with-comments.golden
cabal-install/tests/fixtures/init/golden/exe/exe-minimal-no-comments.golden
cabal-install/tests/fixtures/init/golden/exe/exe-simple-minimal-with-comments.golden
cabal-install/tests/fixtures/init/golden/exe/exe-with-comments.golden
cabal-install/tests/fixtures/init/golden/exe/exe.golden
cabal-install/tests/fixtures/init/golden/lib/lib-build-tools-with-comments.golden
cabal-install/tests/fixtures/init/golden/lib/lib-minimal-no-comments.golden
cabal-install/tests/fixtures/init/golden/lib/lib-simple-minimal-with-comments.golden
cabal-install/tests/fixtures/init/golden/lib/lib-simple.golden
cabal-install/tests/fixtures/init/golden/lib/lib-with-comments.golden
cabal-install/tests/fixtures/init/golden/lib/lib.golden
cabal-install/tests/fixtures/init/golden/test/standalone-test-with-comments.golden
cabal-install/tests/fixtures/init/golden/test/standalone-test.golden
cabal-install/tests/fixtures/init/golden/test/test-build-tools-with-comments.golden
cabal-install/tests/fixtures/init/golden/test/test-minimal-no-comments.golden
cabal-install/tests/fixtures/init/golden/test/test-simple-minimal-with-comments.golden
cabal-install/tests/fixtures/init/golden/test/test-with-comments.golden
cabal-install/tests/fixtures/init/golden/test/test.golden

This PR aims to add common stanzas to the `cabal init` command and possible default flags that could go with it. This PR will close #7465.
---

`cabal init` common stanzas and default flags

---

README.md

The irc channel is not very discoverable so let's fix that!
---
https://github.com/fgaz/cabal/tree/readme-chat-links#readme

Add links to irc/matrix chat to readme

---

Cabal/src/Distribution/Simple/GHC.hs
changelog.d/pr-7581

GHC does not support response files (@file), so we are constrained in
how many characters we can pass to ghc invocations. On macOS <11 this
is 262144 (getconf ARG_MAX), but this also includes the environment
which can be very big. On Windows, ARG_MAX is probably even
less (32K?).
In projects with a lot of modules being linked (1000+), it’s very easy
to hit this limit because of the long length of cabal v2- build
prefixes. For example:
/Users/matthewbauer/my-haskell-project/dist-newstyle/build/x86_64-osx/ghc-8.10.3/mwb-0/noopt/build/Some/Generic/ModulePrefix/MyModule.dyn_o
is 139 chars and 139 * 1200 = 166800. This leads to errors like:
> ghc: createProcess: runInteractiveProcess: exec: resource exhausted (Argument list too long)
To minimize this likelihood, we should limit the path …

Make GHC targetDir commands relative to current directory

---

.github/workflows/users-guide.yml
.gitignore
Makefile
doc/Makefile
doc/pyproject.toml
doc/requirements.in
doc/requirements.txt

Re #7777 #7778: check `requirements.txt` for security advisory:
There is a new make file, `doc/Makefile`, that defines these goals:
- `check-requirements`:
Check requirements.txt for security problems (CVEs) using `skjold`.
This goal is intended for CI.
- `build-and-check-requirements`:
Rebuild `requirements.txt` from `requirements.in` using `pip-compile`, and check.
This goal is intended for manual invocation.
It is invoked from the top `Makefile` via goal `users-guide-requirements`.
Alternatively, these goals could be coupled with the doc build `make users-guide`.  However, since these goals require a couple of seconds to run, I think it is annoying to call them on every build of the documentation.
Workflow `Users guide` now includes `check-requirements`.

Re #7777 #7778: check requirements.txt for security advisory

---

Cabal/Cabal.cabal
Cabal/src/Distribution/Compat/Prelude.hs
Cabal/src/Distribution/FieldGrammar/FieldDescrs.hs
Cabal/src/Distribution/FieldGrammar/Parsec.hs
Cabal/src/Distribution/Simple/Configure.hs
Cabal/src/Distribution/Simple/UHC.hs
Cabal/src/Distribution/Utils/String.hs
cabal-install/src/Distribution/Client/HttpUtils.hs
cabal-install/src/Distribution/Client/Init/Utils.hs
cabal-install/src/Distribution/Client/Upload.hs

Attempt to fix #7744 .
That's my first ever cabal PR so I somehow don't know what I'm doing. Just picked up first `good-first-issue` because I've found this https://twitter.com/bkmlep/status/1432474203245015040
`Distribution.Utils.String` sounds like a good place for `trim` but I had to expose this module unfortunately. 
This the situation after my change:
Any advice or criticism fully welcomed!
Karol
---

Remove code duplication and unify definition of 'trim' function.

---

doc/cabal-commands.rst

Doc change only, added to the existing warning block for `cabal install`, fixes #7275.

Warn about needing to opt in to overwrite-policy for install.

---

Cabal/src/Distribution/Compat/Graph.hs
Cabal/src/Distribution/Utils/IOData.hs

[GHC Proposal #371](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0371-non-magical-eq.md) requires `TypeOperators` to use type equality `a~b`. The following lines are affected:
```
Cabal/src/Distribution/Compat/Graph.hs
181:instance (IsNode a, IsNode b, Key a ~ Key b) => IsNode (Either a b) where
Cabal/src/Distribution/Utils/IOData.hs
61:instance a ~ Char => KnownIODataMode [a] where
```
The fix is to simply enable the extension.

Enable TypeOperators to use (~)

---

cabal-install/src/Distribution/Client/Init/Interactive/Command.hs
cabal-install/src/Distribution/Client/Init/NonInteractive/Command.hs
cabal-install/src/Distribution/Client/Init/Utils.hs
cabal-install/tests/UnitTests/Distribution/Client/Init/NonInteractive.hs

Fixes #7836. ~Testing depends on #7831.~
---

Prepend library to executable deps in cabal init

---

cabal-install/src/Distribution/Client/CmdInstall.hs
cabal-install/src/Distribution/Client/CmdInstall/ClientInstallFlags.hs
cabal-install/src/Distribution/Client/Init/Prompt.hs
cabal-install/src/Distribution/Client/Init/Types.hs
cabal-install/src/Distribution/Client/InstallSymlink.hs
cabal-install/src/Distribution/Client/Types/OverwritePolicy.hs
changelog.d/pr-5672

When linking binaries into a globally accessible location on the machine `--overwrite-policy=always` is needed if an existing file sits where we are trying to create a link. This allows for a prompt-the-user strategy.
---
NA: Couldn't find any existing documentation about `overwrite-policy`.
How I tested the change:
I simply ran `cabal new-install` on `cabal-install` (after having installed `cabal-install` with my feature.

Prompt overwrite policy

---

cabal-install/src/Distribution/Client/CmdListBin.hs
cabal-install/src/Distribution/Client/CmdRun.hs
cabal-install/tests/IntegrationTests2.hs
cabal-install/tests/IntegrationTests2/targets/one-of-each/cabal.project
cabal-install/tests/IntegrationTests2/targets/one-of-each/p.cabal
doc/cabal-commands.rst

Resolves #7403
The modification was tested against https://github.com/dminuoso/cabal-repro and the added integration test.
Documentation will be updated tomorrow.
---

Set exe as default component for `cabal run` and `cabal list-bin`

---

cabal-install/src/Distribution/Client/CmdHaddock.hs
cabal-testsuite/PackageTests/HaddockWarn/Main.hs
cabal-testsuite/PackageTests/HaddockWarn/cabal.out
cabal-testsuite/PackageTests/HaddockWarn/cabal.project
cabal-testsuite/PackageTests/HaddockWarn/cabal.test.hs
cabal-testsuite/PackageTests/HaddockWarn/example.cabal
changelog.d/issue-6679

Attempt to fix #6679
Handle the `v2-haddock` error when it's ran on an invalid target
without any flags.
Now exits gracefully with helpful warning message taken from
`v1-haddock` with updated flags.
---

Fix #6679 : Warn about `v2-haddock` failure

---

cabal-install/cabal-install.cabal
cabal-install/src/Distribution/Client/Init/FileCreators.hs
cabal-install/src/Distribution/Client/Init/Types.hs
cabal-install/src/Distribution/Client/Init/Utils.hs
cabal-install/tests/UnitTests/Distribution/Client/Init.hs
cabal-install/tests/UnitTests/Distribution/Client/Init/FileCreators.hs

This PR adapts `cabal init`'s `FileCreators` module, so it has the capability to be tested through the testing machinery proper. It is also a compromise for the stalemate in #7807, as it will be unblocked.
---

Cabal init fileformat tests

---

Cabal/src/Distribution/Compat/Process.hs
changelog.d/pr-7844

---
---
I have encountered severe issue on Windows 7. `cabal` executable built with `process` 1.6.9 or later is unable to build any packages. The issue manifests itself as cabal being unable to determine version of the ghc but the actual issue is that it's process spawning mechanic is faulty.
The investigation revealed following: starting with `process` 1.6.9 the `Cabal` library enables so-called jobs for newly created processes. This is done to better detect when a spawned process terminates. Simplistically, a job is a set of processes tracked by the OS. When a relevant relevant is supplied, the processes spawned by the `process` package are assigned a …

Fix cabal on Windows 7

---

.github/workflows/bootstrap.yml
.github/workflows/quick-jobs.yml
.github/workflows/windows.yml
templates/ci-bootstrap.template.yml
templates/ci-quick-jobs.template.yml
templates/ci-windows.template.yml

A backport of d83c38b575571750d842d3fac23ec4371769d8fb and 475222dde71b4258abce8133d7005c39be4f3a14 to fix CI on 3.6.
Committed to master in #7658 and #7796.

Backport: Add ghcup install call to boostrap script to be future safe

---

Cabal/Cabal.cabal

In service of [GHC #20547](https://gitlab.haskell.org/ghc/ghc/-/issues/20547).
---

Cabal: Bump time upper bound to allow 1.12

---

Cabal/src/Distribution/Simple/Utils.hs
Cabal/src/Distribution/Verbosity.hs

Haddockumentation fixes to `Cabal`::`Distribution.Verbosity`.
- `verbose(No)Stderr` had the wrong documentation (cut&paste from timestamps)
- turned some comments into haddockumentation
- added some punctuation
---

Haddockumentation fixes to Cabal::Distribution.Verbosity.

---

cabal-install/cabal-install.cabal
cabal-install/src/Distribution/Client/Init/FileCreators.hs
cabal-install/tests/UnitTests/Distribution/Client/Init/FileCreators.hs

Disregard occurrences of "." while backing up

---

Cabal/src/Distribution/Simple/Setup.hs

Fix --repl-options parsing

---

cabal-install/main/Main.hs
cabal-install/src/Distribution/Client/Setup.hs
doc/getting-started.rst

Closes #7871. `cabal init` will now take the first value in `extraArgs` and treat it as the root directory for the new project; i.e.:
```
cabal init -n -- my-project
```
---

Extra argument for `cabal init` as starting dir

---

cabal-install/src/Distribution/Client/ProjectConfig.hs
cabal-testsuite/PackageTests/postCheckoutCommand/cabal.negative.project
cabal-testsuite/PackageTests/postCheckoutCommand/cabal.out
cabal-testsuite/PackageTests/postCheckoutCommand/cabal.positive.project
cabal-testsuite/PackageTests/postCheckoutCommand/cabal.test.hs
cabal-testsuite/PackageTests/postCheckoutCommand/example.cabal
cabal-testsuite/PackageTests/postCheckoutCommand/src/Example.hs
changelog.d/issue-7641

Attempt to fix #7641 
This fixes the crash when `post-checkout-command` option for
`source-repository-package` returns an exit status 0.
---

Fix #7641 : Fix `post-checkout-command` bug

---

Cabal/Cabal.cabal

On request of devs using Cabal sources, I'm updating semigroups dep and I will bump semigroups, time and text deps on Hackage, as a revision (and backport, as needed, to 3.6; `time` bump is already in 3.6).

Update semigroups dep and bump time and text deps on Hackage

---

Cabal/ChangeLog.md
Cabal/src/Distribution/Simple/GHC/Internal.hs
Cabal/src/Distribution/Simple/Program/GHC.hs
cabal-testsuite/PackageTests/CCompilerOverride/Main.hs
cabal-testsuite/PackageTests/CCompilerOverride/custom-cc
cabal-testsuite/PackageTests/CCompilerOverride/custom-cc.bat
cabal-testsuite/PackageTests/CCompilerOverride/foo.c
cabal-testsuite/PackageTests/CCompilerOverride/my.cabal
cabal-testsuite/PackageTests/CCompilerOverride/setup.cabal.out
cabal-testsuite/PackageTests/CCompilerOverride/setup.out
cabal-testsuite/PackageTests/CCompilerOverride/setup.test.hs
changelog.d/issue-4439

I have added test for #7874. It works by cabal package having a c file which will only compile if all the necessary defines are defined. I'm passing defines via various ways, including `cabal configure`, fields of cabal file and test that `gcc` is overridden by passing a custom script which defines final macro without which the c file will not compile.
The original patch seems to be working fine as without it the test doesn't pass. However, I noticed that the original patch only results in `cabal` passing `-pgmc` flag to `ghc`, thus overriding the C compiler. However original issue #4439 also mentioned the intention to override linker, which should have resulted in `-pgml` being passed to the `ghc`, but this doesn't happen in the original patch.

Update #7874: Add test, fix changelog

---

cabal-install/src/Distribution/Client/Init/FileCreators.hs
cabal-testsuite/PackageTests/Init/app/Main.hs
cabal-testsuite/PackageTests/Init/init.out
cabal-testsuite/PackageTests/Init/init.test.hs
cabal-testsuite/src/Test/Cabal/Prelude.hs

Backing up only when overwritting to allow cabalisation

---

doc/cabal-package.rst
doc/cabal-project.rst
doc/developing-packages.rst
doc/getting-started.rst
doc/intro.rst
doc/nix-local-build.rst
doc/setup-commands.rst

Fix #7712 fix #7803: do not link to other `.rst` files by `.html` links.
Links to `.html` files are not checked by sphinx and thus bit-rot.
Rather, link by `:ref:`, `:doc:`, `:option:` etc.
This commit does not address the links of the form
../release/cabal-latest/doc/API/**.html
which I do not know how to handle.  These are all broken on `readthedocs.org` and I have no clue how these were supposed to work.

Fix #7712 fix #7803: do not link to other .rst files by .html links

---

.github/workflows/linux.yml
Cabal/Cabal.cabal
Cabal/src/Distribution/Simple/Utils.hs
cabal-dev-scripts/src/GenValidate.hs
cabal-install/main/Main.hs
cabal-install/src/Distribution/Client/Manpage.hs
cabal-testsuite/PackageTests/Manpage/cabal.test.hs
templates/ci-linux.template.yml

Fix #7714: use `nroff -man /dev/stdin | less` as backend for `cabal man`
WIP: This does not work yet, I need some help with constructing the pipe correctly in Haskell.
I seem to follow the example at
https://stackoverflow.com/questions/41030168/haskell-using-the-handle-created-from-createprocess-and-createpipe-to-pipe-int
which works for me, but my patch does not seem to invoke `less` correctly.
---

Fix #7714: use `nroff -man | less` as backend for `cabal man`

---

Cabal/src/Distribution/Types/VersionRange/Internal.hs

Haddockumentation fixes in `Distribution.Types.VersionRange.Internal`
- 2 typos
- meaningful doc for `wildcardUpperBound`
- cosmetics

Haddockumentation fixes in Distribution.Types.VersionRange.Internal

---

doc/nix-local-build.rst

Unless my English is severely lacking, this seems like a tiny typo in the docs.

docs: typo

---

Cabal/src/Distribution/Types/VersionInterval/Legacy.hs
Cabal/src/Distribution/Types/VersionRange/Internal.hs

Re #7916: `haddockumentation of Distribution.Types.VersionInterval.Legacy`
This commit affects only comments and documentation comments.
- clarifies existing haddock for `Distribution.Types.VersionInterval.Legacy`
- emphasizes the mathematical structure: canonical Boolean algebra
- adds docs when they were missing
- add some asymptotic complexity estimates
- add comments in the code that explain its function
Note: this module is declared "legacy", but the documentation effort
here can be salvaged to non-legacy code once #7916 is resolved.

Re #7916: haddockumentation of Distribution.Types.VersionInterval.Legacy

---

cabal-install/src/Distribution/Client/CmdListBin.hs
cabal-testsuite/PackageTests/ListBin/Script/cabal.out
cabal-testsuite/PackageTests/ListBin/Script/cabal.test.hs
cabal-testsuite/PackageTests/ListBin/Script/script.hs
changelog.d/pr-7851

Small PR to add script support for list-bin. It includes a test.
Because of #7774, I do not  believe there is any documentation that needs to be updated.
Related: #7073

Add list-bin support for scripts.

---

Cabal/src/Distribution/PackageDescription/Check.hs
cabal-testsuite/PackageTests/Check/SynopsisLength/cabal.out
cabal-testsuite/PackageTests/Check/SynopsisLength/cabal.test.hs
cabal-testsuite/PackageTests/Check/SynopsisLength/pkg.cabal
changelog.d/pr-7933

Adjusting cabal check warning for long synopses

---

doc/cabal-project.rst

This is a stop-gap measure against #7930. It's probably not ideal so I'm fine with just waiting for a better feature, if you think it's the right way forward.

docs: cabal.project in parent directories

---

CONTRIBUTING.md
Cabal-syntax/src/Distribution/Compat/Lens.hs
Cabal-syntax/src/Distribution/Types/VersionInterval.hs
Cabal/src/Distribution/Simple/Haddock.hs
cabal-testsuite/PackageTests/InternalLibraries/Haddock/Foo.hs
cabal-testsuite/PackageTests/InternalLibraries/Haddock/InternalAfter.hs
cabal-testsuite/PackageTests/InternalLibraries/Haddock/InternalBefore.hs
cabal-testsuite/PackageTests/InternalLibraries/Haddock/foo.cabal
cabal-testsuite/PackageTests/InternalLibraries/Haddock/haddock.cabal.out
cabal-testsuite/PackageTests/InternalLibraries/Haddock/haddock.out
cabal-testsuite/PackageTests/InternalLibraries/Haddock/haddock.test.hs
changelog.d/issue-1919
doc/nix-local-build.rst
stack.yaml

Fixes https://github.com/haskell/cabal/issues/1919

Fix haddock via Setup.hs with internal libraries

---

Cabal/src/Distribution/Simple/Setup.hs
cabal-testsuite/PackageTests/ReplOptions/ModuleA.hs
cabal-testsuite/PackageTests/ReplOptions/ModuleC.hs
cabal-testsuite/PackageTests/ReplOptions/cabal-repl-options.cabal
cabal-testsuite/PackageTests/ReplOptions/cabal.multiple-repl-options-multiple-flags.out
cabal-testsuite/PackageTests/ReplOptions/cabal.multiple-repl-options.out
cabal-testsuite/PackageTests/ReplOptions/cabal.project
cabal-testsuite/PackageTests/ReplOptions/cabal.single-repl-options-multiple-flags-negative.out
cabal-testsuite/PackageTests/ReplOptions/cabal.single-repl-options-multiple-flags.out
cabal-testsuite/PackageTests/ReplOptions/cabal.single-repl-options.out
cabal-testsuite/PackageTests/ReplOptions/cabal.test.hs
changelog.d/issue-6190

Attempt to fix #6190
Function `words` used instead of cons operator which was just adding
full string value to an empty array.
I'm newbie here but is there any place with kind of CLI tests where I could capture this behavior?
For now I tested it manually and I think it works:
1. ~Negative scenario:
```bash
$ cabal-new v2-repl --repl-options="-fwrite-interface -fbyte-codeaa"
Build profile: -w ghc-8.10.7 -O1
- programming-in-haskell-0.1.0.0 (lib:chapters) (first run)
Preprocessing library 'chapters' for programming-in-haskell-0.1.0.0..
GHCi, version 8.10.7: https://www.haskell.org/ghc/  :? for help
ghc: unrecognised flag: -fbyte-codeaa
did you mean one of:
-fbyte-code
Usage: For basic information, try the `--help' option. …
```

Split --repl-options on whitespace

---

Cabal/src/Distribution/Compat/CopyFile.hs
cabal-install/src/Distribution/Client/Compat/FilePerms.hs

Another follow-up to #7572 
Turns out there's a less gnarly API for file modes than the .Internals stuff we were already using.
---

addFileMode: Replace use of Posix.Internals module with public API

---

cabal-install/tests/UnitTests/Distribution/Client/VCS.hs

CI times appear to be dominated by the VCS tests, which seems
excessive.
A typical Linux validate.sh job takes ~45 minutes, of which
15 are spent in the VCS tests. MacOS is even worse, with the
VCS tests taking >1h out of a total time of >2h.
---

Reduce VCS QuickCheck count to 10 (from 100)

---

cabal-install-solver/src/Distribution/Solver/Modular/MessageUtils.hs

Add the missing space in error messages like:
```
(conflict: requires NumDecimalswhich is not supported)
```

Fix missing space in error message

---

doc/cabal-package.rst

The documentation for the "mixins:" field still featured an obsolete warning about a parsing bug which was solved in #5293 and #5292.
I have verified that it indeed works now.
Open issues about seemingly the same bug: #5150, #4864.

Removed obsolete warning about mixins in the doc

---

cabal-install/src/Distribution/Client/CmdBench.hs
cabal-install/src/Distribution/Client/CmdConfigure.hs
cabal-install/src/Distribution/Client/CmdHaddock.hs
cabal-install/src/Distribution/Client/CmdListBin.hs
cabal-install/src/Distribution/Client/CmdOutdated.hs
cabal-install/src/Distribution/Client/CmdTest.hs

Very minor change for consistency. After the fix:
```
> cabal help
Command line interface to the Haskell Cabal infrastructure.
See http://www.haskell.org/cabal/ for more information.
Usage: <interactive> [GLOBAL FLAGS] [COMMAND [FLAGS]]
Commands:
[global]
update            Updates list of known packages.
install           Install packages.
help              Help about commands.
info              Display detailed information about a particular package.
list              List packages matching a search string.
fetch             Downloads packages for later installation.
user-config       Display and update the user's global cabal configuration.
[package]
get               Download/Extract a package's source code (repository).
unpack            Deprecated alias for 'get'.
init …
```

Consistent starting capital letter, ending period in help text.

---

cabal-install/cabal-install.cabal
release-notes/Cabal-3.6.1.0.md

Fixes #7835 for the 3.6. branch
---

Fix 7835 for 3.6

---

doc/cabal-commands.rst

This is a documentation only change for #7774.

Add a doc section on cabal list-bin.

---

cabal-install/src/Distribution/Client/CmdUpdate.hs
cabal-install/src/Distribution/Client/IndexUtils.hs

Resolves https://github.com/haskell/cabal/issues/5518 and https://github.com/haskell/cabal/issues/4987
Both these errors are in theory non-fatal, but simply gave uncaught exceptions. Cabal now warns on the exceptions and continues. This improves the resilience of cabal to bad cached index state from remote repositories, but does not solve the general problem completely. The most general path is to implement https://github.com/haskell/hackage-security/issues/199

Better recovery from a few index/tar errors

---

bootstrap/linux-8.10.7.json
bootstrap/linux-8.6.5.json
bootstrap/linux-8.8.4.json
cabal-install/cabal-install.cabal
cabal-install/src/Distribution/Client/FetchUtils.hs
cabal-install/src/Distribution/Client/Types/RepoName.hs
cabal-install/src/Distribution/Client/Utils.hs
cabal-install/tests/UnitTests.hs
cabal-install/tests/UnitTests/Distribution/Client/BuildReport.hs
cabal-install/tests/UnitTests/Distribution/Client/FetchUtils.hs
cabal-install/tests/UnitTests/Distribution/Solver/Types/OptionalStanza.hs
changelog.d/pr-7929

This fixes Ctrl-C not interrupting cabal properly while it is downloading. I believe
that might be #6322, although it would be good to verify that.
There are ~~two~~ three concrete bugs:
- `try` catches asynchronous exceptions, preventing `withAsync` from interrupting it when its `body` action finishes prematurely.
- the use of `withAsync` is not safe since we don't wait for the async and hence lose exceptions it might throw
- the use of regular `bracket` in `withTempFileName` can "convert" `AsyncCancelled` into a regular IO exception
The first bug manifests during `cabal build` when hitting Ctrl-C during
download, e.g.:
1. Ctrl-C interrupts a curl process
2. This interrupt is converted into a UserInterrupt exception
via the process package's delegate_ctlc functionality.
3. UserInterrupt …

Fix concurrency/exception bugs in asyncFetchPackages

---

cabal-install/src/Distribution/Client/ProjectPlanning.hs

These two `otherwise`s have been dead code since about 2016 but GHC has
started warning about them only since 9.2.
I have checked that in these cases GHC has always been picking the first matching pattern.

Remove overlapping patterns

---

.github/workflows/bootstrap.yml
.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/quick-jobs.yml
.github/workflows/users-guide.yml
.github/workflows/windows.yml

As per @fgaz question here: https://github.com/haskell/cabal/pull/8000#discussion_r813643975
Rationale
> Good point head_ref is only defined for pull requests and workflows are triggered for direct commits too.
The consequence is that, for consecutive direct and merge commits in master (and 3.6, 3.4 etc), they will be cancelled but the last one.
> So we will lose the status of those intermmediate commits.
> There is a small probability of a green pr breaking master cause we are not enforcing the pr is up to date with master before merging it. Also there is a even small probability of merge another pr just after the offending one and we will not know the real cause is the intemmediate and no the final one.
---
Please also shortly describe …

Use ref instead head_ref to cancelling jobs

---

cabal-install/cabal-install.cabal

This allows building cabal-install-3.4 with ghc-9.0.
I have tested that cabal-install-3.4.1.0 can build with this in current Stackage Nightly (ghc-9.0.2)

[3.4] cabal-install.cabal: allow base-4.15 (ghc-9.0)

---

cabal-install/src/Distribution/Client/Init/Interactive/Command.hs

After discussion in #hackage it seemed prudent to me to add some minimal
explanation of what a valid SPDX identifier might look like to the error
message.
I haven't tested the code and added `[ci skip]` because I'd like to invite comments about wording first.
---

Provide explanation for invalid license identifier

---

cabal-install/src/Distribution/Client/ProjectConfig.hs
cabal-install/src/Distribution/Client/ScriptUtils.hs
cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptWithProjectBlock/cabal.out
cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptWithProjectBlock/cabal.test.hs
cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptWithProjectBlock/s.hs
changelog.d/pr-7851
doc/cabal-commands.rst

Closes #5698
Currently, as with the executable block, this just reads it and does not attempt to validate that the fields set are relevant to scripts. I think this is probably fine, but I'm open to discussing it.

Add support for cabal.project fields to scripts

---

Cabal-tests/Cabal-tests.cabal
cabal-install/cabal-install-solver/cabal-install-solver.cabal
cabal-install/cabal-install.cabal
cabal-testsuite/cabal-testsuite.cabal
cabal.project
cabal.project.validate.libonly
vendor/cabal-doctest-1.0.8/cabal-doctest.cabal

Otherwise GHC 9.2.2 cannot be bootstrapped by GHC 9.2.1. 
@Mikolaj could we please have it merged and released soon as Cabal-3.6.3.0? Just a revision would not be enough, because GHC source tree refers to Cabal repo, not to Cabal package on Hackage.

Allow building cabal-3.6 with GHC 9.2

---

doc/cabal-package.rst

The examples contain pre-SPDX identifiers which causes `cabal check`
to complain about it being an unknown SPDX license identifier.
---

Update old cabal examples to version 3.0

---

Cabal/Cabal.cabal
Cabal/ChangeLog.md
cabal-testsuite/cabal-testsuite.cabal
release-notes/Cabal-3.6.3.0.md

As discussed, we need to bump Cabal version in order for GHC to pick it up. I took a liberty to add a changelog as well, so this should be ready for Hackage release as well.

Bump Cabal to 3.6.3.0 and add changelog

---

Cabal/src/Distribution/Simple/PackageDescription.hs
cabal-testsuite/PackageTests/DuplicateExperimental/Four.hs
cabal-testsuite/PackageTests/DuplicateExperimental/Main.hs
cabal-testsuite/PackageTests/DuplicateExperimental/One.hs
cabal-testsuite/PackageTests/DuplicateExperimental/Three.hs
cabal-testsuite/PackageTests/DuplicateExperimental/Two.hs
cabal-testsuite/PackageTests/DuplicateExperimental/cabal.project
cabal-testsuite/PackageTests/DuplicateExperimental/duplicate.cabal
cabal-testsuite/PackageTests/DuplicateExperimental/setup.out
cabal-testsuite/PackageTests/DuplicateExperimental/setup.test.hs
changelog.d/pr-8023

For some projects (e.g. glean) that make wide use of colon specifiers or
visibility, we get hundreds (thousands) of duplicating warnings about
these language features, spamming our builds.
Flatten this warning into a single instance per parse, and a count of
others.
Example:
```
Warning: glean.cabal:1674:15: colon specifier is experimental feature (issue
Warning: glean.cabal:1625:24: visibility is experimental feature (issue #5660)
(and 32 more occurrences)
```
Test plan:
- try on glean.cabal from https://github.com/facebookincubator/Glean and
see it working as above
- cabal test all
---

Flatten duplicate warnings about experimental features

---

cabal-install/cabal-install.cabal
cabal-testsuite/PackageTests/Backpack/Includes2/setup-external.test.hs
cabal-testsuite/PackageTests/Backpack/Includes2/setup-per-component.test.hs
cabal-testsuite/PackageTests/Backpack/Includes3/setup-external-ok.test.hs
cabal-testsuite/PackageTests/CmmSourcesDyn/setup.test.hs
cabal-testsuite/PackageTests/CustomPlain/setup.test.hs
cabal-testsuite/PackageTests/ForeignLibs/setup.test.hs
cabal-testsuite/PackageTests/NewBuild/T3827/cabal.test.hs
cabal-testsuite/PackageTests/Regression/T4025/setup.test.hs
cabal-testsuite/PackageTests/Regression/T4270/setup.test.hs
cabal-testsuite/PackageTests/SPDX/cabal-old-build.test.hs
cabal-testsuite/PackageTests/TestSuiteTests/ExeV10/cabal-with-hpc.multitest.hs
cabal-testsuite/README.md
cabal-testsuite/src/Test/Cabal/Prelude.hs

This marks tests that are currently failing on CI as "expected broken", to move back towards "green".
My understanding is that these were broken all along, but only started visibly failing recently with an extended test matrix through #7952.
Also
- raises the limit on the memory test suit to make that pass on 9.2 (#8029)
- update some old travis-related test skips
---

Mark failing tests as expected failures, or fix them

---

Cabal/ChangeLog.md
release-checklist.md
release-notes/Cabal-3.6.3.0.md

Also, a PR for any fallout of the Cabal 3.6.3 release that ought to be fixed on master branch, not only 3.6 branch.

Add release notes for 3.6.3 and move release checklist to the wiki and update some

---

doc/cabal-commands.rst
doc/cabal-package.rst
doc/cabal-project.rst

* Rebasing master on #6703
* It removes the v2- prefix from https://github.com/haskell/cabal/blob/master/doc/cabal-commands.rst (the pr changed the version prior to moving the file in [Cabal/doc/cabal-commands.rst](https://github.com/haskell/cabal/pull/6703/files#diff-398cd72d68f75f49e9235320347ffba87abb3af68ea11aed159c630905d6f2d9))
* git was not able to keep track of that file :shrug: 
* It changes the header of that file as it mentions default commands and no `new-style` ones
// @m-renaud feel free to use those changes to rebase yours, other alternative could be close #6703 and merge this

Rebased version of #6703: Remove v2- prefix from command, package, and project docs.

---

Cabal-syntax/src/Distribution/Compat/CharParsing.hs
Cabal-syntax/src/Distribution/Types/Flag.hs

Resolves https://github.com/haskell/cabal/issues/7279
We just weren't lexing trailing whitespace in flag names. So a constraint like "pkg +flag , ..." would fail while "pkg +flag, ..." would succeed.

allow trailing whitespace after flags

---

bootstrap/src/Main.hs

(Not entirely sure what to do with this patch. It's a fix for a bug in bootstrap generation that was triggered by adding a dependency to the cabal-install executable in #7921, but that dependency is no longer there.)
Before this change, with 'signal' as a dependency for
cabal-install:exe:cabal, the dependency list ended
```
...
cabal-install
signal
cabal-install
```
The first copy of "cabal-install" is the library target, which
is a dependency of the final executable target. But when
the bootstrap build encounters "cabal-install", it tries
building the executable target right away, which fails due
to the missing "signal" dependency.
---

Bootstrap generation fix for exe-only dependencies

---

Cabal-syntax/src/Distribution/FieldGrammar/Newtypes.hs
cabal-install/src/Distribution/Client/Init/Defaults.hs
cabal-install/src/Distribution/Client/Init/FileCreators.hs
cabal-install/src/Distribution/Client/Init/FlagExtractors.hs
cabal-install/src/Distribution/Client/Init/Format.hs
cabal-install/src/Distribution/Client/Init/Interactive/Command.hs
cabal-install/src/Distribution/Client/Init/NonInteractive/Command.hs
cabal-install/src/Distribution/Client/Init/NonInteractive/Heuristics.hs
cabal-install/src/Distribution/Client/Init/Simple.hs
cabal-install/src/Distribution/Client/Init/Types.hs
cabal-install/tests/UnitTests/Distribution/Client/Init/Interactive.hs
cabal-install/tests/UnitTests/Distribution/Client/Init/NonInteractive.hs
cabal-install/tests/UnitTests/Distribution/Client/Init/Simple.hs
cabal-install/tests/UnitTests/Distribution/Client/Init/Utils.hs
cabal-install/tests/fixtures/init/golden/pkg-desc/pkg-old-cabal-with-flags.golden
cabal-testsuite/PackageTests/Init/init-interactive-legacy.out
cabal-testsuite/PackageTests/Init/init-interactive-legacy.test.hs
cabal-testsuite/PackageTests/Init/init-interactive.out
cabal-testsuite/PackageTests/Init/init-interactive.test.hs
cabal-testsuite/PackageTests/Init/init-legacy.out
cabal-testsuite/PackageTests/Init/init-legacy.test.hs

This PR aims to fix three buggy behaviours within the `cabal init` file output:
* the versions in the `build-depends` field should not use the caret style constraint for major bound versions if `cabal-version < 2.0`
* the license prompt, for the `License` field, should present legacy or SPDX license options depending on the cabal version picked previously
* for `cabal-version < 2.2`, the field `build-type` must be set
Fixes #7946 and fixes #7947.
---

Fixing `cabal init` file output for `cabal-version < 2.2`

---

cabal-install/src/Distribution/Client/ProjectPlanning.hs

fixes a logic bug.
resolves https://github.com/haskell/cabal/issues/7775

Use the cli flags in fetching packages in building a project config 

---

Cabal/src/Distribution/Simple/Program/Run.hs
Cabal/src/Distribution/Simple/Utils.hs
cabal-install/cabal-install.cabal
cabal-install/main/Main.hs
cabal-install/src/Distribution/Client/ProjectConfig.hs
cabal-install/src/Distribution/Client/Signal.hs
cabal-testsuite/PackageTests/NewBuild/CmdRun/Terminate/Main.hs
cabal-testsuite/PackageTests/NewBuild/CmdRun/Terminate/RunKill.cabal
cabal-testsuite/PackageTests/NewBuild/CmdRun/Terminate/cabal.project
cabal-testsuite/PackageTests/NewBuild/CmdRun/Terminate/cabal.test.hs
cabal-testsuite/src/Test/Cabal/Run.hs
changelog.d/pr-7921

This make cabal-install reliably terminate its children before exiting when cabal-install itself is killed (fixes #7914), by:
- replacing use of [createProcess](https://hackage.haskell.org/package/process-1.6.9.0/docs/System-Process.html#v:createProcess) by [withCreateProcess](https://hackage.haskell.org/package/process-1.6.9.0/docs/System-Process.html#v:withCreateProcess), which provides async-exception-safe subprocess cleanup
- installing a signal handler which converts SIGTERM into an asynchronous exception that's thrown at the main thread
Some notes:
- The use of `withCreateProcess` helps with Ctrl-C behaviour on Windows, fixing the second half of #6322, as a follow-up to #7929.
- The `SIGTERM` change itself doesn't affect Windows -- there appears to be no meaningful way currently to …

Handle SIGTERM properly, on unix systems

---

cabal-install/src/Distribution/Client/Init/FileCreators.hs
cabal-install/src/Distribution/Client/Init/Interactive/Command.hs
cabal-install/tests/UnitTests/Distribution/Client/Init/Golden.hs
cabal-install/tests/UnitTests/Distribution/Client/Init/Interactive.hs
cabal-testsuite/PackageTests/Init/init-backup.out
cabal-testsuite/PackageTests/Init/init-backup.test.hs
cabal-testsuite/PackageTests/Init/init-interactive-legacy.test.hs
cabal-testsuite/PackageTests/Init/init-interactive.test.hs

Closes #7957. This PR will:
* Prompts the user if overwriting files is desired for the interactive workflow;
* Warns the user if the .cabal file remains untouched after `cabal init` is finished;
* Unit tests adjustments for the new prompt;
* A new test in cabal-testsuite;
* Fixes a bug in the overwrite workflow.
---

Making the user aware of an unchanged .cabal file in cabal init

---

cabal-testsuite/cabal-testsuite.cabal
stack.yaml

* No ci job is checking this but i tested it locally in debian 10
* I had to add `Cabal-syntax` to `setup-depends`in the cabal-testsuite or the build throwed the error:
```
cabal-testsuite> /home/debian/cabal/cabal-testsuite/Setup.hs:4:1: error:
cabal-testsuite>     Could not load module `Distribution.Backpack'
cabal-testsuite>     It is a member of the hidden package `Cabal-syntax-3.7.0.0'.
cabal-testsuite>     You can run `:set -package Cabal-syntax' to expose it.
cabal-testsuite>     (Note: this unloads all the modules in the current scope.)
cabal-testsuite>     It is a member of the hidden package `Cabal-3.2.1.0'.
cabal-testsuite>     You can run `:set -package Cabal' to expose it.
cabal-testsuite>     (Note: this unloads all the modules in the current scope.)
cabal-testsuite>     Use …
```

Update stack.yaml resolver and fix cabal-testsuite stack build

---

cabal-install/src/Distribution/Client/Setup.hs
cabal-install/tests/IntegrationTests2.hs
changelog.d/issue-8036

This PR is attempting to close #8036 
The `boolOpt` function will not allow for more than one description so I changed the option type from `option` to `multiOption` so that the "nix" (`--enable-nix` and `--disable-nix`) flags would still be grouped together and allow separate descriptions for disabled and enabled.
As far as the language goes I felt like if the description of "Nix integration" for the `--disable-nix` was taken out it would make it more clear. It is defined in `--enable-nix` and `--disable-nix` is right under it.
---

Make enable/disable nix flag easier to read

---

Cabal-tests/Cabal-tests.cabal
Cabal-tests/tests/CheckTests.hs
Cabal-tests/tests/ParserTests/regressions/issue-7776-a.cabal
Cabal-tests/tests/ParserTests/regressions/issue-7776-a.check
Cabal-tests/tests/ParserTests/regressions/issue-7776-b.cabal
Cabal-tests/tests/ParserTests/regressions/issue-7776-b.check
Cabal-tests/tests/ParserTests/regressions/issue-7776-c.cabal
Cabal-tests/tests/ParserTests/regressions/issue-7776-c.check

* Tests for the regression described in #7776 which will be fixed by #7966.
* Merge before #7966, the rebase will reveal the unexpected success and we only will have to remove the known broken mark

#7776 regression tests

---

Cabal-syntax/src/Distribution/Types/Dependency.hs
Cabal-syntax/src/Distribution/Types/DependencyMap.hs
changelog.d/pr-8061

This change derives the `Eq` type class on `DependencyMap` in the
`Distribution.Types` module.
Closes #7849

Derive Eq on DependencyMap

---

cabal-install/src/Distribution/Client/Security/HTTP.hs
changelog.d/pr-7970

Speculative fix for https://github.com/haskell/cabal/issues/5952
Should be a strict improvement even if it doesn't resolve that ticket, as it just puts in place a sanity check to ensure range requests are not malformed.

ensure range headers are only sent when from < to

---

Cabal-tests/tests/CheckTests.hs
Cabal/src/Distribution/PackageDescription/Check.hs

Resolves https://github.com/haskell/cabal/issues/7776
Now if a package _may_ have duplicate modules (subject to conditionals), cabal warns on this.
But if a package _necessarily_ has duplicate modules (because they are not guarded by conditionals), cabal will error.

Fix the duplicate modules check

---

Cabal-tests/Cabal-tests.cabal
Cabal-tests/tests/HackageTests.hs
validate.sh

* Investigating on how to add tests for #7966 i tried to enable hackage tests for windows, expecting they will not be even buildable
* Surprisingly they were buildable and even passed in my local win env
* The ghcup installation in windows uses CABAL_DIR so i had to make tests honour the env var to make it read my hackage config
* Let's see how is the thing going in ci

Enable hackage tests for windows

---

Cabal-syntax/src/Distribution/System.hs
Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
Cabal/src/Distribution/Simple/PreProcess.hs
changelog.d/pr-8065

So far only the 32-bit S390 architecture is supported. This patch also adds the 64-bit S390X architecture.
---

Add support for the 64-bit S390X architecture

---

Cabal/src/Distribution/Backpack/Id.hs
Cabal/src/Distribution/GetOpt.hs
cabal-install-solver/src/Distribution/Solver/Modular/Dependency.hs
cabal-install/src/Distribution/Client/FileMonitor.hs
cabal-install/src/Distribution/Client/GlobalFlags.hs
cabal-install/src/Distribution/Client/HttpUtils.hs
cabal-install/src/Distribution/Client/IndexUtils.hs
cabal-install/src/Distribution/Client/InstallPlan.hs
cabal-install/src/Distribution/Client/ProjectBuilding.hs
cabal-install/src/Distribution/Client/ProjectPlanning.hs
changelog.d/pr-7349
changelog.d/pr-7407

Cabal/src/Distribution/GetOpt.hs
cabal-install-solver/src/Distribution/Solver/Modular/Dependency.hs
cabal-install/src/Distribution/Client/FileMonitor.hs
cabal-install/src/Distribution/Client/GlobalFlags.hs
cabal-install/src/Distribution/Client/HttpUtils.hs
cabal-install/src/Distribution/Client/IndexUtils.hs
cabal-install/src/Distribution/Client/InstallPlan.hs
cabal-install/src/Distribution/Client/ProjectBuilding.hs
cabal-install/src/Distribution/Client/ProjectPlanning.hs
changelog.d/pr-7349
changelog.d/pr-7407
@Mikolaj missed these in `#8046`
<hr>
typo `concating` unattended to
cabal/Cabal/src/Distribution/Backpack/Id.hs
```
-- show is found to be faster than intercalate and then replacement of
-- special character used in intercalating. We cannot simply hash by
-- doubly concating list, …
```

fix spelling errors

---

cabal-testsuite/PackageTests/NewBuild/CmdRun/Terminate/Main.hs

The "up and running" file was written before the signal handler
was installed, so it was possible for the test to kill the
subprocess before, leading to a missed "exiting" line in the
output.
I hope this fixes the sporadic failures we're seeing (#8080).
(I'm sure it's a good change, just not 100% on whether this
is the problem we saw in CI.)
---

Fix race condition in PackageTests/NewBuild/CmdRun/Terminate

---

Makefile
bootstrap/README.md
bootstrap/cabal.project
bootstrap/src/Main.hs

I found a bug in the bootstrap generation Makefile targets while checking them against #8079:
`cabal v2-run -vnormal+stderr` was (sometimes) writing GHC output to stdout, messing with
the boostrapping JSON. This fixes that, and makes things a tiny bit tidier.
---

Bootstrapping fix

---

Cabal/src/Distribution/Simple/Compiler.hs
Cabal/src/Distribution/Simple/Configure.hs
Cabal/src/Distribution/Simple/Program/Ar.hs
Cabal/src/Distribution/Simple/Setup.hs
changelog.d/pr-8062

As noted in [GHC #21068](https://gitlab.haskell.org/ghc/ghc/-/issues/21068), the lld linker used on Windows by GHC 9.4 and later does not support object merging. Consequently, `--enable-library-for-ghci` can no longer be supported on this platform. In this MR we:
* turn `--enable-library-for-ghci` into an error on platforms where it is not supported.
* teach `Cabal` to use `llvm-ar`'s `L` modifier when available, which is now necessary when building static archives on Windows (since the archive may contain other archives, as noted in [GHC #21068](https://gitlab.haskell.org/ghc/ghc/-/issues/21068))
---

Changes to support new GHC 9.4's new Windows toolchain

---

doc/cabal-project.rst
doc/nix-local-build.rst

This may be a bit too opinionated, and I'd be happy to water it down. But I think it would be nice to explain how to use Stackage, and how it compares.

Document Stackage use with remote project config

---

release-notes/Cabal-3.4.0.0.md

https://github.com/haskell/cabal/commit/8e2ac1a5cc0c7d6d8c26fb0c9fd045620674a75b overlooked this
release-notes/Cabal-3.4.0.0.md

spelling correction

---

.github/workflows/validate.yml
Cabal-syntax/src/Distribution/System.hs
Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs
Cabal/src/Distribution/Simple/GHC.hs
Cabal/src/Distribution/Simple/GHCJS.hs
Cabal/src/Distribution/Simple/PreProcess.hs
changelog.d/pr-8096

This patch adds `wasm32` to known archs, and `wasi` to known oss. It's a part of the work of adding webassembly support to ghc at https://gitlab.haskell.org/ghc/ghc/-/merge_requests/7632.

Add wasm32-wasi to recognized arch/os

---

Cabal/src/Distribution/PackageDescription/Check.hs

Closes #7461
There is a [precedent](https://github.com/haskell/cabal/blob/709799a3dcafe03723de19946e78a36179a8f07c/cabal-install/src/Distribution/Client/CmdLegacy.hs#L105) using readthedocs so i suppose it is fine
does it need a changelog?
---

Correct url to package properties

---

Cabal/src/Distribution/Simple/GHC.hs
Cabal/src/Distribution/Simple/Program/GHC.hs

Previously Cabal did quite some headstands to link against libHSrts.
Note only this is complex but it couples very tightly to GHC's
implementation. Thankfully, as of GHC 9.0 GHC provides a `-flink-rts`
flag for precisely this purpose. Use it when available.
Fixes #7763.
---

Cabal: Use -flink-rts when available

---

cabal-testsuite/PackageTests/ForeignLibs/setup.test.hs
changelog.d/pr-7764

* It seems #7764 fixed the test, but the pr was merged without having the ci green
* Since that, the validate workflow is failing 
---

Unmark foreign lib test as broken for win and ghc >= 9.0

---

.github/workflows/validate.yml

See https://github.com/haskell/cabal/pull/8115#issuecomment-1113136131 and later comments.

Exclude broken 'Validate windows-latest ghc-8.4.4' job that cancels CI

---

Cabal-syntax/src/Distribution/PackageDescription/FieldGrammar.hs
Cabal-syntax/src/Distribution/PackageDescription/Parsec.hs
Cabal-syntax/src/Distribution/Types/BenchmarkInterface.hs
Cabal-syntax/src/Distribution/Types/BenchmarkType.hs
Cabal-syntax/src/Distribution/Types/TestSuiteInterface.hs
Cabal-syntax/src/Distribution/Types/TestType.hs
Cabal-tests/tests/ParserTests/errors/issue-5055-2.errors
Cabal-tests/tests/ParserTests/errors/issue-5055.errors
Cabal-tests/tests/ParserTests/regressions/issue-5055.expr
Cabal-tests/tests/ParserTests/regressions/issue-5055.format
Cabal/src/Distribution/PackageDescription/Check.hs
cabal-install/tests/IntegrationTests2/targets/benchmarks-disabled/p.cabal
cabal-install/tests/IntegrationTests2/targets/multiple-tests/p.cabal
cabal-install/tests/IntegrationTests2/targets/variety/p.cabal
cabal-testsuite/PackageTests/DuplicateModuleName/DuplicateModuleName.cabal
cabal-testsuite/PackageTests/NewBuild/CmdBench/MultipleBenchmarks/MultipleBenchmarks.cabal
changelog.d/pr-8115
doc/cabal-package.rst

Resolves #7459
I manually tested the change using `cabal check` against the various combinations of fields and stanzas.
---

Make `type` field optional for tests and benchmarks

---

Cabal/Cabal.cabal

>= shouldn't be used for cabal-version 1.12 and later, and
9e353b067e7045689003a3c662343dfd8dfd1fd1 changed it to 1.22
We should run `cabal check` in CI to catch errors like this one in the future
---

Remove >= from Cabal cabal-version

---

.github/workflows/validate.yml

To make mergify not merge prs with failing validate jobs
If a main validate job fails github marks as skipped the rest of workflow jobs.
Otoh mergify considers prs with skipped required jobs as mergeable 😮 🤦 
This pr forces the run of the post job, which will fail if any of the previous jobs has failed or skipped
---

Run always validate post-job

---

cabal-testsuite/README.md

I noticed `cabal-testsuite/README.md` is one of the few places where we still mention `cabal new-build`.
This PR replaces `cabal new-build` with `cabal build` in that file. There's another reference to "new-build" but I understand that refers to the "build style" and not the cabal command so I left it (perhaps that paragraph can be reworded).
---

Remove references to `new-build` in testsuite readme

---

Cabal-syntax/src/Distribution/SPDX/LicenseExceptionId.hs
Cabal-syntax/src/Distribution/SPDX/LicenseId.hs
Makefile
cabal-dev-scripts/src/GenSPDX.hs
cabal-dev-scripts/src/GenSPDXExc.hs
cabal-dev-scripts/src/GenUtils.hs
changelog.d/pr-8127
license-list-data/exceptions-3.16.json
license-list-data/licenses-3.16.json
templates/SPDX.LicenseExceptionId.template.hs
templates/SPDX.LicenseId.template.hs

Update the SPDX License List to version 3.16

---

Cabal-syntax/src/Distribution/PackageDescription/FieldGrammar.hs
cabal-testsuite/PackageTests/TestCodeGenerator/my.cabal

followup from https://github.com/haskell/cabal/pull/7688

code-generators now marked to 3.8 spec

---

cabal-install/src/Distribution/Client/CmdSdist.hs
cabal-install/src/Distribution/Client/ProjectConfig.hs
cabal-install/src/Distribution/Client/ProjectFlags.hs
cabal-install/src/Distribution/Client/ProjectOrchestration.hs
cabal-install/src/Distribution/Client/ProjectPlanning.hs
cabal-install/tests/IntegrationTests2.hs
cabal-install/tests/IntegrationTests2/build/ignore-project/A.hs
cabal-install/tests/IntegrationTests2/build/ignore-project/Setup.hs
cabal-install/tests/IntegrationTests2/build/ignore-project/a.cabal
cabal-install/tests/IntegrationTests2/build/ignore-project/cabal.project
cabal-testsuite/PackageTests/Regression/T5318/cabal.project
cabal-testsuite/PackageTests/Regression/T5318/sdist-list-sources.test.hs
cabal-testsuite/PackageTests/SDist/T5195/cabal.project
cabal-testsuite/PackageTests/SDist/T5195/cabal.test.hs
cabal-testsuite/PackageTests/SDist/T7028/cabal.test.hs
cabal-testsuite/PackageTests/SDist/T7124/cabal-list.test.hs
cabal-testsuite/PackageTests/SDist/T7124/cabal.test.hs
cabal-testsuite/PackageTests/SDist/T7698/cabal.test.hs
changelog.d/issue-7965
doc/cabal-project.rst

It seems that many commands did not respect the `--ignore-project` flag at all and always built from the `cabal.project` file that the program can find either in it's current directory or the parent directories. This PR changes the `readProjectConfig` function of the `Distribution.Client.ProjectConfig` to accept a boolean that will determine if the function will return the only the global project config or the settings found in the local `cabal.project` file. Whatever is returned gets merged with the local `foo.cabal` file and the package config is returned. This should make it so that if the `--ignore-project` flag is set then the local `cabal.project` file will be ignored and the global config and the `foo.cabal` file are merged together and the `sdist` command is run with that …

v2-sdist now respects --ignore-project

---

doc/setup-commands.rst

The original Cabal proposal https://www.haskell.org/cabal/proposal/ explained that `runhaskell`, in the proposal, was to refer to a symlink to `runhugs`, `runghc`, or `runnhc`. That explanation has been lost from the Cabal guide. Since the date of the original proposal, HUGS and NHC have fallen by the wayside. This pull request proposes two minor additions to restore the explanation:
1. A sentence "The command `runhaskell` (or its GHC equivalent, `runghc`) allows you to run Haskell programs without first having to compile them." This wording is lifted from the GHC user guide for `runghc`.
2. A clarification that `--help` provides information about the `Setup.hs` script (not the `runhaskell` command).
---
Please also shortly describe how …

Clarify `runhaskell` in Cabal's guide

---

cabal-install/src/Distribution/Client/CmdUpdate.hs
cabal-testsuite/PackageTests/NewUpdate/UpdateIndexState/update-index-state.out
cabal-testsuite/src/Test/Cabal/Prelude.hs

I noticed I had left out a small detail in the previous PR. `current_ts` can be an invalid timestamp (of value `nullTimestamp`) if, e.g., the repository is missing. In this case we shouldn't tell the user how to go back to `current_ts` because it does not make any sense. Test case explains this better than my words :)
---

Minor clean up after PR #7934

---

Cabal-syntax/src/Distribution/PackageDescription/FieldGrammar.hs
Cabal-syntax/src/Distribution/PackageDescription/Parsec.hs
Cabal-tests/tests/ParserTests/errors/issue-5055-2.errors
Cabal-tests/tests/ParserTests/errors/issue-5055.errors
Cabal-tests/tests/ParserTests/regressions/issue-5055.expr
Cabal-tests/tests/ParserTests/regressions/issue-5055.format
cabal-install/tests/IntegrationTests2/targets/benchmarks-disabled/p.cabal
cabal-install/tests/IntegrationTests2/targets/multiple-tests/p.cabal
cabal-install/tests/IntegrationTests2/targets/variety/p.cabal
cabal-testsuite/PackageTests/DuplicateModuleName/DuplicateModuleName.cabal
cabal-testsuite/PackageTests/NewBuild/CmdBench/MultipleBenchmarks/MultipleBenchmarks.cabal
changelog.d/pr-8115
doc/file-format-changelog.rst

Addresses changes requested in https://github.com/haskell/cabal/pull/8115#issuecomment-1122494025
---

Require `type` field when spec < 3.8 (#8115)

---

Cabal/src/Distribution/ReadE.hs
cabal-install/src/Distribution/Client/Setup.hs
changelog.d/pr-8140

~~This is a WIP, it's not beautiful:~~ (see the first comment below)
```
❯ $CABAL build --allow-newer=                                                                                              1 (0.018s) < 04:31:50
Error: cabal: invalid argument to option `--allow-newer': "<parsecToReadE>"
(line 1, column 1):
unexpected empty argument list for --allow-newer=. Use --allow-newer without
the equals sign to permit all packages to use newer versions.
expecting "*"
```
Should `"parsecToReadE"` be removed? It can be but this may make it harder to debug anything that goes via `parsecToReadE`. 
`expecting "*"` is annoying but I'm not sure how to remove it either.
---
Please also shortly describe how you tested your change. Bonus points for …

Improve error message for empty --allow-newer= (fix #7740)

---

README.md

Small typo balancing parentheses in readme.

Typo missing closing parenthesis on license.

---

Cabal-syntax/src/Distribution/SPDX/LicenseExceptionId.hs
Cabal-syntax/src/Distribution/SPDX/LicenseId.hs
Cabal-syntax/src/Distribution/SPDX/LicenseListVersion.hs
doc/file-format-changelog.rst
templates/SPDX.LicenseExceptionId.template.hs
templates/SPDX.LicenseId.template.hs

Add SPDX List v3.16 to LicenseListVersion and the file format changelog

---

Cabal-syntax/src/Distribution/Types/VersionInterval.hs
Cabal-syntax/src/Distribution/Types/VersionInterval/Legacy.hs

Undeprecate `Distribution.Types.VersionInterval.Legacy`, see
- #7916
While `Distribution.Types.VersionInterval` does not export the Boolean algebra operations union, intersection and complement on `VersionIntervals`, the Legacy variant is still needed. Third party tools like `hackage-cli` rely on this API.
This patch only removes a DEPRECATED pragma and fixes the haddocs.  (No functionality changes.)
This needs to go into the 3.8 release.

Re #7916: undeprecate Distribution.Types.VersionInterval.Legacy

---

Cabal-syntax/Cabal-syntax.cabal
Cabal-tests/Cabal-tests.cabal
Cabal/Cabal.cabal
cabal-benchmarks/cabal-benchmarks.cabal
solver-benchmarks/solver-benchmarks.cabal

This makes our packages more uniform and future-proofs their licence fields.

Bump cabal-version in the remaining .cabal files and update BSD3 name

---

Cabal/src/Distribution/Simple/Program/GHC.hs
cabal-install/src/Distribution/Client/ProjectPlanning.hs

because we already test 9.2 in CI. This covers
https://github.com/haskell/cabal/wiki/Making-a-release#for-release-for-new-ghc-version
except for #8168, which is pending.

Update cabal to officially support GHC 9.2

---

.gitlab-ci.yml

This is a blind attempt to fix gitlab failures at https://gitlab.haskell.org/haskell/cabal/-/pipelines/52777 probably caused by using a version of cabal that is not on Hackage (and not otherwise known to ghcup), because that version is a pre-release.
TODO in next PRs: I could add this line to .build, but perhaps one of the cases is going to need a special version of cabal in the future and I don't know if overwriting default variables works.
Edit: I've tagged this commit with gitlab-ci-try1-3.8.0.20220526, but gitlab doesn't seem to bite. Either there is a lag or it's manually started or only the main branches are permitted, I don't know.
Edit2: it worked now, @hasufell says it's an automatic mirror with pull frequency perhaps 30min. All passed, except FreeBSD that failed with `mkdir: …

Permit pre-releases in gitlab CI

---

doc/cabal-commands.rst
doc/cabal-project.rst

Use proper option formatting instead of bullet points.
https://cabal--8193.org.readthedocs.build/en/8193/cabal-commands.html#cabal-sdist
---

Improve documentation formatting of some cabal command flags

---

.github/workflows/validate.yml

If it turns out we need to remove also any newer GHCs, let's investigate and try to work around. For older GHCs I'm resigned to only testing on other OSes.

Exclude broken 'Validate windows-latest ghc-8.6.5' job that cancels CI

---

cabal-install/src/Distribution/Client/Configure.hs

We used to check that, under presence of --allow-newer/older, Cabal version is >=1.19.2 (earlier versions don't get these flags), but we no longer support <.1.19.2 anyway, so the check is not needed. Remove.
Close #2023.
---

Remove Cabal version check that applied to already not supported <1.19.2

---

bootstrap/bootstrap.py

This allows bootstrapping against zlib 0.6.3.0, which ships
without Setup.hs.
I hope this should generally be a more robust approach than
asking maintainers of dependencies to keep Setup.hs.
Testing: I ran the bootstrap successfully locally, with the zlib version updated to 0.6.3.0.

bootstrap: generate missing Setup.hs in dependencies

---

doc/conf.py
doc/requirements.in
doc/requirements.txt

It annoys me beyond measure that I can't freely browse TOC (in the left sidebar) without jumping between pages. It turned out there's a little switch that allows you to (**almost**) freely unfold menu items, and I turn it on in this PR. 
Why "almost" is because it will still only show one section unfolded at a time. There's a long-standing PR to fix that: https://github.com/readthedocs/sphinx_rtd_theme/pull/692 I think that it's still way better than the current state.
Another related but different idea is to have the TOC fully unfolded always. I'm less sure that I'd want that (perhaps I'd), but `sphinx_rtd_theme` currently doesn't allow it out of the box: https://github.com/readthedocs/sphinx_rtd_theme/issues/455
Here's what TOC will look like, and you can unfold entries by clicking in …

docs: allow TOC navigation

---

Cabal/src/Distribution/Simple/Haddock.hs
Cabal/src/Distribution/Simple/Setup.hs
cabal-install/cabal-install.cabal
cabal-install/main/Main.hs
cabal-install/src/Distribution/Client/CmdHaddock.hs
cabal-install/src/Distribution/Client/CmdHaddockProject.hs
cabal-install/src/Distribution/Client/Config.hs
cabal-install/src/Distribution/Client/Haddock.hs
cabal-install/src/Distribution/Client/PackageHash.hs
cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs
cabal-install/src/Distribution/Client/ProjectConfig/Types.hs
cabal-install/src/Distribution/Client/ProjectPlanning.hs
cabal-install/src/Distribution/Client/ProjectPlanning/Types.hs
cabal-install/src/Distribution/Client/Setup.hs
cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs
changelog.d/pr-8162
doc/cabal-commands.rst

Fixes #7669, also fixes `--with-haddock` support which is useful when testing a newer version of `haddock` than the one distributed with `ghc`.
---

Haddocks command

---

Cabal-tests/tests/UnitTests/Distribution/Simple/Program/GHC.hs

Update command line tests for 9.2. Let's wait for CI first, but is there a way to know which `flags which may affect artifacts`?
---

Add command line options tests for 9.2

---

Cabal-syntax/src/Distribution/Fields/ParseResult.hs
Cabal-syntax/src/Distribution/System.hs
Cabal-syntax/src/Distribution/Types/VersionInterval.hs

Future compat for https://github.com/haskell/core-libraries-committee/issues/50

Future compat for liftA2 being exported from Prelude

---

release-notes/cabal-install-3.8.0.20220526.md

Some cosmetics:
- capitalization, punctuation, formatting
- fixed some sentences
- moved `Cabal-syntax` to major changes section
E.g., when upgrading `hackage-cli` to `Cabal-3.7` I noticed the following changes
- `readGenericPackageDescription` disappeared from `Distribution.PackageDescription`
- New module `Distribution.Simple.PackageDescription` (that exports `readGenericPackageDescription`)
This was easy enough to grep in the cabal sources, but I think new modules should be mentioned in the changelogs (the least).

Some cosmetics on the 3.8 changelogs

---

.github/workflows/bootstrap.yml
Makefile
bootstrap/linux-8.6.5.json
bootstrap/linux-8.8.4.json
bootstrap/linux-9.0.2.json
bootstrap/linux-9.2.3.json

This is meant to address #8225.
- Add GHC 9.0.2 and GHC 9.2.3 to the bootstrapping GHC versions
- Updates bootstrap files according to current hackage state
- Updates the bootstrap CI job to test all GHC versions
I haven't tested all the bootstrap builds yet, let's see what CI says.
---

Bootstrapping update (including GHC 9.0, 9.2)

---

Cabal-syntax/src/Distribution/Types/AbiHash.hs

The existing Haddock documentation for `unAbiHash` and `mkAbiHash` appears to have been swapped, in error. This pull request swaps it back.
Please also shortly describe how you tested your change. Bonus points for added tests! N/A - documentation only.

Fix Haddocks for `unAbiHash` and `mkAbiHash`

---

Cabal/src/Distribution/PackageDescription/Check.hs
cabal-testsuite/PackageTests/Check/DifferentGhcOptions/cabal.out

-W -Wall is too (correctly) refused by Hackage.
Closes #8257.
---

Simplify -Werror warning

---

cabal-install/main/Main.hs
changelog.d/pr-8240

* Fixes #4377.
* Superseeds #4552
I want to remember sometimes cabal builds with assetions enabled were leaked to final users.
Anyways i think warn about it would be useful for the reasons noted in #4377
Not sure how could this be tested without build a cabal version with assertions enabled and not sure it it worths it
---

Print a warning when assertions are enabled

---

cabal-install/src/Distribution/Client/CmdHaddock.hs
cabal-testsuite/PackageTests/NewHaddock/ImplyDependencies/B/B.cabal
cabal-testsuite/PackageTests/NewHaddock/ImplyDependencies/B/B.hs
cabal-testsuite/PackageTests/NewHaddock/ImplyDependencies/cabal.out
cabal-testsuite/PackageTests/NewHaddock/ImplyDependencies/cabal.project
cabal-testsuite/PackageTests/NewHaddock/ImplyDependencies/cabal.test.hs
cabal-testsuite/PackageTests/NewHaddock/ImplyDependencies/repo/A-0.1.0.0/A.cabal
cabal-testsuite/PackageTests/NewHaddock/ImplyDependencies/repo/A-0.1.0.0/A.hs
changelog.d/issue-7462
doc/cabal-project.rst

The problem described  below was solved by nuking the store. All good now. Fixing #7462.
---
I hoped that implementing #7462 should be a breath. Alas, an obvious fix turns into a disfunctional `cabal haddock`: it keeps failing with
```
67% (  2 /  3) in 'MyLib'
Missing documentation for:
Module header
haddock: internal error: /home/artem/.cabal/store/ghc-9.0.2/acme-cadre-0.1-084e219a2f22159b817e45921b58427b54e7a20f5f1736c7acdba987d88cc4e2/share/doc/html/doc-index.json: openBinaryFile: does not exist (No such file or directory)
```
For a simple project like this:
```
❯ cat t7462.cabal
cabal-version:      2.4
name:               t7462
version:            0.1.0.0
author:             Artem Pelenitsyn
maintainer:         a.pelenitsyn@gmail.com
extra-source-files: CHANGELOG.md
library …
```

cabal haddock imply enable-documentation

---

.github/workflows/bootstrap.yml
.github/workflows/validate.yml
.gitlab-ci.yml
changelog.d/pr-8272

Fixes #8271.
Do we need this in a changelog? I guess not, just as we don't file CI changes? Though this one is user-visible, namely for the users of our binary archives.

Build release archives (and validate) with GHC 9.2.3

---

cabal-install/src/Distribution/Client/Init/Interactive/Command.hs
cabal-install/tests/UnitTests/Distribution/Client/Init/Interactive.hs
cabal-testsuite/PackageTests/Init/init-interactive-ghc2021.out
cabal-testsuite/PackageTests/Init/init-interactive-ghc2021.test.hs
changelog.d/issue-8265

cabal init -i: add the GHC2021 language option
