haskell/cabal

Cabal/Cabal.cabal, bootstrap/linux-8.10.7.json, bootstrap/linux-8.6.5.json, bootstrap/linux-8.8.4.json, bootstrap/linux-9.0.2.json, bootstrap/linux-9.2.3.json
Compare the discussion in #8208.
=> Bump dependency on process

.github/mergify.yml
Trying to be more lenient to backport PRs...
I also took liberty to restrict normal mergify merges to `master`. If you think it's not ok, let me know and I'll revert.
---
=> [ mergify ] allow 1 approver for backports

cabal-install/main/Main.hs
Clarify `assertionsEnabledMsg`
The original message confused me.
It should be clear from the message text whether it is a debug build of cabal-install itself or of the package that cabal-install is handling.
=> Clarify assertionsEnabledMsg

Cabal-syntax/src/Distribution/Fields/Pretty.hs, cabal-install/tests/fixtures/init/golden/cabal/cabal-lib-and-exe-no-comments.golden, cabal-install/tests/fixtures/init/golden/cabal/cabal-lib-and-exe-with-comments.golden, cabal-install/tests/fixtures/init/golden/cabal/cabal-lib-no-comments.golden, cabal-install/tests/fixtures/init/golden/cabal/cabal-lib-with-comments.golden, changelog.d/issue-8236
fix #8236
`cabal init -n`'s strategy is to create a list of field descriptions (the `PrettyField` type), which then gets transformed into a list of `Block`s, which, finally, goes into a list of strings and those strings go right into the generated `.cabal` file.
Some fields may be deemed unnecessary depending on the `init`'s flags (e.g. by default there's an `executable` field but no `library` field). Those fields are represented by the `PrettyEmpty` constructor of `PrettyField`. On the next stage, `PrettyEmpty` goes into a block with empty contents and no "margins" (cf. the `Margin` datatype). In theory, such empty blocks should turn into nothing in the output file. Unfortunately, the algorithm turning blocks into lines, `flattenBlocks`, is a bit tricky and does show sensitivity to empty …
=> cabal init -n: avoid extra blank lines

.github/mergify.yml, CONTRIBUTING.md
Per discussion on IRC. Some members of the team expressed a concern that PRs sometimes get merged too fast. A chillout time after review was a proposed as a countermeasure. This PR implements 2 day chillout period after last update of any PR against `master` (so, backports are not included in this new policy).
---
=> [ mergify ] require 2 days to pass after last update of PR to merge it

Cabal/src/Distribution/Simple/Program/GHC.hs, changelog.d/pr-8310
A followup to https://github.com/haskell/cabal/pull/8260#issuecomment-1190098926
Not tested. Theoretically one could test locally by using GHC 9.4 and verifying in the cabal -v3 log that arguments are filtered in the same way as for GHC 9.2. One would need to find a cabal invocation in which the filtering is not vacuus. The test would fail without this change, but pass with this change.
---
=> Accept unknown future GHCs in the argument filtering code

changelog.d/pr-8309, doc/cabal-commands.rst, doc/developing-packages.rst
Document (or at least stub): `fetch`, `get`, `info`, `init`, `list`, `report`, `unpack`, `upload`, `user-config`.
Closes #8308, closes #7884, closes #7978 and most likely others I was not able to find.
---
=> Document missing commands

doc/nix-integration.rst
Just a clarification in the documentation
=> Give an example for `--enable-nix` flag

cabal-testsuite/PackageTests/NewBuild/T3827/cabal.test.hs
An emergency CI fix to unblock CI passing for https://github.com/haskell/cabal/pull/8336 and probably others. See https://github.com/haskell/cabal/issues/8032#issuecomment-1204057038 for more info.
=> Turn off T3827 for Linux and OSX due to heisenbugs not caused by cabal

Cabal/src/Distribution/Simple/Build/PathsModule/Z.hs, cabal-testsuite/PackageTests/PathsModule/Executable-Relocatable/Main.hs, cabal-testsuite/PackageTests/PathsModule/Executable-Relocatable/my.cabal, cabal-testsuite/PackageTests/PathsModule/Executable-Relocatable/setup.cabal.out, cabal-testsuite/PackageTests/PathsModule/Executable-Relocatable/setup.out, cabal-testsuite/PackageTests/PathsModule/Executable-Relocatable/setup.test.hs, changelog.d/pr-8220, templates/Paths_pkg.template.hs
=> When generating `Paths` modules, define functions when used

cabal-testsuite/PackageTests/NewSdist/DeterministicTrivial/deterministic.test.hs
=> Turn off DeterministicTrivial test (see #8356)

doc/buildinfo-fields-reference.rst, doc/cabal-package.rst, doc/file-format-changelog.rst
About time I write this :D
Closes #6362
---
=> Document multiple public libraries

Cabal-syntax/Cabal-syntax.cabal, Cabal/Cabal.cabal
Would simplify https://github.com/haskell/hackage-security/pull/281 and fix similar errors for others. More delicate than bumping lower bounds on base.
Fixes https://github.com/haskell/cabal/issues/8371
=> Fix compilation on old GHCs (fixes #8371)

Cabal/Cabal.cabal, bootstrap/linux-8.10.7.json, bootstrap/linux-8.6.5.json, bootstrap/linux-8.8.4.json, bootstrap/linux-9.0.2.json, bootstrap/linux-9.2.3.json, cabal-install/cabal-install.cabal
This mimics #8279 and is needed due to https://github.com/haskell/cabal/pull/8279#issuecomment-1204599705
=> Bump package process dependency version to 1.6.15.0 and move from Cabal to cabal-install

cabal-install/src/Distribution/Client/CmdBuild.hs, cabal-install/src/Distribution/Client/CmdHaddock.hs, changelog.d/issue-8351
=> Expose BuildFlags and ClientHaddockFlags

.github/workflows/validate.yml, cabal-testsuite/PackageTests/NewSdist/DeterministicTrivial/deterministic.test.hs
See https://github.com/haskell/cabal/issues/8356 and https://github.com/haskell/cabal/pull/8385.
=> Exclude CI job 8.10.7 on Windows that corrupts all CI

cabal-install/src/Distribution/Client/CmdUpdate.hs
=> [ docs ] fix typo in cabal update’s help

doc/cabal-package.rst
Addresses documentation changes requested in PR #8115. I've reverted some additional changes that I made, since the original PR made _type_ optional for all _cabal-version_'s, but PR #8138 limited change to versions >= 3.8.
=> Fix optional test-suite/benchmark type docs

cabal-install/src/Distribution/Client/CmdHaddock.hs, cabal-testsuite/PackageTests/NewHaddock/DisableDoc/B/B.cabal, cabal-testsuite/PackageTests/NewHaddock/DisableDoc/B/B.hs, cabal-testsuite/PackageTests/NewHaddock/DisableDoc/cabal.out, cabal-testsuite/PackageTests/NewHaddock/DisableDoc/cabal.project, cabal-testsuite/PackageTests/NewHaddock/DisableDoc/cabal.test.hs, cabal-testsuite/PackageTests/NewHaddock/DisableDoc/repo/A-0.1.0.0/A.cabal, cabal-testsuite/PackageTests/NewHaddock/DisableDoc/repo/A-0.1.0.0/A.hs
Trying to fix my fault from #8259 (thanks @andreasabel for noticing):  `cabal haddock --disable-documentation` seems to work as expected with this patch. 
Below is a description of a problem I initially had but no more. Preserved for historical interest.
---
But the testsuite is not cooperating. I see two options: you, guys, help me or allow me to ditch the test.
Here's the deal with the test:
```haskell
main = cabalTest . withRepo "repo" . fails $
cabal "haddock" ["--disable-documentation", "B"]
```
should work, but it fails even when
```shell
❯ cabal run cabal-tests -- --with-cabal=(cabal list-bin cabal) cabal-testsuite/PackageTests/NewHaddock/DisableDoc/cabal.test.hs --accept
```
I see the output I'm expecting to see, in particular:
```shell
100% (  2 /  2) in 'B'
Warning: B: could not …
```
=> unbreak cabal haddock --disable-documentation

bootstrap/README.md, bootstrap/cabal-bootstrap-gen.cabal, bootstrap/src/Main.hs
Bump `cabal-bootstrap-gen` to GHC 9.2.4 ecosystem.
I ran `cabal outdated`, relaxed upper bounds, and then took away these highest versions which were not picked up by `cabal build -w ghc-9.2.4` (according to `cabal-plan`).
Also polished README a bit.
=> Bump cabal-bootstrap-gen to GHC 9.2.4 ecosystem.

cabal-testsuite/PackageTests/NewBuild/CmdRun/Terminate/Main.hs, cabal-testsuite/PackageTests/NewBuild/CmdRun/Terminate/RunKill.cabal, cabal-testsuite/PackageTests/NewBuild/CmdRun/Terminate/cabal.test.hs
Compare #8416. This adds timestamped debug output, so that next time it fails we can tell a bit better what went wrong.
=> Add some debugging to CmdRun/Terminate test

cabal-install/main/Main.hs
This Fixes #8393
The message warning about assertions being enabled was previously being output to the stdout stream rather than stderr.
---
=> Updated warning message to output on stderr

README.md
[>>> Rendered](https://github.com/haskell/cabal/blob/ap/readme-update-2022-08/README.md)
- add cabal-install-solver to the list of main packages in the repo
- turn ways to install cabal-install into a list instead of a sequence of headers
- add GHCup as the preferred option for getting cabal
- add a reference to CONTRIBUTING.md
---
=> facelift for README

Cabal/src/Distribution/PackageDescription/Check.hs, Cabal/src/Distribution/Simple/Configure.hs, Cabal/src/Distribution/Simple/SrcDist.hs, changelog.d/pr-8311
Both principled (we export, use a pretty printer) and pragmatic (we don't surprise programs depending on `Cabal` by modifying `Show` behaviour (yet)) stance.
---
Testsuite runs fine.
=> Add PackageCheck pretty print

doc/cabal-commands.rst
Requested in #8309 , #8315
---
=> Organise cabal commands into subsections

cabal-testsuite/main/cabal-tests.hs
Make `cabal-test` tests will end with a useful summary:
```
⁝
ConfiguredPackage/License/UnknownLicence/cabal.test.hs                      OK (0.13s)
ConfiguredPackage/License/NoFileSpecified/cabal.test.hs                     OK (0.14s)
ConfiguredPackage/License/NoLicense/cabal.test.hs                           OK (0.13s)
OK
112 tests, 0 skipped, 0 unexpected passes, 0 unexpected fails.
```
This is useful when you are dealing with a lot of failures (e.g. refactoring) and an integer is more useful than a long list of test names.
---
=> Add test summary

Cabal-tests/tests/ParserTests/regressions/issue-774.check, Cabal/src/Distribution/PackageDescription/Check.hs, changelog.d/pr-8432
Fixes #8431. Accompanied by option -flink-rts, option -threaded defines
the flavour of the ghc RTS library the built library will be linked
against. Note that bare ghc does not warn when option -threaded is used
for building a library either.
---
=> Remove warning on option -threaded when building libraries

.github/mergify.yml
Add the same conditions that we apply for the last stage of PR: 2 approvers and merge-me label. Otherwise, we get a lot of old PRs as well as some current ones getting the label prematurely.
As discussed here: https://github.com/haskell/cabal/pull/7386#issuecomment-1235254158
---
=> [ mergify ] fix condition of 'merge delay passed' label

cabal-testsuite/PackageTests/NewSdist/DeterministicTrivial/deterministic.test.hs
It still hits us. All updates are over on #8356.
This reverts commit c68ed017512a6523f8cc81f7bddf2af935a65147.
---
=> Revert "Revert "Turn off DeterministicTrivial test (see #8356)""

.github/workflows/bootstrap.yml, bootstrap/README.md, bootstrap/bootstrap.py, changelog.d/pr-8368
This ports to cabal-install the offline bootstrapping logic which was
introduced for Hadrian in GHC MR !6315.
This adds a "fetch" command to the bootstrap script, which fetches
all the dependency tarballs from Hackage, to be used in an offline
build. See bootstrap/README.md for further information.
I tested this locally but would appreciate further testing, perhaps changing the bootstrap CI scripts to separately fetch the archive and then build with the archives.
---
=> Allow offline bootstrapping of cabal-install

cabal-install/src/Distribution/Client/Manpage.hs, changelog.d/issue-8405
=> cabal man handles $PAGER with more than one word now

doc/conf.py
=> [ci skip] Enable opensearch in Cabal documentation

.github/workflows/validate.yml, cabal-install-solver/cabal-install-solver.cabal, cabal-install/cabal-install.cabal, cabal-testsuite/PackageTests/Backpack/Includes2/setup-external.test.hs, cabal-testsuite/PackageTests/Backpack/Includes2/setup-per-component.test.hs, cabal-testsuite/PackageTests/Backpack/Includes3/setup-external-ok.test.hs, cabal-testsuite/PackageTests/CCompilerOverride/setup.test.hs, cabal-testsuite/PackageTests/CustomPreProcess/cabal.test.hs, cabal-testsuite/PackageTests/FFI/ForeignOptsC/cabal.test.hs, cabal-testsuite/PackageTests/FFI/ForeignOptsCxx/cabal.test.hs, cabal-testsuite/PackageTests/ForeignLibs/UseLib.c, cabal-testsuite/PackageTests/ForeignLibs/setup.test.hs, cabal-testsuite/PackageTests/NewBuild/CmdBench/OptionsFlag/cabal.test.hs, cabal-testsuite/PackageTests/NewBuild/CmdBuild/Script/cabal.test.hs, cabal-testsuite/PackageTests/NewBuild/CmdBuild/ScriptBuildRepl/cabal.test.hs, cabal-testsuite/PackageTests/NewBuild/CmdBuild/ScriptBuildRun/cabal.test.hs, cabal-testsuite/PackageTests/NewBuild/CmdBuild/ScriptRerun/cabal.test.hs, cabal-testsuite/PackageTests/NewBuild/CmdClean/Keep/cabal.test.hs, cabal-testsuite/PackageTests/NewBuild/CmdClean/Orphan/cabal.test.hs, cabal-testsuite/PackageTests/NewBuild/CmdClean/Script/cabal.test.hs, cabal-testsuite/PackageTests/NewBuild/CmdRun/Script/cabal.test.hs, cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptLiterate/cabal.test.hs, cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptNoExtension/cabal.test.hs, cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptRerun/cabal.test.hs, cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptWithProjectBlock/cabal.test.hs, cabal-testsuite/PackageTests/NewBuild/CmdTest/OptionsFlag/cabal.test.hs, cabal-testsuite/cabal-testsuite.cabal
Current status: slowly working through test failures... See discussion below.
---
=> Support GHC 9.4

.github/workflows/quick-jobs.yml, cabal-dev-scripts/cabal-dev-scripts.cabal
This is a workaround for #7798 based on the theory that the recent CI breakage is caused by GHA bumping GHC to 9.4 (I'm quite surprised, but OTOH 9.4 is a good release and IIRC an LTS release).
Edit: a correction: it seems to be GHC 9.2. Much less surprising.
Edit2: actually, it seems this was not GHA upgrading GHC, but ghcup changing the "recommended" version and our scripts install that version
=> Work around CI problem from ghcup switch to GHC 9.2

.github/workflows/changelogs.yml, .github/workflows/users-guide.yml, .github/workflows/whitespace.yml
This is a continuation of #8503. It turns out https://github.com/phadej/changelog-d/pull/2 requires a fixed GHC in CI, as well, but it must have been cached, so I CI passed fine in the workaround PR, but failed in #7386.
=> Stick to GHC 8.10.7 in CI until changelog-d is updated and update CI job names to permit making them mandatory in Settings

Cabal-syntax/src/Language/Haskell/Extension.hs, Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs, changelog.d/pr-8493, editors/vim/syntax/cabal.vim
This change adds the `TypeData` language extension (ghc extension [106](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0106-type-data.rst). GHC merge request [!8962](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8962) has been approved.
=> add DeepSubsumption and TypeData language extensions (ghc proposals 511 & 106)

cabal-install/src/Distribution/Client/ProjectOrchestration.hs, cabal-testsuite/PackageTests/ConfigFile/T8487/cabal.out, cabal-testsuite/PackageTests/ConfigFile/T8487/cabal.project, cabal-testsuite/PackageTests/ConfigFile/T8487/cabal.test.hs, cabal-testsuite/PackageTests/ConfigFile/T8487/config.file, cabal-testsuite/PackageTests/ConfigFile/T8487/src/MyLib.hs, cabal-testsuite/PackageTests/ConfigFile/T8487/test.cabal, changelog.d/issue-8487
It still reports local config's optimization level if it was set.
Fix #8487.
---
=> "Build profile" now reflects optimization level set in global config

Cabal/src/Distribution/Simple/Build/PathsModule/Z.hs, cabal-testsuite/PackageTests/PathsModule/ImportQualifiedPost/Main.hs, cabal-testsuite/PackageTests/PathsModule/ImportQualifiedPost/my.cabal, cabal-testsuite/PackageTests/PathsModule/ImportQualifiedPost/setup.cabal.out, cabal-testsuite/PackageTests/PathsModule/ImportQualifiedPost/setup.out, cabal-testsuite/PackageTests/PathsModule/ImportQualifiedPost/setup.test.hs, templates/Paths_pkg.template.hs
Enabling '-Wprepositive-qualified-module' in a project leads to warnings
when used in combination with Cabal's Paths_* feature. Given that this
is code outside of a user's control, this warning should be disabled
locally.
---
=> Don't warn about 'prepositive-qualified-module' in Paths_pkgs

cabal-install/src/Distribution/Client/CmdBuild.hs, cabal-install/src/Distribution/Client/CmdHaddockProject.hs, cabal-install/src/Distribution/Client/CmdListBin.hs, cabal-install/src/Distribution/Client/CmdRepl.hs, cabal-install/src/Distribution/Client/CmdRun.hs, cabal-install/src/Distribution/Client/ProjectOrchestration.hs, cabal-install/src/Distribution/Client/ScriptUtils.hs, cabal-testsuite/PackageTests/CustomWithoutCabal/cabal.out, cabal-testsuite/PackageTests/CustomWithoutCabalDefaultMain/cabal.out, cabal-testsuite/PackageTests/NewBuild/MonitorCabalFiles/cabal.out, cabal-testsuite/PackageTests/NewHaddock/Fails/cabal.out, cabal-testsuite/PackageTests/ShowBuildInfo/CompileFail/compile-fail.out
fix #5974 #7727
This is a cheap fix via straightforward extension of #6102
---
=> print out dependency build failure during cabal build / repl

Cabal-syntax/src/Language/Haskell/Extension.hs, Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs, editors/vim/syntax/cabal.vim
The extension is introduced in the accepted [GHC Proposal #281](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0281-visible-forall.rst). It hasn't been implemented in GHC yet, but I think it's fine if Cabal knows about it ahead of time.
=> Add RequiredTypeArguments to known extensions

Cabal-syntax/src/Distribution/PackageDescription/FieldGrammar.hs
These two types need to be exported for users to be able to define their own FieldGrammar.
---
=> Export CompatFilePath and CompatLicenseFile

doc/cabal-project.rst, doc/nix-local-build.rst
Please review carefully, I have never used any of these and only documented them in the way it makes sense to me, which is not necessarily the correct one.
closes #5448 
---
=> Document extra-packages a bit better and clean up related entries (closes #5448)

.github/mergify.yml
=> CI: mergify should label automatic backports as such

.github/mergify.yml
That was an oversight on my part when I did it initially: the squash label was overseen.
=> mergify: two-day delay should account for the squash label

cabal.project, cabal.project.coverage, cabal.project.libonly, cabal.project.validate, cabal.project.validate.libonly
Simplifies `*.project.*` files a bit. It wasn't feasible before #7973, as `program-options` were applied to dependencies as well, which is undesirable.
This is undoing 0c99981, which was a stop-gap against #3911. #7973 should cover #3911 these days.
**TODO**:
---
=> *.project.* files use program-options to specify -fno-ignore-asserts

.github/workflows/validate.yml
We use the latest Ubuntu GHA container, which has some advantages, but gets us bitten by such bugs early and so we have to workaround ourselves.
=> Work around git problem with file transport

bootstrap/bootstrap.py
Trying to fix bootstrap job currently broken on CI via explicitly setting a timeout.
=> Set urllib.request.urlopen timeout in bootstrap.py to fix CI

doc/cabal-package.rst
As of cabal-version: 3.4 and higher, it's necessary to use a different syntax to depend on internal libraries than previous versions. Document this change in a note block in the Internal Libraries section.
See: #7565
---
* [X ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [X ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [ X] The documentation has been updated, if necessary.
=> Document internal library syntax changes

bootstrap/bootstrap.py
Again trying to fix bootstrap job currently broken on CI via explicitly setting a timeout. I think the past attempt #8576 helped, but the lag has grown since. But I may be wrong.
=> Increase urllib.request.urlopen timeout in bootstrap.py to fix CI

.github/workflows/bootstrap.yml
A follow-up to #8594 that failed, at least in cases where the error is "Errno 110", meaning ETIMEDOUT, meaning host unreachable or possibly something else similarly non-recoverable.
=> Cache whole of ~/.cabal in bootstrap.yml to fix CI

.github/workflows/bootstrap.yml
This is a fixup PR for #8595. Apparently, the `~./cabal` path from one of our other CI scripts is unused here, so caching was void, so I've hardwired `/home/runner/work/cabal/cabal/_build` instead.
=> Hardwire a different CI cache path, to fix CI

doc/cabal-commands.rst, doc/getting-started.rst
This is a useful feature which I think would benefit newcomers by being a top-level, early entry in the docs. See: https://stackoverflow.com/a/65541020
* [*] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#conventions).
* [*] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [*] The documentation has been updated, if necessary.
No code changes. Documentation only.
=> add documentation for single-file Haskell scripts

.github/dependabot.yml
This will alert of outdated actions used in our workflows.
Copied from https://github.com/haskell/hackage-server/commit/2dadc2ac60a3d259e26282492ddd6ac29917afef
---
=> Add dependabot for github workflows

cabal-install/src/Distribution/Client/Utils.hs
The C call is almost exactly the same as GHC.Conc.Sync.getNumProcessors, and we used the C function from GHC, so there should be no actual difference.
---
=> Use GHC.Conc.Sync.getNumProcessors instead of C

Cabal-syntax/src/Language/Haskell/Extension.hs, Cabal/src/Distribution/Simple/Configure.hs
CLC has approved the proposal to add `{-# WARNING #-}` to `Data.List.{head,tail}` (https://github.com/haskell/core-libraries-committee/issues/87). It means that usage of `head` and `tail` will emit compile-time warnings.
This patch eliminates `head` and `tail` in `Cabal-syntax` and `Cabal` packages. These are boot packages, so it's important for GHC HEAD to compile them without any warnings.
=> Avoid `Data.List.{head,tail}`

cabal-install/src/Distribution/Client/Win32SelfUpgrade.hs
This completes the backport of the fix for #7835 for 3.6 (done in #7983) 
which was missing this change included in 3.8 (#7982).
(see for example commercialhaskell/stackage#6778)
=> [3.6] fixup sYNCHRONIZE for Win32-2.8+

Cabal-syntax/src/Distribution/Types/BenchmarkInterface.hs, Cabal-syntax/src/Distribution/Types/TestSuiteInterface.hs
Hi, I'm hoping to solicit comments/design discussion on an idea to add a new test suite interface. 
I'm the author of the [Sandwich](https://codedownio.github.io/sandwich/) test framework, which provides a way of running and visualizing tests in a terminal UI interface. It would be nice to add first-class support for this way of working to tooling like Cabal, so you could type `cabal test` from your terminal and get dropped into the interface.
This is currently not possible because Cabal's existing test suite types don't allow the tests to use `stdin`; see the [exitcode-stdio-1.0](https://hackage.haskell.org/package/Cabal-syntax-3.8.1.0/docs/Distribution-Types-TestSuiteInterface.html#v:TestSuiteExeV10) documentation.
This PR proposes to add a new `TestSuiteInterface` constructor called …
=> Change exitcode-stdio-1.0 description to match current status quo

.github/workflows/validate.yml
If this solves CI linking errors on 9.4.2, let's merge for the time being, without the waiting period. One more review needed. After the underlying problem is fixed or a ticket created, let's link it (edit: it's here: https://github.com/haskell/cabal/issues/8630).
=> Downgrade ubuntu image to fix a CI linker failure to do with package resolve

cabal-install/src/Distribution/Client/CmdListBin.hs
Fixes #8400
unsure if using the correct service functions to do this 😄 
---
=> add marked output to `cabal list-bin`

Cabal/src/Distribution/Simple/BuildPaths.hs, Cabal/src/Distribution/Simple/Utils.hs, changelog.d/pr-8633
This PR changes default exe extension on wasm32 to be `.wasm`, following convention of other WebAssembly toolchains. This is a part of the effort tracked in https://gitlab.haskell.org/ghc/ghc/-/issues/22594.
---
=> Specify default exe extension on wasm32 to be .wasm

cabal-install/src/Distribution/Client/PackageHash.hs, cabal-install/src/Distribution/Client/ProjectPlanning.hs, changelog.d/pr-7794
Continuing working on the matter and found we were missing the extra-libs-static in PackageHash.
---
=> Include extra-lib-dirs-static into PackageHash

cabal-install/src/Distribution/Client/Configure.hs, cabal-install/src/Distribution/Client/Install.hs, cabal-install/src/Distribution/Client/ProjectPlanOutput.hs, cabal-install/src/Distribution/Client/ProjectPlanning.hs, cabal-install/src/Distribution/Client/SetupWrapper.hs, cabal-install/tests/IntegrationTests2.hs, cabal-testsuite/PackageTests/LinkerOptions/NonignoredConfigs/basic/basic/Basic.hs, cabal-testsuite/PackageTests/LinkerOptions/NonignoredConfigs/basic/basic/basic.cabal, cabal-testsuite/PackageTests/LinkerOptions/NonignoredConfigs/basic/cabal.project, cabal-testsuite/PackageTests/LinkerOptions/NonignoredConfigs/cabal.out, cabal-testsuite/PackageTests/LinkerOptions/NonignoredConfigs/cabal.test.hs, changelog.d/pr-8623
This was originally the first of two parts to the ‘Track static vs. dynamic dependencies.’ pull request ([#8461](https://github.com/haskell/cabal/pull/8461)), which I've cleaned up and split into two separate PRs.
This PR fixes an issue in which configuration flags such as ‘--disable-library-vanilla’ could be silently dropped when a package was built and installed, and it also adds a test that sets up a scenario to demonstrate the issue.
(I ran the cabal-testsuite/PackageTests test suite and found ‘432 tests, 6 skipped, 0 unexpected passes, 0 unexpected fails’.)
=> Fix project-local flags being ignored

Cabal-syntax/Cabal-syntax.cabal
The released Cabal-syntax 3.8.1.0 is already compatible with mtl-2.3.  I am intending to make the respective revision on Hackage (details see this PR).  This PR updates the 3.8 branch accordingly.
Lifted from: https://github.com/haskell/hackage-security/pull/289#issuecomment-1367200577
@Mikolaj wrote:
> if it's useful to anybody, I can revise even omitting the comment (but we should probably amend 3.8 branch, too, which has old bounds, so that somebody compiling from 3.8 branch source doesn't have worse bounds than from Hackage).
(I'd think the said comment can remain.)
=> Cabal-syntax-3.8.1.0: allow mtl-2.3 and transformers-0.6

cabal-install/src/Distribution/Client/SourceFiles.hs, changelog.d/pr-8640
Resolves https://github.com/haskell/cabal/issues/8632 
Resolves https://github.com/haskell/cabal/issues/8634
This was indeed a bug in https://github.com/haskell/cabal/pull/7608
The confusion is that the cabal in the 3.6 series tested against did not contain a backport of that patch.
The issue is that extra-source-file glob expansion was written to expand relative to "." rather than the relative root of the package in question. So this worked in single-package setups, but not when in the base directory of a project with multiple packages.
Along the way, this bumps the verbosity of glob expansion.
=> root relative glob expansion of extra source files

Cabal/Cabal.cabal, Cabal/src/Distribution/Simple.hs, Cabal/src/Distribution/Simple/ConfigureScript.hs, changelog.d/pr-8648
See each commit for details. There are no public interface changes, just shuffling around private details.
=> Tiny refactor of how Cabal handles configure scripts

Cabal-tests/tests/CheckTests.hs, Cabal-tests/tests/ParserTests/regressions/issue-8646.cabal, Cabal-tests/tests/ParserTests/regressions/issue-8646.check, Cabal/src/Distribution/PackageDescription/Check.hs, changelog.d/issue-8646
Fix #8646. I've checked that cabal doesn't complain about presence of `-main-is` whereas it does complain if I revert the commit. 
Please let me know if you'd like to add a test for this.
---
=> Remove "'-main-is' is not portable" check

doc/cabal-package.rst, doc/file-format-changelog.rst
Re #6125: document that glob dirs are buggy in Cabal 2.4.
`cabal-version: 2.4` allows e.g. `data-files: foo/**/*.txt` but `**` directories are only handled correctly since Cabal 3.0 (issue #6125). This information should be part of the cabal file format history documentation.
Rendering here:
- End of this section: https://cabal--8665.org.readthedocs.build/en/8665/cabal-package.html#pkg-field-data-files
- "Caveat" here: https://cabal--8665.org.readthedocs.build/en/8665/file-format-changelog.html#cabal-version-2-4
Relevant CI succeeds.
=> Re #6125: document that glob dirs are buggy in Cabal 2.4

cabal-install/src/Distribution/Client/CmdListBin.hs, cabal-testsuite/PackageTests/ListBin/Script/cabal.out, cabal-testsuite/PackageTests/ListBin/SelectedComponent/cabal.out, cabal-testsuite/PackageTests/ListBin/SelectedComponent/cabal.test.hs
Fix #8400 by marking output of `cabal list-bin`
The regular output of `cabal list-bin` should go to stdout always, but be marked for the sake of the testsuite.
- fixes #8400 
- fixes #8664 
If this PR is merged quickly, we do not need:
- #8668
Replaces:
- #8622
=> Fix #8400 by marking output of `cabal list-bin`

cabal-testsuite/README.md, cabal-testsuite/main/cabal-tests.hs, cabal-testsuite/src/Test/Cabal/Monad.hs
cabal-testsuite #8401: communicate better the need for `--with-cabal`
- include option `--help` in `cabal-testsuite` (separate commit)
- include warning in help text for option `--with-cabal`
- include `--with-cabal` in README examples
- passer-by: remove a CPP-avoidance hack (separate commit)
N.B. Separate commits, no squashing please!
=> cabal-testsuite #8401: communicate better the need for `--with-cabal`

Cabal/src/Distribution/PackageDescription/Check.hs, Cabal/src/Distribution/Simple/Glob.hs, cabal-testsuite/PackageTests/Check/ConfiguredPackage/Paths/RecursiveGlobInRoot/cabal.out, cabal-testsuite/PackageTests/Check/ConfiguredPackage/Paths/RecursiveGlobInRoot/cabal.test.hs, cabal-testsuite/PackageTests/Check/ConfiguredPackage/Paths/RecursiveGlobInRoot/pkg.cabal, changelog.d/pr-8441
Such globs might be expensive to include, as they might pull unnecessary
directories just like `.git` or `dist-newstyle`.
Solves #5311.
I would happily add tests for that, but I don't see any tests for warnings in cabal-check
---
Tested manually with .cabal file that uses expressions **/*.ext in `data-files`, `extra-source-files` and `extra-doc-files`.
```
Warning: The following warnings are likely to affect your build negatively:
Warning: In the 'data-files' field: File glob **/*.dat starts at project root
directory this might include `.git/`, ``dist-newstyle/``, or other large
directories!
Warning: In the 'extra-source-files' field: File glob **/*.hs …
```
=> Add check for recursive glob in root directory

cabal-install/src/Distribution/Client/TargetSelector.hs
This is a mediocre solution, and really should generate a different error entirely at an earlier stage, but I'm not familiar enough with how to achieve that and I don't think I have time at the moment.
Fixes #8484.
```
[nix-shell:~/co/cabal/t8484]$ cabal build lib:generic-deriving
Error: cabal: Internal error in target matching. It should always be possible
to find a syntax that's sufficiently qualified to give an unambiguous match.
However when matching 'lib:generic-deriving' we found lib:generic-deriving
(unknown-component) which does not have an unambiguous syntax. The possible
syntax and the targets they match are as follows:
'lib:generic-deriving' which matches lib:generic-deriving (unknown-component),
:pkg:lib:lib:lib:file:generic-deriving (unknown-file) …
```
=> TargetSelector: Include a hint in the error message for internal error

cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs, cabal-testsuite/PackageTests/LinkerOptions/NonignoredConfigs/cabal.test.hs, cabal-testsuite/PackageTests/RelativePathProjectImports/Lib.hs, cabal-testsuite/PackageTests/RelativePathProjectImports/cabal.out, cabal-testsuite/PackageTests/RelativePathProjectImports/cabal.project, cabal-testsuite/PackageTests/RelativePathProjectImports/cabal.test.hs, cabal-testsuite/PackageTests/RelativePathProjectImports/dep/Dep.hs, cabal-testsuite/PackageTests/RelativePathProjectImports/dep/cabal.project, cabal-testsuite/PackageTests/RelativePathProjectImports/dep/dep.cabal, cabal-testsuite/PackageTests/RelativePathProjectImports/dep2/Dep2.hs, cabal-testsuite/PackageTests/RelativePathProjectImports/dep2/dep2.cabal, cabal-testsuite/PackageTests/RelativePathProjectImports/main.cabal, cabal-testsuite/src/Test/Cabal/CheckArMetadata.hs, changelog.d/pr-8686
Fix bug where cabal tries to resolve imports by relative paths against the directory cabal executable was invoked in rather than directory of cabal.project file that does the import.
The problem occurs if `<toplevel>/cabal.project` does something like `import: dep/cabal.project` and then `cabal build` is invoked from some subridectory e.g. `<toplevel>/dep2`. Cabal tries to resolve `dep/cabal.project` against `<toplevel>/dep2` but it probably should do the resolution against the `<toplevel>` directory that contains `cabal.project` that does the import.
---
=> Fix project relative imports

Cabal/src/Distribution/Simple/GHC.hs
If somebody would like to address https://github.com/haskell/cabal/pull/8260#discussion_r911641340 and factor out the thrice used GHC version number constant, pretty please do, before this PR gets merged. Otherwise, let's kick the can once again.
=> Bump known ghc versions in cabal library to < 9.8

cabal-install/src/Distribution/Client/CmdListBin.hs
Fix #8664 redux: add EOL character to list-bin output.
=> Fix #8664 redux: add EOL character to list-bin output

cabal-install/src/Distribution/Client/FetchUtils.hs, cabal-install/src/Distribution/Client/ProjectPlanning.hs
This removes the warning spam from https://github.com/haskell/cabal/pull/8500
Now we check if a file exists before attempting to compute the hash of it. Doh.
=> elim warning spam from #8500

cabal-install/src/Distribution/Client/Init/Interactive/Command.hs, changelog.d/issue-8680
Any Cabal release prior to 2.0 is no longer working, so cabal should not suggest users to set the `cabal-version` on packages to less than 2.0 as mentioned in #8680. 
With this, the least choice offered to users is 2.0.
=> Fix cabal init should not suggest Cabal < 2.0

.github/workflows/changelogs.yml, .github/workflows/whitespace.yml
This is a continuation of #8739, which fixed a CI problem that now shows up also in these scripts. I hope there is no more affected code.
=> Work around ghcup cache woes also in our tiny CI scripts

changelog.d/issue-8737, doc/cabal-project.rst
Fixes #8737 
---
I tested that the feature really is implemented and left a transcript on the issue.  I tested that the docs build and render using Python 3.8 on NixOS 22.11 in a virtualenv using the `requirements.txt` in the repo and visual inspection.
=> Document the `remote-repo-cache` option as is implemented (it is).

cabal-install/src/Distribution/Client/Config.hs
Johan Tibell is not part of the signing process anymore, so his key is removed.
I've also annotated the keys with their owners and public keys, because every time we consult this, I end up spending a bunch of time in a scratch buffer correlating key IDs, public key values, and ownership attestations. Might as well save the work for next time, with appropriate disclaimers added.
---
I was unable to test the changes, as I can't build the contents of the repo right now:
```
$ cabal update
Downloading the latest package list from hackage.haskell.org
Updated package list of hackage.haskell.org to the index-state 2023-01-13T05:15:22Z
To revert to previous …
```
=> Update bootstrap root keys

cabal-install/src/Distribution/Client/Configure.hs, cabal-install/src/Distribution/Client/Install.hs, cabal-install/src/Distribution/Client/ProjectPlanOutput.hs, cabal-install/src/Distribution/Client/ProjectPlanning.hs, cabal-install/src/Distribution/Client/SetupWrapper.hs, cabal-install/tests/IntegrationTests2.hs, cabal-testsuite/PackageTests/LinkerOptions/NonignoredConfigs/cabal.test.hs, changelog.d/pr-8623
This reverts commit b547ead58bf09bb838c13f02afb2f1042ad1bc7c
from https://github.com/haskell/cabal/pull/8623.
Unexpected side-effect has been found (#8719 and #8721), 
so these code improvements have to be done differently.
The other commit in the reverted PR is a test and it's retained 
and marked as expected broken.
=> Revert "Fix project-local build flags being ignored."

.github/workflows/quick-jobs.yml, Makefile, cabal-testsuite/README.md
which is `cabal repl --with-ghc=doctest`. This not only catches up with the current upstream recommendations, but also simplifies the usage: before this change calling doctest required you to set up an environment with QuickCheck available (we used to do it via cabal-env). The new method takes care of it automatically.
Also add some docs to fix #8147
---
=> doctests: switch to the preffered method of calling the tool

cabal-install/src/Distribution/Client/FetchUtils.hs
Resolves https://github.com/haskell/cabal/issues/8708 and https://github.com/haskell/cabal/issues/8706
Sorry, no additional regression test for this.
=> don't auto-download in hash validation phase

doc/nix-local-build.rst
Documentation says “config (same format as cabal.project)”, but it is an internal binary format.
Close #8782
---
=> Fix `config` format docs.

Cabal-syntax/Cabal-syntax.cabal, Cabal-tests/Cabal-tests.cabal, Cabal/Cabal.cabal, cabal-install-solver/cabal-install-solver.cabal, cabal-testsuite/cabal-testsuite.cabal, changelog.d/pr-8794
=> Disallow GHC <8.0 for Cabal{,-syntax} & cabal-install-solver

.github/workflows/changelogs.yml, .github/workflows/quick-jobs.yml, .github/workflows/validate.yml, Cabal-syntax/src/Distribution/Utils/Structured.hs, cabal-install/src/Distribution/Client/VCS.hs, cabal-testsuite/PackageTests/Backpack/Includes2/setup-external.test.hs, cabal-testsuite/PackageTests/Backpack/Includes2/setup-per-component.test.hs, cabal-testsuite/PackageTests/Backpack/Includes3/setup-external-ok.test.hs, cabal-testsuite/PackageTests/JS/JsSources/js-arch.test.hs
Currently: 9.6alpha3. Corresponding issue #8675.
This is more of an experiment for now.
=> CI: add GHC pre-release

cabal-install/src/Distribution/Client/CmdInstall.hs, cabal-testsuite/PackageTests/LinkerOptions/NonignoredConfigs/cabal.test.hs, changelog.d/issue-8637
---
---
This PR reverses the effects of https://github.com/haskell/cabal/pull/7973 specifically for targets of the "install" command to more closely match expected behavior.
Before this change:
```
cabal v2-install --ghc-option=-foo hello
```
would not apply "-foo" to "hello" because "hello" is not a local package. After this change, -foo is applied to "hello" because it is a direct target of the install command, so gets the local package configs added to it.
To test, I ran:
```
cabal install --ghc-option=-foo alex --verbose
```
which resulted in:
```
/home/patrick/projects/haskell/cabal/dist-newstyle/build/x86_64-linux/ghc-9.2.3/cabal-install-3.9.0.0/x/ …
```
=> Apply command line flags to install packages (#8637)

Cabal-syntax/src/Distribution/Compat/Prelude.hs
Cabal codebase has its fair share of Applicatives/Monads. Adding traceM and traceShowM to the Compat.Prelude is quite convenient for testing purposes.
---
=> Add traceM and traceShowM

cabal-install/src/Distribution/Client/CmdClean.hs, cabal-install/src/Distribution/Client/CmdOutdated.hs, cabal-install/src/Distribution/Client/Config.hs, cabal-install/src/Distribution/Client/DistDirLayout.hs, cabal-install/src/Distribution/Client/ProjectConfig.hs, cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs, cabal-install/src/Distribution/Client/ProjectConfig/Types.hs, cabal-install/src/Distribution/Client/ProjectFlags.hs, cabal-install/src/Distribution/Client/ProjectOrchestration.hs, cabal-install/tests/IntegrationTests2.hs, cabal-install/tests/UnitTests/Distribution/Client/Configure.hs, cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs, cabal-testsuite/PackageTests/ConditionalAndImport/cabal.test.hs, cabal-testsuite/PackageTests/Outdated/outdated-project-file.out, cabal-testsuite/PackageTests/ProjectDir/app/App.hs, cabal-testsuite/PackageTests/ProjectDir/app/app.cabal, cabal-testsuite/PackageTests/ProjectDir/cabal.test.hs, cabal-testsuite/PackageTests/ProjectDir/proj/App.hs, cabal-testsuite/PackageTests/ProjectDir/proj/Lib.hs, cabal-testsuite/PackageTests/ProjectDir/proj/cabal.project, cabal-testsuite/PackageTests/ProjectDir/proj/nix/cabal.project, cabal-testsuite/PackageTests/ProjectDir/proj/proj.cabal, changelog.d/pr-8454, doc/cabal-project.rst
- Added `--project-dir` flag for specifying the project's root directory
- Deprecated using `--project-file` with an absolute path
- Partially resolves #7695 by deprecating absolute project file paths
- An alternative to #7749 (see Alternative proposal below)
- Implements one of the proposed features of #7940
- Resolves #8037
Given the following directory structure:
<pre>
/opt
|-- proj
|-- cabal.project
|-- nix/
|-- cabal.project
|-- lib/
</pre>
Where:
* _proj_ is the project root directory
* _lib_ contains a Cabal file
* _nix_ contains Nix-specific files
|   | current directory | --project-file            | resolved root   | notes |
|---|-------------------|---------------------------|-----------------|-------|
| 1 | _any_             | _/opt/proj/cabal.project_ | _/opt/proj_     | …
=> Add --project-dir flag

cabal-install/src/Distribution/Client/ProjectPlanning.hs
See discussion at https://github.com/haskell/cabal/issues/6006
=> Disable everfailing assertion

cabal-install/src/Distribution/Client/Init/Interactive/Command.hs, cabal-install/src/Distribution/Client/Init/NonInteractive/Command.hs, cabal-install/src/Distribution/Client/Init/NonInteractive/Heuristics.hs, cabal-install/tests/UnitTests/Distribution/Client/Init/FileCreators.hs, cabal-install/tests/UnitTests/Distribution/Client/Init/NonInteractive.hs
As mentioned in #8478, cabal init throws an error when git is not installed as it fails to guess a default name and email for the user. Instead, it should give an empty default (or no default perhaps?) and perhaps a note.
=> Return empty default when git fails

.github/workflows/validate.yml
We have a transient failure there due to bumping our package version numbers (https://github.com/haskell/cabal/pull/8844): the cabal testsuite can't be configured (https://github.com/haskell/cabal/issues/8133 strikes again). So, let's disable it, get CI green and wait until version numbers are settled with the addition of the proper 9.6 release (#8840).
The job could be reenabled later in the future when a new GHC prerelease appears (9.8 family).
=> CI: disable prerelease validation

cabal-install/src/Distribution/Client/Config.hs, cabal-testsuite/PackageTests/ConfigFile/InitSectionFields/cabal.out, cabal-testsuite/PackageTests/ConfigFile/InitSectionFields/cabal.test.hs, changelog.d/issue-8835
=> Allow no-comments, quiet, simple, minimal in init section of config

Cabal/Cabal.cabal
This revision of `Cabal-3.8.1.0` is already on Hackage: allow `mtl-2.3` and `transformers-0.6`.
Syncing to 3.8 branch.
=> Pull revision onto 3.8 branch: Cabal: allow mtl-2.3 and transformers-0.6

.gitlab-ci.yml
GitLab pipeline: [![pipeline status](https://gitlab.haskell.org/haskell/cabal/badges/wip/b/aarch64-linux/pipeline.svg)](https://gitlab.haskell.org/haskell/cabal/-/commits/wip/b/aarch64-linux) 
Makes headway on #8849 
Kudos to @hasufell for making this possible with a fix to GHCUp
=> GitLab CI: Add aarch64-linux-deb{10,11}

Cabal/src/Distribution/Simple/Configure.hs
=> Fix a typo in the split-objs/split-sections warning message

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
This PR adds instructions for adding manual QA instructions to new PRs that relate to cabal-install when a behaviour is introduced or modified.
Relates to #8865
=> Add instructions to the PR template for manual QA

Cabal-syntax/src/Distribution/Fields/Pretty.hs
=> Fix typo in Pretty.hs

cabal-install/src/Distribution/Client/Init/Format.hs, cabal-install/tests/UnitTests/Distribution/Client/Init/Golden.hs, cabal-install/tests/fixtures/init/golden/pkg-desc/pkg-with-flags.golden, changelog.d/issue-8206
Closes #8206. I updated one of the golden tests so it detects this stuff.
---
=> Prepends >= to cabal versions older than 1.12

Cabal/src/Distribution/PackageDescription/Check.hs, Cabal/src/Distribution/Simple/SrcDist.hs, cabal-install/src/Distribution/Client/Check.hs, cabal-install/src/Distribution/Client/Setup.hs, cabal-testsuite/PackageTests/Check/ConfiguredPackage/COptions/CxxOs/cabal.test.hs, cabal-testsuite/PackageTests/Check/ConfiguredPackage/CabalVersion/DefaultExtension/cabal.test.hs, cabal-testsuite/PackageTests/Check/ConfiguredPackage/CabalVersion/DefaultLanguage/cabal.test.hs, cabal-testsuite/PackageTests/Check/ConfiguredPackage/CabalVersion/ExtraDynamicLibraryFlavour/cabal.test.hs, cabal-testsuite/PackageTests/Check/ConfiguredPackage/CabalVersion/Mixins/cabal.test.hs, cabal-testsuite/PackageTests/Check/ConfiguredPackage/CabalVersion/Sources/cabal.test.hs, cabal-testsuite/PackageTests/Check/ConfiguredPackage/CabalVersion/VirtualModules/cabal.test.hs, cabal-testsuite/PackageTests/Check/ConfiguredPackage/Fields/DeprecatedExtension/cabal.test.hs, cabal-testsuite/PackageTests/Check/ConfiguredPackage/Fields/NoCategory/cabal.test.hs, cabal-testsuite/PackageTests/Check/ConfiguredPackage/Fields/NoDescription/cabal.test.hs, cabal-testsuite/PackageTests/Check/ConfiguredPackage/Fields/NoMaintainer/cabal.test.hs, cabal-testsuite/PackageTests/Check/ConfiguredPackage/Fields/NoSynopsis/cabal.test.hs, cabal-testsuite/PackageTests/Check/ConfiguredPackage/Fields/ShortDescription/cabal.test.hs, cabal-testsuite/PackageTests/Check/ConfiguredPackage/GHCOptions/GHCSharedOptions/cabal.test.hs, cabal-testsuite/PackageTests/Check/ConfiguredPackage/License/NoFileSpecified/cabal.test.hs, cabal-testsuite/PackageTests/Check/ConfiguredPackage/License/SuspiciousLicense/cabal.test.hs, cabal-testsuite/PackageTests/Check/ConfiguredPackage/License/SuspiciousVersion/cabal.test.hs, cabal-testsuite/PackageTests/Check/ConfiguredPackage/License/WarnAllRightsReserved/cabal.test.hs, cabal-testsuite/PackageTests/Check/ConfiguredPackage/Sanity/VersionSignatures/cabal.test.hs, cabal-testsuite/PackageTests/Check/NonConfCheck/DevOnlyFlags/Profiling/cabal.test.hs, cabal-testsuite/PackageTests/Check/NonConfCheck/UnusedFlags/cabal.test.hs, cabal-testsuite/PackageTests/Check/PackageFiles/VCSInfo/cabal.test.hs, changelog.d/pr-8897, doc/cabal-commands.rst
tl;dr: `cabal check` will exit with `1` if and only if `Hackage would reject the package`.
As today, `cabal check` handles reports a “failure” in two distinct ways:
- first one: with an informative `Hackage would reject this package.` string
- second one: with exitcode `1`. This one is *not* the same as `Hackage would reject this package.` It is a bit more strict: you could end up with `exitcode 1` but no `Hackage would reject this package.` string.
What this patch does: make the two “failures” bijective. You will get `exitcode 1` iif `Hackage would reject this package.`
Examples of checks which will *not* exit with `1` anymore:
- `description` longer than `synopsis`;
- `-O1` usage;
- missing `maintainer`.
Check last commit for all of them. If someone has a good reason for them to return …
=> Make `check` comply with Hackage requirements

.github/workflows/validate.yml, Makefile, validate.sh
=> CI: remove dependency on cabal-plan (#8891)

doc/cabal-commands.rst
Didn't do any of the listed below, sorry.
---
=> docs: cabal repl fresh-up

doc/cabal-project.rst
Available since 3.10, not 3.8.
Closes #8656
---
=> Fix `prefer-oldest` documentation

Cabal/src/Distribution/Simple/BuildTarget.hs
For CLC ticket [\#86](https://github.com/haskell/core-libraries-committee/issues/86)
---
[N/A] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
[N/A] The documentation has been updated, if necessary.
[N/A] Include [manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) if your PR relates to cabal-install.
=> Avoid using to-be-deprecated Data.List.NonEmpty.unzip

.github/workflows/validate.yml, README.md
As announced on the meeting, this PR adds an automated GitHub prerelease holding the `cabal-install` binaries in this repository.  If you wanna taste what it looks like, you can head out to my fork: the [Releases](https://github.com/ulysses4ever/cabal/releases) tab has the [`cabal-head`](https://github.com/ulysses4ever/cabal/releases/tag/cabal-head) prerelease with three binaries for the three main OSes in the `Assets` section -- that's what you get with this PR.
I add a note about it in the README but perhaps some more advertisement could be done (not sure how). Prereleases appear only on the Releases tab in GitHub UI, while proper releases are also featured on the index page of the repo. So, it's not very visible...
I'm not sure if `ghcup` can be used to easily get these. Suggestions …
=> CI: add automated GitHub prereleases

cabal-install/src/Distribution/Client/Config.hs, changelog.d/issue-8577, doc/config.rst
This is a draft implementation of #8577.
There is one flaw in this implementation: the warning is printed many times, and with non-configurable verbosity.  Changing that would require one of:
1) Significant refactoring of how `getDefaultDir` is called, which has non-local implications.
2) Doing the warning somewhere else (e.g. in Main.hs).
---
=> Ignore ~/.cabal if $XDG_CONFIG_HOME/cabal/config exists.

cabal-install/src/Distribution/Client/Setup.hs, doc/cabal-commands.rst
Highlight which issues are critical for uploading to Hackage and which are not, as suggested on `#cabal`. Rendered:
---
~~Bonus points for added automated tests!~~ no need
=> Clarify `check` documentation

Cabal-syntax/src/Distribution/Compat/Prelude.hs, Cabal-tests/tests/UnitTests/Distribution/Utils/CharSet.hs
See https://github.com/haskell/core-libraries-committee/issues/167
This is, of course, a bit speculative at the moment, but given that the change does not involve CPP, it should not hurt to merge it early to simplify further impact assessment.
=> Future-proof against potential Prelude.foldl'

doc/cabal-package.rst
Just fixing some docs, so nothing below applies I think.
---
=> Put back docs for code-generators (fix #8887)

Cabal-tests/Cabal-tests.cabal, Cabal-tree-diff/Cabal-tree-diff.cabal, cabal-install-solver/cabal-install-solver.cabal, cabal-install/cabal-install.cabal, cabal-testsuite/cabal-testsuite.cabal
bump a few bounds to allow building with ghc-9.6
Yes cabal-install-3.10 ought to be buildable with 9.6...
=> allow building cabal-install-3.10 with ghc-9.6

cabal-install/src/Distribution/Client/ProjectConfig.hs, cabal-install/src/Distribution/Client/ProjectPlanning.hs, cabal-testsuite/PackageTests/Project/WarnBuilddir/cabal.out, cabal-testsuite/PackageTests/Project/WarnBuilddir/cabal.project, cabal-testsuite/PackageTests/Project/WarnBuilddir/cabal.test.hs, cabal-testsuite/PackageTests/Project/WarnBuilddir/main.cabal, changelog.d/pr-8949, doc/cabal-project.rst
=> Warn if builddir is going to be ignored

Cabal-QuickCheck/src/Test/QuickCheck/Instances/Cabal.hs
As described in #8986, you can run
```
❯ cabal run cabal-install:unit-tests -- -j1 -p '/individual parser tests/' --quickcheck-replay=122872
```
before and after this patch: you should see failure and no failure.
---
* [N/A] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
=> Fix QuickCheck instance of PackageName to not produce 'all' (fix #8986)

cabal-testsuite/Setup.hs, changelog.d/pr-9007
Allows to run `cabal repl cabal-testsuite` out of the box. Enables HLS support for `cabal-testsuite`.
Fixes https://github.com/haskell/hie-bios/issues/404
---
=> Generate cabal-testsuite modules at configure time

Cabal-syntax/src/Language/Haskell/Extension.hs, Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs, changelog.d/pr-8992, editors/vim/syntax/cabal.vim
GHC 9.8 will feature a new extension, `ExtendedLiterals`: https://github.com/ghc/ghc/commit/931c8d82f28fb98a7e0ad0a837eff05c08021cbe.
I am adding it to Cabal following [Note [Adding a language extension]](https://github.com/ghc/ghc/blob/00a1e50b65354f65f508408d171ec1af4045dd95/compiler/GHC/Driver/Session.hs#L345) in GHC.
A comment says that I should update `languageExtensions` which I believe is now `compilerExtensions`. As far as I can tell there's nothing to change, since supported GHC flags are fetched rather than hardcoded.
---
=> Add the ExtendedLiterals extension

Cabal/src/Distribution/PackageDescription/Check.hs, cabal-testsuite/PackageTests/Check/NonConfCheck/PackageVersionsNoCheck/cabal.out, cabal-testsuite/PackageTests/Check/NonConfCheck/PackageVersionsNoCheck/cabal.test.hs, cabal-testsuite/PackageTests/Check/NonConfCheck/PackageVersionsNoCheck/pkg.cabal, changelog.d/pr-9004
Internal targets: test-suites or benchmarks.
See #8361 for rationale.
Note that this patch is quite ugly (duplicating allBuildInfo, using list comprehensions, etc.) but we don’t care as everything will be overwritten by a much more sensible reimplementation in #8427.
---
---
1. fetch any cabal package with a test-suite, say `cabal get lentil`
2. `cd` into it
3. in the `build-depends` section of the `test-suite` stanza, add an unbounded dependency
4. run `cabal check`, it should *not* complain about missing upper bounds
=> Do not check PVP on internal targets

Cabal-syntax/src/Distribution/System.hs, Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs, Cabal/src/Distribution/Simple/GHC.hs, Cabal/src/Distribution/Simple/GHCJS.hs, Cabal/src/Distribution/Simple/InstallDirs.hs, Cabal/src/Distribution/Simple/PreProcess.hs, changelog.d/pr-9006
=> haiku: add as known platform

README.md
=> Show how to install cabal-head via GHCup

Cabal/src/Distribution/PackageDescription/Check.hs, cabal-install/cabal-install.cabal, cabal-install/tests/UnitTests/Distribution/Client/ArbitraryInstances.hs, cabal-testsuite/PackageTests/Check/NonConfCheck/PackageVersionsNoCheck/cabal.out, cabal-testsuite/PackageTests/Check/NonConfCheck/PackageVersionsNoCheck/cabal.test.hs, cabal-testsuite/PackageTests/Check/NonConfCheck/PackageVersionsNoCheck/pkg.cabal, changelog.d/pr-9004
backport
Internal targets: test-suites or benchmarks.
See #8361 for rationale.
Note that this patch is quite ugly (duplicating allBuildInfo, using list comprehensions, etc.) but we don’t care as everything will be overwritten by a much more sensible reimplementation in #8427.
---
=> Do not check PVP on internal targets (backport of #9004 to 3.10)

cabal-install/src/Distribution/Client/Setup.hs, cabal-install/src/Distribution/Deprecated/ParseUtils.hs, cabal-testsuite/PackageTests/UserConfig/cabal.out, cabal-testsuite/PackageTests/UserConfig/cabal.test.hs, changelog.d/issue-6268, doc/cabal-commands.rst
The password-command option does not parse its value correctly.
Quotes are ignored, making many kinds of commands impossible to
express (e.g.  `sh -c "foo | bar"`).  Also, `cabal user-config`
treats the argument list as a *list of option values*, rather than a
*value that is a list*.  As a consequence, `cabal user-config
update` corrupts the value in the config file.
Fix these issues by parsing the command as a space separated list of
tokens, and changing the getter to `unwords` the value and return a
*singleton* list.  Also update the argument placeholder from
`PASSWORD` to `COMMAND`.
Fixes: https://github.com/haskell/cabal/issues/6268
- Please, [see the original bugreport](https://github.com/haskell/cabal/issues/6268#issue-500778440) that contains a short and sweet reproducer.
--- …
=> Fix parsing of password-command option (#6268)

doc/cabal-package.rst
The docs make it sound like sublibraries definitely aren't supported, and then go on to explain how to use them. I tried to catch all the cases where that happened.
I've added a couple FIXMEs about things I'm not sure about!
---
* [NA] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [NA] Include [manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) if your PR relates to cabal-install.
=> Documentation cleanup around sublibraries

cabal-install/tests/IntegrationTests2.hs
---
To fix a problem with [this pr](https://github.com/haskell/cabal/pull/8955) I sent the whole file contents of the default config (whatever that is based on the current build) to the error output so that I could see what needed to be fixed. This will probably be useful whenever the test breaks again, so I'm making a PR for it from @Mikolaj 's comment.
=> Show full config file contents when option test fails

Cabal/Cabal.cabal, Cabal/src/Distribution/Utils/TempTestDir.hs, cabal-install/cabal-install.cabal, cabal-install/tests/UnitTests/Distribution/Client/FetchUtils.hs, cabal-install/tests/UnitTests/Distribution/Client/Get.hs, cabal-install/tests/UnitTests/Distribution/Client/VCS.hs, cabal-testsuite/src/Test/Cabal/Monad.hs, cabal-testsuite/src/Test/Cabal/Prelude.hs
This is supposedly more robust on Windows than removeDirectoryRecursive.
---
* [NA] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [NA] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [NA] The documentation has been updated, if necessary.
* [NA] Include [manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) if your PR relates to cabal-install.
=> testsuite: use removeDirectoryRecursiveHack to cleanup

CONTRIBUTING.md, Cabal-syntax/src/Distribution/Fields/Lexer.hs, Cabal-syntax/src/Distribution/Fields/LexerMonad.hs, Cabal-syntax/src/Distribution/Fields/Parser.hs, Cabal-syntax/src/Distribution/Parsec/Warning.hs, Cabal-tests/tests/CheckTests.hs, Cabal-tests/tests/ParserTests/regressions/decreasing-indentation.cabal, Cabal-tests/tests/ParserTests/regressions/decreasing-indentation.check, Makefile, cabal-testsuite/PackageTests/Check/NonConfCheck/DuplicatedModules/pkg.cabal, cabal.project, changelog.d/inconsistent-indentation, templates/Lexer.x
#8975, #8981 and #8983, cherry picked. 
---
=> #8975, #8981, #8983 rebased

doc/cabal-commands.rst
As discussed in https://github.com/haskell/cabal/issues/9009
=> Document the pkg: prefix for package targets

cabal-install/src/Distribution/Client/IndexUtils.hs
The sandbox functionality was removed a while ago. This is one of the few left overs. In this PR, I have first removed the `SandboxIndex` constructor from `Index` and then removed the `Index` type entirely by inlining the two fields of its remaining constructor `RepoIndex`.
=> Remove SandboxIndex

Cabal/src/Distribution/PackageDescription/Check.hs
The `OSHaiku` identifier has been merged in #9006, for a future 3.12 release. However, tools that rely on earlier versions of cabal -- such as hackage -- don't recognise "haiku" as a valid OS identifier.
This allows packages with `os(haiku)` present to pass CI and be uploaded to hackage until hackage can eventually be upgraded to use cabal 3.12.
---
=> check: allow "haiku" as a valid OS string.

Cabal/src/Distribution/Simple/Haddock.hs, changelog.d/pr-9049
6d8adf13101c4d28fef14bdec55d485feec356fd caused cabal to always pass the `--quickjump` flag to haddock. This commit fixes it by requiring that the result of `flagToList` on `argQuickJump` is `True`, instead of anything.
=> Do not always pass `--quickjump` to haddock

Cabal-syntax/src/Distribution/Compat/Prelude.hs
=> Avoid dodgy Rep (..) import in Cabal-syntax

cabal-install/src/Distribution/Client/Config.hs, changelog.d/pr-9068
Hackage Security has gotten two new root keyholders. This PR adds them to the bootstrap set. They're not in the currently-deployed root.json, but I'm in the process of getting that file ready to go (this is part of that process).
The correctness of this PR can be checked against https://github.com/haskell-infra/hackage-root-keys/tree/master/root-keys.
See #8669 for a prior MR in this series. The final comment in that thread mentions getting new root keyholders - this is the realization of that.
---
=> Add new root keys

README.md
The old link to the portaled room will soon become unavailable as per https://libera.chat/news/matrix-deportalling
=> README: update Matrix chat link

Cabal-syntax/Cabal-syntax.cabal, Cabal/Cabal.cabal
Bumps bounds of `Cabal` and `Cabal-syntax` for  GHC 9.8.
=> Bump deepseq bounds to allow 1.5

doc/nix-local-build.rst
Closes https://github.com/haskell/cabal/issues/9086
---
*Seems irrelevant for a documentation PR*
*[Deemed unnecessary](https://github.com/haskell/cabal/pull/9087#issuecomment-1622152060)*
*It* is *the documentation*
*It doesn't*
*Bonus points forgone*
=> Remove v2-prefix from Quickstart guide

.github/ISSUE_TEMPLATE/bug_report.md, CONTRIBUTING.md, Makefile, bootstrap/bootstrap.py, cabal-dev-scripts/src/GenCabalInstallCabal.hs, cabal-dev-scripts/src/GenCabalMacros.hs, cabal-dev-scripts/src/GenPathsModule.hs, cabal-dev-scripts/src/GenValidateDockerfile.hs, solver-benchmarks/HackageBenchmark.hs, validate.sh
Note: I'm aware of @tomjaguarpaw 's PR [here](https://github.com/haskell/cabal/pull/9087) and intend to rebase once that lands as not to duplicate their efforts. 
The general approach I took here was to search for any file that mentioned "v2-" that wasn't a test file and remove the prefix if:
- it appeared to be a recommendation for what command to run
- didn't appear to be commenting on the aliased commands
Happy to consider any cases that I've missed or revert anything that does what we don't want. My goal at the end of this is to not have cabal mention `v2` _anywhere_ it's not appropriate, whether that's in command line output, documentation, or otherwise. I'm happy to update tests if that's what's required. 
I intend to complete this work (and thus properly fill out the checkbox …
=> Remove v2-prefix from other documentation where appropriate

bootstrap/README.md
---
* [N/A] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [N/A] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).
* [N/A] Include [manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) if your PR relates to cabal-install.
=> facelift bootstrap/README.md

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/user_question.md, .github/PULL_REQUEST_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE/full_pr.md, .github/PULL_REQUEST_TEMPLATE/simple_pr.md
Closes #8511.
Adds “Feature Request”, “Documentation” and “Question” issue templates.
Splits PR template in two (simple and full one), adding PR Convetion link to both.
---
~~Bonus points for added automated tests!~~ N/A
=> Revamp issue/PR templates

README.md
Manual and venues where to (h)ask questions.
---
~~Bonus points for added automated tests!~~ N/A
=> Add user-oriented resources in README.md

.github/pull_request_template.md
Labels are not supported in PR templates, see
https://github.com/orgs/community/discussions/12815
=> Remove labels from template PR

Cabal-syntax/src/Distribution/Types/VersionInterval.hs, changelog.d/pr-9034
I tried updating my program cabal-bounds[1] to the newest cabal version, but wasn't able anymore to create a 'VersionIntervals' from a '[VersionInterval]'.
This patch adds back the 'mkVersionIntervals' function.
[1] https://github.com/dan-t/cabal-bounds
---
* [ X] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
=> Add 'mkVersionIntervals' for creating a VersionIntervals from a list

Cabal/src/Distribution/GetOpt.hs, Cabal/src/Distribution/Simple/Command.hs, Cabal/src/Distribution/Simple/Setup/Common.hs, Cabal/src/Distribution/Simple/Setup/Config.hs, cabal-install/src/Distribution/Client/CmdOutdated.hs, cabal-install/src/Distribution/Client/Setup.hs, changelog.d/issue-8785, doc/cabal-commands.rst, doc/cabal-project.rst, doc/setup-commands.rst
See #8785.
I'm not sure a changelog entry is needed but code snippets of the command `--help` output may need to be updated in the docs.
```diff
<  -v, --verbose[=n]              Control verbosity (n is 0--3, default
>  -v[n], --verbose[=n]           Control verbosity (n is 0--3, default
<  -w, --with-compiler=PATH       give the path to a particular compiler
>  -wPATH, --with-compiler=PATH   give the path to a particular compiler
<  -O, --enable-optimization[=n]  Build with optimization (n is 0--2, default is
>  -O[n], --enable-optimization[=n]
>                                 Build with optimization (n is 0--2, default is
<  -f, --flags=FLAGS              Force values for the given flags in Cabal
>  -fFLAGS, --flags=FLAGS         Force values for the given flags in Cabal
<  -c, …
```
=> Render short option with arg.

.hlint.yaml, Cabal/src/Distribution/Simple/PreProcess.hs, Cabal/src/Distribution/Simple/Program/GHC.hs
See #9110. We do nothing with these bindings in list comprehensions. I'd say we're not giving up documentation value by losing these bindings:
```
opt <- ccOptions pkg
opt <- ldOptions pkg
modDefFile <- flags ghcOptLinkModDefFiles
```
=> Follow hlint suggestion: redundant list comprehension

.hlint.yaml, Cabal-syntax/src/Distribution/Fields/ParseResult.hs, Cabal-syntax/src/Distribution/Types/Mixin.hs, cabal-testsuite/src/Test/Cabal/Monad.hs
See #9110, remove dead code detected by hlint.
=> Follow hlint suggestion: redundant where (dead code)

.github/mergify.yml
If a pull request gets the "merge+no rebase" label, it' will be merged directly to master without a rebase/squash or queue. This can be useful in cases when contributors don't allow updating their branches.
=> Mergify: add no-rebase rule

cabal-install/src/Distribution/Client/Init/Interactive/Command.hs, cabal-install/tests/UnitTests/Distribution/Client/Init/Golden.hs, cabal-install/tests/UnitTests/Distribution/Client/Init/Interactive.hs, cabal-testsuite/PackageTests/Init/init-interactive-empty-folder.out, cabal-testsuite/PackageTests/Init/init-interactive-empty-folder.test.hs, changelog.d/pr-9155
Closes #9150, blank projects need not to ask permission to overwrite files.
---
---
**Q&A instructions**
1. create an empty folder, `cd` into it
2. run `cabal init -i`,
3. with old cabal, you will see this string as second question `Do you wish to overwrite existing files (backups will be created) (y/n)? [default: n]`.
4. with new cabal, you will not see the question (since it is useless, as we are in an empty folder).
=> Do not ask overwrite questions for empty dirs

Cabal/src/Distribution/Simple/GHC.hs, Cabal/src/Distribution/Simple/GHCJS.hs
Maybe 7 years ago it was relevant but it seems today it is not needed anymore.
This workaround was not needed in my tests and I found [some evidence](https://stackoverflow.com/questions/23006930/the-shared-library-rpath-and-the-binary-rpath-priority/52647116) it was not needed 10 years ago either.
This workaround prevents Cabal from building complete standalone foreign libraries on Linux, which the documentation says it is not supported but it indeed works (as long as you have a GHC bindist with -fPIC).
Let's see if the CI agrees with me :relaxed:
=> Remove RPATH workaround

doc/cabal-package.rst
=> Fix incorrect conditional block documentation

doc/cabal-package.rst
Two links in the users guide pointed to modules on Hackage which were moved from Cabal to Cabal-syntax
=> Fix two dead links in the users guide

Makefile, doc/Makefile, doc/README.md
Fixes #7977
Before this PR it is only possible to build the user guide
from the root of the repository. An invocation of "make users-guide"
in the "doc/" subdirectory fails. This commit moves the logic for
building the users-guide from the Makefile at the root of the
repository to the file "doc/Makefile".
From the root of the project only the target "users-guide"
remains, all other targets related to building the users-guide
are only available in the "doc/" subdirectory.
Note: This PR builds upon #9178 which fixes an error in the build system for the docs.
=> Make users-guide buildable from within doc/ subdirectory

cabal-install/src/Distribution/Client/Setup.hs
A default config file on Windows is not at _~/.config/cabal/config_ but _%APPDATA%\cabal\config_.
This PR adds it to command line notes.
=> Add a config path on Windows in a message

Cabal-syntax/ChangeLog.md, Cabal/ChangeLog.md, cabal-install-solver/ChangeLog.md, cabal-install/changelog, release-notes/Cabal-3.10.2.0.md, release-notes/cabal-install-3.10.2.0.md
=> Add changelogs for 3.10.2.0

Cabal/src/Distribution/Simple/Errors.hs, Cabal/src/Distribution/Simple/GHC/Internal.hs, Cabal/src/Distribution/Simple/Haddock.hs, Cabal/src/Distribution/Simple/Program/Db.hs, Cabal/src/Distribution/Simple/Program/Run.hs, Cabal/src/Distribution/Simple/Register.hs, Cabal/src/Distribution/Simple/Test.hs, Cabal/src/Distribution/Simple/Test/ExeV10.hs, Cabal/src/Distribution/Simple/Test/LibV09.hs, Cabal/src/Distribution/Simple/Utils.hs, cabal-install/src/Distribution/Client/Install.hs, cabal-testsuite/PackageTests/Check/PackageFiles/Missing/cabal.out
With this PR , the remaining Cabal Package errors are also modified to show the new error output with error codes. 
---
---
* [✅ ] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
=> Remaining Cabal Package Exceptions

cabal-install/cabal-install.cabal
`cabal check` was complaining:
```sh
$ cabal check
These warnings will likely cause trouble when distributing the package:
Warning: cabal-install.cabal:254:4: Inconsistent indentation. Indentation
jumps at lines 254
These warnings may cause trouble when distributing the package:
Warning: Please consider moving the file 'changelog' from the
'extra-source-files' section of the .cabal file to the section
'extra-doc-files'.
```
---
=> Fix inconsistent indentation

CONTRIBUTING.md
This PR does not modify the `cabal` behavior.  It only updates the `CONTRIBUTING.md` documentation with instructions on setting up a Nix developer shell. I believe this could help some newcomers get started more easily to contribute to the project.
[Rendered](https://github.com/yvan-sraka/cabal/blob/nix-devshell/CONTRIBUTING.md)
**Checklist:**
=> Update `CONTRIBUTING.md` with Nix developer shell instructions

Cabal-tests/tests/UnitTests/Distribution/Simple/Program/GHC.hs, Cabal/src/Distribution/Simple/Program/GHC.hs
From `Cabal/src/Distribution/Types/ParStrat.hs`
```
data ParStratX sem
= -- | Compile in parallel with the given number of jobs (`-jN` or `-j`).
NumJobs (Maybe Int)
...
```
However in `Cabal/src/Distribution/Simple/Program/GHC.hs` `show` is applied to the `Maybe Int` and we get errors like:
```
ghc-9.9.20230901: on the commandline: malformed integer argument in -jJust 4
```
This change should correct the behavior in `Simple/Program/GHC.hs` to match the comment in `Types/ParStrat.hs`.
=> Fix use of NumJobs

cabal-install/src/Distribution/Client/Nix.hs, cabal-install/src/Distribution/Client/Setup.hs, doc/nix-integration.rst
This PR modifies `cabal` behavior by adding deprecation warnings to [Nix integration](https://cabal.readthedocs.io/en/latest/nix-integration.html).
This has been discussed [on the discourse](https://discourse.haskell.org/t/community-survey-removing-cabals-nix-integration/). 
**Checklist:**
**QA Notes:**
- Calling `cabal --help` should display the `[DEPRECATED]` label next to each Nix integration-related flag in the list ;
- Using `cabal some-v1-command` with the `--enable-nix` or `--nix=True` flag should display a warning about the deprecation of the feature and provide a link to the online documentation for further information.
=> Add deprecation warnings to Nix integration

cabal-install/src/Distribution/Client/Config.hs
Otherwise
```
$ CONFIG_FILE= cabal build
Error: cabal-3.10.1.0: Config file not found:
```
looks abrupt and confusing. Now it says
```
Error: cabal: Config file name is empty
```
=> Improve error message for empty config file

.gitlab/brew.sh
When the GitLab pipeline failed because of a GitHub outage (https://gitlab.haskell.org/haskell/cabal/-/pipelines/83703/failures), one job in particular (https://gitlab.haskell.org/haskell/cabal/-/jobs/1655828) threw a useless error message. This change might help that.
=> gitlab-ci/brew.sh/curl: fail with more noise

Cabal-syntax/src/Distribution/System.hs, Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs, Cabal/src/Distribution/Simple/PreProcess.hs, changelog.d/pr-9215
LoongArch 64-bit LLVM backend support has merged into GHC since `9.6.2` by this MR: [Implement LoongArch64 LLVM backend support](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/9292)
=> Add support for LoongArch 64-bit architecture

.readthedocs.yml
See https://blog.readthedocs.com/use-build-os-config/ for details.
We are in a temporary brownout with the old config key disabled, so RTD builds will be failing for the next few hours; but the change will become permanent next month.
=> Update RTD config for build.os config change

.gitlab/brew.sh
Use the lowest common denominator features available on supported platforms.
=> gitlab-ci/brew.sh/curl: use LCD feature set

doc/cabal-commands.rst, doc/cabal-package.rst
Fixes #9216 
Documentation of various `cabal-install` commands is split between section `5.2` and section `6.2`. 
This PR was written under the assumption that the documentation of these subcommands is in the wrong place in `6.2`, which otherwise only contains documentation about the .cabal file format.
(Andreas: rendering of this PR at:)
- 5.2 commands: https://cabal--9217.org.readthedocs.build/en/9217/cabal-commands.html
- 6.2 package descriptions: https://cabal--9217.org.readthedocs.build/en/9217/cabal-package.html#package-descriptions
=> Deduplicate documentation of cabal commands

cabal-install/src/Distribution/Client/Config.hs
=> Fix overzealous warnOnTwoConfigs

Cabal-QuickCheck/src/Test/QuickCheck/Instances/Cabal.hs
=> avoid invalid filepaths on Windows

Cabal/src/Distribution/Simple/GHC.hs, cabal-testsuite/PackageTests/CSourcesSanitisation/build.out, cabal-testsuite/PackageTests/CSourcesSanitisation/repro.cabal
#9200 started filtering `.cc` files from `c-sources` and does not always issue a warning (there has to be at least one `.c` file present before it warns you it is ignoring the others).
Some packages in hackage (`double-conversion` for instance) rely on the ability to include `C++` source files in `c-sources`.  This is not ideal, but we should probably continue to support these packages.
This change will relax the filtering, so that only `.h` files are automatically excluded (with a warning).  It will also warn if other non `.c` files are present (suggesting the `cxx-sources` since C++ sources are the most likely to be used).
The bug that prevented warnings being displayed when no `.c` files were present is fixed.
=> Relax extension `.c` requirement for c-sources

cabal-testsuite/README.md
Cosmetic changes in developer docs:
- caption "doctests" was too large
- use tt font for commands
=> README of testsuite: fix formatting in `doctest` section

cabal-install/src/Distribution/Client/Configure.hs, cabal-install/src/Distribution/Client/Dependency.hs, cabal-install/src/Distribution/Client/Fetch.hs, cabal-install/src/Distribution/Client/Freeze.hs, cabal-install/src/Distribution/Client/Install.hs, cabal-install/src/Distribution/Client/ProjectPlanning.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL.hs
This PR does not modify `cabal` behaviour (refactoring). Its purpose is too split https://github.com/haskell/cabal/pull/9206 into two!
=> Removing `chooseSolver` and inline `Modular` solver as default choice

Cabal/src/Distribution/Simple/Program/Builtin.hs, cabal-install-solver/src/Distribution/Solver/Types/PkgConfigDb.hs, changelog.d/pkgconfig-envvars, changelog.d/pkgconfig-once
MinGW's pkg-config returns only one version even if queried for multiple libraries. This PR makes it so that cabal will invoke pkg-config once for each requested library if the result is not of the expected length, therefore supporting these pkg-config implementations, in particular `mingw-w64-x86_64-pkgconf` (which is also installed by GHCup when bootstrapping MSYS2).
```
Javier@DESKTOP-JDT20GG MINGW64 ~
$ pkg-config --modversion libcrypto libffi
3.1.1
```
In the same spirit as https://github.com/rust-lang/pkg-config-rs/issues/92, as we also are not GCC, we also set `PKG_CONFIG_ALLOW_SYSTEM_(CFLAGS|LIBS)` when calling `pkg-config`
Building a package that depends on more than one library provided by `pkg-config` on MinGW should now be able to find the required library.
=> Try each pkg-config query separatedly

Cabal/src/Distribution/Simple/Setup/Install.hs
The original text had missing spaces.
=> Fix `installCommand` description typo

Cabal/src/Distribution/Simple/Haddock.hs
The logic of this change is simple: if the existing condition for the use of Haddock's `--hyperlinked-source` flag is met, don't also include the existing logic for the use of Haddock's `--source-*` options.
=> Fix #9318 Avoid Haddock warning with `haddock --for-hackage`

doc/requirements.in, doc/requirements.txt
As reported by dependabot. Closes #9305.
=> Upgrade urllib3 due to CVE-2023-43804

doc/cabal-project.rst
I saw that flags referenced constraints but not vice-versa in the docs so I added the back reference.
=> Add back reference from constraints to flags

doc/getting-started.rst
edit: I should wait with creating a PR until it is ready for review^^.
=> Restructure Getting Started documentation to be more compact and beginner friendly

cabal-install/src/Distribution/Client/CmdClean.hs
Reduce duplication of project flag handling, fixes #6816 
The nearly identical PR for #7439 was used as a guide for this PR.
---
=> Use ProjectFlags to define CleanCmd

doc/cabal-package.rst, doc/file-format-changelog.rst, doc/setup-commands.rst
Substitute “internal library” occourrences with “sublibrary”.
Note that:
- I did not touch `hcar` documentation files, as they are versioned by date.
- I did update `file-format-changelog.rst` as it was appropriate.
---
=> Make “sublibrary” standard terminology in docs

cabal-testsuite/README.md
I found a typo reading the test suite readme and ended up shortening a sentence to avoid it.
=> Simplify to avoid a typo

doc/conf.py
=> doc: render math with HTML to make it selectable (fix #8453)

cabal-install/src/Distribution/Client/ProjectBuilding.hs, changelog.d/pr-9376
**This PR does not modify `cabal` behaviour**[^1]
[^1]: A double space in a message is reduced to a single space:
```diff
$ cabal run cabal-testsuite:cabal-tests -- \
--with-cabal=./dist-newstyle/build/x86_64-linux/ghc-9.2.7/cabal-install-3.11.0.0/x/cabal/build/cabal/cabal cabal-testsuite/PackageTests/LinkerOptions/NonignoredConfigs/cabal.test.hs
...
-----BEGIN CABAL OUTPUT-----
Build profile: -w ghc-9.2.7 -O1
In order, the following will be built:
- basic-0.1 (lib) (requires build)
-----END CABAL OUTPUT-----
-  Executing install plan  serially.
+  Executing install plan serially.
```
Scratch that. This PR modifies `cabal` behaviour.
=> Avoid double space in "Executing install plan ..."

.hlint.yaml
Ignore because it warns about missing MachDeps.h added in #9061.
```
$ hlint -j .
Warning: Can't find file "MachDeps.h" in directories
./cabal-testsuite/PackageTests/CmmSourcesExe/src
.
Asked for by: ./cabal-testsuite/PackageTests/CmmSourcesExe/src/Demo.hs  at line 8 col 1
No hints
```
I also sorted the `--ignore-glob` list.
=> Have hlint ignore CmmSourcesExe Demo

Cabal/src/Distribution/Make.hs, Cabal/src/Distribution/Simple.hs, Cabal/src/Distribution/Simple/Command.hs, cabal-install/src/Distribution/Client/Main.hs, cabal-install/src/Distribution/Client/SavedFlags.hs, doc/external-commands.rst, doc/index.rst
Fixes: #2349 and #7825 
This PR introduces a simple, extensible, and functional plugin system for `cabal-install`, as suggested in this [comment](https://github.com/haskell/cabal/issues/7825#issuecomment-1586166220): Plugins are standalone executables named `cabal-$COMMAND` that are available in the `PATH`. They can be invoked with `cabal $COMMAND`, and any extra command arguments are directly passed to these executables as CLI arguments. To showcase its potential, I created an example plugin, [`cabal-explain`](https://github.com/yvan-sraka/cabal-explain), which displays Haskell error codes in the terminal.
Although this approach doesn't offer additional functionality over directly calling `cabal-X` at the moment, it does lay the groundwork for a more versatile and useful plugin system. A …
=> [cabal-7825] Implement external command system

Cabal-tests/Cabal-tests.cabal, cabal-benchmarks/cabal-benchmarks.cabal, cabal-install-solver/cabal-install-solver.cabal, cabal-install/cabal-install.cabal, cabal-testsuite/cabal-testsuite.cabal, cabal.project
Bump to latest dependencies for GHC 9.8.1, closes #9368.
Update: I added a `allow-newer` for `rere` into `cabal.project` now.
~~TODO:~~
Upstream issues:
=> Bump dependencies for GHC 9.8

Cabal/src/Distribution/Simple/GHC.hs, Cabal/src/Distribution/Simple/GHCJS.hs
With ghc>=9.6 `ghc --abi-hash` initialises the plugins so it will fail
if a cabal file specifies `ghc-options: -fplugin=Foo`.
=> Revert #3639 (Don't pass -package-db and -package flags to --abi-hash)

.github/workflows/lint.yml
Only changes the lint github workflow, picking up each action from the newer organisation for these actions.
=> Use the newer haskell-actions organisation

Cabal-syntax/src/Distribution/Fields/Field.hs
While not terribly interesting semantically, having `instance Ord` allows to put things into `Set` and `Map` and also allows to derive `instance Ord` for types, containing `Field` as a record field (my motivational example was [`Config`](https://hackage.haskell.org/package/cabal-add-0.1/candidate/docs/Distribution-Client-Add.html#t:Config)).
`{-# LANGUAGE StandaloneDeriving #-}` is there just to attach `@since` annotations without requiring GHC >= 8.2 or so.
=> Add instance Ord for Field, FieldLine, SectionArg and Name

cabal-testsuite/PackageTests/LinkerOptions/NonignoredConfigs/cabal.out, cabal-testsuite/PackageTests/LinkerOptions/NonignoredConfigs/cabal.test.hs
Adds a test of `--force-reinstalls`.
I found no reinstall tests for #9268 but I did find a `LinkerOptions/NonignoredConfigs` test where I could add a reinstall test. Unfortunately this doesn't touch the code path of #9268 with its `Use --overwrite-policy=always to overwrite` message. The message is instead:
> Packages requested to install already exist in environment file at ... Overwriting them may break other packages. Use --force-reinstalls to proceed anyway.
=> Add reinstall test to LinkerOptions/NonignoredConfigs

.gitignore, cabal-install/src/Distribution/Client/CmdUpdate.hs, cabal-install/src/Distribution/Client/Errors.hs, cabal-install/src/Distribution/Client/IndexUtils.hs, cabal-install/src/Distribution/Client/IndexUtils/Timestamp.hs, cabal-install/tests/UnitTests/Distribution/Client/ArbitraryInstances.hs, cabal-install/tests/UnitTests/Distribution/Client/IndexUtils/Timestamp.hs, cabal-testsuite/PackageTests/Get/OnlyDescription/cabal.test.hs, cabal-testsuite/PackageTests/Get/T7248/cabal.out, cabal-testsuite/PackageTests/NewUpdate/RejectFutureIndexStates/cabal.out.in, cabal-testsuite/PackageTests/NewUpdate/RejectFutureIndexStates/cabal.project, cabal-testsuite/PackageTests/NewUpdate/RejectFutureIndexStates/cabal.test.hs, cabal-testsuite/PackageTests/NewUpdate/RejectFutureIndexStates/fake-pkg/Main.hs, cabal-testsuite/PackageTests/NewUpdate/RejectFutureIndexStates/fake-pkg/fake-pkg.cabal, cabal-testsuite/PackageTests/NewUpdate/RejectFutureIndexStates/repo/pkg-1.0/Foo.hs, cabal-testsuite/PackageTests/NewUpdate/RejectFutureIndexStates/repo/pkg-1.0/pkg.cabal, changelog.d/die-on-missing-pkg-list, changelog.d/index-state-cabal-update
The `index-state` warning expresses an internal mismatch in the existing index-states and the requested one, but this does not need an action from the user. On the other hand, requesting an index-state after the last known index means that the user should perform `cabal update`. This PR demotes the first one to verbose mode only and throws an error on the second one.
When building a project with a timestamp for which no index-state exists, cabal now warns the user and picks the previous index-state.
The index-state warning that said:
```
Warning: Requested index-state 2023-04-24T00:00:09Z is newer than
'hackage.haskell.org'! Falling back to older state (2023-04-23T19:32:13Z).
```
1. Setting the index-state in-between two existing index-states warns in verbose mode
```
❯ cabal build all -v …
```
=> Reject index-states after last known index-state

doc/cabal-package-description-file.rst
This is a doc change only, adding a note on how to do "not equal" with constraints when we do not have that operator.
=> Note how to do "not equal" with constraints

cabal-install/src/Distribution/Client/ProjectPlanning.hs
=> Require version 3,11 of Cabal to support --semaphore flag

cabal-testsuite/cabal-testsuite.cabal
The runner allows the tests to use extra dependencies and the custom Prelude from 'exe:cabal-tests'.
However, if the tests use a dependency, say 'directory', and there are two packages with the same unit id available in the store, the test fails since it doesn't know which one to pick.
By including an extra dependency to directory, we force the test runner to use a specific version directory, fixing the test failure.
POC fix for #8356 
---
=> Add dependencies used by `PackageTests` to exe:cabal-tests

doc/setup-commands.rst
https://github.com/haskell/cabal/issues/9182 pointed out that there is some missing documentation.
=> Document --profiling-detail in setup-commands.

.github/pull_request_template.md
Adding test becomes a checkmark instead of “bonus points”.
---
=> Add test requirement to PR template

.github/workflows/validate.yml, cabal-testsuite/PackageTests/CCompilerOverride/custom-cc-clang.bat, cabal-testsuite/PackageTests/CCompilerOverride/setup.test.hs, cabal-testsuite/PackageTests/ForeignLibs/setup.test.hs
Here for testing whether these tests are still failing and hopefully debugging.
=> CI: Attempt to enable tests for 9.6.3 windows

cabal-testsuite/README.md, cabal-testsuite/Setup.hs, cabal-testsuite/cabal-testsuite.cabal, cabal-testsuite/src/Test/Cabal/Script.hs, cabal-testsuite/static/Main.hs
Issue #8356 reports occasional errors from running the testsuite about multiple package versions available. This stems from the invokation of `runghc` not being explicit about all dependencies of the testsuite.
The solution is provide a component in the cabal file which is explicit about which packages the tests can depend on. This component has a build-depends section which lists all the dependencies that the tests require.
It would be better if this component was a library component but we can't do this with a Custom setup because of limitations to do with per-component builds.
Then we also enable `-hide-all-packages`, so the dependency will not be available if it is not explicitly listed as a dependency.
You could also imagine a future where the Setup.hs script found the test files and …
=> testsuite: Be explicit about runtime test dependencies

Cabal/src/Distribution/Simple/GHC.hs, Cabal/src/Distribution/Simple/GHCJS.hs, changelog.d/pr-9441
GNU/Hurd fully supports RPATH and the $ORIGIN development, and we indeed want to use it for relocatable installations shipped in Debian GNU/Hurd.
* [N/A] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
=> hurd: Enable using $ORIGIN in RPATH

Cabal/src/Distribution/Simple/GHC/Internal.hs, changelog.d/pr-9434
Since version 9.4.7-1, ghc fails to build on the GNU/Hurd port of Debian, see
https://buildd.debian.org/status/fetch.php?pkg=ghc&arch=hurd-i386&ver=9.4.7-1&stamp=1697717885&raw=0
```
Error, rule finished running but did not produce file:
_build/stage0/lib/i386-gnu-ghc-9.4.6/ghc-boot-th-9.4.7/libHSghc-boot-th-9.4.7.a
```
and indeed, what did get produce was rather
`_build/stage0/lib/i386-hurd-ghc-9.4.6/ghc-boot-th-9.4.7/libHSghc-boot-th-9.4.7.a` (`i386-hurd` instead of `i386-gnu`).
This is due to confusion between hurd and gnu in various places.  Apparently previous versions of ghc were using gnu for the GNU/Hurd port, and thus putting libraries etc. in i386-gnu. So we have to follow the existing practice.
=> Fix the platform string for GNU/Hurd

Cabal/src/Distribution/Simple/Configure.hs, Cabal/src/Distribution/Simple/GHC/Internal.hs, Cabal/src/Distribution/Simple/Program/Builtin.hs, Cabal/src/Distribution/Simple/Program/Db.hs, changelog.d/pr-9443
Cabal currently adds the `-r` (relocatable) flag to some invocations of `ldProgram`, but `lld` (commonly used on WIndows) does not understand the `-r` flag. This PR just detects if `ldProgram` accepts `-r` during the `configure` step.
Hopefully this far simpler implementation will replace https://github.com/haskell/cabal/pull/9270
=> Use linker capability detection to improve linker use

Cabal-syntax/src/Distribution/System.hs, Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs, Cabal/src/Distribution/Simple/PreProcess.hs, changelog.d/pr-9445
Previously, sparc64 was defined as an alias for the 32-bit SPARC architecture which was true while SPARC mainland was mostly 32 bits. More recently, 64-bit SPARC has become a port of its own, so it needs to be treated as a separate architecture.
=> Add support for 64-bit SPARC as a separate architecture

bootstrap/linux-8.10.7.json, bootstrap/linux-9.0.2.json, bootstrap/linux-9.2.7.json, bootstrap/linux-9.4.4.json, cabal-install-solver/cabal-install-solver.cabal, cabal-install-solver/src/Distribution/Solver/Modular/ConflictSet.hs, cabal-install-solver/src/Distribution/Solver/Modular/Validate.hs
Fixes #8937.
The debug-conflict-sets build flag probably hasn't been used for a long time, and it isn't currently tested. This commit removes the flag, converts the ConflictSet type back to a newtype, and removes an unnecessary instance.
---
=> Remove debug-conflict-sets flag from solver package

.github/workflows/bootstrap.skip.yml, .github/workflows/bootstrap.yml, .github/workflows/validate.skip.yml, .github/workflows/validate.yml, CONTRIBUTING.md
The previous PR was #9355 which reconfigured the validate jobs to not run on documentation changes. This PR finishes the job with the following improvements:
- Previously we only considered changes to `docs/` as documentation changes. We now also recognize changes to  `README.md` and `CONTRIBUTING.md`.
- There is now a "Bootstrap post job" which succeeds if, and only if, all of the bootstrap jobs succeed. This is just copy-pasted from the validate.yml file which also uses this configuration to simplify the configuration of the GitHub repo.
- Documentation changes now also skip the bootstrap jobs.
- I added a small comment to CONTRIBUTING.md mentioning the improvements to the CI.
**VERY IMPORTANT:** This only works properly if we also change the configuration of the repository (which I …
=> Finish improvements to the CI configuration for documentation changes

CONTRIBUTING.md, Makefile
This target allows you to format a range of commits, for example:
```
make style-commit COMMIT=HEAD~1
> Last commit is formatted
make style-commit COMMIT=abcde
> Commits between HEAD and abcde are formatted
```
=> formatting: Add style-commit makefile target

cabal-install-solver/src/Distribution/Solver/Types/PkgConfigDb.hs, changelog.d/pr-9391
Check that the numbers of *versions* output is equal to the number of pkgconf's
fixes #8923
Noting that the pkgconf behavior was since reverted upstream in 2.0.
(checking that equal pkgnames are output also doesn't hurt per se, but that should be trivially true and this should cover that case too anyway)
---
**This PR modifies `cabal` behaviour**
---
A simple testcase is building [libarchive](https://hackage.haskell.org/package/libarchive) with `cabal build -f system-libarchive` and pkgconf-1.9 on Linux (eg with Fedora Linux 39)* -  though *any* package using `pkgconfig-depends` will do.
See also the original issue for more details.
(* which is how I ran into this again while trying to update ghcup version from source)
=> cabal-install-solver: fix pkgconf 1.9 --modversion regression

cabal-install/cabal-install.cabal, cabal-install/src/Distribution/Client/HashValue.hs, cabal-install/src/Distribution/Client/ScriptUtils.hs, cabal-testsuite/cabal-testsuite.cabal, cabal-testsuite/src/Test/Cabal/Prelude.hs, changelog.d/base16-script-cache
Issue #9334 shows that `%` characters on Windows result in invalid paths, also `/` characters on Linux create invalid paths.
This changes from using base64 to using base16 with the same length we use for unit-ids.
This supersedes #9452 or rather makes it not needed.
Building scripts will now use base16 hashes. So doing `cabal run <script> --verbose` should output something like the following:
```
$ cabal run --verbose ./main.hs
Warning: this is a debug build of cabal-install with assertions enabled.
Project settings changed, reconfiguring...
creating C:\msys64\tmp\cabal-repl.-9560\dist-newstyle
creating C:\msys64\tmp\cabal-repl.-9560\dist-newstyle\cache
creating
C:\cabal\script-builds\4b00d58dd930cd841d1a706ed4b329caf686239fc5259400bd20
creating …
```
=> Use Base16 hash for script path.

.github/workflows/validate.yml
As of 2023-09-09, haskell/action/setup is no longer maintained.
=> Migrate to haskell-actions/setup

Cabal-tests/Cabal-tests.cabal, Cabal-tests/lib/Test/Utils/TempTestDir.hs, Cabal/Cabal.cabal, cabal-install/cabal-install.cabal, cabal-install/tests/UnitTests/Distribution/Client/FetchUtils.hs, cabal-install/tests/UnitTests/Distribution/Client/Get.hs, cabal-install/tests/UnitTests/Distribution/Client/VCS.hs, cabal-testsuite/cabal-testsuite.cabal, cabal-testsuite/src/Test/Cabal/Monad.hs, cabal-testsuite/src/Test/Cabal/Prelude.hs, changelog.d/issue-9453
I noticed that Distribution.Utils.TempTestDir was only used in the testsuite but defined in the Cabal library. Rather than expose this in the public interface of the `Cabal` library, it is cleaner to refactor it into a separate library (`Cabal-tests`) which can be used by any testsuite component.
Also, in future it gives a clearer place to put utility functions which need to be shared across the testsuite but not exposed in Cabal. Cabal-tests can also freely add dependencies (such as exceptions) which we might want to avoid adding to the Cabal library.
Fixes #9453
=> testsuite: Introduce Cabal-tests library for common testsuite functions

.github/workflows/validate.yml, Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs, Cabal/src/Distribution/Simple/GHC.hs, cabal-dev-scripts/cabal-dev-scripts.cabal, cabal-install/src/Distribution/Client/Dependency.hs, cabal-install/src/Distribution/Client/Init/NonInteractive/Command.hs, cabal-install/src/Distribution/Client/Init/NonInteractive/Heuristics.hs, cabal-install/src/Distribution/Client/InstallPlan.hs, cabal-install/src/Distribution/Client/Upload.hs, cabal-install/tests/IntegrationTests2.hs, cabal-install/tests/UnitTests/Distribution/Client/FileMonitor.hs, cabal-install/tests/UnitTests/Distribution/Client/InstallPlan.hs, cabal-install/tests/UnitTests/Distribution/Client/Targets.hs, cabal-testsuite/src/Test/Cabal/Prelude.hs, cabal.project, cabal.project.latest-ghc, cabal.project.validate
=> GHC 9.8 compat and CI

cabal-install/src/Distribution/Client/Init/FileCreators.hs, cabal-install/src/Distribution/Client/Init/Types.hs, cabal-install/src/Distribution/Client/Init/Utils.hs, changelog.d/pr-9346
The actual ADT for severity should change because "Log" is useless as a datatype, arguably it shouldn't even be an entry in the ADT and the severity should be at `Info` for everything that's not a `Warn`.
when calling `cabal init` the user sees log entries categorized as Info, while entries categorized as Log should not appear.
=> Fix #9151 (cabal init logs at loglevel "Log")

Cabal/src/Distribution/PackageDescription/Check.hs, cabal-testsuite/PackageTests/Check/ConfiguredPackage/Fields/KnownTypeAbstractions/cabal.out, cabal-testsuite/PackageTests/Check/ConfiguredPackage/Fields/KnownTypeAbstractions/cabal.test.hs, cabal-testsuite/PackageTests/Check/ConfiguredPackage/Fields/KnownTypeAbstractions/pkg.cabal, changelog.d/pr-9503, editors/vim/syntax/cabal.vim
See #9496, backport of #9502.
---
**QA notes**
- create a new package
- put `TypeAbstractions` in `default-extensions`
- run `cabal check`
- it should not complain about “Uknown extensions”.
=> Make `check` recognise `TypeAbstractions`

cabal-install/cabal-install.cabal, cabal-install/src/Distribution/Client/ProjectPlanning.hs, cabal-install/src/Distribution/Client/ProjectPlanning/SetupPolicy.hs
ProjectPlanning is a big module, counting more than 4k lines.
This change separates the code related to the setup policy to its own module.
---
=> Separate setup policy from the rest of project planning

Cabal-syntax/src/Language/Haskell/Extension.hs, Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs, changelog.d/pr-9502, editors/vim/syntax/cabal.vim
Towards #9496.
If needed, the correct `cabal check` behaviour can be backported to 3.10 *without* adding `| TypeAbstractions` constructor (a breaking change).
---
**QA Notes**
1. `mkdir prova && cd prova`
2. `cabal init -nm`
3. add a `default-extensions: TypeAbstractions` in the executable stanza
4. `cabal check` should *not* complain with `unknown-extension` (compare with 3.10 where it does)
=> Add `TypeAbstractions` extension

Cabal/src/Distribution/Simple/Build.hs
This is a pure refactor that reduces code duplication, with the exception that it also fixes a bug in that `preprocessExtras` was not being called for foreign libraries in both functions.
=> Refactor buildComponent and replComponent

doc/cabal-package-description-file.rst, doc/cabal-project-description-file.rst
=> Warn about project conditional blocks

doc/cabal-package-description-file.rst
The existing material in the Cabal Users Guide on library components is written up as incremental 'developments' on top of the 'history'. This reworking aims to recast the existing material to describe the current state of affairs.
It also aims to eliminate duplication and be consistent in the terminology used, as follows: a library component can be the 'main' unnamed library or a named library (which can be referred to as a 'sublibrary'). A sublibrary can be 'public' or 'private'. A private sublibrary can be referred to as an 'internal' library.
It moves `pkg-field:: visibility: visibility specifiers` to the top of the discussion of `library` section fields, as whether a library component is 'public' or 'private' is a fundamental characteristic of the component.
It also clears the …
=> Rework material on library components in Cabal Users Guide

.gitignore, scripts/release/create-release-metadata-for-ghcup.sh, scripts/release/download-cabal-install-release-binaries.sh
Draft PR for feedback and suggestion for issue #9298 
Currently, on a cabal release, for it to be released by GHCup, the metadata of the release required by GHCup is manually generated. The process seems quite arduous and is an overhead for a release manager.
This PR intends to introduce a script that would help make cabal releases easier and more streamlined by automatically generating the required cabal release metadata in the correct format that is usable by GHCup as-is. It then essentially becomes a simpler affair for the release manager to introduce the new release in GHCup.
The [link](url) in the issue 9298 thread was used as a reference for this script.
The basic core functionality of the script works, as in, if you give it a release number as it's first and only argument, it …
=> [Rel-Eng]: Adds script to automatically generate GHCup metadata for Cabal releases

doc/cabal-package-description-file.rst
=> Fix #9548 Improve accuracy of docs for condition `arch(name)`

Cabal-tests/tests/UnitTests/Distribution/SPDX.hs, Cabal-tests/tests/UnitTests/Distribution/Simple/Program/GHC.hs
Satisfy the build with this (uncommited) change:
```diff
git diff
diff --git a/cabal.project b/cabal.project
index d0b2fbabc..c0695f378 100644
--- a/cabal.project
+++ b/cabal.project
@@ -20,4 +20,4 @@ constraints: rere -rere-cfg
constraints: these -assoc
program-options
-  ghc-options: -fno-ignore-asserts
+  ghc-options: -fno-ignore-asserts -Werror=unused-top-binds
```
We can pick up the deleted top binds of `Cabal-tests/tests/UnitTests/Distribution/Simple/Program/GHC.hs` in #9435.
=> Satisfy `-Werror=unused-top-binds`

.github/workflows/quick-jobs.yml, Cabal-described/src/Distribution/Described.hs, Makefile, buildinfo-reference-generator/buildinfo-reference-generator.cabal, buildinfo-reference-generator/template.zinza, cabal.project.buildinfo, doc/buildinfo-fields-reference.rst
Helps with #9186. Revives the `buildinfo-reference-generator` package, replaces a `PHONY` target with `doc/buildinfo-fields-reference.rst` as the target in the Makefile and updates a field reference. Includes the output generated by the Makefile recipe, `doc/buildinfo-fields-reference.rst`.
To test:
```
$ make doc/buildinfo-fields-reference.rst --always-make
```
=> Generate doc/buildinfo-fields-reference.rst

Cabal-described/src/Distribution/Described.hs, Cabal-syntax/src/Language/Haskell/Extension.hs
Helps with #9186. Follow up on #9573. Update `knownLanguages` haddocks to mention sort order. Uses `knownLanguages` for describing the grammar of `Language`.
To test:
```
$ make doc/buildinfo-fields-reference.rst --always-make
```
=> Use knownLanguages for describing Language

changelog.d/pr-9464
Additionally, a Manual QA note for the same ticket:
Running `cabal test cabal-install --enable-coverage` in the root of the cabal project should succeed and generate a coverage report for `cabal-install`.
---
@fgaz I've addressed your comment from #9464. I think all the relevant documentation has already been added but correct me if I'm wrong.
=> Update changelog for per-component with coverage #9464

cabal-testsuite/PackageTests/NewUpdate/RejectFutureIndexStates/cabal.test.hs, cabal-testsuite/PackageTests/NewUpdate/UpdateIndexState/update-index-state.test.hs
Tracking ticket https://github.com/haskell/cabal/issues/9530
---
=> Disable flaky index-state related tests, which often fail to `curl`

Cabal-tests/Cabal-tests.cabal, cabal-install/cabal-install.cabal, cabal-install/src/Distribution/Client/Compat/Tar.hs, cabal-install/src/Distribution/Client/Tar.hs, cabal-install/tests/UnitTests/Distribution/Client/Tar.hs
=> Relax `tar` upper bound

validate.sh
See https://www.shellcheck.net/wiki/SC2028
=> Use printf in validate.sh for proper coloring

.github/workflows/validate.yml, CONTRIBUTING.md
The GitHub workflo defined here can be started manually to check that certain version bumps build fine. It will ask to input an allow-newer line and a constraint line, which it will add to the `cabal.project` file. For example: the "filepath" allow-newer line and "filepath == 1.5" constraints line will make sure that the build plan will have `filepath` at version 1.5.
Unfortunately, it's almost an exact copy of validate.yml and has to be maintained in concert with it.
/cc @Mikolaj who pushed the revisions policy, see https://github.com/haskell/cabal/issues/9531#issuecomment-1866930240
---
=> Add validate-revision workflow

cabal-install/src/Distribution/Client/CmdRepl.hs, cabal-testsuite/PackageTests/MultiRepl/EnabledClosure/cabal.test.hs, cabal-testsuite/PackageTests/MultiRepl/EnabledSucc/cabal.test.hs, doc/internal/multi-repl.md
When using the multi components repl, the last unit given to ghc
is the active unit. This change uses the cabal repl argument
order instead of relying on the 'listDirectory' ordering.
Fixes #9195 
---
=> Sort the unit order for --enable-multi-repl

cabal-dev-scripts/cabal-dev-scripts.cabal, cabal-dev-scripts/src/GenSPDX.hs, cabal-dev-scripts/src/GenSPDXExc.hs
Bumps `aeson` upper bounds so that `cabal-dev-scripts` builds with `ghc-9.8.1`. Also satisfies `-Wunused-imports` of `(<>)`.
This can be tested with:
```
$ cabal repl gen-spdx --project-file=cabal.project.meta
$ make spdx --always-make
$ cabal build all --project-file=cabal.project.meta
```
=> Build cabal-dev-scripts with ghc-9.8.1

.github/workflows/bootstrap.yml, .github/workflows/validate.yml
On MacOS, deletes the cabal XDG directories as a first step. Workaround for haskell-actions/setup#62.
=> Workaround CI for XDG directories existence

Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs, Cabal/Cabal.cabal, Cabal/src/Distribution/Backpack/Configure.hs, Cabal/src/Distribution/Simple/BuildTarget.hs, Cabal/src/Distribution/Simple/Configure.hs, Cabal/src/Distribution/Simple/LocalBuildInfo.hs, Cabal/src/Distribution/Simple/Test.hs, Cabal/src/Distribution/Simple/Test/ExeV10.hs, Cabal/src/Distribution/Types/LocalBuildConfig.hs, Cabal/src/Distribution/Types/LocalBuildInfo.hs, cabal-install/src/Distribution/Client/ProjectPlanning.hs, cabal-install/src/Distribution/Client/ProjectPlanning/Types.hs, cabal-install/src/Distribution/Client/Run.hs
The aim of these commits is to modularise `LocalBuildInfo` to better
reflect implicit invariants.
The top-level split
```haskell
data LocalBuildInfo =
NewLocalBuildInfo
{ localBuildDescr  :: LocalBuildDescr
, localBuildConfig :: LocalBuildConfig
}
```
reflects which part of a `LocalBuildInfo` are set in stone by `Cabal`
(the `LocalBuildDescr`), while `LocalBuildConfig` contains options that
can be controlled/modified by the user in some way.
The split
```haskell
data LocalBuildDescr =
LocalBuildDescr
{ packageBuildDescr :: PackageBuildDescr
, componentBuildDescr :: ComponentBuildDescr
}
```
reflects that some parts of the information determined at configuration
time resides at the package level, while other pieces of information
are pertinent to individual components.
Finally the …
=> Modularise LocalBuildInfo and configure phase

cabal-install/src/Distribution/Client/ProjectBuilding/UnpackedPackage.hs
In f70fc980dca50e7e62c5e803f56d2ef0c9fc7e18, while refactoring buildInplaceUnpackedPackage and buildAndInstallUnpackedPackage, we started logging into a file on both cases, instead of logging to a file only for buildAndInstallUnpackedPackage.
When building a package inplace, it is much more useful to be able to see the GHC invocation directly outside of a log file.
This is especially relevant for Cabal developers working inplace.
Fixes #9606
=> Stop logging to file when build inplace

Cabal/src/Distribution/Simple.hs, changelog.d/issue-9401
In `autoconfUserHooks` we were not updating the `preRepl` hook to read additional build information from /package/@.buildinfo@.
Fixes #9401
=> Account for .buildinfo in repl when build-type: Configure

Cabal-syntax/src/Distribution/Types/Executable.hs, Cabal-syntax/src/Distribution/Types/ForeignLib.hs, Cabal-syntax/src/Distribution/Types/UnqualComponentName.hs
The `Semigroup` and `Monoid` instances for `ForeignLib` were completely broken: for the `foreignLibVersionInfo` and `foreignLibVersionInfo`, we essentially had the following:
```haskell
mempty :: Maybe XYZ
mempty = Nothing
(<>) :: Maybe XYZ -> Maybe XYZ -> Maybe XYZ
_ <> b = b
```
which is obviously not a valid `Monoid`, as `Just x <> Nothing = Nothing`, violating the identity law.
The `Semigroup` instance for `Executable` was also deeply suspicious, as it combined the module paths, which makes no sense. Now we instead error if the two module paths are different (and both nonempty).
=> Fix Monoid instances for ForeignLib & Executable

cabal-benchmarks/bench/CabalBenchmarks.hs, cabal-benchmarks/cabal-benchmarks.cabal
I've recently got frustrated by long CI build times. The patch improves them by eliminating 10 transitive dependencies:
* base-compat-batteries
* binary-orphans
* cassava
* code-page
* criterion
* criterion-measurement
* Glob
* js-chart
* microstache
* Only
As an author of `tasty-bench` I'm obviously biased, so feel free to ignore this shameless act of self-promotion ;) But otherwise `criterion` and `tasty-bench` have compatible APIs; `tasty-bench` capabilities seem sufficient for Cabal purposes, but dependency footprint is much smaller.
=> Switch from criterion to tasty-bench

cabal-testsuite/PackageTests/Help/HelpPrintsConfigFile/help-prints-config-file.out, cabal-testsuite/PackageTests/Help/HelpPrintsConfigFile/help-prints-config-file.test.hs
Ensure that the last line of the help text is the name of the config file.
This invariant is used by clients such as the Haskell setup github action.
See: https://github.com/haskell-actions/setup/pull/63
=> Test that the last line `--help` is the name of the config file

bootstrap/linux-8.10.7.json, bootstrap/linux-9.0.2.json, bootstrap/linux-9.2.7.json, bootstrap/linux-9.4.4.json, cabal-install/cabal-install.cabal, cabal-install/src/Distribution/Client/ProjectBuilding/UnpackedPackage.hs, cabal-install/src/Distribution/Client/Utils.hs
A revisit of #9428. Closes #9417
Tested it on my Windows machine, seems to work both in MinGW shell and in PowerShell.
On a Windows machine, build a haskell project with haddock enabled, and run `cabal haddock --open`. The default browser should be started with the index.html page
=> Fix haddock open on windows

Cabal/src/Distribution/Simple/Configure.hs, Cabal/src/Distribution/Simple/ConfigureScript.hs, Cabal/src/Distribution/Simple/GHC.hs, Cabal/src/Distribution/Simple/GHCJS.hs, Cabal/src/Distribution/Simple/Program/Db.hs, Cabal/src/Distribution/Simple/Program/Find.hs, Cabal/src/Distribution/Simple/Program/GHC.hs, Cabal/src/Distribution/Simple/Program/Run.hs, Cabal/src/Distribution/Simple/Program/Types.hs, cabal-install/src/Distribution/Client/CmdExec.hs, cabal-install/src/Distribution/Client/CmdInstall.hs, cabal-install/src/Distribution/Client/CmdRun.hs, cabal-install/src/Distribution/Client/Config.hs, cabal-install/src/Distribution/Client/Get.hs, cabal-install/src/Distribution/Client/HttpUtils.hs, cabal-install/src/Distribution/Client/ProjectConfig.hs, cabal-install/src/Distribution/Client/ProjectOrchestration.hs, cabal-install/src/Distribution/Client/ProjectPlanning.hs, cabal-install/src/Distribution/Client/SetupWrapper.hs, cabal-install/src/Distribution/Client/VCS.hs, cabal-install/tests/UnitTests/Distribution/Client/Get.hs, cabal-install/tests/UnitTests/Distribution/Client/VCS.hs, changelog.d/pr-9341, changelog.d/propagate-extra-prog-path
Fixes #9519.
Fixes #8391.
This allows finding system executables in:
- `cabal exec` will find whatever executable
- `cabal build` when cloning `source-repository-packages` will find git
- `cabal get` if invoking git (with `-s` for example) will work
- `cabal run`'ed executable inherits the path
In particular this fixes PATH issues when running MinGW cabal in PowerShell.
Paths added are also now logged in info verbosity.
In a Windows system with MSYS2/MinGW installed, either system-wide or by ghcup.
Running the following in a PowerShell with previous cabal should fail:
```
PS C:\Users\Javier\code> cabal exec sh
Error: cabal-3.10.2.0.exe: The program 'sh' is required but it could not be
found.
```
And now it should work:
```
PS C:\Users\Javier\code> …
```
=> Fix extra-prog-path propagation in the codebase.

doc/requirements.in, doc/requirements.txt
=> update jinja2 per CVE-2024-22195

Cabal/src/Distribution/Simple/GHC.hs, cabal-install/src/Distribution/Client/CmdHaddockProject.hs, cabal-install/src/Distribution/Client/CmdInstall.hs, cabal-install/src/Distribution/Client/DistDirLayout.hs, cabal-install/src/Distribution/Client/PackageHash.hs, cabal-install/src/Distribution/Client/ProjectBuilding/UnpackedPackage.hs, cabal-install/src/Distribution/Client/ProjectPlanning.hs, cabal-install/src/Distribution/Client/Store.hs, cabal-install/tests/UnitTests/Distribution/Client/Store.hs, cabal-testsuite/src/Test/Cabal/Monad.hs, cabal-testsuite/src/Test/Cabal/OutputNormalizer.hs, changelog.d/pr-9326
* This allows the use of several API incompatible builds of the same version of GHC without corrupting the cabal store.
* This relies on the "Project Unit Id" which is available since GHC 9.8.1, older versions of GHC do not benefit from this change.
This PR is an alternative to #9325. It changes the store path from e.g. [...]store/ghc-9.8.1 to [..]store/ghc-9.8.1-f7d8.
It is a continuation of #9326 that rebases and finalizes it.
[fixes #8114]
=>  Include the GHC "Project Unit Id" in the cabal store path

Cabal-syntax/Cabal-syntax.cabal
=> Relax `containers` upper bound in `Cabal-syntax`

Cabal-syntax/Cabal-syntax.cabal
Neither of these dependencies appear to be used. I suspect that they were cargo-culted from `Cabal`.
=> Cabal-syntax: Drop dependencies on unix and Win32

cabal-install/src/Distribution/Client/ProjectBuilding/UnpackedPackage.hs, cabal-testsuite/PackageTests/Regression/T9640/CHANGELOG.md, cabal-testsuite/PackageTests/Regression/T9640/LICENSE, cabal-testsuite/PackageTests/Regression/T9640/cabal.out, cabal-testsuite/PackageTests/Regression/T9640/cabal.project, cabal-testsuite/PackageTests/Regression/T9640/cabal.test.hs, cabal-testsuite/PackageTests/Regression/T9640/depend-on-custom-with-exe.cabal, cabal-testsuite/PackageTests/Regression/T9640/repo/one-custom-0.1.0.0/CHANGELOG.md, cabal-testsuite/PackageTests/Regression/T9640/repo/one-custom-0.1.0.0/Main.hs, cabal-testsuite/PackageTests/Regression/T9640/repo/one-custom-0.1.0.0/Setup.hs, cabal-testsuite/PackageTests/Regression/T9640/repo/one-custom-0.1.0.0/cabal.project, cabal-testsuite/PackageTests/Regression/T9640/repo/one-custom-0.1.0.0/one-custom.cabal, cabal-testsuite/PackageTests/Regression/T9640/repo/one-custom-0.1.0.0/src/MyLib.hs, cabal-testsuite/PackageTests/Regression/T9640/src/MyLib.hs
The refactor in f70fc980dca50e7e62c5e803f56d2ef0c9fc7e18 solved an inconsistency in `buildAndInstallUnpackedPackage`. Namely, before the refactor, we didn't pass `hsSetupBuildArgs` to the build invocations, and afterwards we did.
The result is that build targets of (legacy) package `B`, that a package `A` depends on, are now passed to the ./Setup build invocation of package `B` (e.g. `./Setup build lib:openapi3` rather than just `./Setup build`).
This means we no longer /build always all targets of a legacy-package/ (for example, the lib, the testsuites and the executables). Instead only the required target (just the lib) will be built.
However, despite now passing the build args to `./Setup build`, we weren't passing the same arguments to the `./Setup copy` invocation. Therefore, …
=> Don't build unnecessary targets of legacy-fallback deps.

cabal-testsuite/PackageTests/CCompilerOverride/custom-cc
Not all operating systems have `/bin/bash` available, it is more portable to use `/usr/bin/env bash`
For example: https://stackoverflow.com/questions/21612980/why-is-usr-bin-env-bash-superior-to-bin-bash
---
=> testsuite: Fix hardcoded /bin/bash in custom-cc wrapper

cabal-testsuite/PackageTests/PathsModule/Executable-Relocatable/setup.test.hs, cabal-testsuite/main/cabal-tests.hs, cabal-testsuite/src/Test/Cabal/Monad.hs
I can't think of a reason why it would be desirable to expose the user's cabal store or local dist-newstyle to the test runner. In fact, this can break test output in certain situations depending on what is in your store.
Tests should run in as hemertic environment as possible and not depend on anything to do with external system configuration.
Here to test on CI if this breaks any test cases.
=> Don't inherit package database to tests

.github/workflows/validate.yml, CONTRIBUTING.md, README.md
Add a job that builds a statically linked cabal-install executable, and make it available for pre-releases.
Resolves #9631.
Feedback is appreciated! 
In particular, I'm not sure how we want to specify the GHC version we want for this job. I've used a singleton matrix but maybe something else is better.
I've chosen to use a standard alpine image and the haskell setup action rather than a pre-baked alpine image with GHC, since we need to install the latest version of cabal-install for the test suite anyway, and this keeps things similar to the other jobs.
=> Add static pre-release job

.github/pull_request_template.md
=> Add instruction for CI patches

Cabal-tests/Cabal-tests.cabal, cabal-install/cabal-install.cabal, cabal-testsuite/cabal-testsuite.cabal
=> Bump a number of dependencies

cabal-install/src/Distribution/Client/CmdInstall.hs, cabal-testsuite/PackageTests/Install/T7297-8909-7236/Main.hs, cabal-testsuite/PackageTests/Install/T7297-8909-7236/cabal.project, cabal-testsuite/PackageTests/Install/T7297-8909-7236/cabal.test.hs, cabal-testsuite/PackageTests/Install/T7297-8909-7236/t7297-89097236a.cabal
The target of `cabal install` is not considered to be a local package, which means local configuration (e.g. in cabal.project, or flags like --enable-profiling) does not apply to it.
In 76670ebddeb0a914d816f4420c511c1bc1f044eb, we changed the behaviour to applying the local flags to cabal install targets, but it used the literal target string as a package name to which the flags were additionally applied.
However, `cabal install` targets are NOT necessarily package names, so, e.g., if we did `cabal install exe:mycomp`, the local flags would not apply since "exe:mycomp" is not a recognized /package/.
The solution is to parse the target selectors first, and apply the local flags to the package of the resolved targets.
Fixes #7297, #8909, the install part of #7236, #8529, #7832
=> Apply local configuration to install targets

cabal-install/src/Distribution/Client/CmdInstall.hs, cabal-install/src/Distribution/Client/CmdInstall/ClientInstallTargetSelector.hs, cabal-install/src/Distribution/Client/CmdSdist.hs, cabal-install/src/Distribution/Client/CmdUpdate.hs, cabal-install/src/Distribution/Client/ProjectConfig.hs, cabal-install/src/Distribution/Client/ProjectOrchestration.hs, cabal-install/src/Distribution/Client/ProjectPlanning.hs, cabal-install/src/Distribution/Client/ScriptUtils.hs, cabal-install/src/Distribution/Client/Types/PackageSpecifier.hs
CmdInstall.installAction is ~300 lines long and full of nested scopes and ad-hoc logic. This change hopes to make it more readable and understandable.
- Lift withProject and withoutProject out of installAction and split their relative concerns. E.g. not parsing URIs is installAction's concern not withProject's (which would just return a constant []).
- Split an intermediate step into a separate function, resolveTargetSelectorsInProjectBaseContext.
- Reuse withGlobalConfig and fromPkgId (renamed)
- Fix a bug introduced in #9697 802a326fd40bd6f1470114317a807f6c3b198dfa where establishProjectBaseContext is called in a non-project setting. Also simplify its original implementation by moving the change into withProject rather than calling establishProjectBaseContext a second time.
Please read …
=> Refactor CmdInstall / fix bug in #9697

cabal-install/src/Distribution/Client/ProjectBuilding/UnpackedPackage.hs, cabal-install/src/Distribution/Client/ProjectPlanning.hs, cabal-install/src/Distribution/Client/ProjectPlanning/Types.hs
This commit makes it so that cabal-install can explain the reason why it used the legacy fallback, instead of building per-component.
=> cabal-install: justify why legacy-fallback is used

cabal-testsuite/PackageTests/Install/T7297-8909-7236/cabal.test.hs, cabal-testsuite/PackageTests/Install/T7297-8909-7236/repo/external-lib-0.1.0.0/CHANGELOG.md, cabal-testsuite/PackageTests/Install/T7297-8909-7236/repo/external-lib-0.1.0.0/Main.hs, cabal-testsuite/PackageTests/Install/T7297-8909-7236/repo/external-lib-0.1.0.0/external-lib.cabal
In #9697 we fixed passing local options to cabal install targets, but rebasing accidentally dropped one of the added the tests for that PR which tested cabal install target, where target was only available from a remote repository.
=> Add test cabal install remote-pkg for #9697

cabal-install/src/Distribution/Client/ProjectPlanning.hs, cabal-testsuite/PackageTests/MultiRepl/EnabledBadClosure/cabal.out, cabal-testsuite/PackageTests/MultiRepl/EnabledBadClosure/cabal.project, cabal-testsuite/PackageTests/MultiRepl/EnabledBadClosure/cabal.test.hs, cabal-testsuite/PackageTests/MultiRepl/EnabledBadClosure/pkg-a/Foo.hs, cabal-testsuite/PackageTests/MultiRepl/EnabledBadClosure/pkg-a/pkg-a.cabal, cabal-testsuite/PackageTests/MultiRepl/EnabledBadClosure/pkg-b/Bar.hs, cabal-testsuite/PackageTests/MultiRepl/EnabledBadClosure/pkg-b/Setup.hs, cabal-testsuite/PackageTests/MultiRepl/EnabledBadClosure/pkg-b/pkg-b.cabal, cabal-testsuite/PackageTests/MultiRepl/EnabledBadClosure/pkg-c/Quu.hs, cabal-testsuite/PackageTests/MultiRepl/EnabledBadClosure/pkg-c/pkg-c.cabal, cabal-testsuite/PackageTests/NewBuild/CmdRepl/CustomSetup/cabal.out, cabal-testsuite/PackageTests/NewBuild/CmdRepl/CustomSetup/cabal.project, cabal-testsuite/PackageTests/NewBuild/CmdRepl/CustomSetup/cabal.test.hs, cabal-testsuite/PackageTests/NewBuild/CmdRepl/CustomSetup/foo/CHANGELOG.md, cabal-testsuite/PackageTests/NewBuild/CmdRepl/CustomSetup/foo/LICENSE, cabal-testsuite/PackageTests/NewBuild/CmdRepl/CustomSetup/foo/Setup.hs, cabal-testsuite/PackageTests/NewBuild/CmdRepl/CustomSetup/foo/app/Main.hs, cabal-testsuite/PackageTests/NewBuild/CmdRepl/CustomSetup/foo/foo.cabal
This patch deletes a lot of hairy logic to do with removing "bad" edges from the closure. Now the solver just forces `Cabal >= 3.11` universally when `--enable-multi-repl` is enabled.
Fixes #9710
---
---
=> Fix multi-repl closure computation with invalid Custom setup

Cabal-syntax/src/Language/Haskell/Extension.hs, Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs, changelog.d/pr-8854, editors/vim/syntax/cabal.vim
Upcoming extension, see https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8820
=> add the extension ListTuplePuns (GHC proposal 475)

cabal-install/src/Distribution/Client/CmdInstall.hs, cabal-install/src/Distribution/Client/DistDirLayout.hs, cabal-install/src/Distribution/Client/ProjectBuilding/UnpackedPackage.hs, cabal-install/src/Distribution/Client/ProjectOrchestration.hs, cabal-install/src/Distribution/Client/ProjectPlanning.hs, cabal-testsuite/PackageTests/PackageDB/t9678/cabal.test.hs, cabal-testsuite/PackageTests/PackageDB/t9678/p1/CHANGELOG.md, cabal-testsuite/PackageTests/PackageDB/t9678/p1/p1.cabal, cabal-testsuite/PackageTests/PackageDB/t9678/p1/src/MyLib.hs, cabal-testsuite/PackageTests/PackageDB/t9678/p2/CHANGELOG.md, cabal-testsuite/PackageTests/PackageDB/t9678/p2/cabal.project, cabal-testsuite/PackageTests/PackageDB/t9678/p2/p2.cabal, cabal-testsuite/PackageTests/PackageDB/t9678/p2/src/MyLib.hs, cabal-testsuite/PackageTests/PackageDB/t9678/repo/p3-0.1.0.0/CHANGELOG.md, cabal-testsuite/PackageTests/PackageDB/t9678/repo/p3-0.1.0.0/p3.cabal, cabal-testsuite/PackageTests/PackageDB/t9678/repo/p3-0.1.0.0/src/MyLib.hs, changelog.d/issue-9678, doc/cabal-project-description-file.rst
In this PR we make the `--package-db` flag apply only to the default immutable initial package stack rather than also applying to the store package database.
There are two special package databases which cabal install knows about and treats specially.
* The store directory, a global cache of installed packages where cabal builds and installs packages into.
* The inplace directory, a local build folder for packages, where cabal builds local packages in.
It is very important that cabal registers packages it builds into one of these two locations as there are many assumptions that packages will end up here.
With the current design of the `--package-db` flag, you are apparently allowed to override the store location which should have the effect of making the last package database in the …
=> cabal-install: Clarify the semantics of package-db flag

CONTRIBUTING.md
=> Add Issue/PR contributing guidelines

doc/cabal-package-description-file.rst
**This PR does not modify `cabal` behaviour (documentation, tests, refactoring, etc.)**
---
Currently, search the text "A few packages require more elaborate solutions" in https://cabal.readthedocs.io/en/stable/cabal-package.html#example-a-package-containing-a-library-and-executable-programs, click [more elaborate solutions](https://cabal.readthedocs.io/en/stable/morecomplexpackages), result 404 Not Found.
There are many ways to fix this issue.
I use this approach, i.e.
```
`more elaborate solutions <#more-complex-packages>`_
```
because there is a similar internal hyperlink on this page:
```
`find these files at run-time <#accessing-data-files-from-package-code>`_
```
My patch is consistent with it.
=> Fix `<more complex packages>` link lost in doc/cabal-package-description-file.rs

cabal-install/src/Distribution/Client/CmdInstall.hs, cabal-testsuite/PackageTests/Install/T8848/Main.hs, cabal-testsuite/PackageTests/Install/T8848/cabal.project, cabal-testsuite/PackageTests/Install/T8848/cabal.test.hs, cabal-testsuite/PackageTests/Install/T8848/t8848.cabal
Extra-packages listed in a cabal project are to be fetched from hackage,
and will be in memory as 'NamedPackages' rather than resolved to
'SpecificSourcePackage'.
On install, we need to make source-dists for all the specific source
packages, and fetch other packages from hackage. Since extra-packages
are already 'NamedPackages', we simply return them along the sdistize-d
specific source packages and the hackage source packages -- they will be
correctly fetched from Hackage from install.
Previously, cabal install <tgt> on a project with extra-packages would
fail because the branch of 'NamedPackage' for 'PackageSpecifier' was
simply unimplemented.
Fixes #8848
=> Fix cabal install in the presence of extra-packages

Cabal-syntax/Cabal-syntax.cabal, Cabal/Cabal.cabal, cabal-install-solver/cabal-install-solver.cabal, cabal-install/cabal-install.cabal
`extra-doc-files` and `no-autogen-paths` warnings.
=> Update .cabal files

cabal-testsuite/src/Test/Cabal/Monad.hs
Noted in the review of #9717 but somehow missed, removes a reference to a deleted function.
=> Remove stale see 'withSourceCopyDir'

README.md
https://github.com/haskell/cabal/pull/9775#issuecomment-1976598351 :)
I made the badge text be "Release CI Early Warning" to try to make it unambiguous.
=> Add GitLab CI badge

.gitlab/ci.sh
(In GitLab CI)
[![GitLab pipeline status](https://gitlab.haskell.org/haskell/cabal/badges/b/zlib-no-pkg-config/pipeline.svg?key_text=Release%20CI%20Early%20Warning&key_width=150)](https://gitlab.haskell.org/haskell/cabal/-/commits/b/zlib-no-pkg-config)
=> Tell zlib not to use pkg-config

cabal-testsuite/PackageTests/VersionPriority/1-web.test.hs, cabal-testsuite/PackageTests/VersionPriority/2-web.test.hs, cabal-testsuite/PackageTests/VersionPriority/3-web.test.hs
Not a fix for #9738. I'm able to reproduce that problem (that I've written up on #9738) but these tests don't need the `skipIfGhcVersion "== 9.6.3"` because the `.out` files don't include the differing output, the `ghc-<GHCVER>` versus `ghc-9.6.3` difference.
=> Remove skipIfGhcVersion "== 9.6.3"

cabal-install/src/Distribution/Client/ProjectConfig.hs, changelog.d/issue-9641
Closes: https://github.com/haskell/cabal/issues/9641
How this was tested:
- use the example project: https://github.com/peterbecich/cabal2nix-project-issue
- this example pulls the `text` library as a `source-repository-package`
- build, install Cabal from this PR
- `cabal install cabal --overwrite-policy=always`
- in the example project, delete `dist-newstyle` to remove the `text` library cached there
- `rm -rf dist-newstyle; ~/.cabal/bin/cabal build`
- `text` library pulled, build succeeds
- next, build with the cached `text` library and `offline` flag
- `~/.cabal/bin/cabal build  --offline`
- this succeeds
- offline flag does not break the cached library
- next, delete `dist-newstyle` again, and attempt build with `--offline`
- `rm -rf dist-newstyle; ~/.cabal/bin/cabal build --offline` …
=> offline flag disables `source-repository-package` sync

Cabal-syntax/src/Language/Haskell/Extension.hs, Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs, Cabal/src/Distribution/Simple/GHC/ImplInfo.hs, Cabal/src/Distribution/Simple/GHC/Internal.hs, cabal-install/src/Distribution/Client/Init/Interactive/Command.hs, cabal-install/tests/UnitTests/Distribution/Client/Init/Interactive.hs, changelog.d/issue-9736, doc/buildinfo-fields-reference.rst, doc/cabal-package-description-file.rst, editors/vim/syntax/cabal.vim
This adds support for the `GHC2024` language edition, which will be introduced with GHC 9.10. I've grepped for `GHC2021` and copy-pasted; I'm not sure what QA notes or additional tests are needed (if any).
---
=> Support GHC2024 (fixes #9736)

.github/workflows/quick-jobs.yml
Fixes #9601. Add a `build --dry-run` quick job for lightweight checking `cabal.project.release`. Increases duplication in `workflows/quick-jobs.yml`.
=> Add a --dry-run build check of cabal.project.release

cabal-install/src/Distribution/Client/Init/Licenses.hs, changelog.d/pr-9813
`cabal init` text for BSD-2-Clause and BSD-3-Clause licence differed slightly from the one published at SPDX. [1] [2]
This caused some problems to users when dealing with licence-recognition software. [3]
[1] https://spdx.org/licenses/BSD-2-Clause.html
[2] https://spdx.org/licenses/BSD-3-Clause.html
[3] https://discourse.haskell.org/t/non-standard-license-generated-by-stack-new/9059
---
---
**QA Notes**
1. `cabal init` and a series of ⏎ (it should select a BSD licence)
2. `LICENSE` file does not contain the sentence “All rights reserved.”.
=> Conform BSD-2-Clause and BSD-3-Clause text to SPDX

.github/workflows/changelogs.yml, changelog.d/config, changelog.d/issue-8680, changelog.d/issue-9098-lexbraces, changelog.d/issue-9678, changelog.d/issue-9736, changelog.d/pkgconfig-once
See https://codeberg.org/fgaz/changelog-d/issues/6
---
=> Add required-fields to changelog.d config

Cabal-syntax/src/Distribution/SPDX/LicenseExceptionId.hs, Cabal-syntax/src/Distribution/SPDX/LicenseId.hs, Cabal-syntax/src/Distribution/SPDX/LicenseListVersion.hs, Makefile, cabal-dev-scripts/src/GenSPDX.hs, cabal-dev-scripts/src/GenSPDXExc.hs, cabal-dev-scripts/src/GenUtils.hs, changelog.d/pr-spdx, doc/file-format-changelog.rst, license-list-data/exceptions-3.23.json, license-list-data/licenses-3.23.json, templates/SPDX.LicenseExceptionId.template.hs, templates/SPDX.LicenseId.template.hs
Per https://github.com/haskell/cabal/wiki/Updating-the-license-list to version 3.23 (2024-02-08) of SPDX License List.
---
=> Update licence list

Cabal-tests/tests/ParserTests/regressions/issue-6288-d.cabal, Cabal-tests/tests/ParserTests/regressions/issue-6288-f.check, Cabal-tests/tests/ParserTests/regressions/issue-7776-a.cabal, Cabal-tests/tests/ParserTests/regressions/issue-7776-b.cabal, Cabal-tests/tests/ParserTests/regressions/issue-7776-c.cabal, Cabal/src/Distribution/PackageDescription/Check/Target.hs, Cabal/src/Distribution/PackageDescription/Check/Warning.hs, cabal-testsuite/PackageTests/Check/ConfiguredPackage/CabalVersion/DefaultLanguageSoft/cabal.out, cabal-testsuite/PackageTests/Check/ConfiguredPackage/CabalVersion/DefaultLanguageSoft/cabal.test.hs, cabal-testsuite/PackageTests/Check/ConfiguredPackage/CabalVersion/DefaultLanguageSoft/pkg.cabal, changelog.d/pr-9766, doc/cabal-commands.rst
Closes #9620 
Add a warning ("Hackage would refuse this package") when `default-language` is missing. Done to prepare the user to GHC language editions.
---
---
** QA notes **
1. `cabal init` a package, choose `cabal-version` 3.4
2. run `cabal check`
3. old cabal: it will not complain about missing `default-language`
4. new cabal: it wil complain about missing `default-language`
=> Add “Add default-language” suggestion

.github/workflows/validate.yml
This provides temporary life support to the `validate-old-ghcs` action
until node16 will be finally axed by GHA in May 2024.
Workaround for:
- https://github.com/haskell/cabal/issues/9858
=> CI validate-old-ghcs: pin to haskell-actions/setup@v2.6

.github/workflows/quick-jobs.yml, Cabal/src/Distribution/Simple/Build/Macros/Z.hs, Makefile
Fix #9815:
- Cache `~/.local/state/cabal` instead of `~/.cabal/store`
- `~/.local/bin` is used instead of `~/.cabal/bin` and is already in the PATH
(verify this by calling `alex` after installing it)
As I am passing by:
- bump cache action to v4
- double-quote `$USER` to keep actionlint happy
- move `if` from shell-level to job-level
- allow newest `alex`
UPDATE:  This PR has been extended to
- use preinstalled GHC and Cabal in this workflow (saves 90sec on each job)
- clear the remains of the `lexer` goal in the `Makefile` (was removed in #8980)
- while I am add it, use `.PHONY` systematically in `Makefile`
- fix caching for the quick-jobs
* Use key from the build plan where possible
* Use daily key for the doctest job
- update a generated file to make "Meta checks" pass
=> Fix #9815: fix caching for quick-jobs CI (XDG, cache keys)

.github/workflows/changelogs.yml
This is the same as #9845 but for the changelogs.yml workflow.
=> CI changelogs: switch to XDG, fix cache key

Cabal-syntax/Cabal-syntax.cabal, Cabal/Cabal.cabal
=> Bump time upper bound to acccomodate 1.14

bootstrap/cabal-bootstrap-gen.cabal
=> Update Cabal-syntax for bootstrap

cabal-install/cabal-install.cabal, cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs
These commits add some tests I wrote when thinking about #9466 and #9467.
=> testsuite: Add some unit tests for #9466 #9467 

Cabal-described/Cabal-described.cabal, Cabal-syntax/Cabal-syntax.cabal, Cabal-tests/Cabal-tests.cabal, Cabal/Cabal.cabal, cabal-install-solver/cabal-install-solver.cabal, cabal-install/cabal-install.cabal, cabal-testsuite/cabal-testsuite.cabal, project-cabal/ghc-options.config
Fixes #9853. I am a bit frustrated that I've not been able fix or suppress the `-Werror=unused-package` with `cabal-testsuite` except with the following setting in `project-cabal/ghc-options.config`;
```cabal
package cabal-testsuite
ghc-options: -Wwarn=unused-packages
```
I tried adding similar `ghc-options` to `cabal-testsuite:test:test-runtime-deps` (the intentional source of unused package dependencies) but suppose project settings override package settings.
=> Remove unused packages

doc/how-to-build-like-nix.rst, doc/nix-local-build.rst
These are just some trivial docs fixes I noticed while wondering where my store had got to.
---
This PR does not modify `cabal` behaviour (documentation, tests, refactoring, etc.)
=> docs: correct references to location of global store

cabal-install/cabal-install.cabal, cabal-install/src/Distribution/Client/CmdPath.hs, cabal-install/src/Distribution/Client/Config.hs, cabal-install/src/Distribution/Client/Errors.hs, cabal-install/src/Distribution/Client/Main.hs, cabal-install/src/Distribution/Client/ScriptUtils.hs, cabal-install/src/Distribution/Client/Setup.hs, cabal-testsuite/PackageTests/Path/All/cabal.out, cabal-testsuite/PackageTests/Path/All/cabal.test.hs, cabal-testsuite/PackageTests/Path/Compiler/cabal.out, cabal-testsuite/PackageTests/Path/Compiler/cabal.test.hs, cabal-testsuite/PackageTests/Path/Config/cabal.out, cabal-testsuite/PackageTests/Path/Config/cabal.test.hs, cabal-testsuite/PackageTests/Path/Config/config.cabal, cabal-testsuite/PackageTests/Path/Config/fake-cabal.config, cabal-testsuite/PackageTests/Path/Config/fake.cabal.project, cabal-testsuite/PackageTests/Path/Single/cabal.out, cabal-testsuite/PackageTests/Path/Single/cabal.test.hs, cabal-testsuite/src/Test/Cabal/Monad.hs, cabal-testsuite/src/Test/Cabal/OutputNormalizer.hs, cabal-testsuite/src/Test/Cabal/Prelude.hs, changelog.d/pr-9583, doc/cabal-commands.rst
Previously, `cabal path` was only able to query from the global configuration file, e.g., `~/.cabal/config` or the XDG equivalent. This was deemed not useful enough to warrant a new cabal command, which is a user facing change.
We take the foundations and turn them into `cabal v2-path` which takes project configuration, such as `cabal.project` into account. Note, the command is still named `cabal path`, but for the sake of disambiguation, we refer to this new iteration of the command as `cabal v2-path`.
In addition, we add support for multiple output formats, such as key-value pairs and json. Specifying the output format is currently mandatory. This allows us to postpone the decision of the default output format and encourages users to explicitly specify the output format in the future, …
=> Redesign 'cabal path' command to account for projects

.github/workflows/validate.yml, cabal-testsuite/PackageTests/ForeignLibs/setup.test.hs
Changes:
- bump GHC_FOR_RELEASE to 9.4.8
- bump action versions
- uniform quoting style
- satisfy actionlint
- fix order: setup Haskell before cache restore (uses setup.haskell-outputs)
- use `--ignore-project` in `cabal install hackage-repo-tool`
- closes #8858: deleted comment
- closes #9858 by dropping container and use ghcup to setup ghcs
=> CI: stop validating GHC 7

cabal-install-solver/src/Distribution/Solver/Modular/Message.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs, changelog.d/pr-9824
Fixes #9823.
With this fix, the solver rejection message of the reproduction for #9823 is shorter[^1];
```
$ cabal build all --enable-tests --enable-benchmarks --dry-run
Warning: this is a debug build of cabal-install with assertions enabled.
Error: [Cabal-7107]
Could not resolve dependencies:
[__0] next goal: Cabal (user goal)
[__0] rejecting: Cabal-3.11.0.0 (constraint from project config /home/.../cabal.project.local requires ==2.4.1.0 || ==3.0.2.0 || ==3.2.1.0)
[__0] rejecting: Cabal; 3.10.2.1, 3.10.2.0/installed-fd40, 3.10.2.0, 3.10.1.0, 3.8.1.0, 3.6.3.0, 3.6.2.0, 3.6.1.0, 3.6.0.0, 3.4.1.0, 3.4.0.0, 3.2.1.0, 3.2.0.0, 3.0.2.0, 3.0.1.0, 3.0.0.0, 2.4.1.0, 2.4.0.1, 2.4.0.0, 2.2.0.1, 2.2.0.0, 2.0.1.1, 2.0.1.0, 2.0.0.2, 1.24.2.0, 1.24.0.0, 1.22.8.0, 1.22.7.0, …
```
=> Show abbreviated mixed versions with suffix

cabal-testsuite/PackageTests/NewFreeze/T9799a/Setup.hs, cabal-testsuite/PackageTests/NewFreeze/T9799a/T9799.cabal, cabal-testsuite/PackageTests/NewFreeze/T9799a/cabal.test.hs, cabal-testsuite/PackageTests/NewFreeze/T9799a/repo/libA-0.1.0.0/libA.cabal, cabal-testsuite/PackageTests/NewFreeze/T9799a/repo/libA-0.1.0.0/src/MyLib.hs, cabal-testsuite/PackageTests/NewFreeze/T9799a/repo/libA-0.2.0.0/libA.cabal, cabal-testsuite/PackageTests/NewFreeze/T9799a/repo/libA-0.2.0.0/src/MyLib.hs, cabal-testsuite/PackageTests/NewFreeze/T9799a/src/MyLib.hs, cabal-testsuite/PackageTests/NewFreeze/T9799b/Setup.hs, cabal-testsuite/PackageTests/NewFreeze/T9799b/T9799.cabal, cabal-testsuite/PackageTests/NewFreeze/T9799b/cabal.test.hs, cabal-testsuite/PackageTests/NewFreeze/T9799b/repo/libA-0.1.0.0/libA.cabal, cabal-testsuite/PackageTests/NewFreeze/T9799b/repo/libA-0.1.0.0/src/MyLib.hs, cabal-testsuite/PackageTests/NewFreeze/T9799b/repo/libA-0.2.0.0/libA.cabal, cabal-testsuite/PackageTests/NewFreeze/T9799b/repo/libA-0.2.0.0/src/MyLib.hs, cabal-testsuite/PackageTests/NewFreeze/T9799b/src/None.hs
Add tests for #9799 about freeze qualifying all packages with 'any' constraint scope.
=> Add tests for #9799

.github/mergify.yml
Made by copying things from the master squash+merge into a copy of the backport strategy. I'm a neophyte at Mergify, so someone should check this.
Testing notes:
* since this affects only CI of backports, there's no way to test on `master`
* I disrecommend testing on actual release branches. I suspect we need to create a test branch to "backport" things to.
=> add squash+merge for backports

release-notes/Cabal-3.12.0.0.md, release-notes/WIP-cabal-install-3.12.x.0.md
=> Fix release notes grammar

doc/cabal-commands.rst
Fixes #9930 using a common [placeholder name](https://en.wikipedia.org/wiki/Placeholder_name), Alice of Alice and Bob. A follow on from #9583.
=> Use alice as username in cabal path examples

release-notes/Cabal-3.12.0.0.md
And suggestion on what to use (`preBuildComponent`) instead.
=> Add `initialBuildSteps` removal notice

doc/cabal-commands.rst
From #9942, talk about `TARGETS` of `cabal test`; the implicit package target if in the directory of a package and the `all` and `all:tests` targets.
=> Add warning and note to cabal test [TARGETS]

.github/workflows/validate.yml, release-notes/Cabal-3.12.0.0.md
We have a five-year support policy for GHC, but this was never stated in release notes (specifically, list GHCs we stop supporting).
This patch rectifies this for 3.12 release notes, plus I have added a new point to the [“Making a release” document](https://github.com/haskell/cabal/wiki/Making-a-release#c1-preflight-checks), that is: 
> `cabal` has a five-year support window for GHC. Check the [GHC/base table](https://wiki.haskell.org/Base_package), bump `base` lower bound accordingly in all packages, write a changelog file that states we drop support for `GHC x.y`.
---
=> State supported GHC versions in release notes

CONTRIBUTING.md
In support of #9944, define what a user-visible change is in `CONTRIBUTING.md`.
=> Define a user-visible change

.github/workflows/lint.yml, .hlint.yaml
Bumps to `hlint-3.8` and updates the `.hlint.yaml` configuration.
=> Bump to hlint-3.8

cabal-install/src/Distribution/Client/Setup.hs, cabal-testsuite/PackageTests/WorkingDir/Main.hs, cabal-testsuite/PackageTests/WorkingDir/Setup.hs, cabal-testsuite/PackageTests/WorkingDir/cabal.project, cabal-testsuite/PackageTests/WorkingDir/dep/Dep.hs, cabal-testsuite/PackageTests/WorkingDir/dep/Setup.hs, cabal-testsuite/PackageTests/WorkingDir/dep/dep.cabal, cabal-testsuite/PackageTests/WorkingDir/setup.test.hs, cabal-testsuite/PackageTests/WorkingDir/working-dir-test.cabal
The --working-dir flag is only available for Cabal >= 3.13. This commit fixes an incorrect conditional: we only filtered out this flag for Cabal < 3.11, instead of < 3.13.
Fixes #9940
=> Filter Setup flags: filter working dir on < 3.13

Cabal-hooks/Cabal-hooks.cabal, Cabal-syntax/Cabal-syntax.cabal, Cabal-tests/Cabal-tests.cabal, Cabal/Cabal.cabal, cabal-dev-scripts/cabal-dev-scripts.cabal, cabal-install-solver/cabal-install-solver.cabal, cabal-install/cabal-install.cabal, cabal-testsuite/cabal-testsuite.cabal
Per https://github.com/haskell/cabal/issues/9952#issuecomment-2088287364.
=> update `base` bounds for desupported ghc 8.2

doc/cabal-commands.rst, doc/cabal-package-description-file.rst
I didn't think this warranted raising an issue beforehand. Fixes two instances of the proper noun Hackage not being capitalized. This was originally brought to my attention during a code review by @malteneuss, https://github.com/haskell/cabal/pull/9701#discussion_r1582365958.
=> Hackage as a proper noun, capitalized in docs

doc/how-to-run-in-windows.rst, doc/index.rst
This is my humble attempt at providing some documentation for how to use GHC and Cabal in Windows. It aims to resolve #9713 , however all I wrote here is based on my experience and might not be The Correct Way To Do Things :tm:. I could use some thorough reviews.
=> How to use Cabal in Windows

release-notes/WIP-cabal-install-3.12.x.0.md
I'm touching up the release notes generated by @ffaf1 to serve as the changelog for the cabal-install 3.12.0.0 prerelease. I've mostly copied a lot of entries from the Cabal 3.12.0.0 release notes, because they significantly affect the behaviour of cabal-install as opposed to being implementation details of Cabal or changing the portions of Cabal API that are not reflected in the API and/or behaviour of cabal-install. This will require further editing effort for the official 3.12.1.0 release of cabal-install.
I checked with `sort | uniq` that no entries repeat and I had a quick look and couldn't find any text duplicated in the Cabal changelog that has …
=> Touch up release notes for cabal-install 3.12.0.0 pre-release

Cabal/src/Distribution/Simple/Errors.hs, Cabal/src/Distribution/Simple/Install.hs, cabal-testsuite/PackageTests/OnlyTestSuite/OnlyTestSuite.cabal, cabal-testsuite/PackageTests/OnlyTestSuite/cabal.cabal.out, cabal-testsuite/PackageTests/OnlyTestSuite/cabal.out, cabal-testsuite/PackageTests/OnlyTestSuite/cabal.test.hs, cabal-testsuite/PackageTests/OnlyTestSuite/test/Main.hs, changelog.d/issue-6750
This makes Setup copy/install succeed if there's
nothing to do because the package doesn't contain
a library or executable.
This allows downstream users of Cabal to avoid having to add workarounds for this edge case.
Resolves #6750
Let me know what you think. If this sounds OK, I'll add a test case, which test suite would be best?
---
=> Downgrade NoLibraryFound from an error to a warning

cabal-install/src/Distribution/Client/ProjectBuilding/UnpackedPackage.hs, cabal-install/src/Distribution/Client/ProjectPlanning.hs, cabal-testsuite/PackageTests/HaddockKeepsTmps/Simple.hs, cabal-testsuite/PackageTests/HaddockKeepsTmps/cabal.project, cabal-testsuite/PackageTests/HaddockKeepsTmps/cabal.test.hs, cabal-testsuite/PackageTests/HaddockKeepsTmps/my.cabal
This commit initialises the Haddock flag `haddockKeepTempFiles` with the value of `buildSettingKeepTempFiles`.
The only change in the patch is the following, in `setupHsHaddockFlags`:
```diff
- haddockKeepTempFiles = mempty -- TODO: from build settings
+ haddockKeepTempFiles = toFlag keepTmpFiles
```
where `keepTmpFiles` is retrieved from `BuildTimeSettings`.
This addresses an 8 year old TODO in the code.
**Template Α**: This PR modifies [behaviour or interface](https://github.com/cabalism/cabal/blob/master/CONTRIBUTING.md#changelog).
TODO:
=> Haddock: use buildSettingKeepTempFiles

doc/cabal-commands.rst, doc/cabal-package-description-file.rst, doc/cabal-project-description-file.rst, doc/how-to-source-packages.rst, doc/index.rst, doc/version-control-fields.rst
Updates the users guide adding a warning comparing `source-repository` with `source-repository-package`, see #9655. Also;
- Adds pijul as `type`
- explicit `.` is the same as root
=> source-repository versus source-repository-package

doc/cabal-package-description-file.rst
The proposal has been accepted, but its final location is in the 'rfc' subdirectory instead of the 'proposals' subdirectory. This simply updates the link in the Cabal documentation.
--
=> Docs: update link to SetupHooks RFC

cabal-install/src/Distribution/Client/ProjectPlanning/SetupPolicy.hs, cabal-install/src/Distribution/Client/SetupWrapper.hs, cabal-testsuite/PackageTests/SetupHooks/SetupHooksNoBase/A.hs, cabal-testsuite/PackageTests/SetupHooks/SetupHooksNoBase/SetupHooks.hs, cabal-testsuite/PackageTests/SetupHooks/SetupHooksNoBase/cabal.project, cabal-testsuite/PackageTests/SetupHooks/SetupHooksNoBase/cabal.test.hs, cabal-testsuite/PackageTests/SetupHooks/SetupHooksNoBase/setup-hooks-no-base-test.cabal
This allows us to compile Setup.hs without depending on base. In particular, this ensures that a package with `build-type: Hooks` and a custom setup stanza that does not depend on base successfully compiles.
Tested in `PackageTests/SetupHooks/SetupHooksNoBase`.
---
=> Add NoImplicitPrelude to buildTypeScript

cabal.project.release
I have backports failing on 3.12 because the index state update from #9897 is not on 3.12: https://github.com/haskell/cabal/actions/runs/9080152427/job/24950912901?pr=10002
Does it look reasonable to backport this change? @ffaf1 @Mikolaj
---
=> Bump index-state in the release project file

.github/workflows/quick-jobs.yml
This should fix the CI quick jobs that have been failing recently. Could you please have a look @Mikolaj
=> ci: Fix quick-jobs GHC version to 9.6

CONTRIBUTING.md
See #9901, recommend using the latest `cabal-install` either installed or not. Show examples of installing and running without first installing it.
=> Recommend using latest cabal-install

bootstrap/generate_bootstrap_plans
We need to use the cabal.bootstrap.project file to generate the bootstrap plans, otherwise we try to include test components when bootstrapping, which is not useful (and significantly complicates bootstrapping).
I forgot to include this change in 88737ef, but I used this change to generate the plans.
---
=> Use bootstrap project in bootstrapping

doc/cabal-project-description-file.rst
Adds a note that `source-repository-package` is not for the command line.
```
$ cabal build solver-benchmarks --source-repository-package=https://github.com/haskell/vector
Error: cabal: unrecognized 'build' option
`--source-repository-package=https://github.com/haskell/vector'
```
Also shows ".cabal file" as "`.cabal` file" and moves this paragraph up so that it is placed before the note and before any code blocks in this section.
=> Add "no command line variant" for `source-repository-package`.

cabal-testsuite/PackageTests/NewUpdate/RejectFutureIndexStates/cabal.test.hs, cabal-testsuite/PackageTests/NewUpdate/UpdateIndexState/update-index-state.test.hs
RejectFutureIndexStates and UpdateIndexState are marked "skip", but it's under withRemoteRepo, which causes flakiness before skip is called.
=> PackageTests/NewUpdate: fix skipping flaky tests

cabal-testsuite/PackageTests/NewUpdate/RejectFutureIndexStates/cabal.test.hs, cabal-testsuite/PackageTests/NewUpdate/UpdateIndexState/update-index-state.test.hs
RejectFutureIndexStates and UpdateIndexState are marked "skip", but it's under withRemoteRepo, which causes flakiness before skip is called.
backport of #10035
=> [3.12] PackageTests/NewUpdate: fix skipping flaky tests

.github/workflows/changelogs.yml
This will avoid build problems when the GHC in the CI environment is updated sooner than expected.
Previous breakage: https://github.com/haskell/cabal/pull/9177#issuecomment-2125549693
---
=> CI: install changelog-d from bindist

Cabal/src/Distribution/PackageDescription/Check/Target.hs, changelog.d/issue-10042
=> Fix #10042 Don't recommend deprecated/removed 'extensions:' field

.github/workflows/validate.yml, cabal-install/src/Distribution/Client/TargetSelector.hs, cabal-install/tests/IntegrationTests2.hs, cabal-install/tests/UnitTests/Distribution/Client/Init/NonInteractive.hs, cabal-testsuite/PackageTests/CCompilerOverride/foo.c, cabal-testsuite/PackageTests/CCompilerOverride/my.cabal, cabal-testsuite/PackageTests/CCompilerOverride/setup.cabal.out, cabal-testsuite/PackageTests/CCompilerOverride/setup.out, cabal-testsuite/PackageTests/CCompilerOverride/setup.test.hs, project-cabal/ghc-latest.config
=> CI: add GHC 9.10

cabal-install/src/Distribution/Client/JobControl.hs, cabal-install/src/Distribution/Client/ProjectBuilding.hs
---
This PR fixes the message “Created semaphore called cabal_semaphore_XXX with NNN slots.” appearing even with `--verbosity=0`.
=> fix: Make newSemaphoreJobControl respect verbosity

.gitignore, Cabal/src/Distribution/Simple/Haddock.hs, Cabal/src/Distribution/Simple/Setup/Haddock.hs, Cabal/src/Distribution/Types/LocalBuildInfo.hs, cabal-install/src/Distribution/Client/CmdHaddockProject.hs, cabal-install/src/Distribution/Client/Config.hs, cabal-install/src/Distribution/Client/PackageHash.hs, cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs, cabal-install/src/Distribution/Client/ProjectConfig/Types.hs, cabal-install/src/Distribution/Client/ProjectPlanning.hs, cabal-install/src/Distribution/Client/ProjectPlanning/Types.hs, cabal-install/src/Distribution/Client/Setup.hs, cabal-install/tests/IntegrationTests2.hs, cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs, cabal-testsuite/PackageTests/NewHaddock/Fails/cabal.out, changelog.d/pr-9177, doc/cabal-project-description-file.rst, release-notes/WIP-Cabal-3.12.x.0.md, test/IntegrationTests2/config/default-config, test/IntegrationTests2/nix-config/default-config, tests/IntegrationTests2/config/default-config, tests/IntegrationTests2/nix-config/default-config
Haddock no longer writes compilation files by default, so we do not need to pass tmp dirs for `-hidir`, `-stubdir`, and `-odir` via `--optghc`. Indeed, we do not *want* to do so, since it results in recompilation for every invocation of Haddock via Cabal. This commit stops this from happening for Haddock versions 2.28 or greater (when Hi Haddock was introduced).
This commit also prevents the definition of the `__HADDOCK_VERSION__` macro when invoking GHC through Haddock by default, which necessary to avoid recompilation during documentation generation, since the macro invalidates existing build results. Since a limited set of users may rely on this macro still, we introduce the `--haddock-version-cpp` flag and `haddock-version-cpp:` cabal.project field, which enable the definition of the …
=> Haddock recompilation avoidance

cabal-install/src/Distribution/Client/CmdInstall.hs, cabal-testsuite/PackageTests/Install/ProgramAffixes/Main.hs, cabal-testsuite/PackageTests/Install/ProgramAffixes/cabal.project, cabal-testsuite/PackageTests/Install/ProgramAffixes/cabal.test.hs, cabal-testsuite/PackageTests/Install/ProgramAffixes/p.cabal, changelog.d/issue-9919
---
---
Fixes #9919
Fixes #8823
Based on [this comment](https://github.com/haskell/cabal/issues/8823#issuecomment-2079197342).
It took me a lot of time to understand where to look at and I am still unsure this fix does not introduce side effects. I would need some guidance if improvements are needed.
=> Fix --program-suffix resulting in invalid symlink

Cabal/Cabal.cabal, cabal-install-solver/cabal-install-solver.cabal, cabal-install/cabal-install.cabal
`base` and `QuickCheck` + cabal-version since 2.2 seems to have been released [around December 2017](https://cabal.readthedocs.io/en/stable/file-format-changelog.html#cabal-version-2-2).
---
=> Bump dependencies and cabal-version

.github/workflows/validate.yml
=> CI: dogfooding should run on the same Mac runner as validate

Cabal/src/Distribution/Simple/Program.hs, Cabal/src/Distribution/Simple/Program/GHC.hs, changelog.d/pr-10014
Relevant issue https://github.com/haskell/cabal/issues/9729 (blocked by this PR)
This PR is concerned with updating the `Distribution.Simple.Program.GHC` module to include flags added since (inclusively) 9.2 into `normalizeGHCArgs` and remove flags that have since removed in `renderGhcOptions`.
The file didn't seem to be updated since ghc 8.10. I hope to address that in this PR.
Actionable flags, as far as I can tell, are (see commit message):
- `-fdiagnostics-as-json` (changes the format GHC outputs its diagnostics)
- `-fprint-error-index-lists=<always|never|auto>` (changes the way GHC displays compile time)
- `-fbreak-points` (enables/disables break-points in GHCi)
- `-dipe-stats` (dumps information about which info tables have IPE
information)
- `-ffamily-application-cache` (only …
=> add the applicable new (version 9.10) GHC flags to normaliseGhcArgs

cabal-install/src/Distribution/Client/Dependency.hs
GHC 9.10 ships with a new wired-in package, `ghc-internal`, which cannot be reinstalled. This commit prevents `cabal-install` from attempting it. See #10087.
It would be good to include this alongside GHC 9.10 support, if possible.
---
Attempting to build a package called `ghc-internal` that has no dependencies should result in a dependency solving error "constraint from non-reinstallable package requires installed instance".
=> solver: Prevent ghc-internal from being reinstalled (see #10087)

cabal-install/src/Distribution/Client/ProjectBuilding/UnpackedPackage.hs, cabal-testsuite/PackageTests/Recompilation/GHC24926/Repro.hs, cabal-testsuite/PackageTests/Recompilation/GHC24926/cabal.test.hs, cabal-testsuite/PackageTests/Recompilation/GHC24926/repro.cabal, cabal-testsuite/PackageTests/Recompilation/GHC24926/src/Process.hs
Be sure to invalidate the cache if building throws an exception! If not, we'll abort execution with a stale recompilation cache. See ghc#24926 for an example of how this can go wrong.
---
=> Fix recomp bug by invalidating cache on build exception

cabal-testsuite/PackageTests/BuildToolPaths/cabal.test.hs, cabal-testsuite/main/cabal-tests.hs, cabal-testsuite/src/Test/Cabal/Monad.hs, cabal-testsuite/src/Test/Cabal/Prelude.hs
**Template B**: This PR does not modify behaviour or interface of `Cabal` or `cabal-install` – it is purely a change in the testsuite.
This PR modifies `cabal-testsuite` to allow passing the path to the "store" package database. This allows the test suite to handle building packages with a custom setup that depends on other packages (which get installed into the store).
Checklist:
=> testsuite: Pass pkgdb of store used for intree Cabal

doc/cabal-project-description-file.rst
I went in to fix a minor grammar glitch.
```diff
- If you use such explicit file you *must* fill the field.
+ If you use such an explicit file, you *must* fill in the field.
```
On review, I think it is clearer not to have `packages: ./*.cabal` shown as the default value for the `packages` field.
=> Change packages default to empty

Cabal/src/Distribution/Simple/Configure.hs, Cabal/src/Distribution/Simple/Program/Builtin.hs, cabal-install/src/Distribution/Client/ProjectPlanning.hs, cabal-install/src/Distribution/Client/SetupWrapper.hs, cabal-testsuite/PackageTests/ExtraProgPath/setup.out
This PR contains several commits that address problems with how we were handling unconfigured programs in the program database:
- We should configure unconfigured programs before serialising them (using the `Binary ProgramDb` instance) in
`Distribution.Client.ProjectPlanning.configureCompiler`, as otherwise we can accidentally discard information.
Not doing so can lead to situations in which we can build a package just fine, but if we re-start a build we will fail,
because the program database on disk stored after configuring doesn't match the program database in memory.
- As a follow-on from the above, `configureRequiredProgram` needs to gracefully handle an already-configured program.
Not doing so means we would fall back to the `simpleProgram` treatment, which can cause `Cabal` to fail …
=> Be more careful in handling unconfigured programs in the program database

Cabal-syntax/src/Distribution/Compiler.hs, Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs, changelog.d/pr-9878
=> Add MHS as a recognized compiler.

.hlint.yaml, cabal-install/src/Distribution/Client/FetchUtils.hs, cabal-install/src/Distribution/Client/ProjectPlanning.hs, cabal-install/src/Distribution/Client/Utils.hs
verifyFetchedTarball has the effect of deserialising the index tarball (see call to Sec.withIndex).
verifyFetchedTarball is called individually for each package in the build plan (see ProjectPlanning.hs). Not once per repo.
The hackage tarball is now 880mb so it takes a non significant amount of time to deserialise this (much better after haskell/tar#95).
This code path is important as it can add 1s with these 38 calls on to the initial load of a project and scales linearly with the size of your build tree.
Reproducer: Simple project with "lens" dependency deserialises the index tarball 38 times.
Solution: Refactor verifyFetchedTarball to run once per repo rather than once per package.
In future it would be much better to refactor this function so that the items are not immediately …
=> perf: Group together packages by repo when verifying tarballs

bootstrap/generate_bootstrap_plans, bootstrap/linux-8.10.7.json, bootstrap/linux-9.0.2.json, bootstrap/linux-9.2.8.json, bootstrap/linux-9.4.8.json, bootstrap/linux-9.6.4.json, bootstrap/linux-9.8.2.json, cabal.bootstrap.project, cabal.release.project
tar-0.6.3.0 has much improved performance of deserialising .tar index
which has significant ramifications for the start-up time of
cabal-install.
See https://github.com/haskell/cabal/issues/10110
=> Depend on tar-0.6.3.0

release-notes/Cabal-3.12.0.0.md
This was on `master` but missing from 3.12.
=> one last changelog entry

Cabal-described/Cabal-described.cabal, Cabal-tests/Cabal-tests.cabal, cabal-install-solver/cabal-install-solver.cabal, cabal-install/cabal-install.cabal
tasty-quickcheck 0.11, which was just released, is API incompatible with earlier versions. Exclude it from build plans. (Why were we using it without an upper bound?)
=> Skip tasty-quickcheck 0.11

cabal.release.project, cabal.validate.project
We don't want to accidentally create binaries that contain CPU instructions only available in some machines. Hashable has this flag that enables the usage of `-march=native` for its FFI C code, so we have to disable it explicitly.
The `cabal.validate.project` file is also concerned because [we use it to build the `cabal-head` binary that we distribute.](https://github.com/haskell/cabal/blob/c39022a2297bf54f2b77d6be70c33957f224abb4/.github/workflows/validate.yml#L159)
=> Disable arch-native flag when building releases that we distribute

bootstrap/linux-9.0.2.json, bootstrap/linux-9.2.8.json, bootstrap/linux-9.4.8.json, bootstrap/linux-9.6.4.json, bootstrap/linux-9.8.2.json, cabal.bootstrap.project
=> regenerate bootstrap files without arch-native

cabal-testsuite/cabal-testsuite.cabal, validate.sh
=> Use `--io-manager=native` in `lib-suite` on Windows

doc/cabal-package-description-file.rst
Bases for additions to online docs:
* https://downloads.haskell.org/~ghc/6.10.1/docs/html/users_guide/release-6-10-1.html ("... the `includes` field in `.cabal` files ... all have no effect when compiling Haskell source code.")
* EDIT: https://downloads.haskell.org/ghc/latest/docs/users_guide/exts/ffi.html#using-header-files ("... the `include-files` field in a Cabal package specification is ignored.") (The reference to `include-files` is as in the original; it can be understood to mean `includes`.) EDIT2: https://gitlab.haskell.org/ghc/ghc/-/issues/25032
* https://hackage.haskell.org/package/Cabal-2.0.0.2/changelog ("Dropped support for versions of GHC earlier than 6.12 ...")
* https://github.com/haskell/cabal/commit/e1c39fc9ff4bf4eb8e956e2ee77da95d6cc73bbe (removes use of GHC's …
=> Improve online docs for `includes:` field

CONTRIBUTING.md, Cabal/src/Distribution/Simple/Setup/Haddock.hs, changelog.d/issue-10051
Added `--all` (`--haddock-all`) switches for compatibility with
`haddock` command.  `--haddock-all` alias is added, since that's what is
suggested by some warning messages.
Fixes #10051
=> haddock-project: added `--all` switch

Cabal/src/Distribution/Simple/GHC.hs
This fixes the DynWay case to match the other cases which take into
account extra-dyn-lib-flavours.
=> copy: Take into account extra-dyn-lib-flavours when copying bundled library

validate.sh
Otherwise CI prints `validate.sh: 332: [[: not found` and the line does nothing (but `validate.sh` continues to run), unless the system shell is `ksh` / `bash` / `zsh`. This may explain https://github.com/haskell/cabal/pull/10114#issuecomment-2178163927.
---
=> fix non-POSIX [[ ]]

buildinfo-reference-generator/buildinfo-reference-generator.cabal, cabal-testsuite/cabal-testsuite.cabal, project-cabal/ghc-latest.config
When updating to GHC 9.10 (https://github.com/haskell/cabal/pull/9914), we had to put a bunch of allow-newer's and pull some patches from head.hackage. This shouldn't be needed after the ecosystem has caught up. This PR shows that the only issue remaining is `rere` (https://github.com/phadej/rere/issues/28).
We didn't apply the bandaids (allow-newer's and head.hackage source repo) unconditionally and instead used `impl(ghc >= 9.10.0)`. Now, we don't remove this stuff, we bump the conditional from 9.10.0 to 9.12.0 anticipating the same procedure for the future (yet unplanned) release of GHC 9.12.
=> CI: don't allow-newer for GHC 9.10

Cabal-syntax/src/Distribution/Types/Dependency.hs
Type `Dependency` is an instance of `Ord`, from `Cabal-syntax-3.10.1.0` following:
* b7afc9709d120c7b90155a29f41366743c61d133
=> Fix Haddock docs for `Distribution.Types.Dependency`

.github/workflows/validate.yml, CONTRIBUTING.md
This slightly changes the `validate.yml` workflow to allow workflow_dispatch without allow-newer or constraints. It is useful when testing CI or various automations.
=> ci(validate.yml): Allow workflow_dispatch with no allow-newer or constraints

doc/cabal-package-description-file.rst, doc/cabal-project-description-file.rst, doc/cabaldomain.py, doc/config.rst
Best to read the documentation online 
- https://cabal--10173.org.readthedocs.build/en/10173/config.html#program-options
- https://cabal--10173.org.readthedocs.build/en/10173/cabal-project-description-file.html#program-options
- The clarification in the `*-options` fields following this one https://cabal--10173.org.readthedocs.build/en/10173/cabal-package-description-file.html#pkg-field-cc-options
=> Document `program-options`

.gitignore, cabal-install/cabal-install.cabal, cabal-install/tests/IntegrationTests2.hs
They were using the user's config, which is a problem if they don't have one or if it contains settings that interfere with tests (such as `documentation: True`).
I'm not entirely certain of this, but it seems to work here. It's a bit of a hack, though.
Closes: #10187 
=> make cabal-install integration tests hermetic

doc/cabal-project-description-file.rst
"older" sounds like it means "earlier" (e.g. 8.2, 8.0 etc.) to me.
=> Fix write-ghc-environment-files documentation

.gitignore, Cabal/src/Distribution/Simple/Configure.hs, Cabal/src/Distribution/Simple/Errors.hs, cabal-testsuite/PackageTests/NoOSSupport/DynExe/Main.hs, cabal-testsuite/PackageTests/NoOSSupport/DynExe/a.cabal, cabal-testsuite/PackageTests/NoOSSupport/DynExe/cabal.out, cabal-testsuite/PackageTests/NoOSSupport/DynExe/cabal.test.hs, cabal-testsuite/PackageTests/NoOSSupport/RelocatableExe/Main.hs, cabal-testsuite/PackageTests/NoOSSupport/RelocatableExe/a.cabal, cabal-testsuite/PackageTests/NoOSSupport/RelocatableExe/cabal.out, cabal-testsuite/PackageTests/NoOSSupport/RelocatableExe/cabal.test.hs, cabal-testsuite/src/Test/Cabal/Prelude.hs, changelog.d/pr-10217
Closes #9807
Trying to build with `--enable-executable-dynamic` will now stop before attempting to compile.
=> Die if dynamic executable is requested on Windows

cabal-install-solver/src/Distribution/Solver/Types/ConstraintSource.hs
Older ghcs don't like it being after the constructor: https://github.com/haskell/cabal/pull/10092#issuecomment-2246287132
(N.B. while this doesn't change interface, it corrects an error in #9900 which very much does.)
=> reorder Haddock markup for dynprof constructor

Cabal-syntax/src/Language/Haskell/Extension.hs, Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs, changelog.d/pr-10245, editors/vim/syntax/cabal.vim
=> Add MultilineStrings extension

cabal-install/tests/UnitTests/Distribution/Solver/Modular/QuickCheck.hs
The solver QuickCheck tests can already detect exceptions, but this test is simpler and easier to debug.
-----------------
This PR doesn't have a corresponding issue because it only adds tests.
-----------------
=> Add simple QuickCheck test for solver exceptions

.github/workflows/validate.yml, cabal-testsuite/cabal-testsuite.cabal
Implement #10175 by fixing cabal version to (for now) 3.12.1.* (originally 3.10.3.0 but that broke tests added post-3.10). We should decide when we should update this and record it and its rationale in the making-a-release wiki page.
=> use fixed cabal version per #10175

.github/workflows/validate.yml
Further investigation of #9571 is needed, but we can take a breathe in the meantime.
=> CI: skip cli-suite on Windows due to #9571

Cabal/src/Distribution/Simple/Program/GHC.hs, changelog.d/pr-10240
These options shouldn't affect the output of the package and hence
shouldn't affect the store hash of a package.
=> Filter out -dinitial-unique and -dunique-increment from hash flags

Cabal/src/Distribution/Simple/Configure.hs, cabal-install/src/Distribution/Client/ProjectPlanning.hs, cabal-testsuite/PackageTests/Regression/T10046/aa.cabal, cabal-testsuite/PackageTests/Regression/T10046/app/Main.hs, cabal-testsuite/PackageTests/Regression/T10046/cabal.project, cabal-testsuite/PackageTests/Regression/T10046/cabal.test.hs, cabal-testsuite/PackageTests/Regression/T10046/src/MyLib.hs, cabal-testsuite/PackageTests/Regression/T10046/test/Main.hs, cabal-testsuite/PackageTests/Regression/T10046/testbb/Main.hs, changelog.d/issue-10046
We were passing the flag --coverage-for for every library in the package when building the testsuites.
However, if a particular testsuite doesn't depend on one of the packages passed with --coverage-for we would crash.
Since we look for the unit ids of all packages given in --coverage-for in the package database (to find hpc artifacts), if the testsuite builds before the library this lookup would fail.
The fix is easy: don't pass --coverage-for=<lib> to <testsuite> if <testsuite> doesn't depend on <lib>. If <lib> is an indirect dependency of <testsuite> it'll no longer be covered by HPC, but this is a weird behaviour that I doubt anyone relies on.
Fixes #10046
Please read [Github PR Conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#github-pull-request-conventions) …
=> hpc: Don't cover non-dependency libraries

.github/mergify.yml, .github/workflows/bootstrap.yml, .github/workflows/users-guide.yml, .github/workflows/validate.yml
Mergify is requiring different queues for different merge strategies as of mid-September.
`actions/upload-artifact@v3` and `actions/download-artifact@v3` are being removed in November.
=> Mergify and actions upgrades

Cabal/src/Distribution/PackageDescription/Check.hs, Cabal/src/Distribution/PackageDescription/Check/Warning.hs, cabal-testsuite/PackageTests/Check/GitProtocol/cabal.out, cabal-testsuite/PackageTests/Check/GitProtocol/cabal.test.hs, cabal-testsuite/PackageTests/Check/GitProtocol/pkg.cabal, changelog.d/pr-10261, doc/cabal-commands.rst
**Manual QA**
1. Go to a local cabal package that has a `source-repository` stanza.
2. In `location:` substitute `https://` (or what you have) with `git://.`
3. New cabal should display a `git:// is not secure` warning.
=> Add git:// protocol check

cabal-install/src/Distribution/Client/Init.hs, cabal-install/src/Distribution/Client/Init/Interactive/Command.hs, cabal-install/src/Distribution/Client/Init/Types.hs, cabal-install/src/Distribution/Client/InstallSymlink.hs, cabal-install/src/Distribution/Client/ProjectBuilding/PackageFileMonitor.hs, cabal-install/tests/UnitTests/Distribution/Client/Init/FileCreators.hs, cabal-install/tests/UnitTests/Distribution/Client/Init/Golden.hs, cabal-install/tests/UnitTests/Distribution/Client/Init/Interactive.hs, cabal-install/tests/UnitTests/Distribution/Client/Init/NonInteractive.hs, cabal-install/tests/UnitTests/Distribution/Client/Init/Simple.hs, changelog.d/pr-10115
Fixes #10096
Call `cabal init` and choose a package build that will end up asking for multiple languages. The last language you choose it should be the default option the next time. This way the user will just need to confirm that the same language is wanted.
```
% cabal init
Warning: The package list for 'hackage.haskell.org' is 24 days old.
Run 'cabal update' to get the latest list of available packages.
What does the package build:
1) Library
* 2) Executable
3) Library and Executable
4) Test suite
Your choice? [default: Executable] 3
...
Choose a language for your library:
* 1) Haskell2010
2) Haskell98
3) GHC2021 (requires at least GHC 9.2)
4) Other (specify)
Your choice? [default: Haskell2010] 3
...
Choose a language for your executable:
1) Haskell2010
2) Haskell98
* 3) GHC2021 …
```
=> Let `cabal init` remember chosen language within current session

cabal-install/src/Distribution/Client/HttpUtils.hs, changelog.d/pr-10089
This PR updates the curl transport to support HTTP Basic authentication scheme.  There are a
couple of preliminary small refactors.  Best review the commits independently and in order.
Targeting branch `3.12` because I couldn't build `master` (GHC panic, don't worry about it).
It rebases cleanly onto `master`.
Ensure that authenticated operations **using username and password** against `hackage.haskell.org` succeed, when using the Curl transport.
=> cabal-install: update curl transport to support Basic authentication

doc/cabal-package-description-file.rst
These can currently be found by searching the documentation for `Paths_pkgname` and `PackageInfo_pkgname`, but you pretty much need to know that to begin with to find them. Add Sphinx index entries to make them more discoverable.
Fixes: #10233
=> index Paths and Paths_ (resp. for PackageInfo)

.github/mergify.yml
We only handled the case of backports previously, but the current release checklist expects that we can commit PRs to release branches during a release (e.g. changelogs, because we want the list of changelog.d files that are actually part of the release).
=> implement mergify rules for release branches

.github/dependabot.yml, .github/workflows/dependabot.yml
Borrowed from Ubuntu
(https://github.com/ubuntu/authd/commit/3f9df8f21d952cd33fd44d3834d0edeec1f5766f)
Sadly, this won't check our existing config unless I make a dummy update.
=> validate dependabot configuration

Cabal-syntax/src/Distribution/Utils/Structured.hs, Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs, cabal-install/tests/UnitTests/Distribution/Client/FileMonitor.hs
In 9.8 the Generic instance for tuples changed (see https://gitlab.haskell.org/ghc/ghc/-/issues/24291) for more details.
Therefore we remove the dependency on the `Generic` instance and the hashes will be invariant across GHC versions (for now).
Fixes #10269
---
=> tests: Make structured hash tests invariant to GHC version

cabal-install/src/Distribution/Client/ProjectConfig.hs, cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs, cabal-install/tests/fixtures/project-root/cabal.project.symlink, cabal-install/tests/fixtures/project-root/cabal.project.symlink.broken, cabal-install/tests/fixtures/project-root/lib/cabal.project.symlink, cabal-install/tests/fixtures/project-root/lib/cabal.project.symlink.broken, changelog.d/pr-10103
This PR modifies [behaviour or interface](https://github.com/cabalism/cabal/blob/master/CONTRIBUTING.md#changelog)**
```bash
cabal build cabal-install
alias patchedCabal=$(cabal list-bin cabal-install)
```
```bash
cd "$(mktemp --directory)"
cabal init --exe --simple
ln -s I-do-not-exist cabal.project
cabal build
```
**Expected behavour:** cabal ignores the broken link and builds the project (ignoring the `cabal.project` and not signaling anything)
Then, slighly adapting the example provided in the issue
```bash
cd "$(mktemp --directory)"
patchedCabal init --exe --simple
ln -s I-do-not-exist cabal.project
patchedCabal build
```
**Expected behavour:**  cabal should exit with status code `1` and should print:
```
The given project file …
```
=> Add check on project root file and fail if broken link

Cabal-tests/Cabal-tests.cabal, Cabal-tests/tests/HackageTests.hs, validate.sh
As a principle, tests which are required for CI to pass should be
reproducible and not depending on external resources changes or being
modified. The hackage tests currently violate this by depending on the
latest index state from hackage. This is problematic because until the
test is fixed all merges into master are blocked. Even though the
patches in question have nothing to do with the test.
It would be more suitable for a nightly job to run on the latest index
and for normal CI to run with a fixed index which is updated
periodically in a controlled manner.
Fixes https://github.com/haskell/cabal/issues/10284
=> ci: Fix --index-state for hackage roundtrip tests

cabal.bootstrap.project, cabal.release.project
Without this, #10202 breaks `cabal.project.release` on ghc 9.10.1.
=> update the pinned index-state to get the new `rere`

.github/mergify.yml
The bot can use this to announce PRs that are entering the 2-day waiting period.
=> add "ready and waiting" Mergify label

.github/workflows/check-sdist.yml
See https://github.com/haskell/cabal/issues/9833
If a ghc ships with a compatible Cabal, it will be preferred by the solver on `cabal install cabal-install`; the new `cabal-install` should in fact be compatible. So we test this on release branches that have been included in at least one GHC release.
Fixes: #9833
Fixes: #9835
Fixes: #9838
Fixes: #9863
CI note: there's really no way to test this, aside from reproducing #9833 for which it's a bit too late. Testing will only be possible with the 9.12 branch and future release branches. As such, manual CI would mean making an sdist of the `HEAD` of `9.12` branch, then trying to build that sdist against 9.10.1 (which is essentially what this does, except that it won't actually do that test until it's backported). Note that that build may well …
=> make sure cabal-install is compatible with Cabal

.github/workflows/validate.yml, cabal-testsuite/PackageTests/Backpack/Includes3/cabal-external.test.hs, validate.sh
This PR disables the 9.0.2 validate job for Windows and provides `--io-manager=native` for every other GHC. See #9571 for the reasons.
=> Re-enable Windows CI

doc/version-control-fields.rst
=> Do not advertise `git://` in docs

validate.sh
Previously, `validate.sh` would assume that all non-Linux and non-Windows builds were x86_64 macOS. ARM64 macOS and Linux machines (and, to an extent, Windows machines) are now quite common. The test suite should work with them.
=> Support ARM / M1 macOS in `validate.sh`

release-notes/Cabal-3.12.0.0.md
As mentioned by e8c9d19, Cabal 3.12 introduced a breaking change where an unnecessary (not requested) component of a package with a "Custom" build-type is no longer built.
This caused breakage for Agda, and was undocumented.
The behaviour, despite breaking, is the desired one -- a package shouldn't assume the executable will be built if only the library was requested. This commit documents the breaking change to make sure it is more visible.
Closes #9777 and #10235
---
Include the …
=> Custom-build: Document breaking change on built comps.

validate.sh
If `nproc` is available and `--jobs` is not given, this will use the output of `nproc` as the value for `--jobs`.
Otherwise, the old default value of 4 will be used and a warning will be printed.
The default value of 4 has remained unchanged since it was added in 6a9a101ca5e1731b9f099a94579a84d2e19667f8 in 2018; that may have been a reasonable number of cores then, but my development machine today has 20 cores, so setting the parallelism to 4 leaves a lot of performance on the table!
=> validate.sh: `--jobs` should default to `nproc`

validate.sh
We were already relying on Bash features like `echo -e`, so let's make it official.
=> `validate.sh`: Use Bash explicitly

.github/workflows/validate.yml, cabal-install/tests/UnitTests/Distribution/Client/VCS.hs
Closes #10312.
Git 2.38.1 and newer fails to clone from local paths with `fatal: transport 'file' not allowed` unless `protocol.file.allow=always` is set.
This is not safe in general, but it's fine in the test suite.
See: https://github.blog/open-source/git/git-security-vulnerabilities-announced/#fn-67904-1
See: https://git-scm.com/docs/git-config#Documentation/git-config.txt-protocolallow
=> Fix `cabal-install:long-tests` with Git >=2.38.1

Cabal-syntax/Cabal-syntax.cabal, Cabal/Cabal.cabal
=> Bump deepseq bounds to allow 1.6

doc/getting-started.rst
See #10324. Add a warning to the user guide to say that scripts cannot be part of a package, as executable mains or other modules.
=> Warn that scripts cannot be package executables

Cabal-QuickCheck/Cabal-QuickCheck.cabal, Cabal-described/Cabal-described.cabal, Cabal-hooks/Cabal-hooks.cabal, Cabal-syntax/Cabal-syntax.cabal, Cabal-tree-diff/Cabal-tree-diff.cabal, Cabal/Cabal.cabal, bootstrap/cabal-bootstrap-gen.cabal, bootstrap/linux-9.0.2.json, bootstrap/linux-9.2.8.json, bootstrap/linux-9.4.8.json, bootstrap/linux-9.6.4.json, bootstrap/linux-9.8.2.json, cabal-install-solver/cabal-install-solver.cabal, cabal-install/cabal-install.cabal, cabal-testsuite/cabal-testsuite.cabal, cabal.bootstrap.project, cabal.release.project, solver-benchmarks/solver-benchmarks.cabal
#10241
https://github.com/haskell/cabal/wiki/Making-a-release#c3-bumping-version-numbers
---
=> [3.14] Bump version numbers to 3.14

cabal-install/src/Distribution/Client/CmdClean.hs, cabal-install/src/Distribution/Client/VCS.hs, cabal-testsuite/PackageTests/NewBuild/CmdClean/CleanSourceRepositoryPackage/a.cabal, cabal-testsuite/PackageTests/NewBuild/CmdClean/CleanSourceRepositoryPackage/cabal.out, cabal-testsuite/PackageTests/NewBuild/CmdClean/CleanSourceRepositoryPackage/cabal.project, cabal-testsuite/PackageTests/NewBuild/CmdClean/CleanSourceRepositoryPackage/cabal.test.hs, changelog.d/pr-10190
Just one commit, the rest are from the base branch #10255. This still doesn't ensure that the directory can be deleted on the first go, but at least a second cabal clean will for sure clean it.
Closes #10182 #6933
Depends-On: #10225 
Very simple, just doing `cabal clean` if there is a `source-repository-package`
```
❯ cat cabal.project
packages: .
source-repository-package
type: git
location: https://github.com/haskell/bytestring
❯ cabal build
Cloning into 'C:\Users\Javier\code\aa\dist-newstyle\src\bytestring-ea6cd2d51c6ca30b'...
...
❯ cabal clean
C:\Users\Javier\code\aa\dist-newstyle\src\bytestring-ea6cd2d51c6ca30b\.git\objects\pack\pack-8793205445310ec514631949079f7ebb57de3771.rev: removeDirectoryRecursive:removeContentsRecursive:removePathRecursive:removeContentsRecursive:removePathRecu …
```
=> Remove read-only mark on `dist-newstyle` when doing `cabal clean` on Windows

doc/cabal-package-description-file.rst
The original PR (#10306) won't backport because the docs were rearranged on `master`.
=> remove references to git protocol

cabal-testsuite/cabal-testsuite.cabal
Forgot to remove the merge label while testing if the cache was interfering with the Windows fix. (Flip side, that _should_ have fixed the cache, I hope.) Remove the `-fforce-recomp` on `cabal-testsuite` that shouldn't have been merged.
=> remove recomp hack

release-notes/Cabal-3.14.0.0.md, release-notes/cabal-install-3.14.0.0.md, release-notes/cabal-install-3.16.0.0.md
Changelogs touch up. Note:
- Original discussions are on #10336.
- Both this and #10336 needs to be forward ported to `master`.
I have divided various suggestions in commits. The one which created a discusson were:
- GHC note
- removing an entry from cabal-install changelogs
=> Changelogs 3.14

Cabal-syntax/src/Language/Haskell/Extension.hs, Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs, editors/vim/syntax/cabal.vim
=> Add OrPatterns extension (backport #10339)

.github/workflows/bootstrap.skip.yml, .github/workflows/bootstrap.yml, .github/workflows/check-sdist.yml, .github/workflows/validate.skip.yml, .github/workflows/validate.yml
We don't mark changelogs as documentation, so CI unnecessarily does full checks when we add changelogs. Correct this.
NOTE: we only accept changelog files from top-level subdirectories. There are changelog files in package tests that must be considered "code" from the standpoint of CI.
=> changelogs are docs

.gitignore
Not sure what's creating these, but they're showing up when I run tests locally.
=> Gitignore `testdb/.../lx-*.lock` files

.github/workflows/validate.yml
This is pretty much a copy of the HEAD pre-release with "lts" added.
=> make LTS branch pre-releases

.github/workflows/whitespace.yml
=> CI: fix-whitespace: show violations (verbose mode)

.github/mergify.yml
This allows us to interrupt the merge queue for high priority PRs. It's using the "priority: high :fire:" label currently.
Fixes: #10352
=> add Mergify config for high priority PRs

.github/workflows/check-sdist.skip.yml, .github/workflows/check-sdist.yml
There's little point in having a skip-on-docs trigger if there's no alternative, cf. the comment in `validate.yml`.
=> add missing sdist skip job

doc/getting-started.rst
=> Add warning and note about cabal init and script

.github/workflows/validate.yml
Let's see if the runner has stabilized yet. Also, fixed the arch issues (validate no longer assumes everything is x86_64).
=> try Apple AArch64 again

CONTRIBUTING.md
The `CONTRIBUTING.md` makes it sound really hard to run tests locally, but actually `validate.sh` works fine!
`validate.sh` still needs work (see the list in #10320) for example, but it's a great starting point.
=> Point out `validate.sh` more prominently in `CONTRIBUTING.md`

.github/workflows/whitespace.yml, CONTRIBUTING.md, Makefile
`make whitespace` now runs `fix-whitespace --check --verbose` and `make fix-whitespace` runs `fix-whitespace --verbose`. You will need to install `fix-whitespace` yourself, but that's just a `cabal install` away.
This is another step in the direction of fixing #10263.
=> add Makefile targets for fix-whitespace

cabal-install/src/Distribution/Client/ProjectBuilding/UnpackedPackage.hs, cabal-install/src/Distribution/Client/Setup.hs
Split off of #10292.
In #10292, we will move the `--keep-temp-files` setting into `CommonSetupFlags` and out of `ReplFlags`/`HaddockFlags`. This means that the flag-filtering behavior (which adapts flags from new versions of `cabal-install` to old version of `Cabal`) will need to know which command is being run to provide the correct `CommonSetupFlags`.
Therefore, this change adds several new `filterFooFlags` functions to provide this behavior, and removes the `commonFlags` used for all subcommands in `Distribution.Client.ProjectBuilding.UnpackedPackage`.
=> Filter `CommonSetupFlags` more consistently in `UnpackedPackage`

Cabal-syntax/src/Distribution/Utils/Generic.hs
The documentation for `Distribution.Utils.Generic.withFileContents` is incorrect:
```
$ cabal repl Cabal-syntax
ghci> import Distribution.Utils.Generic
ghci> withFileContents "README.md" $ \contents -> pure ("foo" `isInfixOf` contents)
*** Exception: README.md: hGetContents: illegal operation (delayed read on closed handle)
```
=> Fix `withFileContents` documentation (lazy IO strikes again)

Cabal-syntax/src/Distribution/Compat/Binary.hs, Cabal-syntax/src/Distribution/Utils/Structured.hs
This future proofs the code for CLC#285, which will remove `ErrorCallWithLocation` to de-duplicate duplicate CallStacks.
ErrorCall is already a pattern synonym with the same meaning as it will have in the future, so this change is backwards compatible too.
=> Prefer ErrorCall to ErrorCallWithLocation

cabal-install/tests/IntegrationTests2.hs
Before, failing asserts in this test would look like this:
```
Writing default configuration to
/Users/wiggles/cabal/cabal-install/tests/IntegrationTests2/config/cabal-config/config
Downloading the latest package list from hackage.haskell.org
Package list of hackage.haskell.org has been updated.
The index-state is set to 2024-09-04T15:12:07Z.
Integration tests (internal)
Flag tests
Test Config options for commented options: FAIL
tests/IntegrationTests2.hs:2015:
expected: "  urll"
but got: "  url"
```
The output includes a message that a configuration file has been written, but that's not the configuration file under test! The actual configuration file being tested is
`cabal-install/tests/IntegrationTests2/config/default-config`, which shows up nowhere in the output.
Now, the messages …
=> Improve assertion messages in `IntegrationTests2` `testConfigOptionComments`

.github/workflows/validate.yml
Matt Pickering says we should always run all tests. This uses `continue-on-error: true` to run them as long as the build succeeded.
=> keep running tests even if earlier ones failed

.github/workflows/validate.yml
I don't believe we need to backport it since cabal-head only concerns `master`. 
Explanation of the changes (based on the docs for the new action):
- title will be the same as tag (cabal-head)
- auth token has a default value that should work, I hope.
=> CI: cabal-head prerelease: move to a current GitHub Action

cabal-testsuite/src/Test/Cabal/Monad.hs, cabal-testsuite/src/Test/Cabal/Run.hs
`System.Process.createPipe` calls (through many intermediaries) `GHC.IO.Handle.FD.fdToHandle`, whose documentation says:
> Makes a binary Handle. This is for historical reasons; it should
> probably be a text Handle with the default encoding and newline
> translation instead.
The documentation for `System.IO.hSetBinaryMode` says:
> This has the same effect as calling `hSetEncoding` with `char8`, together
> with `hSetNewlineMode` with `noNewlineTranslation`.
But this is a lie, and Unicode written to or read from binary handles is always encoded or decoded as Latin-1, which is always the wrong choice.
Therefore, we explicitly set the output to UTF-8 to keep it consistent between platforms and correct on all modern computers.
See: https://gitlab.haskell.org/ghc/ghc/-/issues/25307
---
=> Fix Unicode output in `cabal-testsuite`

Cabal/src/Distribution/Simple/GHC/Build/Link.hs
Per SPJ suggection.
Closes: #10402
=> avoid incomplete record selection warning

.github/workflows/validate.yml, Cabal-syntax/src/Distribution/Utils/Generic.hs, Cabal-tests/tests/UnitTests/Distribution/Simple/Utils.hs, Cabal/src/Distribution/Simple/Configure.hs, Cabal/src/Distribution/Simple/GHC/Internal.hs, Cabal/src/Distribution/Simple/Haddock.hs, Cabal/src/Distribution/Simple/PreProcess.hs, Cabal/src/Distribution/Simple/Program/Ar.hs, Cabal/src/Distribution/Simple/Program/Ld.hs, Cabal/src/Distribution/Simple/Program/ResponseFile.hs, Cabal/src/Distribution/Simple/Utils.hs, cabal-install/src/Distribution/Client/HttpUtils.hs, cabal-testsuite/PackageTests/Backpack/Includes2/cabal-internal.test.hs, cabal-testsuite/PackageTests/Backpack/Includes3/cabal-external.test.hs, cabal-testsuite/PackageTests/Backpack/Includes3/cabal-internal.test.hs, cabal-testsuite/PackageTests/Backpack/T6385/cabal.test.hs, cabal-testsuite/PackageTests/HaddockKeepsTmps/cabal.test.hs
This change ensures all temporal files are created in the system temp directory which usually is in a short path. This helps with Windows not being capable of creating temp files in long directories, like the ones that result from Backpack.
To be precise, purely temporary files (ghc intermediate files, rsps, etc) were already created in this system temporary directory, because the code called `withTempFile` always with the result from `getTemporaryDirectory`. I just made it so that the user doesn't even have the option to provide a different directory now.
And the other case is the `writeFileAtomic` function which used to create temporary files already in the destination directory and then rename them. If the destination directory was a long path, this would fail on Windows. This function …
=> Create temp files in temp directory

cabal-testsuite/PackageTests/HaddockKeepTmpsCustom/Setup.hs, cabal-testsuite/PackageTests/HaddockKeepTmpsCustom/Simple.hs, cabal-testsuite/PackageTests/HaddockKeepTmpsCustom/cabal.project, cabal-testsuite/PackageTests/HaddockKeepTmpsCustom/cabal.test.hs, cabal-testsuite/PackageTests/HaddockKeepTmpsCustom/my.cabal
Split off of https://github.com/haskell/cabal/pull/10292
Thanks to @mpickering for helping with this test case.
Depends-on: #10388
=> Add `haddock --keep-temp-files` test

Cabal/src/Distribution/Simple/GHC/Build.hs, cabal-testsuite/PackageTests/BuildWays/p/CHANGELOG.md, cabal-testsuite/PackageTests/BuildWays/p/p.cabal, cabal-testsuite/PackageTests/BuildWays/p/src/MyLib.hs, cabal-testsuite/PackageTests/BuildWays/q/CHANGELOG.md, cabal-testsuite/PackageTests/BuildWays/q/app/Main.hs, cabal-testsuite/PackageTests/BuildWays/q/q.cabal, cabal-testsuite/PackageTests/BuildWays/setup.test.hs, changelog.d/i10418
In the profiling dynamic patch I made a mistake when computing the needed ways for a build.
When building an executable, the Haskell modules need to be built
* For the final link way
* For the build way of the compiler if TH is enabled
Before this patch, the modules were being built for all the configured library ways, which built modules in more configurations than the previous version of Cabal.
Fixes #10418
---
---
**Template B: This PR does …
=> Cabal: Take into account compilerBuildWay when computing final library ways

CONTRIBUTING.md
Bug copied from `changelog-d`'s `README.md`. A good example of why copying it into `CONTRIBUTING.md` because we can't reference it from there is a bad idea. ☹
=> patchups to `changelog.d` file descriptions

cabal-testsuite/PackageTests/HaddockKeepTmpsCustom/cabal.test.hs, cabal-testsuite/PackageTests/HaddockKeepsTmps/cabal.test.hs, cabal-testsuite/src/Test/Cabal/Monad.hs
The `HaddockKeepTmpsCustom` test added in #10392 skewed against #10366, which changes where temporary files are written.
We can work around this by setting `$TMPDIR` and `$TEMP` while running tests, so that temporary files are written to the test's temporary directory rather than the system one.
=> Fix `HaddockKeepTmpsCustom` test for merge skew

Cabal/src/Distribution/Simple.hs, cabal-testsuite/PackageTests/Install/DistPrefInstall/CHANGELOG.md, cabal-testsuite/PackageTests/Install/DistPrefInstall/DistPrefInstall.cabal, cabal-testsuite/PackageTests/Install/DistPrefInstall/Setup.hs, cabal-testsuite/PackageTests/Install/DistPrefInstall/setup.test.hs, cabal-testsuite/PackageTests/Install/DistPrefInstall/src/MyLib.hs, changelog.d/t10416
Running ./setup install will give you an error:
```
fromFlag NoFlag. Use fromFlagOrDefault
error, called at src/Distribution/Simple/Flag.hs:110:19 in Cabal-3.15.0.0-inplace:Distribution.Simple.Flag
fromFlag, called at src/Distribution/Simple/Register.hs:161:16 in Cabal-3.15.0.0-inplace:Distribution.Simple.Register
```
This seems to not be tested anywhere and most people will use ./setup register in any case, but we should fix this for the next point release in 3.14 series. # Please enter the commit message for your changes. Lines starting
Fixes #10416
---
**Template Α: This PR …
=> Fix ./setup install comand

cabal-install/src/Distribution/Client/Config.hs
This helper function was challenging to understand, so I added an explicit type signature and documentation comments to it.
=> Add type signature and documentation to `toSavedConfig`

Cabal/src/Distribution/Simple/GHC/Build.hs, cabal-testsuite/PackageTests/ProfShared/setup.test.hs
Patches the component build ways for foreign library components.
---
=> Fix build ways for foreign libs

.github/workflows/validate.yml
`validate-old-ghcs` doesn't work on 24.04, which GHA just updated to; and it uses build artifacts from the earlier steps, so for now the whole thing needs to be downgraded to get thinsg working. We must address this properly later.
=> switch validate to 22.04 for now

Cabal/src/Distribution/Simple/Setup/Haddock.hs, cabal-install/src/Distribution/Client/CmdHaddockProject.hs, cabal-install/src/Distribution/Client/Config.hs, cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs, cabal-install/tests/IntegrationTests2.hs
Split off of #10292. This lets `cabal haddock-project` use the standard `CommonFlags` that other commands use to set verbosity and so on.
=> `haddock-project`: add `CommonSetupFlags`

.github/workflows/validate.yml
It's being skipped, not failing to fire, implying the wrong ref? This subsumes #10415.
=> try to fix LTS prerelease workflow

CONTRIBUTING.md, Makefile
by collecting them and adding hlint. Other checks will follow, e.g. API checking once that lands.
Some other things might be added here later, and might lead to revision of various CI jobs. Consider this a start on addressing #10263 properly.
=> round out local Makefile checks

.github/workflows/validate.yml
It doesn't do what we really want, nor really does anything else that isn't an unwieldy-at-best stack of conditions.
=> kill a `continue-on-error`

.github/workflows/validate.yml
Too many backports in the wrong order = mayhem
=> sync `validate.yml` with `master`

.github/mergify.yml
It didn't do what was intended, and apparently Mergify is now tripping over its own feet about it (see #10425). May require manual merge.
This reverts commit d9c2b4093824c7bdf171b3a2113ff41cd09fd0de.
=> Revert "have Mergify insist on all-green CI"

cabal-validate/src/Cli.hs
This lets you add custom arguments to `Tasty` test suites. This can be used to set `--keep-tmp-files` for debugging:
./validate.sh -v -s build -s cli-suite \
--tasty-arg --keep-tmp-files
=> Add `--tasty-arg` to `validate.sh`

.github/mergify.yml
By request in Matrix. If anyone else has an opinion, speak now or forever hold your peace! ☺
The new format is `Backport #NNN: title`, which with GitHub's addenda (which can't be changed) will be
```
[haskell/cabal] Backport #NNN: title (PR #MMM)
```
* ~~[ ] Is this a PR that fixes CI? If so, it will need to be backported to older cabal release branches (ask maintainers for directions).~~ (Mergify only reads this file on `master`.)
=> change the backport label

.github/workflows/check-sdist.yml
=> try to run check-sdist on the right ghcs

doc/cabal-commands.rst
Make clear what is the heuristic we use to find changelogs files.
Towards #10474 
---
=> Clarify cabal check `no-doc` documentation

Cabal/src/Distribution/Simple/Program/GHC.hs, changelog.d/pr-10468
ghc 9.12 adds several new command line options, divided between
`LANGUAGE`s (already added), warnings, new preprocessor control options,
and compilation control options. Two options needed to be added to the
list of options requiring `Int` parameters.
The new options, excluding warning and language options, are:
* `-fexpose-overloaded-unfoldings`
* `-fmax-forced-spec-args=N`
* `-fno-expose-overloaded-unfoldings`
* `-fno-object-determinism`
* `-fobject-determinism`
* `-fwrite-if-compression=N`
* `-optCmmP…`
* `-optJSP…`
* `-pgmCmmP`
* `-pgmJSP`
As they all affect compilation and store hashes, the only necessary
change was to list the two numeric options so they will be parsed
correctly. To the best of our understanding, `-pgm*` and `-opt*`
options are already handled as a group.
**Template …
=> add new options for ghc 9.12

CONTRIBUTING.md
=> Add a note for contributors installing fourmolu

doc/setup-commands.rst
The PR only touches documentation.
Fix #8906.
* [Y] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [N] Is this a PR that fixes CI? If so, it will need to be backported to older cabal release branches (ask maintainers for directions).
The PR docmuments `Setup.hs repl` by reverting the output of `runhaskell Setup.hs repl --help` into rst format.
=> Document `Setup.hs repl`

.github/workflows/validate.yml
I attempted this before, but ended up syncing `validate.yml` with `master` instead which lost it. Trying again.
This is going directly into 3.12 rather than fighting with a pointless merge to `master` with its additional review and delays. Since 3.12 is otherwise not active right now (which, well, no prerelease is part of what makes this safe) I may force-push it away afterward. ~~Or I may convert it into the fix and then make another PR for `master` that won't be backported.~~ whoops, can't do that since it'll already be committed….
=> try to debug the LTS prerelease

Cabal/src/Distribution/Simple/Build/Macros.hs, Cabal/src/Distribution/Simple/Register.hs, Cabal/src/Distribution/Types/ComponentLocalBuildInfo.hs
With ghc-9.12 ghc will complain about the use of the componentCompatPackageKey selector here, this avoids the warning.
=> Fix a incomplete selector warning

.github/workflows/validate.yml
#10497 fizzled because merging didn't trigger the workflow because there were no changes requiring a rebuild.
=> Debug LTS prereleases, take 3

Cabal/src/Distribution/Simple/PreProcess/Types.hs
The example for using the `PreProcessor` is somewhat out of date.  This patch provides the minimal set of changes to the example to match Cabal 3.8.1 or later.
This PR updates documentation only.
=> Update haddock example for recent changes.

Cabal/src/Distribution/Simple/Setup/Repl.hs, changelog.d/pr-10493
**This PR modifies [behaviour or interface](https://github.com/cabalism/cabal/blob/master/CONTRIBUTING.md#changelog)**
Fix #10482
Text provided by `Setup.hs repl --help` contained outdated information concerning sandbox, which have now been removed.
=> Remove text for sandbox in replCommand

cabal-install/src/Distribution/Client/CmdInstall.hs, cabal-testsuite/PackageTests/Install/ProgramAffixes/overwrite-policy.out, cabal-testsuite/PackageTests/Install/ProgramAffixes/overwrite-policy.test.hs
#10290 shows: when checking for existing installations, cabal would not account for an affix (suffix or prefix). So, if you had a `hello` binary installed, installing a second one with a non-empty affix (a perfectly legal operation) would fail.
The reason seemed to be a typo in 09c04e9aca5de2ca391eb859a5b295fdd617f5c6, which passed the arguments to the Symlink structure in a wrong order.
#10476 shows: when failing to install a binary because of an existing one, cabal would report suffix-less existing target even if a suffix was set.
This turned out to be a little issue in pretty printing.
---
I haven't gotten around to adding tests, sadly.
---
Try to check that both #10290 and #10476 don't reproduce with this patch (they both have clear instructions for reproduction).
---
**Template Α: …
=> fix `cabal install --program-suffix/prefix` (fix #10290 and #10476)

.github/mergify.yml
It's on `squash+merge me` but belongs on `merge+no rebase`. Oops!
=> move ncommits check to correct place

.github/workflows/validate.yml
It seems that when we request multiple artifacts at the same time, they are by default placed in their own subdirectories. There's a key to override this; this commit sets it.
Fixes #10515.
=> make sure downloaded artifacts are all in the same dir

cabal-install/src/Distribution/Client/Init/NonInteractive/Heuristics.hs, cabal-install/src/Distribution/Client/Init/Types.hs, cabal-testsuite/PackageTests/Init/init-without-git.out, cabal-testsuite/PackageTests/Init/init-without-git.test.hs, changelog.d/pr-10486
This is a trivial pr that should fix a bug in `cabal init` when `git` is not installed.
---
`cabal init` should work correctly even if `git` is not installed. This can be tested by running the following commands in an empty directory and answering the prompts:
```
mkdir /tmp/bin
ln -s "$(which ghc)" "$(which cabal)" /tmp/bin/
PATH=/tmp/bin/ cabal init
```
=> Catch exception if git is not installed

.github/pull_request_template.md, CONTRIBUTING.md
Add some heuristic to decide which changes are “significant” and a checkbox to remind PR authors to add the tag if appropriate.
We talked about this in the “release post-mortem” meeting. Rewrites and comments welcome.
---
=> Add “Significant change” guideline

cabal-install/cabal-install.cabal, cabal-install/tests/IntegrationTests2.hs, cabal-install/tests/IntegrationTests2/CPP.hs
Move CPP definitions into a separate module so that Fourmolu can work its magic.
=> Format `IntegrationTests2`

cabal-install/src/Distribution/Client/IndexUtils.hs, cabal-testsuite/PackageTests/Get/T7248/cabal.out
Cherry picked https://github.com/MercuryTechnologies/cabal/commit/ec242b1cb21e450d5212efd5c445f0d70786092e
Would be great to have a test...
---
=> Don't error if package index is missing (fix #10504)

cabal-testsuite/README.md, cabal-testsuite/cabal-testsuite.cabal, cabal-testsuite/main/cabal-tests.hs
This adds the `Tasty` `-p`/`--pattern` argument to the `cabal-testsuite` tests, making it possible to filter `cabal-testsuite` tests just like the other test suites:
./validate.sh -s build -s cli-suite -p HaddockKeepTmpsCustom
See also: #10428
=> Make `cabal-testsuite` filterable with `--pattern`

cabal-testsuite/PackageTests/ConditionalAndImport/cabal.out, cabal-testsuite/PackageTests/ConditionalAndImport/cabal.test.hs, cabal-testsuite/PackageTests/ConditionalAndImport/yops-0.project, cabal-testsuite/PackageTests/ConditionalAndImport/yops-2.config, cabal-testsuite/PackageTests/ConditionalAndImport/yops-4.config, cabal-testsuite/PackageTests/ConditionalAndImport/yops-6.config, cabal-testsuite/PackageTests/ConditionalAndImport/yops-8.config, cabal-testsuite/PackageTests/ConditionalAndImport/yops/yops-1.config, cabal-testsuite/PackageTests/ConditionalAndImport/yops/yops-3.config, cabal-testsuite/PackageTests/ConditionalAndImport/yops/yops-5.config, cabal-testsuite/PackageTests/ConditionalAndImport/yops/yops-7.config, cabal-testsuite/PackageTests/ConditionalAndImport/yops/yops-9.config
Split from #9933, this adds just the project used for that pull request's test without adding any test or behaviour change in cabal.
=> Add Y-forking import project

cabal-install-solver/src/Distribution/Solver/Types/ProjectConfigPath.hs, cabal-install/src/Distribution/Client/ProjectConfig.hs, cabal-install/src/Distribution/Client/ProjectPlanning.hs, cabal-testsuite/PackageTests/ConditionalAndImport/cabal.out, cabal-testsuite/PackageTests/NewConfigure/LocalConfigOverwrite/cabal.out, cabal-testsuite/PackageTests/NewFreeze/BuildTools/new_freeze.out, cabal-testsuite/PackageTests/NewFreeze/Flags/new_freeze.out, cabal-testsuite/PackageTests/NewFreeze/FreezeFile/new_freeze.out, cabal-testsuite/PackageTests/Path/Config/cabal.out, cabal-testsuite/PackageTests/RelativePathProjectImports/cabal.out, cabal-testsuite/PackageTests/VersionPriority/1-local.out, cabal-testsuite/PackageTests/VersionPriority/1-web.out, cabal-testsuite/PackageTests/VersionPriority/2-local.out, cabal-testsuite/PackageTests/VersionPriority/2-web.out, cabal-testsuite/PackageTests/VersionPriority/3-web.out
fix #10547 by printing the project config info to stderr. 
Also, report only top-level project configs with the default verbosity. Otherwise, imported config files can still be seen in the verbose mode.
Try to reproduce  #10547
---
* [N/A] This fixes code that has not been released yet. ~~Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#changelog).~~
=> Print info about current project file in use to stderr and ignore the imports by default

cabal-install/src/Distribution/Client/CmdPath.hs, doc/cabal-commands.rst
Minor, regenerate `cabal help` output in command docs.
=> Regen cabal help after #9583

Cabal/src/Distribution/Simple/Utils.hs
=> Typo, Warning not Waring

cabal-install/src/Distribution/Client/Main.hs, changelog.d/pr-10549
Just adding a warning seems like a good enough solution for now as we don't seem to want to deprecate the command. I think this doesn't deserve a changelog or update to the docs.
---
=> Warn on cabal format invocation

.github/mergify.yml
The problem with it turns out to be that you get no warning at all if it's waiting to be manually rebased; you have to inspect the Mergify state to find out. At least with the old behavior you got an error when Mergify tried to rebase it, and you knew why.
=> end the `#commits-behind=0` experiment

cabal-validate/src/Cli.hs
Add `./validate.sh --no-hide-successes`, which causes the test suites to print out tests that are run when they succeed. This significantly increases visibility into which tests are running.
NB: Maybe we should have `--no-default-tasty-args` or something...?
=> cabal-validate: --no-hide-successes

cabal-install/src/Distribution/Client/ParseUtils.hs, cabal-install/src/Distribution/Deprecated/ParseUtils.hs, cabal-testsuite/PackageTests/ProjectConfig/FieldStanzaConfusion/cabal.out, cabal-testsuite/PackageTests/ProjectConfig/FieldStanzaConfusion/cabal.project, cabal-testsuite/PackageTests/ProjectConfig/FieldStanzaConfusion/cabal.test.hs, cabal-testsuite/PackageTests/ProjectConfig/FieldStanzaConfusion/src/MyLib.hs, cabal-testsuite/PackageTests/ProjectConfig/FieldStanzaConfusion/test.cabal, changelog.d/pr-10525
Here's a mistake I make semi-regularly:
source-repository-package:
type: git
location: https://github.com/parsonsmatt/foundation
tag: 688c32ccd9a951bc96dd09423a6e6684f091d510
subdir: basement
subdir: foundation
Cabal treats this as a warning, so it prints:
Warning: cabal.project: Unrecognized field
'source-repository-package' on line 52
This is fine (if you already know the mistake you've made, at least!), but it's very easy to miss amidst lots of output.
I often re-run `cabal` when I see a ton of output to attempt to get a smaller error message. (Usually it works and I get an error message that's got less "compiling module such and such" noise in it.) However, re-running `cabal` will discard this warning entirely!
Let's make it a hard error instead. This is a backwards-compatibility …
=> Make a trailing colon for stanzas a parse failure

Makefile
Fixes #10583, adding `PHONY` rules for `lint` and `lint-json`.
=> Add PHONY rules for lint and lint-json

doc/cabal-package-description-file.rst, doc/cabal-project-description-file.rst, doc/vcs/branch.rst, doc/vcs/fields.rst, doc/vcs/kind.rst, doc/vcs/location.rst, doc/vcs/subdir.rst, doc/vcs/tag.rst, doc/version-control-fields.rst
Duplicate the VCS content by include reuse, avoiding copy and paste, as I suggested in https://github.com/haskell/cabal/pull/10543#issuecomment-2471095352.
Both package and project pages have content for version control system (VCS) fields.
> [!NOTE]
> With #9701 I'd moved VCS field content to its own page, ["Version Control System Fields"](https://cabal.readthedocs.io/en/latest/version-control-fields.html) page. This PR doesn't change that, neither in the table of contents or how that page is rendered.
I am proposing this change, to create a folder for these includes and in that put `*.rst` snippet content for `.. include::` inclusion by other pages. I duplicate the VCS field content, as it exists now, within both package and project pages and retain the "Version Control System Fields" …
=> Duplicate VCS content

doc/cabal-commands.rst
Minor, typos in [cabal check warnings](https://cabal.readthedocs.io/en/latest/cabal-commands.html#cabal-check).
=> Typo prexif, reseved and unmatched (

cabal-install/tests/UnitTests/Distribution/Client/VCS.hs
Add the following environment variables to `git` invocations in tests:
```bash
export HOME="$TMPDIR/home"
export GIT_CONFIG_NOSYSTEM=1
export GIT_CONFIG_GLOBAL="$HOME/.gitconfig"
export GIT_AUTHOR_DATE=1998-04-30T18:25:03-0400
export GIT_COMMITTER_DATE=1998-04-30T18:25:00-0400
```
Write the following `.gitconfig`:
```
[protocol.file]
allow = always
[user]
name = Puppy Doggy
email = puppy.doggy@example.com
```
=> Make Git deterministic in `UnitTests.Distribution.Client.VCS`

Cabal-syntax/src/Distribution/Fields/Lexer.x
=> Don't use redundant alias Prelude as Prelude

cabal-validate/src/Main.hs
The `cli-tests` are supposed to be ordered so that the quickest ones run first. This is not the case, at least on my machine!
=> cabal-validate: Reorder cli-tests

cabal-install/tests/UnitTests/Distribution/Client/VCS.hs
The `Arbitrary` repo recipes can get quite large due to nesting:
- `RepoRecipes` contain a number of groups (`TaggedCommits` or `BranchCommits`).
- Groups contain a number of `Commit`s.
- Commits contain a number of operations (`FileUpdate` or `SubmoduleAdd`).
There's also another wrinkle in that `SubmoduleAdd`s contain a `Commit` themselves, so square the `operationsPerCommit` number!
Then, a rough upper bound of the number of `git` calls required for an arbitrary `RepoRecipe` is
`groupsPerRecipe * commitsPerGroup * operationsPerCommit^2`.
The original implementation of these instances, which chose reasonable-sounding size parameters of 5-15, led to a maximum of 1875 operations per test case! No wonder they took so long!
In my tests, this change reduces the time of running the …
=> VCS tests: Make smaller `Arbitrary` repositories to speed up `long-tests` 4.2x

.github/workflows/typos.yml, .typos.toml, Cabal/ChangeLog.md, Makefile, README.md, doc/README.md, doc/cabal-commands.rst, doc/cabal-package-description-file.rst, doc/file-format-changelog.rst, doc/getting-started.rst, doc/how-to-use-backpack.rst, release-notes/Cabal-3.10.1.0.md, release-notes/Cabal-3.12.0.0.md, release-notes/cabal-install-3.10.3.0.md, release-notes/cabal-install-3.12.1.0.md
Fix #10601. Adds spell checking (finding typos) and fixing makefile targets with recipes using [typos](https://github.com/crate-ci/typos) and an GitHub action that uses the makefile target (even though there is a canned action available for this).
Limited at the moment to checking and fixing spelling in `*.rst` files (and `*.md` files - requested at review). No configuration is required as yet. The default configuration can be viewed with `typos --dump-config -`.
Fixes the typos that `make typos` found with `make fix-typos` except for the one with an ambiguous fix that I fixed by hand.
---
=> Add typo checking for *.rst and *.md files

cabal-install/src/Distribution/Client/Init/Defaults.hs, changelog.d/pr-9890
Lack of explicit export list can degrade performance. The Main module in particular should always have an explicit export list that contains just the main function.
Fixes #9889 
---
=> Explicit export lists for Main

cabal-install/src/Distribution/Client/VCS.hs, cabal-install/tests/UnitTests/Distribution/Client/VCS.hs, changelog.d/pr-10587
This prevents the tests from spamming lots of output, making it easier to watch them as they run.
Before:
```
check VCS test framework:                                                 10% warning: refname 'd6077f476a7c17fe8528e62688a19cc5bddbfbdc' is ambiguous.
Git normally never creates a ref that ends with 40 hex characters
because it will be ignored when you just specify 40-hex. These refs
may be created by mistake. For example,
git switch -c $br $(git rev-parse ...)
where "$br" is somehow empty and a 40-hex ref is created. Please
examine these refs and maybe delete them. Turn this message off by
running "git config advice.objectNameWarning false"
rm 'file/C'
Cloning into '/private/var/folders/z5/fclwwdms3r1gq4k4p3pkvvc00000gn/T/vcstest-64269/src/file/C'...
done.
Submodule path …
```
=> VCS tests: Quieter output

Makefile
Fix #10596. Add help for some of the makefile targets.
```
$ make help
all                            Build the Cabal libraries and cabal-install executables.
checks                         Run all local checks; whitespace, style, and lint.
doctest-install                Install doctest tool needed for running doctests.
doctest                        Run doctests.
exe                            Builds the cabal-install executables.
fix-whitespace                 Run fix-whitespace in fix mode.
ghcid-cli                      Run ghcid for the cabal-install executable.
ghcid-lib                      Run ghcid for the Cabal library.
help-banner                    Show the help banner.
help                           Show the commented targets.
init                           Set up git hooks …
```
=> Add help target to the makefile

Cabal-hooks/Cabal-hooks.cabal, Cabal-hooks/changelog.md, Cabal-hooks/src/Distribution/Simple/SetupHooks.hs, bootstrap/linux-9.0.2.json, bootstrap/linux-9.2.8.json, bootstrap/linux-9.4.8.json, bootstrap/linux-9.6.4.json, bootstrap/linux-9.8.2.json, cabal-testsuite/main/cabal-tests.hs
This PR targets the Cabal 3.14 branch.
As pointed out in #10412, it isn't currently feasible to version the Cabal-hooks version separately from Cabal due to the large amount of re-exports (in particular the LocalBuildInfo type and its dependencies).
For the time being, we version Cabal-hooks along with the major Cabal library version.
Companion to #10580.
=> 3.14: make Cabal-hooks version track Cabal version

Cabal/src/Distribution/Simple/Program/Run.hs, cabal-install/src/Distribution/Client/VCS.hs, cabal-install/tests/UnitTests/Distribution/Client/VCS.hs, changelog.d/pr-10590
Running `git submodule` commands is harmless but clutters up the logs, making the tests difficult to debug when run in verbose-mode.
Doesn't seem to impact performance much. I measured a ~1.5% speedup with this code, which is well within error margins.
See: https://github.com/haskell/cabal/pull/7625/files#r709617991
=> VCS: Don't run submodule commands unless necessary

Cabal/src/Distribution/Simple/Program/Strip.hs, changelog.d/pr-10616
Brought to our attention by maerwald; see https://cvsweb.openbsd.org/cgi-bin/cvsweb/~checkout~/ports/lang/ghc/patches/patch-libraries_Cabal_Cabal_Distribution_Simple_Program_Strip_hs.
=> OpenBSD `--strip-unneeded` strips too much

.hlint.yaml
For #10560, configure `hlint` to ignore `dist-*` folders. Also bump the `hlint` warnings counts (they're getting worse).
---
=> Have hlint ignore dist-*

cabal-install-solver/src/Distribution/Solver/Types/ProjectConfigPath.hs
Fixes #10628. Follow on from #9578. The haddocks are not rendering well. Some `@` blocks should have been laid out as-is. Haddock literal text `>` does that.
To test, run `cabal haddock cabal-install-solver` and check the rendering. I'm looking at `file:///.../cabal/dist-newstyle/build/x86_64-linux/ghc-9.10.1/cabal-install-solver-3.15.0.0/doc/html/cabal-install-solver/Distribution-Solver-Types-ProjectConfigPath.html`
---
=> `ProjectConfigPath` use haddock literal text for layout

Cabal-tests/tests/UnitTests/Distribution/Simple/Glob.hs, Cabal/src/Distribution/Simple/Glob.hs, cabal-testsuite/PackageTests/Check/ConfiguredPackage/Paths/AbsolutePath/cabal.out
This PR is a less invasive variant of #10502 which moves the special treatment of glob patterns into `runDirFileGlob` directly. Locally, I'm observing a comparable performance improvement to that PR: #10502 takes about 150ms, and this one takes about 250ms.
---
=> Don't Glob if Glob Ain't Glob 2: The Globbening

.github/workflows/validate.yml, cabal-validate/src/Cli.hs, cabal-validate/src/Main.hs, cabal-validate/src/ProcessUtil.hs, cabal-validate/src/Step.hs
Closes #10569
Closes #10570
A new `--quiet` switch has been added, and some behavior in `./validate.sh` (without `--verbose`) has been moved into `--quiet` mode:
- `--hide-successes` will be passed to test suites in `--quiet` mode, making it easier to track tests as they run
- Subprocess output is only captured in `--quiet` mode, making it easier to watch `cabal build` and test suite output
Some output has been hidden unless `--verbose` is used:
- The build plan (listing of all local packages and transitive dependencies) and the dry-run build used to produce the build plan are skipped unless `--verbose` is given
- The runtime configuration (e.g. the `ghc` and `cabal-install` executables being used) and tool versions are not printed unless `--verbose` is given
Additionally, `print-config`, …
=> `cabal-validate`: Better output verbosity defaults 

cabal-install-solver/src/Distribution/Solver/Types/ProjectConfigPath.hs, cabal-install/src/Distribution/Client/ProjectConfig.hs, cabal-testsuite/PackageTests/ConditionalAndImport/cabal.out, cabal-testsuite/PackageTests/ConditionalAndImport/with-ghc.config, cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/0.config, cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/2.config, cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/4.config, cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/6.config, cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/8.config, cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/cabal.out, cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/cabal.test.hs, cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/cfg/1.config, cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/cfg/3.config, cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/cfg/5.config, cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/cfg/7.config, cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/cfg/9.config, cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/no-pkg-1/README.md, cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/no-pkg-3/README.md, cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/no-pkgs.project, cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/with-ghc.config, cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromSimple/a-very-extra.config, cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromSimple/an-extra.config, cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromSimple/cabal.out, cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromSimple/cabal.project, cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromSimple/cabal.test.hs, cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromSimple/with-ghc.config, cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromSimple/z-empty.config, changelog.d/pr-10546
Adds an `Ord` instance for `ProjectConfigPath` and fixes the duplication in the reported "Configuration is affected by the following files", fixes #10509 by using `docProjectConfigFiles` instead of `docProjectConfigPath`.
=> Deduplicate "using config from" message

Cabal/src/Distribution/Simple/Haddock.hs, cabal-install/src/Distribution/Client/CmdHaddock.hs, changelog.d/pr-10637
Fixes #10636
This PR fixes the linked issue by making the stylesheet path absolute before passing it to Haddock, and also passing the stylesheet to the index generator as well.
Calling `cabal haddock-project --css=<css-file>` on a multi-package project where every package has its own subdirectory (and not have their source files at the _project_ root) should produce documentation such that:
- The index (i.e. `./haddocks/index.html`) is styled by the provided CSS file
- Each package has their docs (i.e. `./haddocs/<package>/<module>.html`) styled by the provided CSS file
[This reproducer](https://github.com/ozkutuk/cabal-multi-css-repro) of the original issue can be used for QA purposes. 
---
**Template Α: This PR modifies [behaviour or …
=> Fix multi-package Haddock CSS handling

changelog.d/pr-10546
=> Fix whitespace issue in changelog

.github/mergify.yml
Add a label "waiting too long" if a PR has "merge delay passed" but is still open without any activity. Somewhat hacky, since GitHub's API doesn't provide any real hooks for it so I'm guessing at ways to try to catch it. Can only be tested by merging, since Mergify won't apply it unless it's on `master`.
=> try to alert (via webhook) when Mergify is stuck

Cabal-hooks/Cabal-hooks.cabal, Cabal-hooks/changelog.md, Cabal-hooks/readme.md, Cabal-hooks/src/Distribution/Simple/SetupHooks.hs, bootstrap/linux-9.0.2.json, bootstrap/linux-9.2.8.json, bootstrap/linux-9.4.8.json, bootstrap/linux-9.6.4.json, bootstrap/linux-9.8.2.json, cabal-testsuite/main/cabal-tests.hs
This PR targets the Cabal master branch.
As pointed out in https://github.com/haskell/cabal/issues/10412, it isn't currently feasible to version the Cabal-hooks version separately from Cabal due to the large amount of re-exports (in particular the LocalBuildInfo type and its dependencies).
For the time being, we version Cabal-hooks along with the major Cabal library version.
Companion to #10579.
=> Master: make Cabal-hooks version track Cabal version

cabal-install-solver/src/Distribution/Solver/Types/ConstraintSource.hs, cabal-install-solver/src/Distribution/Solver/Types/PackageConstraint.hs, cabal-install/src/Distribution/Client/Targets.hs
We have a lot of `showType` functions that are effectively a `Pretty` instance but less composable. Let's make them proper `Pretty` instances.
Split off of #10524
=> Convert display functions into `Pretty` instances

.github/workflows/validate.yml
This PR is https://github.com/haskell/cabal/pull/10540 rebased.
It should fix https://github.com/haskell/cabal/issues/10537 and its duplicate https://github.com/haskell/cabal/issues/10652
----
* [n/a] Is this a PR that fixes CI? If so, it will need to be backported to older cabal release branches (ask maintainers for directions).
=> CI: remove cabal-head before updating it (fix #10537)

Cabal/src/Distribution/Simple/GHC.hs
I'm trying out `-XMultilineStrings` in `cabal-testsuite` and struck this warning, having installed `ghc-9.12.1` with ghcup:
```
+Warning: Unknown/unsupported 'ghc' version detected (Cabal 3.15.0.0 supports 'ghc' version < 9.12):
/.../.ghcup/bin/ghc is version <GHCVER>
```
This pull request is the same as #9928 (that adds support for `ghc-9.10.*`) but bumps the GHC version once more.
---
=> Support `ghc-9.12.*`

Cabal/Cabal.cabal, Cabal/src/Distribution/Simple/Utils.hs, cabal-install/cabal-install.cabal, cabal-install/src/Distribution/Client/Main.hs, cabal-install/src/Distribution/Client/Version.hs, cabal.project, cabal.release.project, cabal.validate.project
`cabal --version` in such builds will include the Git commit and branch (if not `master`).
I've already been informed that this is not appropriate, but maybe someone will find something worth salvaging in it. It is also incomplete insofar as it needs a changelog entry and such (but probably not a test).
Consider this my last submission.
=> record Git revision in devel builds

Cabal/src/Distribution/Simple/GHC.hs
This has been requested in the past: https://github.com/haskell/cabal/pull/8666#issue-1531294842
---
=> Minor refactor: spell out max supported GHC once

Cabal/src/Distribution/Simple/Configure.hs, cabal-install-solver/src/Distribution/Solver/Types/ProjectConfigPath.hs, cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs, cabal-testsuite/PackageTests/ProjectImport/UntrimmedImport/cabal.out, cabal-testsuite/PackageTests/ProjectImport/UntrimmedImport/cabal.test.hs, cabal-testsuite/PackageTests/ProjectImport/UntrimmedImport/my.cabal, cabal-testsuite/PackageTests/ProjectImport/UntrimmedImport/tabs-and-spaces.project, cabal-testsuite/PackageTests/ProjectImport/UntrimmedImport/trailing-space.project, cabal-testsuite/PackageTests/ProjectImport/UntrimmedImport/with-ghc.config, changelog.d/pr-10629, fix-whitespace.yaml
Fixes #10622. Trims URIs before parsing them with `parseURI`. If any project config path doesn't equal its trimmed self then it is displayed quoted so that the whitespace is obvious.
---
=> Have projects import trimmed URIs

Cabal/Cabal.cabal, bootstrap/linux-9.0.2.json, bootstrap/linux-9.2.8.json, bootstrap/linux-9.4.8.json, bootstrap/linux-9.6.6.json, bootstrap/linux-9.8.2.json, cabal-install/cabal-install.cabal, cabal.bootstrap.project, cabal.release.project
Patching `cabal.release.project` still allows the buggy `unix` release to be installed via Hackage.
=> fix unix dependency correctly

cabal-install/src/Distribution/Client/Errors.hs, cabal-install/src/Distribution/Client/IndexUtils.hs, cabal-install/src/Distribution/Client/ProjectConfig.hs, cabal-testsuite/PackageTests/BuildTargets/UseLocalPackageForSetup/pkg/pkg.cabal, cabal-testsuite/PackageTests/BuildTargets/UseLocalPackageForSetup/repo/setup-dep-1.0/setup-dep.cabal, cabal-testsuite/PackageTests/BuildTargets/UseLocalPackageForSetup/setup-dep/setup-dep.cabal, cabal-testsuite/PackageTests/IndexCabalFileParseError/cabal.out, cabal-testsuite/PackageTests/IndexCabalFileParseError/cabal.test.hs, cabal-testsuite/PackageTests/IndexCabalFileParseError/repo/my-lib-1.0/my-lib.cabal, cabal-testsuite/PackageTests/NewBuild/CmdRun/Script/cabal.out, cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptBad/cabal.out, cabal-testsuite/PackageTests/NewBuild/CmdRun/ScriptLiterate/cabal.out, cabal-testsuite/PackageTests/NewConfigure/ConfigFile/cabal.out, cabal-testsuite/PackageTests/NewFreeze/BuildTools/new_freeze.out, cabal-testsuite/PackageTests/Regression/T7234/Fail/cabal.out, cabal-testsuite/PackageTests/Regression/T7234/Success/cabal.out, cabal-testsuite/PackageTests/Regression/T9640/cabal.out, cabal-testsuite/src/Test/Cabal/OutputNormalizer.hs, cabal-testsuite/src/Test/Cabal/Prelude.hs, changelog.d/pr-10647
This error message was very confusing -- it doesn't tell you what `.cabal` file it's looking for or why it cannot read the `.cabal` file. (Did it fail to parse the `.tar` archive itself? Did parsing the `.cabal` file fail? If so, why?)
This patch improves the error message to include the name of the `.cabal` file being searched for. Additionally, parse errors and warnings are printed, as are format failures in the tarball itself.
I ran into this error while I was writing tests for Cabal and it confused the hell out of me; this is an expanded version of the changes I made to help debug that failure.
Before:
```
Error: [Cabal-7046]
Cannot read .cabal file inside my-lib-1.0.tar.gz
```
After:
```
Error: In <ROOT>/cabal.dist/repo/my-lib-1.0.tar.gz: Errors encountered when parsing cabal file …
```
=> Improve "Cannot read .cabal file inside ..." errors

doc/cabal-commands.rst
Fixes #10698, a follow on from #9583.
---
=> Move cabal path to project configuration group

CONTRIBUTING.md, cabal-install-solver/src/Distribution/Solver/Types/ProjectConfigPath.hs, cabal-testsuite/PackageTests/BuildDeps/InternalLibrary2/setup.test.hs, cabal-testsuite/PackageTests/BuildDeps/InternalLibrary3/setup.test.hs, cabal-testsuite/PackageTests/CheckSetup/setup.test.hs, cabal-testsuite/PackageTests/ConditionalAndImport/cabal-missing-package.expect.txt, cabal-testsuite/PackageTests/ConditionalAndImport/cabal.test.hs, cabal-testsuite/PackageTests/ConditionalAndImport/hops.expect.txt, cabal-testsuite/PackageTests/ConditionalAndImport/oops.expect.txt, cabal-testsuite/PackageTests/NewBuild/T4288/cabal.test.hs, cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/cabal.out, cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/cabal.test.hs, cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/errors.expect.txt, cabal-testsuite/PackageTests/ProjectImport/ParseErrorProvenance/cabal.out, cabal-testsuite/PackageTests/ProjectImport/ParseErrorProvenance/cabal.test.hs, cabal-testsuite/PackageTests/ProjectImport/ParseErrorProvenance/dir-else/else.config, cabal-testsuite/PackageTests/ProjectImport/ParseErrorProvenance/else.project, cabal-testsuite/PackageTests/ProjectImport/ParseErrorProvenance/msg.expect.txt, cabal-testsuite/PackageTests/Regression/T5409/use-different-versions-of-dependency-for-library-and-build-tool.test.hs, cabal-testsuite/README.md, cabal-testsuite/cabal-testsuite.cabal, cabal-testsuite/src/Test/Cabal/NeedleHaystack.hs, cabal-testsuite/src/Test/Cabal/Prelude.hs, changelog.d/pr-10646.md
Fixes #10645, a small Windows gotcha missed with #10546.
I really had to get into the weeds with this one. The `assertOutputContains` function was modifying the output (a test actual value) before comparision with the unmodified actual value. This change was not visible. I've added an `assertOn` function (that `assertOutputContains` calls) that takes a `NeedleHaystack` configuration for how the search, expectation and display are made. I had wanted to add a pilcrow `¶` for line endings but the terminal output is restricted to ASCII so I've marked line beginnings with `^` and line endings with `$`. The needle (the expected output fragment) is shown annotated this way as can the haystack (the output). The haystack is not shown annotated with line delimiters but can be.
The `concatOutput` …
=> Deduplicate path separator duplicates

Cabal-syntax/src/Distribution/Compiler.hs
=> Add since annotation for MHS

.hlint.yaml, Cabal/src/Distribution/Compat/Internal/TempFile.hs, Cabal/src/Distribution/Compat/Time.hs, Cabal/src/Distribution/Simple/GHC.hs, cabal-install/src/Distribution/Client/CmdTest.hs, cabal-install/src/Distribution/Client/Config.hs, cabal-install/src/Distribution/Client/ProjectPlanning.hs, cabal-install/src/Distribution/Client/SetupWrapper.hs, cabal-install/src/Distribution/Client/Store.hs, cabal-install/tests/IntegrationTests2.hs, cabal-testsuite/src/Test/Cabal/Monad.hs, cabal-testsuite/src/Test/Cabal/NeedleHaystack.hs
See #9110. The HLint "use fewer imports" suggestion was too much trouble to enable before most of the base CPP conditionals, "base 4.13 and older", were removed in #10092.
We're using fourmolu but this doesn't merge multiple imports from the same module.
The removal of `MIN_VERSION_base(4,11,0)` is permitted by https://github.com/haskell/cabal/issues/8998#issuecomment-2564815577 and https://github.com/haskell/cabal/issues/8998#issuecomment-2565296765.
Two files used for our tests taken from other projects are now ignored for linting, in `.hlint.yaml`:
```diff
- arguments:
+    - --ignore-glob=Cabal-tests/tests/custom-setup/CabalDoctestSetup.hs
+    - --ignore-glob=Cabal-tests/tests/custom-setup/IdrisSetup.hs
```
The first of these, `CabalDoctestSetup.hs`, was mentioned by @Kleidukos in …
=> Follow HLint suggestion: use fewer imports

.gitignore
I tried the `cabal haddock-project` command. It dumped thousands of untracked files into the source tree for haskell/cabal. This PR ignores that folder.
```
$ tree haddocks
haddocks
├── array
│   ├── array.haddock
│   ├── array.txt
│   ├── Data-Array-Base.html
...
├── synopsis.png
├── transformers.haddock
└── transformers.txt
67 directories, 3487 files
```
There's the `--output[=DIRECTORY]` option but `haddocks` is the default directory for the output.
```
$ cabal haddock-project --help
Generate Haddocks HTML documentation for the cabal project.
Usage: cabal haddock-project [FLAGS]
or: cabal haddock-project COMPONENTS [FLAGS]
Flags for haddock-project:
...
--output[=DIRECTORY]           Output directory
...
```
---
*E.g. the …
=> Ignore haddocks

Cabal-syntax/src/Distribution/Utils/Path.hs, Makefile, cabal-install/src/Distribution/Client/Config.hs, cabal-install/src/Distribution/Client/GlobalFlags.hs, cabal-install/src/Distribution/Client/IndexUtils.hs, cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs, cabal-install/tests/UnitTests/Distribution/Client/ProjectConfig.hs, cabal-testsuite/src/Test/Cabal/OutputNormalizer.hs, cabal-testsuite/src/Test/Cabal/Prelude.hs, changelog.d/pr-10728, doc/config.rst
This PR fixes the parsing of URIs for file+noindex repositories when using Windows paths. As suggested by @phadej in #10703 we now use (and specify in the docs) `//./C:/...` paths on Windows.
In Windows, one can now specify `//./` paths in file+noindex repositories. To check, create a simple package, then `cabal sdist`, move the tar.gz to some directory and in a different project declare the following stanza:
```
repository my-local-repo
url: file+noindex:////./C:/path/to/repo
```
It might still fail because of https://github.com/haskell/cabal/issues/9891
---
=> Fix file+noindex URI usage on Windows

Cabal/src/Distribution/Compat/Environment.hs, Cabal/src/Distribution/Simple/Build/PathsModule.hs, Cabal/src/Distribution/Simple/Build/PathsModule/Z.hs, cabal-dev-scripts/src/GenPathsModule.hs, cabal-install/src/Distribution/Client/Compat/ExecutablePath.hs, changelog.d/pr-10705, templates/Paths_pkg.template.hs
See details: https://gitlab.haskell.org/ghc/ghc/-/issues/24603#note_565835
The patch adds support Aarch64 builds at Windows platform.
---
**Asking for an exemption** for tests.
I am not sure about `QA notes`. Should I add a link to the compiler which can be used to test it? Temporal link is [here](https://gitlab.haskell.org/ghc/ghc/-/issues/24603#note_602054).
=> Add support for Windows Aarch64

.typos.toml, Cabal-described/src/Distribution/Described.hs, Cabal-described/src/Distribution/Utils/CharSet.hs, Cabal-described/src/Distribution/Utils/GrammarRegex.hs, buildinfo-reference-generator/src/Main.hs, buildinfo-reference-generator/template.zinza, doc/buildinfo-fields-reference.rst, doc/cabal-package-description-file.rst, doc/package-concepts.rst
=> Fix #9507 Describe accurately acceptable package names

cabal-install/cabal-install.cabal, cabal-install/src/Distribution/Client/CmdTarget.hs, cabal-install/src/Distribution/Client/Main.hs, cabal-install/src/Distribution/Client/ProjectOrchestration.hs, cabal-install/src/Distribution/Client/Setup.hs, cabal-testsuite/PackageTests/Target/cabal.all-benches.out, cabal-testsuite/PackageTests/Target/cabal.all-enable-benches.out, cabal-testsuite/PackageTests/Target/cabal.all-enable-tests.out, cabal-testsuite/PackageTests/Target/cabal.all-exes.out, cabal-testsuite/PackageTests/Target/cabal.all-tests.out, cabal-testsuite/PackageTests/Target/cabal.component-target-bench.out, cabal-testsuite/PackageTests/Target/cabal.component-target-exe.out, cabal-testsuite/PackageTests/Target/cabal.component-target-lib.out, cabal-testsuite/PackageTests/Target/cabal.component-target-test.out, cabal-testsuite/PackageTests/Target/cabal.ctype-target.out, cabal-testsuite/PackageTests/Target/cabal.default-all.out, cabal-testsuite/PackageTests/Target/cabal.everything.out, cabal-testsuite/PackageTests/Target/cabal.explicit-all.out, cabal-testsuite/PackageTests/Target/cabal.missing-target.out, cabal-testsuite/PackageTests/Target/cabal.package-target.out, cabal-testsuite/PackageTests/Target/cabal.path-target.out, cabal-testsuite/PackageTests/Target/cabal.project, cabal-testsuite/PackageTests/Target/cabal.test.hs, cabal-testsuite/PackageTests/Target/dir-a/a.cabal, cabal-testsuite/PackageTests/Target/dir-b/b.cabal, cabal-testsuite/PackageTests/Target/dir-c/c.cabal, changelog.d/pr-9744.md, doc/cabal-commands.rst
Fixes #8953. Adds a `cabal target` command for showing targets that can be supplied to other commands like the `cabal build` command.
> [!NOTE]
> Comments prior to https://github.com/haskell/cabal/pull/9744#pullrequestreview-2143366261, prior to Jun 26 2024, refer to an earlier implementation that was a cut down build command. The newer implementation is based off of a suggestion by @andreabedini.
When a project has but one package the targets are easy to find by looking inside the `.cabal` file but when a project has hundreds of packages that method is hard with information under layers of folders and files.
Using grep in `.cabal` files is tough to get right when we need to exclude stuff that is not in the project.
Here's `all:exes` found with this new target command:
```
$ cabal run …
```
=> Add a cabal target command

Cabal-syntax/src/Distribution/PackageDescription/PrettyPrint.hs, Cabal-tests/tests/ParserTests/regressions/issue-6083-b.format, cabal-validate/src/Main.hs
Only munge internal dependencies when printing when there is no explicit syntax
* In `postProcessInternalDeps` the shadowing logic which existed prior to cabal format 3.4 is implemented in a post processing step.
The algorithm there replaces any references to internal sublibraries with an explicit qualifier. For example if you write..
``` 
library build-depends: foo
library foo ... 
```
this is reinterpreted as
``` 
library build-depends: mylib:foo
library foo ... 
```
* In `preProcessInternalDeps` the inverse transformation takes place, the goal is to replace `mylib:foo` with just `foo`.
* Things go wrong if you are using version 3.0 for your cabal file because
- In 3.0 the qualifier syntax is introduced so you can be expliciit about sublibrary dependencies
- The shadowing semantics of …
=> Only munge internal dependencies when printing when there is no explicit syntax

Cabal-described/src/Distribution/Utils/CharSet.hs, Cabal-tests/tests/HackageTests.hs, Cabal-tests/tests/ParserTests.hs, Cabal-tests/tests/custom-setup/CabalDoctestSetup.hs, Cabal-tests/tests/custom-setup/IdrisSetup.hs, Makefile, cabal-install-solver/src/Distribution/Solver/Modular/Solver.hs, cabal-testsuite/src/Test/Cabal/Server.hs
Addresses the parser errors of fourmolu so that #10491 can proceed without having to add `{- FOURMOLU_DISABLE -}` comments.
```
$ make style-todo
Cabal-described/src/Distribution/Utils/CharSet.hs:116:1-6
The GHC parser (in Haddock mode) failed:
[GHC-58481] parse error on input `insert'
Cabal-tests/tests/HackageTests.hs:304:5-9
The GHC parser (in Haddock mode) failed:
[GHC-58481] parse error on input `parse'
Cabal-tests/tests/ParserTests.hs:205:1
The GHC parser (in Haddock mode) failed:
[GHC-58481] parse error (possibly incorrect indentation or mismatched brackets)
Cabal-tests/tests/custom-setup/CabalDoctestSetup.hs:287:1
The GHC parser (in Haddock mode) failed:
[GHC-58481] parse error (possibly incorrect indentation or mismatched brackets) …
```
=> Add `make style-todo` and fourmolu on off comments

.github/workflows/validate.yml
Previously only the artifacts would be replaced and all the other
information would stay the same as the original nightly release.
Resolves #10537
=> ci: properly update metadata on nigthly releases

CONTRIBUTING.md
As per today dev call, comments/modifications welcome
=> Add PR size guidelines

.github/workflows/validate.yml, Cabal/src/Distribution/Simple/Utils.hs, cabal-install/src/Distribution/Client/Version.hs
=> fix static builds lacking git info

Cabal-hooks/Cabal-hooks.cabal, Cabal-syntax/Cabal-syntax.cabal, Cabal/Cabal.cabal, cabal-install-solver/cabal-install-solver.cabal, cabal-install/cabal-install.cabal
Relaxed the upper bound for the containers dependency from <0.8 to <0.9
- Cabal-hooks
- Cabal-syntax
- Cabal
- cabal-install-solver
- cabal-install
I tested this locally by running the command.
```
cabal build --constraint="containers==0.8.*" --allow-newer=resolv:containers --allow-newer=hackage-security:containers --allow-newer=hashable:containers exe:cabal
```
This uses containers version 0.8.x
while relaxing version constraints for the resolv, hackage-security, and hashable packages to allow them to work with this newer containers version.
---
=> Allow containers-0.8

Cabal/src/Distribution/PackageDescription/Check.hs
While diagnosing slow `check` times, I identified that file glob expansion was very slow, even on literal paths (#10495). This was made worse because Cabal would expand a glob four times for each `extra-source-files` line.
Fortunately, we can halve this easily: we call `checkPackageDescription` twice in `checkGenericPackageDescription`. This PR simply removes one of the calls in the function.
On our codebase, this patch has the effect of reducing the time spent expanding globs from 34s to 17s, bringing the time to do `cabal repl --repl-options "-e ()"` from 50s to 33s.
=> Delete second `checkPackageDescription` call

Cabal/src/Distribution/Simple/Bench.hs, Cabal/src/Distribution/Simple/Program/Run.hs, Cabal/src/Distribution/Simple/Test/ExeV10.hs, Cabal/src/Distribution/Simple/Test/LibV09.hs, cabal-install/src/Distribution/Client/Run.hs, cabal-testsuite/PackageTests/DuplicateEnvVars/cabal.project, cabal-testsuite/PackageTests/DuplicateEnvVars/cabal.test.hs, cabal-testsuite/PackageTests/DuplicateEnvVars/p/Main.hs, cabal-testsuite/PackageTests/DuplicateEnvVars/p/p.cabal, changelog.d/pr-10827.md
This fixes a bug where environment variables were duplicated when running executables.
```
overrideEnv <- fromMaybe [] <$> getEffectiveEnvironment ([("PATH", Just newPath)] ++ envOverrides)
let shellEnv = overrideEnv ++ existingEnv
```
Since getEffectiveEnvironment already calls getEnvironment internally, if any overrides
are passed then the result is a complete environment. Appending it to
the already existing environment results in duplicated environment variables.
The fix:
* Added getFullEnvironment function to handle the common pattern correctly
* Updated code in Bench, Test/ExeV10, Test/LibV09, and Client/Run to use this function
In the future it would be good to generalise `getFullEnvironment`
further so it can also handle the `addLibraryPath` case, which modifies
an environment …
=> Fix environment variable handling when running executables 

doc/file-format-changelog.rst
Documents changes in `cabal-version: 1.14`.
(There were no changes in `cabal-version: 1.16`.)
Not applicable, but follows the language of similar parts of the page.
=> Fix #10821 Clear 'to do' in format specification history

doc/file-format-changelog.rst
Also corrects formatting of other existing documentation under `cabal-version: 3.14`.
=> Fix #10773 Document new `build-type: Hooks` in format specification history

doc/cabal-package-description-file.rst
See:
* #10819
Also updates example in section 1.2.9.1 of the Cabal User Guide, accordingly.
Also fixes grammatical typo in section 1.2.9.1.
Not applicable, but follows form of similar language used in that part of the Guide.
=> Fix #10819 Document that executables etc can depend on library in same package

cabal-install/src/Distribution/Client/IndexUtils.hs, changelog.d/pr-10730
Fixes #9891 by creating the file if it is missing. 
Depends on #10728
This will work on Linux:
```
cabal init -m -n --simple --lib
mkdir repo
echo "packages: ." > cabal.project
echo "repository local" >> cabal.project
echo "  url: file+noindex://$(pwd)/repo" >> cabal.project
cabal build
```
For Windows, the path has to be un-cygwinize and prepended by `//./` as described in #10728.
---
=> Create `noindex.cache` if missing

Cabal/src/Distribution/Simple/Program/Builtin.hs, cabal-install/src/Distribution/Client/CmdExec.hs, cabal-install/src/Distribution/Client/ProjectPlanOutput.hs, cabal-testsuite/PackageTests/EnvironmentFile/CHANGELOG.md, cabal-testsuite/PackageTests/EnvironmentFile/EnvironmentFile.cabal, cabal-testsuite/PackageTests/EnvironmentFile/app/Main.hs, cabal-testsuite/PackageTests/EnvironmentFile/cabal.test.hs, cabal-testsuite/PackageTests/EnvironmentFile/ghc.environment, changelog.d/pr-10828.md
Issue https://github.com/haskell/cabal/issues/10759 highlighted the issue that we were not isolating the calls
to ghc from the existence of environment files.
This manifested in a terminal bug where extra arguments form the
environment file were causing a link failure which was due to a
combination of https://github.com/haskell/cabal/issues/10692.
However, even before this bug the test executable was relinked to due to
the extra flags from the environment file.
```
Building test suite 'aeson-schemas-test' for aeson-schemas-1.4.2.1...
Loaded package environment from /home/runner/work/aeson-schemas/aeson-schemas/dist-newstyle/tmp/environment.-69233/.ghc.environment.x86_64-linux-9.6.6
Loaded package environment from /home/runner/work/aeson-schemas/aeson-schemas/dist-newstyle/tmp/environment.- …
```
=> Cabal: Always pass -package-env=- to supported GHC versions 

doc/cabal-package-description-file.rst, doc/file-format-changelog.rst
See:
* #10819 
Also corrects when `default-extensions`, `other-extensions`, `default-language` and `other-languages` were, in fact, first introduced.
Also supplies missing ('TBW') documentation for `other-languages`.
The introduction of the `exitcode-stdio-1.0` value is documented because this is needed to make sense of the changes that occurred in `cabal-version: 1.14` (see:
* https://github.com/haskell/cabal/pull/10822).
Sources for changes:
* Change logs;
* Other documentation provided with released Cabal versions; and
* source code for published Cabal versions, including Haddock documentation and other code documentation.
Not applicable, but added documentation follows the style of similar existing language.
=> Re #10819 Take format specification history back to version 1.8

Cabal/Cabal.cabal, cabal-install/cabal-install.cabal
cabal-install on 3.14 depends on an unreleased Cabal fuction, so, needs a lower bound bump. The function in question is `addInternalBuildToolsFixed` (introduced in https://github.com/haskell/cabal/pull/10838).
This was found by the CI sdist-check job in https://github.com/haskell/cabal/pull/10865
---
=> Cabal API change in 3.14 requires a lower bound bump in cabal-install

.gitlab-ci.yml, .gitlab/ci.sh
Fix for #10804 designed for backport.
For the next major version of Cabal, I suggest a larger update of supported platforms. But *not* in this PR. This one is just about maintaining support of platforms that were already supported.
[![pipeline status](https://gitlab.haskell.org/haskell/cabal/badges/b/backportable-centos7/pipeline.svg)](https://gitlab.haskell.org/haskell/cabal/-/commits/b/backportable-centos7)
=> Use a newer ci-images for centos7

doc/file-format-changelog.rst
=> Document deprecation of hugs- nhc98- jhc-options fields in format history

Cabal-hooks/Cabal-hooks.cabal, cabal-install/cabal-install.cabal
=> Preflight checks

doc/cabal-package-description-file.rst
See change log entry for Cabal 1.10.0.0:
* https://downloads.haskell.org/~cabal/Cabal-1.10.2.0/changelog
=> Fix docs: extensions field was deprecated in Cabal 1.10, not 1.12

Cabal-hooks/Cabal-hooks.cabal, Cabal-syntax/Cabal-syntax.cabal, Cabal/Cabal.cabal, cabal-install-solver/cabal-install-solver.cabal, cabal-install/cabal-install.cabal
3.0 uses SPDX License List version 3.6 2019-07-10
3.4 uses SPDX License List version 3.9 2020-05-15
`cabal-version` 3.0 is out of our support window.
---
=> Bump `cabal-version`

doc/file-format-changelog.rst
The motivation is that the documentation of the history of the format specification is almost complete (it currently stops at Cabal 1.8). This will complete it.
Some background to early Cabal version numbering is available [here](https://pilgrem.com/2025/03/26/early-cabal/).
The format specification appears to have been stable between Cabal 1.2.1 and Cabal 1.6.
Not applicable, but aims to be consistent with existing text.
=> Take format specification history back to Cabal-1.0

Cabal/src/Distribution/Compat/GetShortPathName.hs, Cabal/src/Distribution/Compat/Time.hs, Cabal/src/Distribution/Simple/InstallDirs.hs, cabal-install/src/Distribution/Client/Win32SelfUpgrade.hs
These warnings stop CI process at https://gitlab.haskell.org/ghc/ghc/-/merge_requests/13856 due of `-Werror`:
```
libraries/Cabal/Cabal/src/Distribution/Compat/Time.hs:103:1: warning: [GHC-01245] [-Wunsupported-calling-conventions]
• the 'stdcall' calling convention is unsupported on this platform,
treating as ccall
• When checking declaration:
foreign import stdcall safe "windows.h GetFileAttributesExW" c_getFileAttributesEx
:: LPCTSTR -> Int32 -> LPVOID -> Prelude.IO BOOL
|
103 | foreign import CALLCONV "windows.h GetFileAttributesExW"
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```
----
=> Fix call convention warnings for AArch64

cabal-install/cabal-install.cabal, cabal-install/tests/IntegrationTests2.hs
This fixes a problem where test output was leaking into GitHub Actions results (#8419), making the output unnecessarily verbose and harder to read.
This makes the test output much cleaner while still preserving all the diagnostic information when tests fail.
Fixes #8419
---
---
Include the following …
=> testsuite: Supress stderr when running integration tests

Cabal/src/Distribution/Simple/Haddock.hs, changelog.d/issue-9694
=> Fix #9694 Don't imply that Haddock docs exist, when warning not installed

cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/cabal.test.hs
Fixes #10927, mark a test that sometimes fails with HTTP code 525, SSL handshake failure, as flaky.
=> Mark dedup complex test as flaky

cabal-install/src/Distribution/Client/JobControl.hs, changelog.d/pr-10936.md
This addresses the smaller part of #10885, which seemed to get universal support.
I'll add a changelog when I see how CI is doing.
---
=> Print out the "Created semaphore" message only in verbose mode

Cabal/src/Distribution/Simple/Setup/Benchmark.hs, Cabal/src/Distribution/Simple/Setup/Common.hs, Cabal/src/Distribution/Simple/Setup/Test.hs, doc/cabal-commands.rst, doc/setup-commands.rst
Spawned by a question [on IRC](https://ircbrowse.tomsmeding.com/day/lchaskell/2025/02/12?id=1480039#trid1480039) of what exactly `--ghc-option`, `--ghc-options` and `--repl-options` take as their input format, I reformulated and expanded on the relevant documentation. Correctness of this information was checked in two ways:
- Limited experimentation with the `cabal` CLI;
- Asking questions to @merijn on IRC (later in the same log linked above).
This list conspicuously _excludes_ "looking at the code". My apologies.
Checklist for template B (does not modify behaviour or interface):
=> Clarify splitting/passing behaviour for --*-option(s) arguments

cabal-testsuite/AssertTests/cabal.out, cabal-testsuite/AssertTests/cabal.test.hs, cabal-testsuite/AssertTests/msg.expect.txt, cabal-testsuite/PackageTests/CheckSetup/setup.test.hs, cabal-testsuite/PackageTests/ConditionalAndImport/cabal.test.hs, cabal-testsuite/PackageTests/NewBuild/T4288/cabal.test.hs, cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromComplex/cabal.test.hs, cabal-testsuite/PackageTests/ProjectImport/ParseErrorProvenance/cabal.out, cabal-testsuite/PackageTests/ProjectImport/ParseErrorProvenance/cabal.test.hs, cabal-testsuite/PackageTests/Regression/T5409/use-different-versions-of-dependency-for-library-and-build-tool.test.hs, cabal-testsuite/src/Test/Cabal/NeedleHaystack.hs, cabal-testsuite/src/Test/Cabal/Prelude.hs
A follow on from #10646 that I had to rebase this on top of changes from #10647 that added `assertOutputMatches` and `assertOutputDoesNotMatch` to `cabal-testsuite/src/Test/Cabal/Prelude.hs`. At that time I made this small change but saw that `assertOutputMatches` and `assertOutputDoesNotMatch` could be implemented with `assertOn`. That what this pull request does.
```diff
-    unless (concatOutput output =~ regex) $
+    unless (encodeLf output =~ regex) $
```
---
I've moved tests to `cabal-testsuite/AssertTests/cabal.test.hs` that are only flexing the `assert*` functions and are not truly package tests. These tests pass but you'll want to see them fail too to see that the output is as expected. To do that you'll need to make …
=> Implement assert matches with assert on

cabal-testsuite/PackageTests/ProjectImport/UntrimmedImport/cabal.test.hs
Fixes #10950, mark a test that sometimes fails with a parsing error, as flaky.
=> Mark untrimmed import test as flaky

cabal-install/src/Distribution/Client/ProjectPlanning.hs, cabal-install/src/Distribution/Client/ProjectPlanning/Types.hs, cabal-testsuite/PackageTests/PathRecomp/PathRecomp.cabal, cabal-testsuite/PackageTests/PathRecomp/Setup.hs, cabal-testsuite/PackageTests/PathRecomp/cabal.test.hs, cabal-testsuite/PackageTests/PathRecomp/src/Lib.hs, changelog.d/pr-10817
When a user's PATH environment variable changes between Cabal commands, the environment in the REPL becomes incorrect. This occurs because during initial package configuration, the current PATH is captured via `programSearchPathAsPATHVar` and then stored in the `programOverrideEnv` field of a ConfiguredProgram. These `ConfiguredProgram`s are subsequently serialized into the setup-config file, effectively baking in the PATH environment from the time of configuration.
The issue manifests when `PATH` is updated after initial configuration. Although the solver re-runs when detecting `PATH` changes, the `dryRunLocalPkg` function examines `ElaboratedConfiguredPackage` and incorrectly determines that nothing has changed that would require reconfiguration. This decision is incorrect because …
=> Fix PATH changes not triggering REPL reconfiguration (#2015)

cabal-testsuite/PackageTests/ProjectImport/DedupUsingConfigFromSimple/cabal.test.hs
see https://github.com/haskell/cabal/issues/10975
---
=> test suite: mark DedupUsingConfigFromSimple as flaky

cabal-install/cabal-install.cabal, cabal-install/src/Distribution/Client/CmdGenBounds.hs, cabal-install/src/Distribution/Client/Errors.hs, cabal-install/src/Distribution/Client/GenBounds.hs, cabal-install/src/Distribution/Client/Main.hs, cabal-testsuite/PackageTests/GenBounds/Issue6290/cabal.out, cabal-testsuite/PackageTests/GenBounds/Issue7504/cabal.project, cabal-testsuite/PackageTests/GenBounds/Issue7504/cabal.test.hs, cabal-testsuite/PackageTests/GenBounds/Issue7504/package-a/LICENSE, cabal-testsuite/PackageTests/GenBounds/Issue7504/package-a/package-a.cabal, cabal-testsuite/PackageTests/GenBounds/Issue7504/package-a/src/ModuleA.hs, cabal-testsuite/PackageTests/GenBounds/Issue7504/package-b/LICENSE, cabal-testsuite/PackageTests/GenBounds/Issue7504/package-b/exe/Main.hs, cabal-testsuite/PackageTests/GenBounds/Issue7504/package-b/package-b.cabal, cabal-testsuite/PackageTests/GenBounds/Issue7504/package-b/src/ModuleB.hs, changelog.d/pr-10840.md, doc/cabal-commands.rst
This commit implements project-aware functionality for the `cabal gen-bounds` command, allowing it to work correctly in multi-package projects. Previously, running `gen-bounds` from within a package directory that depends on another local package would fail because it couldn't find the local dependency.
The implementation follows the same pattern as other v2 commands, creating a full project context that knows about all packages defined in the cabal.project file. This allows `gen-bounds` to properly analyze dependencies between local packages and suggest appropriate bounds.
```
cabal gen-bounds <TARGET>
```
Fixes #7504
Fixes #8654
Fixes #9752
Fixes #5932
Please read [Github PR Conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#github-pull-request-conventions) and …
=> Implement v2-gen-bounds function

Cabal/src/Distribution/Simple/Compiler.hs, Cabal/src/Distribution/Simple/Errors.hs, Cabal/src/Distribution/Simple/GHC/Build/Link.hs, cabal-testsuite/PackageTests/MultiRepl/ReexportedModule/cabal.project, cabal-testsuite/PackageTests/MultiRepl/ReexportedModule/cabal.test.hs, cabal-testsuite/PackageTests/MultiRepl/ReexportedModule/package-a/CHANGELOG.md, cabal-testsuite/PackageTests/MultiRepl/ReexportedModule/package-a/package-a.cabal, cabal-testsuite/PackageTests/MultiRepl/ReexportedModule/package-a/src/PackageA.hs, cabal-testsuite/PackageTests/MultiRepl/ReexportedModule/package-b/CHANGELOG.md, cabal-testsuite/PackageTests/MultiRepl/ReexportedModule/package-b/package-b.cabal, cabal-testsuite/PackageTests/MultiRepl/ReexportedModule/package-b/src/PackageB.hs, changelog.d/pr-10880.md
In ghc-9.12 the -rexported-module flag was extended to add support for module renaming.
Therefore now if a module uses a module renaming, then the -reexported-module flag is passed the renaming.
Fixes #10181
---
---
=> multi-repl: Support module renaming for ghc-9.12 onwards

cabal-install/src/Distribution/Client/CmdBench.hs, cabal-install/src/Distribution/Client/CmdBuild.hs, cabal-install/src/Distribution/Client/CmdConfigure.hs, cabal-install/src/Distribution/Client/CmdExec.hs, cabal-install/src/Distribution/Client/CmdFreeze.hs, cabal-install/src/Distribution/Client/CmdGenBounds.hs, cabal-install/src/Distribution/Client/CmdHaddock.hs, cabal-install/src/Distribution/Client/CmdHaddockProject.hs, cabal-install/src/Distribution/Client/CmdInstall.hs, cabal-install/src/Distribution/Client/CmdListBin.hs, cabal-install/src/Distribution/Client/CmdOutdated.hs, cabal-install/src/Distribution/Client/CmdPath.hs, cabal-install/src/Distribution/Client/CmdRepl.hs, cabal-install/src/Distribution/Client/CmdRun.hs, cabal-install/src/Distribution/Client/CmdTest.hs, cabal-install/src/Distribution/Client/CmdUpdate.hs, cabal-install/src/Distribution/Client/NixStyleOptions.hs, cabal-install/src/Distribution/Client/ScriptUtils.hs, cabal-testsuite/PackageTests/HaddockProject/haddock-project.out
I was working on a fix for #10527 and noticed that all but one of the callers of `withContextAndSelectors` had already accessed verbosity in the same way that `withContextAndSelectors` does (`Cmd*.hs` modules do this):
https://github.com/haskell/cabal/blob/62073c99833111dc7369dd22524f3b2a250a5f1d/cabal-install/src/Distribution/Client/CmdRepl.hs#L509
https://github.com/haskell/cabal/blob/62073c99833111dc7369dd22524f3b2a250a5f1d/cabal-install/src/Distribution/Client/ScriptUtils.hs#L340
This is a refactor that adds a verbosity argument to `withContextAndSelectors` and a function `cfgVerbosity` that simplifies grabbing the verbosity from the configuration or using a default value.
With this a lot of `-XRecordWildCards` can be removed as can a lot of imports from `Distribution.Client.Setup`. …
=> Add cfgVerbosity

Cabal/src/Distribution/Simple/GHC.hs, Cabal/src/Distribution/Simple/Utils.hs, changelog.d/pr-10979
When using a development compiler the compilerId isn't a prefix of the Project Unit Id. This led to a failure to parse the AbiTag.
We extend the parsing logic to handle these cases by only removing the common prefix and then any leading '-'s.
Resolves #10170
To test this try using cabal-install with a development version of the compiler, and check that the AbiTag is actually parsed. (I did this with traces locally)
---
=> Fix parsing AbiTag for development compilers

bootstrap/bootstrap.py
fix #10998 
The fix was suggested by ChatGPT.
---
=> bootstrap.py: fix incomplete reads when fetching from Hackage

Cabal-QuickCheck/Cabal-QuickCheck.cabal, Cabal-hooks/Cabal-hooks.cabal, Cabal-syntax/Cabal-syntax.cabal, Cabal/Cabal.cabal, cabal-install-solver/cabal-install-solver.cabal, cabal-install/cabal-install.cabal
=> Preflight checks for 3.16

doc/cabal-package-description-file.rst
=> Docs: fix the detailed-0.9 example

Cabal-syntax/src/Distribution/SPDX/LicenseExceptionId.hs, Cabal-syntax/src/Distribution/SPDX/LicenseId.hs, Cabal-syntax/src/Distribution/SPDX/LicenseListVersion.hs, Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs, Makefile, cabal-dev-scripts/src/GenSPDX.hs, cabal-dev-scripts/src/GenSPDXExc.hs, cabal-dev-scripts/src/GenUtils.hs, changelog.d/pr-11014, license-list-data/exceptions-3.26.json, license-list-data/licenses-3.26.json, templates/SPDX.LicenseExceptionId.template.hs, templates/SPDX.LicenseId.template.hs
Per release checklist C.3.4
---
=> add SPDX license data version 3.26

cabal.bootstrap.project, cabal.release.project, cabal.validate.project
=> bump index state to get new `hackage-security`

.github/mergify.yml
Also enabling parallel checks, which should speed things up even more especially since Mergify forced us to separate the normal and squash-merge queues.
Also adjust the labels set for the bot to try to avoid making noise when it's being shoved straight in.
---
=> try out merge queues

Cabal-QuickCheck/Cabal-QuickCheck.cabal, Cabal-described/Cabal-described.cabal, Cabal-hooks/Cabal-hooks.cabal, Cabal-syntax/Cabal-syntax.cabal, Cabal-tree-diff/Cabal-tree-diff.cabal, Cabal/Cabal.cabal, Cabal/Makefile, bootstrap/linux-9.10.2.json, bootstrap/linux-9.12.2.json, bootstrap/linux-9.2.8.json, bootstrap/linux-9.4.8.json, bootstrap/linux-9.6.7.json, bootstrap/linux-9.8.4.json, cabal-install-solver/cabal-install-solver.cabal, cabal-install/cabal-install.cabal, cabal-testsuite/cabal-testsuite.cabal, doc/conf.py, solver-benchmarks/solver-benchmarks.cabal
This commit is directly to 3.16 branch.
Note that I discovered two missed version bumps on `master` which must be addressed in a separate PR.
---
=> adjust versions for 3.16.0.0 release

doc/cabal-project-description-file.rst, doc/nix-local-build.rst
Minor documentation addition to express a specific usecase for config importing, that of using stackage as your package set.
* [/] Patches conform to the [coding conventions](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#other-conventions).
* [/] Is this a PR that fixes CI? If so, it will need to be backported to older cabal release branches (ask maintainers for directions).
@Kleidukos as requested.
=> add paragraph mentioning stackage

.github/mergify.yml
It just inappropriately used a backport queue (luckily with no ill effects) for a release branch non-backport PR. Use the label we set on backports (which has a better pattern for matching them) instead of a body check.
Also undid the attempted hack to stop the Mergify upgrade bot from breaking our priorities.
---
=> adjust Mergify queue rules for release branches

Cabal/src/Distribution/Simple/Build/PathsModule.hs, Cabal/src/Distribution/Simple/Build/PathsModule/Z.hs, cabal-dev-scripts/src/GenPathsModule.hs, changelog.d/pr-10705, templates/Paths_pkg.template.hs
The official capitalisation is “AArch”,
see https://developer.arm.com/documentation/102374/latest/.
---
As noted by @ulysses4ever in #11033. Addition in #10705 by @GulinSS (who might want to tell us if he is OK with the change)
=> Capitalise “AArch” properly

Cabal/src/Distribution/Simple/Build/PathsModule.hs, Cabal/src/Distribution/Simple/Build/PathsModule/Z.hs, cabal-dev-scripts/src/GenPathsModule.hs, templates/Paths_pkg.template.hs
This is a backport, the relevant documentation (release notes) was already taken care of in #11033.
=> Backport #11047: Capitalise “AArch” properly

Cabal-hooks/Cabal-hooks.cabal, Cabal-syntax/Cabal-syntax.cabal, Cabal-tests/Cabal-tests.cabal, Cabal/Cabal.cabal, cabal-benchmarks/cabal-benchmarks.cabal, cabal-install-solver/cabal-install-solver.cabal, cabal-install/cabal-install.cabal, cabal-testsuite/cabal-testsuite.cabal, cabal-validate/cabal-validate.cabal, solver-benchmarks/solver-benchmarks.cabal
=> missed updating all the copyrights in the cabal files

CONTRIBUTING.md, README.md, proposals.md
The cabal developers are interested to adopt a proposal process, the details are found in the `proposals.md` file. I am proposing this change but the process has been shaped alongside other cabal developers, it is something I want to work on together with people through this PR.
The process is designed to make developers feel empowered to make decisions.
* It is light-weight, a PR is opened and discussed on a repo with a fixed discussion period.
* It is developer-led, final decisions are made by developers at the Cabal developers meeting.
* It is flexible, there is no formal voting procedure, decisions are made by rough consensus.
Overall, we hope that this will allow developers to move the cabal project forward.
cc @Mikolaj @ulysses4ever @geekosaur @ffaf1 as the attendees of the meeting …
=> First draft of the cabal-proposals process

cabal-install/src/Distribution/Client/Config.hs, cabal-install/tests/IntegrationTests2.hs, changelog.d/pr-11067
When calling `cabal update` with an empty state (empty CABAL_DIR or new machine), cabal writes out a default config file with many fields commented out to show their defaults. This suggests that the user can uncomment the field and override the default. This is wrong for fields that aren't allowed in the config file like `builddir`. This patch avoids generating a comment with `builddir` in the default config.
Fix #11050. 
```shellsession
❯ cabal build cabal
❯ c=$(cabal list-bin cabal)
❯ CABAL_DIR=$PWD/cabal-dir-testing $c update
❯ grep builddir ./cabal-dir-testing/config
❯ 
```
---
=> cabal update: don't show comment with builddir in the default config

doc/cabaldomain.py
=> Fix typo exsting

.github/workflows/lint.yml, .hlint.yaml
Bumps to `hlint-3.10` and updates the `.hlint.yaml` configuration.
---
=> Bump to hlint-3.10

Makefile
A follow on from #9845. Fix a typo in `.PHONY hackage-roundtrip-tests`.
---
=> Typo in Makefile .PHONY target

cabal-install/src/Distribution/Client/Config.hs, changelog.d/pr-11095.md
Hackage Security has one new key and one key needing removal. The new root.json should go live on hackage in the next week.
The new root.json is here: https://github.com/haskell-infra/hackage-root-keys/pull/23 is you want to compare the key signatures.
See https://github.com/haskell/cabal/pull/9068 for a prior MR in this series.
* [N/A] [Manual QA notes](https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#qa-notes) have been included.
* [N/A] Tests have been added. (*Ask for help if you don’t know how to write them! Ask for an exemption if tests are too complex for too little coverage!*)
=> Update Hackage root keys

.hlint.yaml, Cabal-syntax/src/Distribution/Compat/Parsing.hs, Cabal-tests/tests/UnitTests/Distribution/Version.hs, Cabal/src/Distribution/Simple/BuildPaths.hs, Cabal/src/Distribution/Simple/Configure.hs, Cabal/src/Distribution/Simple/GHCJS.hs, Cabal/src/Distribution/Simple/Haddock.hs, cabal-install/src/Distribution/Client/BuildReports/Upload.hs, cabal-install/src/Distribution/Client/CmdOutdated.hs, cabal-install/src/Distribution/Client/CmdRepl.hs, cabal-install/src/Distribution/Client/ProjectOrchestration.hs, cabal-install/src/Distribution/Client/ProjectPlanOutput.hs, cabal-install/src/Distribution/Client/ProjectPlanning.hs, cabal-install/src/Distribution/Client/Run.hs, cabal-install/src/Distribution/Client/Utils.hs, cabal-install/src/Distribution/Deprecated/ViewAsFieldDescr.hs
See #9110. Apply hlint suggestions with a single count so that these warnings are no longer ignored and will be picked up by our CI linting.
I left one or two single count warnings that didn't have a small diff or that I didn't think would be otherwise easy to review.
Each applied suggestion is an individual commit but I'll squash these if this pull request is approved.
When reviewing #8889, we noticed that plenty of hlint suggestions were being ignored in `.hlint.yaml` that would have been triggered for new modules and new code of #8889.
---
=> Apply hlint suggestions with a single count

.github/workflows/validate.yml
We had problems with their image last time. Let's see if they're fixed now.
---
=> try Ubuntu 24.04 again

.github/workflows/reusable-release.yml
=> Only enable FreeBSD private runner on demand

Cabal/src/Distribution/Simple/Program/Builtin.hs, doc/setup-commands.rst
=> docs: explicitly list programs known to Cabal (fix #7899)

.hlint.yaml, Cabal-syntax/src/Distribution/ModuleName.hs, Cabal-syntax/src/Distribution/Types/Version.hs, Cabal-syntax/src/Distribution/Types/VersionRange.hs, Cabal/src/Distribution/GetOpt.hs, Cabal/src/Distribution/Simple/Program/GHC.hs, Cabal/src/Distribution/Simple/Utils.hs, cabal-install/src/Distribution/Client/ProjectConfig/Legacy.hs, cabal-install/src/Distribution/Client/ProjectOrchestration.hs, cabal-install/src/Distribution/Client/VCS.hs
See #9110. Discharges and no longer ignores the "Use list literal" and "Use list literal pattern"  suggestions so that these will be suggested by our CI linting.
I picked these suggestions to bundle together in one pull request as they both improve readability of lists, if you agree that `[a, b]` is more readable than `a : b : []`.
I'll squash commits before applying the merge label if this pull request is approved.
=> HLint list literals

doc/file-format-changelog.rst
=> Fix docs, `PackageInfo_*` modules and `cabal-version: 3.12`

cabal-install/src/Distribution/Client/CmdPath.hs, cabal-install/src/Distribution/Client/Config.hs, cabal-install/src/Distribution/Client/Main.hs, cabal-install/src/Distribution/Client/ProjectConfig.hs, cabal-install/src/Distribution/Client/ProjectPlanning.hs
Now only warns about duplicate configs when a configuration file has not been explicitly provided by the user.
Fixes #11023.
One wart is that in the implementation of `cabal path` I could not figure out how to get my hands on a `Verbosity`, so I just went with `normal`.
https://github.com/haskell/cabal/pull/11181#issuecomment-3214775232
---
=> Remove undesirable warnings about duplicate configs.

cabal-testsuite/src/Test/Cabal/NeedleHaystack.hs
Fixes a typo I introduced in #10646.
---
=> Fix haddock typo: coversion

.hlint.yaml, Cabal-syntax/src/Distribution/Compat/Graph.hs, Cabal/src/Distribution/Simple/BuildTarget.hs, Cabal/src/Distribution/Utils/MapAccum.hs, cabal-install/src/Distribution/Client/IndexUtils/ActiveRepos.hs, cabal-install/src/Distribution/Client/ProjectConfig.hs, cabal-install/src/Distribution/Client/ProjectOrchestration.hs, cabal-install/src/Distribution/Client/TargetSelector.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/Builder.hs
See #9110. Discharges and no longer ignores the "Use first" and "Use second" suggestions so that these will be suggested by our CI linting.
These suggestions seem reasonable and don't reduce readability. Checking each replacement, it seems easy to find out from the surrounding code what the first or second element of each pair is.
I'll squash commits before applying the merge label if this pull request is approved (or use `squash+merge me`).
---
=> HLint: use first and use second

Cabal-syntax/src/Distribution/Compiler.hs, Cabal-tests/tests/UnitTests/Distribution/Simple/Program/GHC.hs, Cabal-tests/tests/UnitTests/Distribution/Utils/Structured.hs, Cabal/src/Distribution/Simple/Compiler.hs, Cabal/src/Distribution/Simple/GHC.hs, Cabal/src/Distribution/Simple/GHCJS.hs, Cabal/src/Distribution/Simple/UHC.hs, cabal-install-solver/src/Distribution/Solver/Modular/Message.hs, cabal-install-solver/src/Distribution/Solver/Modular/Package.hs, cabal-install-solver/src/Distribution/Solver/Modular/Preference.hs, cabal-install-solver/src/Distribution/Solver/Modular/Tree.hs, cabal-install-solver/src/Distribution/Solver/Types/PackageConstraint.hs, cabal-install/src/Distribution/Client/Dependency.hs, cabal-install/tests/UnitTests/Distribution/Client/Store.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/DSL/TestCaseUtils.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/QuickCheck.hs, cabal-install/tests/UnitTests/Distribution/Solver/Modular/Solver.hs, cabal-testsuite/Setup.hs, changelog.d/pr-10982
This change allows reinstalling packages like `base` and
`template-haskell` with GHC >=9.14, and it doesn't modify the behaviour
of cabal-install with older versions of GHC for backwards-compatibility.
cabal-install includes a hardcoded list of non-reinstallable packages.
cabal-install will refuse to use a different version of these packages
in a build plan unless the --allow-boot-library-installs flag is set.
This list of packages is too pessimistic, and needlessly coupled to GHC.
For instance, as of GHC-9.12, `base` and `template-haskell` can be
"re-installed" without issue.
This patch allows compilers to specify exactly which packages are wired-in
and so should not be reinstalled.
In the case of GHC-9.14+, this amounts to ghc-internal and ghc itself.
If a compiler chooses to specify …
=> Support reinstalling more packages (including base and template-haskell) with GHC >=9.14

Cabal-syntax/src/Distribution/Types/BuildInfo/Lens.hs, changelog.d/pr-10609
```
cxxSources f s = fmap (\x -> s{T.cSources = x}) (f (T.cxxSources s))
```
should be
```
cxxSources f s = fmap (\x -> s{T.cxxSources = x}) (f (T.cxxSources s))
```
=> Fix mistake in BuildInfo.Lens.hs

MAINTAINERS.md, README.md
@Mikolaj @ffaf1 @geekosaur please, let me know what you think. My idea was to avoid formal criteria like "participated in K out of last N meetings" (there was a valid concern about the exclusionary nature of synchronous events) and instead to focus on release procedures (but meetings count too :-)). 
@mpickering do you want to be on this list? I think you absolutely qualify. Just wanted to ask you first.
---
=> Add list of maintainers

.github/mergify.yml
=> mergify's "waiting too long" check waits too long

.gitlab-ci.yml
* Background: Release CI has been implemented on GitHub, but my working assumption is that the previous GitLab CI will still be used for minor releases of 3.16 to ensure no breaking changes regarding platform availability.
* Situation: GitLab CI (may it soon RIP) is failing and will take a hot minute to fix again
* An eager reaping process removed all the Docker images used by CI (I think? Ben Gamari may know).
* The images can't be regenerated from the [same commit](https://gitlab.haskell.org/ghc/ci-images/-/pipelines/110688), because apt-get update fails during the run.
* The easiest workaround—using the [latest commit](https://gitlab.haskell.org/ghc/ci-images/-/pipelines/114988)—would force a change in platforms, albeit not much of one.
* Possible solutions
* Option 1: Declare GitLab …
=> gitlab ci: Use today's ci-images build; move to alpine3_22

.github/workflows/validate.yml
So people don't have to open all of the collapsed test output to find any failures.
---
=> indicate which of the joined tests failed
